### ISSUE TITLE
Application Insights Error - java.io.FileNotFoundException renaming temp file

### ISSUE THREAD

**Issue by geoarchitect** [microsoft/ApplicationInsights-Java#1009]
We have been seeing a lot of these errors from application insights using the Spring Boot Starter and Logback. The issue is present from v1.1.1 through 2.5.0-Beta.2.

AI: ERROR 06-08-2019 23:27:46.162+0000, 17(ActiveTransmissionLoader-worker-0): Rename To Temporary Name failed, exception: java.io.FileNotFoundException: Source '/tmp/root/transmissions/Transmission5847754688257616391.trn' does not exist

When we execute a shell on the pod, we can see this directory and some files existing.

Also when this starts happening there seems to be a major spike in CPU usage. 

Other Notes:

- Azure AKS cluster using Kubernetes 1.13.7
- OpenJDK 8u212 Stretch used as the base Docker image
- Container is limited to 1vcpu in the cluster (1vcpu requested with 1vcpu limit)

**Comment by geoarchitect** [comment]
Let me know if you want us to test or try anything.

**Comment by littleaj** [comment]
@geoarchitect, This error can be safely ignored.

This can happen when sending telemetry to Azure has failed and the items have been written to disk for sending in the future. If a thread has already read one of these files this error can occur, but does not indicate an issue in data flow.

The CPU spike is likely the result of the thread(s) reading the files and resending the telemetry.

We discussed a change to this workflow which would smooth out the CPU spike and eliminate this error.

**Comment by trask** [comment]
note to future self: i got lots of these warning messages after my laptop woke up from overnight sleep while running multiple apps being monitored by Application Insights (so they were all sharing the same temp directory)

**Comment by trask** [comment]
We believe this is fixed in next release (3.2.0-BETA.2). If you run into this issue in 3.2.0-BETA.2 or later, please open a new issue to let us know, thx!

**Comment by trask** [comment]
this should be resolved now in [3.2.0-BETA.2](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.2.0-BETA.2)
