### ISSUE TITLE
Log warning if trace message exceeds Sanitizer.MAX_MESSAGE_LENGTH

### ISSUE THREAD

**Issue by Dpetters** [microsoft/ApplicationInsights-Java#1021]
**Is your feature request related to a problem? Please describe.**
I spent too much time debugging why we had an odd drop in a metric in a PowerBI dashboard that we power with our AI telemetry. The root cause ended up being some trace messages getting silently truncated.

**Describe the solution you would like**
Enabling SDKLogger should cause some warnings to be printed out in the cases where the messages exceed Sanitizer.MAX_MESSAGE_LENGTH.

**Describe alternatives you have considered**
n/a

**Additional context**
n/a

**Comment by trask** [comment]
this is addressed now in [3.2.0-BETA.2](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.2.0-BETA.2)
