### ISSUE TITLE
Upgrade issue

### ISSUE THREAD

**Issue by pamarthid18** [microsoft/ApplicationInsights-Java#1022]
### Expected behavior
After updating the applications insight sdk in java application, no need to show again upgrade information.

### Actual behavior
After updating the applications insight SDK in java application, still in the portal, it is showing need to upgrade 2.4.0 or lataer

### System information
Please provide the following information:
 - SDK Version: 2.4.1 (Java)
 - OS type and version: Windows 10
 - Application Server type and version (if applicable):
 - Using spring-boot? yes
 - Additional relevant libraries (with version, if applicable):

### Screenshots
![image](https://user-images.githubusercontent.com/53813400/63331984-658e3b00-c354-11e9-97da-624def3d9456.png)

**Comment by trask** [comment]
The portal U/X has been fixed
