### ISSUE TITLE
Support request tracking of the new Java 11 Http Client

### ISSUE THREAD

**Issue by colonMan** [microsoft/ApplicationInsights-Java#1023]
Currently requests made with the new Java 11 Http Client don't get tracked by the Application Insights Agent. With the new Java 11 support the new http client should also be supported (https://openjdk.java.net/groups/net/httpclient/intro.html).

**Comment by littleaj** [comment]
Thanks for mentioning this. We will be adding this support in a future version.

**Comment by trask** [comment]
hi @colonMan!

It's been a while, not sure if you're still here 😄, but wanted to let you know that we pulled in the Java 11 Http Client instrumentation from upstream (in #1650).

It's opt-in preview instrumentation for now, so you'll need to enable it, either in your applicationinsights.json file:

```
{
  "preview": {
    "instrumentation": {
      "javaHttpClient": {
        "enabled": true
      }
    }
  }
}
```

or using environment variable: `APPLICATIONINSIGHTS_PREVIEW_INSTRUMENTATION_JAVA_HTTP_CLIENT_ENABLED=true`

This opt-in preview is available in the latest SNAPSHOT build: https://github.com/microsoft/ApplicationInsights-Java/files/6388703/applicationinsights-agent-3.0.4-BETA-SNAPSHOT.jar.zip

**Comment by trask** [comment]
This is released now in https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.4-BETA.2
