### ISSUE TITLE
NPE in TraceContextCorrelation when running in Kubernetes

### ISSUE THREAD

**Issue by dahlsdata** [microsoft/ApplicationInsights-Java#1029]
Using Spring Boot 2 actuators i have created a Health Endpoint that does an apache httpClient connection to localhost to check if a specific page is loading ok.

We have instrumented the app with application insights java agent.
It works fine running applicationinsights-agent-2.4.1.jar
When running applicationinsights-agent-2.5.0-BETA.jar, it will sometimes crash with a NPE when running in AKS. (Azure Kubernetes Services). 
Urls containing "localhost" are also ignored using TelemetryProcessor filter, but seems to still be instrumented.

### Expected behavior
No NPEs. 

### Actual behavior
NPEs happening.

### To Reproduce
Create Spring Boot Application using SpringBoot 2.1.0, with actuator.
Create hello world page using Spring MVC or similar
Create scheduler to use apache httpclient to query localhost page above at certain intervals
Instrument with applicationinsights-agent-2.5.0-BETA.jar
Deploy to AKS.

### System information
problem in applicationinsights-agent-2.5.0-BETA.jar
works fine in applicationinsights-agent-2.4.1.jar
- Azure Kubernetes Services 1.13
- Spring Boot 2.1.0
- Apache HttpClient 4.5.6

### logs
[Stacktrace.txt](https://github.com/microsoft/ApplicationInsights-Java/files/3533257/Stacktrace.txt)

**Comment by trask** [comment]
Hi @dahlsdata, this looks like same problem as #910, which was fixed in 2.4.1, and was merged into 2.5.0-BETA.3 (that was released just yesterday!).

**Comment by dahlsdata** [comment]
Yes seems the NPE is fixed on 2.5.0-BETA.3 version
