### ISSUE TITLE
Log Markers to be shown in Application Insight

### ISSUE THREAD

**Issue by shantanookirtane** [microsoft/ApplicationInsights-Java#1035]
Capture [Log4j Markers](https://logging.apache.org/log4j/2.x/manual/markers.html) and [Logback Markers](https://www.slf4j.org/apidocs/org/slf4j/Marker.html) as custom properties on the corresponding trace (log message) telemetry.

**Comment by MS-jgol** [comment]
@LarsWH We do not currently support log4j and logback marker yet.
Could you expand on the June 10th milestone?

**Comment by LarsWH** [comment]
@MS-jgol The post by @shantanookirtane holds sentenses like "...Capture Log4j Markers and Logback Markers as custom propertie..." and "...added this to the future milestone on Jun 10...". 

So, are you saying that there are no such plans? That would be sad as 'Markers' are very useful.

**Comment by LarsWH** [comment]
I just realized that 'Jun 10' is the day of the comment - not the 'future' milestone. It would still be good to know when that might become available.

**Comment by jain-chinmay** [comment]
Hi @trask,

Are we still looking into the above feature request? It could be a great addition in managing the logs via Azure Application Insights.

Let me know what you think?

**Comment by jeanbisutti** [comment]
Hi @jain-chinmay,
We are working on it. The feature should be available in the next release.

**Comment by jain-chinmay** [comment]
Hi @jeanbisutti,

That is great news. Thank you so much for your prompt response.

**Comment by trask** [comment]
this is released in 3.4.2: https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#log-markers-for-logback-and-log4j-2-preview
