### ISSUE TITLE
Possible to leak threads 

### ISSUE THREAD

**Issue by lawrencegripper** [microsoft/ApplicationInsights-Java#1043]
### Expected behavior

TelemetryClient not leak threads. 

### Actual behavior

In a high throughput application we had instances which called the code below, as different requests used different initializes to augment telemetry. 

```
       TelemetryConfiguration telemetryConfig = new TelemetryConfiguration();
        TelemetryConfigurationFactory.INSTANCE.initialize(telemetryConfig);
        telemetryConfig.getTelemetryInitializers().add(new FunctionsTelemetryInitializer());
        telemetryConfig.getContextInitializers().add(new FunctionsContextInitializer());
        return new TelemetryClient(telemetryConfig);
```

We saw the application slowly accumulate threads and eventually fail as when idle from our workload it had 32k threads pinning CPU at 80%+ on a large box. 

![image](https://user-images.githubusercontent.com/1939288/63939208-9bbb7100-ca5e-11e9-8487-fe1b763b0cfa.png)

If we didn't create the client like this we would see `ConcurrentModification` exceptions thrown as multiple threads interacted with the same `TelemetryConfiguration` 

```
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at com.microsoft.applicationinsights.TelemetryClient.activateInitializers(TelemetryClient.java:460)
	at com.microsoft.applicationinsights.TelemetryClient.track(TelemetryClient.java:428)
	at com.microsoft.applicationinsights.TelemetryClient.trackDependency(TelemetryClient.java:357)
	at nhs.prescriptions.helpers.TelemetryHelper.executeAndMonitorDependencyCall(TelemetryHelper.java:73)
	at customer.thing.RecogniseTextSend.postBatchReadRequest(RecogniseTextSend.java:203)
	at customer.thing.RecogniseTextSend.submitOrCheckOcrRequest(RecogniseTextSend.java:136)
	at customer.thing.RecogniseTextSend.run(RecogniseTextSend.java:96)
```

## Proposed fix

I have two expectations that aren't met at the moment:

1. If the resource I'm creating needs closing due to long running thread pools or other resources it should implement `IClosable`.  
2. If I'm expected to use a single instance of it it should be threadsafe. Currently the SDK doesn't do either of these. 

### System information

Java Function Azure Webapps

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

**Comment by littleaj** [comment]
@lawrencegripper, based on your description, it seems like several function requests are being served within the same application and since each `TelemetryClient` spawns threads each time its constructed, this would explain the increase.

I suggest you promote the `TelemetryClient` to a static variable and do the initialization in the static constructor of your function. Let me know if you see a difference in thread count under load over time.
