### ISSUE TITLE
Unable to deactivate Application Insights in application.properties

### ISSUE THREAD

**Issue by TimtationOne** [microsoft/ApplicationInsights-Java#1048]
I'm using Application Insights with Spring and try to deactivate it by default, to be able to activate it only on the environments where I need it.

So I followed the guide which is saying:
> Completely disable Application Insights using application.properties
azure.application-insights.enabled=false
azure.application-insights.web.enabled=false
Note: Do not configure azure.application-insights.instrumentation-key property for optimal performance and avoiding any Application Insights beans creation by Spring.

But if don't set the azure.application-insights.instrumentation-key config I get the following Error:
```
***************************
APPLICATION FAILED TO START
***************************
Description:

instrumentationKey must be set to report metrics to Application Insights.

Action:

Update your application to provide the missing configuration.
```

So what is meant by "do not configure azure.application-insights.instrumentation-key property for optimal performance"? Setting it to zero?

Thanks for your help.

**Comment by fox918** [comment]
I can confirm this behaviour using the latest version 2.5.1 of applicationinsights-spring-boot-starter

**Comment by trask** [comment]
Please try 3.0 (https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent), it is tolerant to missing instrumentation key
