### ISSUE TITLE
Capture dependencies during non-servlet requests (e.g. during scheduled jobs, queue processing, service buses, etc)

### ISSUE THREAD

**Issue by trask** [microsoft/ApplicationInsights-Java#1051]
These dependencies are not captured in 2.3.1 and prior. But they are captured in 2.4.0 and 2.4.1. But now, again, they are not captured in 2.5.0.

**Comment by hirowla** [comment]
From my observations, less information was captured in 2.4.1 than 2.3.1 or 2.5.0. Having said that, I'm not capturing any dependencies automatically for non-servlet requests. This is definitely a feature I would like to have.

**Comment by mercer** [comment]
I also want to learn how to instrument calls to service bus, correlate them, and see the calls in application map.

I see this documented for .net client. What about java client?

https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-end-to-end-tracing

**Comment by mercer** [comment]
I also see https://github.com/microsoft/ApplicationInsights-Java/wiki/Tracking-Azure-ServiceBus-message-processing-with-Apache-Qpid

Is this the way?

**Comment by trask** [comment]
This is resolved in [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent)

**Comment by cchetangeek** [comment]
I don't see Service Bus message processing track with 3.0.0-PREVIEW.4
However, I do see http dependencies and sql dependencies tracked (similar to 2.6.0).
I would want to track dependencies with ServiceBuss send/receive too.
Application is using spring boot 2.x and azure-servicebus 3.2.0 and 
ApplicationInsights.json contains connectionString and roleName.
Is there any configuration to enable ServiceBus tracking?

**Comment by trask** [comment]
Hi @cchetangeek, if you are using JMS to access Service Bus then it is supported in 3.0-PREVIEW, but if you are using Azure SDK it is not supported yet.

**Comment by u757865** [comment]
@trask Is there any plans to support the Service Bus ( without JMS ) in the coming releases?

**Comment by trask** [comment]
hi @u757865! there is some work going on for this, but no release date, if you open a new issue for this, we can update over there with availability
