### ISSUE TITLE
Using Struts RequestNameInterceptor doesn't Load ApplicationInsights.xml

### ISSUE THREAD

**Issue by jakehell** [microsoft/ApplicationInsights-Java#1055]
### Expected behavior
After following https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-get-started#if-youre-using-struts-2 and creating an ApplicationInsights.xml file, I would expect the ```RequestNameInterceptor``` to have the ```ApplicationInsights.xml``` file loaded.

### Actual behavior
In the ```setRequestNameSafe()``` method in ```RequestNameInterceptor```:
 ```RequestTelemetryContext context = ThreadContext.getRequestTelemetryContext()```
 context is null when trying to use a struts action. 

### To Reproduce
1. Create a struts application and follow https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-get-started#if-youre-using-struts-2.
2. Set a breakpoint in the ```setRequestNameSafe()``` method in ```RequestNameInterceptor.java```
3. Notice that ```ThreadContext.getRequestTelemetryContext()``` returns null.

### System information
Please provide the following information:
 - SDK Version: applicationinsights-web [2.0,)
 - OS type and version: windows 10
 - Application Server type and version (if applicable): tomcat 6
 - Using spring-boot? no
 - Additional relevant libraries (with version, if applicable): struts 2.3.34

### Logs
No "Configuration file has been successfully found" message.

### Screenshots
In below image, ```context``` is null:
![image](https://user-images.githubusercontent.com/5951826/64349399-82657800-cfbc-11e9-8836-50ad6a977f53.png)
If I subclass ```RequestNameInterceptor``` and attempt to load the file via ```ConfigurationFileLocator```, calling ```getConfigurationFile()``` will return a valid ```InputStream```:
![image](https://user-images.githubusercontent.com/5951826/64349578-d708f300-cfbc-11e9-9de2-cb89e7507323.png)

**Comment by trask** [comment]
Hi @jakehell, have you registered the ApplicationInsights web filter in your `web.xml`?

**Comment by jakehell** [comment]
@trask I followed https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-get-started#applications-using-webxml and the configuration is still not being loaded.

**Comment by trask** [comment]
Hi @jakehell,

Is the `WebRequestTrackingFilter` listed before all other filters in your `web.xml`?

Is Application Insights capturing any request data?

What version of Application Insights are you using?

Thanks,
Trask

**Comment by jakehell** [comment]
It must be something specific with my application as I am not able to reproduce with https://github.com/jakehell/struts2-starter-sample.

Will create a future issue if I believe there is something wrong with the api.

Thanks for the help @trask
