### ISSUE TITLE
Provide a common jar of applicationinsights-core 

### ISSUE THREAD

**Issue by andxu** [microsoft/ApplicationInsights-Java#1060]
I am using very basic(we don't need to inject http requests) AI features in [azure maven plugins](https://github.com/microsoft/azure-maven-plugins) the packing way AI used produces a very large  jar by [shadowjar](https://github.com/microsoft/ApplicationInsights-Java/blob/master/core/build.gradle#L135) which will causes many duplicated classes loaded like `org.apache.commons.lang3` which will consuming extra large memories and cpu cycles verifying these classes. Can you public a core jar without any dependencies in maven central for users with similar behaviors like us? Thanks.

**Comment by littleaj** [comment]
This is something we'd like to do in the future

**Comment by trask** [comment]
Closing, if you are unable to use the auto-instrumentation solution (this repo), you can now use the auto-instrumentation solution's underlying OpenTelemetry exporters directly: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/monitor/azure-monitor-opentelemetry-exporter/README.md
