### ISSUE TITLE
Specify module information

### ISSUE THREAD

**Issue by tobiasdiez** [microsoft/ApplicationInsights-Java#1061]
For usage with Java 9+, it would be nice if you could modularize AI by adding a `module-info` file.

**Comment by Torrenal** [comment]
I'm willing to discuss and/or assist with this.
I have insights and cxf both working locally in Java 11 using modules, but I would rather work _with_ other people for a formal submission rather than dumping a large "fix" for people to consider.   What I have locally here works for me... but certainly breaks some things, making it a less than ideal as a universal solution).

**Comment by Torrenal** [comment]
Perhaps things might be best served if I draw up a detailed "how to" document for creating a demonstrational jlink image of an application that includes a fair number of non-modular jars (insights included? No reason not to) and link that back here.  Anybody know a good open-source thing I can use for this? (brownie points if it uses CXF - that gets into a couple ticklish areas that can trip people up).

Java modules have a steep learning curve, especially if you look for prepared solutions.  Personally, I find the worst is a lack of demonstrational examples, or even just a document that enumerates all the module-info keywords...

**Comment by Torrenal** [comment]
Document location: http://modules.torrenal.com/
It's a work-in-progress, not specific to insights, and is presently mostly incomplete, possibly not entirely coherent (draft version done late at night, and my first language is bash, not English) but I think I have enough there now to give more enterprising developers a useful starting point...
Basically I've taken a cxf example project, tacked on insights, and I'm working towards the final goal of getting it's client to work under jlink, which requires all-the-bits be modularized.   The outline at the top touches on subjects I plan to cover at some point and fill out, and in brief summary:
Skillsets may require: Service Providers, Resource Providers, Reflection.
Tools can/should include: jar, jdeps, moditect, and access to a debugger

I realize my work on that is tangental to this here (again: I'll gladly cooperate/coordinate with people here to get this issue moving toward a resolution) but I'm honestly fuzzy on where I should drop a "how to do this complicated task" document.  XD

**Comment by trask** [comment]
Closing, there are new 3.4.0 versions `applicationinsights-core` and `applicationinsights-web` artifacts that are modularized, and specifically target Application Insights Java 3.x. Please see [upgrading from 2.x](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-upgrade-from-2x).
