### ISSUE TITLE
Adaptive sampling for springboot app

### ISSUE THREAD

**Issue by kuldeepagrawal** [microsoft/ApplicationInsights-Java#1063]
Can we add adaptive sampling for springboot application. I see that we have class added https://github.com/microsoft/ApplicationInsights-Java/tree/master/core/src/main/java/com/microsoft/applicationinsights/internal/channel/sampling and there is a way to achieve in using applicationinsight.xml https://github.com/microsoft/ApplicationInsights-Java/wiki/Sampling#adaptive-sampler but can we add it for application.properties https://github.com/microsoft/ApplicationInsights-Java/blob/master/azure-application-insights-spring-boot-starter/README.md#configure-more-parameters-using-applicationproperties. Adding @trask

**Comment by dylan-asos** [comment]
+1 - is this being worked on? Otherwise may have a look at effort involved

**Comment by dylan-asos** [comment]
@littleaj @trask I had a look, this seems pretty easy to bring inline with the XML based approach. 

* Add new class Adaptive to ApplicationInsightsProperties->Sampling to hold adaptive sampling config. All existing settings of Sampling remain as-is.

* Remove _TelemetryProcessor fixedRateSamplingTelemetryProcessor from_ ApplicationInsightsModuleConfiguration. 

* Add new class _TelemetrySamplerInitializer_ that follows same approach as XML based initialisation, except _getSampler_  method takes a parameter of type ApplicationInsightsProperties.TelemetryProcessor.Sampling.

* In ApplicationInsightsTelemetryAutoConfiguration, amend telemetryChannel to use the new TelemetrySamplerInitializer to configure the sampler on the channel, e.g.

```
ApplicationInsightsProperties.TelemetryProcessor.Sampling samplingSettings
        = applicationInsightsProperties.getTelemetryProcessor().getSampling();

if (samplingSettings.isEnabled()) {
    TelemetrySampler telemetrySampler = new TelemetrySamplerInitializer().getSampler(samplingSettings);
    channel.setSampler(telemetrySampler);
}

configuration.setChannel(channel);
```

I _think_ that's back-compat and would then support both Fixed and Adaptive sampling. (Would removal of the TelemetryProcessor bean be an issue?)

Happy to raise a PR with the changes if the approach sounds OK to you,

**Comment by trask** [comment]
Closing, sampling configuration for 3.0 is documented [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#sampling) and [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-sampling-overrides).
