### ISSUE TITLE
Glowroot => ApacheHttpClient4xInstrumentation#onReturn() is broken for few api methods.

### ISSUE THREAD

**Issue by smathangi** [microsoft/ApplicationInsights-Java#1067]
### Expected behavior
Instrumentation should work for all execute() methods of HttpClient interface.  

### Actual behavior
It seems there is a bug in the glowroot's ApacheHttpClient4xInstrumentation [https://github.com/glowroot/instrumentation/issues/1](url)
Because of this our application which is using ApacheHttpClient4 throwing errors when integrated with applicationinsights-agent-2.5.0.jar. 

Is there a way to disable ApacheHttpClient instrumentation ? 

### System information
Please provide the following information: 
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable):
   Apache HttpClient : 4.5.8
  applicationinsights-agent : 2.5.0

**Comment by trask** [comment]
Thanks for reporting this!

I'll look into it now.

In the meantime, to disable the instrumentation, try

```
<ApplicationInsightsAgent>
  <Instrumentation>
    <BuiltIn enabled="true">
      <HTTP enabled="false" />
    </BuiltIn>
  </Instrumentation>
</ApplicationInsightsAgent>
```

**Comment by timja** [comment]
@trask would it be possible for a release of this?
Today owasp dependency failures came out hitting dependencies of application insights (older versions i.e. 2.3.0), we've had some teams try upgrade to latest and they've hit this bug

**Comment by trask** [comment]
Hi @timja, thanks for the nudge, we will release 2.5.1-BETA today.

**Comment by trask** [comment]
2.5.1-BETA is released now

**Comment by timja** [comment]
Any chance of a GA release @trask soon?
We're running the beta on quite a few applications but we get questions often on why we're using a beta...

**Comment by trask** [comment]
Hi @timja, just released now, thanks again for reporting this!
