### ISSUE TITLE
Use WEBSITE_SITE_NAME and WEBSITE_INSTANCE_ID environment variables if available

### ISSUE THREAD

**Issue by trask** [microsoft/ApplicationInsights-Java#1082]
`WEBSITE_SITE_NAME` ==> default role name if available
`WEBSITE_INSTANCE_ID` ==> default role instance if available

**Comment by cijothomas** [comment]
current impl:
https://github.com/microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/WindowsServer/WindowsServer.Shared/AzureWebAppRoleEnvironmentTelemetryInitializer.cs

The current implementation has an issue that it wont detect slot swap instantly (a major customer confusion). The proposal is to read this from incoming http header which is always accurate:
https://github.com/microsoft/ApplicationInsights-dotnet-server/issues/1207

**Comment by trask** [comment]
Resolved in [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent)
