### ISSUE TITLE
Outdated "app insights web" module for java 

### ISSUE THREAD

**Issue by cforce** [microsoft/ApplicationInsights-Java#1094]
I am wonderig that i get messages in azure porrtal app insights worrkpace live metrics view i need to updatet to newer version than 2.5.0
![image](https://user-images.githubusercontent.com/393286/66747116-06483500-ee84-11e9-9645-7a33e4bc2fc1.png)

But there is no newer stable version for java here and the link from portal points me to a nuget package.
https://www.nuget.org/packages/Microsoft.ApplicationInsights.Web/2.11.1

So how can i get the  2.11.1 for java ?

**Comment by nuk23** [comment]
@cforce .Did you find a solution to this one ? I am facing the same issue.

**Comment by littleaj** [comment]
@nuk23 What region is your application insights resource located? Could you share a screenshot of the message?
