### ISSUE TITLE
Dependency tracking does not work from app running in docker (linux) container

### ISSUE THREAD

**Issue by vdcloud** [microsoft/ApplicationInsights-Java#1095]
I have a Java application that is sending request telemetry and dependencies correctly when i run the application from my windows 10 machine. When i run the same application from a docker container (linux), only the request telemetry and perf counters seem to be getting collected and pushed, not the dependencies to SQL Server.

![image](https://user-images.githubusercontent.com/19971842/66778911-01db4680-ee9b-11e9-9c1a-cc24cd20c1a6.png)

**Comment by trask** [comment]
This setup should be much clearer now in [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent)
