### ISSUE TITLE
Configurable masking for SQL statements with sensitive data

### ISSUE THREAD

**Issue by petergphillips** [microsoft/ApplicationInsights-Java#1098]
We have enabled the new java agent with JDBC SQL tracking and are very pleased with the information it provides.

However we due to having to work with a legacy application we have to alter user passwords with an oracle SQL statement - namely `ALTER USER user_name IDENTIFIED BY new_password;`

This oracle statement can't be written as a prepared statement so therefore can't be parameterised and unfortunately therefore outputs the new user's password in the clear to the logs.

Is there any way that we can manipulate the SQL tracking to obfuscate the password, or at least filter out those SQL statements?  I've tried implementing a `TelemetryProcessor` which looks like it can filter out request telemetry, but can't see any way of intercepting the traffic from the java agent in that way.

As a workaround we've disabled JDBC telemetry in the AI-Agent.xml, but would like to turn it back on without exposing users passwords.

**Comment by trask** [comment]
Just adding a note here that we are currently working on a solution for this

cc: @kryalama

**Comment by trask** [comment]
Closing, SQL statement parameters should be masked now in 3.0.

`ALTER USER user_name IDENTIFIED BY new_password;` should be captured as `ALTER USER user_name IDENTIFIED BY ?;`

**Comment by petergphillips** [comment]
Thanks very much, we can confirm this is indeed the case with the v3 agent :+1:
