### ISSUE TITLE
Unable to implement logging with Application Insights on spring-boot app

### ISSUE THREAD

**Issue by jyotsnaravikumar** [microsoft/ApplicationInsights-Java#1114]
### Expected behavior
Describe what you expected to happen.
Spring-Boot Application to log into application insights as per docs:
https://docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-java-applicationinsights?view=azure-java-stable#configure-springboot-application-to-send-log4j-logs-to-application-insights

### Actual behavior
Describe what actually happened that was unexpected.
Error Thrown:
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'actorsController': Unsatisfied dependency expressed through field 'telemetryClient'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.microsoft.applicationinsights.TelemetryClient' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

### To Reproduce

Followed the steps as in :

https://docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-java-applicationinsights?view=azure-java-stable#configure-springboot-application-to-send-log4j-logs-to-application-insights

pom.xml
<dependency>
  <groupId>com.microsoft.azure</groupId>
  <artifactId>applicationinsights-spring-boot-starter</artifactId>
  <version>1.0.0-BETA</version>
</dependency>

<dependency>
  <groupId>com.microsoft.azure</groupId>
  <artifactId>applicationinsights-logging-logback</artifactId>
  <version>2.1.1</version>
</dependency>

<dependency>
  <groupId>com.microsoft.azure</groupId>
  <artifactId>applicationinsights-logging-log4j2</artifactId>
  <version>2.1.1</version>
</dependency>

application.properties
azure.application-insights.instrumentation-key=instrumentation-key
# Specify the name of your springboot application. This can be any logical name you would like to give to your app.
spring.application.name=Application

log4j2.xml
?xml version="1.0" encoding="UTF-8" ?>
<Configuration packages="com.microsoft.applicationinsights.log4j.v2">
    <Properties>
        <Property name="LOG_PATTERN">
            %d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${hostName} --- [%15.15t] %-40.40c{1.} : %m%n%ex
        </Property>
    </Properties>
    <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
        </Console>
        <ApplicationInsightsAppender name="aiAppender">
        </ApplicationInsightsAppender>
    </Appenders>
    <Loggers>
        <Root level="trace">
            <AppenderRef ref="Console"  />
            <AppenderRef ref="aiAppender"  />
        </Root>
    </Loggers>
</Configuration>

Controller.java code:

@Autowired
TelemetryClient telemetryClient;

@RequestMapping(value = "", method = RequestMethod.GET)
@ApiOperation(value = "Get all actors", notes = "Retrieve and return all actors")
@ApiResponses(value = { @ApiResponse(code = 200, message = "List of actor objects") })
public ResponseEntity<List<Actor>> getAllActors(
        @ApiParam(value = "The actor name to filter by", required = false) @RequestParam("q") final Optional<String> query) {
    telemetryClient.trackEvent("Sending a custom event...");
    //trace a custom trace
    telemetryClient.trackTrace("Sending a custom trace....");

    //track a custom metric
    telemetryClient.trackMetric("custom metric", 1.0);
    telemetryClient.trackDependency("SQL", "Insert", new com.microsoft.applicationinsights.telemetry.Duration(0, 0, 1, 1, 1), true);

     final Sort sort = new Sort(Sort.Direction.ASC, "actorId")List<Actor> actors = service.getAllActors(query,sort);    return new ResponseEntity<>(actors, HttpStatus.OK);
}

RUNNING THE CODE errors out:
------------------------

mvn clean package

Error Thrown:
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'actorsController': Unsatisfied dependency expressed through field 'telemetryClient'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.microsoft.applicationinsights.TelemetryClient' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: 
 - OS type and version: Mac
 - Application Server type and version (if applicable):
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable):

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

**Comment by littleaj** [comment]
@jyotsnaravikumar Do you see the same issue in the latest version of the starter? 2.5.0

**Comment by villaratio** [comment]
I'm using version 2.5.1 and ran into the same issue.
Here's my maven config

`    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>applicationinsights-spring-boot-starter</artifactId>
      <version>2.5.1</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>applicationinsights-logging-logback</artifactId>
      <version>2.5.1</version>
    </dependency>`

When trying to use an autowired TelemetryClient
`No qualifying bean of type 'com.microsoft.applicationinsights.TelemetryClient' available`

P.S. 
I noticed that the TelemetryClient exists both in the core and in the web jar. Both with the same package. A bit strange...

**Comment by normalian** [comment]
I had same issue here with trying a version below.


		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>applicationinsights-spring-boot-starter</artifactId>
			<version>2.5.0</version>
		</dependency>

**Comment by andrejpk** [comment]
Here's a pom.xml excerpt that works (logging and metrics):
``` xml
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>applicationinsights-spring-boot-starter</artifactId>
			<version>2.6.0</version>
	</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>applicationinsights-logging-logback</artifactId>
			<version>[2.6,)</version>
		</dependency>
		<dependency> 
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-spring-boot-metrics-starter</artifactId>
			<version>[2.2,)</version>
		</dependency>
```

**Comment by trask** [comment]
Please try out [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent) and let us know if that resolves the issue for you
