### ISSUE TITLE
Add support for automatic context propagation across messaging technologies (ex: JMS)

### ISSUE THREAD

**Issue by sairam-github** [microsoft/ApplicationInsights-Java#1165]
Please add support for automatic context propagation across messaging technologies (ex: JMS) so that both operation_id and operation_parentId need not be embedded in the actual message object.

**Comment by trask** [comment]
JMS is auto-captured and auto-correlated now in [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent)
