### ISSUE TITLE
Live Metrics support for custom filtering

### ISSUE THREAD

**Issue by kasuri** [microsoft/ApplicationInsights-Java#1166]
Hi,

We are incorporating App Insights for my company and one feature that we are very interested in (live stream metrics) does not seem to be supported by the Java SDK. It's available for .NET but our apps are using JAVA.  Is there an alternative available or any plan to incorporate with Java?

Here is the reference URL that suggests with JAVA custom filters are not supported.   https://docs.microsoft.com/en-us/azure/azure-monitor/app/live-stream 

Thanks!

**Comment by littleaj** [comment]
Yes, we currently only have partial support for live metrics in the Java SDK. [The table on that page](https://docs.microsoft.com/en-us/azure/azure-monitor/app/live-stream#supported-features-table) does reflect the currently supported features.

I'll update this ticket there are plans to implement in the future.

**Comment by trask** [comment]
Closing in favor of #1512
