### ISSUE TITLE
Could not send data to Application Insights in Azure China.

### ISSUE THREAD

**Issue by anotherfatcat** [microsoft/ApplicationInsights-Java#1168]
### Expected behavior
Leveraging this SDK should be able to send telemetry/metrics to Application Insights of Azure China area.

### Actual behavior
Even I've gotten the instrumentation key and set it to APPLICATION_INSIGHTS_IKEY environment variable correctly, still no data was saved in the Application Insights within Azure China area. And the same approach could help us to send telemetry/metrics to Application Insights of other areas.

### To Reproduce
Initialize an instance of TelemetryClient and then call trackTrace() or trackMetric().

### System information
Please provide the following information:
 - SDK Version: 2.5.0
 - OS type and version: Ubuntu 18.04
 - Application Server type and version (if applicable): 
 - Using spring-boot? No
 - Additional relevant libraries (with version, if applicable):

### Logs
Attached.
[AI-2019-11-29-11-55-37-JavaSDKLog7983645624983117194.zip](https://github.com/microsoft/ApplicationInsights-Java/files/3903698/AI-2019-11-29-11-55-37-JavaSDKLog7983645624983117194.zip)

### Screenshots
N/A

**Comment by joergjo** [comment]
Have you set the [custom endpoint](https://docs.microsoft.com/en-us/azure/azure-monitor/app/custom-endpoints) for Azure China?

**Comment by littleaj** [comment]
@anotherfatcat, from the logs, I can see that @joergjo is correct; you need to override the SDK endpoint.

I strongly recommend upgrading to version 2.5.1. This adds the [Connection String feature](https://github.com/microsoft/ApplicationInsights-Java/wiki/ApplicationInsights.XML#connectionstring) which makes setting the SDK endpoints much easier, and also fixes a bug with live metrics in Azure China.

The connection string can be found just under your instrumentation key in the azure portal. It should contain your instrumentation key as well as a setting for the endpoint (`EndpointSuffix=applicationinsights.azure.cn`).

**Comment by anotherfatcat** [comment]
> Have you set the [custom endpoint](https://docs.microsoft.com/en-us/azure/azure-monitor/app/custom-endpoints) for Azure China?

No, I didn't. After I set the endpoint for Azure China, it works fine. Thanks for your reminder.

**Comment by anotherfatcat** [comment]
> @anotherfatcat, from the logs, I can see that @joergjo is correct; you need to override the SDK endpoint.
> 
> I strongly recommend upgrading to version 2.5.1. This adds the [Connection String feature](https://github.com/microsoft/ApplicationInsights-Java/wiki/ApplicationInsights.XML#connectionstring) which makes setting the SDK endpoints much easier, and also fixes a bug with live metrics in Azure China.
> 
> The connection string can be found just under your instrumentation key in the azure portal. It should contain your instrumentation key as well as a setting for the endpoint (`EndpointSuffix=applicationinsights.azure.cn`).

Thanks for your suggestion. Could you please let me know where I can find more details about the environment variable EndpointSuffix? Currently I can only do the endpoint override in ApplicationInsights.XML file, but if an environment variable can help me to override the endpoint, that would be great.

**Comment by littleaj** [comment]
@anotherfatcat, the EndpointSuffix is part of the connection string, e.g you would set the environment variable 
```
APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=*your ikey*;EndpointSuffix=applicationinsights.azure.cn
```
Where `*your ikey*` is replaced with the instrumentation key for your Application Insights resource.
You should find the connection string shown in the Overview tab in your Application Insights resource.

**Comment by anotherfatcat** [comment]
> @anotherfatcat, the EndpointSuffix is part of the connection string, e.g you would set the environment variable
> 
> ```
> APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=*your ikey*;EndpointSuffix=applicationinsights.azure.cn
> ```
> 
> Where `*your ikey*` is replaced with the instrumentation key for your Application Insights resource.
> You should find the connection string shown in the Overview tab in your Application Insights resource.

Cool! It is working well now!

Thanks for your detailed comments.
