### ISSUE TITLE
How to use Application Insights in Web Java deployed in Wildfly

### ISSUE THREAD

**Issue by apescione** [microsoft/ApplicationInsights-Java#1169]
Hi,
I have an web application (I cannot modify its code) deployed on Wildfly and I want to use Application Insights and its Agent to monitor it.

Is There a Jboss/Wildfly module that I could use for?

Could I apply another approach for doing this?

Thank you in advance.

I've created this issue as Feature because probably there is a way to do it.

**Comment by itsforbrijesh** [comment]
We also have same requirement where we don't want to package SDK with Apps rather have it on the server where all apps can refer. This will allow us to deploy the newer version without redeploying the app and just restart is needed to take an effect of the new SDK jar.

**Comment by trask** [comment]
Please try out [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent) and let us know if that resolves the issue for you
