### ISSUE TITLE
class conflict with a "glowroot$auxContext" class

### ISSUE THREAD

**Issue by eseybee** [microsoft/ApplicationInsights-Java#1170]
We are trying Application Insights integration with Artifactory (Java web app) in Azure IAAS. 

There is a class conflict with a "glowroot$auxContext" class.
```
Exception in thread "main" java.lang.ClassFormatError: Duplicate field name "glowroot$auxContext" with signature "Lorg.glowroot.instrumentation.api.AuxThreadContext;" in class file org/apache/juli/ClassLoaderLogManager$Cleaner
```

AI-Agent.xml file:
```
<?xml version="1.0" encoding="utf-8"?>
<ApplicationInsightsAgent>
   <Instrumentation>
      <BuiltIn enabled="true">

         <!-- capture logging via Log4j 1.2, Log4j2, and Logback, default is true -->
         <Logging enabled="false" />

         <!-- capture outgoing HTTP calls performed through Apache HttpClient, OkHttp,
              and java.net.HttpURLConnection, default is true -->
         <HTTP enabled="false" />

         <!-- capture JDBC queries, default is true -->
         <JDBC enabled="false" />

         <!-- capture Redis calls, default is true -->
         <Jedis enabled="false" />

         <!-- capture query plans for JDBC queries that exceed this value (MySQL, PostgreSQL),
              default is 10000 milliseconds -->
         <MaxStatementQueryLimitInMS>1000</MaxStatementQueryLimitInMS>

      </BuiltIn>
   </Instrumentation>
</ApplicationInsightsAgent>
```

System Information:
-    os.name: Linux
-    os.version: 3.10.0-957.5.1.el7.x86_64
-    java.runtime.name: OpenJDK Runtime Environment
-    java.runtime.version:1.8.0_222-b10

**Comment by trask** [comment]
Hi @eseybee, Artifactory has a Glowroot-based monitoring of its own (http://bullfrog.live/), which we are probably conflicting with as we are also using Glowroot-based instrumentation. Can you check if you are using the BullFrog monitoring, and if so, are you able to remove it? Thanks!

**Comment by eseybee** [comment]
Hi @trask, we have removed BullFrog but we are still seeing the “Exception in thread "main" java.lang.ClassFormatError: Duplicate field name "glowroot$auxContext" with signature "Lorg.glowroot.instrumentation.api.AuxThreadContext;" in class file org/apache/juli/ClassLoaderLogManager$Cleaner”

**Comment by trask** [comment]
Please try out [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent) and let us know if that resolves the issue for you

**Comment by multicaststorm** [comment]
A similar issue was happening to me when running within my IDE, although I think it was due to IntelliJ doing something 'intelligent'

When I ran standalone as a gradle java exec task, then all was fine.

I have also given 3.0 preview a go and it seems to work well for me.

Any news on 3.0 being fully released (including an accessible sdk)?....We want to starting using applications insights for all of our java apps and it would nice to know when it was going to land

**Comment by MS-jgol** [comment]
@multicaststorm Glad to hear that 3.0 is working for you.
Why is 3.0 GA critical? We have customers using it production already. Official GA data though is early November. 
What are you planning to use the SDK for? We are investing heavily into the agent in hopes that it will give you the functionality you are looking for.

**Comment by multicaststorm** [comment]
@MS-jgol It would set off alarm bells at my workplace if I want to use a dependency that is not in maven and has the name 'Preview'! (even though im sure its fine)

I wanted to use the SDK for customizations e.g. Custom TelemetryInitializer

Also I want to have finer grain control over my logging telemetry. So I created my own Log handler against v2.6.1 sdk (with custom field mappings and filter).

I can see this might work if I disable logging instrumentation in the 3.0 agent, and then continue to use my 2.6.1 customization.

But It all just feels a bit messy, so I was wondering what the future proof recommendation is?

**Comment by trask** [comment]
Hi @multicaststorm, could you share your custom TelemetryInitializers with us? We are trying to understand the various ways that they are being used as we plan for 3.0 GA. If you prefer not to share publicly, please send to trask.stalnaker@microsoft.com. Thanks.

**Comment by multicaststorm** [comment]
Our custom initializer is only doing simple stuff like setting some global fields, e.g:
```java
telemetry.getContext().getComponent().setVersion("1.0.0");
telemetry.getContext().getProperties().putIfAbsent("DataClassification", "Confidential");
```

But our bigger issue is the other areas we plan to customise:

- Our custom log handlers (similar to your Log4J apppender in 2.6.x). We want to have complete control over what logs are sent and also the ability to set additional context specific dimensions via our semantic logging api.

- The ability to send custom telemetry (as you describe for 2.6.x in [sending custom telemetry](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#sending-custom-telemetry-using-application-insights-java-sdk-2x))

- Our instrumentation key can't be configured upfront in the agent json file....we need to fetch it securely at runtime based on what environment we are in. So already we are considering writing our own agent that wraps the application insights agent so we can fetch it and then programatically set it as an environment variable

In general I think its great that you can just attach the agent and off you go, but the ability to extend and customise is going to be show stopper for us.

**Comment by trask** [comment]
hey @multicaststorm, thanks for getting back,

* For your custom initializer - is there any conditional logic involved here, or these are just statically applied to all telemetry?
  * Would it work for you if we supported declaring global attributes in `ApplicationInsights.json`?
* Custom log handlers - you can disable agent log capture and continue doing the same in 3.0
* Custom telemetry - you can continue doing the same in 3.0 (but no telemetry initializers / processors)
* Instrumentation key - are you running in Azure cloud (vs on-prem)? are you fetching it from keyvault?

**Comment by multicaststorm** [comment]
@trask 

- Global Attributes in `ApplicationInsights.json` - This would be an improvement, but I can already see that I might want to set my application version number (which I could do programmatically in a custom initializer)
- Custom log handlers - Do you mean by continuing to do the custom stuff with 2.x sdk, and rest via 3.x codeless agent? Is this a sustainable approach going forward? i.e. will development continue on 2.x ?
- Custom telemetry - _same issue as log handler_
- Instrumentation key - Currently we are on-prem and have our own custom mechanism for storing enviroment specific config/secrets. Once we move to Azure cloud then I suspect we will use keyvault (I think our C# teams do that)

**Comment by trask** [comment]
hey @multicaststorm,

> * Global Attributes in `ApplicationInsights.json` - This would be an improvement, but I can already see that I might want to set my application version number (which I could do programmatically in a custom initializer)

application version number can be set now: https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#custom-dimensions

> * Custom log handlers - Do you mean by continuing to do the custom stuff with 2.x sdk, and rest via 3.x codeless agent? Is this a sustainable approach going forward? i.e. will development continue on 2.x ?
> * Custom telemetry - _same issue as log handler_

Once OpenTelemetry hits 1.0 we will start recommending that for new users who need to do custom stuff on top of auto-instrumentation. We will continue to support the 2.x SDK.

> * Instrumentation key - Currently we are on-prem and have our own custom mechanism for storing enviroment specific config/secrets. Once we move to Azure cloud then I suspect we will use keyvault (I think our C# teams do that)

I think most of the Azure cloud environments have a way to pull env var from keyvault.
