### ISSUE TITLE
Question: Tracking Dependencies in a JMS Consumer

### ISSUE THREAD

**Issue by DamianJava** [microsoft/ApplicationInsights-Java#1175]
Hi,

Is it possible to track dependencies in a JMS consumer rather than a web request.

Looking at the code it seems that dependency tracking is tied to the agent bridge, but I may have got this wrong.

Would I have to bind the agent bridge to the thread around processing a message in a JMS  consumer?

Thanks

### System information
Please provide the following information:
 - SDK Version: 2.5.1
 - OS type and version: windows 10/centos 7
 - Application Server type and version (if applicable): tomcat
 - Using spring-boot? no
 - Additional relevant libraries (with version, if applicable):

**Comment by MS-jgol** [comment]
Are you running your app in App Service or AKS by any chance?

**Comment by DamianJava** [comment]
Unfortunately not. The application is deployed in a standalone tomcat instance and is consuming messages from an ActiveMQ instance. Thanks.

**Comment by trask** [comment]
This is supported in [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent)
