### ISSUE TITLE
Question: Java 1.6 support - please see below

### ISSUE THREAD

**Issue by StuartConnor1** [microsoft/ApplicationInsights-Java#1176]
HI we have an old application that is on Java 1.6 and we are looking to roll Azure Appinsights into all our applications. I can see that at the momnet Java 1.8 and above is supported. Was 1.6 every supported? and if so can I have teh SDK's if it was? Appreciate that it's not supported. We are looking to upgrade the Java but want to use Appinsights to get a bench mark of performance before we upgrade so we can identify degredation in service as we upgrade. cheers

**Comment by littleaj** [comment]
@StuartConnor1 The last version to support Java 6 was [1.0.10](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/v1.0.10). Support was dropped in version [2.0.1](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/v2.0.1) (See notes in [2.0.0-BETA](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/v2.0.0-BETA))

Currently, we build with Java 8 but we still support Java 7.
