### ISSUE TITLE
SDK must truncate fields to the length acceptable by the backend

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-Java#1180]
### Expected behavior
If `SessionID` was set to the value that is longer than 64 characters, telemetry must be send with the truncated value to be received by Application Insights backend

### Actual behavior
See error message: "Error sending data: 100: Field 'ai.session.id' on type 'ContextTagKeys' is too long. Expected: 64 characters, Actual: 66"

### To Reproduce
Steps to reproduce the behavior (from customer):
- read sessionID from the jsessionID cookie.
- getting error

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: 2.5.1

**Comment by SergeyKanzhelev** [comment]
See https://github.com/microsoft/ApplicationInsights-dotnet/blob/94495100a60c9278973cc10df34e0a9245cec5a5/BASE/src/Microsoft.ApplicationInsights/Extensibility/Implementation/Property.cs#L31-L54

**Comment by littleaj** [comment]
@trask, this shouldn't be too difficult. Queuing for BETA.2.
