### ISSUE TITLE
Exclude some urls from tracking

### ISSUE THREAD

**Issue by lidkowiak** [microsoft/ApplicationInsights-Java#1183]
It would be nice to have a possibility of defining URL patterns to filter by WebRequestTrackingFilter. There are cases when we don't want to collect telemetries for particular paths/resources (e.g. actuator endpoints)

Solution proposal:
You can add config property (with default value "/*")

**Comment by martupeppe** [comment]
> It would be nice to have a possibility of defining URL patterns to filter by WebRequestTrackingFilter. There are cases when we don't want to collect telemetries for particular paths/resources (e.g. actuator endpoints)
> 
> Solution proposal:
> You can add config property (with default value "/*")
> 

It would be nice to have this configuration on java codeless agent also...

**Comment by hangryfabian** [comment]
Is there an easy solution to url filtering? 
In some of the azure docs I see "NotNeededUrls", but when I look at the library and the RequestTelemetryFilter class, it does not use this property.

In the xml I have the following:
  <TelemetryProcessors>
    <BuiltInProcessors>
      <Processor type="RequestTelemetryFilter">
        <Add name="MinimumDurationInMS" value="20"/>
        <Add name="NotNeededUrls" value="home"/>
      </Processor>
    </BuiltInProcessors>
  </TelemetryProcessors>

**Comment by zhoufenqin** [comment]
@trask the feature hasn't been supported yet? It would be nice to support this

**Comment by trask** [comment]
[3.0.3-BETA.2](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.3-BETA.2) is released with [sampling overrides (preview)](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-sampling-overrides) which allows you to exclude (or reduce sampling percentage) for health checks(!)
