### ISSUE TITLE
Do you support normal java application [not web app] to use for capturing custom events?

### ISSUE THREAD

**Issue by kunalchandratre1** [microsoft/ApplicationInsights-Java#1185]
I created a sample java application in eclipse. It is not a web application. It is a simple class with main method. I plan to use this project to log custom events. 
Do you support normal java application in eclipse[not web app] to use for capturing custom events?

**Comment by MS-jgol** [comment]
@kunalchandratre1 
If by "not web app" you mean a non-http app, then no, we do not support that.

**Comment by littleaj** [comment]
@kunalchandratre1 We don't support any automatic instrumentation for non-webapps, but you can still use the `TelemetryClient.track` methods (e.g. `trackEvent`) with an ApplicationInsights.xml configuration file.

**Comment by trask** [comment]
This is supported now in [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent)
