### ISSUE TITLE
Out of the box support for tracking telemetry of I/O operations

### ISSUE THREAD

**Issue by sairam-github** [microsoft/ApplicationInsights-Java#1198]
**Is your feature request related to a problem? Please describe.**
Describe what the problem you have encountered; e.g I'm always frustrated when [...]

**Describe the solution you would like**
Describe what you want to happen.

**Describe alternatives you have considered**
Describe any alternative solutions or features you've considered.

**Additional context**

**Comment by sairam-github** [comment]
Currently, the only way to track the telemetry of I/O operations is by using custom events. It would be very useful if Java SDK has out-of-the-box support.

**Comment by trask** [comment]
Hi @sairam-github, what I/O operations are you interested in tracking?

**Comment by sairam-github** [comment]
Hi Trask, our app is reading (FileInputStream/DataInputStream) and writing (FileOutputStream/DataOutputStream) to the file system or a shared mount. I would like the ability to capture, at a high level, some info about the connection and track the telemetry data. I know I could track it using custom events, however, just wondering if SDK covers this by default (as it does for Rest calls, Oracle DB calls, etc.,)

**Comment by trask** [comment]
Hi @sairam-github, file operations tend to be a bit lower-level than what we typically capture (e.g. network operations). We're working on providing options for lower-level diagnostics in the future, but no timeline on that yet.

**Comment by sairam-github** [comment]
Thanks for the update, I appreciate it.
