### ISSUE TITLE
NopThreadContext is used for background process

### ISSUE THREAD

**Issue by gennadiy-dubina** [microsoft/ApplicationInsights-Java#1208]
Hi everybody,

We are using appinsight agent for monitoring spring boot applications.
some application consume request via http, other uses service bus (we use azure service bus via https://github.com/microsoft/spring-cloud-azure )

Agent records dependencies correctly for  apps with http endpoints and DOES NOT record dependencies for apps with service bus endpoints,

After some debugging i have found that everything depends on thread context.
if thread context is populated with **ThreadContextImpl** span will be recorded when thread context is **NopThreadContext**  - everything will be ignored

I have found that **ThreadContextImp** is populated via **AgentBridgeImpl.bindToThread** from 
**com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter**

So my question is how to implement the same behavior for service bus endpoints? How to inject thread context to allow record dependencies?

Thanks,

**Comment by trask** [comment]
Hi @gennadiy-dubina, are you using JMS for your service bus endpoints? If so, [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent) should auto-capture that now.
