### ISSUE TITLE
SecurityException: class "org.xmlpull.v1.XmlPullParserFactory"'s signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by adamkulcsar** [microsoft/ApplicationInsights-Java#1209]
Shadow JAR is evil and source of numerous class loading problems. Please provide a distribution with proper pom.xml files.

### Expected behavior
Able to use XStream indepenendently from this lib

### Actual behavior
Exception thrown because of this shadow jar

### To Reproduce
Use XStream

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: 2.5.1
 - OS type and version: Adoptopenjdk 9 container
 - Application Server type and version (if applicable): Spring boot 2.2.1 on Tomcat
 - Using spring-boot?
 - Additional relevant libraries (with version, if applicable): XStream 1.4.11.1

### Logs
java.lang.SecurityException:
   at java.lang.ClassLoader.checkCerts
   at java.lang.ClassLoader.preDefineClass
   at java.lang.ClassLoader.defineClass
   at java.security.SecureClassLoader.defineClass
   at jdk.internal.loader.BuiltinClassLoader.defineClass
   at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull
   at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull
   at jdk.internal.loader.BuiltinClassLoader.loadClass
   at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass
   at java.lang.ClassLoader.loadClass
   at com.thoughtworks.xstream.io.xml.XppDriver.createDefaultParser (XppDriver.java62)
   at com.thoughtworks.xstream.io.xml.XppDriver.createParser (XppDriver.java68)
   at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader (AbstractXppDriver.java54)
   at com.thoughtworks.xstream.XStream.fromXML (XStream.java1338)

**Comment by littleaj** [comment]
This will be fixed in 2.6.0. 2.6.0-BETA.2 has already addressed this issue if you'd like to try that version.
