### ISSUE TITLE
Unable to view Live Metric for Java Web app

### ISSUE THREAD

**Issue by nuk23** [microsoft/ApplicationInsights-Java#1212]
### Expected behavior
I am using Maven based Java Web application (Mulesoft) which essentially uses Java Spring. I am using Application Insights web auto SDK version 2.5.0 to send the tememetry data to App insights and using Application.xml file. 
while checking on the Live Metric tab its unable to show any telemtry/traces and keeps giving a pop up to update the SDK version. However I am able to send the traces, events, request manually using the java classes but still no telemetry data shows up in the Live Metric. 

### Actual behavior
Should be able to see the traces/temetry in the Live Metric.
 
#### Sample Application
Application.xml
```
<?xml version="1.0" encoding="utf-8"?>
<ApplicationInsights  xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings" schemaVersion="2014-05-30">
 
  <!-- The key from the Azure portal: -->
   <InstrumentationKey>**********</InstrumentationKey> 
  
    <RoleName>test-api</RoleName>
   <!-- HTTP request component (not required for bare API) -->
   <TelemetryModules>
      <Add type="com.microsoft.applicationinsights.web.extensibility.modules.WebRequestTrackingTelemetryModule"/>
      <Add type="com.microsoft.applicationinsights.web.extensibility.modules.WebSessionTrackingTelemetryModule"/>
      <Add type="com.microsoft.applicationinsights.web.extensibility.modules.WebUserTrackingTelemetryModule"/>
   </TelemetryModules> 

   <!-- Events correlation (not required for bare API) -->
   <!-- These initializers add context data to each event -->
   <TelemetryInitializers>
      <Add type="com.microsoft.applicationinsights.web.extensibility.initializers.WebOperationIdTelemetryInitializer"/>
      <Add type="com.microsoft.applicationinsights.web.extensibility.initializers.WebOperationNameTelemetryInitializer"/>
      <Add type="com.microsoft.applicationinsights.web.extensibility.initializers.WebSessionTelemetryInitializer"/>
      <Add type="com.microsoft.applicationinsights.web.extensibility.initializers.WebUserTelemetryInitializer"/>
      <Add type="com.microsoft.applicationinsights.web.extensibility.initializers.WebUserAgentTelemetryInitializer"/>
   </TelemetryInitializers> 

  <!-- OS Performance counters should be sucked in by default unless you set "UseBuiltIn" to False -->
  <PerformanceCounters>
    <!-- a couple JMX counters as an example of Java specific monitoring -->
    <Jmx>
      <Add objectName="java.lang:type=ClassLoading"
        attribute="TotalLoadedClassCount" displayName="Loaded Class Count"/>
      <Add objectName="java.lang:type=Memory"
        attribute="HeapMemoryUsage.used" displayName="Heap Memory Usage-used" type="composite"/>
      <Add objectName="java.lang:type=Threading"
        attribute="ThreadCount" displayName="Thread Count" />
 
<!--       
	  <Add objectName="java.lang:type=GarbageCollector,name=&quot;PS MarkSweep&quot;"
        attribute="CollectionCount" displayName="GC MarkSweep Count" />
      <Add objectName="java.lang:type=GarbageCollector,name=&quot;PS Scavenge&quot;"
        attribute="CollectionCount" displayName="GC Scavange Count" />
 
   
 	   <Add objectName="Mule.7eleven-marketing-api:type=Flow,name=&quot;7eleven-marketing-api-main&quot;"
        attribute="AverageProcessingTime" displayName="mule Ave Proc Time exampleFlow" />
       <Add objectName="Mule.7eleven-marketing-api:type=Flow,name=&quot;stores:7eleven-marketing-api-config&quot;"
        attribute="MaxProcessingTime" displayName="mule Max Proc Time exampleFlow" />
       <Add objectName="Mule.7eleven-marketing-api:type=Flow,name=&quot;stores:7eleven-marketing-api-config&quot;"
        attribute="ProcessedEvents" displayName="mule Events Processed exampleFlow" />
 -->
    </Jmx>
  </PerformanceCounters>  
   
  <!-- This turns on diagnostic level logging -->
  <SDKLogger></SDKLogger>
</ApplicationInsights >
```
### System information
Please provide the following information:
 - SDK Version: 2.5.0
 - OS type and version: Windows
 - Application Server type and version (if applicable): 
 - Using spring-boot? No
 - Additional relevant libraries (with version, if applicable):

### Screenshots
![AppInsight](https://user-images.githubusercontent.com/61678548/75649683-fc469780-5ca7-11ea-8aca-5e7b5698514a.jpg)

**Comment by littleaj** [comment]
@nuk23 This view has recently been updated and will be released in your region soon. Not all features of live metrics are supported by the Java SDK. The full list of supported features is documented here: https://docs.microsoft.com/en-us/azure/azure-monitor/app/live-stream#supported-features-table.

**Comment by trask** [comment]
The UX fix for this should be rolled out to all regions next Mon 3/16.

**Comment by surbhin** [comment]
Hi , 
Is the fix already rolled out? 
I am facing the same issue for a spring app deployed in Tomcat. 
The steps defined here at 
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-get-started?tabs=maven 
are being followed.
SDK version tried:
2.5.0
2.6.0
1.0.10 ->> mentioned https://github.com/microsoft/ApplicationInsights-Java/issues/450

None of these versions are helping send logs to to Azure Monitor.
I am also placing the files as mentioned here in Tomcat: WEB-INF/classes folder

All other troubleshoot steps are also checked : https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-troubleshoot

Any help or update is appreciated.

**Comment by trask** [comment]
Hi @surbhin, can you attach a screenshot of what you are seeing in Live Metrics? Thanks!

**Comment by gitrepo12345** [comment]
Hi @trask. I am using appinsights version 1.0.8 and my gradle build is passing but I do not see Live Metrics in Azure. I tried updating to latest version and my build fails with error. 
![image](https://user-images.githubusercontent.com/39868420/83293801-e450b800-a1b1-11ea-9e15-4e0af0bd7411.png)
Any help is much appreciated.

**Comment by trask** [comment]
Hi @gitrepo12345, live metrics is not supported in `1.0.8`. The latest version is `2.6.0`, or you can try the 3.0 Preview which is generally much easier to get up and running.

**Comment by gitrepo12345** [comment]
@trask I tried updating to version 2.0.14 but the build fails. When I run the build with version 1.0.8, I do not have any issues with the build. This is the build error - 

![image](https://user-images.githubusercontent.com/39868420/83318961-834fd100-a1ff-11ea-82a1-d45c0cbfd528.png)

**Comment by MS-jgol** [comment]
@gitrepo12345 Have you tried the 3.0 version? Strongly recommend that one.

**Comment by gitrepo12345** [comment]
@MS-jgol I just tried 3.0 version. Getting similar error.

**Comment by trask** [comment]
Hi @gitrepo12345, 3.0 is not a maven dependency, see https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent

**Comment by gitrepo12345** [comment]
@trask Thanks for your prompt response. I am wondering how to pass this argument in Azure Pipelines. I am using Azure Hosted Windows Agent 2019 to run this pipeline.

**Comment by trask** [comment]
Hi @gitrepo12345, not sure about this setup, you'll need to figure out where to add JVM args to the Java process you are trying to monitor.

Typical JVM args include -Xmx512m and -XX:+UseG1GC. So try to find out where to add these, and it will be the same place.
