### ISSUE TITLE
using applicationinsights-web-auto 2-6-3-BETA.3 for JAVA, Azure still redirect me to nuget

### ISSUE THREAD

**Issue by gianlucagravina** [microsoft/ApplicationInsights-Java#1215]
### Expected behavior
Using the latest version of the library I would expect the AppInsights live metrics would notify me only in case of newer version (would love to configure even if just stable or prereleases too)

### Actual behavior
Using the latest version 2.6.3-BETA3 in the live metrics preview I still have the message on the right pane ("Your application is instrumented with Application Insights SDK version java:2.6.0-BETA.3. Upgrade to the latest stable SDK to get a live feed of events with details like request url, response code, SQL query, and exception stack."). the link redirect to nuget (I am using the Java lib)

### To Reproduce
Simply put this line in your gradle file 
compile group: 'com.microsoft.azure', name: 'applicationinsights-web-auto', version: '2.6.0-BETA.3'
cofigure, build and run. And then navigate to your Live Metrics page.

#### Sample Application
If applicable, provide a sample application which reproduces the issue.
NONE

### System information
Please provide the following information:
 - SDK Version: 2.6.3-beta3
 - OS type and version: Ubuntu 18.04 VM on Azure.
 - Application Server type and version (if applicable): Spring APP (java -javaagent:agent.jar -jar app.jar)
 - Using spring-boot? YES
 - Additional relevant libraries (with version, if applicable):

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

### Screenshots
![image](https://user-images.githubusercontent.com/55887306/76283095-a6d83f00-62d4-11ea-9dcb-6d30b3fc3928.png)

**Comment by trask** [comment]
Hi @gianlucagravina, the UX fix for this should be rolled out to all regions next Mon 3/16. With the new UX, it will direct you to [this support matrix](https://docs.microsoft.com/en-us/azure/azure-monitor/app/live-stream#supported-features-table) instead of displaying that incorrect message.
