### ISSUE TITLE
Unable to track External Dependencies with JAVA Agent

### ISSUE THREAD

**Issue by grava** [microsoft/ApplicationInsights-Java#1216]
### Expected behavior
Spring boot app should track external dependencies in the application map

### Actual behavior
No dependencies tracked if not manually tracked (client.trackDependency(...)) tried using
- OkHttp Client for Feign
- Apache HttpClient for Feign
- Normal RestClient
still no dependency tracking in the application map in app insights.

### To Reproduce
libraries used:
'org.springframework.boot' version '2.2.5.RELEASE'
"com.microsoft.azure:applicationinsights-spring-boot-starter:2.6.0-BETA.3"
"com.microsoft.azure:applicationinsights-logging-log4j2:2.6.0-BETA.3"
"io.github.openfeign:feign-httpclient:10.8"
"io.github.openfeign:feign-okhttp:10.8"

#### Sample Application
https://github.com/gianlucagravina/appInsightsDemo

**Comment by trask** [comment]
Hi @grava! Thanks for the sample application! When I ran it and hit `http://localhost:10030/manual`, it captured remote dependency for me:

![image](https://user-images.githubusercontent.com/218610/76918493-a36c2700-6883-11ea-8823-f34cb786fcbf.png)

Is this what you are not seeing, or is it something else that you are not seeing?

Thanks!
