### ISSUE TITLE
Heartbeat Module using default config when using Logback Appender in Spring Boot app

### ISSUE THREAD

**Issue by the-wrangler17** [microsoft/ApplicationInsights-Java#1217]
### Expected behavior
The Heartbeat Module should use the configuration in application.properties,  not the default configuration, regardless of the Logback Appender. 

### Actual behavior
The presence of the Logback Appender is causing the Heartbeat Module to initialize with the defaults, heartbeat interval of 15 minutes. The heartbeat interval in application.properties is configured to 60 seconds. When the Logback Appender is removed, the Heartbeat Module uses the application.properties settings, as expected.

### To Reproduce
1. Configure the Logback Appender in logback-spring.xml
2. Add azure.application-insights.heart-beat.heart-beat-interval=60 to application.properties
3. Start the application.

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: 2.5.1
 - OS type and version: Windows 10 and RHEL 7.6
 - Application Server type and version (if applicable):
 - Using spring-boot? Yes. 2.1.10
 - Additional relevant libraries (with version, if applicable):
        implementation 'com.microsoft.azure:applicationinsights-spring-boot-starter:2.5.1'
	implementation 'com.microsoft.azure:applicationinsights-logging-logback:2.5.1'

### Logs
[SDK_logs_no_logback.txt](https://github.com/microsoft/ApplicationInsights-Java/files/4344309/SDK_logs_no_logback.txt)
[SDK_logs_with_logback.txt](https://github.com/microsoft/ApplicationInsights-Java/files/4344313/SDK_logs_with_logback.txt)

**Comment by littleaj** [comment]
@the-wrangler17 It looks like the appender is initializing the heartbeat module before application.properties is processed. As a workaround, you could try providing an ApplicationInsights.xml with the heartbeat configuration.

**Comment by trask** [comment]
This should be resolved in [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent)
