### ISSUE TITLE
Spring-boot configuration clarification 

### ISSUE THREAD

**Issue by giventocode** [microsoft/ApplicationInsights-Java#1218]
The documentation for spring-boot states the following:

Note: Do not configure azure.application-insights.instrumentation-key property for optimal performance and avoiding any Application Insights beans creation by Spring.

If it is not recommended to use standard spring DI and config, what is the suggested approach?

**Comment by trask** [comment]
Hi @giventocode! That note is under the section [Completely disable Application Insights using application.properties](https://github.com/microsoft/ApplicationInsights-Java/blob/master/azure-application-insights-spring-boot-starter/README.md#completely-disable-application-insights-using-applicationproperties), and only applies if you are trying to completely disable Application Insights.

**Comment by giventocode** [comment]
Thank you!
