### ISSUE TITLE
Remove dependency to guava

### ISSUE THREAD

**Issue by gdufrene** [microsoft/ApplicationInsights-Java#1223]
**Is your feature request related to a problem? Please describe.**
ApplicationInsight is provided as a shaded jar with quite a lot of dependency.
It leads to a jar around 20 Mo.
Most of this comes from guava dependency.

**Describe the solution you would like**
Would you like a PR to remove guava ?
Most of guava usage is Strings.isNotOrEmpty Or Preconditions
It could easily be replaced with commons-lang StringUtils.isEmpty equivalent...

**Additional context**
As an exemple, I forked master of this project and removed guava, xstream, and set some others things ... so it is perfectly possible.
https://github.com/gdufrene/ApplicationInsights-Java

If You are Ok I can provide a PR only with guava removed.
And If needed, with xstream replaced with common jaxb.

**Comment by trask** [comment]
Closing, please let us know if this is still a concern for you in 3.0, which is deployed solely as a java agent
