### ISSUE TITLE
Update documentation for Sampling configuration

### ISSUE THREAD

**Issue by dylan-asos** [microsoft/ApplicationInsights-Java#1224]
The documentation for the sampling configuration is out of date - XML Element names have changed from what is documented,

https://github.com/microsoft/ApplicationInsights-Java/wiki/Sampling

For example, adaptive sampling should be like: (values here are the defaults configured if not provided)

```
    <Sampling>
        <Adaptive>
            <MaxTelemetryItemsPerSecond>100</MaxTelemetryItemsPerSecond>
            <MovingAverageRatio>0.25</MovingAverageRatio>
            <EvaluationIntervalInSec>120</EvaluationIntervalInSec>
            <MinSamplingPercentage>1</MinSamplingPercentage>
            <InitialSamplingPercentage>100</InitialSamplingPercentage>
            <MaxSamplingPercentage>100</MaxSamplingPercentage>
            <SamplingPercentageIncreaseTimeoutInSec>120</SamplingPercentageIncreaseTimeoutInSec>
            <SamplingPercentageDecreaseTimeoutInSec>900</SamplingPercentageDecreaseTimeoutInSec>
        </Adaptive>
    </Sampling>
```

Please update!

**Comment by trask** [comment]
Closing, sampling configuration for 3.0 is documented [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#sampling) and [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-sampling-overrides).
