### ISSUE TITLE
Order of Context Initializers

### ISSUE THREAD

**Issue by the-mod** [microsoft/ApplicationInsights-Java#1231]
### Expected behavior
I wrote a custom ContextInitializer which sets the Cloud Role Instance.
The Cloud Role Instance should appear in AppInsights with each and every log message.
Messages with Log4J seams fine, but logs send with TelemetryClient got overwritten by the default values again.

### Actual behavior
Value is overwritten by IP in this Case
[see here](https://github.com/microsoft/ApplicationInsights-Java/blob/bc01d832bb351c5150978b816cf394de24853aea/core/src/main/java/com/microsoft/applicationinsights/common/CommonUtils.java#L41)

### System information
Please provide the following information:
 - SDK Version:
  * applicationinsights-logging-log4j2 2.5.1
  * applicationinsights-spring-boot-starter 2.5.1
 - OS type and version: WIN10
 - Using spring-boot? yes

### Declaration in ApplicationInsights.xml
```
 <ContextInitializers>
    <Add type="com.example.MyContextInitializer" />
  </ContextInitializers>
```

### Implementation of MyContextInitializer
```
 public class MyContextInitializer implements ContextInitializer {
    @Override
    public void initialize(TelemetryContext context) {
            context.getCloud().setRoleInstance("whatever");
    }
}
```

### Screenshots
<img width="447" alt="snap" src="https://user-images.githubusercontent.com/31224087/80967045-01de6c00-8e16-11ea-9e1f-5749b0559635.png">

Looks like the default Initializers are applied twice and overwrite the changes of mine.

Any Suggestion to avoid this or how to reorder to execute mine as the last one?

**Comment by trask** [comment]
In [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent) you can set the cloud role instance either via configuration file or environment variable: https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#cloud-role-instance

**Comment by the-mod** [comment]
@trask thanks for that hint. It will solve the Issue to set the Role Instance, but were you able to reproduce/investigate the order of the initializers?

**Comment by trask** [comment]
@the-mod are you still having this issue? if so, can you provide a repro that we can use to troubleshoot the issue?
