### ISSUE TITLE
Example for custom telemetry with OpenTelemetry and agent 3.0

### ISSUE THREAD

**Issue by yvespp** [microsoft/ApplicationInsights-Java#1232]
**Is your feature request related to a problem? Please describe.**
I'm trying to add custom telemetry using OpenTelemetry and agent 3.0.0-PREVIEW.4 but I can't get it to work. I can see the dependencies and requests etc. in Application Insights that are automatically created by the agent but my custom telemetry isn't showing up.

My code looks like this:
```
@Path("/")
public class TracedResource {
    Tracer tracer = OpenTelemetry.getTracerProvider().get(null);

    @GET
    @Path("/hello")
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return traceBonjour();
    }

    private String traceBonjour() {
        Span parentSpan = tracer.getCurrentSpan();
        logger.info("prentSpan: " + parentSpan);
        Span span = tracer.spanBuilder("bonjour").setParent(tracer.getCurrentSpan()).startSpan();
        String result = "";
        span.addEvent("calling bonjour");
        try (Scope scope = tracer.withSpan(span)) {
            result = exampleBean.bonjour();
        } catch (Throwable t) {
            Status status = Status.UNKNOWN.withDescription("Bonjour went wrong...");
            span.setStatus(status);
        } finally {
            span.addEvent("bonjour called");
            span.end();
        }
        return result;
    }
}
```

**Describe the solution you would like**
I would be nice to have an example/test to look at to see how to create a tracer correctly and start a new span from an exist parent span.

**Additional context**
My test app uses Quarkus.

**Comment by trask** [comment]
Hi @yvespp, what version of OpenTelemetry API are you using? Because OpenTelemetry API is still in beta, and still rapidly changing, 3.0.0-Preview.4 only supports the OpenTelemetry API version at the time of it's release, which was OpenTelemetry 0.3.0.

**Comment by yvespp** [comment]
Hi @trask, I was using OpenTelemetry 0.4.0 snapshot. I downgraded to to 0.3.0 and now it works.
Thanks!
