### ISSUE TITLE
Agent 3.0 PREVIEW.4 In Process Agent - Custom JMX Metrics with Boolean Values Not Collected

### ISSUE THREAD

**Issue by zoomingrocket** [microsoft/ApplicationInsights-Java#1235]
Using PREVIEW.4 in process java agent with custom jmx metrics configured in json for collection. JMX Metric will show in Metrics list until first time a value is set either to true or false and it will stop showing up in Application Insights

Request to either provide a mechanism to define type of jmx attribute so that a translation of boolean to numeric can be done or auto parse

**Comment by trask** [comment]
Hi @zoomingrocket do you have a single jmx metric that sometimes reports `true`/`false` and sometimes reports a numeric value? Curious what is the specific metric? Trying to think how best to capture that.

**Comment by trask** [comment]
This is supported now in [Preview.7](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.0-PREVIEW.7)
