### ISSUE TITLE
Add auto-instrumentation support for RabbitMQ (AMPQ)

### ISSUE THREAD

**Issue by zoomingrocket** [microsoft/ApplicationInsights-Java#1236]
**Is your feature request related to a problem? Please describe.**
We are monitoring complete middleware java JVM using in process agent. We noticed that calls made out from JVM over AMPQ protocol to Rabbitmq brokers were not captured automatically as dependency.

**Describe the solution you would like**
It would be good to bundle AMPQ (0-9-1, 1.0) protocol monitoring alongside Kafka & JMS.

**Describe alternatives you have considered**
RabbitMQ today exposes metrics over Prometheus if enabled or high level via HTTP API
We are looking to see how we can post this into our Application Insight instrumentation externally to establish some level of E2E visibility of transactions

**Additional context**
RabbitMQ Monitoring Options - https://www.rabbitmq.com/monitoring.html

**Comment by zoomingrocket** [comment]
@trask - Any update on when this potentially will be available in GA or beta branch :)

**Comment by trask** [comment]
hi @zoomingrocket! 

We pulled in the RabbitMQ instrumentation from upstream (in #1650).

It's opt-in preview instrumentation for now, so you'll need to enable it, either in your applicationinsights.json file:

```
{
  "preview": {
    "instrumentation": {
      "rabbitmq": {
        "enabled": true
      }
    }
  }
}
```

or using environment variable: `APPLICATIONINSIGHTS_PREVIEW_INSTRUMENTATION_RABBITMQ_ENABLED=true`

Please give the latest SNAPSHOT build a try and let us know how it works out: https://github.com/microsoft/ApplicationInsights-Java/files/6388703/applicationinsights-agent-3.0.4-BETA-SNAPSHOT.jar.zip

**Comment by zoomingrocket** [comment]
@trask - Thanks! Will give it a shot early next week and provide feedback. Appreciate the progress!

**Comment by trask** [comment]
This is released now in https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.4-BETA.2

**Comment by zoomingrocket** [comment]
@trask  - Confirming that we are able to see instrumentation for RabbitMQ and E2E correlation. Verified with v3.1.1. GA agent, sorry got to it late.

![image](https://user-images.githubusercontent.com/2420449/123120815-a18ffc80-d412-11eb-9f6f-f9b31e3f07b3.png)

Huge help, thanks for getting this feature in!
