### ISSUE TITLE
Environment variable for logging level

### ISSUE THREAD

**Issue by ravindrakmr** [microsoft/ApplicationInsights-Java#1237]
Looks like we can not set logging level external to ApplicationInsights.json file. Can we have an option to set logging level as well via some environment variable similar to connection string ? My scenario is I want different logging levels for different environments.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#application-log-capture

**Comment by trask** [comment]
[Preview.7](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.0-PREVIEW.7) now has this `APPLICATIONINSIGHTS_LOGGING_THRESHOLD` https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#application-log-capture
