### ISSUE TITLE
applicationinsights-spring-boot-starter: Don't crash when an instrumentionKey is not supplied; just run without AI

### ISSUE THREAD

**Issue by andrejpk** [microsoft/ApplicationInsights-Java#1238]
**Is your feature request related to a problem? Please describe.**
Yes: When I use the applicationinsights-spring-boot-starter package, my app can't run without an App Insights instrumentation key. This breaks my CI tests which have no use for app insights. Now in my build pipeline I need to create a dummy App Insights environment to keep my CI builds happy.

**Describe the solution you would like**
Make the azure.application-insights.instrumentation-key parameter optional. If it's not detected, maybe log a Warn message and set azure.application-insights.enabled=false and go on with your day. No need to crash the app because logging isn't on.

**Describe alternatives you have considered**
I tried setting azure.application-insights.enabled=false in the config and it still crashes because it isn't getting an instrumentation key.

**Additional context**
This is creating extra complexity where it's not needed. I had App Insights logging set up without applicationinsights-spring-boot-starter and it worked as it should -- it logged to AI when it had an ikey and didn't crash when it didn't.

**Comment by andrejpk** [comment]
One might say: just disable app insights in the config for the CI builds:
```
azure.application-insights.enabled=false
```
but it crashes anyway. Even if AI is disabled, it won't let your app run without an ikey.

**Comment by trask** [comment]
hi @andrejpk, please try 3.0 (https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent), it is tolerant to missing ikey
