### ISSUE TITLE
Unable to Send Custom Metrics during application shutdown

### ISSUE THREAD

**Issue by StevenAtMSI** [microsoft/ApplicationInsights-Java#1240]
### Expected behavior
To be able to send last minute metrics during a normal exit or user interrupt.

### Actual behavior
Generally Application Insights silently fails to send the metrics during the TransmissionNetworkOutput due to the httpClientRef in ApacheSender43 having a closed connection manager. A IllegalStateException is produced stating "Connection pool shut down".

### To Reproduce
Run Application Insights through Spring Boot add a Spring Boot @PreDestroy annotation to the method that will send metrics before shutdown. Debug breakpoints during shutdown process and watch as metric gets to TransmissionNetworkOutput and fails at line 176: "response = httpClient.sendPostRequest(request);"

### System information
Please provide the following information:
 - SDK Version: 2.6.0
 - OS type and version: Windows 10
 - Application Server type and version (if applicable):
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable):

**Comment by trask** [comment]
Hi @StevenAtMSI, 3.0 Preview supports this (it registers a shutdown hook and flushes any buffered telemetry). https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent
