### ISSUE TITLE
Duplicated HTTP dependencies reported

### ISSUE THREAD

**Issue by emmansun** [microsoft/ApplicationInsights-Java#1242]
### Expected behavior
For every http (tracked component) dependency, there should be only one AI dependency record.

### Actual behavior
There are 2 http dependency records per single http dependency. One type is HTTP and another one is Http (tracked component), both dependencies client_Browser=Apache-HttpClient 4.5

For type = HTTP, there are no resultCode, target is domain name, name is url without path. 
![image](https://user-images.githubusercontent.com/7235232/82419953-a9fc6200-9ab1-11ea-88b1-0f8c7dc63b23.png)

For type = Http (tracked component), name and target are same (in fact, the target is empty), and there are Method and URI in customDimensions.
![image](https://user-images.githubusercontent.com/7235232/82420218-052e5480-9ab2-11ea-8b3b-bfc544fc0e1d.png)

### To Reproduce
Steps to reproduce the behavior: every time.

We used RestTemplate which used apache HttpClients to perform remote call.

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: 2.4.1
 - OS type and version:deployed in PCF
 - Application Server type and version (if applicable):
 - Using spring-boot? yes
 - Additional relevant libraries (with version, if applicable):applicationinsights-agent-2.4.1

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

2020-05-20T17:43:05.933+08:00 [APP/PROC/WEB/0] [ERR] AI: WARN 20-05-2020 09:43:05.932+0000, 58(DefaultMessageListenerContainer-1): Target value is null and hence returning empty string
2020-05-20T17:43:05.933+08:00 [APP/PROC/WEB/0] [ERR] AI: TRACE 20-05-2020 09:43:05.933+0000, 58(DefaultMessageListenerContainer-1): 'org/apache/http/impl/client/InternalHttpClient.doExecute' sent an HTTP method: 'POST', uri: 'https:/xxx.com/api/documents/BookingRequest/', duration=3771 ms
2020-05-20T17:43:05.938+08:00 [APP/PROC/WEB/0] [ERR] AI: TRACE 20-05-2020 09:43:05.938+0000, 58(DefaultMessageListenerContainer-1): Sending HTTP RDD event, URL: 'https://xxx.com/api/documents/BookingRequest/', duration=3786 ms

**Comment by trask** [comment]
Hi @emmansun! I don't recall seeing this issue before. Can you try with 2.6.0 (or [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent))?

**Comment by emmansun** [comment]
Thanks @trask , i handled it via custom TelemetryProcessor first. My request is started from JMS Listener.
![image](https://user-images.githubusercontent.com/7235232/82543022-8a366e00-9b85-11ea-94c9-23a78bce55b3.png)
