### ISSUE TITLE
Configuration in ApplicationInsights.json is not in effect

### ISSUE THREAD

**Issue by gpj1** [microsoft/ApplicationInsights-Java#1244]
### Expected behavior
Configuration like rolename, logging.threshold should take effect when configured as documented in https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config

### Actual behavior
Data sent to AppInsights but roleName and loglevel is not what is given in ApplicationInsights.json.
In AppInsights, cloud rolename is AppServiceName and log level is 'trace'

### To Reproduce
Create ApplicationInsights.json file with below content and provide environment variable APPLICATIONINSIGHTS_CONFIGURATION_FILE with absolute path to this file.
Set env.variable APPLICATIONINSIGHTS_CONNECTION_STRING with instrumentation conn.string and start application with -javagent <path to applicationinsights-agent-3.0.0-PREVIEW.4.jar >

{
  "instrumentationSettings": {
    "preview": {
      "roleName": "MyAppName",
      "instrumentation": {
        "logging": {
          "threshold": "INFO"
        }
      }
    }
  }
}

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: Java codeless agent: applicationinsights-agent-3.0.0-PREVIEW.4.jar
 - OS type and version: Linux
 - Application Server type and version (if applicable): App Service In Container
 - Using spring-boot? - Yes
 - Additional relevant libraries (with version, if applicable):

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

**Comment by MS-jgol** [comment]
@gpj1 We tried to reproduce the issue on our side through the steps above, and could not. Can you please try opening a support ticket in Azure Portal?

**Comment by zoomingrocket** [comment]
Have not tried using environment variables, but definitely customized the ApplicationInsights.json default location by using JVM startup parameter as below. Environment variables becomes tricky depending upon how you are starting the service and if those variables are in effect :)

-javaagent:/d00/install.d/appinsights/applicationinsights-agent-3.0.0-PREVIEW.4.jar
-Dapplicationinsights.configurationFile=/d00/install.d/appinsights/config/ApplicationInsights.json

**Comment by ToBeKedge** [comment]
@zoomingrocket have you tried to put the agent .jar and the config .json in the same folder without using -Dapplicationinsights.configurationFile?
On our side, it's work when .jar and .json are in the same folder.

It is described [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent):

> creating a configuration file named ApplicationInsights.json, and placing it in the same directory as applicationinsights-agent-3.0.0-PREVIEW.4.jar

**Comment by gpj1** [comment]
@MS-jgol Can I create support ticket while using public preview features?

**Comment by zoomingrocket** [comment]
@ToBeKedge  - Yup, that works! But we have multiple JVM processes that we needed to monitor with different configurations so we did not want to duplicate the agent jar multiple times, only create separate ApplicationInsights.json file based on different JVM processes requirement

**Comment by MS-jgol** [comment]
> @MS-jgol Can I create support ticket while using public preview features?

@gpj1 Definitely, our public preview features are fully supported :)

**Comment by ToBeKedge** [comment]
@zoomingrocket solution is duplicated .jar and .json for each config... if you use linux, you can make a link on the .jar to keep only one version, no?

**Comment by zoomingrocket** [comment]
> @zoomingrocket solution is duplicated .jar and .json for each config... if you use linux, you can make a link on the .jar to keep only one version, no?

@ToBeKedge  Why to do that when it has out of box functionality to point to different configuration :)

**Comment by ToBeKedge** [comment]
Yes for sure! 😉
