### ISSUE TITLE
Put AI Agent 3.0 into MVN repo

### ISSUE THREAD

**Issue by MNicks** [microsoft/ApplicationInsights-Java#1251]
Even it's still in preview, do you see a change to provide AI Agent 3.0 as dependency in the official MVN repo. To download and include the JAR manually into a project is somehow cumbersome

**Comment by multicaststorm** [comment]
I agree....Also it would great to have the sources available in maven (preferably aligned to the jar classes post-shading)

**Comment by Smaranikasarla** [comment]
With the  latest AI Agent Preview Version 5, we were able to completely trace the logs on AppInsights for our Application built using Spring WebFlux. We are planning to put this in production sometime in 4th Quarter. Can you help us with an estimated timeline when the GA version would be available?

**Comment by MS-jgol** [comment]
@Smaranikasarla Wow, great to hear such a positive feedback! 
We plan to GA the Java 3.0 agent in the early November. This should work with your timeline it seems.

**Comment by Smaranikasarla** [comment]
@MS-jgol  Awesome! Yes that about the same time we are planning to go live. Thank you for that information

**Comment by MrBuddyCasino** [comment]
Now that 3.0.0 is GA, I don't see Maven Central artifacts yet?

**Comment by heyams** [comment]
It's [here](https://search.maven.org/artifact/com.microsoft.azure/applicationinsights-agent/3.0.0/jar).

    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>applicationinsights-agent</artifactId>
      <version>3.0.0</version>
    </dependency>
