### ISSUE TITLE
Issue with Java Agent 2.6.0

### ISSUE THREAD

**Issue by prat19** [microsoft/ApplicationInsights-Java#1252]
Hi,
I have setup the Java agent 2.6.0 for my Jersey Restful Web Services. After hitting some requests successfully, I get the below error.
java.lang.NoClassDefFoundError: com/microsoft/applicationinsights/internal/schemav2/ExceptionData
    com.microsoft.applicationinsights.TelemetryClient.trackException(TelemetryClient.java:279)
    com.microsoft.applicationinsights.TelemetryClient.trackException(TelemetryClient.java:292)
    com.microsoft.applicationinsights.web.internal.httputils.HttpServerHandler.handleException(HttpServerHandler.java:147)
    com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.doFilter(WebRequestTrackingFilter.java:145)

<b>root cause</b>
 <pre>java.lang.ClassNotFoundException: com.microsoft.applicationinsights.internal.schemav2.ExceptionData
    org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1702)
    org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1547)
    com.microsoft.applicationinsights.TelemetryClient.trackException(TelemetryClient.java:279)
    com.microsoft.applicationinsights.TelemetryClient.trackException(TelemetryClient.java:292)
    com.microsoft.applicationinsights.web.internal.httputils.HttpServerHandler.handleException(HttpServerHandler.java:147)
    com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.doFilter(WebRequestTrackingFilter.java:145)
</pre>

The issue is error is not consistent, sometimes we get the response and sometimes we get the above error.
Please help to fix it.

**Comment by MS-jgol** [comment]
@prat19 We recommend to switch to the Java 3.0 agent: 
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent

It looks like you are using TelemetryClient.trackException() to track the custom logs/exceptions - you can do so via log4j and the telemetry will be captured automatically. 

To configure the log capture, please follow the instructions here:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#application-log-capture

**Comment by prat19** [comment]
@MS-jgol , thank you for the solution, we are using applicationinsights-agent-3.0.0-PREVIEW.4.jar and found not errors in the last 24 hrs.
