### ISSUE TITLE
Question - pre-aggregated metrics

### ISSUE THREAD

**Issue by dylan-asos** [microsoft/ApplicationInsights-Java#1256]
The AI SDK for .Net supports multi-dimensional pre-aggregated metrics, e.g. https://github.com/microsoft/ApplicationInsights-dotnet/issues/774. 

While the Java SDK has trackMetric functionality, I couldn't find an equivalent for client metric aggregation. 

Micrometer supports this functionality and has a source for Azure Monitor (https://docs.microsoft.com/en-us/azure/azure-monitor/app/micrometer-java)  - would the general steer be to take this approach? i.e. design metrics in micrometer, let that do the pre-aggregation and push to AzMon?

**Comment by trask** [comment]
Yes, that's a good approach, I suggest you use [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent), which has built-in Micrometer support

**Comment by dylan-asos** [comment]
OK thanks @trask
