### ISSUE TITLE
Java Agent causing out-of-memory issue

### ISSUE THREAD

**Issue by shrutinar** [microsoft/ApplicationInsights-Java#1258]
### Expected behavior
We had done the integration of Adobe Experience Manager (AEM) for telemetry following the article: https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent and the logs and KMX metrics are now being written to appinsights. 
### Actual behavior
However on AEM VMs we are getting OOM issues. 
The integration was done using applicationinsights-agent-3.0.0-PREVIEW.3.jar (not applicationinsights-agent-3.0.0-PREVIEW.4.jar) which was the latest jar available about a month back. However we are running into out-of -memory issues on the AEM server and when the heap dumps were analyzed it indicated class included in the package to be accumulating memory
 
![image](https://user-images.githubusercontent.com/66740960/84289362-0528ee00-ab60-11ea-9c23-65c5cdc29fa1.png)

 
Can you please if the issue is being resolved in a recent version?

### To Reproduce
leave the AEM server running, it generates heap dumps and the serevr hangs within 24 hrs
#### Sample Application
AEM

### System information
Please provide the following information:
 - SDK Version: Java 8
 - OS type and version: Linux
 - Application Server type and version (if applicable):
 - Using spring-boot? No

_Be sure to remove any private information from the logs before posting!_

**Comment by shrutinar** [comment]
Hello Trask,
Here are the required details:

1.       PFA the complete screen shot from Heap dump memory analyzer (Heap_dump_1.png & Heap_dump_2.png) that we observed on our pre-prod server.



2.       There is only one javaagent being used, here is the command
CQ_JVM_OPTS="-server -Djava.awt.headless=true -Djava.io.tmpdir=/tmp -Xmx2g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCDateStamps -verbose:gc -XX:+PrintGCDetails -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=20M -Xloggc:/{{ install_dir }}/crx-quickstart/logs/gc.log  -javaagent:{{ app_insight_lib }}/applicationinsights-agent-3.0.0-PREVIEW.jar"


3.       With trace level, just starting the AEM server and logging into the console generated 5.5 MB of trace. I then cleared it and navigated to one folder and the trace for it are attached (applicationinsights.log)


Let me know if any other details are needed from my side.
Thanks!

Regards,
Shruti

**Comment by shrutinar** [comment]
Any update on this issue?

Regards,
Shruti

**Comment by MS-jgol** [comment]
@shrutinar We highly recommend to open a support ticket with us. Do you think you can that?

**Comment by shrutinar** [comment]
Hi,
Yes, my colleague has logged Support Request Id 120061626005899 for this.


Regards,
Shruti

**Comment by trask** [comment]
Hi @shrutinar, can you upload the `applicationinsights.log` and the heap dump to the support case? (you mentioned earlier that you had attached the log file but i don't think it worked)

**Comment by shrutinar** [comment]
Please find the appinsightslogs attached.

[applicationinsights-log.txt](https://github.com/microsoft/ApplicationInsights-Java/files/4818866/applicationinsights-log.txt)

The heap dumps are around 5GB thus not able to attach in the thread, is there any other way i can share?

Thanks!

**Comment by trask** [comment]
Hi @shrutinar, we found the memory leak! And it should be fixed in the newly released 3.0.0-PREVIEW.5: https://github.com/microsoft/ApplicationInsights-Java/releases

**Comment by shrutinar** [comment]
Thanks for the update.
