### ISSUE TITLE
Web Flux and Application Insights Spring Boot starter

### ISSUE THREAD

**Issue by johanstenberg-sj** [microsoft/ApplicationInsights-Java#1261]
Hi,

Is Web Flux still not supported by Application Insights Spring Boot starter?
If so it would make an excellent candidate for a new feature request.

BR

Johan

**Comment by MS-jgol** [comment]
@johanstenberg-sj Check out the Application Insights Java 3.0 - https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent
WebFlux is supported in that version
