### ISSUE TITLE
OpenTelemetry exporter build?

### ISSUE THREAD

**Issue by knutwannheden** [microsoft/ApplicationInsights-Java#1266]
We are currently using a custom implementation of the OpenTracing SPI to send our tracing data to Application Insights (the implementation is based on the Application Insights SDK 2.6.1) from a Quarkus application. Our plan is to move to OpenTelemetry as soon as it is supported by Quarkus.

Since Quarkus also supports native image generation (using GraalVM) auto-instrumentation using a Java agent won't be possible and a "deep integration" with Quarkus will be required. I would like to know if use cases like this one are on the radar and if builds (i.e. Maven artifacts) will be provided, which cater for this use case. I imagine there would be a build which provides an exporter only.

**Comment by trask** [comment]
Just wanted to post an update that we are planning to do this, probably sometime in the next few months.

**Comment by DominiqueClaes** [comment]
Is there any update on this?

**Comment by trask** [comment]
hi @DominiqueClaes!

Work on this has picked back up recently. We have split out a standalone component that contains trace, metrics and log exporters (https://github.com/microsoft/ApplicationInsights-Java/tree/main/agent/azure-monitor-exporter) and are planning to publish those.

There's also #2125 if you want auto-instrumentation and have control of your `public static void main(String[])` method, but are not able to use `-javaagent` on your command-line.

**Comment by trask** [comment]
Closing, you can now use the Java agent's underlying OpenTelemetry exporters directly: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/monitor/azure-monitor-opentelemetry-exporter/README.md

**Comment by jeanbisutti** [comment]
@knutwannheden  @DominiqueClaes For GraalVM native, you can now use the Quarkus Azure exporter: https://docs.quarkiverse.io/quarkus-opentelemetry-exporter/dev/quarkus-opentelemetry-exporter-azure.html
