### ISSUE TITLE
MockMvc-based tests fail with App Insights enabled

### ISSUE THREAD

**Issue by andrejpk** [microsoft/ApplicationInsights-Java#1281]
This the same issue as #895 . I was able to implement the recommended solution to do a test setup that stubbed out the App Insights initialization but this isn't a great solution for my project. 

Our approach is to build our APIs so we can enable App Insights through configuration where/as needed (by adding it in via our pom.xml), so we are trying to limit our app code to the Spring logging and instrumentation stack (SLF4J, Micrometer). This is working except in this case I need to add App Insights code to my tests need AI-specific code to work around this issue, breaking our approach.

Is it possible to put a null check [before in this line](https://github.com/microsoft/ApplicationInsights-Java/blob/master/web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java#L131) to avoid this issue entirely? That would avoid going through the extra plumbing to avoid this issue in my tests.

I'm happy to make a PR on this if the team agrees with this approach. 

The other approach would be a simple way to disable App Insights when running under test, but I don't see a way to do that.

**Comment by littleaj** [comment]
@andrejpk, That makes sense to me. A PR would be great. You could combine the null check as the first part of the conditional on [Line 120](https://github.com/microsoft/ApplicationInsights-Java/blob/4a8eba2eee5ce073089e803a55a9c6ddb96b54f8/web/src/main/java/com/microsoft/applicationinsights/web/internal/WebRequestTrackingFilter.java#L120). Whatever you choose, just make sure `chain.doFilter(req, res)` is still called.

**Comment by andrejpk** [comment]
Hi @littleaj .. I'm back at the office this week and forked the repo to make this change and test it. When I try ```gradle test``` on master, I get a few failed tests:
- WebOperationIdTelemetryInitializerTests. testRequestTelemetryInitializedWithOperationId
- WebOperationNameTelemetryInitializerTests. testRequestTelemetryInitializedWithOperationName
- WebRequestTrackingTelemetryModuleTests. testHttpRequestTrackedSuccessfully
- WebRequestTrackingTelemetryModuleTests. testUserAgentIsBeingSet
- WebSessionTrackingTelemetryModuleTests. testWhenCookieExistCorrectSessionIdAttachedToSentTelemetry
- WebUserTrackingTelemetryModuleTests. testWhenCookieExistCorrectUserIdAttachedToSentTelemetry

I see the build passing badge on the README but it doesn't link to any details to compare my results and the CI. I haven't made any changes yet but want to start in a good state before I do. Am I missing something here?

**Comment by littleaj** [comment]
@andrejpk, that's interesting. The test reports are in `web/build/reports/tests/test/index.html` or you can run `gradlew test --info` to print the stdout/stderr during tests to the console. If you're not already, I would run with JDK 8.

**Comment by andrejpk** [comment]
Hi  @littleaj .. Java 11->8 helped, also had some state that needed a ```gradlew clean``` but I'm good now. Thanks for your help.

**Comment by andrejpk** [comment]
Hi @littleaj , I think the PR on this issue is ready. Please let me know if I need to do anything on the CHANGELOG related to this (I wasn't sure how to mark the version in the PR).
