### ISSUE TITLE
APPINSIGHTS_INSTRUMENTATIONKEY gets overriden by Environment variable over System Property

### ISSUE THREAD

**Issue by rohimsh** [microsoft/ApplicationInsights-Java#1288]
### Expected behavior
Hey Team, first of all, great work! 
As an avid user of App Insights with Spring Boot, I faced an issue which is described below :- 

It's mentioned [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-get-started?tabs=maven#alternative-ways-to-set-the-instrumentation-key) that the order of precedence being followed for `APPINSIGHTS_INSTRUMENTATIONKEY` is 

```
Application Insights SDK looks for the key in this order:

System property: -DAPPINSIGHTS_INSTRUMENTATIONKEY=your_ikey
Environment variable: APPINSIGHTS_INSTRUMENTATIONKEY
Configuration file: ApplicationInsights.xml
```

### Actual behavior
Although, in my case the key specified in System property was being overriden with the one in Environment variable.

### To Reproduce
1. Set an environment variable with key `APPINSIGHTS_INSTRUMENTATIONKEY` let's say value was "00000000-0000-0000-0000-000000000000"
2. Set a System property while running the Spring Boot Jar as `-DAPPINSIGHTS_INSTRUMENTATIONKEY=11111111-1111-1111-1111-111111111111`
3. On running you'll see that the TelemetryConfiguration sets the instrumentation Key as "11111111-1111-1111-1111-111111111111" but then it gets overriden as "00000000-0000-0000-0000-000000000000"

### Reason
In class TelemetryConfigurationFactory [here](https://github.com/microsoft/ApplicationInsights-Java/blob/58b944e8dcd977a867314a0c22795e61af65a7f4/core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java#L292) you'll see that the order being followed for fetching `APPINSIGHTS_INSTRUMENTATIONKEY` is in inline with the expectations and as per doc:

```
private void setInstrumentationKey(ApplicationInsightsXmlConfiguration userConfiguration, TelemetryConfiguration 
 configuration) {
        try {
            String ikey = System.getProperty("APPLICATION_INSIGHTS_IKEY");
            if (!Strings.isNullOrEmpty(ikey)) {
                configuration.setInstrumentationKey(ikey);
                return;
            }

            ikey = System.getProperty("APPINSIGHTS_INSTRUMENTATIONKEY");
            if (!Strings.isNullOrEmpty(ikey)) {
                configuration.setInstrumentationKey(ikey);
                return;
            }

            ikey = System.getenv("APPLICATION_INSIGHTS_IKEY");
            if (!Strings.isNullOrEmpty(ikey)) {
                configuration.setInstrumentationKey(ikey);
                return;
            }

            ikey = System.getenv("APPINSIGHTS_INSTRUMENTATIONKEY");
            if (!Strings.isNullOrEmpty(ikey)) {
                configuration.setInstrumentationKey(ikey);
                return;
            }

            if (userConfiguration != null) {
                ikey = userConfiguration.getInstrumentationKey();
                if (ikey == null) {
                    return;
                }

                ikey = ikey.trim();
                if (ikey.length() == 0) {
                    return;
                }

                configuration.setInstrumentationKey(ikey);
            }
        } catch (Exception var4) {
            InternalLogger.INSTANCE.error("Failed to set instrumentation key: '%s'", new Object[]{var4.toString()});
        }

    }
```

But, in class IkeyResolver [here](https://github.com/microsoft/ApplicationInsights-Java/blob/aabde3dcc6c8584d7913a63999d4a0c437c3b2bf/azure-application-insights-spring-boot-starter/src/main/java/com/microsoft/applicationinsights/autoconfigure/helpers/IkeyResolver.java#L36
) you'll see that the order being followed is different :- 

``` 
public static String getIkeyFromEnvironmentVariables() {
        String v = System.getenv("APPLICATION_INSIGHTS_IKEY");
        if (StringUtils.isNotBlank(v)) {
            return v;
        } else {
            v = System.getenv("APPINSIGHTS_INSTRUMENTATIONKEY");
            if (StringUtils.isNotBlank(v)) {
                return v;
            } else {
                v = System.getProperty("APPLICATION_INSIGHTS_IKEY");
                if (StringUtils.isNotBlank(v)) {
                    return v;
                } else {
                    v = System.getProperty("APPINSIGHTS_INSTRUMENTATIONKEY");
                    return StringUtils.isNotBlank(v) ? v : v;
                }
            }
        }
    }
}
```

and that's what causes this issue. 
On the first time when TelemetryConfigurationFactory is setting the key it's looking for the correct sequence but then shortly 
TelemetryConfiguration's setInstrumentationKey method is called with the key being passed as the one fetched from IkeyResolver, thus overriding the originally expected value. 

### System information
Please provide the following information:
 - SDK Version: 2.6.1
 - OS type and version: MACOS 10.15.5 (19F101)
 - Application Server type and version (if applicable):
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable): https://github.com/microsoft/ApplicationInsights-Java/releases/download/2.6.1/applicationinsights-agent-2.6.1.jar

**Comment by MS-jgol** [comment]
@rohimsh 
We strongly recommend to go with the Java 3.0 agent instead of the SDK:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent

Can you please take a look and let us know what you think?

**Comment by rohimsh** [comment]
Hey @MS-jgol , thank you for your reply. I checked the documentation link above, but unfortunately have an issue with the way the new design forces us to configure key. 
My use case is I have two different Spring Boot processes running inside same container; in the present state I specify two different AI key in their separate `application.yaml` files like:
```
azure:
  application-insights:
    instrumentation-key: ${XYZ_APPINSIGHTS_INSTRUMENTATIONKEY}
```
Thus, even though they both use the Agent JAR from the same folder they can still send their metrics to two separate instances of Application Insights. 
In the proposed 3.0.0.PREVIEW the design makes it a global environment variable and hence my two processes can not use two separate AI keys. 
As a workaround, probably I can copy the preview JAR in two separate folders and then use them in my different processes but I'm sure you'd understand copying the same JAR twice which is of 13+MBs is not a great thought.

**Comment by MS-jgol** [comment]
@rohimsh If the purpose is to differentiate the two instances running in the same container, you could specify different cloud role names:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#cloud-role-name

Will this work for you?

**Comment by rohimsh** [comment]
Hey @MS-jgol , its working by using two different Env variables and setting them up in YAML as below :- 
```
azure:
  application-insights:
    instrumentation-key: ${XYZ_APPINSIGHTS_INSTRUMENTATIONKEY}
```
and, 
```
azure:
  application-insights:
    instrumentation-key: ${ABC_APPINSIGHTS_INSTRUMENTATIONKEY}
```
Their cloud names were different because it defaults to the Spring Application name anyway. 
Thank you for your help, closing this now.
