### ISSUE TITLE
Unable to distinguish between applications running with same javaagent in Application Map

### ISSUE THREAD

**Issue by simoneby** [microsoft/ApplicationInsights-Java#1289]
### Expected behavior
I expected the agent to detect the different applications running on the same server and detect the role names given in application.properties. 

### Actual behavior
The applications gets bundeled into one instance and the calls between them are visualised as an application calling itself 

### System information
Please provide the following information:
 - SDK Version: 2.5.0 and applicaitoninsights-agent-3.0.0-PREVIEW.5.jar
 - OS type and version: Ubuntu 18
 - Application Server type and version (if applicable): Tomcat(?)
 - Using spring-boot? yes
 - Additional relevant libraries (with version, if applicable):

Alternatively I can have dupicated directories where the "Role name" in the ApplicationInsights.json file is different, but this seems like a poor solution. 

Illustration of problem:
![image](https://user-images.githubusercontent.com/16305584/88269757-e9734480-ccd4-11ea-9687-4d6a13861dbc.png)

**Comment by MS-jgol** [comment]
@simoneby 
If cloud role name is not set, the Application Insights resource's name will be used to label the component on the application map.

Here is how you can set the cloud role name and cloud role instance:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#cloud-role-name

Does this solve the issue?

**Comment by simoneby** [comment]
@MS-jgol it does not solve the issue, im using the same key for both applications but would like to distinguish them. I don't know if this is possible, but I think it should be. When using only the sdk's I get the representation I want in the AppMap but no HTTP tracking(no arrows between the circles), but when I use the agent I can't distinguish the applications from each other as they get bundled under the same name. Either the name defined in the ApplicationInsights.json file or the Application Insights resource name. 

It is fixable by having multiple agent folders which hold both the .jar file and different .json files, but I don't think that's an optimal solution and I hope there is a more elegant way of achieving what I want. This might also not be possible in the actual enviornment I want to monitor with the application map.

**Comment by MS-jgol** [comment]
@simoneby 
You can also set the cloud role name using the environment variable APPLICATIONINSIGHTS_ROLE_NAME.
Can you try this - set two different cloud role names for the two of your apps running on the same server?

Please let me know how it goes!

**Comment by simoneby** [comment]
@MS-jgol problem was that I started the applications seperately instead of both at once using the same agent instance.
