### ISSUE TITLE
Illegal reflective access

### ISSUE THREAD

**Issue by EwanNoble** [microsoft/ApplicationInsights-Java#1291]
### Expected behavior
No warnings when running `mvn package` (using azure-functions-maven-plugin:1.6.0 which depends on `applicationinsights-core:2.6.1`)

### Actual behavior
```WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.microsoft.applicationinsights.core.dependencies.xstream.core.util.Fields (file:/C:/Users/me/.m2/repository/com/microsoft/azure/applicationinsights-core/2.6.1/applicationinsights-core-2.6.1.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.microsoft.applicationinsights.core.dependencies.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

### To Reproduce
Run `mvn package` with `azure-functions-maven-plugin:1.6.0`

### System information
Please provide the following information:
 - SDK Version: `applicationinsights-core:2.6.1`
 - OS type and version: Windows 10.0.19559 Build 19559

**Comment by MS-jgol** [comment]
@EwanNoble 
Can you please try the new Java 3.0 agent - https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent
Just a few simple steps to enable.

Configuration options are here:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config

**Comment by noce2** [comment]
Hello @MS-jgol , the steps you linked don't seem to solve the problem. I am using azure-functions-maven-plugin:1.9.0 and despite downloading the jar etc, I still get this error. Are we supposed to remove the use of the plugin altogether?

**Comment by trask** [comment]
hi @noce2, can you post a small repro of the issue that we can use to see exactly what's going on?

**Comment by pkunk** [comment]
Created a new issue with link to a repro example: https://github.com/microsoft/ApplicationInsights-Java/issues/1446
