### ISSUE TITLE
Not all records in dependencies table have corresponding "parent" records in requests table

### ISSUE THREAD

**Issue by blyakhmanv** [microsoft/ApplicationInsights-Java#1292]
### Expected behavior
If I get operation_Id of any record in dependencies table I expect to find "parent" call in requests table with the same operation-Id

### Actual behavior
I can find parent requests for dependency calls to MySQL  but I can't find parent calls for dependency calls to Kafka and also for some HTTP calls. 

### To Reproduce
It is reproducible on my Java app. i can't provide the code. 

#### Sample Application
Can't provide

### System information
Please provide the following information:
 - SDK Version: java:3.0.0-PREVIEW.5
 - OS type and version: CentOS Linux 7 (Core), application is packed in openjdk 11.0.8 2020-07-14 docker container
 - Application Server type and version (if applicable):
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable):

### Logs
There is no logs enabled at the moment

**Comment by MS-jgol** [comment]
@blyakhmanv Can you please open a support ticket for this issue from Azure Portal?

**Comment by trask** [comment]
Closing. If you are able to provide a standalone repro that would be great, then we can look into it further.
