### ISSUE TITLE
Unused Field

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [microsoft/ApplicationInsights-Java#1295]
https://github.com/microsoft/ApplicationInsights-Java/blob/aabde3dcc6c8584d7913a63999d4a0c437c3b2bf/core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/PerformanceCounterData.java#L40
https://github.com/microsoft/ApplicationInsights-Java/blob/aabde3dcc6c8584d7913a63999d4a0c437c3b2bf/core/src/main/java/com/microsoft/applicationinsights/internal/schemav2/PerformanceCounterData.java#L45

This field is never used

**Comment by MS-jgol** [comment]
@QiAnXinCodeSafe
Do you experience any issues associated with the reported field that is not used?

**Comment by trask** [comment]
Closing, we will be replacing this model with https://github.com/Azure/azure-sdk-for-java/pull/15429, probably sometime in the next few months.
