### ISSUE TITLE
Enable INFO log capture in Azure Functions

### ISSUE THREAD

**Issue by casper-79** [microsoft/ApplicationInsights-Java#1300]
### Expected behavior
I have enabled distributed tracing for my Java based function app, by adding two application settings as described [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/monitor-functions). I then expect all logging from my application to be part of end-to-end transactions. Example: When i drill into specific samples from the AI application map and choose to view all telemetry for a given sample, I expect to find all logging made by my application.  

### Actual behavior
When i drill into specific samples from the AI application map and choose to view all telemetry for a given sample, I only find logging from the Azure services themselves and logging done using the context logger. Logging done using log4j2/logback can be found on AI when I search for it, but it is NOT integrated in end-to-end transactions. If log4j2/logback is not supported for distributed tracing, it should be stated clearly in the documentation. We have spent a lot of time trying to get this to work, but I am starting to think it just might not be supported.

### To Reproduce
Create java function app v3, enable application insights, deploy code that does logging with logback or log4j, enable distributed tracing as described here https://docs.microsoft.com/en-us/azure/azure-monitor/app/monitor-functions). Execute a function that writes to the log and verify how you can find logback/log4j logging by searching, but it is not part of end-to-end transactions.

#### Sample Application
-

### System information
Please provide the following information:
 - SDK Version: Application insights codeless attach (auto instrumentation), azure-functions-java-library 1.3.1
 - OS type and version: Java Azure functions v3 on consumption plan (Windows).
 - Application Server type and version (if applicable): Not applicable
 - Using spring-boot? Not using Spring.

### Logs
Not relevant

### Screenshots
Not relevant

**Comment by trask** [comment]
Hi @casper-79, it should be capturing WARN and ERROR level log messages. We are planning to start capturing INFO level messages soon as well. Can you confirm if this matches what you are seeing, or maybe there's some other issue. Thanks!

**Comment by casper-79** [comment]
Hi @trask 

Do you have an update on this issue?

Thanks!

Casper

**Comment by MS-jgol** [comment]
@casper-79 
End of September release will cover that, stay tuned :)

**Comment by trask** [comment]
> As a side note - do you make any general assumptions about the message pattern and what each log message contain? During a stage in my experimentation I had AI turn every message into INFORMATION and I suspect it might have been caused by my output message pattern not containing log level at the time ...?

Hey @casper-79, sorry, missed this question, we instrument log4j, logback and java.util.logging, and we capture the logging level that was passed to the logging framework, not sure if that answers your question?

**Comment by Sherkdavid** [comment]
@trask should this issue be confined to Azure Functions only? We're using the applicationinsights-agent-3.0.0-PREVIEW.6.jar for a java application server and are also seeing only WARN and above events ingested in AppInsights, with sdkVersion java:3.0.0. When we remove the 3.0.0 javaagent JVM arg from our application, INFO events are ingested with sdkVersion java:2.6.1.
We had already been successfully using 2.6.1 log4j ApplicationInsightsAppender for logging prior but when trying to gather server performance metrics using that version we hit issue https://github.com/microsoft/ApplicationInsights-Java/issues/1170 and tried the 3.0.0-PREVIEW upgrade recommended.

Our experience of this is that 2.6.1 works for logging ingest, 3.0.0 works for performance ingest and the two appear to be mutually exclusive. My understanding from https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#upgrading-from-application-insights-java-sdk-2x is that these versions should work compatibly?

**Comment by heyams** [comment]
@Sherkdavid Please use our latest version [PREVIEW.7](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.0-PREVIEW.7).  We change the log capture level to INFO by default.  It was released two weeks ago.

**Comment by trask** [comment]
👍 you can also configure the level you want to capture in 3.0 https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#application-log-capture

**Comment by trask** [comment]
Closing, please let us know if you are still having this issue
