### ISSUE TITLE
Update OpenTelemetry to v0.7.1

### ISSUE THREAD

**Issue by arjun-1** [microsoft/ApplicationInsights-Java#1302]
The java agent is now build against version 0.5.0 of OpenTelemetry.

While some users using the agent can simply use that corresponding version of OpenTelemetry in their project, some users use a wrapping library around OpenTelemetry, which is build not against version 0.5.0 (but version 0.7.1 in my case).

Upgrading would make the java agent usable in one of my projects :pray:

**Comment by trask** [comment]
Updated to otel 0.8.0 in [Preview.7](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.0-PREVIEW.7)
