### ISSUE TITLE
Deploying application insight java agent on azure Web app.

### ISSUE THREAD

**Issue by junpark12** [microsoft/ApplicationInsights-Java#1304]
### Environment.
I tried to deploy containerized java app to azure web app.
here's part of pom.xml file.

`<plugin>
        
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.1.1</version>
        <executions>
          <execution>
            <id>copy</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>copy</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <artifactItems>
            <artifactItem>
              <groupId>com.microsoft.azure</groupId>
              <artifactId>applicationinsights-agent</artifactId>
              <version>2.6.1</version>
            </artifactItem>
          </artifactItems>
        </configuration>
      </plugin>
      <plugin>
        
        <artifactId>maven-war-plugin</artifactId>
        <version>3.2.3</version>
        <configuration>
          <webResources>
            <resource>
              <directory>${project.build.directory}/dependency</directory>
              <targetPath>WEB-INF</targetPath>
            </resource>
          </webResources>
        </configuration>
      </plugin>`

I put AI-Agent.xml file under WEB-INF folder.
![image](https://user-images.githubusercontent.com/20918194/91154139-18c60880-e6fc-11ea-84ae-85f190987e12.png)

and here's dockerfile.
`FROM tomcat:9-jre8-alpine

RUN apk --update add curl ca-certificates tar 
RUN set -x \
    && mkdir /home/mysql \
    && curl -fSL https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.40.tar.gz -o /home/mysql/mysql-connector.jar \
    && cd /home/mysql \
    && tar -xzvf mysql-connector.jar \
    && pwd \
    && mkdir -p /usr/share/java \
    && mv /home/mysql/mysql-connector-java-5.1.40/mysql-connector-java-5.1.40-bin.jar /usr/share/java/mysql-connector-java.jar \
    && cd /home \
    && rm -R *

RUN export CLASSPATH=$CLASSPATH:/usr/share/java/mysql-connector-java.jar

ADD ./target/myshuttledev.war /usr/local/tomcat/webapps/myshuttledev.war`

I created Linux & container based azure web app and configured web app's configuration setting using the following.

"For Azure App Services, do the following:
* Select Settings > Application Settings
* Under App Settings, add a new key value pair:
Key: JAVA_OPTS Value: -javaagent:D:/home/site/wwwroot/applicationinsights-agent-2.5.0.jar"
In my case agent path was "/home/site/wwwroot/webapps/ROOT/WEB-INF/applicationinsights-agent-2.6.1.jar".
But when i tried to start my web app, i received the following exception.
2020-08-25T08:12:58.405014190Z Error opening zip file or JAR manifest missing : /home/site/wwwroot/webapps/ROOT/WEB-INF/applicationinsights-agent-2.6.1.jar

After then, I run the container in my local environment. When i attached to that container, I see the agent's full path was "/usr/local/tomcat/webapps/myshuttledev/WEB-INF/applicationinsights-agent-2.6.1.jar". 
I changed agent path in web app configuration, but I received the same error.
So what is the right path to start the agent?
Thanks.

### Logs
2020-08-25T08:12:58.405014190Z Error opening zip file or JAR manifest missing : /home/site/wwwroot/webapps/ROOT/WEB-INF/applicationinsights-agent-2.6.1.jar
2020-08-25T08:12:58.405093292Z Error occurred during initialization of VM
2020-08-25T08:12:58.405220497Z agent library failed to init: instrument

2020-08-25T08:18:28.833089385Z Error opening zip file or JAR manifest missing : /usr/local/tomcat/webapps/myshuttledev/WEB-INF/applicationinsights-agent-2.6.1.jar
2020-08-25T08:18:28.833664303Z Error occurred during initialization of VM
2020-08-25T08:18:28.834646235Z agent library failed to init: instrument

2020-08-25T08:24:51.492824088Z Error opening zip file or JAR manifest missing : /usr/local/tomcat/webapps/myshuttledev/WEB-INF/applicationinsights-agent-2.6.1.jar
2020-08-25T08:24:51.492903991Z Error occurred during initialization of VM
2020-08-25T08:24:51.493016095Z agent library failed to init: instrument

_Be sure to remove any private information from the logs before posting!_

**Comment by MS-jgol** [comment]
@junpark12 
Can you please try to use Application Insights Java3.0 instead? 

https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent

**Comment by trask** [comment]
Closing, please let us know if you are still having this issue
