### ISSUE TITLE
Spring Boot (Stateless) log4j2 logs are missing user id and session id values

### ISSUE THREAD

**Issue by sudheeranguluri** [microsoft/ApplicationInsights-Java#1309]
### Description
We have enabled Application Insights for our spring boot application and implemented the following
1. AI Appender for log4j xml file (Existing app)
2. Custom metrics
3. Custom event
4. Custom dependency

I have also set following in securityFilter
**telemetryClient.getContext().getUser().setId(request.getHeader(AppConstants.HDR_USER_ID));**

Our application has no frontend and consists of just microservices without any session maintenance

### Issue
All the events are properly getting pushed application insights. But only custom pushes (2,3,4 above) above has userId attribute set in query results column. Logs that are pushed using AIAppender has no userId value.

How to get log4j events pushed to application insights to have userId header set?

### System information
Please provide the following information:
 - SDK Version: Java 8
 - OS type and version: Windows
 - Application Server type and version (if applicable): Tomcat
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable):

_Be sure to remove any private information from the logs before posting!_

### Screenshots

Custom Events - UserId present

![image](https://user-images.githubusercontent.com/29436986/92164843-05a1ef80-ee04-11ea-998b-a93cc8b929b9.png)

Log4j traces (Pushed using AIAppender) - UserID Not present

![image](https://user-images.githubusercontent.com/29436986/92164980-4d287b80-ee04-11ea-88eb-019a13a6f3b5.png)

**Comment by MS-jgol** [comment]
@sudheeranguluri Would you be able to open a support ticket for the issue?

**Comment by sudheeranguluri** [comment]
@MS-jgol 
I am only seeing Bug Report and Feature Request as options. Should I click on "Open a blank issue." link?

**Comment by MS-jgol** [comment]
@sudheeranguluri 
I was responding yesterday but did not hit the 'comment' button. :) 
Can you log in to portal.azure.com and open a ticket from there (instructions in the image attached)?

![image](https://user-images.githubusercontent.com/52080200/92175747-06318a80-edf2-11ea-8888-e761349d472e.png)

**Comment by sudheeranguluri** [comment]
@MS-jgol  I will have to escalate this to our management. Not sure if it is going to be easy task. is there a way someone can look at issue description and point what is wrong? If not, please feel free to close the bug.

Thanks

**Comment by MS-jgol** [comment]
@sudheeranguluri I see... Let me get back to this, hopefully next week, I will see what I can do.

**Comment by MS-jgol** [comment]
@sudheeranguluri 
Question: you are using the Java SKD 2.6, correct?
Can you add the Java 3.0 agent - it will still collect the customer telemetry you are emitting, but has additional benefits such as aotucollecting log4j logs 
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent

**Comment by trask** [comment]
Hi @sudheeranguluri,

> I have also set following in securityFilter
telemetryClient.getContext().getUser().setId(request.getHeader(AppConstants.HDR_USER_ID));

This code `telemetryClient.getContext().getUser().setId(..)` is updating the user on the global context each time, which will lead to unpredictable results under concurrent requests.

> How to get log4j events pushed to application insights to have userId header set?

With 3.0, you can set MDC properties and those will be added to the automatically captured logs (https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#send-custom-traces-and-exceptions-using-your-favorite-logging-framework).

**Comment by sudheeranguluri** [comment]
Thanks @trask and @MS-jgol for looking into this. I will use 3.0 as suggested.
