### ISSUE TITLE
Unable to see telemetry data for requests from Dropwizard java application

### ISSUE THREAD

**Issue by Tylerremmie** [microsoft/ApplicationInsights-Java#1310]
I am trying to integrate the 2.6.1 applicationinsights-web-auto sdk along with the 2.6.1 javaagent into our rest api using the Dropwizard framework and I followed the instructions from [Quickstart: Get started with Application Insights in a Java web project](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-get-started?tabs=gradle) and am still struggling to get it working. 

I noticed there was a similar issue [reported last October ](https://github.com/microsoft/ApplicationInsights-Java/issues/1092) that mentioned this problem and seemed to be resolved with using the applicationinsights-web sdk and manually registering WebRequestTrackingFilter. Do you have any advice or documentation for accomplishing this manual filter registration for a java application?

On a side note, I did try using the applicationinsights-agent-3.0.0-PREVIEW and that seemed to work flawlessly. Do you have any dates or road map for when this is expected to enter full release?

**Comment by MS-jgol** [comment]
I strongly suggest that you go with Java 3.0, the GA is just around the corner, first week of November. The 3.0 version is fully supported and used by many customers in production already.

**Comment by Tylerremmie** [comment]
That is great news, I will definitely go that route then. Thanks!
