### ISSUE TITLE
Apache HttpAsyncClient calls not tracked

### ISSUE THREAD

**Issue by pbloigu** [microsoft/ApplicationInsights-Java#1321]
### Expected behavior
As per the [documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#autocollected-requests-dependencies-logs-and-metrics) dependency calls made with Apache HttpAsyncClient should be tracked.

### Actual behavior
I do not see calls made with Apache HttpAsyncClient in Insights.

### To Reproduce
Spring Boot application with an instance of ElasticsearchRestTemplate as a bean. Calls made via the template are not tracked. It seems to use Apache HttpAsyncClient internally. Calls made through Spring WebClient (i.e. WebFlux) do seem to be tracked.

### System information
Please provide the following information:
 - SDK Version: Agent version 3.0.0-PREVIEW-5
 - OS type and version: Windows 10
 - Using spring-boot? Yes, Spring Boot version 2.1.13.RELEASE, applicationinsights-spring-boot-starter version 2.6.1

**Comment by pbloigu** [comment]
I managed to enable the agent logging. This is what gets printed in the log:
```
AI: TRACE 21-09-2020 10:34:15.435+0000, 23(restartedMain): agent not found
AI: INFO 21-09-2020 10:34:15.435+0000, 23(restartedMain): Agent is not running
```
However, JDBC calls to the database are traced and as well as WebClient calls.

**Comment by trask** [comment]
Hi @pbloigu, thanks for reporting this! I was able to reproduce and this should be fixed in Preview.7 which we are targeting for end of this week.

**Comment by pbloigu** [comment]
> Hi @pbloigu, thanks for reporting this! I was able to reproduce and this should be fixed in Preview.7 which we are targeting for end of this week.

Excellent! Thanks for the quick response! 🙏

**Comment by pbloigu** [comment]
I can confirm this now being fixed in PREVIEW.7. I can see ES queries made with ElasticsearchRestTemplate in Insights. Thank you!
