### ISSUE TITLE
Datetime format for TimeStamp in AppInsights custom properties

### ISSUE THREAD

**Issue by Harisyam** [microsoft/ApplicationInsights-Java#1322]
I am trying to change the datetime format for TimeStamp in AppInsights custom properties from a Java spring boot application. 
In the application's `logback-spring.xml` file I am using `ApplicationInsightsAppender` for application logs to be captured in ApplicationInsights and `TelemetryClient` for the custom logs to ApplicationInsights 

```xml
<appender name="aiAppender" class="com.microsoft.applicationinsights.logback.ApplicationInsightsAppender">
```

below is the code for application logs and these logs get automatically logged in ApplicationInsights since I am using `ApplicationInsightsAppender`

```
LOGGER.info("Reading the values");
```

To change the date time format of the TimeStamp, just before calling the Logger I need to put the timestamp into MDC just like below code, So that it will replace the default TimeStamp logged by ApplicationInsight with the custom one

```
MDC.put("TimeStamp", formatDate(Instant.now(), "yyyy-MM-dd'T'HH:mm:ss.SSSZ"));
LOGGER.info("Reading the values")
```
		
But there are many places where `LOGGER.info();`, `LOGGER.error();` methods are called.

Is there any other way I can achieve this by simple change, So that I don't have to go and add this custom TimeStamp property to MDC everywhere in the code?

**Comment by trask** [comment]
Hi @Harisyam! The AI appender sends the timestamp to Azure Portal as a date value, not as text. Can you explain a bit more what you are trying to do here?

**Comment by Harisyam** [comment]
Hi @trask ,

I want a consistent timestamp format across all the logs and App Insights.

I am trying to change the datetimeformat of TimeStamp to "yyyy-MM-dd'T'HH:mm:ss.SSSZ"  format.
Since AI appender sends the timestamp as date value I am adding an MDC property with same name TimeStamp and adding a string value to it, using below code
`MDC.put("TimeStamp",  "2020-09-11T07:03:32.2160000Z"));`

Then calling the `LOGGER.info()` method. So that it is changing the TimeStamp format to "yyyy-MM-dd'T'HH:mm:ss.SSSZ".

But this requires lot of effort in changing everywhere in the code where logger is called.

Is there any other simple way to change the format of TimeStamp?

**Comment by trask** [comment]
Where do you see the timestamp in Application Insights? Do you mean in the Azure Portal UI? Or in some log file somewhere?

**Comment by Harisyam** [comment]
@trask , In the Azure Portal UI.

**Comment by trask** [comment]
Can you attach a screenshot?

**Comment by Harisyam** [comment]
![image](https://user-images.githubusercontent.com/8931722/93849578-0ffc2e80-fcca-11ea-91bf-0db36401229c.png)

**Comment by trask** [comment]
Hi @Harisyam, I understand now, thank you. This property seems unnecessary since the telemetry already has a real timestamp (which you can format as you wish in the Portal UI), so we will plan to remove the unnecessary (formatted) timestamp.

**Comment by Harisyam** [comment]
Hi @trask ,

If I don't want to change the format through portal and always wanted my application to log in a specific format how can I achieve this?

**Comment by trask** [comment]
Hi @Harisyam, as we discussed on Teams, other telemetry doesn't have this "formatted date" field. Only trace telemetry (incorrectly) has it, which is why we are removing it. You should be able to format regular dates across all telemetry as needed in the Portal U/X.

**Comment by Harisyam** [comment]
Hi @trask,

Thank you for the update.

When we use the Kusto query I can format the date now.

Actually we are not using any UI to look at log Instead these logs will be exported to different system and we need to ensure before exporting the datetime format is in the format given by customer

**Comment by trask** [comment]
Hey @Harisyam, I'm not clear if this means your issue is resolved or not?
