### ISSUE TITLE
Future plans on SDK

### ISSUE THREAD

**Issue by dicody** [microsoft/ApplicationInsights-Java#1326]
Dear Team,

Can you please share your future plans on SKD development, particularly on 'Spring Boot starter' support. As I understood you plan to focus only on 'codeless' solution (Java agent) and leave behind projects, like: [App Insights Spring Boot starter](https://github.com/microsoft/ApplicationInsights-Java/tree/master/azure-application-insights-spring-boot-starter) or this impression is wrong? 

Best Regards,
Dmitry

**Comment by trask** [comment]
Hi @dicody! Yes, we are focusing our effort on the codeless onboarding path (which supports spring boot projects as well).

**Comment by dicody** [comment]
Hi @trask , thanks for the quick answer. Just to clarify, there are no plans to continue development (e.g. release v3) on 'applicationinsights-spring-boot-starter' project? I mean:


<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>applicationinsights-spring-boot-starter</artifactId>
    <version>2.6.2</version>
</dependency>

Best Regards,
Dmitry

**Comment by MS-jgol** [comment]
@dicody At the moment we have no plans for the future development of 'applicationinsights-spring-boot-starter' specifically. Have you been able to try 3.0 version?

**Comment by dicody** [comment]
> @dicody At the moment we have no plans for the future development of 'applicationinsights-spring-boot-starter' specifically. Have you been able to try 3.0 version?

Hi @MS-jgol ,

Thanks for the clarification. I'm specifically interested in 'applicationinsights-spring-boot-starter' since we did a quite enhancement to it (for our local needs), but yeah we did tried out v3.0 already and it works great.

Thanks again for your answers!
