### ISSUE TITLE
Raise Warning when logs do not get populated in application insights 'Traces' table

### ISSUE THREAD

**Issue by vibhuti99** [microsoft/ApplicationInsights-Java#1331]
**Is your feature request related to a problem? Please describe.**
Due to various reasons people may update some maven dependency versions in a project. Sometimes when this happens there is failure of logs getting populated in application insights 'Traces' table. It would be super helpful to be able to get notified about this as soon as possible. Currently what happens is that we go look for logs and then realize logs have not been coming in.

**Describe the solution you would like**
If there are no new logs in Traces table for a given period of time (preferable this period should be configurable), then raise a warning message.

**Describe alternatives you have considered**
N/A

**Additional context**
N/A

**Comment by trask** [comment]
> If there are no new logs in Traces table for a given period of time (preferable this period should be configurable), then raise a warning message.

Hi @vibhuti99! I think you are looking for the Application Insights Alerts feature. This is not a feature of the Java SDK/agent, but hopefully this page will help you get started with it: https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-log

**Comment by kishore25kumar** [comment]
Hi @trask the ask here is if the logs are not written to application insights because of some issue it should be communicated through some warning. Last time we updated the library version logs stopped coming in traces table. A separate issue is created for the same [here](https://github.com/Azure/azure-sdk-for-java/issues/15773).

**Comment by trask** [comment]
Hi @kishore25kumar, I recommend updating to 3.0, which doesn't require any library dependencies (so avoids the breakage you mention) and will auto-capture micrometer and spring actuator metrics: https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#autocollected-requests-dependencies-logs-and-metrics

**Comment by trask** [comment]
Closing, please let us know if you are still having this issue
