### ISSUE TITLE
Question: Find Traces for a given RequestID/OperationID

### ISSUE THREAD

**Issue by anumalasri** [microsoft/ApplicationInsights-Java#1347]
We are successfully able to integrate Spring Boot Application with Azure AppInsights and able to view different details and metrics in AppInsights. 

Currently AppInsights have two different event types  - **Requests & Traces.**

Requests are for Web or Incoming request calls and AppInsights will assign a requestId /operationId based on few details. 
Traces is for log messages coming out of application.  These logs are might be for a given request Id.

In regular Spring Cloud, we have _traceId and spanID_ and able to log them using headers syntax in Log Patterns.  

However,  We are not clear from Azure Documentation,  how to find specific trace messages (logs) for a given Request/OperationID. 

**Questions :** 

- Is there any way to log specific OperationId/RequestId in traces ?  
- If so,  can you provide details on how to do that ? 

Thanks

**Comment by trask** [comment]
Hi @anumalasri!

Are you using 3.0? That will instrument your loggers and capture send your logs directly to Application Insights along with correlation to spanId/traceId.

**Comment by anumalasri** [comment]
@trask .. Currently, We are using v2.6.1.   Is it possible to log AI OperationID in log messages using AI v2.6.1? 

We can wait for v3.0 release.   May we know, AI v3.0 compatibility with Spring Boot versions ?

**Comment by trask** [comment]
> May we know, AI v3.0 compatibility with Spring Boot versions ?

Yes, as long as you are using Java 8+

**Comment by anumalasri** [comment]
Sorry we could NOT able to find Spring Boot started in v3.0-PREVIEW, at this time.   We will wait for v3.0 release and understand better on how to upgrade for our application. 


We would like to find all traces/logs for a given Operation ID , within log files (instead of AI Instance).  Let us know if its possible and how to Log Operation ID in log messages using v2.6.1.

**Comment by trask** [comment]
Closing, let us know if you have any issues with 3.0.

Check out the [documentation on upgrading from 2.x](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-upgrade-from-2x).
