### ISSUE TITLE
Configuration to turn off trace telemetry automatically generated by java agent

### ISSUE THREAD

**Issue by m-gawel** [microsoft/ApplicationInsights-Java#1388]
**Is your feature request related to a problem? Please describe.**
We have faced an issue during analysing which data is automatically collected after taking agent to our application. With a team, we have found that most of our daily cap is taken by trace telemetry.
![image](https://user-images.githubusercontent.com/56826591/99888727-23d2fb00-2c4f-11eb-8e2e-9597dda2fd97.png)
![image](https://user-images.githubusercontent.com/56826591/99888738-36e5cb00-2c4f-11eb-824a-4dfa655bd2a0.png)
About 99% of trace telemetry is generated during redis call.
![image](https://user-images.githubusercontent.com/56826591/99888762-64327900-2c4f-11eb-9628-6f742bc32e50.png)

Temporarily we have lower data sampling to 8,3 %

**Describe the solution you would like**
I would like to have the possibility to turn off trace telemetry or find a way to not send all or auto-generated trace telemetry to application insights. Is it possible in some way or should we remove auto-generation of telemetry and do make it manually?

**Comment by trask** [comment]
Hi @m-gawel, try setting logging collection level to `OFF`: https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#auto-collected-logging

**Comment by m-gawel** [comment]
Hi @trask, Thanks for replay. I have checked that and I still see those traces:
![image](https://user-images.githubusercontent.com/56826591/99951563-9b537800-2d7e-11eb-88cd-4202cbca4106.png)
Here is our configuration:
![image](https://user-images.githubusercontent.com/56826591/99951631-b1f9cf00-2d7e-11eb-9818-9378732bd72c.png)

**Comment by m-gawel** [comment]
Hi @trask, thanks for your reply.
After deployment new version (3.0.0) with json configuration:
![image](https://user-images.githubusercontent.com/56826591/99952271-aa86f580-2d7f-11eb-965b-fc74817d4394.png)
I'm still having those traces in application insights:
![image](https://user-images.githubusercontent.com/56826591/99952350-c8ecf100-2d7f-11eb-9834-a163dc9bd0aa.png)
Amount of traces are lower due to the fact that is our development environment.

**Comment by trask** [comment]
Can you confirm that you are using 3.0.0 GA? This looks like an earlier version where redis.encode.start/redis.encode.end were mapped to `traces`. They should be mapped to `customEvents` now in 3.0.0 GA.

**Comment by trask** [comment]
Closing, please let us know if you are still facing this issue
