### ISSUE TITLE
Populating application_Version with agent V3

### ISSUE THREAD

**Issue by electrified** [microsoft/ApplicationInsights-Java#1392]
**Is your feature request related to a problem? Please describe.**
We have recently migrated to agent V3. We are continuing to use SDK 2.6.2 as we have some custom events. Previously we were populating the version number via the SDK and the ContextInitializer, now this has no effect

```
@Bean
fun versionContextInitializer() = ContextInitializer { it.component.setVersion(version) }
```

**Describe the solution you would like**
Ideally a way to populate the version number

**Describe alternatives you have considered**
We are currently adding a customDimension via `applicationinsights.json` as below, but ideally we would like to populate the "real" `application_Version` field

```
  "customDimensions": {
    "application_Version": "${BUILD_NUMBER}"
  }
```

**Comment by trask** [comment]
This is supported now in 3.0.1-BETA: https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#custom-dimensions
