### ISSUE TITLE
V3.0.0 - Fail to start due to missing connection string or instrumentation key provided

### ISSUE THREAD

**Issue by jycamier** [microsoft/ApplicationInsights-Java#1393]
### Expected behavior

I have follow the process to integrate Application Insight in my Spring Boot application : https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent

With, `APPLICATIONINSIGHTS_CONNECTION_STRING` filled, no problem. The agent is running. However, I need more configuration in my apps so, I decide to use the `applicationinsights.json` method with somthing of simple : 

```json
{
  "connectionString": "InstrumentationKey=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx;IngestionEndpoint=https://westeurope-1.in.applicationinsights.azure.com/"
}
```
### Actual behavior

He doesn't care about my connectionString.

```
2020-11-24 19:31:02.598Z ERROR c.m.applicationinsights.agent - ApplicationInsights Java Agent failed to start
java.lang.reflect.InvocationTargetException: null
com.microsoft.applicationinsights.agent.bootstrap.configuration.ConfigurationBuilder$ConfigurationException: No connection string or instrumentation key provided
```

I have try with the previous definition style : 

```json
    {
      "instrumentationSettings": {
        "connectionString": "InstrumentationKey=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx;IngestionEndpoint=https://westeurope-1.in.applicationinsights.azure.com/",
        "preview": {
          "roleName": "foobar"
        }
      }
    }
```

And...

```
com.microsoft.applicationinsights.agent.bootstrap.configuration.ConfigurationBuilder$ConfigurationException: Error parsing configuration file: /opt/agents/applicationinsights.json
...
 Caused by: java.lang.IllegalStateException: It looks like you are using an old applicationinsights.json file which still has "instrumentationSettings", please see the docs for the new format: https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config
```
So, I'm sure that my file is read and parsed.

### To Reproduce
Just to follow the documentation at https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent

### System information
 - SDK Version: v3.0.0
 - Spring Boot 2.2.1
 - openjdk version "11.0.6" 2020-01-14
 - OS type and version: Azure Kubernetes Service base on image `gcr.io/distroless/java:11`

**Comment by jycamier** [comment]
Sorry. 
It's a PEBKAC.

**Comment by trask** [comment]
> PEBKAC

I had to look that up 😂👍
