### ISSUE TITLE
Publish 3.0 to Maven central

### ISSUE THREAD

**Issue by rjdkolb** [microsoft/ApplicationInsights-Java#1401]
3.0 was released 27 days ago, can 3.0 be deployed to maven central please ?

Latest version is 2.6.2:
https://mvnrepository.com/artifact/com.microsoft.azure/applicationinsights-web

thanks

**Comment by heyams** [comment]
@rjdkolb it's located here: https://search.maven.org/artifact/com.microsoft.azure/applicationinsights-agent.

**Comment by rjdkolb** [comment]
Thanks @heyams 
My mistake. From the documentation this did not seem apparent.

**Comment by heyams** [comment]
Thanks. I will make sure this link will become available on the public doc.
