### ISSUE TITLE
applicationinsights-web bundles instead of dependency on applicationinisghts-core

### ISSUE THREAD

**Issue by pauldaustin** [microsoft/ApplicationInsights-Java#1402]
applicationinsights-web seems to bundle everything in applicationinisghts-core. Which means if both are included in a project there are an extra 6.8MB of files in an application.

applicationinsights-web should just have a depenedency to applicationinisghts-core and not duplicate the code.

In my project I have the following two depenedencies. The first has a dependency to applicationinsights-web and the second applicationinisghts-core.

```
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>applicationinsights-spring-boot-starter</artifactId>
			<version>2.6.2</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>applicationinsights-logging-logback</artifactId>
			<version>2.6.2</version>
		</dependency>
```

**Comment by heyams** [comment]
@pauldaustin looks like you're using 2.6.2.  Have you considered upgrading to [3.0.0 GA](https://search.maven.org/artifact/com.microsoft.azure/applicationinsights-agent/3.0.0/jar).  

this is all you need:
```
<dependency>
  <groupId>com.microsoft.azure</groupId>
  <artifactId>applicationinsights-agent</artifactId>
  <version>3.0.0</version>
</dependency>
```

**Comment by pauldaustin** [comment]
Helen,

I didn't know it was available.

A quick looks like its 17MB in size. That seems like a lot.

This is due to following.

- Both x86 and 64 bit versions of dlls are included. Could you create a bundle that just has 64 bit dlls
- Every external API has been copied to a package specific to this module. This adds a lot of duplication in an application. If every library did this apps would be huge. Is there a way that you could offer two versions. One that fully utilizes maven/java module system to include dependencies. And the other which is the version that automatically takes the source code and changes all the imports to embedded versions of the code and has a single budle.

**Comment by heyams** [comment]
Thanks. I will discuss with @trask if we want to separate dlls for x84 and 64 bit.  Stay tune. 
By the way, 3.0.0 GA has a new config structure, please follow [doc here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent).

**Comment by heyams** [comment]
Try to watch our repo for new releases in the near future.

**Comment by heyams** [comment]
@trask https://github.com/microsoft/ApplicationInsights-Java/issues/1402#issuecomment-738268823

**Comment by trask** [comment]
3.0 is deployed as a javaagent, it's not used as a maven dependency anymore

**Comment by pauldaustin** [comment]
@trask, ok that makes sense that everything is bundled.

When I get a chance I will see if I can update my docker configuration to use it.

**Comment by trask** [comment]
Closing, let us know if this is still an issue
