### ISSUE TITLE
Is it possible to exclude some urls when I using codeless monitoring(applicationinsights-agent-3.0.0.jar)

### ISSUE THREAD

**Issue by zhoufenqin** [microsoft/ApplicationInsights-Java#1405]
**Is your feature request related to a problem? Please describe.**
I follow [this page ](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent) to realize Application Insight with my spring boot project. It's easy and I just need to download the jar then config my Application Insight ConnectionString.
Now I have to exludes some urls, but I don't find some annotation or other efficient way to realize this feature.
I see [the doc](https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling) says that we can filter with telemetry processors, it seems we need to realize a processor implements `ITelemetryProcessor`? but I use the codeless way with `-javaagent`, how can I realize this function?
Hope to receive a response. thx

**Describe the solution you would like**
Describe what you want to happen.

**Describe alternatives you have considered**
Describe any alternative solutions or features you've considered.

**Additional context**

**Comment by gunsliver** [comment]
I think this may help https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-telemetry-processors .

**Comment by Sachin1O1** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-telemetry-processors .

The above document is not so clear to understand and also this functionality is in preview. can we have any better way to do that?

**Comment by MS-jgol** [comment]
@Sachin1O1 The team is working on a way to exclude certain URLs from tracking. There is no definite ETA yet. The TelemetryProcessors will not solve this.

**Comment by trask** [comment]
[3.0.3-BETA.2](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.3-BETA.2) is released with [sampling overrides (preview)](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-sampling-overrides) which allows you to exclude (or reduce sampling percentage) for health checks(!)

**Comment by paveljakov** [comment]
Hello, will you publish 3.0.3-BETA.2 to maven repo?

**Comment by trask** [comment]
Yes! https://search.maven.org/search?q=g:com.microsoft.azure%20a:applicationinsights-agent
