### ISSUE TITLE
Sending custom metrics along with request in Application Insights

### ISSUE THREAD

**Issue by CapTaek** [microsoft/ApplicationInsights-Java#1413]
Hi,
Is it possible to add a TransactionId (for example) to the properties of the automatically captured HTTP request? End goal is to track the transaction ID along with the "Request" as an additional/custom property in the request.

**Comment by trask** [comment]
hi @CapTaek, we just added support for this in 3.0.1-BETA released today:

https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#add-request-custom-dimensions-using-the-2x-sdk
