### ISSUE TITLE
role name not reflecting on azure app insights portal when set on applicationinsights.json file

### ISSUE THREAD

**Issue by raytapan** [microsoft/ApplicationInsights-Java#1425]
### Expected behavior
I am running java app as Web app on Azure app service. I am trying to integrate with applicationinsights-agent-3.0.0 to send telemetry to application insights.
I am trying to specify a role name as my web app name as i have multiple application sending telemetry to same application insights resource. The role name specified on applicationinsights.json file should reflect as component name on Application map on app insights portal

### Actual behavior
The role name specified on applicationinsights.json file is NOT reflecting as component name on Application map on app insights portal

### To Reproduce
The below is my declaration on applicationinsights.json file.
{
    "connectionString": "InstrumentationKey.../",
    "role": {
        "name": "my role name"
    }
}

Then when i go to Application map on azure app insights portal, it doesn't show the role name specified on applicationinsights.json file. Instead it displays my actual web app name on azure app service.

However if I set environment variable APPLICATIONINSIGHTS_ROLE_NAME in app settings in web app, it correctly displays on  Application map on app insights portal

**Comment by raytapan** [comment]
I went thru the app insights source code and it seems like a code issue.

In the code snippet from ConfigurationManager.java file below, the role.name is being set. 
The overlayWithEnvVars method is being called with (APPLICATIONINSIGHTS_ROLE_NAME, WEBSITE_SITE_NAME, config.role.name) parameters. 
It sets the APPLICATIONINSIGHTS_ROLE_NAME if not null, other wise it will look at WEBSITE_SITE_NAME environment variable. Since WEBSITE_SITE_NAME environment variable is always available in Azure App service, it is not coming to config.role.name value at all.

Instead 2nd and 3rd parameter should be switched which will make sure config.role.name value from applicationinsights.json is second preference after APPLICATIONINSIGHTS_ROLE_NAME environment variable. if both are unavailable, then set default value which is WEBSITE_SITE_NAME.

I believe it should be replaced as below.
**config.role.name = overlayWithEnvVars(APPLICATIONINSIGHTS_ROLE_NAME, config.role.name, WEBSITE_SITE_NAME);**


    static void overlayEnvVars(Configuration config) throws IOException {
        config.role.name = overlayWithEnvVars(APPLICATIONINSIGHTS_ROLE_NAME, WEBSITE_SITE_NAME, config.role.name);
        config.role.instance = overlayWithEnvVars(APPLICATIONINSIGHTS_ROLE_INSTANCE, WEBSITE_INSTANCE_ID, config.role.instance);

        config.sampling.percentage = overlayWithEnvVar(APPLICATIONINSIGHTS_SAMPLING_PERCENTAGE, config.sampling.percentage);

        loadLogCaptureEnvVar(config);
        loadJmxMetrics(config);
    }

    // visible for testing
    static String overlayWithEnvVars(String name1, String name2, String defaultValue) {
        String value = getEnv(name1);
        if (value != null && !value.isEmpty()) {
            return value;
        }
        value = getEnv(name2);
        if (value != null && !value.isEmpty()) {
            return value;
        }
        return defaultValue;
    }

**Comment by raytapan** [comment]
Hi Trask, 
Since this issue is closed now, may i know which version of app applicationinsights-agent jar file will have this fix available?

**Comment by trask** [comment]
hi @raytapan, it will be in 3.0.1 which should be available later this week.

**Comment by raytapan** [comment]
Thanks @trask for taking care of my request. I appreciate it!!
