### ISSUE TITLE
Question - Will Application Insights SpringBoot Starter be released as 3.0 ? 

### ISSUE THREAD

**Issue by UrbanF0x** [microsoft/ApplicationInsights-Java#1429]
**Is your feature request related to a problem?
Yes. 

 Please describe.**
Can you confirm if using the 'Application Insights SpringBoot Starter' library is deprecated ? Or will 3.0 be released at some point ?

The library is still on 2.6.2 and has not been updated since September and when I click on 'Application Insights with SpringBoot' it suggests using the applicationinsights-core or applicationinsights-web dependencies instead. 

**Describe the solution you would like**
Do you have a release date ? Or should we switch our implementation approach. I see Application Insights for Java is released as 3.0 which is great and details on how to use it.

**Comment by trask** [comment]
Hi @UrbanF0x, we are not planning to release a 3.0 version of the Application Insights Spring Boot Starter. Please see https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent for the 3.0 documentation.

**Comment by UrbanF0x** [comment]
Thanks for the confirmation @trask. I will update our projects.
