### ISSUE TITLE
Illegal reflective access on Java 11

### ISSUE THREAD

**Issue by pkunk** [microsoft/ApplicationInsights-Java#1446]
### Expected behavior
Support for Java >= 11 in 2.* and 3.* versions of ApplicationInsights. No warnings.

### Actual behavior
Warning caused by shaded xstream dependency. https://github.com/x-stream/xstream/issues/101

This issue is mitigated in xstream 1.4.13 and later, ApplicationInsights currently includes old 1.4.11.1 version.
See for more details:
https://github.com/x-stream/xstream/pull/216
https://github.com/x-stream/xstream/pull/218

### To Reproduce
 * clone project: https://github.com/pkunk/ai-reflection
 * ./gradlew build

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: 2.6.2

### Logs
Executing task 'build'...

> Task :compileJava
> Task :processResources UP-TO-DATE
> Task :classes
> Task :bootJar
> Task :jar SKIPPED
> Task :assemble
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses

> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.microsoft.applicationinsights.core.dependencies.xstream.core.util.Fields (file:/home/pkunk/.cache/gradle/modules-2/files-2.1/com.microsoft.azure/applicationinsights-web/2.6.2/689b4af8d82bd54d8ba694fff77c63ddaa89afc/applicationinsights-web-2.6.2.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.microsoft.applicationinsights.core.dependencies.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by trask** [comment]
Resolved by #1479
