### ISSUE TITLE
Augment RequestTelemetry later in the pipe

### ISSUE THREAD

**Issue by dimsedane** [microsoft/ApplicationInsights-Java#1458]
Hi!

We have a multi tenant spring boot application using Application Insights. Since it is multi tenant, we use a TelemetryInitializer to tag all telemetry with the current tenant. The information of which tenant is making the request is contained in a JWT that we parse using a Filter. 

This is causing an issue for the RequestTelemetry, since the TelemetryInitializer is called before the filter runs, meaning that the tenant information is not yet available. What is the best way to get around this? 

We have tried using a TelemetryProcessor to update the RequestTelemetry, but that seems not to work. Is there any documentation that describes when the processor is run?

**Comment by trask** [comment]
hi @dimsedane, sorry for the late reply, try something like below, you can get the current (auto-collected) request telemetry and add the tenant dimension to it:

```
RequestTelemetry requestTelemetry = ThreadContext.getRequestTelemetryContext().getHttpRequestTelemetry();
requestTelemetry.getProperties().put("tenant", "xyz");
```

(see https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#add-request-custom-dimensions-using-the-2x-sdk)

**Comment by trask** [comment]
Closing, let us know if this is still an issue.
