### ISSUE TITLE
Application insights not recording telemetry for Azure Spring Boot FunctionApp

### ISSUE THREAD

**Issue by mlakshminara** [microsoft/ApplicationInsights-Java#1466]
I have created a Spring Boot FunctionApp using Blob Trigger and ServiceBus Trigger and the function code is working fine. I could the trace logs in Azure but application insights telemetry like Performance, Metrics, Failures does not work and is not recording request count.

I have configured the following in FunctionApp
1) I have enabled "All Data" for data sampling in Application insights under usage and estimated cost
2) Added APPLICATIONINSIGHTS_CONNECTION_STRING in application settings in function app pointing to the correct instrumentation key
3) Added APPINSIGHTS_INSTRUMENTATIONKEY in application settings with only the key value
4) Added applicationinsights.json in as part of function application zip deployment and is extracted in D:/home/site/wwwroot/ 
```
{
	"sampling": {
    	"percentage": 100
  	},
	"instrumentation": {
    	"micrometer": {
      		"enabled": true
    	}
  	}
}
```
4) Added applicationinsights-agent-3.0.2.jar in the deployment and placed in D:/home/site/wwwroot
5) Added JAVA_OPTS application settings for the function app with value: -javaagent:D:/home/site/wwwroot/applicationinsights-agent-3.0.2.jar
6) I have added applicationinsights-logging-logback-2.6.2.jar and configured logback-spring.xml with com.microsoft.applicationinsights.logback.ApplicationInsightsAppender and I was able to get the logs and traces in Azure

screenshot of console in function application:
![console](https://user-images.githubusercontent.com/7725557/106355882-eced2580-6320-11eb-9c96-28bf902e4701.jpg)

Am not able to see data in Application insights Performance, Metrics, Failures tabs. Can any one let me know how to configure application insights for Spring Boot Function application

**Comment by trask** [comment]
hi @mlakshminara, can you attach the `applicationinsights.log` file, and the stdout/stderr logs from your application? thx!

**Comment by mlakshminara** [comment]
I don't see applicationinsights.log when I look in Function > Development Tools > Advance Tools > click on Go to open Kudu browser and in that I don't see applicationinsights.log

**Comment by trask** [comment]
hi @mlakshminara, there's a preview available in the Azure Functions environment that allows you to automatically attach the javaagent if you want to give that a try instead of manually uploading the javaagent and changing the JVM args:

https://docs.microsoft.com/en-us/azure/azure-monitor/app/monitor-functions#distributed-tracing-for-java-applications-on-windows-public-preview
