### ISSUE TITLE
Disable Default PageViewTelemetry

### ISSUE THREAD

**Issue by geoarchitect** [microsoft/ApplicationInsights-Java#1471]
We are currently testing the SnapShot from #1452 

One thing I keep seeing is a single user being posted from the agent. This sets all of the properties as Undefined. It appears to almost be an additional user, as the user with the custom properties is being set. 

Can we confirm if this is indeed the case, and can we disable the Agent from posting user data so we can collect it via the Custom settings included in the ticket (#1452)?

![image](https://user-images.githubusercontent.com/16295185/106856091-fb726e80-668b-11eb-97a7-de0094fcb86d.png)

**Comment by trask** [comment]
Hi @geoarchitect, I'm not quite following, can you provide a bit more details? thanks!

**Comment by trask** [comment]
Closing, let us know if this is still an issue.
