### ISSUE TITLE
How to use Application Insights agent 3.0.x with Spring Boot

### ISSUE THREAD

**Issue by MelleD** [microsoft/ApplicationInsights-Java#1474]
Hello,

does the spring boot starter project no longer exist? We would like to test the 3.0.x agent. However, I cannot find any documentation on the applicationinsights-spring-boot-starter project.

Does the agent have to be added separately now?
Add -javaagent: path / to / applicationinsights-agent-3.0.2.jar to your application's JVM args. Until now, this was not necessary with spring boot starter. Am I right there?

Is it still possible to store the instrumentation key in a key vault?

**Comment by trask** [comment]
Hi @MelleD, a separate starter is no longer needed, and the same [steps for enabling the 3.0 agent](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#quickstart) apply for both spring boot and non-spring boot apps.

The agent doesn't have native key vault support currently, but you can populate the env var `APPLICATIONINSIGHTS_CONNECTION_STRING` from key vault, e.g. https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references.

**Comment by MelleD** [comment]
Hey @trask,

thanks for the quick reply. Then i try to upgrade the agent.

**Comment by MelleD** [comment]
Hey @trask,

one more question. I'm not sure, but is the applicationinsights-logging-logback still needed with the new agent or can I remove it as well?

**Comment by trask** [comment]
hi @MelleD, you can remove applicationinsights-logging-logback, the 3.0 agent auto-collects logging now on it's own: https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#auto-collected-logging

**Comment by MelleD** [comment]
Hey @trask 

that's exactly what I thought, but as soon as I take out the logback insights deps, I don't see a stack trace in the end to end transaction details overview and all the details are missing

**Comment by kasdihacene** [comment]
Application Insights using Java SDK is no more recommended. You can follow the steps here https://docs.microsoft.com/en-us/azure/azure-monitor/app/micrometer-java

**Comment by MelleD** [comment]
After a restart all works with the Agent 3.0..

Thanks :)
