### ISSUE TITLE
Only logs with Level Warn and Error are displayed in Azure Application Insights?

### ISSUE THREAD

**Issue by kandouda** [microsoft/ApplicationInsights-Java#1489]
Hi,

we have a Java Spring Boot WebApp (App Service) running in a Linux environment on Azure, which uses slf4j/Logback for logging.
These logs should be displayed in our Application Insights.  It works but i can see all warnings and errors we log in our application within App InsightsWe can not see the logs with with level INFO, TRACE, DEBUG.

We use these dependencies:
```
<dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>applicationinsights-spring-boot-starter</artifactId>
            <version>2.6.2</version>
</dependency>
 <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>applicationinsights-logging-logback</artifactId>
            <version>2.6.2</version>
 </dependency>
```
The logging level of our application itself seems to be correct, because I can see all my expected logs within the Console Logs .
The configuration for the logback is:
```
<springProfile name="dev">
	<include
		resource="org/springframework/boot/logging/logback/base.xml" />
	<appender
		name="STDOUT"
		class="ch.qos.logback.core.ConsoleAppender">
		<encoder>
			<charset>UTF-8</charset>
			<pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %class{36}:%L - %msg%n</pattern>
		</encoder>
	</appender>
	<appender
		name="aiAppender"
		class="com.microsoft.applicationinsights.logback.ApplicationInsightsAppender">
		<instrumentationKey>${APPLICATION_INSIGHTS_KEY}</instrumentationKey>
		</appender>
	<root level="info">
		<appender-ref ref="aiAppender" />
                <appender-ref ref="STDOUT" />
	</root>
</springProfile>
```
What am I missing here? How i can change the Loglevel? I use the last application insights spring boot dependency 2.6.2

**Comment by trask** [comment]
hi @kandouda! are you able to update to 3.0.2? there's no specific spring boot starter in 3.0, because 3.0 supports easy set up for any java app: https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent

**Comment by kandouda** [comment]
Ok thank you for your answer. I have read the documentation and understand that I should do the following:

1- **Remove** the dependency ```applicationinsights-spring-boot-starter: 2.6.2``` from the pom.xml

2- The dependency ```applicationinsights-logging-logback: 2.6.2``` **remains** in pom.xml. This is used by the aiAppender from logback-spring.xml

3- Download `` applicationinsights-agent-3.0.2.jar ''

4- Point the JVM to the agent
Add ```-javaagent: path / to / applicationinsights-agent-3.0.2.jar``` to your application's JVM args

  5- Point the agent to your Application Insights resource, by setting an environment variable:
```
APPLICATIONINSIGHTS_CONNECTION_STRING = InstrumentationKey = ...
```
Have I missed anything else?

**Comment by trask** [comment]
You can remove `applicationinsights-logging-logback` from your pom.xml if you want. If you don't, that's ok too, the 3.0 javaagent will suppress it since it captures logging on its own.

You may also want to set `APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL` since from above it sounds like you want to capture more than the default INFO: https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#auto-collected-logging

**Comment by kandouda** [comment]
@trask Great your comments helped me. ```applicationinsights-agent-3.0.2.jar``` works for me and all logs with the configured loglevel in applicationinsights.json are displayed in application insights. But I have one more question: How can I set the log level for certain packages. Previously it worked via logback-spring.xml e.g.
```
		<logger
			name="org.hibernate"
			additivity="false"
			level="ERROR">
			<appender-ref ref="STDOUT" />
		</logger>
```


yet with version 3.0.2 the ```logback-sprint.xml``` is probably ignored and all packages send their logs to application insight. For example for hibernate, how can I now set up hibernate to only send error logs to application insights logs.

**Comment by trask** [comment]
hi @kandouda, the logback-spring.xml is not ignored!

> Logging is only captured if it first meets the logging frameworks' configured threshold, and second also meets the Application Insights configured threshold.

(https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#auto-collected-logging)

**Comment by trask** [comment]
Closing, please let us know if you are still having this issue
