### ISSUE TITLE
No HTTP methods names in main performance window

### ISSUE THREAD

**Issue by garoplin** [microsoft/ApplicationInsights-Java#1497]
### Actual behavior
When using agent in versions 3.* http methods are not visible in performance page. 
![agent3](https://user-images.githubusercontent.com/79226004/108263455-98daa180-7166-11eb-935b-c97f4d6ed751.png)
This is quite inconvenient, as we cannot filter by operation type.

### Expected behavior
It works fine with agent version 2.6.2
![agent2 6](https://user-images.githubusercontent.com/79226004/108263453-98420b00-7166-11eb-9339-fa4ebb6a3c01.png)

### System information
Please provide the following information:
 - SDK Version: 3.0.2
 - OS type and version: Windows 10
 - Application Server type and version (if applicable): Tomcat 11
 - Using spring-boot? yes
 - Additional relevant libraries (with version, if applicable): applicationinsights-web-2.6.2, applicationinsights-core-2.6.2

**Comment by trask** [comment]
hi @garoplin, check out https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-upgrade-from-2x#prefix-the-operation-name-with-the-http-method-get-post-etc
