### ISSUE TITLE
Can we use applicationInsights agent maven dependency instead agent.jar file for auto-instrumentation 3.0 ?

### ISSUE THREAD

**Issue by kasdihacene** [microsoft/ApplicationInsights-Java#1506]
Is there any way to use the maven dependency for enabling application insights agent 3.0 instead injecting the jar file `19Mo` on the resources of the application ?

**Comment by trask** [comment]
hi @kasdihacene, can you describe a bit more what you are trying to do?

**Comment by kasdihacene** [comment]
Hi @trask I want to know if I can replace this agent located on the project `/resources` by a maven dependency of the agent then this will be loaded at deploy phase to be run on production environment.
Instead pointing the JVM to the jar file, I'm wondering if we can inject dynamically the agent maven dependency into the project ?
```xml
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>applicationinsights-agent</artifactId>
    <version>3.0.2</version>
</dependency>
```

**Comment by MS-jgol** [comment]
@kasdihacene Placing the agent jar file requires no redeployment, you will just simply restart your application. If I am reading your message correctly this should work you?

**Comment by x4FF3** [comment]
Hi,
i tried the maven plugin as well in an instance of our app, but it seems i wasnt able to configure it, so that it reported anything to our insights. Is there documentation somewhere to configure it, when it was added to pom.xml?

**Comment by MS-jgol** [comment]
@x4FF3 Are you trying to add the application insights Java 3.0 agent without restarting the app - is this the essence of what you are trying to do? If so, this is not going to work, you have to follow the steps described here: https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent

**Comment by x4FF3** [comment]
@MS-jgol Hi, no. As we are running a Springboot App in an AppService, i tried to add it as dependency to our pom.xml. And run a build and tried to configure it via ENV variables.
So it is only possible to use it, when calling it via -javaagent? Why does the Maven-Plugin exist then?

**Comment by kasdihacene** [comment]
@x4FF3, I understand your issue, let met show you what I have put on my pom.xml to upload the dependency on maven phases.

1. Add a plugin to download the dependency then copy it to agent workspace (where you put config files)

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>${maven-dependency-plugin.version}</version>
                <executions>
                    <execution>
                        <id>copyAppInsightsAgent</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <artifactItems>
                        <artifactItem>
                            <groupId>com.microsoft.azure</groupId>
                            <artifactId>applicationinsights-agent</artifactId>
                            <version>${applicationinsights-agent.version}</version>
                            <type>jar</type>
                            <overWrite>false</overWrite>
                            <outputDirectory>${project.basedir}/src/main/jib/agent</outputDirectory>
                            <destFileName>applicationinsights-agent-${applicationinsights-agent.version}.jar</destFileName>
                        </artifactItem>
                    </artifactItems>
                </configuration>
            </plugin>
```

2. So, I'm using jib to build docker image, bellow the plugin to generate the image according to your config files that I put on my /jib` dir`

```xml
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>${jib.plugin.version}</version>
                <configuration>
                    <allowInsecureRegistries>true</allowInsecureRegistries>
                    <from>
                        <image>adoptopenjdk:11-jdk-openj9-bionic</image>
                    </from>
                    <to>
                        <image>sgefacr.azurecr.io/sgef-graydon-gateway</image>
                        <tags>
                            <tag>${project.version}</tag>
                            <tag>${git.commit.id}</tag>
                        </tags>
                    </to>
                    <container>
                        <jvmFlags>
                            <jvmFlag>${jib.args}</jvmFlag>
                        </jvmFlags>
                    </container>
                </configuration>
                <executions>
                    <execution>
                        <phase>deploy</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

Hope this will help you ;)

Hacene.

**Comment by trask** [comment]
thanks @kasdihacene 👍

**Comment by florianrusch** [comment]
@kasdihacene I like your way of adding the agent to a container build. This approach can also be used to create a "normal" artefact. Moreover, it gives you the ability to manage all dependencies in one place, which should be preferred most of the time.

Thanks for sharing! :-)

**Comment by trask** [comment]
Closing, but please feel free to post further comment or create a new issue.

**Comment by trask** [comment]
fyi for anyone landing on this issue, we recently added an official Sample to show how to use this approach: https://github.com/Azure-Samples/ApplicationInsights-Java-Samples/blob/main/maven/pom.xml

(and similar samples for gradle)
