### ISSUE TITLE
XML configuration with XSD file definitions

### ISSUE THREAD

**Issue by WoodenAndrew** [microsoft/ApplicationInsights-Java#1509]
**Is your feature request related to a problem? Please describe.**
After looking through the application insights documentation I found it that the configuration file is configured using JSON format. Without having an application insights specific plugin in my editor I cannot know whether or not the configuration file that I am currently editing is properly formatted according to the format that the currently loaded agent requires. As a result, there is too much dependency on trial and error sort of poking at running the application and checking if the file is properly defined.

**Describe the solution you would like**
JSON file configuration replaced with XML + XSD configuration file combo.

**Describe alternatives you have considered**
Application insights 3.0 does not seem to provide any alternative configurations. In previous releases when AI still used XML file configuration there was no XSD file to assert your configuration against.

**Comment by trask** [comment]
hi @WoodenAndrew! would something like https://json-schema.org/ address your needs?

**Comment by trask** [comment]
Closing, but please feel free to post further comment or create a new issue.
