### ISSUE TITLE
Support for Sample telemetry

### ISSUE THREAD

**Issue by tommytusj** [microsoft/ApplicationInsights-Java#1512]
Are there any plans to support **Sample telemetry**? It's listed as not supported in the support matrix @ https://docs.microsoft.com/en-us/azure/azure-monitor/app/live-stream

Or are there any other way in Azure to live stream the application logs? and not just metrics

**Comment by MS-jgol** [comment]
@tommytusj 
We do not have an ETA at the moment, but adding sample telemetry is definitely in our plans.

**Comment by trask** [comment]
this is resolved by #1852 🎉

here's a SNAPSHOT build if you want to try it out before the next release: [applicationinsights-agent-3.2.0-BETA.3-SNAPSHOT.jar.zip](https://github.com/microsoft/ApplicationInsights-Java/files/7080209/applicationinsights-agent-3.2.0-BETA.3-SNAPSHOT.jar.zip)
