### ISSUE TITLE
Overwriting operationId in version 3.0.2.

### ISSUE THREAD

**Issue by garoplin** [microsoft/ApplicationInsights-Java#1521]
**Is your feature request related to a problem? Please describe.**
In version 3.0.2 it's not possible to overwrite **operationId** and **parentId**, as it is in version 2.6.2. According to the documentation it is possible to retrieve it (and indeed I was able to retrieve it), moreover, I didn't get any exception when trying to overwrite it, but the new value wasn't visible in the Application Insights.

**Comment by trask** [comment]
hi @garoplin, can you describe why you need to overwrite the operationId and parentId, so we can try to find a solution?

**Comment by garoplin** [comment]
Hi @trask, let's say, we're making a request to our Spring application from console application in python. We want to have an effect of a distributed logging so that we can trace the full flow of both python and java apps. We thought of passing new operationId in header and then updating it in AppInsights from java code side. I've tested it on version 2.6.2, and it worked, however, the updated operationId wasn't populated to further events, such as database transactions.

**Comment by trask** [comment]
hey @garoplin, can you send operationId in the W3C traceparent header instead of in a custom header? then it will get picked up and correlated automatically by the Java agent

**Comment by winseros** [comment]
(offtopic) @garoplin you managed to retrieve the `operationId` from `3.0.2`? Could you point a finger? I've looked through all the docs I could find and still got no answer.

**Comment by trask** [comment]
hey @winseros, try

```
ThreadContext.getRequestTelemetryContext()
        .getHttpRequestTelemetry()
        .getContext()
        .getOperation()
        .getId()
```

(you're right, I checked, we don't have docs on this, I will add a new section for this below https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#override-the-request-telemetry-name-using-the-2x-sdk)

**Comment by winseros** [comment]
Thanks. But that returns not quite what I expected. It gives the `id` of a particular operation that can't be used for search inside the portal.

What I'm looking for is `operation_Id`

![image](https://user-images.githubusercontent.com/6763540/110526639-1458be80-8127-11eb-9a1d-c2a1531ad3a3.png)

**Comment by winseros** [comment]
The snapshot works correctly. Thank you!

**Comment by trask** [comment]
[3.0.3-BETA.2](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.3-BETA.2) is released
