### ISSUE TITLE
Agent 3.0.2 track the wrong ClientIP when sending telemetry from server

### ISSUE THREAD

**Issue by rbickel** [microsoft/ApplicationInsights-Java#1535]
**Expected behavior**
When unmasking Client IP in Log Analytics (https://docs.microsoft.com/en-us/azure/azure-monitor/app/ip-collection?tabs=net), the Client IP should be the public IP of the end-user.  

**Actual behavior**
When unmasking Client IP in Log Analytics (https://docs.microsoft.com/en-us/azure/azure-monitor/app/ip-collection?tabs=net), the IP appearing is the server outbound IP (and not the end user Public IP).  

**ENVIRONMENT**
Web Server: JBoss Wildfly 17.0.1 Standalone
Web Application: Sample Maven Web Application Hello World

**To Reproduce**
Deploy applicationinsights-agent-3.0.2.jar and the web application on a Wildfly Standalone web server. The agent 3.0.2 send server telemetry to app insight, but the client IP is the outbound ip of the server. There is also no AI tracking cookie attached to the responses, is that expected ?

**Comment by trask** [comment]
hi @rbickel, thanks for reporting this!

Populating the client IP should get resolved by #1538. You can try out a snapshot build from that PR if you'd like: 
[applicationinsights-agent-3.0.3-BETA-SNAPSHOT.jar.zip](https://github.com/microsoft/ApplicationInsights-Java/files/6088495/applicationinsights-agent-3.0.3-BETA-SNAPSHOT.jar.zip)

3.0 is not currently setting AI tracking cookies, are you using the JavaScript SDK on the client side? can you describe your use case for the AI tracking cookies? thx!

**Comment by rbickel** [comment]
hi @trask,

It looks a bit better, as it logs the same value as "request.getRemoteAddr()". However, in an AKS with CNI enabled, it returns the kube proxyIP instead of the client IP. Which makes is also unusable in this context. Do you have a trick to retrieve the real end-user IP ?

thx

**Comment by trask** [comment]
is `Forwarded` or `X-Forwarded-For` header being sent by the proxy?

**Comment by rbickel** [comment]
Nope, but I found the fix. In AKS, to retrieve the Client IP, we need to set the `externalTrafficPolicy:Local` spec to the Load Balancer service:
https://kubernetes.io/docs/tutorials/services/source-ip/
The issue is then solved with your fix.
Thanks !
