### ISSUE TITLE
Mongo DB dependencies not caught

### ISSUE THREAD

**Issue by Strabox** [microsoft/ApplicationInsights-Java#1543]
When using the jar 3.0.0 the dependencies from Mongo DB (using Spring Data Mongo lib) are caught and sent correctly to Application Insights, but when using 3.0.1 or 3.0.2 jar the Mongo DB dependencies are not sent.

Sample of the json used to configure the agent.
```json
{
        "connectionString": "InstrumentationKey=#{APP_INSIGHTS_INSTRUMENTATION_KEY}#;",
        "role": {
            "name": "SoI Control Manager API",
            "instance": #RUNTIME_POD_NAME#
        },
        "sampling": {
            "percentage": 100
        },
        "instrumentation" : {
            "logging": {
                "level": "INFO"
            }
        },
        "heartbeat": {
            "intervalSeconds": 30
        },
        "selfDiagnostics": {
            "destination": "file+console",
            "level": "INFO",
            "file": {
                "path": "/tmp/control-manager-api/applicationinsights-agent.log",
                "maxSizeMb": 10,
                "maxHistory": 2
            }
        }
    }
```

Thanks for your help,

**Comment by trask** [comment]
hey @Strabox! there have been some improvements to the mongo instrumentation in the latest SNAPSHOT, can you try https://github.com/microsoft/ApplicationInsights-Java/files/6106201/applicationinsights-agent-3.0.3-BETA-SNAPSHOT.jar.zip?

if it's not resolved in the latest SNAPSHOT, can you let us know which driver and version you're using?

**Comment by trask** [comment]
can you try the SNAPSHOT and 3.0.2 side-by-side, it would be great to know if there's a difference between the two (there have been some changes in this area), or if it's legitimate network/ingestion service issues you are running into?

**Comment by trask** [comment]
[3.0.3-BETA.2](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.3-BETA.2) is released
