### ISSUE TITLE
Use of application insights on iot edge device

### ISSUE THREAD

**Issue by JardarM** [microsoft/ApplicationInsights-Java#1546]
Hi,

I am able to report both custom telemetry and log-messages through logback appender. However I need to associate the metrics with my iot edge device-id. I assume that I need to have "Role instance" set somehow. 

As this is inferred from the device connection string I need to set this in code. However most of the documentation I find for app insights seems to lack details on how to do detailed configurations. We also want to have the log level reported to by set in code.

I am currently using 2.6.2 and with a com.microsoft.applicationinsights.logback.ApplicationInsightsAppender with a customer filter where the log level can be set.

So what is the best way to go about this?

**Comment by trask** [comment]
hey @JardarM! is the [Application Insights Java 3.0 agent](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent) an option for you?

**Comment by trask** [comment]
Closing, but please feel free to post further comment or create a new issue.
