### ISSUE TITLE
Correlation doesn't work in Container (Quarkus)

### ISSUE THREAD

**Issue by mtaghavi2005** [microsoft/ApplicationInsights-Java#1595]
### Expected behavior
We are trying to use application insight agent in a Java service (Quarkus framework), but the correlation doesn't work, that means in an Operation Logic across multiple services it cannot be tracked together with other services and gets always new OperationId in AI. Whenever it runs out of container everything works well but when it deploys to the cluster or even runs in a local machine inside a container the correlation gets lost.  

### Actual behavior
Logging entries will be logged with another OperationId and cannot be tracked.

### To Reproduce
clone the sample app
add .env file in the root folder, which contains the following variable:
APPINSIGHTS_INSTRUMENTATIONKEY=APP-Insight Resource Instrumentation KEY
```
docker build -f Dockerfile.jvm -t quarkus/quarkus-application-insight-jvm .
docker run --env-file=.env -i --rm -p 8080:80 quarkus/quarkus-application-insight-jvm
```
call sample api -> http://localhost:8080/weather-forecast
then in application insight you will find following entries:
![image](https://user-images.githubusercontent.com/1976118/113175218-7e0e4900-924b-11eb-873a-2d3251cb38e2.png)
as you can see request and dependency have different operation_id. 
#### Sample Application
[quarkus-application-insight](https://github.com/mtaghavi2005/quarkus-application-insight)

### System information
Please provide the following information:
 - Java Agent Version:  3.0.3-BETA.3
 - OS type and version: Container Image: registry.access.redhat.com/ubi8/ubi-minimal:8.3  
 - Using spring-boot? No
 - Additional relevant libraries (with version, if applicable): Quarkus Framework

### Logs
[applicationinsights.log](https://github.com/microsoft/ApplicationInsights-Java/files/6241250/applicationinsights.log)

**Comment by mkowa42** [comment]
@mtaghavi2005 For a workaround please have a look at https://github.com/microsoft/ApplicationInsights-Java/issues/1980#issuecomment-984808797.

**Comment by trask** [comment]
Here's a SNAPSHOT build with the fix: https://github.com/microsoft/ApplicationInsights-Java/suites/4658614061/artifacts/126616732

Next release is currently targeted for mid-Jan
