### ISSUE TITLE
 c.m.a.agent.Exporter Error for URI Params

### ISSUE THREAD

**Issue by zoomingrocket** [microsoft/ApplicationInsights-Java#1600]
Hi,

We are seeing this error frequently in logs where we have URLs with multiple uri parameters and error reported for '&' character starting from the second uri param 

Java Agent: Application Insights Java 3.0.2 (GA)

E.g. Error Logs
```
2021-03-23 22:20:32.088Z INFO  i.o.a.b.i.aiappid.AiHttpTraceContext - Unparseable tracestate header. Returning span context without state.
2021-03-23 22:20:32.849Z ERROR c.m.a.agent.Exporter - Illegal character in query at index 94: https://xxxxx-xx.xxx.com/dev/ws/rest/crm/xxx/v1/?nextRecordsUrl=&filter=XXX_Number__c='xxxxxx' and Source_system__c='xxxxxxxxx'
```

Actual URL was: https://xxxxx-xx.xxx.com/dev/ws/rest/crm/xxx/v1/?nextRecordsUrl=&filter=XXX_Number__c='xxxxxx'&Source_system__c='xxxxxxxxx'

Masked the actual values in the URL

Thanks

**Comment by trask** [comment]
Hi @zoomingrocket, what http client library are you using, so we can try to narrow down where this is coming from?

**Comment by trask** [comment]
and if you can include an example of how you are using that http client library would be helpful

**Comment by zoomingrocket** [comment]
@trask  - We are using a proprietary platform and not written our own code. Any way we can increase selfDiagnostics log to print out the required info?

**Comment by trask** [comment]
hi @zoomingrocket, please try with 3.0.3, and enable self-diagnostic debug level (https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#self-diagnostics), and attach the full debug log

**Comment by zoomingrocket** [comment]
@trask - After upgrading to 3.0.3 and running for the last 48hrs, this error is no longer reproducible.
