### ISSUE TITLE
Telemetry Initializer for log masking

### ISSUE THREAD

**Issue by rkganji** [microsoft/ApplicationInsights-Java#1605]
Is there some documentation of how to use telemetry initializer for masking the sensitive information in log statements? Examples found were all for adding attributes but didn't find relevant docs to update log message with custom masking.

**Comment by MS-jgol** [comment]
@rkganji 
Please refer to this section in the doc on Telemetry Processors:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-telemetry-processors-examples#exclude-spans

Good examples here:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-telemetry-processors-examples#span-processor-samples

And an overview here:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-telemetry-processors

**Comment by kryalama** [comment]
@rkganji we recently added log processor feature in version 3.1.1. Here is an example on how to mask sensitive data in logs. https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-telemetry-processors-examples#masking-sensitive-data-in-log-message
Please give it a try.

**Comment by trask** [comment]
Closing since this feature is now released, but please feel free to post additional comment on this issue, or create a new issue, if you have further questions.
