### ISSUE TITLE
Question: Can I use the 3.0 agent for java app services?

### ISSUE THREAD

**Issue by tijmenamsing** [microsoft/ApplicationInsights-Java#1615]
Hi,

My goal is to to enable application insights for our java app services. When looking into the [Microsoft documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-get-started?tabs=maven) for this, I get the warning that the 3.0 agent is recommended. However, other pages seem to suggest that this is not yet supported for Java app services.

It is not completely clear to me if it is supported or not. So my question is whether I can implement agent 3.0 or that I should follow the guide for code-based monitoring (https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-get-started?tabs=maven)

**Comment by heyams** [comment]
@tijmenamsing Yes. you can use 3.x Java agent to instrument your java app. Please check out the detailed [Quickstart Guide](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent).

If you're running your Java app on Azure App Services Windows or Linux, please check out [Azure App Services](https://docs.microsoft.com/en-us/azure/azure-monitor/app/azure-web-apps?tabs=net#enable-application-insights).

**Comment by tijmenamsing** [comment]
Hi @heyams, I followed the quickstart guide and was able to get it to work when running the on my local machine, but not for the app service. Could you guide me on how to set it up correctly?

- I downloaded `applicationinsights-agent-3.0.3.jar` and manually uploaded it to `D:\home\site\wwwroot\applicationinsights-agent-3.0.3.jar` using the App Service Editor
- I added the following application setting:
  key: `JAVA_OPTS`
  value: `-javaagent:D:/home/site/wwwroot/applicationinsights-agent-3.0.3.jar`
- I enabled application insights for the app service using the portal. This action added some application settings, among others the APPLICATIONINSIGHTS_CONNECTION_STRING

General settings for the app service:
- Java version: Java 8
- Java web server: Tomcat 8.5

**Comment by heyams** [comment]
@tijmenamsing You can use App Services Site Extension by setting these application settings via the configuration blade:
XDT_MicrosoftApplicationInsights_Java -> 1
ApplicationInsightsAgent_EXTENSION_VERSION -> ~2

this will point to java agent 3.0.2. If you choose to use the latest version of java agent, what you did is correct. You just need to manually stop and restart your app services. It should work.  Once your app is back up running, check applicationinsights.log in the same folder as the java gent jar, it should tell you which version it's using. Ping me if you still have issues.

**Comment by heyams** [comment]
@tijmenamsing you will need to upload your java app to the same path: D:\home\site\wwwroot\ before restarting and the app name needs to be "**app.jar**".  It doesn't work for any other names.

**Comment by tijmenamsing** [comment]
@heyams thanks for your help!
I can see logs in app insights now but I would like to understand what the minimum setup requirements are for both versions since I feel like I'm mixing up stuff now. I also don't see an applicationinsights.log, why would that be?

1. Is manually uploading the agent and setting JAVA_OPTS only necessary if I want 3.0.3?
2. If for 3.0.2 I only need to set the app settings like you said, will it automatically upgrade to 3.0.3 later on?
3. Renaming the .jar file to app.jar for all my apps requires some work, is there no other way?

Right now I got the following settings:

- XDT_MicrosoftApplicationInsights_Java -> 1
- ApplicationInsightsAgent_EXTENSION_VERSION -> ~2
- JAVA_OPTS -> -javaagent:D:/home/site/wwwroot/applicationinsights-agent-3.0.3.jar

**Comment by tijmenamsing** [comment]
@heyams, I just found two log files regarding app insights, but in another directory as you mentioned. The logs indicate that I'm currently using 3.0.2

- /LogFiles/ApplicationInsights/status/status_RD0003FFDF68FE_9784.json
- /LogFiles/ApplicationInsights/applicationinsights-extension.log

The latter also logs some errors:

```
{"time":"2021-04-08T07:04:16.527Z","level":"INFO","logger":"com.microsoft.applicationinsights.agent.bootstrap.diagnostics.status.StatusFile","message":"Wrote status to file: D:\\home\\LogFiles\\ApplicationInsights\\status\\status_RD0003FFDF68FE_9784.json","properties":{"siteName":"landingzone-dev","ikey":"***","extensionVersion":"~2","sdkVersion":"3.0.2","subscriptionId":"***"}}
{"time":"2021-04-08T07:04:18.374Z","level":"ERROR","logger":"com.microsoft.applicationinsights.internal.perfcounter.JniPCConnector","message":"Failed to fetch current process instance name, process counters for for the process level will not be activated.","properties":{"operation":"Startup","siteName":"landingzone-dev","ikey":"***","extensionVersion":"~2","sdkVersion":"3.0.2","subscriptionId":"***"}}
{"time":"2021-04-08T07:04:18.452Z","level":"WARN","logger":"com.microsoft.applicationinsights.internal.perfcounter.JniPCConnector","message":"Performance coutner registration failed for Processor \\ % Processor Time [_Total]","properties":{"operation":"Startup","siteName":"landingzone-dev","ikey":"***","extensionVersion":"~2","sdkVersion":"3.0.2","subscriptionId":"***"}}
{"time":"2021-04-08T07:04:18.468Z","level":"ERROR","logger":"com.microsoft.applicationinsights.internal.perfcounter.ProcessBuiltInPerformanceCountersFactory","message":"Failed to create WindowsPerformanceCounterAsPC: 'java.lang.Exception: Cannot translate instance name: Unknown current instance name'","properties":{"operation":"Startup","siteName":"landingzone-dev","ikey":"***","extensionVersion":"~2","sdkVersion":"3.0.2","subscriptionId":"***"}}
{"time":"2021-04-08T07:04:35.046Z","level":"INFO","logger":"com.microsoft.applicationinsights.agent","message":"ApplicationInsights Java Agent 3.0.2 started successfully","properties":{"operation":"Startup","siteName":"landingzone-dev","ikey":"***","extensionVersion":"~2","sdkVersion":"3.0.2","subscriptionId":"***"}}
{"time":"2021-04-08T07:04:35.046Z","level":"INFO","logger":"applicationinsights.extension.diagnostics","message":"Application Insights Codeless Agent 3.0.2 Attach Successful","properties":{"operation":"Startup","siteName":"landingzone-dev","ikey":"***","extensionVersion":"~2","sdkVersion":"3.0.2","subscriptionId":"***"}}
{"time":"2021-04-08T07:04:35.796Z","level":"INFO","logger":"com.microsoft.applicationinsights.agent.bootstrap.diagnostics.status.StatusFile","message":"Wrote status to file: D:\\home\\LogFiles\\ApplicationInsights\\status\\status_RD0003FFDF68FE_9784.json","properties":{"siteName":"landingzone-dev","ikey":"***","extensionVersion":"~2","sdkVersion":"3.0.2","subscriptionId":"***"}}
{"time":"2021-04-08T07:53:08.834Z","level":"INFO","logger":"com.microsoft.applicationinsights.agent.bootstrap.diagnostics.status.StatusFile","message":"Wrote status to file: D:\\home\\LogFiles\\ApplicationInsights\\status\\status_RD0003FFDF68FE_2864.json","properties":{"siteName":"landingzone-dev","ikey":"***","extensionVersion":"~2","sdkVersion":"3.0.2","subscriptionId":"***"}}
{"time":"2021-04-08T07:53:10.507Z","level":"ERROR","logger":"com.microsoft.applicationinsights.internal.perfcounter.JniPCConnector","message":"Failed to fetch current process instance name, process counters for for the process level will not be activated.","properties":{"operation":"Startup","siteName":"landingzone-dev","ikey":"***","extensionVersion":"~2","sdkVersion":"3.0.2","subscriptionId":"***"}}
{"time":"2021-04-08T07:53:10.616Z","level":"WARN","logger":"com.microsoft.applicationinsights.internal.perfcounter.JniPCConnector","message":"Performance coutner registration failed for Processor \\ % Processor Time [_Total]","properties":{"operation":"Startup","siteName":"landingzone-dev","ikey":"***","extensionVersion":"~2","sdkVersion":"3.0.2","subscriptionId":"***"}}
{"time":"2021-04-08T07:53:10.616Z","level":"ERROR","logger":"com.microsoft.applicationinsights.internal.perfcounter.ProcessBuiltInPerformanceCountersFactory","message":"Failed to create WindowsPerformanceCounterAsPC: 'java.lang.Exception: Cannot translate instance name: Unknown current instance name'","properties":{"operation":"Startup","siteName":"landingzone-dev","ikey":"***","extensionVersion":"~2","sdkVersion":"3.0.2","subscriptionId":"***"}}
{"time":"2021-04-08T07:53:27.630Z","level":"INFO","logger":"com.microsoft.applicationinsights.agent","message":"ApplicationInsights Java Agent 3.0.2 started successfully","properties":{"operation":"Startup","siteName":"landingzone-dev","ikey":"***","extensionVersion":"~2","sdkVersion":"3.0.2","subscriptionId":"***"}}
{"time":"2021-04-08T07:53:27.645Z","level":"INFO","logger":"applicationinsights.extension.diagnostics","message":"Application Insights Codeless Agent 3.0.2 Attach Successful","properties":{"operation":"Startup","siteName":"landingzone-dev","ikey":"***","extensionVersion":"~2","sdkVersion":"3.0.2","subscriptionId":"***"}}
{"time":"2021-04-08T07:53:29.005Z","level":"INFO","logger":"com.microsoft.applicationinsights.agent.bootstrap.diagnostics.status.StatusFile","message":"Wrote status to file: D:\\home\\LogFiles\\ApplicationInsights\\status\\status_RD0003FFDF68FE_2864.json","properties":{"siteName":"landingzone-dev","ikey":"***","extensionVersion":"~2","sdkVersion":"3.0.2","subscriptionId":"***"}}
```

**Comment by heyams** [comment]
`Right now I got the following settings:`

`XDT_MicrosoftApplicationInsights_Java -> 1`
`ApplicationInsightsAgent_EXTENSION_VERSION -> ~2`
`JAVA_OPTS -> -javaagent:D:/home/site/wwwroot/applicationinsights-agent-3.0.3.jar`

That makes sense.  When you have these two env vars 'XDT_MicrosoftApplicationInsights_Java' and 'ApplicationInsightsAgent_EXTENSION_VERSION', it will use the version that is currently integrated with App Services, which is 3.0.2.  When you set 'JAVA_OPTS' **alone**, it will use whatever the version you have uploaded. There is no workaround for manual upload.  "app.jar" is required by App Services. Please use whatever the version that has been integrated with App Services.  It will get updated automatically when they roll out a new version of Site Extension.

**Comment by wanttoh** [comment]
@heyams Good day sir, [the doc](https://docs.microsoft.com/en-us/azure/azure-monitor/app/azure-web-apps?tabs=java#enable-agent-based-monitoring) you provided also said app service hasn't support. `The automatic integration is not yet available for App Service`. Let's assume for now that the documentation is outdated. 

Then my question is, how to upload 'applicationinsights-agent-3.0.3.jar' to azure app service or where is the  'App Services Site Extension' you said above? I mean that if I need to use this codeless monitor for my application, at least I need to use this jar file, I can set it in my local machine, but I don't know how to set it in azure.

 And then according to the tutorial offered by microsoft, we can create a file named 'applicationinsights.json' to point the agent to your Application Insights resource, could you pls describe how to create this file? I created an azure web app(Java 8, java se container and s1 tie) to deploy my java application. I didn't create vm in azure. 

Thanks in advance.

**Comment by tijmenamsing** [comment]
@wanttoh I was able to to manually upload applicationinsights-agent-3.0.3.jar using the `App Service Editor (Preview)` blade of the app service. You can also get there directly with this link: https://[app-name].scm.azurewebsites.net/dev/wwwroot/. Right click and then choose Upload Files. You can do the same for the applicationinsights.json file. If you want to automate deployment, I think you should be able to include them in your build artifact.

**Comment by tijmenamsing** [comment]
@heyams I'm opting for version 3.0.2 since that doesn't require me to manually upload the agent. The simplest setup I found is by setting these two application settings:

- XDT_MicrosoftApplicationInsights_Java -> 1
- ApplicationInsightsAgent_EXTENSION_VERSION -> ~2

I removed the agent from the app service and removed the `JAVA_OPTS` setting. It also appears to work if the name of my package isn't `app.jar`. I'm interested in why you say that it is required by app service?

**Comment by heyams** [comment]
Nice, good to know. They might have fixed it in the newer version of app services.  Last time when i did manual testing (a couple of months ago), it had to be 'app.jar'. 
Since 3.0.3-BETA.2, we switched native perf counters collection to use [Oshi](https://github.com/oshi/oshi).  Those errors are noise.  I created a work item [9707145](https://msazure.visualstudio.com/One/_sprints/taskboard/TelReachSDKTeam/One/AEP/Cobalt/2104?workitem=9707145) to clean it up.
