### ISSUE TITLE
How to send client IP when tracking an event.

### ISSUE THREAD

**Issue by hemikak** [microsoft/ApplicationInsights-Java#1618]
I am using the java client in a server to send azure events to azure application insights. The server receives the client's IP using the http request's `X-Forwarded-For` header, but how do I add the client's IP to the app insights event ? I couldnt find a way to attach the client IP to the event.

This is my code:
```
TelemetryConfiguration configuration = TelemetryConfiguration.createDefault();
TelemetryClient telemetry = new TelemetryClient(configuration);
telemetry.getContext().setInstrumentationKey("XXXXXX");
Map<String, String> props = new HashMap<>();
props.put("foo", "bar");
Map<String, Double> metrics = new HashMap<>();
telemetry.trackEvent("temp-cmd", props, metrics);
telemetry.flush();
```

**Describe the solution you would like**
To be able to send the client's IP to the event so that geographical data can be shown using a dashboard in azure.

**Describe alternatives you have considered**
Describe any alternative solutions or features you've considered.

**Additional context**

**Comment by heyams** [comment]
@hemikak can you try `telemetry.getContext().getLocation().setIp(...)`? Hope that helps.

**Comment by hemikak** [comment]
Thank you @heyams !
