### ISSUE TITLE
Spring webclient instrumentation

### ISSUE THREAD

**Issue by konjp** [microsoft/ApplicationInsights-Java#1640]
We have project where we using java 11, spring boot(webclient/webflux/netty), Application insights agent 3.0.3.

If we specify custom traceparent header in webclient, auto-instrumentation from application insights agent appends additional value to traceparent header:
`traceparent: 00-4bf92f3577b34da6a3ce929d0e0e4736-b9c7c989f97918e1-01, 00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01` .

Is this expected behavior? Problem with this that service which is called by webclient now returns 400, because `traceparent `header is invalid.

@PavelKhatsimtsau I can see that you managed to disable webclient instrumentation with "_otel.instrumentation.spring.webflux.client.enabled=false_", but we could not to disable it, we still see instrumentation in application insights. Is there some additional things that needs to be done to disable this instrumentation?

**Comment by trask** [comment]
hi @konjp! this is a known issue that was recently fixed upstream https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2727

I will pull that into our distribution and provide a link to SNAPSHOT release with the fix later today for you to try out.

**Comment by konjp** [comment]
@trask What is after that fix expected behavior? Who will have precedence, header set by client or auto-instrumentation?

Is it possible to disable auto-instrumentation for http clients? For example, this bug made that we temporally have to disable agent completely.

**Comment by trask** [comment]
hey @konjp, it looks like the agent is setting it last (and was using addHeader previously, but with the update will use setHeader), and so the agent will overwrite the value you set.

why are you needing to set a different traceparent header? is the agent not propagating the correct traceparent on its own? there are other options to influence the traceparent that the agent uses if you can describe the issue you are having a bit more

**Comment by konjp** [comment]
Service that we call has the API that clearly says that traceparent header needs to be provided in request. It is correct that auto-instrumentation creates syntactically correct traceparent header, but that creates direct dependency on the agent. I think that should not be a case, and bits the fundamental purpose of using agents.

And that dependency will be so hidden, and only person that written code first will know what is going on, and where that header is coming from.

One more example in test cases, f.e. using Hoverfly to simulate request/response, how that header will be set, if client is not in charge to set that header?

**Comment by trask** [comment]
is it ok if the agent overwrites the `traceparent` when it is enabled? the agent's `traceparent` should be more correct (propagated from upstream requests)

**Comment by konjp** [comment]
I did not quite understand exatcly wht you mean here?
> is it ok if the agent overwrites the `traceparent` when it is enabled? 


In this concrete case that I'm working now, this is first call(start of trace), therefore I think it should take traceparent header that I supplied, and propagate further.
> the agent's `traceparent` should be more correct (propagated from upstream requests)

**Comment by trask** [comment]
another reason to prefer the agent's traceparent header (when the agent is running), is that will match the telemetry (traceId/spanId) that the agent captures and that you can view in the Portal

is there a specific reason to prefer the traceparent that you are setting in the code when the agent is running?

**Comment by konjp** [comment]
It will also do the same if it honors the traceparent that I set, remember this is start of trace, and it just as if it propagates from some upstrem request.
> another reason to prefer the agent's traceparent header (when the agent is running), is that will match the telemetry (traceId/spanId) that the agent captures and that you can view in the Portal


I have case where I do not one to run telemetry/agent in out test Azure subscription, or on my local developer machine. If agent is not running, application fails right now.
> is there a specific reason to prefer the traceparent that you are setting in the code when the agent is running?

Why application should have direct dependency on agent?

**Comment by trask** [comment]
I'm agreeing with you that you should set the traceparent manually so that it works without the java agent.

But asking if it's ok for the java agent to overwrite that traceparent when it is enabled, so that the java agent can make sure to propagate (and report back to the Portal) correct distributed tracing telemetry?

**Comment by konjp** [comment]
No, I do not think it should overwrite header. Also, in scenario where this client call is in middle of upstream call. If someone specify that header manual, and brakes the trace, it is his/her decision to do so. Auto-instrumentation should not play smart there, it should honor always manually entered header. Some people can only learn on hard way :-).

> But asking if it's ok for the java agent to overwrite that traceparent when it is enabled, so that the java agent can make sure to propagate (and report back to the Portal) correct distributed tracing telemetry?

**Comment by trask** [comment]
> If someone specify that header manually, and brakes the trace, it is his/her decision to do so.

If you want to create a new trace for your outgoing http request, you can do that using OpenTelemetry API (https://github.com/microsoft/ApplicationInsights-Java/wiki/OpenTelemetry-API-support-(3.0)), and the java agent will respect that.

Do you have a specific need to break the trace and start a new one for that outgoing http request?

**Comment by konjp** [comment]
I did ask different question about more complex scenario for [distributed trace](https://github.com/microsoft/ApplicationInsights-Java/issues/1634).

Now I'm focused that get application working and have logging again. So for now, I do not need to brake the trace, but I'm still thinking why auto-instrumentation would ignore perfectly legal traceparent header?

If it is not there, auto-intrumentation can kick in and create that header.

**Comment by trask** [comment]
hey @konjp, please have a try with this SNAPSHOT release, and let us know how it goes! https://github.com/microsoft/ApplicationInsights-Java/files/6347146/applicationinsights-agent-3.0.4-BETA-SNAPSHOT.jar.zip

**Comment by konjp** [comment]
@trask Unfortunately, this 3.0.4 snapshot release did not resolve double header problem. Still getting both headers, header that I supplied and header supplied by auto-instrumention.

**Comment by trask** [comment]
@konjp can you provide a repro? not sure what's going on in your case, but we can definitely fix if we get a repro

**Comment by konjp** [comment]
Sorry, it is private repository. But, I'm not doing anything special. Creating spring-boot bean that injects WebClient, and call other web service with ._block()_ . Nothing more then that.

**Comment by trask** [comment]
Can you create a sample project that does what you are describing, and exhibits the same behavior that you are seeing in your application?

**Comment by konjp** [comment]
Today, I'm booked, therefore I will not able to do it.

It would be huge help, if I can temporally disable http clients tracing, because now I have reverted to use logging on old way with application insights sdk 2.6.

**Comment by konjp** [comment]
@trask I created small [demo project](https://github.com/konjp/springBootWebClientInstrumentationHeadersBug) When you running it  together with agent, you should be able to see in console that traceparent header has two values.

**Comment by trask** [comment]
perfect, thank u, this is really helpful ❤️

**Comment by trask** [comment]
I pushed a fix upstream, will merge here and post a new SNAPSHOT release tomorrow

**Comment by trask** [comment]
SNAPSHOT release available with this fix: [applicationinsights-agent-3.0.4-BETA-SNAPSHOT.jar.zip](https://github.com/microsoft/ApplicationInsights-Java/files/6362473/applicationinsights-agent-3.0.4-BETA-SNAPSHOT.jar.zip)

Thanks for reporting this, great find!
