### ISSUE TITLE
HTTP Verb is not captured in Spring boot

### ISSUE THREAD

**Issue by VikramNisarga** [microsoft/ApplicationInsights-Java#1677]
**Is your feature request related to a problem? Please describe.**
Our application uses HTTP verbs to differentiate requests i.e creating objects vs updating objects etc

**Describe the solution you would like**
Like other application insight agents(.net sdk) HTTP verb should be captured as part of the request

**Comment by trask** [comment]
hey @VikramNisarga! This behavior has been changed in the 3.1.0 release to now match the other Application Insights SDK behavior.
