### ISSUE TITLE
Update docs and release notes before a new version is released

### ISSUE THREAD

**Issue by jakubnabrdalik** [microsoft/ApplicationInsights-Java#1682]
Yesterday ai agent got a 3.1.0 release. I've found out about it  looking at maven central.

There is no release log at 
https://docs.microsoft.com/en-us/azure/azure-monitor/app/release-notes
or anywhere I searched

Docs still point out to old 3.0 version
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-get-started?tabs=maven

Please use Spring approach to release notes: create documentation for a Snapshot version and make it available before the release. Also please create release notes.

**Comment by MS-jgol** [comment]
@jakubnabrdalik The release notes point to this GitHub page, the release is out there:
https://github.com/Microsoft/ApplicationInsights-Java/releases

You are right, the public docs are not there yet - going through a release process, which takes a bit more time than expected at this point. The changes should be merged any time now.

**Comment by trask** [comment]
Microsoft docs are updated: https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent

Release notes are available in this repo, both on the releases page: https://github.com/microsoft/ApplicationInsights-Java/releases and in the [CHANGELOG.md](https://github.com/microsoft/ApplicationInsights-Java/blob/master/CHANGELOG.md)

**Comment by jakubnabrdalik** [comment]
Thank you.
