### ISSUE TITLE
Set cloud role name using Java system property

### ISSUE THREAD

**Issue by paveljakov** [microsoft/ApplicationInsights-Java#1684]
**Is your feature request related to a problem? Please describe.**
Currently we use Application Insights e2e transaction logging on all our environments, even for local development. Now we have an issue (annoyance) that we have to provide cloud role name of application either using Environment Variable (does not work when you run multiple applications locally) or using JSON configuration file. It would be nice if it would be also possible to set application name (cloud role name) using Java system property, just like we can for configuration file path.

**Describe the solution you would like**
Ability to set cloud role name using Java system property, i.e. `applicationinsights.role.name`.

**Comment by trask** [comment]
> does not work when you run multiple applications locally

hey @paveljakov! are you able to set the environment variable in the startup script for each java process separately?

**Comment by paveljakov** [comment]
Hi @trask,

As mentioned in #1685, we are pushing all developers to use AI before creating PRs to analyze how their changes impact the system overall and I would like to make their life as simple as possible. Some people open multiple services at the same time, some open single one each time. Asking to configure Environment Variables for each run configuration is not ideal and can lead to misconfigurations. Having ability to provide Cloud Role Name using Java system property would be simpler.

**Comment by trask** [comment]
this is supported now in [3.2.0-BETA.2](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.2.0-BETA.2)
