### ISSUE TITLE
Operation Id not propagating to WebFlux requests when set on ThreadContext

### ISSUE THREAD

**Issue by jhevans** [microsoft/ApplicationInsights-Java#1686]
Hi, I'm trying to correlate across an AWS SQS queue by setting the OperationId in the receiving application and have tried unsuccessfully to use [this method](https://github.com/microsoft/ApplicationInsights-Java/issues/1442#issuecomment-763250512_) suggested in another issue.

Unfortunately this doesn't seem to apply the operationId for subsequent requests from the service. We're using WebFlux, so intuitively setting anything on the ThreadContext feels like it's not going to work but I'm not sure if passing that context to the new thread is something that is/should be managed by the library code?

We're running agent v3.1.0 so I also had a go at directly using the opentelemetry API but again no joy  - I'm guessing for similar reasons 😕

```final var context = SpanContext.createFromRemoteParent(operationId, operationId, TraceFlags.getDefault(), TraceState.getDefault());
        try (Scope ignored = Context.root().with(Span.wrap(context)).makeCurrent()){
            process(message, messageId); // This triggers calls using webflux
        }
```

Is what I'm trying to do possible using the current API?

**Comment by trask** [comment]
hi @jhevans, sorry for the late reply, if you can share a small repro of what you are trying to do, that would probably be the easiest way to understand what you are doing and how to make it work
