### ISSUE TITLE
Log HTTP Headers, Request/Response Body as Custom Request Properties

### ISSUE THREAD

**Issue by zoomingrocket** [microsoft/ApplicationInsights-Java#1693]
**Is your feature request related to a problem? Please describe.**
We use extensive custom HTTP Headers for various API transactions and would like to trace or have visibility into App Insights and visualize as part of the Request Properties panel

**Describe the solution you would like**
Allow configuration to enable logging for list of HTTP headers specified or if possible log all headers, Request/Response Body as custom Request Properties

**Describe alternatives you have considered**
Currently, we are trying to print headers, body as an INFO in STDOut to get captured in detailed telemetry and then locate transactions via transaction search

**Additional context**
Current Use: Java Agent - 3.0.3 GA
Request Properties Panel - Custom Properties

![image](https://user-images.githubusercontent.com/2420449/118728891-e7014e80-b802-11eb-8f7b-cbf0d5bf1379.png)

**Comment by trask** [comment]
hey @zoomingrocket! have you seen this example for adding custom dimensions to the captured requests? https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#add-request-custom-dimensions-using-the-2x-sdk

**Comment by zoomingrocket** [comment]
@trask - We are using java agent-based v3.0.3 and based on that JSON for custom dimension requires environment variable? Just trying to understand how we can make it dynamic to collect with jvm execution?

`{
  "customDimensions": {
    "mytag": "my value",
    "anothertag": "${ANOTHER_VALUE}"
  }
}`

**Comment by trask** [comment]
hey @zoomingrocket, are you able to modify the code in the application? if so, the link above describes how to use the 2.x SDK to send add custom dimensions to the request that is auto-collected by the 3.0 agent

**Comment by zoomingrocket** [comment]
@trask - No scope of plugging 2.x SDK as its proprietary platform where we are using in JavaAgent. Hoping we can allow few headers to log via JSON file custom dimension?

**Comment by trask** [comment]
Got it, so no ability to modify the app, and you need pure codeless configuration option for this.
