### ISSUE TITLE
Application Insights shows GET calls while my code does not have any such calls being made

### ISSUE THREAD

**Issue by vishalgoyal16444** [microsoft/ApplicationInsights-Java#1703]
We have integrated Azure Application insights with our bot built using Azure bot framework using node.JS and typescript. Everything looks fine and we can see telemetry data flowing in. In the failures section, we can see Operation name "GET /api/messages" showing repeated times - one failed call (405) and one success call (200).

But we have no GET operation being done on "/api/messages" in our code. We only have "POST" operations.
We are unable to understand why telemetry shows GET operation and one as failed and one as success.

operation_SyntheticSource column is NULL for all these records.
[query-GET.xlsx](https://github.com/microsoft/ApplicationInsights-Java/files/6520197/query-GET.xlsx)

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version:
 - OS type and version:
 - Application Server type and version (if applicable):
 - Using spring-boot?
 - Additional relevant libraries (with version, if applicable):

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

**Comment by trask** [comment]
hey @vishalgoyal16444! this is the Application Insights Java repo, it sounds like you are looking for https://github.com/microsoft/ApplicationInsights-node.js or https://github.com/microsoft/ApplicationInsights-JS?
