### ISSUE TITLE
Public roadmap of proposed upcoming changes

### ISSUE THREAD

**Issue by stevendick-swissre** [microsoft/ApplicationInsights-Java#1722]
# Context
There's no visibility on the project's direction and proposed features.

This is frustrating as while we love the simplicity of the agent, we're currently getting crushed by costs associated with excessive metrics volume. We lack information to see if it's worthwhile sticking with the agent or we need a different approach for metric capture.

# Goal
Visibility on committed features and at least a rough target time period.

**Comment by MS-jgol** [comment]
@stevendick-swissre 
Will be happy to help out and see how we can help with the cost management, Have you had a chance to explore the sampling and sampling overrides?
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-sampling-overrides

**Comment by trask** [comment]
@MS-jgol this is the issue: #1665

@stevendick-swissre I'll get back to you later today with an update on that issue

**Comment by stevendick-swissre** [comment]
We already switch off Kafka and have changed the sampling frequency to 5 mins. This helps, but still isn't sufficient to gain control over the volume.

**Comment by MS-jgol** [comment]
@stevendick-swissre We have a different thread on this, and the metrics overrides that we recently released should help. 
It would be great to arrange a meeting between our teams. Would you be able to reach out to jgol at microsoft.com?

**Comment by stevendick-swissre** [comment]
@trask has cleared up which integrations are the source of metrics with the agent.

Combined with:
- the agent supporting metric exclusions
- figuring out how to get Spring Boot/Micrometer to conditionally enable/disable metrics

I think we're good for now and can now gain control over our App insights ingestion costs.

I may be back in another ticket to learn how to control the volume of dependencies, as I suspect that will be the next largest volume of data captured by the agent after metrics.

**Comment by trask** [comment]
Closing, but please feel free to post further comment or a new issue.
