### ISSUE TITLE
OTEL Trace propagation to Otel collector

### ISSUE THREAD

**Issue by robododge** [microsoft/ApplicationInsights-Java#1727]
Hi,

I see that the opentelemtry project's javaagent is bundled straight into the applicationinsights-agent-3.1.0.jar    Does this mean we can configure custom exports to otel-sepecific collectors such as? :

```
-Dotel.javaagent.debug=true \
-Dotel.traces.exporter=zipkin \
-Dotel.metrics.exporter=none \
-Dotel.exporter.zipkin.endpoint=<endpoint name> \
-Dotel.resource.attributes=service.name=<SERVICE_NAME>
```

**Comment by trask** [comment]
hey @robododge! the applicationinsights agent only contains an exporter to azure monitor (also the agent replaces the otel configuration layer with its own, and so normal otel agent configuration properties aren't picked up anyways)

**Comment by robododge** [comment]
Thanks @trask .   One more question that will really help, what is the protocol used between agent and azure monitor,  Otlp?  Is it GRPC-based with TLS?    Thanks So much!

**Comment by trask** [comment]
no problem, it sends newline-delimited json (one telemetry record per line) over https
