### ISSUE TITLE
Big increase in ingested volumes (Operations, Dependencies) after upgrade to 3.0.3 (also 3.1.1)

### ISSUE THREAD

**Issue by geertn** [microsoft/ApplicationInsights-Java#1733]
### Expected behavior
I upgraded to 3.1.1-BETA.4 to be able to explore filtering out telemetry as we're looking to reduce costs. I expect the amount of ingested operations to stay more or less the same since I didn't change the configuration.

### Actual behavior
The amount of ingested Operations (same pattern for dependencies) went up big. If I pick 1 particular Operation Name (API endpoint) this was from about 200-300 request count to 20000-30000 request count. See screenshot. It seems like Sampling isn't working at all since our sample rate was 1%.

### To Reproduce
Upgrade from `applicationinsights-agent-3.0.2.jar` to `applicationinsights-agent-3.0.3.jar` or `applicationinsights-agent-3.1.1-BETA.4.jar`

### System information
Please provide the following information:
 - SDK Version: Java Agent 3.0.3 / 3.1.1-BETA.4
 - OS type and version:

cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.7 LTS"

openjdk version "1.8.0_282"

 - Application Server type and version (if applicable):

Jetty 9.4.8.v20171121

 - Using spring-boot? no
 - Additional relevant libraries (with version, if applicable):

### Config

```
cat applicationinsights.json 
{
    "connectionString": "InstrumentationKey=xxx",
    "role": {
        "name": "Azure xxx API"
    },
    "sampling": {
        "percentage": 1
    },
    "heartbeat": {
        "intervalSeconds": 60
    },
    "instrumentation": {
        "logging": {
            "level": "ERROR"
        }
    },
    "selfDiagnostics": {
        "level": "INFO",
        "destination": "file",
        "file": {
            "path": "applicationinsights.log",
            "maxSizeMb": 5,
            "maxHistory": 1
        }
    }
}
```

### Screenshots

Normal Volume:

![old-appinsight-302](https://user-images.githubusercontent.com/4923332/121331292-04639d00-c917-11eb-8204-742027c9af10.png)

Increased Volume:

![new-appinsights-311b4](https://user-images.githubusercontent.com/4923332/121331289-03cb0680-c917-11eb-9822-57294ff4d508.png)

**Comment by trask** [comment]
hey @geertn!

> It seems like Sampling isn't working at all since our sample rate was 1%.

the count on that screen takes the sampling rate into consideration (so it gives you approx the real count for your application).

you can check the raw telemetry by going to "logs" and querying the requests table:

![image](https://user-images.githubusercontent.com/218610/121846032-31a7a680-cc9b-11eb-8120-c4dbd099ed97.png)

let us know if this answers your question or if you are still seeing issues.

**Comment by geertn** [comment]
Thanks for your reply, I still see the issue:

![gh-requests](https://user-images.githubusercontent.com/4923332/121884323-16787d80-cd13-11eb-980f-31268fe9422a.png)

**Comment by trask** [comment]
hi @geertn, in the above query, you have `sum(itemCount)`, which still takes sampling into consideration.

e.g. when sampling is set to 1%, all of the telemetry records have `itemCount = 100`, because each one represents approximately 100 records

**Comment by geertn** [comment]
Hi @trask thanks for your patience :) Even though the query is returning the amount with sampling taken into consideration I still wouldn't expect the numbers go up when changing to 3.1.1 even though I'm not changing the sampling rate. 

I changed the query into
```
requests
| summarize totalCount=count() by bin(timestamp, 1m)
| render timechart
```

The peak numbers below (the peak being 3.1.1) basically correlates with the amount of requests this process is actually handling.

Result
![gh-screen2](https://user-images.githubusercontent.com/4923332/121958093-90385780-cd63-11eb-944e-d495681c4d0b.png)

**Comment by trask** [comment]
Interesting, I'm not sure what's going on, I just tried locally with sampling percentage 1, and it's working for me as expected on both 3.0.2 and 3.1.1 (didn't try any other versions).

Is there any chance you could put together a repro that I can run and troubleshoot?

**Comment by geertn** [comment]
I see it consistently in production but reproducing locally didn't work yet. I'll let you know if I can set something up useful.

**Comment by geertn** [comment]
Weirdly enough we can only reproduce it consistently in production. I'll spend more time on it, but if you are interested I would be happy to show you in a shared screen session. Something that might be related is a log message that we only see when running with 3.1.1 and not with 3.0.2:

```
2021-06-16 15:18:05.959+02 DEBUG i.o.j.i.api.SafeServiceLoader - Unable to load instrumentation class: io/opentelemetry/javaagent/instrumentation/httpclient/HttpClientInstrumentationModule has been compiled 
by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

We run this with `openjdk version "1.8.0_282"` and apparently run into a compatibility issue between jdk 11 and 8.

**Comment by trask** [comment]
hey @geertn, this debug message is expected in 3.1.1 because it now includes [Java 11 HttpClient](https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpClient.html) instrumentation

keep us posted on your findings
