### ISSUE TITLE
Possible duplicate Kafka metrics

### ISSUE THREAD

**Issue by stevendick-swissre** [microsoft/ApplicationInsights-Java#1734]
### Context
My project is using Kafka via Spring Boot, which in turn uses the Spring Kafka library.

We have disabled for now the Application Insights integration with Kafka, but we are still seeing Kafka metrics published to App Insights.

Further investigation shows that Spring Kafka is adding the Kafka metrics to Micrometer. So while the agent isn't capturing the Kafka metrics from Kafka itself, it is getting the same metrics from the Micrometer integration.

I assume that if the Kafka integration isn't disabled, the agent might be publishing Kafka metrics from the Kafka libraries and from Micrometer - potentially duplicating the metrics.

We have now also disabled Kafka metrics sourced from Micrometer.

I'm wondering if this isn't a general problem for metrics that are captured directly by the agent from libraries and Spring Boot is also automatically adding to Micrometer.

### Desired outcome
1. Update the documentation to let people know about Kafka metrics coming from Micrometer as well as the Kafka integration
2. You find an automatic solution to avoid duplicate metrics (no idea if this if practical)

**Comment by trask** [comment]
> I assume that if the Kafka integration isn't disabled, the agent might be publishing Kafka metrics from the Kafka libraries and from Micrometer - potentially duplicating the metrics.

The kafka integration doesn't capture these metrics, so I don't think you should see duplicates, but let us know if you are seeing duplicates for some reason.

**Comment by stevendick-swissre** [comment]
I haven't confirmed duplicates, it was a suspicion assuming metrics were captured both from Micrometer and the Kafka libs.

If the kafka integration doesn't capture metrics, what does it capture? Just the dependencies?

Does the agent only capture metrics from Micrometer?

**Comment by trask** [comment]
> If the kafka integration doesn't capture metrics, what does it capture? Just the dependencies?

it captures dependencies (producers) and requests (consumers), and propagates distributed tracing headers so that they are linked as part of a single transaction (e.g. in the Application Map and End-to-end transaction view).

> Does the agent only capture metrics from Micrometer?

what you see in the `customMetrics` table? yes, those are only from JMX metrics that have been configured (plus a few that are default), and from Micrometer

**Comment by stevendick-swissre** [comment]
Thanks for clarifying.
