### ISSUE TITLE
Configuration to disable default JVM perfcounters

### ISSUE THREAD

**Issue by rieckpil** [microsoft/ApplicationInsights-Java#1738]
**Is your feature request related to a problem? Please describe.**

We're using Spring Boot (+ Actuator) and the Azure Java Agent 3.1.0 to expose metrics, logs, and other telemetry data. Currently, we emit metric information about the JVM (threads, memory, GC, etc.) twice: once by the AI Java Agent itself (I guess the internal package is called [`perfcounter`](https://github.com/microsoft/ApplicationInsights-Java/tree/02898af9be35e6fa1b62bf39662007ec1eb8d3b1/core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter)) and from the Spring Boot application.

This is redundant information and adds unnecessary $$$ to our monthly bill.

![grafik](https://user-images.githubusercontent.com/14176609/121478502-611f9000-c9c9-11eb-82b9-9ef32781b150.png)

**Describe the solution you would like**

Provide a boolean configuration flag to turn on/off the automatically collected performance counters. We would like to rely solely on the Micrometer metrics and don't emit duplicated JVM performance stats.

Something similar to the configuration for other automatically detected telemetry data would be great:

```json
{
  "role": {
    "name": "XYZi"
  },
  "instrumentation": {
    "perfcounter": {
      "enabled": false
    },
    "micrometer": {
      "enabled": true
    }
  }
}
```

**Describe alternatives you have considered**

- As a workaround, one could use telemetry filtering (?) to achieve this?
- Disable the JVM metrics as part of the Actuator

**Additional context**

**Comment by trask** [comment]
hey @rieckpil! check out the just recently released metrics filters: https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-telemetry-processors#metric-filter

**Comment by rieckpil** [comment]
Thanks for getting back so quickly, @trask.

So the solution could be to list all internal perf counters like this?

```json
"processors": [
  {
    "type": "metric-filter",
    "exclude": {
      "matchType": "strict",
      "metricNames": [
        "Loaded Class Count",
        "Suspected Deadlock Threads",
        "..."
      ]
    }
  }
]
```

The only _downside_ I see with this approach is that potential renamings of the metric name or when new perf counters are added could _break_ this.

I'll give it a try and list all perf counters in the `exclude` field 👍

**Comment by rieckpil** [comment]
I managed to exclude the perfcounters collected by the Application Insights Agent itself with the following `applicationinsights.json` and AI 3.1.1.

```json
{
  "preview": {
    "processors": [
      {
        "type": "metric-filter",
        "exclude": {
          "matchType": "strict",
          "metricNames": [
            "Loaded Class Count",
            "Suspected Deadlocked Threads",
            "Current Thread Count",
            "% Of Max Heap Memory Used",
            "Heap Memory Used (MB)",
            "GC Total Count",
            "GC Total Time"
          ]
        }
      }
    ]
  }
}
```

@trask I'm closing this ticket. Introducing a boolean to toggle on/off such out-of-the-box metrics might be still beneficial to avoid manual efforts whenever there's a new perfcounter.
