### ISSUE TITLE
Operation Names not in new format with 3.1.1 GA Agent

### ISSUE THREAD

**Issue by zoomingrocket** [microsoft/ApplicationInsights-Java#1752]
### Expected behavior
Not all Operation names are in format of Http Method - Path, only some reflecting new format
E.g. POST /vet.html

### Actual behavior
Old v3.0 Agent Behavior when preview option for includeHttpMethodInOperationName is set
 "preview": {
    "includeHttpMethodInOperationName": true
}
i.e. HTTP POST or HTTP GET
### To Reproduce
Upgrade Agent JAR to 3.1.1 and restart JVM

#### Sample Application
N/A - Proprietary Middleware Platform

### System information
Please provide the following information:
 - SDK Version: 3.1.1 GA Agent
 - OS type and version: Linux, CentOS 7

### Logs
2021-06-22 18:50:25.842Z INFO  c.m.applicationinsights.agent - ApplicationInsights Java Agent 3.1.1 started successfully

### Screenshots
![image](https://user-images.githubusercontent.com/2420449/122984357-ebbda300-d36a-11eb-9c57-70470d6da1c8.png)

**Comment by trask** [comment]
hey @zoomingrocket! what server web framework(s) are you using?

is it the same server web framework in both the cases where its capturing the route, and the cases where its capturing `HTTP GET`?

did this work in a prior Application Insights Java version?

**Comment by zoomingrocket** [comment]
I will need to dig a bit for underlying libraries as it is proprietary
middleware platform.

With v3.0 GA behavior was just url paths as operation name before we added
preview option to switch to HTTP Method operation name and with v3.1.1 we
were going to get Method + Path so were excited but seeing partial behavior.

Anything i can print out in diagnostic log for more info?

**Comment by trask** [comment]
If you can enable agent debug logging:

```
{
   "selfDiagnostics": {
      "level": "debug"
   }
}
```

and repro and attach the full debug log, that will give me some clues where to look next.
