### ISSUE TITLE
In Spring boot, Error controller(/error) will shown in the failure requests tab instead of the actual request URI

### ISSUE THREAD

**Issue by VikramNisarga** [microsoft/ApplicationInsights-Java#1791]
### Expected behavior
In Spring boot if a request is failed, the request URI should be captured 

### Actual behavior
URI of the default error controller is captured

![image](https://user-images.githubusercontent.com/26029452/124340344-2547a700-dbd2-11eb-9425-6aadc1226525.png)

### System information
Please provide the following information:
 - SDK Version: 3.0.1
 - OS type and version: ubuntu 18.04
 - Using spring-boot? yes
 - Additional relevant libraries (with version, if applicable): spring boot 5

**Comment by trask** [comment]
hey @VikramNisarga! I think this may be resolved in 3.1.1, can you give that a try?

**Comment by VikramNisarga** [comment]
Hey @trask, after updating the agent the HTTP verb is getting added to /error but it's still not showing the request URI
[]()![Screenshot_20210706-080008.jpg](https://user-images.githubusercontent.com/26029452/124533710-76ed6d00-de30-11eb-9ede-ef2bb4a3ac0a.jpg)

**Comment by VikramNisarga** [comment]
Closing the issue as its working fine in 3.1.1
