### ISSUE TITLE
Application failed to start when use applicationinsights-spring-boot-starter:2.6.3 due to more than one telemetryConfiguration bean defined

### ISSUE THREAD

**Issue by garridobarrera** [microsoft/ApplicationInsights-Java#1795]
### Expected behavior
Application start successful with more than one bean of type telemetryConfiguration. Is it possible to qualified the parameter telemetryConfiguration in the public class ApplicationInsightsTelemetryAutoConfiguration class?. Suggestion:
```

    @Bean({"internalTelemetryConfiguration"})
    @DependsOn("internalLogger")
    public TelemetryConfiguration telemetryConfiguration() {
    ....
}

   @Bean
    public TelemetryClient telemetryClient(@Qualifier("internalTelemetryConfiguration") TelemetryConfiguration configuration) {
        return new TelemetryClient(configuration);
    }

```

### Actual behavior
I have a project witch export metrics through application insights. In that configuration it have a qualified bean of typ telemetryConfiguration. If I configure the starter applicationinsights-spring-boot-starter to send logs too get the next error. 

Parameter 0 of method telemetryClient in com.microsoft.applicationinsights.autoconfigure.ApplicationInsightsTelemetryAutoConfiguration required a single bean, but 2 were found:
	- telemetryMetricsConfiguration: defined by method 'telemetryConfiguration' in class path resource [XXXXX/AzureMonitorTelemetryConfiguration.class]
	- telemetryConfiguration: defined by method 'telemetryConfiguration' in class path resource [com/microsoft/applicationinsights/autoconfigure/ApplicationInsightsTelemetryAutoConfiguration.class]

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed

### To Reproduce
Define one bean of type TelemetryConfiguration in the spring context and include applicationinsights-spring-boot-starter as dependency project.

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: openjdk 11
 - OS type and version: Ubuntu 20.04
 - Application Server type and version (if applicable): 
 - Using spring-boot? YES , 2.2.13
 - Additional relevant libraries (with version, if applicable):

### Logs
N/A

### Screenshots
N/A

**Comment by trask** [comment]
hey @garridobarrera! I recommend updating to [Application Insights Java 3.x](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent). The applicationinsights-spring-boot-starter no longer exists in 3.x because you get the same easy on-boarding in 3.x now whether you are using spring boot or not.
