### ISSUE TITLE
Spring Boot - AppInsight does not should the Application Map for RestTemplate with HttpClient

### ISSUE THREAD

**Issue by Anand0583** [microsoft/ApplicationInsights-Java#1814]
Hello Team,

I have created 2 microservices using Spring Boot and I am trying to create the Application Map using AppInsights.
But in AppInsight we only see 2 Separate Spring Boot application and they are not connected.

![image](https://user-images.githubusercontent.com/35911769/126896795-02ffe2eb-ddd2-4518-8d8a-9142c2dd8ebf.png)

I have followed all the steps which have been mentioned in the Microsoft Documentation but I am not able to get the Application Map.

Also there is another issue, with using Logback Logs too are not following to AppInsight.

I am able to see the requests flowing to AppInsight but none of the traces are flowing to AppInsight.

Please note that I have masked the "instrumentation-key" on purpose.

Please find github links for the Source Code.

[https://github.com/Anand0583/order-service.git](url)
[https://github.com/Anand0583/customer-service.git](url)

To Test Invoke order-service [http://localhost:8084/order/v1?orderId=99055](url)

Help is much appreciated.

Thanks & Regards,

**Comment by trask** [comment]
hi @Anand0583! can you try with 3.x? https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-upgrade-from-2x

many more things work out-of-the-box now in 3.x

**Comment by Anand0583** [comment]
Hello @trask can you please let me know whether after having the applicationinsights-spring-boot-starter included in the build.gradle should we also add the javaagent

Or only the applicationinsights-spring-boot-starter is sufficient to be added in the spring-boot application.

Thanks & Warm Regards,
Anand

**Comment by trask** [comment]
hey @Anand0583, the spring boot starter is not needed anymore with the 3.x release, you can remove `applicationinsights-spring-boot-starter` and just add the 3.x javaagent

**Comment by Anand0583** [comment]
Thanks @trask but the result is the same even when using 3.x javaagent. TApplication Map between Order-Service and Customer-Service are two distinct components with no relationship.

They are individual spring-boot applications where order-service invokes customer-service via RestTemplate of ApacheHttpClient.

![image](https://user-images.githubusercontent.com/35911769/128053472-82f703df-a070-402a-b4f9-dfcc19c7050b.png)

But when I look into the dependencies inside the logs they are good.

![image](https://user-images.githubusercontent.com/35911769/128058107-a380ceb3-6100-43b6-a0f2-86dfa1cfd5de.png)

Please let me know your comments.

**Comment by trask** [comment]
hey @Anand0583,

I think you might be running into a requirement of the back-end ingestion service that you send data for more than a minute before it correlates.

Can you try sending more requests and see if it starts working?

**Comment by Anand0583** [comment]
Thanks @trask after sending more than 5 requests it correlated. Can you please explain a more on why we did see the correlation earlier. Because there are few services which get only a few transactions in a hour.

![image](https://user-images.githubusercontent.com/35911769/128064590-8604afd0-f382-4c13-972c-7f2d2ec6b9fb.png)

**Comment by trask** [comment]
> there are few services which get only a few transactions in a hour.

I've asked for clarification from the correlation service on the exact limits, and will get back to you.

> Also @trask can you please let me know whether for DotNet Application what will be approach.

Check out https://github.com/microsoft/ApplicationInsights-dotnet#getting-started for getting started with Application Insights .NET.
