### ISSUE TITLE
More documentation/examples for applicationinsights.json

### ISSUE THREAD

**Issue by konstantinblaesi** [microsoft/ApplicationInsights-Java#1815]
**Is your feature request related to a problem? Please describe.**
Upgrading from insights agent 2.x to 3.x

**Describe the solution you would like**
Documentation is not so clear to me
* Is applicationinsights.json replacing AI-Agent.xml ? It seems like it is
* What would the applicationinsights.json look like for this AI-Agent.xml? 
```
<ApplicationInsightsAgent>
    <Instrumentation>
        <BuiltIn enabled="true">
            <MaxStatementQueryLimitInMS>1000</MaxStatementQueryLimitInMS>
        </BuiltIn>
    </Instrumentation>
</ApplicationInsightsAgent>
```

Could I use some telemetry processor in applicationinsights.json as a replacement for MaxStatementQueryLimitInMS ?

**Describe alternatives you have considered**
I have been reading some documentation regarding the insights data model and telemetry processors, but I have no idea how I could verify that my applicationinsights.json makes sense.

**Comment by trask** [comment]
hey @konstantinblaesi!

> Is applicationinsights.json replacing AI-Agent.xml ? It seems like it is

correct

> What would the applicationinsights.json look like for this AI-Agent.xml?
> 
> ```
> <ApplicationInsightsAgent>
>     <Instrumentation>
>         <BuiltIn enabled="true">
>             <MaxStatementQueryLimitInMS>1000</MaxStatementQueryLimitInMS>
>         </BuiltIn>
>     </Instrumentation>
> </ApplicationInsightsAgent>
> ```
> 
> Could I use some telemetry processor in applicationinsights.json as a replacement for MaxStatementQueryLimitInMS ?

`MaxStatementQueryLimitInMS` was related to query plans, which are not captured in 3.x, so there is no comparable setting in 3.x
