### ISSUE TITLE
application insights jar 3.0.1 is throwing a socket timeout

### ISSUE THREAD

**Issue by voollasandeepkumar-wandisco** [microsoft/ApplicationInsights-Java#1816]
we are running  AI agent with our service using -javaagent:/XXXX/XXXX/applicationinsights-agent-3.0.1.jar 

we have observed below error is that something that needs to addressed on our end or yours ?
 
-or can we ignore this ??

Jul 24 07:29:09 frp01 metric-cruncher[50474]: java.net.SocketTimeoutException: Read timed out
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at java.net.SocketInputStream.socketRead0(Native Method)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at java.net.SocketInputStream.read(SocketInputStream.java:171)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at java.net.SocketInputStream.read(SocketInputStream.java:141)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:457)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1332)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:73)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:948)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at com.microsoft.applicationinsights.internal.channel.common.ApacheSender43.sendPostRequest(ApacheSender43.java:79)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.sendSync(TransmissionNetworkOutput.java:162)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutput$1.run(ActiveTransmissionNetworkOutput.java:80)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Jul 24 07:29:09 frp01 metric-cruncher[50474]: at java.lang.Thread.run(Thread.java:748)

**Comment by trask** [comment]
hi @voollasandeepkumar-wandisco! this is an exception connecting to the ingestion service to send telemetry to azure portal. it should have been stored to disk and sent later. more recent versions report this exception message better if you want to upgrade to 3.1.1
