### ISSUE TITLE
Excluding some http requests (health check)

### ISSUE THREAD

**Issue by kasdihacene** [microsoft/ApplicationInsights-Java#1825]
Hello,

I'm trying to exclude and supress some traces reported by the agent, like the http requests `/actuator/health`

![image](https://user-images.githubusercontent.com/25183892/127865772-2be9df5a-7911-4352-ab36-718e6d2ddb26.png)

I updated the version of the agent (now I'm pointing to 3.1.1) and am using the sampling solution on my applicationInsights.xml file like, bellow:

```xml
    <Processor type="PageViewTelemetryFilter">
        <Add name="NotNeededUrls" value="/actuator/health" />
    </Processor>
```
someone can provide me an example of excluding some http requests/filtering the incoming traffic to suppress some traces and dependencies using `applicationInsights.xml` or (AI-agent.xml) configuration ? (I didn't find any sample on the documentation)

Any help is appreciated

Best regards.

**Comment by trask** [comment]
hey @kasdihacene! `ApplicationInsights.xml` and `AI-Agent.xml` are only used by 2.x

for excluding health checks in 3.x, check out https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-sampling-overrides#example-suppress-collecting-telemetry-for-health-checks

**Comment by kasdihacene** [comment]
I have updated the configuration using 3.x version and `applicationinsights.json` file as below: 
```json
{
  "role": {
    "name": "monitoring-app"
  },
  "preview": {
    "sampling": {
      "overrides": [
        {
          "attributes": [
            {
              "key": "http.url",
              "value": "http?://[\\w\\d\\S]+/actuator/health",
              "matchType": "regexp"
            },
            {
              "key": "http.url",
              "value": "GET /sgef-graydon-gateway/actuator/health",
              "matchType": "strict"
            },
            {
              "key": "http.url",
              "value": "https?://[\\w\\d\\S]+/actuator/health",
              "matchType": "regexp"
            }
          ],
          "percentage": 0
        }
      ]
    }
  }
}
```

But the trace of the requests are still here, it seems not working,
is all right with my configuration above ?

![image](https://user-images.githubusercontent.com/25183892/128738482-b7e31e7a-83bb-495b-8593-611004dec1e0.png)

**Comment by trask** [comment]
hey @kasdihacene!

It looks like those regular expressions may not be correct for your urls.

Can you check the regular expressions against your urls using https://regex101.com/?flavor=java to verify?
