### ISSUE TITLE
Performance issue when using applicationinsights-agent-3.1.0.jar

### ISSUE THREAD

**Issue by chen1005** [microsoft/ApplicationInsights-Java#1844]
Hello,

I recently integrate app insights in my java program and the running time is increased by 10-20s.

I checked the internal self-diagnose log and found the warm up time is about 8-10s and the tear down is about 2-3s.

Since my java program is very light weight (normal run time is 10-20s) and with app insights integrated, the running time is doubled.

I already tried changing app insights configs like sampling rate and the JVM arguments (increase memory, prevent scanning unnecessary codes etc.) but it doesn't help much for the performance issue.

Can you tell me if anything I can improved the performance?

Thanks,

**Comment by trask** [comment]
hi @chen1005! are you running on Java 8? if so, can you try on Java 11 also? the applicationinsights-agent.jar file is signed, which causes some additional startup slowness on Java 8, so that will help isolate if that's the cause for you or not, thx!
