### ISSUE TITLE
Add support for log appenders to redirect certain logs elsewhere in AI java agent

### ISSUE THREAD

**Issue by navjinderkaur** [microsoft/ApplicationInsights-Java#1850]
Application Insight SDK had the option to specify log appenders to redirect the logs to different storage locations.  With AI agent, the only logging configuration option we have is to be able to specify log level. We have certain logs that we would like to redirect to files instead. 
**Correction** : Even with AI agent, we are able to redirect logs to files. The only issue that these logs also make their way to Azure logs, even with **additivity** set to false, which is unintended.

**Comment by trask** [comment]
hi @navjinderkaur! can you share the logback.xml that you were using with the 2.x SDK?

**Comment by navjinderkaur** [comment]
Frankly, I haven't attempted logging with the SDK, but I referred a changelog [here](https://github.com/microsoft/ApplicationInsights-Java/blob/main/CHANGELOG.md#version-250-beta), which said that it was possible. And based upon the correction in my request, I think its just the additivity that needs to be fixed. The logback.xml that I'm using with AI agent is attached.
[logback.txt](https://github.com/microsoft/ApplicationInsights-Java/files/6991211/logback.txt)

**Comment by trask** [comment]
hi @navjinderkaur, I'm not sure I understand the issue still. Could you provide a repro that I can run, and describe what you are seeing with the repro, and what you would like to see?

**Comment by navjinderkaur** [comment]
Referring to the logger hierarchy in logback, ideally if I have a logger configuration defined like below, my logs would be printed both at stdout and MyLog.log file.
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration debug="false">
<appender name="MyAppender" class="ch.qos.logback.core.rolling.FileAppender">
    <File>MyLog.log</File>
    <encoder>
      <pattern>%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n</pattern>
    </encoder>
  </appender>
    <logger name="MyLogger" level="INFO">
		<appender-ref ref="MyAppender" />
	</logger>
    <root level="INFO">
    </root>
    <contextListener class="ch.qos.logback.classic.jul.LevelChangePropagator">
    </contextListener>
</configuration>
```
But if I wanted to print them only to MyLog.log, with logback configuration, we could use the "additivity" attribute to push our logs to only one appender and prevent them from being handled by parent loggers. For example the following configuration would print my logs only to MyLog.log file.
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration debug="false">
<appender name="MyAppender" class="ch.qos.logback.core.rolling.FileAppender">
    <File>MyLog.log</File>
    <encoder>
      <pattern>%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n</pattern>
    </encoder>
  </appender>
    <logger name="MyLogger" level="INFO" **additivity="false"**>
		<appender-ref ref="MyAppender" />
	</logger>
    <root level="INFO">
    </root>
    <contextListener class="ch.qos.logback.classic.jul.LevelChangePropagator">
    </contextListener>
</configuration>
```
If I try to think of application-insights agent as another appender to push the logs to application insights logs in Azure, it should be possible for me to choose to send the logs only to application-insights logs, and not to stdout. But I did not find a way to do so with application insights agent 3.0. There's no configuration available to handle this redirection of logs. Is my perception of how application-insights agent work even correct ?

**Comment by trask** [comment]
> it should be possible for me to choose to send the logs only to application-insights logs, and not to stdout

oh I understand now, thanks!

would it work for you to add a `ThresholdFilter` to your appender to effectively suppress it? (the agent should then still capture the log)

http://logback.qos.ch/manual/filters.html#thresholdFilter

```
    <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
      <level>OFF</level>
    </filter>
```
