### ISSUE TITLE
applicationinsights-core after update to 3.x

### ISSUE THREAD

**Issue by jansorg** [microsoft/ApplicationInsights-Java#1870]
Apologies if this isn't the right place for this issue.

I'm using `com.microsoft.azure:applicationinsights-core:2.6.3` in a desktop application to report telemetry to Azure Insights.

Now, as far as I understand, 2.x seems to be outdated and 3.x should be used instead. But 3.x seems to purely built around a JVM agent, which I can't use in my setup. My context is a desktop Java application (an IDE) which doesn't allow to define a JVM agent at bootstrap. 
Also, I couldn't find a replacement for `com.microsoft.azure:applicationinsights-core`, which I'm currently using as a single dependency.

Is there a way to use 3.x instead of 2.x without using a JVM agent?

**Comment by heyams** [comment]
We do support loading agent dynamically at runtime. 
Can you try attaching 3.x programmatically? 

https://github.com/microsoft/ApplicationInsights-Java/issues/1680?

**Comment by jansorg** [comment]
Attaching a JVM agent isn't possible in my context. It's a plugin of an IDE process (IntelliJ) and attaching an agent to all of the IDE isn't what a plugin should do. I guess I'll have to  stick to 2.6.

**Comment by heyams** [comment]
In that case, I would suggest [Azure Monitor OpenTelemetry Exporter](https://docs.microsoft.com/en-us/java/api/overview/azure/opentelemetry-exporters-azuremonitor-readme?view=azure-java-preview) and [OpenTelemetry SDK](https://github.com/open-telemetry/opentelemetry-java). See if that will solve your issue.
