### ISSUE TITLE
 Auto Collected dependencies 

### ISSUE THREAD

**Issue by anumalasri** [microsoft/ApplicationInsights-Java#1880]
Application developed using SpringBoot 2.5.x and included dependency of appinsights-spring-boot-starter v2.6.3. It was deployed onto Azure App Service. 

Using AI Agent v2.x, the dependency telemetry has below values and able to track outgoing REST Service calls by URI. 

Property | Value
-- | --
Remote dependency name | GET /pathv1/abc/path

After upgrading to Agent v3.x, the dependency telemetry has only HTTP GET and unable to track dependencies by URI

Property | Value
-- | --
Remote dependency name | HTTP GET

That's causing some issues to use pre-defined AI Metrics like Performance & Failures and track individual GET paths.

**Can we able to track dependencies just like how Agent V2.x was tracking?**

 

### Expected behavior
We should be able to track dependencies using hostName and URI. 

### Actual behavior
Dependency tracking was happening only using httpMethod and baseName

### To Reproduce
We need to invoke outgoing REST calls from Application and monitor them in App Insights.  

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version:   3.x 
 - OS type and version: 
 - Application Server type and version (if applicable):
 - Using spring-boot?  Yes 
 - Additional relevant libraries (with version, if applicable):
       AI Agent Version -  3.x 
        appinsights-spring-boot - 2.6.3
 
### Screenshots
![image](https://user-images.githubusercontent.com/27963315/134165227-be39acf9-8f0d-46f0-8529-d92935cf692a.png)

**Comment by trask** [comment]
3.2.0-BETA.4 was just released and http dependencies now capture this additional info

**Comment by trask** [comment]
3.2.0 GA is released. it takes a few months generally before it will be available directly in Azure AppServices
