### ISSUE TITLE
Double traceparent headers

### ISSUE THREAD

**Issue by xsmrcek** [microsoft/ApplicationInsights-Java#1883]
ApplicationInsights Java Agent 3.1.1 is adding another traceparent hedaer into my requests.

Log sample:
{"timestamp":"2021-09-25T16:57:28.540Z","level":"TRACE","thread":"reactor-http-epoll-4","logger":"org.zalando.logbook.Logbook","message":"server request [f7c14e1cbb6d074c] GET ... with body '' headers '{Accept=[*/*], Accept-Encoding=[gzip, deflate, br], Authorization=[Basic dXNlcjp1c2VyLXBhc3N3b3Jk], Connection=[keep-alive], Host=[localhost:8080], Postman-Token=[16d47001-70e7-4f03-a5c5-55ecc88f55b4], traceparent=[00-00000000000000000000000000000001-9f485572825e8a02-00], User-Agent=[PostmanRuntime/7.26.8], X-Test=[true]}'","context":"default"}
{"timestamp":"2021-09-25T16:57:30.459Z","level":"TRACE","thread":"reactor-http-epoll-1","logger":"org.zalando.logbook.Logbook","message":"client request [f73ff4b0480d517b] ... headers '{accept=[*/*], accept-encoding=[gzip], Authorization=[...], content-length=[808], Content-Type=[text/xml], host=[...], Request-Id=[|7382b912b98672434beceb151848b70f.2c488bdb9f64a031.], traceparent=[00-7382b912b98672434beceb151848b70f-2c488bdb9f64a031-01, 00-00000000000000000000000000000001-e0714505f7f757f3-00], user-agent=[ReactorNetty/1.0.11], X-B3-ParentSpanId=[3f57f815b9a5533c], X-B3-Sampled=[0], X-B3-SpanId=[e0714505f7f757f3], X-B3-TraceId=[0000000000000001], X-Test=[true]}'","context":"default"}

My app is writen in Kotlin with spring webflux and kotlin logger with logbook for logging. I am using spring sleuth to propagate trace headers (I need w3c and b3 formats on my requests).
Everything works just fine before I add agent to my app, when I do that, there is second traceparent header as on the example above.

Versions:
Java 15
Kotlin: 1.5.31
spring-boot-starter-parent: 2.5.5
spring-cloud-dependencies: 2020.0.4

Is there any way to temporary force agent to stop propagation headers on it's own? I just need this ganet to export data to ApplicationInsights not to change my headers.

**Comment by xsmrcek** [comment]
Hello @trask , now my applications are using opentelemetry agents (with a little custom adjustments) to propagate tracecontext,b3multi,baggage (- it's configuration). If your agent would be able to propagate that for me it would be awesome, as I would be able to do that and export data to application insights.
Spring sleuth in previous example was just my workaround to allow me to use your javaagent. 
After some more digging I found out that problem with your agent is when I use sleught to propagate headers and zolando logbook for logging, it's not compatible as logging is done sooner than propagation. 
Opentelemtry agent doesn't have this problem. So if it can propagate all the headers I would just replace those agents.

Btw: My applications are running as a integration layer between two systems which uses different trace headers, that's why I have to propagate both as only one is comming from each system and I have to be able to trace whole flow.

**Comment by trask** [comment]
@xsmrcek I added `b3multi` support in #1949, can you try out snapshot from CI https://github.com/microsoft/ApplicationInsights-Java/files/7471986/applicationinsights-agent-3.2.3-BETA-SNAPSHOT.jar.zip and see if that works for you?

You can enable the configuration using:

```
{
  "preview": {
    "additionalPropagators": [
      "b3multi"
    ]
  }
}```

**Comment by xsmrcek** [comment]
@trask Thank you!
I did try newest version, but it's still generating new traceIds/traceparents :(
>2021-11-04 15:08:22,114 {} [reactor-http-epoll-3] TRACE org.zalando.logbook.Logbook server request [9c19b8330c224947] POST ... with body '...' headers '...'
>2021-11-04 15:08:25,628 {traceId=6bf2fba466f5b565b83cf4417bcd2911, spanId=78239a162d4b4a8c, sampled=true} [reactor-http-epoll-4] TRACE org.zalando.logbook.Logbook client request [f3c4ead5dead16e3] POST ... with body '...' headers '... traceparent=[00-6bf2fba466f5b565b83cf4417bcd2911-78239a162d4b4a8c-01], ... X-B3-SpanId=[78239a162d4b4a8c], X-B3-TraceId=[6bf2fba466f5b565b83cf4417bcd2911], ...'
>2021-11-04 15:08:26,296 {traceId=6bf2fba466f5b565b83cf4417bcd2911, spanId=78239a162d4b4a8c, sampled=true} [reactor-http-epoll-4] TRACE org.zalando.logbook.Logbook client response [f3c4ead5dead16e3] 200 for ... with body '...' and headers '...'. Duration 651 ms
>2021-11-04 15:08:27,098 {traceId=8df35c6c3e471b49821ded85f596439f, spanId=f9f9833dc43627fd, sampled=true} [reactor-http-epoll-1] TRACE org.zalando.logbook.Logbook client request [9c6c20e386975146] POST ... with body '...' headers '... traceparent=[00-8df35c6c3e471b49821ded85f596439f-f9f9833dc43627fd-01], ... X-B3-Sampled=[1], X-B3-SpanId=[f9f9833dc43627fd], X-B3-TraceId=[8df35c6c3e471b49821ded85f596439f], X-Test=[true]}'
>2021-11-04 15:08:27,350 {traceId=8df35c6c3e471b49821ded85f596439f, spanId=f9f9833dc43627fd, sampled=true} [reactor-http-epoll-1] TRACE org.zalando.logbook.Logbook client response [9c6c20e386975146] 201 for ... with body '...' and headers '...'. Duration 252 ms
>2021-11-04 15:08:27,865 {traceId=f955c90ee94826c1815fd716a04cfaa7, spanId=e7247134efe62019, sampled=true} [reactor-http-epoll-2] TRACE org.zalando.logbook.Logbook client request [d7479ae9101facb7] POST ... with body '...' headers '...traceparent=[00-f955c90ee94826c1815fd716a04cfaa7-e7247134efe62019-01],... X-B3-Sampled=[1], X-B3-SpanId=[e7247134efe62019], X-B3-TraceId=[f955c90ee94826c1815fd716a04cfaa7],...'
>2021-11-04 15:08:28,101 {traceId=f955c90ee94826c1815fd716a04cfaa7, spanId=e7247134efe62019, sampled=true} [reactor-http-epoll-2] TRACE org.zalando.logbook.Logbook client response [d7479ae9101facb7] 201 for ... with body '...' and headers '...'. Duration 238 ms
>2021-11-04 15:08:28,316 {} [DefaultDispatcher-worker-1] INFO  n.h.k.h.p.AbstractScoringHandler Request processed successfully

I think there is some issue with Kotlin/Webflux/Logbook :(

**Comment by trask** [comment]
hi @xsmrcek, you mentioned above that you were able to use OpenTelemetry Java agent successfully, is this still true? Application Insights Java agent is built on top of OpenTelemetry Java agent, so trying to think what difference might be (e.g. we don't include _all_ of the instrumentation from upstream)

**Comment by xsmrcek** [comment]
[opentelemetry.zip](https://github.com/microsoft/ApplicationInsights-Java/files/7496322/opentelemetry.zip)
Hi @trask,
after some more digging into our code I found implementation above. Sadly this code is above my understanding. But I hope it will be helpful for you, to see what my predecessors did there.

**Comment by xsmrcek** [comment]
Hi @trask ,
I did it right this time and had issue fixed in OpenTelemetry project (https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/5154)
Would it be possible to include this fix and propagation you did for me before? It should resolve most of my issues.

**Comment by xsmrcek** [comment]
Hi @trask , sorry for spamming your. I closed last issue as it was issue in my sample application not agent issue.
Would it be possible to combine newest opentelemetry agent and this b3multi propagation as it would solve my problem.

**Comment by trask** [comment]
no worries. I updated the PR to our `vnext` branch which has the latest otel update and here the SNAPSHOT build from CI: https://github.com/microsoft/ApplicationInsights-Java/suites/5339978559/artifacts/166827546

**Comment by xsmrcek** [comment]
Hello @trask Thank you!
But I still have one problem here :(
When I am using opentelemetry agent MDC is filled in logs as it suppesed to be:
```
{"timestamp":"2022-02-17T07:42:18.165Z","level":"TRACE","thread":"reactor-http-epoll-1","mdc":{"trace_id":"0000000000000000c1265d33d3764f3e","trace_flags":"01","span_id":"4c1ac644e1eaf33b"},"logger":"org.zalando.logbook.Logbook","message":"server request [9dfe70793311b976] GET /send/dummy/message 
```
Configuration of agent:
```
      - name: OTEL_PROPAGATORS
        value: "tracecontext,b3multi,baggage"
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "service.name=***,service.instance.id=$(POD_NAME)"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "***"
      - name: OTEL_EXPORTER_OTLP_TIMEOUT
        value: "10000"
      - name: OTEL_METRICS_EXPORTER
        value: none
      - name: OTEL_TRACES_SAMPLER
        value: always_on
      - name: OTEL_INSTRUMENTATION_SPRING-WEBFLUX.EXPERIMENTAL-SPAN-ATTRIBUTES
        value: "true"
```
But when I use application insights agent MDC is missing.
```
{"timestamp":"2022-02-17T07:08:54.880Z","level":"TRACE","thread":"reactor-http-epoll-3","logger":"org.zalando.logbook.Logbook","message":"server request [ec710ffc169c51b7] GET /send/dummy/message
```
my applicationinsights.json:
```
{
  "role": {
    "name": "***"
  },
  "sampling": {
    "percentage": 100
  },
  "instrumentation": {
    "logging": {
      "level": "TRACE"
    },
    "micrometer": {
      "enabled": true
    }
  },
  "preview": {
    "additionalPropagators": [
      "b3multi"
    ],
    "sampling": {
      "overrides": [
        {
          "attributes": [
            {
              "key": "http.url",
              "value": "https?://[^/]+/actuator.*",
              "matchType": "regexp"
            }
          ],
          "percentage": 0
        }
      ]
    },
    "captureHttpServerHeaders": {
      "requestHeaders": [
        "***"
      ]
    },
    "captureHttpClientHeaders": {
      "requestHeaders": [
        "***"
      ]
    }
  }
}
```
I am probably missing some config here :( Do you have any isue what may be wrong? Should I try to reate another minimal example project for you?

**Comment by xsmrcek** [comment]
I have one more question.
I am using [yalando logbook(]https://github.com/zalando/logbook) for loggin as logging webflux is a real pain.
I was a little naive when I thought agent will be able to autocollect headers and request/response bodies from this logger. Do you think it is worth to create issue for this support? Or I should forget about it and try to add it somehow manually or use different logger.

**Comment by trask** [comment]
> This issue makes it hard to search in logs which are not present in application insights. When we turn on sampling, we will be still collecting all logs somewhere else and for this I need MDC in logs :( Beside that your agent works great!

ya, we are not adding MDC in the logs themselves since we are already correlating and ingesting the logs

> When we turn on sampling, we will be still collecting all logs somewhere else and for this I need MDC in logs

would it work for you if logs were not sampled in the agent? then you will have all logs (with correlation where it exists) in Application Insights backend

**Comment by xsmrcek** [comment]
> > This issue makes it hard to search in logs which are not present in application insights. When we turn on sampling, we will be still collecting all logs somewhere else and for this I need MDC in logs :( Beside that your agent works great!
> 
> ya, we are not adding MDC in the logs themselves since we are already correlating and ingesting the logs
> 
Would it be somehow possible to add this feature? We will be sampling application insights traffic ourself and collect logs somewhere else.
> > When we turn on sampling, we will be still collecting all logs somewhere else and for this I need MDC in logs
> 
> would it work for you if logs were not sampled in the agent? then you will have all logs (with correlation where it exists) in Application Insights backend
Two questions here:
Are those logs sampled now? If so, it is configurable? In case logs are not sampled (or I can configure it) it would be temporary OK to have logs only in application insights. But for future I have to sample application insights to cut a cost (we will have milions of live user every day) so I would really appreciate to ave option to turn on adding of MDC.

**Comment by trask** [comment]
> Would it be somehow possible to add this feature?

ya, we're considering it, here's a SNAPSHOT build from #2140, if you can test it out and see if it would work for you that would be helpful:

https://github.com/microsoft/ApplicationInsights-Java/suites/5439717239/artifacts/172590254

> Are those logs sampled now?

Logs which have a "parent span" (e.g. are part of a request) are captured if the span is captured and are not captured if the span is not. This way you get full traces including their logs.

Logs which do not have a "parent span" (e.g. startup logs) are always captured.

>  If so, it is configurable?

Not currently, but would like to get feedback if there's some configuration that would be helpful.

**Comment by xsmrcek** [comment]
Hello @trask ,
> > Would it be somehow possible to add this feature?
> 
> ya, we're considering it, here's a SNAPSHOT build from #2140, if you can test it out and see if it would work for you that would be helpful:
> 
> https://github.com/microsoft/ApplicationInsights-Java/suites/5439717239/artifacts/172590254
> 
I am sorry it is not working for me. Is there any additional configuration I should use?

> > Are those logs sampled now?
> 
> Logs which have a "parent span" (e.g. are part of a request) are captured if the span is captured and are not captured if the span is not. This way you get full traces including their logs.
> 
> Logs which do not have a "parent span" (e.g. startup logs) are always captured.
> 
Thank you for explanation. I have one more stupid question: 
My application is rarery generating totaly new spans, in most cases I receive traceparent header, so there is actually no need of sampling as agent will use sampling flag from header. Is this right?
> > If so, it is configurable?
> 
> Not currently, but would like to get feedback if there's some configuration that would be helpful.

I don't have valid use case right now, if I have one in future I will let you know.
Btw I was looking into [doc](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-sampling-overrides)
And wonder if it is possible to adjust sampling (of whole span, not jsut logs) according to some custom attribute, which is being set up manualy in code like:
```
Span.current().setAttribute("IsTest", "true)
```
And then set sampling like: if IsTest==true >> 80% if IsTest==false >> 20% 
(this is just in case of spans, where there is no traceparet or B3 headers on request).

**Comment by trask** [comment]
> I am sorry it is not working for me. Is there any additional configuration I should use?

what logging library and version are you using? and can you share your logging configuration that you used for injecting the trace id?

e.g. I just tried with log4j 2.16.0 and this pattern layout:

```
<PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - trace_id=%X{trace_id} - %msg%n"/>
```

and it worked for me

**Comment by trask** [comment]
> Thank you for explanation. I have one more stupid question:
My application is rarery generating totaly new spans, in most cases I receive traceparent header, so there is actually no need of sampling as agent will use sampling flag from header. Is this right?

So, it should be right, except that for compatibility with Application Insights .NET SDK, the javaagent ignores traceflags "0".

Which means that the javaagent respects upstream decision to sample _in_ a trace (capture it), but doesn't respect upstream decision to sample _out_ a trace (throw it away)

I think we'll change this behavior in `3.3.0` to follow the default/expected behavior (at least in the OpenTelemetry world), #2151.

For now, you can add this setting to get the behavior you're looking for:

```
{
  "preview": {
    "ignoreRemoteParentNotSampled": false
  }
}
```

> And wonder if it is possible to adjust sampling (of whole span, not jsut logs) according to some custom attribute, which is being set up manualy in code like:
> 
> ```
> Span.current().setAttribute("IsTest", "true)
> ```
>
> And then set sampling like: if IsTest==true >> 80% if IsTest==false >> 20%
(this is just in case of spans, where there is no traceparet or B3 headers on request).

the problem here is that the sampling decision takes place on span start, so calling `Span.current().setAttribute("IsTest", "true)` is too late

**Comment by xsmrcek** [comment]
> > Thank you for explanation. I have one more stupid question:
> > My application is rarery generating totaly new spans, in most cases I receive traceparent header, so there is actually no need of sampling as agent will use sampling flag from header. Is this right?
> 
> So, it should be right, except that for compatibility with Application Insights .NET SDK, the javaagent ignores traceflags "0".
> 
> Which means that the javaagent respects upstream decision to sample _in_ a trace (capture it), but doesn't respect upstream decision to sample _out_ a trace (throw it away)
> 
> I think we'll change this behavior in `3.3.0` to follow the default/expected behavior (at least in the OpenTelemetry world), #2151.
> 
> For now, you can add this setting to get the behavior you're looking for:
> 
> ```
> {
>   "preview": {
>     "ignoreRemoteParentNotSampled": false
>   }
> }
> ```
> 
> > And wonder if it is possible to adjust sampling (of whole span, not jsut logs) according to some custom attribute, which is being set up manualy in code like:
> > ```
> > Span.current().setAttribute("IsTest", "true)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And then set sampling like: if IsTest==true >> 80% if IsTest==false >> 20%
> > (this is just in case of spans, where there is no traceparet or B3 headers on request).
> 
> the problem here is that the sampling decision takes place on span start, so calling `Span.current().setAttribute("IsTest", "true)` is too late

Thank you! I will update configuration to reflect sam-pling from parent system.

**Comment by xsmrcek** [comment]
> > I am sorry it is not working for me. Is there any additional configuration I should use?
> 
> what logging library and version are you using? and can you share your logging configuration that you used for injecting the trace id?
> 
> e.g. I just tried with log4j 2.16.0 and this pattern layout:
> 
> ```
> <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - trace_id=%X{trace_id} - %msg%n"/>
> ```
> 
> and it worked for me

I am using logback:
`
<configuration>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="ch.qos.logback.contrib.json.classic.JsonLayout">
                <timestampFormat>yyyy-MM-dd'T'HH:mm:ss.SSSX</timestampFormat>
                <timestampFormatTimezoneId>Etc/UTC</timestampFormatTimezoneId>
                <appendLineSeparator>true</appendLineSeparator>
                <jsonFormatter class="ch.qos.logback.contrib.jackson.JacksonJsonFormatter">
                    <prettyPrint>false</prettyPrint>
                </jsonFormatter>
            </layout>
        </encoder>
    </appender>

    
    <logger name="com.azure.core" level="ERROR" />
    <logger name="com.azure.messaging" level="ERROR" />

    <root level="info">
        <appender-ref ref="STDOUT"/>
    </root>

</configuration>
`
If I am not mistaken, it is using [this](https://github.com/qos-ch/logback-contrib/blob/master/json/classic/src/main/java/ch/qos/logback/contrib/json/classic/JsonLayout.java).
I did try to add this logign to my code:
`
logger.info { "MDC: ${MDC.getCopyOfContextMap().toString()}" }
`
And it failed with NullPointerException, I assume that MDC wasn;t propagated for me.
(I am using combination of reactive Spring Webflux and Kotlin)
There is [minimal-example](https://github.com/xsmrcek/minimal-example) of my applicatoin.

**Comment by trask** [comment]
thanks, can you try this new SNAPSHOT build?

https://github.com/microsoft/ApplicationInsights-Java/suites/5493003940/artifacts/175576458

**Comment by trask** [comment]
great, here you go: https://github.com/microsoft/ApplicationInsights-Java/suites/5509462221/artifacts/176506191

**Comment by xsmrcek** [comment]
Thank you!
I tested it and it works as expected!

**Comment by florianRieb** [comment]
Hello everyone, this conversation has helped me a lot. Thanks for that!

But I still have a problem with the B3 multi headers, that the trace id is not propagated correctly and regenerated instead.

 My spring app, runs with the app insights java agent and receives request with header like this:
```
X-B3-TraceId: 63ac35c9f6413ad48485a3953bb6124
X-B3-SpanId: a2fb4a1d1a96d312
X-B3-ParentSpanId: 0020000000000001
X-B3-Sampled: 1
```
Versions:
Java OpenJDK Temurin-17+35
spring-boot-starter-parent: 2.6.2

My applicationinsights.json looks like this:

```
{
  "preview": {
    "additionalPropagators": [
      "b3multi"
    ],
    "captureHttpServerHeaders": {
      "requestHeaders": [
        "***"
      ]
    },
    "captureHttpClientHeaders": {
      "requestHeaders": [
        "***"
      ]
    }
  }
}
```
And I added also the ENV:
```
OTEL_PROPAGATORS = "tracecontext,b3multi,baggage"
```
I tried the agent-3.2.7, but with this neither 3B single nor multi worked.
Then I took your 3.2.3-BETA-SNAPSHOT and 3.3.0-BETA-SNAPSHOT, with these the single b3 works but also not the multi-header propagation.

Can you imagine what I am doing wrong?

**Comment by trask** [comment]
> My client responces are missing MDC. And their logs are missing in Application Insights too. But client request have it correctly filled and are present in applicatoin insights.

@xsmrcek my guess is that this is related to the context (which contains the current span) not getting propagated across threads. can you try checking `Span.current()` in the same place where you are performing the logging? that will help isolate what the issue is here

**Comment by trask** [comment]
@florianRieb if you can open a new issue and provide a small repro, that would be super helpful, thx

**Comment by florianRieb** [comment]
@trask When I created the Reproducer, I no longer had this problem. The agent 3.3.0-BETA-SNAPSHOT now works for me as desired.

**Comment by florianRieb** [comment]
@trask all right, here i created a new issue with a small demo app. 
https://github.com/microsoft/ApplicationInsights-Java/issues/2158

**Comment by xsmrcek** [comment]
> > My client responces are missing MDC. And their logs are missing in Application Insights too. But client request have it correctly filled and are present in applicatoin insights.
> 
> @xsmrcek my guess is that this is related to the context (which contains the current span) not getting propagated across threads. can you try checking `Span.current()` in the same place where you are performing the logging? that will help isolate what the issue is here

Hello @trask , I will try to determine where the issue is next week. I think we can close this issue and I will create new one. Thank you for awesome help you provided us!!!
