### ISSUE TITLE
Provide support for integrating Java agent with Felix OSGi

### ISSUE THREAD

**Issue by musicjunkieg** [microsoft/ApplicationInsights-Java#1891]
**Is your feature request related to a problem? Please describe.**
I am unable to monitor Jira with the in-process Java agent. When I try, many times Jira will not start due to limitations with the Felix OSGi because the container's CLASSPATH is not delegated to the bootstrap classloader, which keeps Jira's system plugins from loading, and so Jira will not start. This means we cannot use the in-process Java agent to monitor Jira. 

**Describe the solution you would like**
I would like to have documentation on how to configure Java webapps that use the Felix OSGi container with appropriate flags in order to load the in-process agent effectively. 

**Describe alternatives you have considered**
Considered using Zabbix and PRTG's probes, but we are trying to centralize all of our monitoring in Azure. Also tried discerning which classes needed to be delegated, but was unable to determine all of them.

**Additional context**
Atlassian has this documented here: [Using javaagent with Jira](https://confluence.atlassian.com/jirakb/using-javaagent-with-jira-790793295.html?utm_medium=scheduledLogScan&utm_source=STP)
Atlassian provides a flag to delegate the CLASSPATH to the bootloader, but all classes that need to be delegated need to be known. See [here](https://confluence.atlassian.com/jirakb/adding-classes-to-osgi-boot-class-loader-bootdelegation-973483231.html)
Related issue where I was directed here: https://github.com/MicrosoftDocs/azure-docs/issues/80198

**Comment by musicjunkieg** [comment]
Will do!!

Bryan Guffey | ATLASSIAN ADMINISTRATOR | D: 440.485.5559 | M: 785.215.2140<https://aka.ms/o0ukef>
________________________________

**Comment by musicjunkieg** [comment]
@trask  - about to do this - one question: how is this supposed to address the issue? I don't have a list of classes to delegate.

**Comment by trask** [comment]
the javaagent instruments the class loaders themselves, and overrides the delegation for the javaagent classes, so there's nothing you should need to do. if you can try with latest agent and post logs/errors hopefully that will give us some clues why this isn't working in your case
