### ISSUE TITLE
Get span.current().getSpanContext() in Azure eventhub consumer returning empty span context

### ISSUE THREAD

**Issue by imdad-ms** [microsoft/ApplicationInsights-Java#1892]
### Expected behavior
Describe what you expected to happen.

var context = Span.current() != null && Span.current().getSpanContext() != null ? Span.current().getSpanContext().getTraceId() : null;

### Actual behavior
returning default empty span context

### To Reproduce

1. create Spring boot non-web event hub consumer worker based on spring cloud stream
2. inside spring cloud consumer function , get current span context
    var spanContext = getCurrentSpanContext();

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version:    com.microsoft.azure:applicationinsights-agent:3.1.1; com.microsoft.azure:applicationinsights-web:2.6.3
 - OS type and version: Mac and Linux
 - Application Server type and version (if applicable):
 - Using spring-boot? yes non-web
 - Additional relevant libraries (with version, if applicable):  io.opentelemetry:opentelemetry-api:1.5.0;  com.azure.spring:azure-spring-cloud-stream-binder-eventhubs:2.5.0

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.
 Logs can be provided if required.

_Be sure to remove any private information from the logs before posting!_

**Comment by lmolkova** [comment]
@imdad-ms  
can you please share a few details
- versions of Event Hub SDK/springboot starter
- if used, version of azure-core-tracing-opentelemetry (it's should be ok if you don't have it in the POM)
- version if ApplicationInsights agent
- Is it a Springboot starter? or `EventHubProcessorClient`?
- can you please share consume callback/event handler code snippet? 

We're working on solving [issues](https://github.com/Azure/azure-sdk-for-java/issues/23035) with Span.current() in reactor callbacks. To my best knowledge, they affect event hub consumers much less than producers, so I hope we can find mitigation while the proper fix is on the way.

Thanks!

**Comment by cicorias** [comment]
A repo is here: 
https://github.com/cicorias/opentelemetry-span-empty-issue-1892

- it's a spring boot app
- spring cloud stream


We are not seeing any correlationid from the below code - or actually, it's showing up as all "0"s..

We adorned the Web REST controller with similar code --- see the [repro repo](https://github.com/cicorias/opentelemetry-span-empty-issue-1892) for the details, and there too in the Web REST controller context we get all "0"s too.

my internal is scicoria 

```java
    public String getCorrelationId() {

        Span current = null;
        SpanContext context = null;
        String traceid = null;

        current = Span.current();

        if (null != current)
            context = current.getSpanContext();

        if (null != current && null != context)
            traceid = context.getTraceId();
        

        return traceid;


        // return Span.current() != null && Span.current().getSpanContext() != null ? Span.current().getSpanContext().getTraceId() : null;

        // Span.current()
    // PropagatedSpan@231 "PropagatedSpan{ImmutableSpanContext{traceId=00000000000000000000000000000000, 
    //spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}}"
      }
```

**Comment by cicorias** [comment]
FYI, we missed setting the `applicationinsights.json` preview flag  [OpenTelemetry API support (3.0)](https://github.com/microsoft/ApplicationInsights-Java/wiki/OpenTelemetry-API-support-(3.0)#enabling-this-feature)

I believe this issue can be closed.

```
"preview" :  
     {
         "openTelemetryApiSupport": true
     }
...
```

**Comment by trask** [comment]
3.2.0-BETA.4 was just released, and this option is now enabled by default, so no need to remember to set it anymore 👍
