### ISSUE TITLE
Service Bus - Apache Camel AMQP: consumers are not being reported in application map

### ISSUE THREAD

**Issue by apoguy** [microsoft/ApplicationInsights-Java#1898]
### Expected behavior
We are running an app using Apache Camel with amqp component, connected to Service Bus queues and topics. When sending messages we can see the traces and it is displayed on application map just fine:

![image](https://user-images.githubusercontent.com/5913516/135628849-295d29f5-82cf-4aab-af38-4c3293799070.png)

However, received messages even tho they appear in traces and end-to-end transactions:

![image](https://user-images.githubusercontent.com/5913516/135629222-8d15de57-12a7-4af4-9470-1b78b4fd5b29.png)

they are not displayed in application map. I believe this is an issue with the agent, as we have other java apps that do not use Camel AMQP that are being reported just fine. It could be a Camel AMQP issue, however, as in traces the "recieves" show up, suggests that is more an application insights issue. 

### To Reproduce
This can be reproduced using a basic apache camel routes:

```
<route id="test">
   <from uri="direct:test"/>
   <!-- set any header for topic filter -->
   <to uri="amqp:topic:stx_healthcheck_topic?disableReplyTo=true"/>
   <pollEnrich timeout="2000">
      <constant>amqp:topic:stx_healthcheck_topic/subscriptions/{{subName}}</constant>
   </pollEnrich>
</route>
```

### System information
Please provide the following information:
 - SDK Version: 3.1.1
 - OS type and version: RHEL ubi image
 - Additional relevant libraries (with version, if applicable): Apache Camel AMQP 2.24.0

**Comment by apoguy** [comment]
Noticed there is a BETA version, tested BETA 4, with even less success, now receives don't even show up in logs or traces:

![image](https://user-images.githubusercontent.com/5913516/135658144-5338e588-1ccf-41c5-8b0e-e529e2d3d49d.png)

**Comment by phanbyte** [comment]
i have the same issue

**Comment by phanbyte** [comment]
> Noticed there is a BETA version, tested BETA 4, with even less success, now receives don't even show up in logs or traces:
> 
> ![image](https://user-images.githubusercontent.com/5913516/135658144-5338e588-1ccf-41c5-8b0e-e529e2d3d49d.png)

i have the same issue, no solution found yet. waiting for support.
