### ISSUE TITLE
Question - metrics sampling

### ISSUE THREAD

**Issue by NguyHa03** [microsoft/ApplicationInsights-Java#1902]
I see that we could override sampling for request [(docs)](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-sampling-overrides), do we have something like that for custom metrics ? 
I want to keep all metrics at 100% and other telematry at sampling (like 10%)

I found that Standard Metric would be suitable for my scenario [(docs)](https://docs.microsoft.com/en-us/azure/azure-monitor/app/pre-aggregated-metrics-log-metrics), but java codeless is currently not support. Could we have any other solution ?

**Comment by heyams** [comment]
@NguyHa03 can you try [metrics filtering](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-telemetry-processors#metric-filter).  It was introduced in 3.1.1.

**Comment by NguyHa03** [comment]
@heyams `metrics filtering` means that I have to set sampling rate of application insight to 100% and filter out metrics that I don't want. It's not suitable for my case.
I need to keep sampling for all telematry like (traces, perfomances..) at 10% and metrics at 100%.

**Comment by heyams** [comment]
if you're using "trackMetrics" from the 2.x SDK, please use [metric-interval](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#metric-interval) for now.  it doesn't affects calls to "trackMetrics", i.e. custom metrics, but will impact metrics that are auto-collected.

**Comment by NguyHa03** [comment]
I used 3.x agent along with micrometer-core 1.7.3 to send metric like this
`
static final Counter counter = Metrics.counter("test_counter");
counter.increment();
`

**Comment by trask** [comment]
thanks for the explanations @NguyHa03! agree that it is unexpected for sampling percentage to apply to metrics, will fix in #1942
