### ISSUE TITLE
Turn off  customMetrics, performanceCounters and metrics collected by default

### ISSUE THREAD

**Issue by lidkowiak** [microsoft/ApplicationInsights-Java#1905]
**Is your feature request related to a problem? Please describe.**
By default agent collects lots of metrics/data:

customMetric	Loaded Class Count
customMetric	% Of Max Heap Memory Used
customMetric	Heap Memory Used (MB)
customMetric	Suspected Deadlocked Threads
customMetric	Current Thread Count
customMetric	GC Total Time
customMetric	GC Total Count
customMetric	HeartbeatState
performanceCounter	Available Bytes
performanceCounter	IO Data Bytes/sec
performanceCounter	% Processor Time
performanceCounter	Private Bytes
metric	Loaded Class Count
metric	% Of Max Heap Memory Used
metric	Heap Memory Used (MB)
metric	Suspected Deadlocked Threads
metric	Current Thread Count
metric	GC Total Time
metric	GC Total Count
metric	HeartbeatState
metric	Available Bytes
metric	% Processor Time
metric	Private Bytes
metric	IO Data Bytes/sec	

I prefer to use standard provided by Spring Boot/Micrometer. Is there a possibility to turn off collecting of the above telemetries?

**Describe the solution you would like**

By default no telemetries should be collected by default. Adding  a config entry like collectStandardJVMMetric should cause collecting the data.

**Describe alternatives you have considered**
-

**Additional context**
-

**Comment by heyams** [comment]
```
{
  "instrumentation": {
        "jms": {
               "enabled": false
        }
}
```

have you tried this?

**Comment by heyams** [comment]
[default metrics and perf counter collected by 3.x agent](https://github.com/microsoft/ApplicationInsights-Java/wiki/Default-Metrics-Captured-by-Java-3.0-Agent).  you can use [metrics filtering](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-telemetry-processors#metric-filter) to filter both perf counter and custom metrics. i don't believe we use jvm to define any metrics we collect.

**Comment by heyams** [comment]
fyi: 

some metrics specific to jvm are like the following:
none of these matched what you had above.

  | jvm_memory_used |  
  | jvm_buffer_memory_used |  
  | jvm_threads_states |  
  | jvm_memory_committed |  
  | jvm_gc_pause |  
  | jvm_memory_max |  
  | jvm_buffer_total_capacity |  
  | jvm_threads_live |  
  | jvm_classes_unloaded |  
  | jvm_classes_loaded |  
  | jvm_threads_peak |  
  | jvm_threads_daemon |  
  | jvm_buffer_count |  
  | jvm_gc_memory_promoted |  
  | jvm_gc_memory_allocated |  
  | jvm_gc_max_data_size |  
  | jvm_gc_live_data_size

**Comment by heyams** [comment]
here is an example how to use metric filter:

```
{
  "preview": {
    "processors": [
      {
        "type": "metric-filter",
        "exclude": {
          "matchType": "strict",
          "metricNames": [
            "a_test_metric",
            "another_test_metric"
          ]
        },
        "id": "metric-filter/exclude-two-metrics"
      }
    ]
  }
}
```

**Comment by heyams** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#auto-collected-metrics
https://github.com/microsoft/ApplicationInsights-Java/wiki/Default-Metrics-Captured-by-Java-3.0-Agent

we do documented auto-collected metrics. hope this will clear your confusion.

**Comment by lidkowiak** [comment]
Thanks, what I want to achieve is to turn off collecting of metrics/perf counters that are enabled by default.
I partially achieved the goal with metric filtering but there are some leftovers.
Obviously I still want to collect other telemetries, especially these that come from micrometer.

I think the scenario I want to achieve is pretty standard. I don't understand why there is something enabled by default that can not be completely turn off. Better approach would be to explicitly enable collecting of default metrics with some config. 

I haven't found a link (https://github.com/microsoft/ApplicationInsights-Java/wiki/Default-Metrics-Captured-by-Java-3.0-Agent )  on docs.microsoft.com so I thought it's not documented at all :)

**Comment by trask** [comment]
hi @lidkowiak @emmansun can you confirm your reason for wanting to turn of the default metrics below? is it for cost, or for other reasons? thx!

https://github.com/microsoft/ApplicationInsights-Java/blob/53ea6e7c0423968664a53ff128c384e96e608deb/agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/telemetry/MetricFilter.java#L37-L45

**Comment by emmansun** [comment]
Hi @trask , in our use case, we use ApplicationInsights-Java for e2e trace, e.g. Request/Dependency/Trace log/..., for metric monitor, we have other solution. So we hope end user can have options to enable/disable those metrics collection, include default metrics. Yes, cost is also our concern. Thx!
