### ISSUE TITLE
Memory leak when enabling the application

### ISSUE THREAD

**Issue by mostrovoi** [microsoft/ApplicationInsights-Java#1909]
### Expected behavior
Describe what you expected to happen.

I am using the following configuration for the app insights java:

{
  "role": {
    "name": "app-customer-service-communications-service-java-ms"
  },
  "preview": {
    "profiler": {
      "enabled": true
    },
    "metricIntervalSeconds": 10
  }
}

### Actual behavior
Describe what actually happened that was unexpected.

This is the stack trace and memory leak that appears in the logs:

2021-10-10 06:30:55.361Z INFO  i.o.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: null
2021-10-10 06:30:57.368Z WARN  c.m.a.s.JfrProfilerService - INITIALISING JFR PROFILING SUBSYSTEM THIS FEATURE IS IN BETA
2021-10-10 06:31:12.458Z INFO  c.m.applicationinsights.agent - ApplicationInsights Java Agent 3.2.0 started successfully (PID 1)
2021-10-10 06:33:31.535Z ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:402)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115)
	io.netty.handler.ssl.SslHandler.allocate(SslHandler.java:2247)
	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1338)
	io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)
	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Thread.java:829)

### To Reproduce

Use the aforementioned configuration and start up the agent

### System information
Please provide the following information:
 - SDK Version:
Open JDK 11
 - OS type and version:
 - Application Server type and version (if applicable):
 Netty
 - Using spring-boot?
 Yes
 - Additional relevant libraries (with version, if applicable):

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

**Comment by trask** [comment]
hey @mostrovoi! here's a snapshot you can test out to see if it resolves the issue: https://github.com/microsoft/ApplicationInsights-Java/files/7333605/applicationinsights-agent-3.2.1-BETA-SNAPSHOT.jar.zip

**Comment by trask** [comment]
re-opening, need to revert this fix in #1913

@mostrovoi do you only get the netty warning when profiling is enabled?
