### ISSUE TITLE
Add option to disable the logged warning if trace message exceeds Sanitizer.MAX_MESSAGE_LENGTH

### ISSUE THREAD

**Issue by Ramblurr** [microsoft/ApplicationInsights-Java#1964]
This PR (https://github.com/microsoft/ApplicationInsights-Java/issues/1021) added warnings when telemetry is truncated. This is fine, but it should be possible to turn the warnings off, or disable the warnings for certain types of telemetry.

In our case we have some large sql queries that trigger this truncation and fill our logs with this warning.

### Expected behavior

We should be able to turn off the TelemetryTruncation logging.

### Actual behavior

Our logs are filled with warnings like:

`WARN  c.m.a.a.i.common.TelemetryTruncation - In the last 5 minutes, the following warning has occurred 188 times: Telemetry was truncated:`

### To Reproduce

1. Use the javaagent
2. Have long sql queries

#### Sample Application

n/a

### System information
Please provide the following information:
 - SDK Version: applicationinsights-agent-3.2.0.jar 
 - OS type and version: Debian Docker
 - Application Server type and version (if applicable): tomcat
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable): n/a

### Logs

`WARN  c.m.a.a.i.common.TelemetryTruncation - In the last 5 minutes, the following warning has occurred 188 times: Telemetry was truncated:`

### Screenshots

n/a

**Comment by trask** [comment]
hi @Ramblurr, thanks for reporting this!

I agree, the current situation doesn't seem great.

Would it work for you if we limit this to only be logged once (and to truncate the logged value to 80 characters)?

I have submitted PR #1968 to implement this approach (and to log more verbosely at `debug` level).

(we are trying to avoid configuration option proliferation where possible)

**Comment by Ramblurr** [comment]
Thanks for the reply.

This sounds like a reasonable solution. But what does once mean exactly? Once per JVM execution? And once per all truncation notices or just once per trace type?

Happy with any combination of those, but would be good to understand the behavior.

**Comment by trask** [comment]
@Ramblurr thx! it would be once per JVM execution. Well, up to max of 10 times per JVM execution if there are >= 10 different fields that overflow. In your case, if only sql queries are overflowing, it would just be once per JVM execution.

**Comment by trask** [comment]
Resolved by #1968

**Comment by trask** [comment]
here's a snapshot build with the improvement if you want to try it out: https://github.com/microsoft/ApplicationInsights-Java/files/7583682/applicationinsights-agent-3.2.4-BETA-SNAPSHOT.jar.zip
