### ISSUE TITLE
Be able to configure logging levels for classes in the applicationinsights-agent.jar

### ISSUE THREAD

**Issue by vap78** [microsoft/ApplicationInsights-Java#1972]
### Expected behavior
Log levels for classes in the agent jar should be configurable like any other loggers.

### Actual behavior
I have a Spring Boot application instrumented with application insights and running in a Docker container. 
Command line is similar to what is described in https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-arguments . 

I attempted to configure log level for com.microsoft.applicationinsights.agent.internal.common to ERROR in:
- the application.yaml file of Spring Boot
- in the logback-spring.xml file

None of these has any effect. The effective log level remains the same. 

Example configuration:

application.yaml:
```
logging:
    level:
        com.microsoft.applicationinsights.agent.internal.common: ERROR

```
logback-spring.xml

```
<configuration>
    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
    <include resource="org/springframework/boot/logging/logback/console-appender.xml" />
    <root level="WARN">
        <appender-ref ref="CONSOLE" />
    </root>
    <logger name="com.microsoft.applicationinsights.agent.internal.common" level="ERROR"/>
</configuration>

```
With this configuration we still get logs like:

`2021-11-22 13:35:13.423Z WARN  c.m.a.a.i.common.TelemetryTruncation - Telemetry was truncated: truncated RemoteDependencyData.data...
`

### System information
Please provide the following information:
 - SDK Version: 3.2.3 - taken from https://github.com/microsoft/ApplicationInsights-Java/releases/download/3.2.3/applicationinsights-agent-3.2.3.jar
 - OS type and version: docker image based on  docker.io/openjdk:8-jdk-alpine
 - Application Server type and version (if applicable): Spring Boot 2.5.5
 - Using spring-boot - Yes

**Comment by vap78** [comment]
As a side note - there is a link that is supposed to advice how to collect debug data from the SDK:
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk which might contain a hint about how to configure those log levels. 

However there is no such anchor on the page and I don't find any information about collecting debug data from the SDK there.

**Comment by trask** [comment]
hi @vap78!

the TelemetryTruncation logging was indeed way too verbose (#1964)

this was just fixed recently, can you try out the latest SNAPSHOT build to see if this works for you? https://github.com/microsoft/ApplicationInsights-Java/files/7583682/applicationinsights-agent-3.2.4-BETA-SNAPSHOT.jar.zip

**Comment by Ramblurr** [comment]
> None of these has any effect. The effective log level remains the same.

FYI your attempts to change the logging have no affect because AI is running as a javaagent, and is totally separate from the spring boot application. Boot is not aware that AI even exists.

**Comment by vap78** [comment]
Thanks!

The beta release looks much better. We'll however wait for an official release, before adopting this to production. 
From what I can see those logs are not sent to app insights, but they appear in the container log of K8S and in the "kubectl logs ..." command which is a bit annoying.

So there is no way to configure the log severities for code that is running as javaagent? If there is, then it might be a useful addition to the documentation since this is how this component is running all the time.
Otherwise I consider then this ticket closed - there is a fix that is going to be release sooner or later. 

Best regards
Vasil
