### ISSUE TITLE
Unable to Get Operation_ID and Operation_Name while using slf4j-logback  for function app

### ISSUE THREAD

**Issue by saikiran12344** [microsoft/ApplicationInsights-Java#1988]
I am using the slf4j logback in the funciton app

I am getting the logs as expected but not operation Id and operation name

### To Reproduce

###logback.xml

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%message%n</pattern>
    </encoder>
  </appender>

  <logger name="com.azure.core" level="ERROR" />

  <root level="INFO">
    <appender-ref ref="STDOUT" />
  </root>
</configuration>

**Comment by heyams** [comment]
Can you answer a couple of questions:
- Is it linux or windows? 
- which version of java agent? 
- can you share what you get and what do you expect to see?

We didn't capture operation_id  in the log when there is no parent. not sure if you are in this case. please clarify a bit more.
