### ISSUE TITLE
Get SQL Command params

### ISSUE THREAD

**Issue by sidyes** [microsoft/ApplicationInsights-Java#1989]
**Is your feature request related to a problem? Please describe.**
I cannot see the paramaters on Application Insights for a performed SQL command. They are masked with a `?`.

**Describe the solution you would like**
I would like to have possibility to not mask the parameters. This should be somehow configurable.
Is this possible?

**Describe alternatives you have considered**
Logging SQL statements manually by wrapping their calls.

**Additional context**

**Comment by Jitu-Ranjan** [comment]
When are we expecting an enhancement around this requirement, do we have any configs to disable masking in AI agent JSON config yet?

**Comment by trask** [comment]
hi @sidyes @Jitu-Ranjan! we will pull this feature into Application Insights Java once it has been added upstream in OpenTelemetry (https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/400)
