### ISSUE TITLE
Json structured log miss some attributes

### ISSUE THREAD

**Issue by morland96** [microsoft/ApplicationInsights-Java#1991]
### Expected behavior
Logs collected from the containerLog (original)
```
{
"@timestamp":"2021-12-02T06:50:04.014Z",
"@version":"1",
"message":"********************",
"logger_name":"**************",
"thread_name":"http-nio-8080-exec-4",
"level":"INFO",
"level_value":20000,
"x-request-id":"a5ce96e3cd2ed43fd4dc174b392f6e14",
"podNamespace":"******",
"podName":"**********"
}
```
Expecting same log structure in the app insights
### Actual behavior
customDimension in app insights
```
{"LoggerName":"*******",
"LoggingLevel":"INFO",
"SourceType":"Logger",
"ThreadName":"http-nio-8080-exec-4",
"x-request-id":"a5ce96e3cd2ed43fd4dc174b392f6e14"}
```

### System information
Please provide the following information:
 - SDK Version: 3.2.3
 - Application Server type: AKS
 - Using spring-boot: yes
 - Additional relevant libraries: logbook

**Comment by trask** [comment]
hi @morland96! can you post your logback configuration file, and how you are passing those attributes into your logs (e.g. slf4j MDC or some other way)? thx
