### ISSUE TITLE
Need to prevent blank url requests

### ISSUE THREAD

**Issue by grvriend** [microsoft/ApplicationInsights-Java#1995]
### Expected behavior
Not to receive thousands of blank requests

### Actual behavior
Enabled the java agent on the JVM on the Coldfusion server and received thousands of blank requests in addition to the good requests.

### To Reproduce
Add java agent to the jvm and restart the server

#### Sample Application
Below is my applicationinsights.json
`{
    "connectionString": "{REMOVED}",
    "sampling": {
      "percentage": 100
    },
    "jmxMetrics": [
    ],
    "customDimensions": {
    },
    "instrumentation": {
      "logging": {
        "level": "INFO"
      },
      "azureSdk": {
        "enabled": false
      },
      "cassandra": {
        "enabled": false
      },
      "jdbc": {
        "enabled": true
      },
      "jms": {
        "enabled": false
      },
      "kafka": {
        "enabled": false
      },
      "micrometer": {
        "enabled": false
      },
      "mongo": {
        "enabled": false
      },
      "rabbitmq": {
        "enabled": false
      },
      "redis": {
        "enabled": false
      },
      "springScheduling": {
        "enabled": false
      }
    },
    "proxy": {
    },
    "selfDiagnostics": {
        "destination": "file+console",
        "level": "INFO",
        "file": {
          "path": "applicationinsights.log",
          "maxSizeMb": 5,
          "maxHistory": 1
        }
    }
}`

### System information
Please provide the following information:
 - Java agent 3.2.3
 - Java 11.0.12
 - Coldfusion 2018 Enterprise Update 12

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

### Screenshots
![image](https://user-images.githubusercontent.com/6607480/145273802-bb8f9d3e-8a3a-4fca-9f0c-1aabc4b14c7c.png)

**Comment by trask** [comment]
hi @grvriend! can you enable `debug` logging (under `selfDiagnostics`) and attach the debug log, or at least the portion that corresponds to the capture of one of those empty urls? that will hopefully give us some clues what might be wrong, thx!

**Comment by grvriend** [comment]
Closing issue, as I have found in the logs it was a firewall heartbeat causing the issue.  Thanks for the quick response!
