### ISSUE TITLE
HTTP 302 is changed to 200 after App Insights agent enabled, webapp hosted in WebLogic Server

### ISSUE THREAD

**Issue by c10100** [microsoft/ApplicationInsights-Java#1999]
When Java agent is not enabled, the normal flow is
1.	user enter a wrong credential 
2.	302 to /obrar.cig?encreply=xx
3.	302 to /ords-int/apex/f?p=101 
4.	302 to /ords-int/apex/f?p=101:1::::::

Environment
====
Server:                 Red Hat Enterprise Linux Server release 7.9
Middleware:      Oracle WebLogic Server 12.2.1.4.210629
Oracle JDK:         Version 1.8.0_301
ORDS:                   Version 19.2

Codeless agent version: version 3.2.1 and 3.2.3, both have this problem

However it stops at step 3 when Java codeless agent is enabled.
(left: without agent, right: with agent; the full HAR files are attached)
![image](https://user-images.githubusercontent.com/22928611/145505036-d46030c5-b587-424a-8969-07b948b8e51e.png)
![image](https://user-images.githubusercontent.com/22928611/145505044-9ca54521-cdf4-4bd7-9780-f53379f04bd2.png)

Analysis
====
Besides this behavior change, we don’t notice other app insight problem yet. Metrics are collected and sent to app insights successfully. 

We also enabled agent log, but no error / issue we find might be related to this problem.
We also filtered the URL according to https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-sampling-overrides#example-suppress-collecting-telemetry-for-health-checks, but the issue persists.

**Comment by heyams** [comment]
there is an icm created for the same issue. I've responded to the icm. I think it's you. please confirm. we can communicate over there. can you provide a sample app for a repro? thanks.

**Comment by c1010buggy** [comment]
> 

yep. it was me :)

**Comment by trask** [comment]
this was fixed in 3.2.5-BETA
