### ISSUE TITLE
ERROR : Unable to find valid certification path to requested target.

### ISSUE THREAD

**Issue by Sachin1O1** [microsoft/ApplicationInsights-Java#2006]
ERROR log:

2021-12-08 09:48:29.449Z ERROR c.m.a.a.i.telemetry.TelemetryChannel -
*************************
Unable to find valid certification path to requested target.
*************************

Description:
ApplicationInsights Java Agent failed to send telemetry data.

Action:
Please import the SSL certificate from https://dc.services.visualstudio.com/v2.1/track, into the default java key store located at:
/opt/java/openjdk/lib/security/cacerts
Learn more about importing the certificate here: https://go.microsoft.com/fwlink/?linkid=2151450

Note:
This message is only logged the first time it occurs after startup.

2021-12-08 09:48:29.649Z WARN c.m.a.a.i.telemetry.TelemetryChannel - Sending telemetry to the ingestion service (telemetry will be stored to disk on failure and retried later):: Error sending telemetry items: handshake timed out after 10000ms (future warnings will be aggregated and logged once every 5 minutes)
io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
at io.netty.handler.ssl.SslHandler$7.run(SslHandler.java:2112)
at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:836)
2021-12-08 09:49:21.650Z INFO c.m.applicationinsights.agent - ApplicationInsights Java Agent 3.2.3 started successfully (PID 6)

Question: 
Do I need to do the above action for all the services that I have or do we have any other way?

**Comment by heyams** [comment]
Yes, please import the ssl cert and follow the instruction link provided. You only need to do once.

**Comment by Sachin1O1** [comment]
Ok great. Thanks for the quick response @heyams.
Just one more question why do we need to do this. isn't this should be auto resolved. Like if I have more than 100 containers then this can be toil.

**Comment by Sachin1O1** [comment]
Also, I have to add different SSL certificates for different env (dev/QA/prod) as they are in different regions and hence ingestion endpoint will be different leads to different SSL certificates I guess.

**Comment by zohebs341** [comment]
@Sachin1O1 @heyams 
I'm also facing similar type of errors, but not specific to certs. In my case, pods are crashing/restarting with OOM error. I've created an issue as well, please assist if possible

Region being used in configmaps is UAE North, but in logs it's showing west- us. 

Error:

java.net.UnKnownHostException: westus-0.in.applicationinsights.azure.com: System error

No where we have specified region as westus-0, but in logs its pointing to westus-0 and after few hours - pods are crashing with OOM error.

Continuously logs are flowing like below:

Error sending telemetry items: westus-0 - in the last 5 minutes, following Operation has failed 10 times

**Comment by trask** [comment]
hi @zohebs341, I replied to the separate issue (#2017) you opened for this issue

**Comment by Sachin1O1** [comment]
Hi, @trask any update on my issue?

**Comment by trask** [comment]
hey @Sachin1O1, have you customized the default jdk cert file? (in your case, `/opt/java/openjdk/lib/security/cacerts`)

the necessary root certs should be in there already by default

**Comment by Sachin1O1** [comment]
Hi @trask,

No, I didn't customize the default JDK cert file.
I am using adoptopenjdk:11 image btw.

**Comment by trask** [comment]
> I am using adoptopenjdk:11 image btw

thx this was helpful. I confirmed that this image has the correct certs.

I noticed that the underlying exception you are getting is `SslHandshakeTimeoutException`, so it looks like you are getting a timeout issue instead of a cert issue, and we are misinterpreting it and logging that you have a cert issue from inside of the application insights agent.

does this happen every time, or does it work sometimes?

can you try to `curl` to the endpoint from inside of your container (and time how long it takes)? e.g.

```
root@8e576a4f3390:/# curl https://dc.services.visualstudio.com/v2.1/track
Method Not Allowed
root@8e576a4f3390:/#
```

(`Method Not Allowed` is expected)

**Comment by Sachin1O1** [comment]
Hi @trask,

I check all my services and now I am not seeing the cert error at application startup in the logs and also not sure for **SslHandshakeTimeoutException** in the logs need to monitor for more time.

I also executed the curl https://dc.services.visualstudio.com/v2.1/track and I am getting the same response 

root@8e576a4f3390:/# curl https://dc.services.visualstudio.com/v2.1/track
Method Not Allowed

and response is too quick.

**Comment by trask** [comment]
@Sachin1O1 thx for the update, we will fix the misleading `SslHandshakeTimeoutException` message about invalid cert. let us know if you see the `SslHandshakeTimeoutException` in the future and we can look into it further

**Comment by dupinderdhiman** [comment]
Hello @trask,
In what version of application insight we are going to see the fix?
