### ISSUE TITLE
Pod is crashing/restarting with OOM Error

### ISSUE THREAD

**Issue by zohebs341** [microsoft/ApplicationInsights-Java#2017]
### Expected behavior
Pod should not crash/restart

### Actual behavior
Pod is crashing/restarting with OOM error.

I'm having few questions related to Application Insights version 3.2.3.

Azure AKS with microservies being deployed along with App Insights Jar.

Continuously within a day or twice, microservies are crashing with OOM error & pod is restarting.

When I've gone through logs, I can see below error all the times.

Error/Exception:

Sending telemetry to ingestion service
UnknownHostException westus-0.in.applicationinsights.azure.com: system error

In our code, the actual location we pointed is UAE North. But I don't know in logs, its showing west- us & application is crashing frequently with OOM error.

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: 3.2.3
 - OS type and version: App insight is running with a pod with default configuration
 - Application Server type and version (if applicable):
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable):

**Comment by trask** [comment]
> Sending telemetry to ingestion service
UnknownHostException westus-0.in.applicationinsights.azure.com: system error
>
> In our code, the actual location we pointed is UAE North. But I don't know in logs, its showing west- us & application is crashing frequently with OOM error.

hi @zohebs341, this should be resolved in 3.2.4

**Comment by zohebs341** [comment]
@trask Thanks for your feedback.

Is it a bug in 3.2.3, which is going to be fixed in 3.2.4 ?

if you can provide more details, it will be helpful for us to plan for upgrade.

As for upgrade version, we need to have proper justification.

Appreciate your response on this.

**Comment by trask** [comment]
@zohebs341 yes, it was fixed by #1994, which was included in 3.2.4 release which is already available: https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.2.4 (just noticed we need to update [docs.microsoft.com](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent) to point to 3.2.4)

**Comment by zohebs341** [comment]
@trask Thanks for confirming.

**Comment by trask** [comment]
hi @zohebs341, just wanted to check if your issue is resolved now? thx

**Comment by zohebs341** [comment]
Hi @trask just tested for one microservice with 3.2.4 version. In that, we don’t see logs pointing to westus

thank you
