### ISSUE TITLE
Log entries lost due to "Queue is full"

### ISSUE THREAD

**Issue by amarkevich** [microsoft/ApplicationInsights-Java#2028]
### Expected behavior
All logs available using
```
traces
| where cloud_RoleName == "app"
| order by timestamp desc
```

### Actual behavior
Some log records missing:
`1/4/2022, 12:33:02.355 PM ...`
[missing]
`1/4/2022, 12:32:28.396 PM ...`

Happens regularly during Camel routes activated by scheduler (import from file to in-memory SQL DB):

Route 1 started at 01:30: `1/6/2022, 1:30:31.790 AM | * Queue is full (5894 times)`

Route 2 started at 05:00: `1/6/2022, 5:05:31.796 AM | * Queue is full (2456 times)`

### System information
 - SDK Version: 3.2.4 (no such issue with 3.1.1)
 - OS type and version: Linux 5.4.0-1062-azure x86_64
 - Application Server type and version (if applicable): Tomcat 8.5.58
 - Using spring-boot? No
 - Additional relevant libraries (with version, if applicable): AKS 1.20.13, no CPU limit set,
   IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/
   Camel 2.20.1, instrumentation is not configured
    OpenJDK Runtime Environment (Zulu 8.42.0.23-linux64)-Microsoft-Azure-restricted (build 1.8.0_232-b18)
    OpenJDK 64-Bit Server VM (Zulu 8.42.0.23-linux64)-Microsoft-Azure-restricted (build 25.232-b18, mixed mode)

### Logs
`2022-01-04 12:32:22.924Z WARN c.m.a.a.i.t.BatchSpanProcessor - Queuing span: Queue is full (future warnings will be aggregated and logged once every 5 minutes)`

**Comment by amarkevich** [comment]
there is no such error in case env var `APPLICATIONINSIGHTS_INSTRUMENTATION_JDBC_ENABLED` set to `false`

**Comment by trask** [comment]
hi @amarkevich, thanks for reporting this!

> SDK Version: 3.2.4 (no such issue with 3.1.1)

just to clarify, this was probably an issue in 3.1.1 also, we just weren't logging it

I just added an config option that you can use to increase the queue size, if you have a chance, try out the latest SNAPSHOT build:

https://github.com/microsoft/ApplicationInsights-Java/suites/4874320064/artifacts/139220773

and add this configuration option:

```
{
  "preview": {
    "exportQueueCapacity": 10000
  }
}
```

the log message also now includes info on how to increase the queue size.

**Comment by trask** [comment]
btw, we found that a common culprit of "queue is full" is due to bursty metric recording which occurs once a minute, so we have split out metrics into separate queue and increased the size of that queue. this will be available in next release, or now in latest SNAPSHOT: https://github.com/microsoft/ApplicationInsights-Java/suites/4997129948/artifacts/146434756
