### ISSUE TITLE
How to retrieve Cloud Role Instance ID using SDK ?

### ISSUE THREAD

**Issue by anumalasri** [microsoft/ApplicationInsights-Java#2029]
While monitoring logs, we find that logging 'Role Instance ID' might be helpful for quick troubleshooting. 

We tried to get cloud role instance using below snippet.

```
RequestTelemetry requestTelemetry = ThreadContext.getRequestTelemetryContext().getHttpRequestTelemetry();
log.info('Cloud Role: {}', requestTelemetry.getContext().getCloud().getRoleInstance() )
```

However, we could see below log and Role Instance Id is null. 

`WARN  c.m.applicationinsights.interop.web - ThreadContext.getRequestTelemetryContext().getRequestTelemetry().getContext().getCloud() is not supported by the Application Insights for Java 3.0 agent (this message will only be logged once)`
 
 Is there any way to get Role Instance Id using SDK 2.6.x and Java Agent 3.2.x+. 
 
 Thanks

**Comment by heyams** [comment]
can you try this instead:
`ThreadContext.getRequestTelemetryContext().getHttpRequestTelemetry().getProperties().get("ai.cloud.roleInstance")`. 

`ThreadContext.getRequestTelemetryContext().getRequestTelemetry().getContext().getCloud()` currently is not supported yet.

**Comment by trask** [comment]
> can you try this instead: `ThreadContext.getRequestTelemetryContext().getHttpRequestTelemetry().getProperties().get("ai.cloud.roleInstance")`.
> 
> `ThreadContext.getRequestTelemetryContext().getRequestTelemetry().getContext().getCloud()` currently is not supported yet.

unfortunately this won't work either

when you do `log.info(...)`, the agent will capture the info message and send to the portal, and the role instance id will be attached to the info message automatically

or are you specifically wanting the role instance id to appear in a log file on disk? if this is the case, do you specifically need the role instance id, or are you just looking to log the machine name?

thx

**Comment by anumalasri** [comment]
Currently we are running application in App Service using container environment.  We also setup dynamic scale out, so that containers will be created and/or removed dynamically.   

> do you specifically need the role instance id, or are you just looking to log the machine name?

I believe,  Role instance id will be same as machine name in container environment.

**Comment by trask** [comment]
hi @anumalasri, if you are looking for the machine name, I'd recommend `InetAddress.getLocalHost().getHostName()` (this is same call that the agent uses for the default role instance id)

**Comment by anumalasri** [comment]
@trask ..  We will fall back onto that option to get hostname.  Thanks for update.
