### ISSUE TITLE
Filtering out exception telemetries sent by agent

### ISSUE THREAD

**Issue by lidkowiak** [microsoft/ApplicationInsights-Java#2032]
**Is your feature request related to a problem? Please describe.**

When using AI agent with JDBC API in case of an exception agent sends an exception telemetry to AI. The exception is then also handled by application code and in some case there is not need to send the exception to AI because such exception is expected  or operation could be retried. This is especially import when sensitive alerting (on each exception) is used that causes false positives.

**Describe the solution you would like**
Add the possibility to agent config to filter out exceptions sent by agent. In version 2.x of the agent we use custom telemetry processor to filter out such exceptions based on empty LoggerName custom dimension.  

**Describe alternatives you have considered**
We can write alert queries that ignores such exceptions.

**Comment by trask** [comment]
> When using AI agent with JDBC API in case of an exception agent sends an exception telemetry to AI

This is resolved in 3.3.0-BETA.2 by #2307.
