### ISSUE TITLE
HTTP 404 from Spring Boot using app insights v2.6.0

### ISSUE THREAD

**Issue by skylaro** [microsoft/ApplicationInsights-Java#2049]
### Expected behavior
Application would run as expected and send telemetry to app insights resource.

### Actual behavior
All requests to Spring Boot app would return HTTP 404 on app insights v2.6.0 while telemetry continued being sent over. This is not a request for a fix, but rather help to RCA why v2.6.0 would break our Spring Boot application.

### To Reproduce
1. Deploy application WAR file to azure app services.
2. Send requests to application and receive 404 errors in response.
3. Remove app insights v2.6.0 from dependency tree to eliminate 404 errors. Also works by upgrading to v2.6.4.

#### Sample Application
If applicable, provide a sample application which reproduces the issue.
N/A

### System information
Please provide the following information:
 - SDK Version: 2.6.0
 - OS type and version: Azure app services Windows container app
 - Application Server type and version (if applicable): Tomcat 9
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable):

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

**Comment by heyams** [comment]
As you have mentioned, v2.6.4 works for you. Is there reason you need to use v2.6.0?  If you go through the releases notes from v2.6.0 to v2.6.4, there are many fixes.  I would recommend upgrade to the latest.
