### ISSUE TITLE
OpenTelemetry TraceId & SpanId values return zeros

### ISSUE THREAD

**Issue by zoomingrocket** [microsoft/ApplicationInsights-Java#2057]
### Expected behavior
We are trying to get existing trace id & span id for logging and additional correlation so actual traceid & spanid values should be non zeroes

### Actual behavior
Actual Traceid & spanid are returned as zeros
TraceId:00000000000000000000000000000000
SpanId:0000000000000000

App Insight only captures Trace Entries, no request registered

### To Reproduce
Include opentelemetry-api-1.6.0.jar & opentelemetry-context-1.6.0.jar in classpath
JVM started with java agent 3.2.4.jar
Run the app to print values

```
import io.opentelemetry.api.trace.Span;

String traceId = Span.current().getSpanContext().getTraceId();
String spanId = Span.current().getSpanContext().getSpanId();

```

#### Sample Application
N/A. App is constructed within proprietary middleware platform

### System information
Please provide the following information:
 - SDK Version: Java Agent 3.2.4
 - OS type and version: Cent OS LInux x64 7.9
 - Application Server type and version (if applicable):
 - Using spring-boot? No
 - Additional relevant libraries (with version, if applicable): opentelemetry-api-1.6.0.jar & opentelemetry-context-1.6.0.jar

### Screenshots
![image](https://user-images.githubusercontent.com/2420449/150032187-97c91504-f26e-4db6-9a71-61606a5496e5.png)

**Comment by trask** [comment]
hi @zoomingrocket!

where are you adding this code?

```
import io.opentelemetry.api.trace.Span;

String traceId = Span.current().getSpanContext().getTraceId();
String spanId = Span.current().getSpanContext().getSpanId();
```

e.g. in a servlet filter, spring controller, etc?

**Comment by zoomingrocket** [comment]
@trask  - We opened another Issue# [2048](https://github.com/microsoft/ApplicationInsights-Java/issues/2048) and after studying some material around Event Hub it was apparent that Event Hubs do not have a message header concept where W3C trace related info can be pushed in automatically for correlation. We use RabbitMQ in the ecosystem and we see those trace headers are automatically pushed onto messages for distributed correlation of a transaction by Java Agent.

So in the same spirit, we investigated Event Hub and bumped into a sample use case between [Azure Event Hub & Azure functions](https://medium.com/swlh/correlated-logs-deep-dive-for-eventhub-triggered-azure-function-in-app-insights-ac69c7c70285) which requires us to use specific event message body with properties where trace id can be pushed for establishing correlation. 
As part of the whole experiment, our first step was to get the current trace id, span id so that we can interject in the event body properties to see if correlation comes out well but stuck on step 1 to get current trace id & span id!

The piece of code is part of the API developed on the middleware platform (COTS) which is actually going to publish the event message to Event Hub. Middleware platform JVM is hooked to 3.2.4 App Insight JavaAgent and that's how we keep our observability for entire ecosystem

**Comment by trask** [comment]
@zoomingrocket it sounds like #2048 is the real issue then?

**Comment by zoomingrocket** [comment]
@trask  - That's right, this is another alternate way we were trying to manually register the request, but we were unable to span or propagate the traceparent for subsequent executions within the parent execution just due to the nature of COTS. Ideally we need a way to indicate to App Insight Agent that, any invocations of a particular class name, start a new request span and collect remaining invocations as dependencies, and actually, all the dependencies do get captured correctly if the starting request gets registered properly in case of known java entry points like a new JMS message or a HTTP REST API invocation.
Not sure if I am making sense, but trying our best to extend App Insight observability for our COTS which functions for 95% of usecases, except for these gray areas where the request starts with a custom class.

**Comment by trask** [comment]
makes sense, let's close this issue then and continue discussing on #2048
