### ISSUE TITLE
Allow reading the connection string from a file

### ISSUE THREAD

**Issue by timja** [microsoft/ApplicationInsights-Java#2069]
**Is your feature request related to a problem? Please describe.**
I would like to be able to separate the connection string information from the general configuration and not check it into source code as we have different instances of application insights for different environments

**Describe the solution you would like**
A environment variable and system property that point to the file to read just the Connection string information from

**Describe alternatives you have considered**
- Currently I'm having to store the whole configuration in Azure Key Vault so that I can mount it as a file to be read by the application using the `APPLICATIONINSIGHTS_CONFIGURATION_FILE` override.

**Additional context**
This is in a container on AKS using the [csi-secrets-store-driver](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)

We're running in distroless containers with no shell so can't run an init script to hack around this

**Comment by heyams** [comment]
@timja You can set the connection string using the environment variable APPLICATIONINSIGHTS_CONNECTION_STRING.  (which will then take precedence over connection string specified in the json configuration).  Hope that helps.

**Comment by timja** [comment]
It doesn’t because all our secrets come in as files mounted to the file system using the csi driver above.

**Comment by heyams** [comment]
once you mounted secrets (including connection string) to the file system, you can read it and set it into APPLICATIONINSIGHTS_CONNECTION_STRING env var?  

Alternatively, instead of using a configuration file, you can specify the entire content of the json configuration via the environment variable APPLICATIONINSIGHTS_CONFIGURATION_CONTENT.

**Comment by timja** [comment]
How could I read and set it? In the description I said there’s no shell.

I don’t see how setting the config env var helps at all

previously we used the spring boot support for Kubernetes and it handled this trivially but now that there’s no spring boot starter the configuration options here are far more limited, (we’ve put this upgrade off for ages but 2.x doesn’t support Java 17 so finally doing it)

I’m also happy to contribute this if it’s something you would take

**Comment by heyams** [comment]
Sorry, i missed the no shell part. Please let us think about a bit more and will get back to you.

**Comment by heyams** [comment]
@timja will this work for you: 

`{
   connectionString: "${file:mounted_connection_string_file.txt}" 
}`

mounted_connection_string_file.txt contains only the connection string and in the format of `InstrumentationKey=${InstrumentationKey};IngestionEndpoint=${IngestionEndpoint}` (i.e. connection string from the azure portal). 

Please confirm.

**Comment by timja** [comment]
Yes that would be perfect

**Comment by heyams** [comment]
Yes, I will implement it this week and will give you a snapshot to try it out when available.

**Comment by heyams** [comment]
@timja can you try [3.2.6-BETA-SNAPSHOT.jar](https://applicationinsightsjava.blob.core.windows.net/unsigned/applicationinsights-agent-3.2.6-BETA-SNAPSHOT.jar)? We will release it in the near future.  Thanks.

**Comment by heyams** [comment]
@timja oops, I fixed the release note. but I remembered to include in the azure doc PR which is pending on review. thanks!
