### ISSUE TITLE
Allow multiple configuration files

### ISSUE THREAD

**Issue by timja** [microsoft/ApplicationInsights-Java#2070]
**Is your feature request related to a problem? Please describe.**
I would like to be able to separate the connection string information from the general configuration

**Describe the solution you would like**
Allow reading multiple files via env var or system property with a comma separated list
(No need to mix and match, i.e just environment or system property at the same time to keep it simpler)

**Describe alternatives you have considered**
- Currently I'm having to store the whole configuration in Azure Key Vault so that I can mount it as a file to be read by the application using the `APPLICATIONINSIGHTS_CONFIGURATION_FILE` override.

- A separate configuration value just for the connection string that points to a file that it will be read from, raised as https://github.com/microsoft/ApplicationInsights-Java/issues/2069

**Additional context**
This is in a container on AKS using the [csi-secrets-store-driver](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)

We're running in distroless containers with no shell so can't run an init script to hack around this

**Comment by heyams** [comment]
does the answer in #2069 resolve this?

**Comment by timja** [comment]
No

**Comment by trask** [comment]
hey @timja, we would like to avoid multiple configuration files, because the merging behavior is not obvious for some of the configuration settings, e.g. `jmxMetrics` (do you union them, or does one set win).

do you have a specific need for this, or does the latest proposal in #2069 address your needs? thx

**Comment by timja** [comment]
Hey Trask, https://github.com/microsoft/ApplicationInsights-Java/issues/2069#issuecomment-1021582939 would solve it nicely, I'll close this
