### ISSUE TITLE
Application Insighsts creating Memory Leak in combination with Azure Blob Storage ( Reactor Netty)

### ISSUE THREAD

**Issue by kwims** [microsoft/ApplicationInsights-Java#2074]
Application Insighsts creating Memory Leak in combination with Azure Blob Storage ( Reactor Netty)

### Expected behavior
We have a application that can send in a short time multiple file to Azure Blob storage and we are using com.azure:azure-storage-blob:12.14.2
When we are not using the application insights the memory remain still

### Actual behavior
When adding -javaagent:/applicationinsights-agent.jar is causing the memory to go rapidly high, leading to GC Roots issues
 

### To Reproduce
1. Run multiple blob put in azure storage without activating  -javaagent:/applicationinsights-agent.jar  and notice that the memory is getting GC
2. Run multiple blob put in azure storage while activating  -javaagent:/applicationinsights-agent.jar  and notice that the memory is NOT getting GC

#### Sample Application
```
class OomBlobStorageTest @Autowired constructor(
    @MockBean val blobMetrics: BlobMetrics,
    val blobStorageClients: List<BlobStorageClient>,
) {

    private val simpleSequence = (1..100).asSequence()

    @Test
    fun provokeSimple() {
        val testFileName = "/oom/test.pdf"
        val byteArray = javaClass.getResource(testFileName)?.readBytes() ?: return
        simpleSequence.forEach {
            val tmpFileName = "test_$it.pdf"
            uploadToAllStorageAccounts(tmpFileName, byteArray, MediaType.APPLICATION_PDF)
        }
        cleanupSimple()
    }

    private fun uploadToAllStorageAccounts(blobName: String, content: ByteArray, mediaType: MediaType) {
        println("Upload file: $blobName to all storage accounts.")
        blobStorageClients.forEach { client ->
            client.storeAsBlob(blobName = blobName, content = content, mediaType = mediaType)
        }
    }

    private fun cleanupSimple() {
        simpleSequence.forEach {
            val tmpFileName = "test_$it.txt"
            println("Delete temp file: $tmpFileName from all storage accounts.")
            blobStorageClients.forEach { client ->
                client.deleteBlob(blobName = tmpFileName)
            }
        }
    }
}
```

### System information
Please provide the following information:
 - SDK Version:  3.2.4
 - OS type and version: zulu-openjdk-alpine:17
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable):
com.azure:azure-storage-blob:12.14.2

### Screenshots
![image](https://user-images.githubusercontent.com/6030506/151139045-621d3d80-2a62-42e7-b015-6e2633757e3e.png)

**Comment by hargut** [comment]
As I also wanted to create a similar ticket, I'm adding the informations in here as the impact is similar.

We are using Spring Boot with OpenJDK 11.0.10 on Azure Container Instances within CentOS container images.

The applications use various other azure libraries (but in our case, no blob storage):
- servicebus
- cosmosdb
- eventhub

Activating the agent leads to a memory leak, which drives the application into OOM. Please find below a screenshot from the ACI monitoring and yesterdays tests. The difference between the situations is only the javaagent flag for application insights. The environment, the container and the workload is nearly identical.
![image](https://user-images.githubusercontent.com/415705/151208923-4eda737a-29ad-4382-8367-8ade8a55a932.png)
![image](https://user-images.githubusercontent.com/415705/151210269-23eaae9d-d277-4e3e-a7db-0fb9fdd36d17.png)

The configuration in place was the following:
```
{
  "instrumentation": {
    "azureSdk": {
      "enabled": false
    },
    "cassandra": {
      "enabled": false
    },
    "jdbc": {
      "enabled": false
    },
    "jms": {
      "enabled": false
    },
    "kafka": {
      "enabled": false
    },
    "logging": {
      "level": "OFF"
    },
    "micrometer": {
      "enabled": true
    },
    "mongo": {
      "enabled": false
    },
    "rabbitmq": {
      "enabled": false
    },
    "redis": {
      "enabled": false
    },
    "springScheduling": {
      "enabled": false
    }
  },
  "selfDiagnostics": {
    "destination": "console",
    "level": "INFO"
  },
  "sampling": {
    "percentage": 0
  },
  "preview": {
    "instrumentation": {
      "akka": {
        "enabled": false
      },
      "apacheCamel": {
        "enabled": false
      },
      "grizzly": {
        "enabled": false
      },
      "quartz": {
        "enabled": false
      },
      "springIntegration": {
        "enabled": false
      }
    },
    "statsbeat": {
      "disabled": true
    },
    "liveMetrics": {
      "enabled": false
    },
    "profiler": {
      "enabled": false
    },
    "sampling": {
      "overrides": [
        {
          "attributes": [
            {
              "key": "http.method",
              "value": ".*",
              "matchType": "regexp"
            }
          ],
          "percentage": 0
        }
      ]
    }
  }
}
```
The artifact used was:
```
com.microsoft.azure:applicationinsights-agent:3.2.4
```

Best regards,
Harald

**Comment by trask** [comment]
hi @kwims and @hargut, for out of memory issues, we need a Java heap dump from the running process to analyze. can you open a support ticket in order to submit one, or you can contact me at trask.stalnaker@microsoft.com if you have another way to get us a heap dump. or if you can provide a standalone repro that we can run that exhibits the same behavior that works too. thx!

**Comment by hargut** [comment]
Hi @trask,

thank you for your feedback. We resolved the issue on our side by switching to the native micrometer azuremonitor registry which works fine, and does not cause any leak.

As we activated the application agent on four containers at the same time and the leak showed up on two of them I wanted to provide some more details on the differences/used libraries. Eventually the issue is related to the servicebus library.

container1 (worked as expected):
 - eventhub

container2 (worked as expected):
 - eventhub
 - cosmos

container3 (agent leaked):
 - servicebus
 - cosmos
 - eventhub

container4 (agent leaked):
 - servicebus
 - cosmos
 - eventhub


Best regards,
Harald

**Comment by trask** [comment]
@kwims @hargut can you test with 3.2.5? I realized this is likely https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4862, which would not have been included in 3.2.4 but is included in 3.2.5

**Comment by trask** [comment]
fantastic 👍

**Comment by hargut** [comment]
Also looks good over here. Thank you. :+1:
