### ISSUE TITLE
Mobile app live metrics support

### ISSUE THREAD

**Issue by rferreira** [microsoft/ApplicationInsights-Java#2090]
**Describe what the problem you have encountered; e.g I'm always frustrated when**
Live metrics work on the web app but not on the mobile, iOS, app. 

**Describe what you want to happen.**
It would be handy if it worked on both the web site as well as the mobile app 

**Describe any alternative solutions or features you've considered.**
Use the web site version of "live metrics" 

**Add any other context or screenshots about the feature request here.**
I'm operating under the assumption here that making it work on the mobile app is just a matter of talking to that team to understand what special requirements they have since the feature already work, quite well if I might add, on the web site 

Thanks!

**Comment by trask** [comment]
hi @rferreira! sorry for the very late reply, is this question related to Application Insights Java?

**Comment by rferreira** [comment]
It is @trask, AI for a Java application does not work on the mobile app, well, the "live metrics" does **not** work that is.

**Comment by trask** [comment]
hi @rferreira, are you instrumenting a mobile app? Or using the Azure Portal on a mobile device?
