### ISSUE TITLE
Add support for postgres R2DBC in the java agent

### ISSUE THREAD

**Issue by petergphillips** [microsoft/ApplicationInsights-Java#2111]
We've looking at switching from using JDBC to using a completely reactive stack and using [R2DBC](https://spring.io/projects/spring-data-r2dbc) with postgres instead.

Using JDBC we had all of the database calls logged as `dependencies`.  This no longer happens when using R2DBC.

It looks like you might support mongo R2DBC (according to https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#autocollected-dependencies) already, but can't see any support for other flavours.

Please could you therefore consider supporting R2DBC using postgres.  I can see our `requests` come through so you currently support netty and webflux, so would be good to add support for the whole stack.

**Comment by trask** [comment]
This is tracked at https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2515, we will pull into Application Insights once it is available upstream

**Comment by trask** [comment]
Instrumentation for r2dbc has just been added upstream in https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2515

**Comment by trask** [comment]
Preview instrumentation for r2dbc is now available in the latest Application Insights Java version: https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#preview-instrumentations
