### ISSUE TITLE
Correlation with trace id in Spring Cloud Slueth

### ISSUE THREAD

**Issue by leonard520** [microsoft/ApplicationInsights-Java#2138]
**Is your feature request related to a problem? Please describe.**
We are using Spring Cloud Slueth and it will genearte a trace id in the app logs
We are in the meanwhile using Application insight agent (3.2.6) to collect information, which will have another trace id (operation id in application insight context).
We are wondering if it is possible to correlate the two parts for easy troubleshooting purpos.
We have tried https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel but not works -- when enable application insight agent, there will be no trace id in sleuth logs.

**Describe the solution you would like**
Is it possible that Spring Cloud Slueth and Application insight agent use the same trace id?

**Describe alternatives you have considered**
N/A

**Additional context**

**Comment by trask** [comment]
hi @leonard520! 

we are considering to pull in upstream OpenTelemetry MDC instrumentation in #2140.

I think this would allow you to capture the OpenTelemetry (Application Insights) trace_id and span_id into your logs using https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/logger-mdc-instrumentation.md

If you could give the SNAPSHOT build a try and see if that works for you that would be really helpful:

https://github.com/microsoft/ApplicationInsights-Java/suites/5439717239/artifacts/172590254

**Comment by trask** [comment]
the prior SNAPSHOT build didn't work for logback, please try this new SNAPSHOT build:

https://github.com/microsoft/ApplicationInsights-Java/suites/5493003940/artifacts/175576458

**Comment by leonard520** [comment]
It should work. Thanks!
