### ISSUE TITLE
B3-multi header propagation

### ISSUE THREAD

**Issue by florianRieb** [microsoft/ApplicationInsights-Java#2158]
### Expected behavior
When the client send a B3-multi header, the trace ID is to be taken from the request.

### Actual behavior
I have a problem with the B3 multi headers, that the trace id is not propagated correctly and regenerated instead.

My spring webflux app, runs with the applicationinsights-java-agent and receives request with header like this:
```
X-B3-TraceId: 63ac35c9f6413ad48485a3953bb6124
X-B3-SpanId: a2fb4a1d1a96d312
X-B3-ParentSpanId: 0020000000000001
X-B3-Sampled: 1
```

My applicationinsights.json looks like this:
```
{
  "preview": {
    "additionalPropagators": [
      "b3multi"
    ],
    "captureHttpServerHeaders": {
      "requestHeaders": [
        "***"
      ]
    },
    "captureHttpClientHeaders": {
      "requestHeaders": [
        "***"
      ]
    }
  }
}
```
And I added also the ENV:
```
OTEL_PROPAGATORS = "tracecontext,b3multi,baggage"
```
I tried the agent-3.2.7, but with this neither 3B single nor multi worked.
Then I took your 3.2.3-BETA-SNAPSHOT and 3.3.0-BETA-SNAPSHOT, with these the single b3 works but also not the multi-header propagation.

Can you imagine what I am doing wrong?

#### Sample Application
Here you can find a minimal [reproducer](https://github.com/florianRieb/b3multi-reproducer)

### System information
 - opentelemetry-api:1.11.0
 - applicationinsights-agent-3.3.0-BETA-SNAPSHOT.jar
 - spring-boot-starter-parent: 2.6.2
 - Java OpenJDK Temurin-17+35

**Comment by trask** [comment]
hi @florianRieb! just wanted to confirm that you intended to close this?

**Comment by florianRieb** [comment]
@trask Yes thanks for your attention, it was not a issue of the agent. The client sende a invalid formatet B3 trace, this leads into an ew genrated trace id.
