### ISSUE TITLE
B3 single headers propagation

### ISSUE THREAD

**Issue by xsmrcek** [microsoft/ApplicationInsights-Java#2162]
**Is your feature request related to a problem? Please describe.**
I figured out, that someapplication in our environemnt are using B3 single header to propagate trace info. So my applicatoin is generation new one, instead of using it.

**Describe the solution you would like**
I would like to your agent to be able to populate traceId etc, from B3 single headers and to be able to send them too, the same was as b3multi and traceparent.

**Describe alternatives you have considered**
I have considered creating some spans manually to do that.

**Additional context**
B3 single format:
`b3={x-b3-traceid}-{x-b3-spanid}-{if x-b3-flags 'd' else x-b3-sampled}-{x-b3-parentspanid}, where the last two fields are optional.`

**Comment by trask** [comment]
here's a 3.3.0-BETA snapshot (from #2183) that supports "b3" (single header b3 format):

https://github.com/microsoft/ApplicationInsights-Java/suites/5642301778/artifacts/184377016

**Comment by trask** [comment]
here's the latest 3.3.0-BETA SNAPSHOT that has everything in it including "b3" support: https://github.com/microsoft/ApplicationInsights-Java/suites/5656154172/artifacts/185207848

**Comment by xsmrcek** [comment]
> 



> here's the latest 3.3.0-BETA SNAPSHOT that has everything in it including "b3" support: https://github.com/microsoft/ApplicationInsights-Java/suites/5656154172/artifacts/185207848

Hello @trask , thank you! But this artefact doesn't seems to be correct. It is 3.2.8-SNAPSHOT and it is sending b3 multi even with configuration:
```
"preview": {
    "additionalPropagators": [
      "b3"
    ],
```

btw: It is possible to turn on both b3 and b3-multi propagators? I wouldn't say it is according to PR, for me personaly it would be great to be able to turn on any crazy combination, as I am developing integration layer of our system and systems we integrate with doesn't always use the same format.

**Comment by trask** [comment]
sorry! wrong download, here you go: https://github.com/microsoft/ApplicationInsights-Java/suites/5660094239/artifacts/185433031

yes, it should support multiple (both `b3` and `b3multi`)

and yes, it should include all of those
