### ISSUE TITLE
A lot of warn error from DeltaMetricStorage

### ISSUE THREAD

**Issue by MelleD** [microsoft/ApplicationInsights-Java#2168]
### Expected behavior
Exclude/Disbale the warn error or how can we avoid this message.

### Actual behavior
Since upgrade to 3.2.7 agent. We have a lot of warn errors of

```
2022-03-10 07:47:04.910Z WARN  i.o.s.m.i.state.DeltaMetricStorage - Instrument http.server.duration has exceeded the maximum allowed accumulations (2000).
2022-03-10 07:47:52.728Z WARN  i.o.s.m.i.state.DeltaMetricStorage - Instrument http.server.duration has exceeded the maximum allowed accumulations (2000).

```

### To Reproduce
Not sure :-)

### System information
Please provide the following information:
 - SDK Version: 3.2.7
 - OS type and version: Azure AKS
 - Application Server type and version (if applicable): jetty
 - Using spring-boot? yes
 - Additional relevant libraries (with version, if applicable):

**Comment by heyams** [comment]
Please take a look at this config: [instrumentation logging level](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#auto-collected-logging)

You can change the logging level to ERROR.  Those warning messages are from OpenTelemetry upstream.

**Comment by MelleD** [comment]
Yes is this new? Upgraded from 3.2.1, never see before.

Ok i will try the ENV property.

**Comment by heyams** [comment]
@MelleD warning log was added 4 months ago according to this [PR](https://github.com/open-telemetry/opentelemetry-java/pull/3831/files).
it was merged on Nov 9, 2021. 
3.2.1 was released before Nov 2021. That might explain why you're seeing it in 3.2.4.  Changing instrumentation logging level should take care of it.

**Comment by MelleD** [comment]
Thanks :)

**Comment by heyams** [comment]
@MelleD Correction. Please use [self-diagnostics logging level](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#self-diagnostics). Instrumentation logging level will control which level of logging will be captured by application insights.. It doesn't have anything to do with logs inside applicationinsights.log. Sorry for the confusion.

**Comment by MelleD** [comment]
Ok 👍
