### ISSUE TITLE
Warning response 500

### ISSUE THREAD

**Issue by sm524s** [microsoft/ApplicationInsights-Java#2172]
### Expected behavior
Describe what you expected to happen.
expected to show only application insight connection error and loss of data
### Actual behavior
Describe what actually happened that was unexpected.
unexpected the warning logs in the pods which are not useful
 WARN  c.m.a.a.i.telemetry.TelemetryChannel - In the last 5 minutes, the following operation has failed 1 times (out of 64): Sending
 * received response code 500 (telemetry will be stored to disk and retried later) (1 times)
### To Reproduce
I tested two pods with the self Diagnostics with ERROR and WARN. 
When I use ERROR as below
"selfDiagnostics": {
    "destination": "file",
    "level": "ERROR"
    }
 I don't see any logs in the applicationinsight.log file.

When I use WARN as below
"selfDiagnostics": {
    "destination": "file",
    "level": "WARN"
    }
I see below warnings in the applicationinsight.log file

2022-03-10 00:00:47.437Z WARN  c.m.a.a.i.telemetry.TelemetryChannel - Sending telemetry to the ingestion service: received response code 500 (telemetry will
2022-03-10 01:40:47.445Z WARN  c.m.a.a.i.telemetry.TelemetryChannel - In the last 5 minutes, the following operation has failed 1 times (out of 64): Sending
 * received response code 500 (telemetry will be stored to disk and retried later) (1 times)
2022-03-10 02:10:47.447Z WARN  c.m.a.a.i.telemetry.TelemetryChannel - In the last 5 minutes, the following operation has failed 1 times (out of 65): Sending
 * received response code 500 (telemetry will be stored to disk and retried later) (1 times)
2022-03-10 03:05:47.449Z WARN  c.m.a.a.i.telemetry.TelemetryChannel - In the last 5 minutes, the following operation has failed 1 times (out of 64): Sending
 * received response code 500 (telemetry will be stored to disk and retried later) (1 times)

#### Sample Application
If applicable, provide a sample application which reproduces the issue.
In the ISAAC application we are using application insight inside the deployment and seeing this unwanted warning in the pod logs.
### System information
Please provide the following information:
 - SDK Version: 
 - OS type and version:
 - Application Server type and version (if applicable):
 - Using spring-boot? yes
 - Additional relevant libraries (with version, if applicable):

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

**Comment by trask** [comment]
hi @sm524s, fix for this is merged, and will be included in 3.3.0 release (eta 1-2 months for GA release)
