### ISSUE TITLE
Camel JMS trace propagation 

### ISSUE THREAD

**Issue by florianRieb** [microsoft/ApplicationInsights-Java#2186]
### Expected behavior
For tracking, we run the Java Agent with a third-party Java application that generates some JMS events and sends them to the Azure Service Bus via AMQP.

The consumers are Spring applications that use the Camel JMS component and receive events on the AMQP endpoint from ASB. This also runs with the java agent + the applicationinsights.json to enable the camel support.

```json
{
  "preview": {
    "instrumentation": {
      "apacheCamel": {
        "enabled": true
      }
    }
  }
}
```

The expected behavior here is that we can track from the creation of the event in the third-party application to the consumption of the event by our consumers and the steps that follow. But the trace propagation to the consumers are not working. At the application map of Azure App Insights we cant follow the trace and see any connection from 3th-party -> ASB -> consumer and no TraceId is generated in the consumer either. 

### Actual behavior
At the consumer we log the JMS event, in the headers we see a traceparent. I assume that this is created by the Java agent.
![f4709d67-6c61-4eab-a97f-edd56e4c604d](https://user-images.githubusercontent.com/22997553/158142885-f9accdf2-94df-4672-88e8-6ff53051b3af.jpg)

As you can see, no TraceId is taken or generated:
![4f81aee4-d07a-4579-aa1a-1b11b373d711](https://user-images.githubusercontent.com/22997553/158143195-ad6da79e-3a06-4f36-8d86-d533964b1397.jpg)

### To Reproduce

For the reproduction I'll take a ActiveMQ instance with a corresponding consumer and send an event with a traceparent header.
 

### System information
Please provide the following information:
 - SDK Version: openjdk 17 2021-09-14
 - Using spring-boot: spring-boot-starter-parent:2.6.2,  camel-jms-starter:3.9.0, qpid-amqp-1-0-client-jms:0.24
 - Application-Insights: applicationinsights-agent-3.2.2.jar

**Comment by trask** [comment]
hi @florianRieb! sorry for the late reply, would it be possible for you to create a sample application which reproduces this issue that we can use to troubleshoot?
