### ISSUE TITLE
exportQueueCapacity - How to determine appropriate value?

### ISSUE THREAD

**Issue by zoomingrocket** [microsoft/ApplicationInsights-Java#2212]
We frequently bump into this entry in the application insight log file

```
`Queuing span:
 * Max export queue size of 16384 has been hit, dropping a span (max export queue size can be increased in the applicationinsights.json configuration file, e.g. { "preview": { "exportQueueCapacity": 32768 } } (48099 times)

```
We have increased based on recommended size, but we get the next incremental value upon restart :D So any suggestion on how to determine the appropriate value instead of trial and error?
Also could not find any documentation around this, so how this value contributes in terms of increased memory consumption or disk usage, etc?

System information
Please provide the following information:

SDK Version: Java Agent 3.2.10
OS type and version: Cent OS LInux x64 7.9
Application Server type and version (if applicable):
Using spring-boot? No

**Comment by trask** [comment]
hi @zoomingrocket, are you still seeing this after updating to 3.2.10? I was hoping this would go away with #2204

**Comment by zoomingrocket** [comment]
@trask  - Yes, still seeing with 3.2.10. Currently no more errors with this configuration: "exportQueueCapacity": 65536

**Comment by trask** [comment]
@zoomingrocket can you attach your applicationinsights.log? I'm a bit uncertain, because `exportQueueCapacity` is not the right setting any more in 3.2.10:

https://github.com/microsoft/ApplicationInsights-Java/blob/main/agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java#L245-L248

**Comment by zoomingrocket** [comment]
@trask  - False alarm! My new 3.2.10 agent jar was not getting into effect. Looked at the logs carefully and it said  "ApplicationInsights Java Agent 3.2.5-BETA started successfully" so after correcting the startup and restarting the application no new alerts for exportQueueCapacity over last 8hrs.

We are good to close this issue.

**Comment by trask** [comment]
Fantastic 🎉
