### ISSUE TITLE
JMX stats : Cannot able to fetch JMX active connection stat from tomcat jdbc connection pool

### ISSUE THREAD

**Issue by Sachin1O1** [microsoft/ApplicationInsights-Java#2247]
Hi, I am trying to get the JDBC connection count that is used by my service.

I am using the following configuration in the JSON config file

 "jmxMetrics": [
    {
      "name": "CP - Active",
      "objectName": "Catalina:type=DataSource,name=Tomcat Connection Pool[1-992682794]",
      "attribute": "Active"
    },
    {
      "name": "CP - MaxActive",
      "objectName": "tomcat.jdbc:type=ConnectionPool,name=Tomcat Connection Pool[1-992682794]",
      "attribute": "MaxActive"
    }
  ]

**Comment by Sachin1O1** [comment]
Hi @trask ,
Still no luck, tried various combinations but getting following error. 
ERROR c.m.a.a.i.p.AbstractJmxPerformanceCounter - Error while fetching JMX data: 'java.lang.IllegalArgumentException: Cannot find object name 'tomcat.jdbc:type=ConnectionPool,name=T*''
ERROR c.m.a.a.i.p.AbstractJmxPerformanceCounter - Error while fetching JMX data: 'java.lang.IllegalArgumentException: Cannot find object name 'Catalina:type=DataSource,name=T*,*''
ERROR c.m.a.a.i.p.AbstractJmxPerformanceCounter - Error while fetching JMX data: 'java.lang.IllegalArgumentException: Cannot find object name 'tomcat.jdbc:type=ConnectionPool,name=j*''

**Comment by trask** [comment]
can you enable self-diagnostic debugging `APPLICATIONINSIGHTS_SELF_DIAGNOSTICS_LEVEL=debug`, and post the debug log? in particular this part should be helpful: https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-jmx-metrics-configuration#how-do-i-know-what-metrics-are-available-to-configure

**Comment by Sachin1O1** [comment]
Hi @trask, I can see two types of debug logs
-> available jmx metrics
-> newly available JMX metrics since the last output

 INFO  c.m.a.a.i.p.AvailableJmxMetricLogger - available jmx metrics: don't have any object name reaalted to connection pool

but after some time I can see newly available JMX Metrics which contains connection pool object as you can see below

`2022-05-06 05:50:19.824Z INFO  c.m.a.a.i.p.AvailableJmxMetricLogger - newly available jmx metrics since last output:
  - object name:        Catalina:j2eeType=Servlet,WebModule=//localhost/mono,name=<something> ,J2EEApplication=none,J2EEServer=none
    attributes: asyncSupported (boolean), available (number), backgroundProcessorDelay (number), classLoadTime (number), countAllocated (number), errorCount (number), loadOnStartup (number), loadTime (number), maxInstances (number), maxTime (number), minTime (number), modelerType (string), objectName (string), processingTime (number), requestCount (number), runAs (other), servletClass (string), singleThreadModel (boolean), stateName (string)
  - object name:        tomcat.jdbc:name="jdbc/catalystone",context=/mono,engine=Catalina,type=ConnectionPool,host=localhost,class=org.apache.tomcat.jdbc.pool.DataSource,connections=PooledConnection[0]
    attributes: AutoCommit (boolean), Catalog (string), Closed (boolean), ConnectionVersion (number), Discarded (boolean), Holdability (number), Initialized (boolean), LastConnected (number), LastValidated (number), MaxAgeExpired (boolean), ReadOnly (boolean), Released (boolean), Schema (string), Suspect (boolean), Timestamp (number), TransactionIsolation (number)
  - object name:        tomcat.jdbc:name="jdbc/catalystone",context=/mono,engine=Catalina,type=ConnectionPool,host=localhost,class=org.apache.tomcat.jdbc.pool.DataSource,connections=PooledConnection[1]
    attributes: AutoCommit (boolean), Catalog (string), Closed (boolean), ConnectionVersion (number), Discarded (boolean), Holdability (number), Initialized (boolean), LastConnected (number), LastValidated (number), MaxAgeExpired (boolean), ReadOnly (boolean), Released (boolean), Schema (string), Suspect (boolean), Timestamp (number), TransactionIsolation (number)
  - object name:        Catalina:type=Valve,host=localhost,context=/mono,name=StandardContextValve
    attributes: asyncSupported (boolean), className (string), modelerType (string), stateName (string)
  - object name:        Catalina:type=DataSource,host=localhost,context=/mono,class=javax.sql.DataSource,name="jdbc/catalystone"
    attributes: abandonWhenPercentageFull (number), accessToUnderlyingConnectionAllowed (boolean), active (number), alternateUsernameAllowed (boolean), borrowedCount (number), className (string), commitOnReturn (boolean), connectionProperties (other), createdCount (number), dataSource (other), dataSourceJNDI (other), defaultAutoCommit (boolean), defaultCatalog (other), defaultReadOnly (other), defaultTransactionIsolation (number), driverClassName (string), fairQueue (boolean), idle (number), ignoreExceptionOnPreLoad (boolean), initSQL (other), initialSize (number), jdbcInterceptors (string), jmxEnabled (boolean), logAbandoned (boolean), logValidationErrors (boolean), loginTimeout (number), maxActive (number), maxAge (number), maxIdle (number), maxWait (number), minEvictableIdleTimeMillis (number), minIdle (number), modelerType (string), name (string), numActive (number), numIdle (number), numTestsPerEvictionRun (number), password (string), poolSweeperEnabled (boolean), propagateInterruptState (boolean), reconnectedCount (number), releasedCount (number), releasedIdleCount (number), removeAbandoned (boolean), removeAbandonedCount (number), removeAbandonedTimeout (number), returnedCount (number), rollbackOnReturn (boolean), size (number), suspectTimeout (number), testOnBorrow (boolean), testOnConnect (boolean), testOnReturn (boolean), testWhileIdle (boolean), timeBetweenEvictionRunsMillis (number), url (string), useDisposableConnectionFacade (boolean), useEquals (boolean), useLock (boolean), useStatementFacade (boolean), username (string), validationInterval (number), validationQuery (string), validationQueryTimeout (number), validatorClassName (other), waitCount (number)
  - object name:        Catalina:type=Valve,host=localhost,context=/mono,name=NonLoginAuthenticator
    attributes: cache (boolean), changeSessionIdOnAuthentication (boolean), className (string), disableProxyCaching (boolean), modelerType (string), securePagesWithPragma (boolean), stateName (string)
  - object name:        tomcat.jdbc:name="jdbc/catalystone",context=/mono,engine=Catalina,type=ConnectionPool,host=localhost,class=org.apache.tomcat.jdbc.pool.DataSource
    attributes: AbandonWhenPercentageFull (number), AccessToUnderlyingConnectionAllowed (boolean), Active (number), AlternateUsernameAllowed (boolean), BorrowedCount (number), CommitOnReturn (boolean), ConnectionProperties (other), CreatedCount (number), DataSource (other), DataSourceJNDI (other), DbProperties (other), DefaultAutoCommit (boolean), DefaultCatalog (other), DefaultReadOnly (other), DefaultTransactionIsolation (number), DriverClassName (string), FairQueue (boolean), Idle (number), IgnoreExceptionOnPreLoad (boolean), InitSQL (other), InitialSize (number), JdbcInterceptors (string), JdbcInterceptorsAsArray (other), JmxEnabled (boolean), LogAbandoned (boolean), LogValidationErrors (boolean), MaxActive (number), MaxAge (number), MaxIdle (number), MaxWait (number), MinEvictableIdleTimeMillis (number), MinIdle (number), Name (string), NumActive (number), NumIdle (number), NumTestsPerEvictionRun (number), Password (string), PoolName (string), PoolSweeperEnabled (boolean), PropagateInterruptState (boolean), ReconnectedCount (number), ReleasedCount (number), ReleasedIdleCount (number), RemoveAbandoned (boolean), RemoveAbandonedCount (number), RemoveAbandonedTimeout (number), ReturnedCount (number), RollbackOnReturn (boolean), Size (number), SuspectTimeout (number), TestOnBorrow (boolean), TestOnConnect (boolean), TestOnReturn (boolean), TestWhileIdle (boolean), TimeBetweenEvictionRunsMillis (number), Url (string), UseDisposableConnectionFacade (boolean), UseEquals (boolean), UseLock (boolean), UseStatementFacade (boolean), Username (string), ValidationInterval (number), ValidationQuery (string), ValidationQueryTimeout (number), Validator (other), ValidatorClassName (other), WaitCount (number)
  - object name:        tomcat.jdbc:name="jdbc/catalystone",context=/mono,engine=Catalina,type=ConnectionPool,host=localhost,class=org.apache.tomcat.jdbc.pool.DataSource,connections=PooledConnection[4]
    attributes: AutoCommit (boolean), Catalog (string), Closed (boolean), ConnectionVersion (number), Discarded (boolean), Holdability (number), Initialized (boolean), LastConnected (number), LastValidated (number), MaxAgeExpired (boolean), ReadOnly (boolean), Released (boolean), Schema (string), Suspect (boolean), Timestamp (number), TransactionIsolation (number)
  - object name:        tomcat.jdbc:name="jdbc/catalystone",context=/mono,engine=Catalina,type=ConnectionPool,host=localhost,class=org.apache.tomcat.jdbc.pool.DataSource,connections=PooledConnection[5]
    attributes: AutoCommit (boolean), Catalog (string), Closed (boolean), ConnectionVersion (number), Discarded (boolean), Holdability (number), Initialized (boolean), LastConnected (number), LastValidated (number), MaxAgeExpired (boolean), ReadOnly (boolean), Released (boolean), Schema (string), Suspect (boolean), Timestamp (number), TransactionIsolation (number)
  - object name:        tomcat.jdbc:name="jdbc/catalystone",context=/mono,engine=Catalina,type=ConnectionPool,host=localhost,class=org.apache.tomcat.jdbc.pool.DataSource,connections=PooledConnection[2]
    attributes: AutoCommit (boolean), Catalog (string), Closed (boolean), ConnectionVersion (number), Discarded (boolean), Holdability (number), Initialized (boolean), LastConnected (number), LastValidated (number), MaxAgeExpired (boolean), ReadOnly (boolean), Released (boolean), Schema (string), Suspect (boolean), Timestamp (number), TransactionIsolation (number)
  - object name:        tomcat.jdbc:name="jdbc/catalystone",context=/mono,engine=Catalina,type=ConnectionPool,host=localhost,class=org.apache.tomcat.jdbc.pool.DataSource,connections=PooledConnection[3]
    attributes: AutoCommit (boolean), Catalog (string), Closed (boolean), ConnectionVersion (number), Discarded (boolean), Holdability (number), Initialized (boolean), LastConnected (number), LastValidated (number), MaxAgeExpired (boolean), ReadOnly (boolean), Released (boolean), Schema (string), Suspect (boolean), Timestamp (number), TransactionIsolation (number)
  - object name:        tomcat.jdbc:name="jdbc/catalystone",context=/mono,engine=Catalina,type=ConnectionPool,host=localhost,class=org.apache.tomcat.jdbc.pool.DataSource,connections=PooledConnection[6]
    attributes: AutoCommit (boolean), Catalog (string), Closed (boolean), ConnectionVersion (number), Discarded (boolean), Holdability (number), Initialized (boolean), LastConnected (number), LastValidated (number), MaxAgeExpired (boolean), ReadOnly (boolean), Released (boolean), Schema (string), Suspect (boolean), Timestamp (number), TransactionIsolation (number)
  - object name:        tomcat.jdbc:name="jdbc/catalystone",context=/mono,engine=Catalina,type=ConnectionPool,host=localhost,class=org.apache.tomcat.jdbc.pool.DataSource,connections=PooledConnection[7]
    attributes: AutoCommit (boolean), Catalog (string), Closed (boolean), ConnectionVersion (number), Discarded (boolean), Holdability (number), Initialized (boolean), LastConnected (number), LastValidated (number), MaxAgeExpired (boolean), ReadOnly (boolean), Released (boolean), Schema (string), Suspect (boolean), Timestamp (number), TransactionIsolation (number)
2022-05-06T05:50:19.825812595Z`

after sometime I can also see a debug log saying no longer available jmx metrics since last output as below

`2022-05-06 05:51:18.023Z INFO  c.m.a.a.i.p.AvailableJmxMetricLogger - no longer available jmx metrics since last output:
  - object name:        Catalina:j2eeType=Servlet,WebModule=//localhost/mono,name=local_default,J2EEApplication=none,J2EEServer=none
    attributes: singleThreadModel (other)
  - object name:        tomcat.jdbc:name="jdbc/catalystone",context=/mono,engine=Catalina,type=ConnectionPool,host=localhost,class=org.apache.tomcat.jdbc.pool.DataSource,connections=PooledConnection[5]
    attributes: AutoCommit (boolean), Catalog (string), Closed (boolean), ConnectionVersion (number), Discarded (boolean), Holdability (number), Initialized (boolean), LastConnected (number), LastValidated (number), MaxAgeExpired (boolean), ReadOnly (boolean), Released (boolean), Schema (string), Suspect (boolean), Timestamp (number), TransactionIsolation (number)
  - object name:        tomcat.jdbc:name="jdbc/catalystone",context=/mono,engine=Catalina,type=ConnectionPool,host=localhost,class=org.apache.tomcat.jdbc.pool.DataSource,connections=PooledConnection[2]
    attributes: AutoCommit (boolean), Catalog (string), Closed (boolean), ConnectionVersion (number), Discarded (boolean), Holdability (number), Initialized (boolean), LastConnected (number), LastValidated (number), MaxAgeExpired (boolean), ReadOnly (boolean), Released (boolean), Schema (string), Suspect (boolean), Timestamp (number), TransactionIsolation (number)
  - object name:        Catalina:j2eeType=Servlet,WebModule=//localhost/mono,name=default,J2EEApplication=none,J2EEServer=none
    attributes: singleThreadModel (other)
  - object name:        tomcat.jdbc:name="jdbc/catalystone",context=/mono,engine=Catalina,type=ConnectionPool,host=localhost,class=org.apache.tomcat.jdbc.pool.DataSource,connections=PooledConnection[6]
    attributes: AutoCommit (boolean), Catalog (string), Closed (boolean), ConnectionVersion (number), Discarded (boolean), Holdability (number), Initialized (boolean), LastConnected (number), LastValidated (number), MaxAgeExpired (boolean), ReadOnly (boolean), Released (boolean), Schema (string), Suspect (boolean), Timestamp (number), TransactionIsolation (number)
`

Maybe this can help you to understand and suggest something. :)

**Comment by Sachin1O1** [comment]
@trask any update?

**Comment by Sachin1O1** [comment]
@trask  Gentle reminder :)

**Comment by trask** [comment]
hi @Sachin1O1,

> INFO c.m.a.a.i.p.AvailableJmxMetricLogger - available jmx metrics: don't have any object name reaalted to connection pool
>
> but after some time I can see newly available JMX Metrics which contains connection pool object as you can see below

and

> after sometime I can also see a debug log saying no longer available jmx metrics since last output as below

Application Insights can only report the JMX metrics that are available. Do you think that the above is incorrect, and those JMX metrics are available?

**Comment by trask** [comment]
Hi @arditazo3! can you open a new issue and describe your question/issue in more detail?
