### ISSUE TITLE
Question - Dependency Tracking 

### ISSUE THREAD

**Issue by anumalasri** [microsoft/ApplicationInsights-Java#2262]
Question: 

We are finding some weird differences in the time taken by our application and dependent HTTP Calls, which transfers a big size of the response. 

May we know,  How does AppInsights track time taken by a dependency HTTP call - say using Apache HTTP Client?  

Does it stop the timer at the first chuck of response?  
         OR 
Does it wait until the last chuck of response?

**Comment by trask** [comment]
hi @anumalasri! ideally we would like to capture time until last chunk (TTLB), but some instrumentation only captures TTFB (and in some older versions and some instrumentations it was even worse)

If you let me know which version of Application Insights Java are you using, and which specific Http Client library and version are you using, I can give you a more precise answer.

**Comment by anumalasri** [comment]
Hi @trask... Here are the versions, we have currently.
 
 AppInsights Agent v3.2.6   
 AppInsight Java SDK v2.6.4
 Spring Boot v2.5.8
 Apache HttpClient v4.5.13

**Comment by anumalasri** [comment]
@trask  ..  can you please update whether dependency tracking is based on TTFB or TTLB ??

**Comment by trask** [comment]
upstream OpenTelemetry Javaagent's Apache HttpClient 4.x is capturing time-to-headers (so closer to TTFB then TTLB)

**Comment by anumalasri** [comment]
Thanks for the confirmation. 

From the application end,  Can we be able to change it to TTLB?

**Comment by trask** [comment]
You can capture your own OpenTelemetry HTTP client spans. If you use the `opentelemetry-instrumentation-api` to capture the HTTP client spans, it will suppress the underlying auto-captured HTTP client span. As `opentelemetry-instrumentation-api` is not yet declared API-stable, this is all slightly bleeding edge, and you will probably need to use upcoming `opentelemetry-instrumentation-api` 1.14.0 release in conjunction with the Application Insights 3.3.0-BETA for it to work.
