### ISSUE TITLE
Filter/Sample requests based on captured header value via app insights config using sampling override feature

### ISSUE THREAD

**Issue by kaynat12** [microsoft/ApplicationInsights-Java#2285]
**Is your feature request related to a problem? Please describe.**
I am using 3.2.11 app insights agent and could capture header values as below in config file, 

"preview": {
    "captureHttpServerHeaders": {
      "requestHeaders": [ "test"] }

I could see that values are stored under custom dimensions as http.request.header.test in requests table

I want to filter out the requests with header 'test' value as true. I tried sampling as below but doesn't seems to work
"sampling": {
      "overrides": [{
          "attributes": [ {
              "key": "http.request.header.test",
              "value": "true",
              "matchType": "strict"}],
          "percentage": 0
        }
I tried with key as customDimensions.["http.request.header.test"] also, still same issue.

**Describe the solution you would like**
1. Need to have a feature to filter requests based on header value via sampling or possible attribute key for it.
2. Any other alternative if above is not possible

**Comment by trask** [comment]
hi @kaynat12, I would expect the sampling override to work, can you put together a small repro that we can use to troubleshoot / identify the issue?

**Comment by kaynat12** [comment]
hi @trask , Thank you for the reply, I have created one sample application and have added you for the repository access, could you take a look?

**Comment by kaynat12** [comment]
hi @trask , could you find any solution?

**Comment by trask** [comment]
hi @kaynat12, if you have a chance, give the latest SNAPSHOT build a try:

https://github.com/microsoft/ApplicationInsights-Java/suites/6753934261/artifacts/258125728

**Comment by kaynat12** [comment]
hi @trask , the sampling is working now, thank you!

**Comment by trask** [comment]
3.3.0-BETA.2 has been released with this fix
