### ISSUE TITLE
hi @sm524s, fix for this is merged, and will be included in 3.3.0 release (eta 1-2 months for GA release)

### ISSUE THREAD

**Issue by declanTreanor** [microsoft/ApplicationInsights-Java#2315]
hi @sm524s, fix for this is merged, and will be included in 3.3.0 release (eta 1-2 months for GA release)

what does this mean? if the data is being saved to disk, how can I be sure that this is not occurring in an endless loop? and version 3.3.0 of what? how do I check what version I'm on? Apologies for the basic question.

_Originally posted by @trask in https://github.com/microsoft/ApplicationInsights-Java/issues/2172#issuecomment-1078610732_

**Comment by heyams** [comment]
Hi @declanTreanor, this is an aggregated warning message every 5 mins if any requests that get an error response code. 
telemetry will be written to disk and retry later. telemetry on the disk will be automatically expire after 48 hours. Anything older than that will get purged. Disk persistence has a capacity of 50 MB. Hope this answers your question. Thanks.

**Comment by declanTreanor** [comment]
> Hi @declanTreanor, this is an aggregated warning message every 5 mins if any requests that get an error response code. telemetry will be written to disk and retry later. telemetry on the disk will be automatically expired after 48 hours. Anything older than that will get purged. Disk persistence has a capacity of 50 MB. Hope this answers your question. Thanks.

thanks Helen.
