### ISSUE TITLE
[upstream] JVM Agent fails to initialize on k8s with containerd runtime

### ISSUE THREAD

**Issue by clawoflight** [microsoft/ApplicationInsights-Java#2328]
Hi, the current version 3.2.11 is affected by https://github.com/open-telemetry/opentelemetry-java/issues/4507,  which completely prevents the agent from starting when `containerd` is used as runtime.
The bug was fixed in [OpenTelemetry 1.15](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.15.0).

Would it be possible to upgrade to that with the 3.3 agent? Not receiving any telemetry is very annoying :)

**Comment by heyams** [comment]
@clawoflight we will notify you when we upgrade to 1.15. thanks for reporting it.

**Comment by clawoflight** [comment]
On June 15, 2022 11:43:16 PM GMT+02:00, Helen ***@***.***> wrote:
***@***.*** we will notify you when we upgrade to 1.15. thanks for reporting it.
>

Thank you! :)

**Comment by trask** [comment]
3.3.0 is released with this fix
