### ISSUE TITLE
Operation Id cannot be overridden for implicitly collected dependencies

### ISSUE THREAD

**Issue by MarekLani** [microsoft/ApplicationInsights-Java#2330]
### Expected behavior
We are setting custom operation id for custom events we track, and we would expect this operation id to propagate to implicitly collected dependencies within the same processing chain. This is however not the case, and it basically means we are not able to achieve distributed tracing.

We tried setting operation Id using telemetry client as well as ThreadContext (see snippet below). Nevertheless, behavior we are seeing is, that any auto collected dependency (in our case HTTP request) invoked in the same processing thread are obtaining different, auto populated telemetry id.

We need to set the operation id to our custom value, as in our tracing we need to cross external boundries (external API Service) which is not supporting propagation of the operation id using headers defined by w3c standard.

### Actual behavior
Implicitly collected dependencies are not honoring operation id set for the context.

### To Reproduce
N/A

#### Sample Application
```
public void setOperationId(String operationId) {
      if (operationId != null) {
          telemetryClient.getContext().getOperation().setId(operationId);
          RequestTelemetryContext c = new RequestTelemetryContext(0);
          c.getHttpRequestTelemetry().getContext().getOperation().setId(operationId);
          c.getHttpRequestTelemetry().getContext().getOperation().setParentId(operationId);
          ThreadContext.setRequestTelemetryContext(c);
      }
}
```

### System information
Please provide the following information:
 - SDK Version: 2.6.4
 - OS type and version: Linux
 - Application Server type and version (if applicable): -
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable): 
   - com.microsoft.azure:applicationinsights-agent:3.2.11
   - com.microsoft.azure:applicationinsights-spring-boot-starter:2.6.4
   - respectively: com.microsoft.azure:applicationinsights-core:2.6.4

### Logs
N/A

**Comment by trask** [comment]
hi @MarekLani!

Is this all happening within a servlet request which is being captured already by Application Insights?

Or is this a background job that you are running, and which Application Insights doesn't automatically capture already?

Or something else?

Thanks,
Trask

**Comment by MarekLani** [comment]
thank you for response @trask . It is background job receiving messages from the queue and making http request on the very same thread. We are trying to set the operation ID just after we receive the message from the queue. We were also trying to obtain the correlation_id generated by App Insights, but when we access the telemetry context it is returning null for operation_id.

**Comment by trask** [comment]
hey @MarekLani, you'll want to use the OpenTelemetry API for this, e.g.

``
    Context context =
        Context.root()
            .with(
                Span.wrap(
                    SpanContext.create(
                        "your-trace-id",
                        "your-parent-span-id",
                        TraceFlags.getDefault(),
                        TraceState.getDefault())));
    try (Scope ignored = context.makeCurrent()) {
      // do your message processing here
    }
```

If you already have a w3c traceparent from your upstream message, check out https://github.com/microsoft/ApplicationInsights-Java/issues/1903#issuecomment-943933680.

**Comment by MarekLani** [comment]
@trask thank you for assistance, I can now confirm, version 3.0.3. of Application Insights Agent contains fix for creating request context for each received message from RabbitMQ which solves our original issue. We can now obtain operation id from telemetry context.

**Comment by trask** [comment]
hi @MarekLani, that's great to hear!

for accessing via AI Telemetry Context, were you trying to use this, or some other way?

```
ThreadContext.getRequestTelemetryContext()
        .getHttpRequestTelemetry()
        .getContext()
        .getOperation()
        .getId()
```

**Comment by MarekLani** [comment]
To access the telemetry context, we ended up using above stated approach thru ThreadContext.getRequestTelemetryContext().

Subsequently to override operation id in the next request processing block, we have created new Span Context using OpenTelemtry:

```
Context context = Context.root().with(
                    Span.wrap(
                        SpanContext.create("<trace-id>", "<span-id>",
		                    	Span.current().getSpanContext().getTraceFlags(),
		                    	Span.current().getSpanContext().getTraceState())));

try (Scope ignored = context.makeCurrent()) {
  // Correlated processing here
}
```

Please note trace-id and span-id need to have specific format. Correctness of trace-id and span-id values can be checkd by calling:

```
SpanId.isValid(CharSequence spanId) 
TraceId.isValid(CharSequence traceId) 
```

A valid trace-id is a 32 character lowercase hex (base16) String, where at least one of the characters is not a "0".
A valid span-id is a 16 character lowercase hex (base16) String, where at least one of the characters is not a "0".

**Comment by trask** [comment]
hi @MarekLani!

I would suggest:

* `Span.current().getSpanContext().getTraceFlags()` -> `TraceFlags.getSampled()`
* `Span.current().getSpanContext().getTraceState()` -> `TraceState.getDefault()`

unless there is a particular reason you need `Span.current()` values there
