### ISSUE TITLE
Async Database/Requests not correlated with main operation (Kafka event)

### ISSUE THREAD

**Issue by Strabox** [microsoft/ApplicationInsights-Java#2356]
### Expected behavior

I would expect to see the trace of the event with all the requests that I make using my Executors.newWorkStealingPool.

I even tried to perform context wrapping with the OpenTelemetry task wrapping, but nothing works the, Mongo DB access which is executed in threadpool stays in a completely separated trace, which makes the traces a bit useless in terms of tracking.

`var es = Context.taskWrapping(Executors.newWorkStealingPool(2));`

### Actual behavior

Mongo DB access which is executed in threadpool (with a submit) stays in a completely separated trace, which makes the traces a bit useless in terms of tracking.

### To Reproduce

Receive an event from Kafka for example and perform a mongo db/cosmos query in a workstealling threadpool.

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: 3.2.11 and 3.3.0
 - OS type and version: Windows 11
 - Application Server type and version (if applicable):
 - Using spring-boot? 2.6.4
 - Additional relevant libraries (with version, if applicable):

### Screenshots

Mongo traces appear like this alone.

![imagem](https://user-images.githubusercontent.com/6809719/176063081-e3a2aa82-eb19-4a31-adb0-a9b83f8a16b2.png)

**Comment by trask** [comment]
hi @Strabox! if you can provide a simple repro (e.g. in a github repository that we can clone) that would help us to investigate this more quickly, thx!

**Comment by jeanbisutti** [comment]
Hi @Strabox, I have added a [test on  the work stealing pool](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6315) and it seems correctly instrumented. A Github repository reproducing the problem would help us to investigate. Thanks!
