### ISSUE TITLE
Span custom dimensions to MDC

### ISSUE THREAD

**Issue by xsmrcek** [microsoft/ApplicationInsights-Java#2381]
I am not able to push logs to application insights as cost would be to big to handle. So I am collecting my logs somewhere else (log analytics currently). I am amissing span custom dimensions there.

I would be glad if agent would be able to add custom dimensions into MDC the same way as it is adding traceId etc.

I have considered doing that manually, or adjusting logback and my loggin mechanism to enrich my log entry with custom fileds. But I would be happy if there is solution everyone from our project can reuse, and application insights javaagent seems as a great choice. As I would be able to use the same filter in application isnsights and log analytics.

**Comment by trask** [comment]
hi @xsmrcek! check out #2138 and let us know if that works for you
