### ISSUE TITLE
How to get OpenTelemetry Tracer instance required to build custom span

### ISSUE THREAD

**Issue by ajaythakran** [microsoft/ApplicationInsights-Java#2401]
I am using this dependency in Spring Boot v2.3 application with Application Insights agent v3.2.1

`		<dependency>
			<groupId>io.opentelemetry</groupId>
			<artifactId>opentelemetry-api</artifactId>
			<version>1.10.0</version>
		</dependency>
`

Creating custom span using below given code. The basic question is to know how to get Tracer object. There is no documentation on how to get Tracer or OpenTelemetry object initialized by Application Insights Agent. 

`
      try (Scope scope = W3CTraceContextPropagator.getInstance().extract(Context.current(), message, new TraceHeadersGetter()).makeCurrent()) {

        // Automatically use the extracted SpanContext as parent.
        Span consumerSpan = tracer.spanBuilder(RECEIVE_OPERATION + message.getLabel())
          .setSpanKind(SpanKind.CONSUMER)
          .startSpan();

        consumerSpan.setAttribute("receivedTime", Instant.now().toString());
        putIfNotNull(consumerSpan, "messageId", message.getMessageId());
        putIfNotNull(consumerSpan, "sessionId", message.getSessionId());
        putIfNotNull(consumerSpan, "correlationId", message.getCorrelationId());
        putIfNotNull(consumerSpan, "deliveryCount", Long.valueOf(message.getDeliveryCount()));
        putIfNotNull(consumerSpan, "lockToken", message.getLockToken().toString());
        putIfNotNull(consumerSpan, "enqueuedTime", message.getEnqueuedTimeUtc());
        putIfNotNull(consumerSpan, "sequenceNumber", message.getSequenceNumber());

        try {

          // Processing logic goes here 
          consumerSpan.setStatus(StatusCode.OK);

        } catch (Exception e) {
          consumerSpan.recordException(e);
          consumerSpan.setStatus(StatusCode.ERROR);
        }
        consumerSpan.end();
      }
`

**Comment by jeanbisutti** [comment]
Hi @ajaythakran,
You can get a tracer with this piece of code: `Tracer tracer = GlobalOpenTelemetry.getTracerProvider().tracerBuilder("MyTracer") ;`

**Comment by ajaythakran** [comment]
> Hi @ajaythakran, You can get a tracer with this piece of code: `Tracer tracer = GlobalOpenTelemetry.getTracerProvider().tracerBuilder("MyTracer") ;`

Hi @jeanbisutti  
Is this thread-safe statement, Can it be called multiple times in the application and it will always return same tracer?

**Comment by jeanbisutti** [comment]
@ajaythakran With this code you will get an  _io.opentelemetry.api.trace.DefaultTracer_ that seems unique (singleton) and [is marked as thread-safe in OpenTelemetry](https://github.com/open-telemetry/opentelemetry-java/blob/6de5c50b7ec934f2913e381d7d0e10d83376b1e6/api/all/src/main/java/io/opentelemetry/api/trace/DefaultTracer.java#L17). So, the answer to your question seems yes. To be sure, @trask  could you please confirm?

**Comment by trask** [comment]
> Is this thread-safe statement, Can it be called multiple times in the application and it will always return same tracer?

yes this is correct

as a side note: the Javaagent instruments GlobalOpenTelemetry and ends up returning a bridge to the `SdkTracer` that is in the agent (if you do Class.forName, you will see it as `io.opentelemetry.javaagent.instrumentation.opentelemetryapi.trace.ApplicationTracer`, but no need to worry about this detail)

**Comment by ajaythakran** [comment]
Thanks @jeanbisutti & @trask for help, closing the issue.
