### ISSUE TITLE
Duplicated Requests in Application Insights

### ISSUE THREAD

**Issue by garoplin** [microsoft/ApplicationInsights-Java#2402]
### Expected behavior
We expected that each entry of a type Requests is logged only once
### Actual behavior
We see, that each entry of a type Requests is logged twice. However, we have identical setup on all environments, but the issue occurs only on prod.
#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: Application Insights Agent 3.2.0, Java 11
 - OS type and version: Windows 
 - Application Server type and version (if applicable): Tomcat
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable):

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

### Screenshots
![Screenshot 2022-07-19 at 11 47 52](https://user-images.githubusercontent.com/79226004/179724328-5bca3c15-d852-4e5e-b20d-3d7c89d7d4ee.png)

**Comment by trask** [comment]
hi @garoplin! see https://github.com/microsoft/ApplicationInsights-Java/issues/2251#issuecomment-1115403163 and let us know if this resolves the issue for you

**Comment by garoplin** [comment]
Hi @trask, it seems that indeed that's the case. Thank you for the quick response!
