### ISSUE TITLE
Adaptive sampling not supported anymore

### ISSUE THREAD

**Issue by asos-jitu** [microsoft/ApplicationInsights-Java#2416]
**Is your feature request related to a problem? Please describe.**
We are planning to migrate to Java 3.x agent version from 2.x and are using adaptive sampling in our configurations. Since 3.x, the support for adaptive sampling has been taken off and we would need a migration path for 3.x

**Describe the solution you would like**
Java agent and SDK 3.x should support Adaptive sampling

**Describe alternatives you have considered**
NA

**Additional context**
![sampling](https://user-images.githubusercontent.com/100283756/180968264-856826f5-9210-4c41-874b-e148f63b1255.PNG)

**Comment by trask** [comment]
hi @asos-jitu! adding fixed-rate sampling in 3.x is on our short list, we'll keep you posted

**Comment by trask** [comment]
oops! yes, that's what I meant (rate-limited / adaptive sampling)
