### ISSUE TITLE
OpenTelemetry API driven Span dependency appears as InProc type in Application Insights

### ISSUE THREAD

**Issue by ajaythakran** [microsoft/ApplicationInsights-Java#2448]
### Expected behavior
When OpenTelemetry Span Builder is used to create dependency of type SpanKind.PRODUCER, it should appear as dependency and also enable a way to set telemetryType that Application Insights recognizes, such as "Azure Service Bus"

### Actual behavior
The Span appears as InProc in Application Insights.

### To Reproduce
 - Build Span using tracer.spanBuilder and set spanKind to SpanKind.PRODUCER
 - set custom attributes like type as "Azure Service Bus" 

### System information
Please provide the following information:
 - OpenTelemetry API Version: 1.10.0
 - Application Insights Agent Version: 3.2.11
 - OS type and version: Alpine Linux
 - Application Server type and version (if applicable): Undertow
 - Using spring-boot? Yes , v2.3
 - Additional relevant libraries (with version, if applicable): 

### Screenshots
- Previously with Azure Application Insights SDK, it appears as dependency of type Azure Service Bus
![AppInsightsSDK](https://user-images.githubusercontent.com/33127870/184963506-e99102f8-31e3-4d13-b216-40aae6cdcc4c.png)

- New with OpenTelemetry API with Agent, it appears as InProc 
![OpenTelemetryAPI](https://user-images.githubusercontent.com/33127870/184963479-3cd3e756-d9c2-4b80-b5f0-6dcc1dba24f0.png)

**Comment by trask** [comment]
hi @ajaythakran!

can you try setting span attribute `db.system=Microsoft.ServiceBus` on your span builder? I think that should get it to be recognized

**Comment by ajaythakran** [comment]
> hi @ajaythakran!
> 
> can you try setting span attribute `db.system=Microsoft.ServiceBus` on your span builder? I think that should get it to be recognized

We will try and let you know.

**Comment by ajaythakran** [comment]
Hi @trask This worked for us. Could you please help me find more such possible values of db.system understood by Azure Application Insights. For example what is the correct value for JMS or Kafka dependencies ?

**Comment by trask** [comment]
hi @ajaythakran, I checked, and there's nothing public. `kafka` should work. `jms` doesn't have any special icon.
