### ISSUE TITLE
Suppress collecting telemetry for health checks doesn't work

### ISSUE THREAD

**Issue by bvahdat** [microsoft/ApplicationInsights-Java#2469]
### Expected behavior
Based on the following 2 documentations:

https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-sampling-overrides#example-suppress-collecting-telemetry-for-health-checks

https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#configuration-file-path

filtering out the outgoing calls to `https://login.microsoftonline.com` as well as the incoming requests of K8S for the liveness & readiness probes based on the default Spring Boot Actuator settings doesn't work:

```
{
  "role": {
    "name": "my-app"
  },
  "preview": {
    "sampling": {
      "overrides": [
        {
          "attributes": [
            {
              "key": "http.url",
              "value": "https://login.microsoftonline.com/.*",
              "matchType": "regexp"
            },
            {
              "key": "http.url",
              "value": "https?://[^/]+/actuator/.*",
              "matchType": "regexp"
            }
          ],
          "percentage": 0
        }
      ]
    }
  }
}
```

### Actual behavior
The filtering doesn't happen and one can see all the corresponding `Dependency` and `Request` traces inside the portal.

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: `3.2.11`
 - OS type and version: Running in AKS using the `azul/zulu-openjdk-alpine:11-jre-headless` base image.
 - Application Server type and version (if applicable):
 - Using spring-boot? Yes, version `2.7.2`
 - Additional relevant libraries (with version, if applicable): Apache Camel `3.18.1`

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

The `Turn on SDK logs` link above doesn't work for me.

### Screenshots

![Screen Shot 2022-08-26 at 16 41 58](https://user-images.githubusercontent.com/3122177/186930643-1e534482-5039-4722-bb65-79288be6fc83.png)
![Screen Shot 2022-08-26 at 16 41 02](https://user-images.githubusercontent.com/3122177/186930674-e0120ed7-449d-4c14-aceb-42b3f0707bc1.png)

And the following 2 lines of code proves that the provided regular expression for filtering the K8S requests is correct:

```
public class TelemetrySuppressDoesNotWork {

    public static void main(String[] args) {
        java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("https?://[^/]+/actuator/.*");
        System.out.println(pattern.matcher("http://10.244.9.4:8081/actuator/health/liveness").matches());
    }
}
```

**Comment by trask** [comment]
hi @bvahdat! the attribute conditions are AND'd together, try splitting those two conditions out into two separate sampling overrides

**Comment by bvahdat** [comment]
Thanks @trask. Do you mean something like:

```
{
  "role": {
    "name": "bp-ihub-connector-servicebus-salesforce"
  },
  "preview": {
    "sampling": {
      "overrides": [
        {
          "attributes": [
            {
              "key": "http.url",
              "value": "https://login.microsoftonline.com/.*",
              "matchType": "regexp"
            }
          ],
          "percentage": 0
        },
        {
          "attributes": [
            {
              "key": "http.url",
              "value": "https?://[^/]+/actuator/.*",
              "matchType": "regexp"
            }
          ],
          "percentage": 0
        }
      ]
    }
  }
}
```

**Comment by bvahdat** [comment]
Thanks @trask. Do you mean something like the following?

```
{
  "role": {
    "name": "my-app"
  },
  "preview": {
    "sampling": {
      "overrides": [
        {
          "attributes": [
            {
              "key": "http.url",
              "value": "https://login.microsoftonline.com/.*",
              "matchType": "regexp"
            }
          ],
          "percentage": 0
        },
        {
          "attributes": [
            {
              "key": "http.url",
              "value": "https?://[^/]+/actuator/.*",
              "matchType": "regexp"
            }
          ],
          "percentage": 0
        }
      ]
    }
  }
}
```

**Comment by trask** [comment]
Yes 👍

**Comment by bvahdat** [comment]
>try splitting those two conditions out into two separate sampling overrides

Thanks @trask, that did the trick.

By any chance, do you maybe know where this very important detail is documented?

**Comment by trask** [comment]
@bvahdat that's great to hear. I thought this was documented at https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-sampling-overrides#how-it-works, but looks like not, so I sent a doc PR to add it, should be updated in a day or two. thx!
