### ISSUE TITLE
Exclude single custom exception from being logged in application insights v3

### ISSUE THREAD

**Issue by simplyanything** [microsoft/ApplicationInsights-Java#2475]
I am using application insights `3.1.1` in my application and am successfully able to see all sorts of logs, exceptions and metrics in application insights.
I have a custom exception, `InvalidActionException`, which is thrown inside my application based on an invalid user action. Unfortunately though, this exception is cluttering the `exceptions` logs inside application insights.

I would like to hide this exception, but am not able to figure out how. In the older (v2) library, you could use Telemetry Processor to exclude an exception. It is not as clear how to achieve this in the new version.

I have tried to create an `applicationinsights.json` file and have added this inside `main/java/resources`, but the exception log is still visible inside application insights:

```
{
	"connectionString": "InstrumentationKey=00000000-0000-0000-0000-000000000000",
	"preview": {
		"processors": [{
				"type": "attribute",
				"exclude": {
					"matchType": "regexp",
					"metricNames": [
						".*InvalidActionException.*"
					]
				}
			},
			{
				"type": "span",
				"exclude": {
					"matchType": "regexp",
					"metricNames": [
						".*InvalidActionException.*"
					]
				}
			},
			{
				"type": "log",
				"exclude": {
					"matchType": "regexp",
					"metricNames": [
						".*InvalidActionException.*"
					]
				}
			},
			{
				"type": "metric-filter",
				"exclude": {
					"matchType": "regexp",
					"metricNames": [
						".*InvalidActionException.*"
					]
				}
			}
		]
	}
}
```

**Comment by trask** [comment]
hi @simplyanything! can you share the `customDimensions` for one of these exceptions?

**Comment by simplyanything** [comment]
Hi @trask , thanks for the quick response!
The `customDimensions` property is empty.

**Comment by trask** [comment]
thx, does the `operation_parentId` point to a `request` record or to a `dependency` record? (check the `id` column in those tables)

**Comment by simplyanything** [comment]
The `operation_parentId` of the exception points to a `dependency` record.

**Comment by trask** [comment]
what kind of dependency is it? (what is its `type` column)

**Comment by simplyanything** [comment]
The dependency type is `InProc`

**Comment by trask** [comment]
oh, I see, you are using 3.1.1, check out:

https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#download-the-jar-file

> Starting from 3.2.0, controller "InProc" dependencies are not captured by default. For details on how to enable this, please see the [config options](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#autocollect-inproc-dependencies-preview).

also, if you do want to continue capturing "InProc" dependencies, the upcoming release 3.4.0-BETA will no longer capture exceptions on InProc dependencies, because we agree also they are noisy and not that helpful, from upcoming release notes:

> Exceptions are no longer captured directly on dependency records, in order to reduce ingestion
  cost and because exceptions which are logged or bubble up to the request are already captured

**Comment by simplyanything** [comment]
You rock! Many thanks for the quick help & information @trask !
