### ISSUE TITLE
Add logging properties 'method name', 'line number'

### ISSUE THREAD

**Issue by jack-berkut** [microsoft/ApplicationInsights-Java#2477]
**Is your feature request related to a problem? Please describe.**
Application Insights Agent has not sent 'method name' and 'line number'. So it is bit difficult to find which log is related to my source code.

**Describe the solution you would like**
I would like to see those properties on Azure Application Insights.

**Describe alternatives you have considered**
Is there any way to add those properties by using OpenTelemetry SDK? 
In the agent version 2.x, I am using custom Logback Appender to capture and send those properties.

**Additional context**
N/A

**Comment by trask** [comment]
This is available now in the 3.4.0 release, see doc at https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#code-properties-for-logback-preview
