### ISSUE TITLE
Enable masking option for Mongo

### ISSUE THREAD

**Issue by asos-jitu** [microsoft/ApplicationInsights-Java#2498]
**Is your feature request related to a problem? Please describe.**
I  would need following option for Mongo instrumentation type
{
  "instrumentation": {
    "jdbc": {
      "masking": {
        "enabled": false
      }
    }
  }
}

**Describe the solution you would like**
Enable masking configurations for Mongo type, similar to [2453](https://github.com/microsoft/ApplicationInsights-Java/pull/2453)

**Describe alternatives you have considered**
Describe any alternative solutions or features you've considered.

**Additional context**

**Comment by trask** [comment]
This is available now in the 3.4.0 release, see https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#mongo-query-masking
