### ISSUE TITLE
applicationinsights-core 2.6.4 cause to high build time

### ISSUE THREAD

**Issue by YairoR** [microsoft/ApplicationInsights-Java#2522]
Hi,

Once I'm adding the applicationinsights-core 2.6.4 package to my project, the build time increases from 30 seconds to 4 minutes.
When building in debug mode, I can see that the build is stuck on copying the applicationinsights-core class files:
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/7312492/190519756-8d1c786a-5335-4966-b094-f3d64f5d8831.png">

### System information
Please provide the following information:
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /opt/homebrew/Cellar/maven/3.8.5/libexec
Java version: 15.0.2, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home
Default locale: en_IL, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
Not using spring boot.

Any idea why?

Thanks!

**Comment by YairoR** [comment]
Hi, anyone can help me with that?

Adding more information - when I'm updating to the latest package (version 3.4.0) the build time issue resolves but my custom telemetry (that is coming from using the TelemetryClient) is not being sent to my AI instance.
When looking at the applicationinsights.log file, I can see the following error:

> 2022-09-20 15:14:25.966+03:00 ERROR c.m.a.a.i.l.TelemetryClientClassFileTransformer - configuration field not found in TelemetryClient

But - my slf4j logs are being tracked as usual.

Any insight?

**Comment by trask** [comment]
hi @YairoR! are you able to update to the latest 3.4.0 version of the agent as well? that should resolve the ERROR above

**Comment by YairoR** [comment]
Hi @trask, thanks for the reply!
You can see my latest reply, I've referred to version 3.4.0:

> Adding more information - when I'm updating to the latest package (version 3.4.0) the build time issue resolves but my custom telemetry (that is coming from using the TelemetryClient) is not being sent to my AI instance.
> When looking at the applicationinsights.log file, I can see the following error:
> 
> 2022-09-20 15:14:25.966+03:00 ERROR c.m.a.a.i.l.TelemetryClientClassFileTransformer - configuration field not found in TelemetryClient
> 
> But - my slf4j logs are being tracked as usual.

**Comment by trask** [comment]
it looks like you are using 3.4.0 of `applicationinsights-core`, but using an earlier version of `applicationinsights-agent`.

are you manually adding the `applicationinsights-agent` jar, or maybe using the version integrated into a platform like App Services?

**Comment by trask** [comment]
ya, but try with version 3.4.0 of the applicationinsights-agent

**Comment by YairoR** [comment]
Ok, I've just tried and it works. Thanks a lot!
BTW, maybe it should be mentioned somewhere in the release notes/here - https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#send-custom-telemetry-by-using-the-2x-sdk

**Comment by trask** [comment]
@YairoR ya, thanks for reporting this, I think we can fix in the 3.4.1 release of `applicationinsights-core` so that it still works with earlier 3.x versions of the agent, to avoid this kind of confusion

**Comment by YairoR** [comment]
@trask Sounds perfect.
