### ISSUE TITLE
License Risks with Transitive Dependency

### ISSUE THREAD

**Issue by vishaldhardubey** [microsoft/ApplicationInsights-Java#2524]
There is license related collaboration issue between us and the license applicable to transitive dependency  _**ch.qos.logback.logback-core & ch.qos.logback.logback-classic**_  which is coming from _**com.microsoft.azure.applicationinsights-logging-logback**_ .

logback-core & logback-classic utilizes :- _Eclipse Public License - v1.0_ & _GNU Lesser General Public License v2.1_ (Not acceptable)

Any suggestions to resolve the issue?

Thanks in Advance !

**Comment by trask** [comment]
hi @vishaldhardubey! what is your specific concern about these licenses?
