### ISSUE TITLE
Appinsights logging for different environments

### ISSUE THREAD

**Issue by andesk10** [microsoft/ApplicationInsights-Java#2576]
Azure app insights is working in the way shown below.

Added these two dependencies:
1. implementation("com.microsoft.azure:applicationinsights-agent:3.4.1")
2. implementation("com.microsoft.azure:applicationinsights-runtime-attach:3.4.1")

Invoked the attach() method as mentioned in docs
@SpringBootApplication
public class SpringBootApp {

  public static void main(String[] args) {
    ApplicationInsights.attach();
    SpringApplication.run(SpringBootApp.class, args);
  }
}

I have created applicationinsight.json, added my connection string and placed in src/main/resources.

However, my need is to log local and dev logs to one connection string (resource group) and prod logs to another connection string (resource group).
I have tried creating a new file applicationinsight-local.json, applicationinsight-dev.json in same path. But, that doesnt seem to work.
Dont you offer this functionality.

Thanks.

**Comment by heyams** [comment]
we don't support applicationinsights-local.json nor applicationinsights-dev.json. 
can you check out [connection string overrides](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#connection-string-overrides-preview)?

**Comment by trask** [comment]
I could see supporting custom classpath location for `applicationinsights.json`, maybe runtime attach could try resolving `APPLICATIONINSIGHTS_CONFIGURATION_FILE` against the classpath first, and then fall back to resolving it against the file system

**Comment by trask** [comment]
btw @andesk10

> implementation("com.microsoft.azure:applicationinsights-agent:3.4.1")

you shouldn't add an implementation dependency on the agent, the runtime-attach artifact bundles it internally (not as a transitive dependency)

**Comment by jeanbisutti** [comment]
> I could see supporting custom classpath location for `applicationinsights.json`, maybe runtime attach could try resolving `APPLICATIONINSIGHTS_CONFIGURATION_FILE` against the classpath first, and then fall back to resolving it against the file system

This would not work when the applicationinsight.json file (applicationinsight-local.json, applicationinsight-dev.json, ...) is included into a Spring Boot jar file. So, I would suggest providing a system property overriding the default name of the applicationinsight.json when the json file is retrieved from the classpath. This solution would fit well with Spring Boot profile configuration via system property (`-Dspring.profiles.active=dev`).
