### ISSUE TITLE
Support Standalone Java apps

### ISSUE THREAD

**Issue by jezzsantos** [microsoft/ApplicationInsights-Java#2600]
Leading on from #1870 

I am also building a plugin for a desktop app (in this case a plugin for Jetbrains IntelliJ IDE), that has to be written in (Java/Gradle) and I want to use Application Insights to send my telemetry, both CrashReports, Log files and custom Events for tracking usage.
I need to do that when online  and also when offline.

Seems like I can do all that with version 2.6.4 of `com.microsoft.azure:applicationinsights-core:2.6.4` but not with any version after `2.6.4`.

In the latest version `3.4.1` the code that was there in `core` apparently now relies on `com.microsoft.azure:applicationinsights-agent` to deliver the telemetry to azure. 
But to install the agent requires me to add it to my JVM using some tricks with `javaagent` (and other magic that I cannot get working in my case). I'm not even sure if that using a javaagent is an option for a desktop app plugin? and since I can make it work, Im not sure if this a a viable solution. 

Secondly, I see a lot of talk (around the forums) about executing this line: `ApplicationInsights.attach()` before the `main` function of your application. But in the case of a java plugin of the type I am having to write, there is no such thing as a `main` function. I tried adding that line in some code that runs in my plugin, but it made no difference - the sending of telemetry still does not work - it does not fail either.

I would like a solution that allows me to stay up to date with the latest version of these packages (like `com.microsoft.azure:applicationinsights-core`), that works for a grade plugin that is not a Spring Boot application.

**Comment by trask** [comment]
hi @jezzsantos, thanks for posting! this is a good use case for https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/monitor/azure-monitor-opentelemetry-exporter (which is shared code that the Java agent uses internally also). we don't expect many users to use the underlying exporter directly, but we are providing them because there are a few use cases (like yours) where it's just not feasible to use auto-instrumentation.

**Comment by jezzsantos** [comment]
Thanks @trask 

Can you tell me if this library manages the Java client being offline? (similar to what `ServerTelemetryChannel` does)
I am looking to manage the telemetry that cannot be delivered if the computer is not connected?

**Comment by trask** [comment]
> Can you tell me if this exporter library manages the Java client being offline? (similar to what ServerTelemetryChannel does)

yes, the standalone exporter library has the same disk persistence/retry logic that the Java agent has

**Comment by jezzsantos** [comment]
Thanks,
Any docs/examples of how to manage/define the options for that feature?

**Comment by trask** [comment]
> 1. So far I can do pretty much everything I need to do with `com.microsoft.azure:applicationinsights-core:2.6.4`. Do I need to change to the exporter?

No. We recently announced that 2.x will be retired in 2025, but there have been no service retirement announcements, so at this point we expect it to continue working even beyond that if you choose to keep using it.

> 2. Offline is a big problem. I need to be sure that telemetry is stored locally somewhere when my java app is offline and uploaded later when the app is run and its online. Is the exporter a better way than using `com.microsoft.azure:applicationinsights-core:2.6.4`?

The offline storage is likely more robust in the exporter, as any new fixes and improvements have gone into that, but 2.x does have offline storage capability as well.

**Comment by jezzsantos** [comment]
Thanks @trask 

This all sounds just all good to me  to stick on 2.X

Any coordinates/samples you can give me on how to configure 2.X for offline better than out of the box? 
(I believe it is using the `InProcessTelemetryChannel` out of the box? is it not?)

**Comment by trask** [comment]
check out https://github.com/microsoft/ApplicationInsights-Java/wiki/ApplicationInsights.XML-(2.x)#channel
