### ISSUE TITLE
Question: pass operation id to service response

### ISSUE THREAD

**Issue by karatkep** [microsoft/ApplicationInsights-Java#2633]
Dear Community,
Could you please share the easiest way to add `operation_id` to service response (as a header for example)?

Thanks in advance!

**Comment by trask** [comment]
hi @karatkep! check out https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#get-the-trace-id-or-span-id

in particular

`Span.current().getSpanContext().getTraceId()`

should give you the operation id

**Comment by karatkep** [comment]
Thank you @trask,

Just tried and got `00000000000000000000000000000000`.
According to OpenTelemetry javadoc, 
> Returns an invalid Span. An invalid Span is used when tracing is disabled, usually because there is no OpenTelemetry SDK installed.

Should I install OpenTelemetry SDK somehow?

**Comment by trask** [comment]
> Just tried and got `00000000000000000000000000000000`

Are you using the Javaagent, and did you call `Span.current().getSpanContext().getTraceId()` inside of an active request?

**Comment by karatkep** [comment]
@trask , yes, I am using Javaagent. I tired to call `Span.current().getSpanContext().getTraceId()` inside of request interceptor to add operation ID to all needed request. 

The idea is to simplify troubleshooting, so user will be able to provide operation ID for any problematic request.

**Comment by trask** [comment]
> inside of request interceptor

what kind of request intercepter?

**Comment by trask** [comment]
If you can provide a small repro that would be ideal to help me understand clearly

**Comment by karatkep** [comment]
Sorry, my bad - just realised issue with adding app insights agent. Fixed, code works as expected:

```
public class OperationIdInterceptor implements HandlerInterceptor {

    @Override
    public boolean preHandle(final HttpServletRequest request, final HttpServletResponse response, final Object handler) {
        response.setHeader("operation-id", Span.current().getSpanContext().getTraceId());
        return true;
    }

}
```

@trask thank you very much for support!
