### ISSUE TITLE
Response code < 400 is treated as a fail request

### ISSUE THREAD

**Issue by megachan** [Microsoft/ApplicationInsights-Java#264]
By default, it flags as failed any request with a response code >= 400. However, we found that it also flag response code < 400 as fail request as well. Can you please check it is a bug or something?

Kind regards,
Yui

**Comment by gupele** [comment]
Hi Yui,

This is going to be fixed in next version, which I hope will be out next week

**Comment by symm** [comment]
@gupele any update on when this will be fixed? I ran into the same issue and opened a pull request #268

Cheers

**Comment by amnonshmsft** [comment]
Gareth, Yui, 
We apologize for the delay which is caused mainly due to Israel holidays.
We'll make efforts to fix it and publish a new version this week.

**Comment by amnonshmsft** [comment]
Gareth, Yui - thank you very much for your help here.
Gareth's fix was merged to master and version 1.0.2 containing this fix was published to Maven about an hour ago.

**Comment by megachan** [comment]
Thank you so much
