### ISSUE TITLE
Lifecycle policy?

### ISSUE THREAD

**Issue by mayrstefan** [microsoft/ApplicationInsights-Java#2694]
Does this Agent have a lifecycle policy ? 
How long are 2.6.x, 3.0.x, 3.1.x, 3.2.x, 3.3.x or 3.4.x versions supported?

**Comment by trask** [comment]
Hi @mayrstefan!

We recently announced End-of-Life for the 2.x version will be September 2025.

All 3.x versions are supported, though new fixes and features are only be added to the latest version.

**Comment by mayrstefan** [comment]
Where can I find this information? Is there a lifecycle overview or just an individual announcement somewhere which I missed?

**Comment by trask** [comment]
here's the specific announcement about 2.x: https://azure.microsoft.com/id-id/updates/application-insights-java-2x-retirement/

here's the [Application Insights SDK support guidance](https://learn.microsoft.com/en-us/azure/azure-monitor/app/sdk-support-guidance)

**Comment by mayrstefan** [comment]
Thanks for the links
