### ISSUE TITLE
AgentNotificationsHandler is missing from the maven package?

### ISSUE THREAD

**Issue by erkieh** [Microsoft/ApplicationInsights-Java#270]
An error is logged upon startup:

AI: ERROR 17-09-2015 13:17, 1: Failed to register 'ApplicationInsightsWebFilter', exception: 'com/microsoft/applicationinsights/agent/internal/coresync/AgentNotificationsHandler'

It turns out the problem is actually that the file for the interface
com.microsoft.applicationinsights.agent.internal.coresync.AgentNotificationsHandler
is missing from the maven jar.

**Comment by gupele** [comment]
This means that the Agent is not present, which is ok, you can work with or without the Agent.

We will change the log level, though

**Comment by jmrossy** [comment]
Can you elaborate on that Gupele? 
What does the Agent do? And will it be added to the maven jar?

**Comment by gupele** [comment]
The Agent is for monitor dependencies, exceptions and execution times in Java web, you can read about that in this blog apps://azure.microsoft.com/en-us/documentation/articles/app-insights-java-agent/
