### ISSUE TITLE
webflux filter is added which throws an exception, the instrumentation does not currently capture the http.status_code.

### ISSUE THREAD

**Issue by Bonnie-Chen95** [microsoft/ApplicationInsights-Java#2731]
Hi Team,

I am attaching the related upstreaming issue link: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7251

And wish to use this one as a tunnel where we could receive a notification when the fix getting rolled out.

Appreciate for the future application insight release version.

**Comment by trask** [comment]
3.4.7 is now released: https://github.com/microsoft/ApplicationInsights-Java/releases

**Comment by Bonnie-Chen95** [comment]
> 3.4.7 is now released: https://github.com/microsoft/ApplicationInsights-Java/releases

Thanks trask, will notify the others.  Appreciate the help.
