### ISSUE TITLE
missing logs after upgrading to Application Insights Java 3.x SDK

### ISSUE THREAD

**Issue by r-michal-ah** [microsoft/ApplicationInsights-Java#2739]
Hello, 

I am following this 2 documents: https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-spring-boot#enabling-programmatically and https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-upgrade-from-2x. 

So that more less this is my pom:

```xml
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>applicationinsights-web</artifactId>
    <version>${microsoft.azure.version}</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>applicationinsights-runtime-attach</artifactId>
    <version>${microsoft.azure.version}</version>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-log4j2</artifactId>
</dependency>
```

I am also setting APPLICATIONINSIGHTS_ROLE_NAME and APPLICATIONINSIGHTS_CONNECTION_STRING via environment variables. I also removed the ApplicationInsightsAppender from log4j2.yaml. 

In the logs I can see agent has successfully started: Application Insights Java Agent 3.4.4 started successfully.

Metrics are there, unfortunately my logs are gone (logs which I am logging in my application). Application Insights -> Logs section has only logs from AgentLogExporter.

What am I missing? Could someone support me?

**Comment by trask** [comment]
hi @r-michal-ah!

> Application Insights -> Logs section has only logs from AgentLogExporter.

I didn't follow this comment, can you explain it a bit more?

a couple of other questions:

* can you see the logs in your application log (or console)?
* are any logs at all getting collected by Application Insights Java agent?
* can you check this article to see if it can explain any of what you are seeing?
https://learn.microsoft.com/en-us/troubleshoot/azure/azure-monitor/app-insights/java-standalone-troubleshoot#some-logging-is-not-auto-collected

**Comment by r-michal-ah** [comment]
hello @trask, let me answer your questions: 

> can you see the logs in your application log (or console)?

yes in the console, all logs are present, no problem here.

> are any logs at all getting collected by Application Insights Java agent?

yes, some logs are present, for instance I can see following Spring Boot log in the console and AI:
```
2022-11-29 18:18:58.313Z DEBUG c.m.a.a.i.exporter.AgentLogExporter - exporting log: SdkLogRecordData{body=StringBody{asString=Running with Spring Boot ... }}
```
but this
```kotlin
logger.info { "i am trying to log something" }
```
is only printed in the console, nothing in AI.

> can you check this article to see if it can explain any of what you are seeing

yes I already went through this document. Just for the sake of testing I set following environment properties:

```yaml
LOGGING_LEVEL_ROOT: debug
APPLICATIONINSIGHTS_SELF_DIAGNOSTICS_LEVEL: debug
APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: debug
```
and in log4j2.yaml
```yaml
Loggers:
  Root:
    level: debug
    AppenderRef:
      - ref: Console_Appender
```
but still some logs are missing in AI.

**Comment by r-michal-ah** [comment]
> > Application Insights -> Logs section has only logs from AgentLogExporter.
> 
> I didn't follow this comment, can you explain it a bit more?

By that I meant: if I see in the console this `AgentLogExporter - exporting log` I also see it in AI.

**Comment by trask** [comment]
> but this
> ```kotlin
> logger.info { "i am trying to log something" }
> ```
> is only printed in the console, nothing in AI.

can you put together a small standalone repro that we can use to troubleshoot this?

**Comment by r-michal-ah** [comment]
@trask I think I found the rootcause. We are using https://github.com/MicroUtils/kotlin-logging for logging. And it seems those logs are not exported to AI. By any chance can you think of any reason why it is not working? for Application Insights Java 2.x SDK it was working fine.

**Comment by r-michal-ah** [comment]
oh sorry logs are still missing, i think console and AI should be 1 to 1, but its not.

**Comment by trask** [comment]
hi @r-michal-ah, can you put together a small standalone repro that we can use to troubleshoot this?

**Comment by sneaker102** [comment]
Hello guys,
It seems like I encounter the same problem now.
We have an azure java function app that was using the appinsights-core dependency 2.x and now we had to upgrade to 3.x.
I upgraded it and use the connection string instead of instrumentation key and had to setup also the java-agent.
Here I tried first with custom maven execution goal:
`
  <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <id>copy-ai-agent</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>com.microsoft.azure</groupId>
                                    <artifactId>applicationinsights-agent</artifactId>
                                    <version>3.4.14</version>
                                    <outputDirectory>${project.build.directory}</outputDirectory>
                                    <destFileName>applicationinsights-agent.jar</destFileName>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
`
and with env var "JAVA_OPTS" = "-javaagent:/home/site/wwwroot/applicationinsights-agent.jar" but the logs still do not appear into the appinsights-logs customEvents table or in my AppEvents table in the logs analytics workspace, but still appears for the table FunctionAppLogs in the logs analytics workspace.
So I tried again with:
`
<dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>applicationinsights-runtime-attach</artifactId>
            <version>${azure.applicationinsights.runtime.attach.version}</version>
        </dependency>
` 
and attaching it on a static block on my function class like this: 
`
public class StartPipelineFunctionTimer implements AzFunHandlerTimeTrigger {
    static {
        ApplicationInsights.attach();
    }
}
`

At this point I can not think on any alternative that I could try...
Maybe you can give a fresh viewpoint into it.

Thx
