### ISSUE TITLE
testSDKInfoFileIsWrittenWithInstrumentationKey fails on Fedora Linux 22

### ISSUE THREAD

**Issue by olivierdagenais** [Microsoft/ApplicationInsights-Java#278]
I ran `gradlew test` on my Fedora 22 VM and one of the tests in `core` failed:

Class: com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializerTests
Method: testSDKInfoFileIsWrittenWithInstrumentationKey

```
Argument(s) are different! Wanted:
fileFactory.create(
    "/usr/appinsights/docker/sdk.info",
    "InstrumentationKey=A-test-instrumentation-key"
);
-> at com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializerTests.testSDKInfoFileIsWrittenWithInstrumentationKey(DockerContextInitializerTests.java:133)
Actual invocation has different arguments:
fileFactory.create(
    "/usr/appinsights/docker/sdk.info",
    "InstrumentationKey=c9341531-05ac-4d8c-972e-36e97601d5ff"
);
```

A quick spelunking in the code suggests that the test might be sensitive to ordering since it [indirectly] accesses the `TelemetryConfiguration` singleton and its configuration wasn't loaded from the `ApplicationInsights.xml` test resource.

**Comment by Yonisha** [comment]
Hi Olivier,

Thanks for your feedback and suggestion.
We'll address this issue shortly.

**Comment by beckylino** [comment]
@olivierdagenais are you still experiencing any issues with this test?

**Comment by olivierdagenais** [comment]
@beckylino I haven't used this project in over a year.  I had encountered this test failure when I was testing a fix for another issue and figured the maintainers might be interested to know some of the tests were unreliable.  I don't currently have a Fedora Linux VM to test with, sorry.
