### ISSUE TITLE
CPU metrics uses VM CPU instead of container CPU

### ISSUE THREAD

**Issue by felipmiguel** [microsoft/ApplicationInsights-Java#2786]
### Expected behavior
For Azure Spring Apps, CPU metrics in Application Insights Live Metrics should show the PodCpuUsage. When the application is at its max CPU capacity it should appear 100%.
It is expected to show the same than process.cpu.usage.

### Actual behavior
Application Insights Metrics show CPU utilization as number of vCPU assigned to Azure Spring Apps application divided by the number of cores of the real VM. 
For instance, if app has 4vCPU and the VM has 16 cores it shows as 1/4 of the application CPU. So if the application is running at its max capacity it shows 25% instead of 100%.
![image](https://user-images.githubusercontent.com/52053185/206739277-556c9019-b91d-449b-bb83-9c32fd46809c.png)
If the app has 1vCPU it shows 1/16 ratio, instead of 100% it shows 6,25%.
However at the same time process.cpu.usage has a value of 1.
![image](https://user-images.githubusercontent.com/52053185/206739899-409d9511-1c6f-4650-be71-f6e911be6dcf.png)

### To Reproduce
Perform an stress test over an Azure Spring Apps.

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: Managed by Azure Spring Apps
 - OS type and version: Managed by Azure Spring Apps
 - Application Server type and version (if applicable): Azure Spring Apps Enterprise
 - Using spring-boot: yes
 - Additional relevant libraries (with version, if applicable):

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

**Comment by trask** [comment]
@felipmiguel from your Teams message it sounds like this was due `-XX:ActiveProcessorCount=16`?

**Comment by felipmiguel** [comment]
Agree, I think it is related to Spring Apps settings
