### ISSUE TITLE
Application Map does not display externals services with agent 3.4.4

### ISSUE THREAD

**Issue by ezYakaEagle442** [microsoft/ApplicationInsights-Java#2790]
### Expected behavior
I have an App that calls an externa service whatismyip.akamai.com which should be then displayed on the AppMap.
This did work as expected with a another version of the agent,  I can not remember which one.

### Actual behavior
whatismyip.akamai.com is not displayed on the Map.

### To Reproduce
[https://github.com/ezYakaEagle442/azure-spring-apps-petclinic-mic-srv](https://github.com/ezYakaEagle442/azure-spring-apps-petclinic-mic-srv)

#### Sample Application
If applicable, provide a sample application which reproduces the issue:
[https://github.com/ezYakaEagle442/azure-spring-apps-petclinic-mic-srv](https://github.com/ezYakaEagle442/azure-spring-apps-petclinic-mic-srv)

[https://github.com/ezYakaEagle442/azure-spring-apps-petclinic-mic-srv/blob/azure/spring-petclinic-vets-service/src/main/java/org/springframework/samples/petclinic/vets/VetsServiceApplication.java#L61](https://github.com/ezYakaEagle442/azure-spring-apps-petclinic-mic-srv/blob/azure/spring-petclinic-vets-service/src/main/java/org/springframework/samples/petclinic/vets/VetsServiceApplication.java#L61)

```sh
URL url_name = new URL("http://whatismyip.akamai.com");
BufferedReader sc = new BufferedReader(new InputStreamReader(url_name.openStream()));
systemipaddress = sc.readLine().trim();
```

### System information
Please provide the following information:
 - SDK Version: Java 11 
 - OS type and version: ASA/AKS default OS
 - Application Server type and version (if applicable): N/A
 - Using spring-boot? **YES**
 - Additional relevant libraries (with version, if applicable):

See POM at [https://github.com/ezYakaEagle442/azure-spring-apps-petclinic-mic-srv/blob/azure/pom.xml#L37](https://github.com/ezYakaEagle442/azure-spring-apps-petclinic-mic-srv/blob/azure/pom.xml#L37)

```sh
    <properties>
        <java.version>11</java.version>
        <maven.compiler.release>11</maven.compiler.release>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <assertj.version>3.17.1</assertj.version>
        <lombok.version>1.18.22</lombok.version>

        <!-- https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping#which-version-of-spring-cloud-azure-should-i-use -->
        <spring-cloud-azure.version>4.4.0</spring-cloud-azure.version>
        <spring-boot.version>2.6.13</spring-boot.version> <!-- /!\ Bug in Netty with Spring Boot 2.6.6, see https://github.com/netty/netty/issues/12343 -->
        <spring-cloud.version>2021.0.4</spring-cloud.version>
```

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

### Screenshots
![ASA_AppInsight_AppMap](https://user-images.githubusercontent.com/43554247/207004157-672b9e04-9226-4f22-b940-80762a9c332e.jpg)

@trask

**Comment by trask** [comment]
hi @ezYakaEagle442, I wasn't able to reproduce this, can you take a look at my small repro and see what I might be doing differently than you are?

https://github.com/trask/url-open-stream-repro

and this is the app map picture I get:

<img src="https://user-images.githubusercontent.com/218610/207147638-22247c3f-7daf-4b4b-926f-c56f1d2cac89.png" width="50%">
