### ISSUE TITLE
ThreadContext.getRequestTelemetryContext().getRequestTelemetry().setDuration() is not supported by the Application Insights for Java 3.x agent

### ISSUE THREAD

**Issue by rangarnow** [microsoft/ApplicationInsights-Java#2808]
### Expected behavior
`ThreadContext.getRequestTelemetryContext().getRequestTelemetry().setDuration()` method is invoked without errors resulting changed duration of request.

This is needed, because we are receiving message which is then processed asynchronously. Then we have subscribe on `Mono` result, so in fact I would like to see real time of processing (including subscribe invocation), that's why the need to modify duration of the request programatically.

There is an example code showing my problem and workaround I try to have with `ThreadContext.getRequestTelemetryContext().getRequestTelemetry().setDuration()`:

```java
public void processMessage() {
   long startTime = System.currentTimeMillis();
   RequestTelemetryContext telemetryContext = ThreadContext.getRequestTelemetryContext();
   RequestTelemetry requestTelemetry = telemetryContext.getHttpRequestTelemetry();

   someAsyncTask().subscribe(data -> {
      long endTime = System.currentTimeMillis();
      requestTelemetry.setDuration(new Duration(endTime - startTime)); // Warning is thrown, has no effect

      // This works, but I would like to have parent request with real time, not a dependency
      RemoteDependencyTelemetry telemetry = new RemoteDependencyTelemetry();
      telemetry.setId(requestTelemetry.getId());
      telemetry.setName("Processing time 2");
      telemetry.setDuration(new Duration(endTime - startTime));
   });     
}
```

Effect:
![image](https://user-images.githubusercontent.com/92714803/209086476-08e38faf-7c5b-4e76-ad45-dab5dcef3510.png)

If you have any other idea how to make ServiceBus.process (other than via setting Duration) to take the same time as "Processing time 2" it would be welcome.

I tried also with open telemetry API (given https://github.com/microsoft/ApplicationInsights-Java/issues/1442#issuecomment-763250512), but still no luck:
```java
Span currentSpan = Span.current();
SpanContext spanContext =
                SpanContext.createFromRemoteParent(
                        currentSpan.getSpanContext().getTraceId(), currentSpan.getSpanContext().getSpanId(), TraceFlags.getDefault(), TraceState.getDefault());
try (Scope scope = Context.root().with(Span.wrap(spanContext)).makeCurrent()) {
   Span.current().end();
}
```

### Actual behavior
An error occur when trying to execute this method. This also occur for other methods, like `setResponseCode()` etc.:
`ThreadContext.getRequestTelemetryContext().getRequestTelemetry().setDuration() is not supported by the Application Insights for Java 3.x agent (this message will only be logged once)`

### To Reproduce
- use Java program with latest application insights jar 3.4.7,
- import these dependencies to pom.xml:

```xml
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>applicationinsights-core</artifactId>
            <version>3.4.7</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>applicationinsights-web</artifactId>
            <version>3.4.7</version>
        </dependency>
```

**Comment by trask** [comment]
hi @rangarnow!

can you post a small repro of your issue (including the service bus sdk)? I'd like to look at it to see how best to solve this issue.

even if you could call "setDuration", the request would have already been ended/exported, and so it would have no real effect.

**Comment by rangarnow** [comment]
hi @trask, thank you for your response. I was on holidays so that's why no feedback from my side :) I will prepare today an example code to highlight my problem.

**Comment by rangarnow** [comment]
Service bus implementation details:

I am using **Service Bus Processor** as below:

```java
ServiceBusProcessorClient processorClient = new ServiceBusClientBuilder()
                .connectionString(...)
                .processor()
                .queueName(...)
                .processMessage(this::processMessage)
                .processError(this::processError)
                .receiveMode(ServiceBusReceiveMode.PEEK_LOCK)
                .maxConcurrentCalls(...)
                .disableAutoComplete()
                .maxAutoLockRenewDuration(...)
                .buildProcessorClient();

        processorClient.start();
```

**Process message function (returns void):**

```java
this.executeAsyncTask(message)
                .publishOn(Schedulers.boundedElastic()) // because context.compelete is synchronous
                .subscribe(data -> {
                        context.complete();
                });
```

Time elapsed doesn't take into account `context.complete()` invocation, but instead it ends without waiting for async result to arrive resulting with different time than real `context.complete()` execution.

I've also checked **pure Service bus async client** and it's working fine (time calculated in Application Insights is correct, despite context.complete doesn't end really Service Bus message, idk why yet, but I've just check this way to see how Application Insights behave in that case), **but I would like to use processor, since it gives out of the box async wrapper utilities** already where we can limit max concurrent calls etc.

**Process message function returns Mono\<T\> in that case**
```java
        ServiceBusReceiverAsyncClient receiver = new ServiceBusClientBuilder()
                .connectionString(...)
                .receiver()
                .queueName(...)
                .disableAutoComplete()
                .maxAutoLockRenewDuration(...)
                .buildAsyncClient();

        Disposable subscription = receiver.receiveMessages()
                .flatMap(message -> this.processMessage(message)
                        .map(data -> receiver.complete(message))
                )
                .subscribe(
                        (arg) -> System.out.println("Message processed.")
                );

        try {
            countdownLatch.await(100000, TimeUnit.DAYS);
        } catch (InterruptedException e) {
            e.printStackTrace();
        } finally {
            // Disposing of the subscription will cancel the receive() operation.
            subscription.dispose();

            // Close the receiver.
            receiver.close();
        }
```

**Is there any way to make processor behave just like pure async client?**

**Comment by rangarnow** [comment]
I think you are right that at the point I would like to call `setDuration`, request has been already ended so it has no real effect. I just don't know how to let it wait for async result and if that's even possible.

**Comment by trask** [comment]
@rangarnow can you post the full (runnable) example to a github repository? thx!

**Comment by rangarnow** [comment]
hi @trask, basically there are ready to use MS examples on the Azure SDK for Java Github:
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusProcessorPeekLockReceiveSample.java

The only difference is processMessage function, where `context.complete` is being called from async task subscribe, instead of synchronized task. There is not really something more I could post for this issue, it's just async task completion which I would like to be take into account by app insights tracking instead of calculating time prematurely.

So process function in my case (compared to example implementation) can look like the following:

```java
private static void processMessage(ServiceBusReceivedMessageContext context) {
        executeLongAsyncTask()
                .publishOn(Schedulers.boundedElastic()) // It's for context.complete() which is blocking and cannot be invoked in http thread
                .subscribe(data -> {
                    context.complete();
                });
    }
    
    private static Mono<Void> executeLongAsyncTask() {
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        
        return Mono.empty();
    }
```

**Comment by rangarnow** [comment]
hi @trask, we switched to `ServiceBusProcessorClient` with synchronized flow, but the problem persists. `ServiceBus.process` request span (checked via `Span.current()`) is already ended when I try to do any changes in the begininng of a process function when receiving message. In fact, I cannot do anything except changing name or adding custom properties.

Due this fact we cannot for example:
- see real processing time, as duration of `ServiceBus.process` is just few millis, instead of whole time processing (synchronized),
- status of the Request is already determined as OK in StatusCode, while I could abandon, deadletter or complete message at the end (with `disableAutoComplete`).

Honestly, I start thinking that it's normal, because previouslly we had async processing, but here with sync is the same (current span completely ignores process message function). I saw similar issue in this Pull image:
https://github.com/Azure/azure-sdk-for-java/pull/30508
https://user-images.githubusercontent.com/2347409/185205252-f4f92bf5-6a7a-480a-9ed5-662bf92d5ed2.png

It seems, that the only thing we can do, is to create separate request which we will track separately (resulting 2 requests for each request) - we've checked and that works well. We cannot really modify `ServiceBus.process` since it's already ended before executing single line of code in Processing message function.

I didn't want to depend on project specifics, as there always may be something causing this behaviour, so I just grab this example code:
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ServiceBusProcessorPeekLockReceiveSample.java

I've added in the beginning of `processMessage` function to check if time is well calculated:
```
try {
   Thread.sleep(xxx);
} catch (InterruptedException e) {
   e.printStackTrace();
}
```

Results:
![image](https://user-images.githubusercontent.com/92714803/215986139-45fb21b9-7a78-4076-8d96-46c54fb198fa.png)

I would expect that ServiceBus.process will durate around 2 sec.

**Comment by trask** [comment]
hey @rangarnow, I wasn't able to repro the short `ServiceBus.process` timing.

I posted my repro here: https://github.com/microsoft/ApplicationInsights-Java-Repros/tree/main/issue-2808

can you take a look and see what you might be doing different so I can update the repro accordingly?

**Comment by rangarnow** [comment]
hi @trask, thanks for letting me know. I will check out your repo and sample code on my side.

**Comment by rangarnow** [comment]
hi @trask, I made a review of your code to check for differences. 
I've found that the config `.maxConcurrentCalls` setting for the service bus processor is the root source of incorrect tracing.

Without `maxConcurrentCalls` setting (your current code) -> OK:
![image](https://github.com/microsoft/ApplicationInsights-Java/assets/92714803/97e89218-8e38-41db-92ee-d4cc81b1a4f7)

Added setting `.maxConcurrentCalls(2)` to your code -> Not OK (not anymore 2 seconds of ServiceBus.process):
![image](https://github.com/microsoft/ApplicationInsights-Java/assets/92714803/4e5a2ec7-1feb-47ff-9b2d-867fa9626811)
![image](https://github.com/microsoft/ApplicationInsights-Java/assets/92714803/4295904b-855e-4dcf-bebd-6504e85e43e4)

**Comment by trask** [comment]
@rangarnow this is super helpful, thanks! I've updated the repro and opened an issue in the Azure SDK repository at https://github.com/Azure/azure-sdk-for-java/issues/35916

**Comment by rangarnow** [comment]
hi @trask, do you know when we could expect to see the new agent version and be able to test it?

**Comment by trask** [comment]
Hi @rangarnow, it looks like the fix made it into [azure-messaging-servicebus_7.14.3](https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-messaging-servicebus_7.14.3)

**Comment by trask** [comment]
I don't think you will need a new Java agent version for this, but looking forward to your testing it and letting us know how it goes, thx

**Comment by rangarnow** [comment]
thanks @trask will test and let you know whenever we can close this issue.

**Comment by rangarnow** [comment]
@trask to be honest, now the time is calculated well, but we have many requests under one Operation ID which is worse than before and in fact we will stay with an old release :/

![image](https://github.com/microsoft/ApplicationInsights-Java/assets/92714803/bf5b4196-1347-417f-b0e1-7b2620c653c2)

**Comment by rangarnow** [comment]
hi @trask, unfortunately I do not have free service bus instance that I can connect to in my tests, however I see that this is a well known issue as per sb ticket:
https://github.com/Azure/azure-sdk-for-java/issues/35916

**Comment by trask** [comment]
hi @rangarnow, 7.14.4 should have the fix: https://repo1.maven.org/maven2/com/azure/azure-messaging-servicebus/7.14.4/

**Comment by rangarnow** [comment]
hi @trask, finally after almost one year, we have a working Service Bus tracing without any hacks with a separate request :) thanks, it's working now!

**Comment by trask** [comment]
thanks for working through this with us!! 🚀
