### ISSUE TITLE
Method setStatus(int sc, String sm) in ApplicationInsightsHttpResponseWrapper must be override

### ISSUE THREAD

**Issue by mkosiorek** [Microsoft/ApplicationInsights-Java#282]
In ApplicationInsightsHttpResponseWrapper status code is not properly mapped when method setStatus(int sc, String sm) is used.
Jersey library (org.glassfish.jersey.containers:jersey-container-servlet-core:2.22.1) is using deprecated method setStatus in class org.glassfish.jersey.servlet.internal.ResponseWriter
```
        final String reasonPhrase = responseContext.getStatusInfo().getReasonPhrase();
        if (reasonPhrase != null) {
            response.setStatus(responseContext.getStatus(), reasonPhrase);
        } else {
            response.setStatus(responseContext.getStatus());
        }
```
Please update code and override missing method:

```
    @Override
    public void setStatus(int sc, String sm) {
        super.setStatus(sc, sm);

        this.httpStatusCode = sc;
    }
```

**Comment by OriYosefiMSFT** [comment]
Thank you for reporting and thank you @knapsu for contributing a fix!
