### ISSUE TITLE
It is observed that some request report success false but response code say 200.

### ISSUE THREAD

**Issue by Sachin1O1** [microsoft/ApplicationInsights-Java#2827]
### Expected behavior
The response code should not be 200 if success is false or vice versa. 

### Actual behavior
some request report success as false but the response code say 200.

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: 3.4.2
 - OS type and version: Linus
 - Application Server type and version (if applicable):
 - Using spring-boot? yes
 - Additional relevant libraries (with version, if applicable):

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

### Screenshots
<img width="308" alt="image" src="https://user-images.githubusercontent.com/59076596/211001902-42243a76-b280-4936-89e1-7cd6846cf8c6.png">

**Comment by trask** [comment]
hi @Sachin1O1! can you check your exceptions table to see if there are any which parent that request? that _could_ explain the behavior, though I'm looking into whether that's expected or not...

**Comment by trask** [comment]
one possibility is that the status code could have been committed (sent to the client) and then an error occurred while writing the response body. if you can narrow down, or capture Application Insights Java agent debug logs when it happens, that would help

**Comment by Sachin1O1** [comment]
Sorry, I was unable to respond here because I was on holiday. I need to see when I can take this, but I will try to get some insight here ASAP.
