### ISSUE TITLE
No traces after upgrading from 2.6 to 3.4

### ISSUE THREAD

**Issue by stmax82** [microsoft/ApplicationInsights-Java#2834]
Is it possible to use 3.4.7 without appending -javaagent:applicationinsights-agent-3.4.7.jar?

We're using com.microsoft.applicationinsights-core in a library so we cannot append -javaagent.

In 2.6.x the following worked:

```java
var config = TelemetryConfiguration.createDefault();
config.setConnectionString(cnnstr);
var telemetryClient = new TelemetryClient(config);
telemetryClient.trackTrace("hello from 2.6.4");
telemetryClient.flush();
```

After upgrading to 3.4.x I cannot get App Insights to send any data unless I append -javaagent:

```java
var telemetryClient = new TelemetryClient();
telemetryClient.getContext().setConnectionString("...");
telemetryClient.trackTrace("hello from 3.4.7");
telemetryClient.flush();
```

I also tried passing the connection string through an environment variable and through the applicationinsights.json config file to no avail.

Are we stuck on 2.6 or am I doing something wrong?

**Comment by trask** [comment]
hi @stmax82! is your library reporting data to the library user's Application Insights resource, or to your own (library author's) Application Insights resource? if it's to your own Application Insights resource, you'll probably need to use https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/monitor/azure-monitor-opentelemetry-exporter

**Comment by stmax82** [comment]
Hi @trask, it is reporting data to our own (library author's) App Insights resource.

I'm not sure I understand - we successfully used com.microsoft.applicationinsights-core up to version 2.6.
Do you mean we cannot upgrade to 3.x and have to use another package?

**Comment by trask** [comment]
Application Insights Java 3.x is built on top of OpenTelemetry and https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/monitor/azure-monitor-opentelemetry-exporter are the underlying OpenTelemetry exporters which are used inside of Application Insights Java 3.x.
