### ISSUE TITLE
QUESTION: Proxy usage

### ISSUE THREAD

**Issue by xsmrcek** [microsoft/ApplicationInsights-Java#2839]
Hello,
I am deploying service using application insighs into server with FW.
I wanted to use proxy whoch will allow me communicatoin to internet via env variable:
APPLICATIONINSIGHTS_PROXY_HOST:  some-proxy.my.cluster
 APPLICATIONINSIGHTS_PROXY_PORT:  3128
It seem's it is not working correctly.

I am using agent version 3.4.1
Can you please point me to right configuration? Using applicationinsight.json is not possible for now (my set up).
Thank you!

**Comment by heyams** [comment]
Hi @xsmrcek, 

Thanks for reaching out. 
Please consider using [global https.proxyHost and https.proxyPort system properties](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#http-proxy:~:text=Application%20Insights%20Java%203.x%20also%20respects%20the%20global%20https.proxyHost%20and%20https.proxyPort%20system%20properties%20if%20they%27re%20set%2C%20and%20http.nonProxyHosts%2C%20if%20needed.) along with the `-javaagent` command by adding these two arguments:
`-Dhttps.proxyHost=some-proxy.my.cluster -Dhttps.proxyPort=3128`

Please let us know if that works.

**Comment by trask** [comment]
you can also use `APPLICATIONINSIGHTS_PROXY=https://myproxy:8888` (looks like this env var is missing from our documentation, we'll fix that)

**Comment by xsmrcek** [comment]
Hello guys,
APPLICATIONINSIGHTS_PROXY=https://myproxy:8888
worked for me!
Thank you and sorry for late reply.
