### ISSUE TITLE
Cannot Export OpenTelemetry Spans to OTEL Collector When Using App Insights Agent

### ISSUE THREAD

**Issue by azizabah** [microsoft/ApplicationInsights-Java#2871]
### Expected behavior
Given that the App Insights Agent is a distribution of https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/ (from my understanding), I would expect to be able to attach a separate OTEL exporter such as https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel and export to a different target besides App Insights (in addition to having data flowing to App Insights). 

### Actual behavior
When I pass the App Insights Agent as a javaagent command line arg, data flows to App Insights but no data flows to my OTEL collector (local Jaeger in this case). 

When I pass the opentelemetry java agent, data flows to my OTEL collector but I am not sure how to also integrate that into App Insights. 

When I pass both the App Insights and OTEL agents as two javaagent command line args then whichever is first wins. 

When I pass the OTEL agent as a javaagent arg and try to do a programmatic attach of the App Insights agent I get this log message (WARNING: Application Insights is already attached. It is not attached a second time.) and the same behavior as if there was no App Insights Agent

### To Reproduce
Pass the App Insights Agent to a project configured to do OTEL export using the open telemetry agent and see that they do not play nice together. 

I'm not sure if there's some configuration or other process I've missed in testing this but I'm not sure what other options I have currently.

**Comment by trask** [comment]
hi @azizabah, what is the issue you are running into with only using OpenTelemetry Java agent for this scenario?

**Comment by azizabah** [comment]
> hi @azizabah, what is the issue you are running into with only using OpenTelemetry Java agent for this scenario?

How do I get info into App Insights at the same time? The goal is to have data flowing to an OTEL collector we're running internally and also Azure App Insights so we don't lose our current monitoring capabilities.

**Comment by azizabah** [comment]
@trask - Instead of using the app insights agent, would it make more sense to instead use the Azure Monitor exporter side by side with our otlp exporter on our otel-agent's? https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/azuremonitorexporter

**Comment by azizabah** [comment]
@trask - Got this working using the approach articulated of instrumenting code with OTEL's java agent and then using the newly release 0.71.0 otel collector to send traces and metrics to Azure monitor.
