### ISSUE TITLE
How come there is no Windows 11 device OS listed in Azure application insights?

### ISSUE THREAD

**Issue by Sachin1O1** [microsoft/ApplicationInsights-Java#2882]
### Expected behavior
client_OS in the Request table should contain Windows 11

### Actual behavior
client_OS in the Request table does not contain  Windows 11

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: 3.4.7
 - OS type and version:
 - Application Server type and version (if applicable):
 - Using spring-boot? yes
 - Additional relevant libraries (with version, if applicable):

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

### Screenshots
<img width="269" alt="image" src="https://user-images.githubusercontent.com/59076596/215466255-901d52eb-d986-4702-9ac9-4b5c0aa99895.png">

**Comment by Sachin1O1** [comment]
Hi @jeanbisutti , Thanks for the update. Still, do we have any way to fix this?

**Comment by trask** [comment]
hey @Sachin1O1, we don't have any way to do this automatically at this point. If Windows 11 detection is important, you could try to do that manually and add a custom dimension to the request telemetry using something like `Span.current().setAttribute("windows11", true)`.
