### ISSUE TITLE
Use JRE to run applicationinsights-runtime-attach 

### ISSUE THREAD

**Issue by Hu-Eb** [microsoft/ApplicationInsights-Java#2883]
**Is your feature request related to a problem? Please describe.**
We encounter an issue with docker images with JRE to run our microservices. We have a Spring application with **applicationinsights-runtime-attach** to gather telemetry into app insights. There is an error to start which indicates this maven packages is not compatible with JRE

**Describe the solution you would like**
Use JRE to have a smaller and more secure docker images

**Describe alternatives you have considered**

**Additional context**

**Comment by jeanbisutti** [comment]
If you see the _Runtime attachment has failed. Are you using a JRE (not a JDK)?_ message, it means that a required JDK library is missing to do the runtime attachment. You can attach Application Insights with [-javaagent](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-spring-boot#enabling-with-jvm-argument) if you want to use a JRE.

**Comment by Hu-Eb** [comment]
Thanks for the response.

1. Are you ware is there a plan to move to JRE for attachment from code ?  Wondering why wee need to use JDK .
2. Seems data coming from agent is a bit different and less accurate comparing to attaching from code.

**Comment by jeanbisutti** [comment]
> 1. Are you ware is there a plan to move to JRE for attachment from code ?  Wondering why wee need to use JDK .

The reasons are the same as those described in [this Byte Buddy issue](https://github.com/raphw/byte-buddy/issues/374). We don't plan today to make it work with JRE (complexity and maintenance for different JRE, tools.jar is very big, ...)

> 2. Seems data coming from agent is a bit different and less accurate comparing to attaching from code.

`-javaagent:applicationinsights-agent-3.4.8.jar` and `ApplicationInsights.attach()` both inject the Application Insights Java agent, only the injection mechanism differs.

**Comment by Hu-Eb** [comment]
Fair enough. 
We switched back to agent. Seems telemetry pretty much the same. Maybe we used an older version in agent in the past. 

Thanks for the help.
