### ISSUE TITLE
Unable to see MDC properties in App Insights via Function App

### ISSUE THREAD

**Issue by mikeliucc** [microsoft/ApplicationInsights-Java#2904]
### Expected behavior
Based on the various docs on Microsoft Learn, I'm under the understanding that MDC properties can be captured under `customDimensions` in the `traces` table. However, so far I am only able to capture log messages (in `message` field). Can't find the MDC properties anywhere... Please help!

### Actual behavior
No MDC properties are captured (AFAIK)

### To Reproduce
We are using Java 8 to create our Function Apps. Here's our stack:
- Java 8 (no spring or springboot)
- SLF4J/Logback
- Cognitive Search SDK
- Cosmos SDK

#### Sample Application
In our function app, the code looks something like this:

Logger logger = LogFactory.getLogger(getClass());
...
MDC.put("search.result", ...);
MDC.put("client.group", ...);
...
loggger.info("Client requesting product search {} with {} ...", searchParam, clientContext);

### System information
Please provide the following information:
 - SDK Version: azure-core 1.35.0, azure-functions-java-library 3.0.0
 - I've followed the instructions in
   - https://learn.microsoft.com/en-us/azure/azure-monitor/app/azure-web-apps-java
   - https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent
Log messages are captured as expected, but not the MDC properties.

Hoping for any suggestions you might have... Thanks in advance!

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

**Comment by mikeliucc** [comment]
Tagging @trask ... hoping you can provide some insights here (puns intended). Thanks!

**Comment by trask** [comment]
hi @mikeliucc! what does the `sdkVersion` column report on those `trace` records?

**Comment by trask** [comment]
we just released a new [Public Preview of Application Insights Java agent integration into Azure Functions](https://learn.microsoft.com/en-us/azure/azure-monitor/app/monitor-functions#distributed-tracing-for-java-applications-public-preview), can you try this (instead of attaching the Java agent yourself)?

I tested MDC yesterday using this route and it worked for me: https://github.com/trask/azure-functions-logback-mdc-example

**Comment by mikeliucc** [comment]
Hot cakes - That worked beautifully!!

![image](https://user-images.githubusercontent.com/8107782/217981781-19821aff-06cf-478e-9cb3-6d42c8a0c83e.png)

Thank you so much!
