### ISSUE TITLE
Error pulling service profiler settings after upgrading to Application Insight Java Agent 3.4.9

### ISSUE THREAD

**Issue by arvicloveria** [microsoft/ApplicationInsights-Java#2927]
### Expected behavior
There should be no error related to pulling service profiler settings which was caused by javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### Actual behavior
Logs shows that Application Insights Java Agent 3.4.9 started successfully but it is also having an error pulling service profiler settings.

### To Reproduce
1. add the applicationinsights-runtime-attach version 3.4.9 maven dependency in spring boot application's pom.xml
2. invoke the attach() method of com.microsoft.applicationinsights.attach.ApplicationInsights
3. run the spring boot application in Azure Kubernetes cluster

### System information
Please provide the following information:
 - SDK Version: 3.4.9
 - OS type and version:
 - Application Server type and version (if applicable): Azure Kubernetes 1.24.6
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable): applicationinsights-runtime-attach 3.4.9

### Screenshots
![image](https://user-images.githubusercontent.com/32754972/220513846-2d399b1e-edb1-4856-847e-46d9b86d58b6.png)

**Comment by jeanbisutti** [comment]
@arvicloveria Can you please [enable the self-diagnostics feature](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#self-diagnostics) at the TRACE level and send the logs from the beginning at jeanbisutti@microsoft.com?

**Comment by teplyuska** [comment]
I am also getting this after upgrading from a really old version that did not support profiling to 3.4.9. Since we did not have it before, i tried to disable profiler:

    "preview": {
        "profiler": {
            "enabled": false
        }
    }
    
However the exception still seems to happen.

Allowing access to "agent.azureserviceprofiler.net" in our firewall seems to solve the problem.

Should the agent be pulling service profiler settings if preview.profiler.enabled=false ?

**Comment by trask** [comment]
> Should the agent be pulling service profiler settings if preview.profiler.enabled=false ?

hey @arvicloveria, we aren't able to reproduce this.

can you try with 3.4.10 and confirm your full json configuration is:

```
{
  "preview": {
    "profiler": {
      "enabled": false
    }
  }
}
```

**Comment by teplyuska** [comment]
Hello @trask

Thank you for getting back so quick!

After removing access to "agent.azureserviceprofiler.net" in the firewall, and deploying our application with version 3.4.10 (still with preview.profiler.enabled=false), we no longer get the error pulling service profiler settings.

**Comment by arvicloveria** [comment]
Hello @trask 
After upgrading to 3.4.10, we no longer get the error pulling service profiler settings. By the way, we're not using json configuration, I'm just using the environment variable **APPLICATIONINSIGHTS_CONNECTION_STRING**. I guess what we ae using is the default configuration of Application Insights.

Thank you.

**Comment by trask** [comment]
Great, thanks for the confirmation!
