### ISSUE TITLE
Application Insights Appender missing ability to use connection string

### ISSUE THREAD

**Issue by Ricky-G** [microsoft/ApplicationInsights-Java#2928]
**Is your feature request related to a problem? Please describe.**
There are situations where we cant' use the App Insights agent, a prime example we encountered is with Mulesoft which runs as a SaaS/iPaaS offering and each layer instance of an API runs as an isolated Java application. We don’t have access to the JVM to attach the Application Insights Agent. See [https://help.mulesoft.com/s/article/Unable-to-use-javaagent-on-Cloudhub](https://help.mulesoft.com/s/article/Unable-to-use-javaagent-on-Cloudhub)

They do support Log4j2 Appenders. We use [https://mvnrepository.com/artifact/com.microsoft.azure/applicationinsights-logging-log4j2](https://mvnrepository.com/artifact/com.microsoft.azure/applicationinsights-logging-log4j2). The last [release for this is 2.6.4](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/2.6.4).

This currently only supports instrumentation key and no support for connection string.  With the instrumentation key being deprecated in 2025 what are the options to keep using the appender?

**Describe the solution you would like**
Ideally would like to see an update to the appender with the ability to use connection string, alternatively are there other options available here?

**Additional context**
On March 31, 2025, support for instrumentation key ingestion will end. Instrumentation key ingestion will continue to work, but we'll no longer provide updates or support for the feature. [Transition to connection strings](https://learn.microsoft.com/en-us/azure/azure-monitor/app/migrate-from-instrumentation-keys-to-connection-strings) to take advantage of [new capabilities](https://learn.microsoft.com/en-us/azure/azure-monitor/app/migrate-from-instrumentation-keys-to-connection-strings#new-capabilities).

**Comment by trask** [comment]
hi @Ricky-G!

this should be possible using the [standalone azure monitor opentelemetry exporter](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/monitor/azure-monitor-opentelemetry-exporter#azure-monitor-opentelemetry-exporter-client-library-for-java) along with the [opentelemetry log4j2 appender instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/log4j/log4j-appender-2.17/library#appender-instrumentation-for-log4j2-version-217-and-higher)

let us know if you have trouble with this, thx

**Comment by Ricky-G** [comment]
Hi @trask,

Thank you very much for getting back, using the standalone open telemetry exporter, and then using the log4j2 appender to push to Azure Monitor.

This suggested approach will work for us for now, so please feel free to close this issue.

**Comment by Ricky-G** [comment]
Hi @trask,

Thank you very much for getting back, using the standalone open telemetry exporter and then using the log4j2 appender to push to Azure Monitor.

This suggested approach will work for us for now, so please feel free to close this issue.
