### ISSUE TITLE
Logback MDC values overwritten when Application Insight is used

### ISSUE THREAD

**Issue by Lesrac** [microsoft/ApplicationInsights-Java#2942]
I'm having a Spring-Boot (3.0.2) Application that uses Kotlin coroutines, the Application Insight SDK (3.4.10), Micrometer Tracing (1.0.2) and Logback.
The log messages are successfully written to Application Insight. But the "mdc" part differs depending on if Application Insight is used or not.
Logback is configured as described in the official [log-with-logback](https://learn.microsoft.com/en-us/azure/spring-apps/structured-app-log#log-with-logback)
The issue is, that when Application Insight is configured (by correctly setting the environment variable APPLICATIONINSIGHTS_CONNECTION_STRING) each parallel executed coroutine has the same trace-id. If not, then the trace-id is different.
Is something missing? Is it not yet Spring Boot 3.0 ready?

### Expected behavior
The logs 
```
{"timestamp":"2023-02-28T15:29:53.729Z","logger":"com.myown.clientvm.handler.FileHandling","level":"INFO","thread":"DefaultDispatcher-worker-2","mdc":{"traceId":"2378d84342a106d96378305bba572d13","spanId":"f8afb97d4a1c2cee"},"message":"Sync practitioner '12345' with trace-id: '2378d84342a106d96378305bba572d13'"}
{"timestamp":"2023-02-28T15:29:53.73Z","logger":"com.myown.clientvm.handler.FileHandling","level":"INFO","thread":"DefaultDispatcher-worker-3","mdc":{"traceId":"7f876ae27d2e57f144eae3fdfec350a2","spanId":"5b37d03f8dd60c14"},"message":"Sync practitioner '98765' with trace-id: '7f876ae27d2e57f144eae3fdfec350a2'"}
```

### Actual behavior
The MDC part changes and the trace-id and span-id remains the same for each entry:
```
{"timestamp":"2023-02-28T15:28:00.847Z","logger":"com.myown.clientvm.handler.FileHandling","level":"INFO","thread":"DefaultDispatcher-worker-3","mdc":{"trace_id":"790e45ea83271e9c16338efe088947e1","trace_flags":"01","span_id":"dde2dee684e33a64"},"message":"Sync practitioner '98765' with trace-id: '790e45ea83271e9c16338efe088947e1'"}
{"timestamp":"2023-02-28T15:28:00.848Z","logger":"com.myown.clientvm.handler.FileHandling","level":"INFO","thread":"DefaultDispatcher-worker-2","mdc":{"trace_id":"790e45ea83271e9c16338efe088947e1","trace_flags":"01","span_id":"dde2dee684e33a64"},"message":"Sync practitioner '12345' with trace-id: '790e45ea83271e9c16338efe088947e1'"}
```

### To Reproduce
Have a multi-process application where you set the tracer manually

#### Sample Application
Code Snipped:
```
fun syncFilesToClientFolders() {
    logger.info { "Triggered sync" }

    runBlocking {
        val jobs = mutableListOf<Job>()
        withContext(dispatcher) {
            clientConfig.practitioners.forEach { practitioner ->
                jobs += launch(dispatcher) {
                    runCatching {
                        syncPractitioner(practitioner)
                    }.onFailure {
                        logger.error(it) { "Error syncing practitioner '$practitioner'. Reason: ${it.message}" }
                    }
                }
            }
        }
        jobs.joinAll()
    }
}

suspend fun syncPractitioner(practitioner: String) {
        val newSpan = tracer.nextSpan().name("Sync practitioner $practitioner")
        try {
            tracer.withSpan(newSpan.start())
            newSpan.tag("practitioner", practitioner)
            newSpan.event("Start syncing of practitioner")
            logger.info { "Sync practitioner '$practitioner' with trace-id: '${newSpan.context().traceId()}'" }
            var counter = -1
           // do other stuff
            logger.info { "Sync practitioner '$practitioner' done - '$counter' file(s) synchronized" }
        } finally {
            newSpan.event("Sync practitioner done")
            newSpan.end()
        }
    }
```

### System information
Please provide the following information:
 - SDK Version: 3.4.10
 - OS type and version: Linux
 - Application Server type and version (if applicable):
 - Using spring-boot: yes, 3.0.2
 - Additional relevant libraries (with version, if applicable): io.micrometer:micrometer-tracing & io.micrometer:micrometer-tracing-bridge-otel 1.0.2, net.logstash.logback:logstash-logback-encoder: 7.2

### Logs
No logs, as there are no errors that could be shown

**Comment by trask** [comment]
hi @Lesrac! can you try without using micrometer-tracing so we can know if it's due to interaction with that tracing library?

**Comment by Lesrac** [comment]
Hello @trask without micrometer-tracing I don't have any "mdc" values when running without Application Insight `"mdc":{},"message":"Sync practitioner `.
And when running with Application Insight I'm having the same behaviour as described in the question (mdc entry is present, but the trace and span id is the same for each entry).

**Comment by woglinde** [comment]
Hi @Lesrac,

are you aware that you have to set the MDCContext() when using coroutines?
https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-slf4j/kotlinx.coroutines.slf4j/-m-d-c-context/

So I think this has nothing todo with app insights or mircrometer.

**Comment by trask** [comment]
sorry, I think I understand now, the Application Insights Java agent doesn't interop with Micrometer tracing today, can you try using OpenTelemetry for creating spans manually instead of Micrometer tracing? thx!

**Comment by trask** [comment]
> So Micrometer is only the facade for OpenTelemetry that is used for tracing

Can you try using OpenTelemetry API directly instead of via Micrometer Tracing facade? That is what we test and should work.

**Comment by Lesrac** [comment]
@trask ah sorry, my bad. I've tried it out and found with it the solution that also works in Micrometer.
I need to call "setNoParent()" (in Micrometer and also when using OpenTelemetry API directly) so that a trace_id for each call is created.
So my code looks now like this:
```
suspend fun syncPractitioner(practitioner: String) {
        val newSpan = tracer.spanBuilder().setNoParent().name("Sync practitioner ${practitioner.number}")
        tracer.withSpan(newSpan.start()).use {
            newSpan.tag("practitioner", practitioner)
            newSpan.event("Start syncing of practitioner")
            logger.info { "Sync practitioner '${practitioner.number}'" }
            var counter = -1
            // do other stuff
            logger.info { "Sync practitioner done - '$counter' file(s) synchronized" }
        }
    }
```

Thanks for taking your time and helping me out here.
