### ISSUE TITLE
Request not present in application insights when it got cancelled

### ISSUE THREAD

**Issue by xsmrcek** [microsoft/ApplicationInsights-Java#2943]
Hello,
when my application is called and request is cancelled (due to up stream timeout), canceled request is not present in application insights, which leads to dependency calls not linked to any request or trace and it makes log really hard to read.

To simulate this behavior you can use application https://github.com/xsmrcek/minimal-example there is /sample endpoint with loop, so there is plenty of time to cancel requests (from postman for example). I did my testing with agent version 3.4.1 and 3.4.4.

![image](https://user-images.githubusercontent.com/50624143/221971600-d0f9a532-002c-4254-96b8-638f10631341.png)

**Comment by heyams** [comment]
@xsmrcek I tried your sample app and wasn't able to reproduce by canceling the request via browser.
Can you please share how you cancel the request? Please share your exact repro steps. Thanks.

**Comment by xsmrcek** [comment]
Hello @heyams , I managed to cancel request via postman:
![image](https://user-images.githubusercontent.com/50624143/223342876-89a35bef-e959-40e2-937e-70f07d37b38e.png)

**Comment by heyams** [comment]
I tried it via postman 'cancel', same though. can you email [Application Insights Java Help](appinsightsjavahelp@microsoft.com) to schedule a call with me?
