### ISSUE TITLE
3.4.x Agents no longer providing cloud_RoleName and other behavior changes

### ISSUE THREAD

**Issue by my3sons** [microsoft/ApplicationInsights-Java#2975]
We have been fighting various things with our Spring Boot apps running on App Services using Java 17 for a while now. We dealt with the 404 issue for some time by disabling app insights (which is obviously not a good thing), then when the 3.4.x agent got released that finally got fixed, but now we are fighting logging issues that were not there with Java 11. We are using the codeless agent and with Java 11 all that was required was to include the following dependencies in our deployment. The logging framework we are using is the slf4j implementation from lombok.

```xml
<dependency>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>applicationinsights-spring-boot-starter</artifactId>
	<version>2.6.4</version>
</dependency>
<dependency>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>applicationinsights-logging-logback</artifactId>
	<version>2.6.4</version>
</dependency>
```

With that all our app logs ended up as expected in Log Analytics. However, with Java 17 and the 3.4.10 agent, in order for our app logs to make it to Log Analytics, we now need to also include at a minimum the following logback.xml in our deployment as well:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="org/springframework/boot/logging/logback/base.xml"/>
    <appender name="aiAppender"
              class="com.microsoft.applicationinsights.logback.ApplicationInsightsAppender">
    </appender>
    <root level="info">
        <appender-ref ref="aiAppender" />
    </root>
</configuration>
```
This is no big deal, but what we are also observing which is much more impactful is that with the 3.4.10 agent, the "cloud_RoleName" field and some others as well are not get populated anymore in log analytics. We have multiple apps leveraging the same application insights resource and the cloud_RoleName is the one field that allowed us to write queries that would filter just the app logs you were interested in. With Java 11 and the older agents, the cloud_RoleName was automatically populated for us. Is this a bug in the 3.4.x agents or is there something that we now need to do differently to get that working again?

**Comment by jeanbisutti** [comment]
Hi @my3sons,

Could you  please provide:
* The Spring Boot version
* The logback version (`mvn dependency:tree`)
* The lombock version

The Application Insights 2 dependency above has only been added to reobtain Logs Analytics?

```
<dependency>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>applicationinsights-spring-boot-starter</artifactId>
	<version>2.6.4</version>
</dependency>
```

Thank you.

**Comment by my3sons** [comment]
Hello @jeanbisutti,

Here are the details you requested:
- spring boot version: 3.0.4
- logback version: 1.4.5
- lombok version: 1.18.24

you can disregard my mention of the applicationinsights-spring-boot-starter dependency, that was my bad. I should not have included that as it is not impacting the results one way or the other.

Thanks for any help you can offer!

**Comment by heyams** [comment]
HI @my3sons, If you don't provide a custom role name, it will auto-generate the role name using App Service's name. 
Can you please share the name of App Service on Azure? How did you use 3.4.10? Did you follow this [instructions(https://learn.microsoft.com/en-us/azure/azure-monitor/app/azure-web-apps-java#manually-deploy-the-latest-application-insights-java-version)?

**Comment by jeanbisutti** [comment]
> Hello @jeanbisutti,
> 
> Here are the details you requested:
> 
> * spring boot version: 3.0.4
> * logback version: 1.4.5
> * lombok version: 1.18.24
> 
> you can disregard my mention of the applicationinsights-spring-boot-starter dependency, that was my bad. I should not have included that as it is not impacting the results one way or the other.
> 
> Thanks for any help you can offer!

Hi @my3sons,

I have tested the Logback 1.4.5 instrumentation with Application Insights 3.4.10. It seems to work fine.

I have deployed a Spring Boot 3.0.4 application with Logback 1.4.5 and Lombok 1.18.24 on App Service, with Java 17. I have also enabled Application Insights 3.4.10 on App Service with these [instructions](https://learn.microsoft.com/en-us/azure/azure-monitor/app/azure-web-apps-java#manually-deploy-the-latest-application-insights-java-version). The cloud role name is populated:

![image](https://user-images.githubusercontent.com/14811066/227374469-bea5e0ab-2ae2-4816-970e-70f9f3fd4c30.png)

So, I may think that you have disabled Application Insights on App service. I suggest you enable Application Insights 3.4.10 on App Service with these [instructions](https://learn.microsoft.com/en-us/azure/azure-monitor/app/azure-web-apps-java#manually-deploy-the-latest-application-insights-java-version) and remove `applicationinsights-logging-logback` to have fields, as the cloud role name, populated by the Application Insights Java agent.

**Comment by my3sons** [comment]
Hello @my3sons and @heyams,

We use terraform automation to build all our Azure infrastructure (including app services) and the way that we configure the app to use Application Insights and specifically to use the 3.4.10 agent, is to set the following app_settings on the app service when it gets created. 

```
APPLICATIONINSIGHTS_CONNECTION_STRING={key vault secret uri to app insights connection string} 
ApplicationInsightsAgent_EXTENSION_VERSION=3.4.10  //with Java 11, we would set this to ~3
```
This has worked fine for us up until Java 17. Jean, to your question above, App Insights is enabled on our App Services. If I look through the instructions that both of you have linked, it seems that it is just a manual implementation of what we are doing via automation, correct? We manage a lot of App Services and we don't want to do anything manually so I am hoping we can continue to build out all our resources using automation if possible. The one sort of weird thing is that we did observe that one of our App Services actually did generate a cloud_RoleName but it was simply "Application", which did not correlate to anything with that App Service. All our app App Services follow a rather strict naming convention (controlled through our automation) and "Application" is no where in the name.

**Comment by jeanbisutti** [comment]
@my3sons 
Can you please provide a line example from Log analytics by hiding the sensitive information? I will reply your questions after. Thank you.

**Comment by my3sons** [comment]
> @my3sons Can you please provide a line example from Log analytics by hiding the sensitive information? I will reply your questions after. Thank you.

here you go...
[query_data.csv](https://github.com/microsoft/ApplicationInsights-Java/files/11061456/query_data.csv)

**Comment by jeanbisutti** [comment]
@my3sons 

Thank you. In the line example, the `sdkVersion` field value is `java:2.6.4`. So, this line does not come from the Application Insights 3.4.10 agent.

To use the last version of the Application Insights agent in App service (3.4.10 today), `ApplicationInsightsAgent_EXTENSION_VERSION` has not be updated. 

You have several possibilities to use the last agent version on App service:
* Follow the instructions provided [here](https://learn.microsoft.com/en-us/azure/azure-monitor/app/azure-web-apps-java#manually-deploy-the-latest-application-insights-java-version)
* Use the [programmatic attachment](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-spring-boot#enabling-programmatically) for Spring Boot applications. As for the first solution, you have to disable the default agent provided by App service (not 3.4.10 today)

` The one sort of weird thing is that we did observe that one of our App Services actually did generate a cloud_RoleName but it was simply "Application", which did not correlate to anything with that App Service. `

It probably comes from `applicationinsights-logging-logback` 2.6.4 you have added. With Application Insights 3 and App service , the default value is different (see my screenshot below). You have the possibility to [override this default value](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#cloud-role-name) with Apllication Insights 3.

**Comment by my3sons** [comment]
Hello @jeanbisutti 
A couple things.. first can you provide a bit more context to this statement above: "ApplicationInsightsAgent_EXTENSION_VERSION has not be updated."  I am not exactly following what you mean by that?  

The other thing is that clearly when we set the ApplicationInsightsAgent_EXTENSION_VERSION=3.4.10 (rather than ~3) it is having a material impact, because without that, we then see all our requests fail to the services with the 404 issue. That being said, we will try the suggestions above and let you know how it goes, thanks!

**Comment by jeanbisutti** [comment]
@my3sons 

The following scenario may have happened in your case:
* A new version of Application Insights was released on App service leading to your 404 issue. We are sorry about that.
* You have updated `ApplicationInsightsAgent_EXTENSION_VERSION` at `3.4.10`, which has disabled the Application Insights agent provided by App service. **_So, please try to continue indeed with a version different from `~3` (`off `may be more explicit)_**
* You have lost the Application Insights 3 telemetry and tried to have logging telemetry from Application Insights 2 (which has a different behavior than Application Insights 3)

So, could you please try with one of the 2 possibilies mentioned above (instructions [here](https://learn.microsoft.com/en-us/azure/azure-monitor/app/azure-web-apps-java#manually-deploy-the-latest-application-insights-java-version) or programamtic configuration), so that you will use Application Insights 3.4.10 and you should find the expected logging behavior.

Thank you.

**Comment by my3sons** [comment]
Hello @jeanbisutti and @heyams 

So good news, we went with the programmatic approach suggested above by Jean and everything seems to be working as expected (e.g. all logs are flowing in and cloud_RoleName is populated accordingly). I honestly did not even know this programmatic option existed until now, so good to now have that in our bag of tricks! Thanks again for the help on this, it is greatly appreciated!
