### ISSUE TITLE
Requests resulting in response code 5xx are not marked as failed requests

### ISSUE THREAD

**Issue by jgogstad** [Microsoft/ApplicationInsights-Java#298]
The exception handling logic in `WebRequestTrackingFilter` rethrows the exception before invoking `onEndRequest` on all the modules. This results in 5xx-responses not being logged as failed requests in Application Insights and is inconsistent with the way the .NET-library works.

**Comment by OriYosefiMSFT** [comment]
Closing as [#294](https://github.com/Microsoft/ApplicationInsights-Java/issues/294) was merged
