### ISSUE TITLE
Do we have any version of applicationinsights-spring-boot-starter that can support Spring Boot 3.0?

### ISSUE THREAD

**Issue by JayPoon** [microsoft/ApplicationInsights-Java#2997]
We are now using *applicationinsights-spring-boot-starter-2.6.0.jar* in our Spring Boot 2.6 project.

Recently, we are planning to upgrade our project to Spring Boot 3.0，
However, we found that current applicationinsights-spring-boot-starter-2.6.0.jar is not compatible with Spring Boot 3.0, because of below change:

>Spring Boot 2.7 [introduced](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#changes-to-auto-configuration) a new META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports file for registering auto-configurations, while maintaining backwards compatibility with registration in spring.factories. With this release, support for registering auto-configurations in spring.factories has been removed in favor of the imports file.

References:
- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files
- META-INF\spring.factories file
in applicationinsights-spring-boot-starter-2.6.0.jar

**Our questions are as following:**
- Do we have any version of applicationinsights-spring-boot-starter that can support Spring Boot 3.0?
- If no, do we have release plan to support Spring Boot 3.0?

**Comment by heyams** [comment]
Hi @JayPoon, thank you for reaching out.

I have created a test app by enabling Java Agent 3.x programmatically, which support Spring boot 3.x. 
Can you please give it a try and let us know your feedback? 
https://github.com/microsoft/ApplicationInsights-Java-Repros/tree/main/SpringBoot3xSupport

More details on attach Java agent programmatically: https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-spring-boot#enabling-programmatically
