### ISSUE TITLE
Mark Non HTTP Requests successful=false incase of dependency exception

### ISSUE THREAD

**Issue by zoomingrocket** [microsoft/ApplicationInsights-Java#2999]
**Is your feature request related to a problem? Please describe.**
We are using Java Agent 3.4.10 with COTs Middleware. 
In case of non-HTTP requests, e.g. JMS request while getting processed, if a dependency causes an exception, still the entire request is still marked successful with response code 0

**Describe the solution you would like**
Have request status successful=false in case of dependency exceptions for non-HTTP Requests

**Describe alternatives you have considered**
Not explored

**Additional context**
E.g. screenshot
![image](https://user-images.githubusercontent.com/2420449/231233755-af12e2cf-aeda-4374-99e5-faf186691a65.png)

**Comment by heyams** [comment]
@zoomingrocket can you please submit a repro app to https://github.com/microsoft/ApplicationInsights-Java-Repros?
