### ISSUE TITLE
In Java, Azure applicationinsights starter dependency not compatible with spring boot 3.x.x

### ISSUE THREAD

**Issue by charu-jain-sapient** [microsoft/ApplicationInsights-Java#3016]
### Expected behavior
Azure applicationinsights starter dependency should work properly with spring boot 3.x.x

### Actual behavior
Azure applicationinsights starter dependency working correctly till spring boot 2.7.11

### To Reproduce

PR here: https://github.com/microsoft/ApplicationInsights-Java-Repros/pull/2

### System information
Please provide the following information:
 - SDK Version: Java 17
 - OS type and version: Windows 10 Enterprise
 - Application Server type and version (if applicable): 
 - Using spring-boot? yes, v3.0.0
 - Additional relevant libraries (with version, if applicable):    implementation 'com.microsoft.azure:applicationinsights-spring-boot-starter:2.6.4'

### Logs

***************************
APPLICATION FAILED TO START
***************************

Description:

Field telemetryClient in com.example.demo.app.insights.UserController required a bean of type 'com.microsoft.applicationinsights.TelemetryClient' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'com.microsoft.applicationinsights.TelemetryClient' in your configuration.

Process finished with exit code 1

### Stackoverflow issue
Raised an issue here: https://stackoverflow.com/questions/76073120/in-java-azure-applicationinsights-starter-dependency-not-compatible-with-spring

**Comment by heyams** [comment]
Hi @charu-jain-sapient, thank you for submitting a repro app to our repo. 
I appreciate it :)

I have created a new module in the same repo based on your test app to help you with spring boot 3 issue. 
Can you please give it a try by following the [README](https://github.com/microsoft/ApplicationInsights-Java-Repros/tree/main/SpringBoot3xSupport) and let us know if that is sufficient?

**Comment by charu-jain-sapient** [comment]
Thankyou @heyams for the quick resolution. It works for me. Thanks again. You can close this ticket now :)
