### ISSUE TITLE
TransmissionNetworkOutput - Failed to send, wrong host address or cannot reach address due to network issues

### ISSUE THREAD

**Issue by RathiRojini** [microsoft/ApplicationInsights-Java#3021]
Hi,

we are  using application insight agent 3.0.2 . 
Created a custom availability test using application insight and powershell. 
Ref: https://swimburger.net/blog/azure/run-availability-tests-using-powershell-and-azure-application-insights

It was working successfully for almost 1.5 years . since 31st March , data are not sent to azure on the scheduled interval (5m) .. Data are available once in an hour or two .

Below logs are found in the applicationinsight log file

ERROR c.m.a.i.c.c.TransmissionFileSystemOutput - Persistent storage max capacity has been reached; currently at 10486324 bytes. Telemetry will be lost, please consider increasing the value of MaxTransmissionStorageFilesCapacityInMB property in the configuration file.

what needs to be done to fix this issue ?  Other than the availability tests , dependency and  exception logs are not affected.

**Comment by RathiRojini** [comment]
@heyams , thank you ! we are planning to do the upgrade but we would try to fix the issue first before proceeding the upgrade. 
i couldnt find '/applicationinsights' folder but found  C:\WindowsAzure\Logs  and removed telemetry logs .Now  Persistent storage max capacity has been reached is resolved but following error still exists.

2023-04-25 17:20:42.300+03 ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send, wrong host address or cannot reach address due to network issues
java.net.UnknownHostException: dc.services.visualstudio.com
	at java.net.InetAddress.getAllByName0(Unknown Source)

**Comment by heyams** [comment]
@RathiRojini can you upgrade to the latest? 3.0.2 is really old from 2021. Or turn on 'APPLICATIONINSIGHTS_SELF_DIAGNOSTICS_LEVEL=debug' and share the full log with me?

**Comment by RathiRojini** [comment]
@heyams , thank you . will try the upgrade option.
