### ISSUE TITLE
Error in dependency graph, core marks agent in provided scope but can't run without it

### ISSUE THREAD

**Issue by jgogstad** [Microsoft/ApplicationInsights-Java#303]
Module `Core` marks module `Agent` in provided scope in [build.gradle][core dep], but depends explicitly on `StringUtils` which is found in `Agent` in [TelemetryConfigurationFactory][core usage]. Results in runtime exceptions unless `Agent` is on classpath. This was introduced by the processors support [PR][296].

Maybe move StringUtil out of the agent module?

[core dep]: https://github.com/Microsoft/ApplicationInsights-Java/blob/v1.0.5/core/build.gradle#L35
[core usage]: https://github.com/Microsoft/ApplicationInsights-Java/blob/v1.0.5/core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java#L199
[296]: https://github.com/Microsoft/ApplicationInsights-Java/pull/296/files#diff-9b0619effbeef16cfa899fe3c01af150

**Comment by jgogstad** [comment]
On closer inspection I see that you already depend on `org.apache.commons:commons-lang3` which provides `org.apache.commons.lang3.StringUtils#isBlank`. I suggest you use that instead.

**Comment by gupele** [comment]
Thanks @jgogstad, great catch :)

I am posting a PR with fixes, the fix will use the Core's internal LocalStringsUtils. As a rule of thumb we try avoiding 3rd party use, as much as possible, and this one is very easy to avoid
