### ISSUE TITLE
cloud-role: java-standalone-upgrade-from-2x

### ISSUE THREAD

**Issue by Jitu-Ranjan** [microsoft/ApplicationInsights-Java#3037]
### Expected behavior
A migration path to achieve the segregation of telemetry at the application level.

### Actual behavior
How does the migration work for configurations at applications hosted on the same node? The Java agent does not provide options to segregate the telemetry per application. Cloud role and HTTP-based configurations work at an environment level which again can be achieved by initializing values at the node level. 

### To Reproduce

Following this page https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-upgrade-from-2x, talks about using Java agent to replace application based configs. But what's equivalent of telemetries configured in ApplicationInsights.xml configs per application. Cloud role and HTTP routing never works at app level.

**Comment by trask** [comment]
hi @Jitu-Ranjan!

check out https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#cloud-role-name-overrides-preview, and let us know if that works for you, thx

**Comment by Jitu-Ranjan** [comment]
Hi @trask , the cloud-role name is enabled using an environment variable and this is a web server with multiple applications (a,b,c) for each app I need a segregation of all the logs not only httpPathPrefix config. Do we have an option to enable such sgegration using codeless agent?

**Comment by trask** [comment]
> for each app I need a segregation of all the logs not only httpPathPrefix config

do you mean for logs which aren't part of any request?
