### ISSUE TITLE
JAVA - Caused by: java.lang.NoClassDefFoundError: org/apache/http/impl/conn/PoolingClientConnectionManager

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-Java#307]
Copy from: https://github.com/Microsoft/ApplicationInsights-Home/issues/55 

@oak-tree reported:

> I'm using Java,Tomcat, Spring and log4js. I'm trying to use applicationinsights with those tools. 
>  I followed this links https://azure.microsoft.com/en-us/documentation/articles/app-insights-java-get-started/
> 
> But i get `Caused by: java.lang.NoClassDefFoundError: org/apache/http/impl/conn/PoolingClientConnectionManager`
> 
> Ok it seems that  `applicationInsights` has dependency on `https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient/4.5.2`
>  maybe its worth to update the documents for that?

**Comment by Dmitry-Matveev** [comment]
1.0.7 release includes all Core JAR dependencies within the JAR itself (shadow JAR), this issue should be addressed.
