### ISSUE TITLE
Where do we download the newest release of the java agent?

### ISSUE THREAD

**Issue by jgogstad** [Microsoft/ApplicationInsights-Java#308]
* It's not available in maven central: https://mvnrepository.com/artifact/com.microsoft.azure
* The [documentation][docs] points to [this link](https://azuredownloads.blob.core.windows.net/applicationinsights/sdk.html) which only contains links to version 1.3. Substituting version number in the download URL gives 404.

[docs]: https://azure.microsoft.com/en-us/documentation/articles/app-insights-java-get-started/

**Comment by OriYosefiMSFT** [comment]
We're in the process of updating the location above with the new binaries. We have to go through a different team in order to upload binaries, so it takes a little while longer.

**Comment by OriYosefiMSFT** [comment]
The SDK and binaries are available [here](https://aka.ms/aijavasdk). I have also submitted a pull request to update the documentation.
