### ISSUE TITLE
Spring custom log level for specific classses

### ISSUE THREAD

**Issue by koddea** [microsoft/ApplicationInsights-Java#3081]
I'm using applicationinsights-runtime-attach (3.4.12) under Spring Boot.

I have setted logLevel as warn in applicationinsights.json.
And i just want to set different logLevels for some specific classes as i do in properties json/yaml files and logback/log4j xmls.

`logging.level.com.roof.payment.controller.RestLogHandler=DEBUG`
`<logger name="com.roof.payment.controller.RestLogHandler" level="DEBUG" />`

Is there any way to accomplish above configuration under applicationinsights.json or any other way?

**Comment by heyams** [comment]
Hi @koddea, 

I have created a new sample app to meet your need.
https://github.com/Azure-Samples/ApplicationInsights-Java-Samples/pull/98. 

It's pending on approval, but feel free to check it out and run it by following the [README](https://github.com/Azure-Samples/ApplicationInsights-Java-Samples/pull/98/files#diff-6be285e9e6c63cdf797528a7e166d9b399c93a1ff849c492fbce49afe4e2ee74).
