### ISSUE TITLE
Span changes are ignored when running application inside Kubernetes

### ISSUE THREAD

**Issue by YevhenMaksymovych** [microsoft/ApplicationInsights-Java#3103]
### Expected behavior
Span changes should be propagated to Java AI Agent 

### Actual behavior
We use following code to update AI operationName via OpenTelemetry API to make OperationName more verbose:
`Span.current().setAttribute("applicationinsights.internal.operation_name", operationName);` //attribute name is taken from com.azure.monitor.opentelemetry.exporter.implementation
Thus it's working when running application locally (we can see our operation_Name in AI logs), Kubernetes deployment for some reason sends default operationName set by auto-instrumentation.

Short debug shown that Span.current() returns OpenTelemetry's ApplicationSpan wrapping SdkSpan, containing auto-instrumentaled name inside. 
So basically, either following 
`Span.current().updateName(operationName);`
or 
`Span.current().setAttribute("applicationinsights.internal.operation_name", operationName);`
should work to make AI agent mapping take correct value.

And both of them work when running application locally, but deployed in Kubernetes - not.

If being more specific - Span changes are ignored for ServiceBus triggered flows.

### System information
Please provide the following information:
 - SDK Version: JDK 17.0.6, AI Agent 3.4.9, 3.4.13
 - Using spring-boot: yes

### Screenshots
Span is updated with local run
<img width="725" alt="Знімок екрана 2023-05-30 о 12 11 43" src="https://github.com/microsoft/ApplicationInsights-Java/assets/108663543/ceee2bc3-735b-46da-a188-b6d893948fff">

Span changes are ignored for Kubernetes deployment
<img width="611" alt="Знімок екрана 2023-05-30 о 12 18 43" src="https://github.com/microsoft/ApplicationInsights-Java/assets/108663543/42e7e906-b12f-49b2-817d-c524b95663d8">

**Comment by heyams** [comment]
@YevhenMaksymovych can you wrap around your span update method with the following?

context propagation:
```Java
try(Scope ignored =Span.current().makeCurent()) {
    // update span
}
```
