### ISSUE TITLE
Is there a way to sample inProc dependency?

### ISSUE THREAD

**Issue by Sachin1O1** [microsoft/ApplicationInsights-Java#3145]
Hi @trask, 

We are facing the problem of having a lot of inproc dependencies spamming. I tried to find a way to sample them in the doc but failed. Please suggest me a way to do it.

**Comment by Sachin1O1** [comment]
Hi @heyams,

I am using java agent 3.2.12. I read that inProc dependencies are automatically suppressed by default but we have them in our system.

can you tell me the key and value for sampling in-proc?

"attributes": [
            {
              "key": "?",
              "value": "?",
              "matchType": "strict"
            },

**Comment by heyams** [comment]
![image](https://github.com/microsoft/ApplicationInsights-Java/assets/56097766/4c85b0a8-9d50-4d60-bf5a-eb9b4cc030a7)

**Comment by Sachin1O1** [comment]
Hi @heyams , If I am getting it right you are asking me to enable debug log for application insight and check attributes for  in-proc dependency and then use it.

I tried following but didn't work.
`{
          "telemetryType": "dependency",
          "attributes": [
            {
              "key": "thread.name",
              "value": "<package>*",
              "matchType": "regexp"
            }
          ],
          "percentage": 0
        }` 

and also as you said that inproc is automatically suppressed by default but why it is not working?

**Comment by heyams** [comment]
@Sachin1O1 can you use the following json config instead?

```json
{
  "connectionString": "<your connection string>",
  "preview": {
    "sampling": {
      "overrides": [
        {
          "telemetryType": "dependency",
          "attributes": [
            {
              "key": "thread.name",
              "value": "<package>.*",
              "matchType": "regexp"
            }
          ],
          "percentage": 0
        }
      ]
    }
  }
}
```

Replace `<package>` with actual package name and `connectionString` with your app insights resource.
 If it still doesn't work, please share your applicationinsights.log and applicaitoninsights.json.

**Comment by Sachin1O1** [comment]
Hi @heyams ,
I tried what you suggested but it didn't work. Can you share your email so that I can share applicationinsights.log and applicaitoninsights.json.

**Comment by heyams** [comment]
@Sachin1O1 sure. please email me at helen.yang@microsoft.com.

**Comment by Sachin1O1** [comment]
Hi @heyams, I emailed the required files to your email id.

**Comment by Sachin1O1** [comment]
HI @heyams , any update?

**Comment by heyams** [comment]
I did check your log and json config. Attributes you used in your json config are not found in the log. That might explain why sampling overrides didn't work for you. Can you use fiddler to monitor all your telemetry to verify telemetry that you are expecting to be sent to Application Insights?

**Comment by heyams** [comment]
@Sachin1O1 We were able to confirm that thread.name doesn't work using sampling override. It was added after sampling was applied.  I will propose a fix upstream to add thread.name before span onStart.

We also noticed that instrumentationScope is GlobalTracer. Are you creating that span programmatically?

**Comment by Sachin1O1** [comment]
@heyams , We are not creating this span programmatically.

**Comment by trask** [comment]
@Sachin1O1 do you know who is capturing this InProc span?

`name=GlobalTracer` doesn't look like something that is captured by auto-instrumentation:

> instrumentationScopeInfo=InstrumentationScopeInfo{name=GlobalTracer

**Comment by Sachin1O1** [comment]
@trask , I am sure that we are not using anything other than the application insight jar for capturing data.

**Comment by trask** [comment]
I searched a bit, and it looks like `GlobalTracer` may be coming from OpenTracing (https://github.com/opentracing/opentracing-java/blob/master/opentracing-util/src/main/java/io/opentracing/util/GlobalTracer.java). Do you happen to have the `opentelemetry-opentracing-shim` in your classpath?

**Comment by Sachin1O1** [comment]
Hi @trask, I check the lib and found following in the classpath.

opentelemetry-api-1.23.1.jar
opentelemetry-context-1.23.1.jar
opentelemetry-instrumentation-api-1.23.0.jar
opentracing-api-0.33.0.jar
opentracing-grpc-0.2.3.jar
opentracing-noop-0.33.0.jar
opentracing-spring-web-2.1.4-SNAPSHOT.jar
opentracing-util-0.33.0.jar
opentracing-web-servlet-filter-0.4.0.jar

**Comment by Sachin1O1** [comment]
Hi @trask and @heyams, Apologies. I dig a little deeper when I found open telemetry libs in classpath and got to know that there is a new code that is using open telemetry tracer to trace the scheduled thread and enrich the span that gets captured.

**Comment by trask** [comment]
> got to know that there is a new code that is using open telemetry tracer to trace the scheduled thread

does this solve your sampling question (are you able to change the code itself)? thx

**Comment by Sachin1O1** [comment]
Hi @trask , No problem is not solved yet, We can look for alternatives to do the same thing but it can take time. As you guys know the best so I need your advice.

**Comment by trask** [comment]
hey @Sachin1O1, sorry, I think I'm probably still not understanding something

> there is a new code that is using open telemetry tracer to trace the scheduled thread

can you change this code to not create the unwanted inProc dependency?

**Comment by Sachin1O1** [comment]
Hi @trask ,The new code use this (https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-add-modify?tabs=java#use-the-opentelemetry-api) to track schedular threads as enrich span. I don't see anything related to creating an inProc dependency in the code.

**Comment by trask** [comment]
are you able to remove the code which is creating that span?

**Comment by xsmrcek** [comment]
Hi @Sachin1O1 , @trask .
I was experimeting with similar issue today. It seems I was able to solve it via following config:
```json
"preview": {
    "sampling": {
      "overrides": [
        {
          "telemetryType": "request",
          "attributes": [
            {
              "key": "code.function",
              "value": "refresh",
              "matchType": "regexp"
            }
          ],
          "percentage": 0
        }
        ]
    }
  }
```

For scheduled function like this:
```kotlin
@Scheduled(cron = "0 * * ? * *")
    fun refresh() {  /*do some magic*/ }
```

key `code.namespace` was working too (it uses class name with apckage like 'org.my.org.my.project.myClass' but it was sampling every Span from this class, whoch wasn;t OK for me.
