### ISSUE TITLE
Send custom metrics to Live Metrics stream?

### ISSUE THREAD

**Issue by sebastian-alfers** [microsoft/ApplicationInsights-Java#3152]
This is more of a question. Is it possible to contribute with manually generated metrics to the pre-defined "Live Metrics" dashboard? E.g. Sending `Incoming Requests` metrics? Maybe through some global QuickPulse api or so?

I am using the latest version of the app insights agent and already use the `GlobalOpenTelemetry`.

**Comment by sebastian-alfers** [comment]
For example, I had had the idea if I could create a custom OpenTelemetry based counter with a special  name, it could show up on the Live metrics dashboard.

**Comment by heyams** [comment]
https://learn.microsoft.com/en-us/azure/azure-monitor/app/live-stream?tabs=dotnet6#enable-live-metrics-by-using-code-for-any-net-application

You can play with QuickPulse API. I only find .net library though. I have reached out to Live Metrics team for other options. 

[here](https://learn.microsoft.com/en-us/azure/azure-monitor/app/live-stream?tabs=dotnet6#enable-live-metrics-by-using-code-for-any-net-application:~:text=additional%20steps.%0A%20%20%20%20client.-,TrackDependency,-(%22My%20dependency) you can try to use `trackMetric` instead. Personally, I haven't tried it myself. 

Custom Metrics are not supported for Live Metrics in Application Insights Java Agent today. We did have a hackathon last year to play with that idea, but it did not turn into a PROD feature.

**Comment by sebastian-alfers** [comment]
Thank you for your feedback!
