### ISSUE TITLE
Compressed version of dependency

### ISSUE THREAD

**Issue by abhinvj** [microsoft/ApplicationInsights-Java#3176]
Hi,
Could you please create compressed version of the dependency.

Thanks,
Abhinav

**Comment by trask** [comment]
hi @abhinvj! can you clarify which dependency (and version) you're seeing is uncompressed?

**Comment by abhinvj** [comment]
Hi @trask , size of applicationinsights-agent jar is around 37 mb. is it possible to generate compressed version of this jar.

**Comment by trask** [comment]
hi @abhinvj, the 37 mb is already compressed. if you uncompress it you'll find that it's ~90 mb
