### ISSUE TITLE
In Java agent 3.4.14 is there a way to update session_id and user_id in the telemetry client object?

### ISSUE THREAD

**Issue by balaji2796** [microsoft/ApplicationInsights-Java#3177]
Describe what you expected to happen.

in applicationinsights-spring-boot-starter version 2.6.0 we were updating the session_id and user_id values in telemetry initializer

public void initialize(Telemetry t) {
		t.getContext().getUser().setId("values here");
		t.getContext().getSession().setId("values here");
}

now we have updated to java agent approach so we are initializing the telemetry client this way
		TelemetryClient telemetryClient = new TelemetryClient();
		telemetryClient .getContext().getUser().setId("values here");
		telemetryClient .getContext().getSession().setId("values here");
		
when i try to update this object by updating the session and user details its not getting reflected any idea?

**Comment by balaji2796** [comment]
for auto instrumented request that is coming through java agent automatically,  is there any way where i could initialize the custom dimensions so that it comes for custom and auto instrumented requests?

**Comment by trask** [comment]
hi @balaji2796! check out https://github.com/Azure-Samples/ApplicationInsights-Java-Samples/blob/main/advanced/migration-3x/src/main/java/com/example/ExampleWebTelemetryModule.java and let us know if that example answers your question

**Comment by balaji2796** [comment]
@trask thanks its working
