### ISSUE TITLE
In Java agent 3.4.14 is there a way to update custom dimension for auto instrumented request?

### ISSUE THREAD

**Issue by balaji2796** [microsoft/ApplicationInsights-Java#3178]
using applicationinsights-runtime-attach 3.4.14 

Is there a way where we can update custom dimensions to all auto instrumented request programmatically from spring boot?
i'm actually using spring boot 3 and wanted all the auto instrumented request to have some default custom dimensions updated. is there any way to update it? saw examples for c# but want it for java based.

**Comment by balaji2796** [comment]
hey @trask,

yes we want to apply these custom dimensions to all these telemetry calls and custom dimensions are same but need to set the values once the application starts so that the auto instrumentation picks this up

**Comment by trask** [comment]
can you use https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#custom-dimensions, and set env vars before launching the app? or are the values only something that can be retrieved programmatically after the application starts?

**Comment by trask** [comment]
another option since you're using runtime-attach might be to dynamically write out the applicationinsights.json file before calling ApplicationInsights.attach()
