### ISSUE TITLE
In Java agent 3.4.14 is there a way to filter certain file types like .css, .html during auto instrumentation?

### ISSUE THREAD

**Issue by balaji2796** [microsoft/ApplicationInsights-Java#3179]
using applicationinsights-runtime-attach 3.4.14 for spring boot 3

1.in applicationinsights-spring-boot-starter version 2.6.0 we were using telemetry processor and  through which we didnt allow files such as .html,.css,.js to be auto collected for request.

is there any approach in java agent 3.4.14?

2. seeing this error log in console while running java agent 3.4.14 

ERROR c.azure.core.http.policy.RetryPolicy - {"az.sdk.message":"Retry attempts have been exhausted.","exception":"Network is unreachable: no further information: /","tryCount":3}

Added dependencies related to azure are below:

applicationinsights-runtime-attach -3.4.14
applicationinsights-core - 3.4.14
applicationinsights-web -3.4.14

at times the spring application load stops after this message and getting terminated.

**Comment by trask** [comment]
hi @balaji2796! check out https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-sampling-overrides and let us know if this addresses your need, thx

**Comment by balaji2796** [comment]
can this be done programmatically using the request telemetry similar to this ?
[](https://github.com/Azure-Samples/ApplicationInsights-Java-Samples/blob/main/advanced/migration-3x/src/main/java/com/example/ExampleWebTelemetryModule.java )

**Comment by heyams** [comment]
Trask is OOF.

No, sampling override can't be done programmatically.

Thanks,
Helen
________________________________

**Comment by balaji2796** [comment]
thanks for the update

**Comment by heyams** [comment]
is it ok to close this issue? @balaji2796
