### ISSUE TITLE
ApplicationInsights Java Agent discards logs

### ISSUE THREAD

**Issue by lehnert-andre** [microsoft/ApplicationInsights-Java#3207]
### Expected behavior

Azure ApplicationInsights for Java can handle all generated logs and all logs are available in the Azure Monitor.

### Actual behavior

The Java Agent permanently discards application logs as soon as the App Service is used intensively.
In particular, error messages or Java stack traces are not logged.

Current workload is ~ 1M AppTraces logs per day.

### To Reproduce

applicationinsights.json

```
{
  "role": {
    "name": "Wildfly"
  },
  "heartbeat": {
    "intervalSeconds": 60
  },
  "instrumentation": {
    "logging": {
      "level": "TRACE"
    },
    "jdbc": {
      "masking": {
        "enabled": false
      }
    }
  },
  "jmxMetrics": [
    {
      "name": "numberOfCommittedTransactions",
      "objectName": "jboss.as:subsystem=transactions",
      "attribute": "numberOfCommittedTransactions"
    },
    {
      "name": "numberOfApplicationRollbacks",
      "objectName": "jboss.as:subsystem=transactions",
      "attribute": "numberOfApplicationRollbacks"
    },
    {
      "name": "numberOfAbortedTransactions",
      "objectName": "jboss.as:subsystem=transactions",
      "attribute": "numberOfAbortedTransactions"
    },
    {
      "name": "numberOfTimedOutTransactions",
      "objectName": "jboss.as:subsystem=transactions",
      "attribute": "numberOfTimedOutTransactions"
    },
    {
      "name": "numberOfTransactions",
      "objectName": "jboss.as:subsystem=transactions",
      "attribute": "numberOfTransactions"
    },
    {
      "name": "averageCommitTime",
      "objectName": "jboss.as:subsystem=transactions",
      "attribute": "averageCommitTime"
    },
    {
      "name": "CpuLoad",
      "objectName": "java.lang:type=OperatingSystem",
      "attribute": "CpuLoad"
    },
    {
      "name": "SystemCpuLoad",
      "objectName": "java.lang:type=OperatingSystem",
      "attribute": "SystemCpuLoad"
    },
    {
      "name": "TotalMemorySize",
      "objectName": "java.lang:type=OperatingSystem",
      "attribute": "TotalMemorySize"
    },
    {
      "name": "FreeMemorySize",
      "objectName": "java.lang:type=OperatingSystem",
      "attribute": "FreeMemorySize"
    },
    {
      "name": "ThreadCount",
      "objectName": "java.lang:type=Threading",
      "attribute": "ThreadCount"
    }
  ],
  "preview": {
    "captureLogbackMarker": true,
    "captureLogbackCodeAttributes": false,
    "captureLoggingLevelAsCustomDimension": true
  }
}
```

Dockerfile

```
ENV APPLICATIONINSIGHTS_CONNECTION_STRING=""
ENV APPLICATIONINSIGHTS_CONFIGURATION_FILE="${JBOSS_HOME}/standalone/applicationinsights.json"
ENV APPLICATIONINSIGHTS_ROLE_INSTANCE="LOCAL"
...
COPY applicationinsights-agent-3.4.10.jar ${JBOSS_HOME}/standalone/applicationinsights-agent-3.4.10.jar
RUN chmod -R gu+x ${JBOSS_HOME}/standalone/applicationinsights-agent-3.4.10.jar
```

Wildfly JAVA_OPTS 

```
JAVA_OPTS="$JAVA_OPTS -javaagent:$JBOSS_HOME/standalone/applicationinsights-agent-3.4.10.jar"
```

### System information
Please provide the following information:
 - SDK Version: applicationinsights-agent-3.4.10.jar
 - OS type and version: AppService PremiumV3 (P2v3) with Docker image (Docker base image eclipse-temurin:17-alpine)
 - Application Server type and version (if applicable): Wildfly 28.0.1.Final
 - Using spring-boot? No
 - Additional relevant libraries (with version, if applicable):
   logback: 1.4.5
   slf4j: 2.0.7

### Logs

AppServiceConsoleLogs

```
2023-07-19 09:47:31,410 INFO [stdout] 2023-07-19 09:47:31.410+02:00 WARN c.a.m.o.e.i.l.LocalFileWriter - In the last 5 minutes, the following operation has failed 6 times (out of 14): Writing telemetry to disk (telemetry is discarded on failure):
2023-07-19 09:47:31,411 INFO [stdout] * Local persistent storage capacity has been reached. It's currently at (51207KB). Telemetry will be lost. (6 times)
```

### Screenshots

<img width="2014" alt="Screenshot 2023-07-19 at 14 02 52" src="https://github.com/microsoft/ApplicationInsights-Java/assets/41591268/358bfc54-93c8-45aa-bbdb-7cc9cecf5fda">

Table contents (for 3 App Services and 30 days retention time)

```
union withsource=["$TableName"] *
| summarize Count=count() by TableName=["$TableName"]
| where TableName in ("AppTraces", "AppDependencies", "AppMetrics", "AppExceptions")

AppExceptions 6714
AppMetrics 2673979
AppDependencies 20548897
AppTraces 87730887
```

**Comment by trask** [comment]
Hi @lehnert-andre! Can you post your applicationinsights.log file so we can see the additional details around the failures?

**Comment by lehnert-andre** [comment]
Hi @trask,

we do not have access to the running App Service.

Access via SSH (https://appsvc-XXXXX.scm.azurewebsites.net/webssh/host)
or FTP/S is not possible. 
The Azure infrastructure is managed by the platform team of our customer.

We just have the console logs and the ApplicationInsights logs...

**Comment by trask** [comment]
hi @lehnert-andre!

I missed this above:

> 2023-07-19 09:47:31,410 INFO [stdout] 2023-07-19 09:47:31.410+02:00 WARN c.a.m.o.e.i.l.LocalFileWriter - In the last 5 minutes, the following operation has failed 6 times (out of 14): Writing telemetry to disk (telemetry is discarded on failure):
2023-07-19 09:47:31,411 INFO [stdout] * Local persistent storage capacity has been reached. It's currently at (51207KB). Telemetry will be lost. (6 times)

unfortunately this log is not showing us the underlying reason why the initial attempt to send the telemetry to the ingestion service failed.

we're making improvements to the logging in https://github.com/Azure/azure-sdk-for-java/pull/36064 which should give us this info

this should make it into next month's release.

in the meantime, you could try increasing the disk storage limit: https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#recovery-from-ingestion-failures

which may smooth things out enough to not lose telemetry, until we can see the underlying reason for those (many) sporadic ingestion failures

**Comment by lehnert-andre** [comment]
Hi @trask 

we will change the disk storage limit and update the Java Agent.

Thank you!

**Comment by trask** [comment]
great, feel free to re-open if you continue running into issues
