### ISSUE TITLE
Telemetry processor documentation is missing documentation about mask action in attribute processor

### ISSUE THREAD

**Issue by manishtulsiani** [microsoft/ApplicationInsights-Java#3210]
### Expected behavior
Telemetry processor document should mention mask action in attribute processor with usage and example similar to other actions described [here](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-telemetry-processors#attribute-processor)

Mask action was introduced in [this](https://github.com/microsoft/ApplicationInsights-Java/pull/1977) pr and can be seen in the code [here](https://github.com/microsoft/ApplicationInsights-Java/blob/f3e3b7280d9068271c590b25011d698c8ddf2e69/agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/processors/AttributeProcessor.java#L73)

Document should be updated so that the feature is known and can be used by others, I stumbled upon it accidentally while browsing something else in the code but it was exactly what we wanted.

### Actual behavior
Documentation missing about mask action. Telemetry processor [document](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-telemetry-processors#attribute-processor) mentions only insert, update, delete, hash, extract
### To Reproduce
N/A
### System information
Please provide the following information:
 - SDK Version: 3.4.x
 - OS type and version: Linux
 - Application Server type and version (if applicable): N/A
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable):

### Logs
N/A

### Screenshots
Screenshot from documentation showing mask action is not documented
![image](https://github.com/microsoft/ApplicationInsights-Java/assets/17932316/13153a51-0d1d-4335-b94e-0dbfeced7064)

**Comment by jeanbisutti** [comment]
@manishtulsiani 
We have reworked on this feature in the Application Insights Java 3.4.16 release. The documentation is here: https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-telemetry-processors#mask

**Comment by manishtulsiani** [comment]
Thanks @jeanbisutti , there are minor typos in the document but otherwise it is fine, I think the issue can be closed.

group spelled as gorup and mask with uppercase k

![image](https://github.com/microsoft/ApplicationInsights-Java/assets/17932316/ddba2504-ba8a-477d-a017-c9832fd02349)

**Comment by trask** [comment]
> group spelled as gorup and mask with uppercase k

thanks @manishtulsiani! we've fixed these
