### ISSUE TITLE
In Java agent 3.4.14, warning is shown in console when we attach the app insights

### ISSUE THREAD

**Issue by balaji2796** [microsoft/ApplicationInsights-Java#3242]
using applicationinsights-runtime-attach 3.4.14

getting the console warning when spring boot 3.X application starts 

OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

**Comment by trask** [comment]
hi @balaji2796! this warning is expected, because Application Insights Java appends some classes to the bootstrap classpath
