### ISSUE TITLE
Env resolution is not working with applicationinsights-runtime-attach

### ISSUE THREAD

**Issue by if-of** [microsoft/ApplicationInsights-Java#3250]
### Expected behavior
Environment variable placeholders are resolved in applicationinsights.json file when runtime attach is used.

### Actual behavior
In [documentation ](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#custom-dimensions) mentioned that I can use placeholders for env variables.

applicationinsights-runtime-attach is used.

But when I tried to add authentication to applicationsnsights.json file with env variable, it failed with [CredentialUnavailableException ](https://learn.microsoft.com/en-us/azure/azure-monitor/app/azure-ad-authentication?tabs=java#credentialunavailableexception)

    "authentication": {
      "enabled": true,
      "type": "UAMI",
      "clientId": "${APPLICATIONINSIGHTS_CLIENT_ID}"
    },

However, when I replaced env variable with actual value it worked.

    "authentication": {
      "enabled": true,
      "type": "UAMI",
      "clientId": "00000000-0000-0000-0000-00000000"
    },

### System information
Please provide the following information:
 - SDK Version: 3.4.14
 - OS type and version: Alpine Linux
 - Application Server type and version (if applicable):
 - Using spring-boot: 3.1.1
 - Additional relevant libraries (with version, if applicable):
   - com.microsoft.azure:applicationinsights-runtime-attach:3.4.14
   - com.microsoft.azure:applicationinsights-agent:3.4.14

**Comment by trask** [comment]
hi @if-of! just checking that you meant to close this, and that you were able to get things working?

**Comment by if-of** [comment]
@trask 
Hi, thanks for asking, we've chosen to programmatically replace all the placeholders in the configuration and then pass this updated configuration as an environment variable APPLICATIONINSIGHTS_CONFIGURATION_FILE. It doesn't look pretty, but work
