### ISSUE TITLE
EventHubs process span reporting failure with no underlying failed events

### ISSUE THREAD

**Issue by bradooles** [microsoft/ApplicationInsights-Java#3303]
### Expected behavior
EventHub spans are represented with successful or failed events in Application Insights. If span is failed then failed events should be highlighted (and conversely if there are no failed events then span should report success=true).

### Actual behavior
EventHub process span is reporting as failure (and is counted as a failure in the Application Insights portal) but the events underneath appear to be successful

### To Reproduce
This behavior occurring in Azure within kubernetes service with a downstream EventHub + blob storage.

We have a service which sets up an EventProcessorClient bean using EventProcessorClientBuilder() and attaches a checkpointstore as part of its setup. In the screen attached the events underneath the overall span appear to be successful including the Blobstorage events. The Eventhubs.Process reports "Success": false.  The 'process' request with a response of '0' does a have "Successful request" property which equals 'true' in app insights.

Using agent 3.4.16 with the following libs:
\<dependency>
	\<groupId>com.azure\</groupId>
	\<artifactId>azure-messaging-eventhubs\</artifactId>
        \<version>5.15.8\</version>
\</dependency>

\<dependency>
	\<groupId>com.azure\</groupId>
	\<artifactId>azure-messaging-eventhubs-checkpointstore-blob\</artifactId>
        \<version>1.16.9\</version>
\</dependency>

### System information
Please provide the following information:
 - SDK Version: **3.4.16**
 - OS type and version: **Alpine 3.18**
 - Using spring-boot? **Yes**
 - Additional relevant libraries (with version, if applicable):
azure-messaging-eventhubs: 5.15.8
azure-messaging-eventhubs-checkpointstore-blob:1.16.9

Issue didn't occur in our previous agent version (3.4.12) however it looks like the EventHub.process span wasn't being generated in that version of the agent - Potentially related to https://github.com/microsoft/ApplicationInsights-Java/issues/3084

### Logs
Logs can be provided if required, let us know which ones which ones you would want to inspect

### Screenshots
![image](https://github.com/microsoft/ApplicationInsights-Java/assets/9922670/42b7fbc0-39b9-49a9-9170-e413ca7ba70b)

**Comment by jeanbisutti** [comment]
@bradooles Could you please provide a minimal example reproducing the issue by creating a PR on [this repo](https://github.com/microsoft/ApplicationInsights-Java-Repros)?

**Comment by lmolkova** [comment]
@bradooles thanks for reporting this!

The issue was in the `azure-messaging-eventhubs` SDK and was [fixed](https://github.com/Azure/azure-sdk-for-java/pull/33600) in version 5.16.0 (stable one released a few hours ago). We plan to release the new BOM that includes it sometime this week.

I could repro the issue with `5.15.8`, but `5.16.0` works fine:

<img width="1090" alt="image" src="https://github.com/microsoft/ApplicationInsights-Java/assets/2347409/b738c012-7434-4eda-bc29-9d75341b8db0">

Sorry for the inconvenience.

**Comment by bradooles** [comment]
@lmolkova thanks for letting us know - we tested with the updated azure-messaging-eventhubs 5.16.0 version and it now looks like as we expect with successful EventHubs.process transactions :)

I'll close the ticket out

**Comment by azizabah** [comment]
@lmolkova - Is there any update on getting the new BOM rolled out with the fixed versions managed in it? Looking at this dependency - com.azure.spring:spring-cloud-azure-dependencies

**Comment by trask** [comment]
hi @azizabah, if you're still not seeing it in the bom, can you open a new issue about it? that way it can get routed to the right folks, thx

**Comment by azizabah** [comment]
@trask - Looks like it's out there. Thanks for the ping.
