### ISSUE TITLE
Missing telemetry for LogBook events

### ISSUE THREAD

**Issue by wildthing81** [microsoft/ApplicationInsights-Java#3309]
### Expected behavior
Application Insights request telemetry should display trace events for logs created by `https://github.com/zalando/logbook` 

### Actual behavior
Application Insights request telemetry more often than not, drops trace events for these logs

### System information
Please provide the following information:
 - applicationinsights-agent-3.4.11.jar:
 - Spring boot 2.7.3/ Java 17 application running on AKS
 - https://github.com/zalando/logbook

Log Analytics for Azure Kubernetes service confirms  application is printing Client request/application response 
The AppInsights portal which ingests application telemetry ( log statements, incoming/outgoing http requests etc) via the agent process running with the application is not showing the same logs ( the correlation-id in LogBook logs is configured to be same as operationId  in AppInsights request telemetry)

**Comment by trask** [comment]
hi @wildthing81! can you put together a small repro that we can use to troubleshoot the issue you're seeing?
