### ISSUE TITLE
Connection string overrides syntax causes Unrecognized field "connectionStringOverrides" configuration error

### ISSUE THREAD

**Issue by shayne-marriage-scp** [microsoft/ApplicationInsights-Java#3348]
### Expected behavior
Adding the [Connection string overrides (preview)](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#connection-string-overrides-preview) works as documented.

### Actual behavior
The error below is logged.
023-10-18 13:57:21.612-05:00 WARN  c.m.a.a.i.c.ConfigurationBuilder - Unrecognized field "connectionStringOverrides" (class com.microsoft.applicationinsights.agent.internal.configuration.Configuration), not marked as ignorable (15 known properties: "selfDiagnostics", "sampling", "preview", "metricIntervalSeconds", "jmxMetrics", "connectionString", "instrumentationSettings", "role", "connectionStringConfiguredAtRuntime", "heartbeat", "internal", "customDimensions", "instrumentation", "authentication", "proxy"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: com.microsoft.applicationinsights.agent.internal.configuration.Configuration["connectionStringOverrides"])
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "connectionStringOverrides" (class com.microsoft.applicationinsights.agent.internal.configuration.Configuration), not marked as ignorable (15 known properties: "selfDiagnostics", "sampling", "preview", "metricIntervalSeconds", "jmxMetrics", "connectionString", "instrumentationSettings", "role", "connectionStringConfiguredAtRuntime", "heartbeat", "internal", "customDimensions", "instrumentation", "authentication", "proxy"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: com.microsoft.applicationinsights.agent.internal.configuration.Configuration["connectionStringOverrides"])

See attached log [applicationinsights.log](https://github.com/microsoft/ApplicationInsights-Java/files/13034406/applicationinsights.log)

### To Reproduce

1. Add real connection strings to the attached [applicationinsights.json](https://github.com/microsoft/ApplicationInsights-Java/files/13034353/applicationinsights.json) configuration file, then place it in the same directory as applicationinsights-agent-3.4.17.jar. In my case it's /usr/share/java/.
2. Add the -javaagent:/usr/share/java/applicationinsights-agent-3.4.17.jar to JAVA_OPTS in tomcat.conf.
3. Restart Tomcat and check the logs.

[applicationinsights.json](https://github.com/microsoft/ApplicationInsights-Java/files/13034353/applicationinsights.json)

### System information
Please provide the following information:
 - SDK Version: 3.4.17
 - OS type and version: Rocky Linux 8.8
 - Application Server type and version (if applicable): Apache Tomcat 9.0.62
 - Using spring-boot? No
 - Additional relevant libraries (with version, if applicable): None

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

**Comment by heyams** [comment]
@shayne-marriage-scp your json seems correct to me except a typo (screenshot). However, 

 _**Unrecognized field "connectionStringOverrides"**_ 
this log implies that "connectionStringOverrides" was at the top-level (not under "preview"). please double check your applicationinsights.json that is actually picked up by Java agent.

![image](https://github.com/microsoft/ApplicationInsights-Java/assets/56097766/bf81bfd2-d2ca-43fd-82d6-a5d21d3453d1)
