### ISSUE TITLE
Query for next expected version of applicationinsights-agent

### ISSUE THREAD

**Issue by pratyusha0912** [microsoft/ApplicationInsights-Java#3353]
Microsoft has added latest version of io.netty:netty-codec-http2 library 4.1.99.Final to 4.1.100.Final on 11th oct 2023 but latest version of application insights 3.4.17 is released on 19th sept 2023. So we need next  version of appinsights to update netty version. When can we expect the next version of appinsights-agent jar

**Comment by heyams** [comment]
@pratyusha0912 Sometime next week. We're waiting for a dependency to be released from azure-sdk side. Our release is currently blocked because of it.

**Comment by heyams** [comment]
@pratyusha0912 [3.4.18](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.4.18) was released yesterday.
