### ISSUE TITLE
Eventgrid Telemetry Correlation

### ISSUE THREAD

**Issue by wslaghekke** [microsoft/ApplicationInsights-Java#3361]
**Is your feature request related to a problem? Please describe.**
I have two services that exchange messages through eventgrid. To be able to trace requests better i would like to have the requests through EventGrid be correlated.

**Describe the solution you would like**
I would like the child-request to be shown in Application Insights on the end-to-end transaction details of a request.

**Describe alternatives you have considered**
I've tried to get it working by injecting traceparent and tracestate fields in my eventgrid event-data through the W3CTraceContextPropagator and configuring Eventgrid to send those fields to the child-service (which uses webhooks) in the headers traceparent and tracestate. 
That however does not make the child-request appear, how do i correlate dependencies manually (or how do i make automatic correlation function if available)?

The adding of data is done using the following code:

```kotlin
abstract class AbstractEventData: EventData {
    var traceparent: String? = null
    var tracestate: String? = null

    override fun asAzureEventGridEvent(): EventGridEvent {
        // Inject 'traceparent' and 'tracestate' into the event data before sending it to Event Grid
        W3CTraceContextPropagator.getInstance().inject(
            Context.current(),
            this,
            EVENT_GRID_SETTER
        )
        return super.asAzureEventGridEvent()
    }

    companion object {
        private val EVENT_GRID_SETTER: TextMapSetter<AbstractEventData> = TextMapSetter<AbstractEventData> { carrier, key, value ->
            if (carrier === null) {
                // Noop
            } else if ("traceparent" == key) {
                carrier.traceparent = value
            } else if ("tracestate" == key) {
                carrier.tracestate = value
            }
        }
    }
}
```

**Additional context**
Screenshot of the inproc dep in end-to-end 
![Screenshot from 2023-10-28 16-52-35](https://github.com/microsoft/ApplicationInsights-Java/assets/617558/61f2a4b4-2386-4ee2-9aaf-5b4e754100dd)

**Comment by jeanbisutti** [comment]
Hi @wslaghekke,

Are you using [Azure Event Grid client library for Java](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventgrid/azure-messaging-eventgrid/README.md#azure-event-grid-client-library-for-java) with the Application Insights Java agent?

**Comment by wslaghekke** [comment]
@jeanbisutti Yes i am using that, i saw that there was some instrumentation code related to eventgrid but it only works for the cloudEvent type of events and i use the EventGrid schema which is why i added custom fields manually

**Comment by jeanbisutti** [comment]
@wslaghekke Sorry for the delay. Can you please look at [this blog post](https://devblogs.microsoft.com/azure-sdk/distributed-tracing-with-azure-functions-event-grid-triggers/) (Java examples are in the end)?

**Comment by wslaghekke** [comment]
@jeanbisutti Thank you, after implementing the span code as specified by that article it works.
