### ISSUE TITLE
Telemetry processors bug

### ISSUE THREAD

**Issue by ivan-zaitsev** [microsoft/ApplicationInsights-Java#3378]
### Expected behavior
Include filter with non-string value should be correctly applied.

### Actual behavior
Currently only string filter fields are supported. 

### To Reproduce

Create such applicationinsights.json file:
```
{
    "preview": {
        "processors": [
            {
                "type": "attribute",
                "include": {
                    "matchType": "regexp",
                    "attributes": [
                        {
                            "key": "http.status_code",
                            "value": 400
                        }
                    ]
                },
                "actions": [
                    {
                        "action": "insert",
                        "key": "key",
                        "value": "value"
                    }
                ]
            }
        ]
    }
}
```

As "http.status_code" is not a string key (`AttributeKey.stringKey`) but rather long (`AttributeKey.longKey`), it will not be resolved, and this code will return null instead of actual value.

https://github.com/microsoft/ApplicationInsights-Java/blob/547ec61e8cfe8b7dbe77de73c8c53d51c03377f5/agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/processors/AgentProcessor.java#L88

Same for regexp:

https://github.com/microsoft/ApplicationInsights-Java/blob/547ec61e8cfe8b7dbe77de73c8c53d51c03377f5/agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/processors/AgentProcessor.java#L126

https://github.com/microsoft/ApplicationInsights-Java/blob/547ec61e8cfe8b7dbe77de73c8c53d51c03377f5/agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/processors/AgentProcessor.java#L179

**Comment by heyams** [comment]
@ivan-zaitsev I tested it using non-String type value, it works for me though.

```json

"preview": {
  "processors": [
    {
      "type": "attribute",
      "actions": [
        {
          "key": "attribute1",
          "value": 1,
          "action": "insert"
        },
        {
          "key": "attribute2",
          "value": "testValue2",
          "action": "insert"
        },
        {
          "key": "sensitiveAttribute1",
          "value": "sensitiveData1",
          "action": "insert"
        }
      ]
    }
  ]
}

```

this is the payload sent to Application Insights:

```json

{
  "ver": 1,
  "name": "Message",
  "time": "2023-11-15T20:25:29.382Z",
  "iKey": "00000000-0000-0000-0000-0FEEDDADBEEF",
  "tags": {
    "ai.internal.sdkVersion": "java:3.4.19-SNAPSHOT",
    "ai.cloud.roleInstance": "testroleinstance",
    "ai.cloud.role": "testrolename"
  },
  "data": {
    "baseType": "MessageData",
    "baseData": {
      "ver": 2,
      "message": "1::testValue2",
      "severityLevel": "Information",
      "properties": {
        "LoggerName": "org.apache.catalina.startup.VersionLoggerListener",
        "SourceType": "Logger",
        "attribute1": "1",
        "ThreadName": "main",
        "attribute2": "testValue2",
        "sensitiveAttribute1": "redacted"
      }
    }
  }
}
```

**Comment by heyams** [comment]
Please try to use the latest version of Java Version. Alternatively, you can submit a repro app at https://github.com/microsoft/ApplicationInsights-Java-Repros.

**Comment by ivan-zaitsev** [comment]
@heyams 

I am talking not about actions, but about "include" filters.

                "include": {
                    "matchType": "regexp",
                    "attributes": [
                        {
                            "key": "http.status_code",
                            "value": 400
                        }
                    ]
                },

**Comment by ivan-zaitsev** [comment]
@heyams 

Example:

Suppose that there is a span with such attributes:

```
{
  "data": {
    "baseType": "MessageData",
    "baseData": {
      "ver": 2,
      "message": "1::testValue2",
      "severityLevel": "Information",
      "properties": {
        "LoggerName": "org.apache.catalina.startup.VersionLoggerListener",
        "SourceType": "Logger",
        "attributeInteger": 1,
        "attributeBool": false,
      }
    }
  }
}
```

You want to insert a new attribute if an existing attribute with key "attributeInteger" and value 1 exist.
For this you will use such config:

```
{
    "preview": {
        "processors": [
            {
                "type": "attribute",
                "include": {
                    "matchType": "strict",
                    "attributes": [
                        {
                            "key": "attributeInteger",
                            "value": 1
                        }
                    ]
                },
                "actions": [
                    {
                        "action": "insert",
                        "key": "newAttribute",
                        "value": "newAttributeValue"
                    }
                ]
            }
        ]
    }
}
```

But it will not work, because "attributeInteger" will be retrieved as a AttributeKey.stringKey in AgentProcessor instead of AttributeKey.longKey.

**Comment by heyams** [comment]
@ivan-zaitsev i tested include and it seems to be working.  Please submit a repro app to help me further investigate.

```json
"preview": {
  "processors": [
    {
      "type": "attribute",
      "actions": [
        {
          "key": "attribute1",
          "value": 1,
          "action": "insert"
        }
      ],
      "id": "attributes/insert"
    },
    {
      "type": "attribute",
      "include": {
        "matchType": "strict",
        "attributes": [
          {
            "key": "attribute1",
            "value": 1
          }
        ]
      },
      "actions": [
        {
          "key": "myNewAttributeKey",
          "value": "myNewAttributeValue",
          "action": "insert"
        }
      ],
      "id": "attributes/myNewAttributeValue"
    }
  ]
}

```

log sent to application insights:
```json
{
  "ver": 1,
  "name": "Message",
  "time": "2023-11-15T21:17:59.755Z",
  "iKey": "00000000-0000-0000-0000-0FEEDDADBEEF",
  "tags": {
    "ai.internal.sdkVersion": "java:3.4.19-SNAPSHOT",
    "ai.operation.id": "ea8260e295ca98e19912078d290931dc",
    "ai.cloud.roleInstance": "testroleinstance",
    "ai.operation.name": "GET /TelemetryProcessors/test",
    "ai.cloud.role": "testrolename",
  },
  "data": {
    "baseType": "MessageData",
    "baseData": {
      "ver": 2,
      "message": "1::testValue2",
      "severityLevel": "Information",
      "properties": {
        "LoggerName": "smoketestappcontroller",
        "SourceType": "Logger",
        **"attribute1": "1",**
        "ThreadName": "http-nio-8080-exec-2",
        "attribute2": "testValue2",
        **"myNewAttributeKey": "myNewAttributeValue"**
      }
    }
  }
}
```

**Comment by ivan-zaitsev** [comment]
@heyams 

In your example attribute `attribute1` contains value `"1"` as a String, but if you change it to Integer `1` it will not work.

**Comment by heyams** [comment]
@ivan-zaitsev yes, i will give you a snapshot to try. I think I understand your issue now.

**Comment by ivan-zaitsev** [comment]
@heyams 

I only mentioned Integer case, but actually the value can be any type (boolean, double, long, string)
https://javadoc.io/static/io.opentelemetry/opentelemetry-api/0.16.0/io/opentelemetry/api/common/AttributeKey.html

**Comment by ivan-zaitsev** [comment]
Also, could you please update the documentation if the feature with non-string telemetry processor attributes will be implemented. https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-telemetry-processors

**Comment by heyams** [comment]
@ivan-zaitsev Sorry, I was out of office last week. 
Yes, it will support all the data type you mentioned. I will update the doc when we are ready to release it in 3.4.19.

**Comment by heyams** [comment]
@ivan-zaitsev can you try this [snapshot](https://github.com/microsoft/ApplicationInsights-Java/suites/18543831332/artifacts/1076707896) and let me know the result?

**Comment by ivan-zaitsev** [comment]
@heyams 

Hello, the first processor with "strict" type is working, but the second one with regexp is not. In case of range conditions like status codes it will be really convenient to support regexp. 

```
{
  "sampling" : {
    "percentage" : 100
  },
  "preview" : {
    "processors": [
      {
        "id" : "processors/attribute/strict",
        "type": "attribute",
        "include": {
          "matchType": "strict",
          "attributes": [
            {
              "type": "long",
              "key": "http.status_code",
              "value": "400"
            }
          ]
        },
        "actions": [
          {
            "action": "insert",
            "key": "strictKey",
            "value": "strictValue"
          }
        ]
      },
      {
        "id" : "processors/attribute/regexp",
        "type": "attribute",
        "include": {
          "matchType": "regexp",
          "attributes": [
            {
              "type": "long",
              "key": "http.status_code",
              "value": "(40[0-9]|4[1-9][0-9])"  --- all 4xx errors, from 400 to 499
            }
          ]
        },
        "actions": [
          {
            "action": "insert",
            "key": "regexpKey",
            "value": "regexpValue"
          }
        ]
      }
    ]
  }
}

```

**Comment by heyams** [comment]
@ivan-zaitsev please try out this new [snapshot](https://github.com/microsoft/ApplicationInsights-Java/suites/18607687885/artifacts/1081551907). it supports regex now.

**Comment by ivan-zaitsev** [comment]
@ivan-zaitsev This one works both for strict and regexp.

**Comment by ivan-zaitsev** [comment]
@heyams
Can you also please take a look at https://github.com/microsoft/ApplicationInsights-Java/issues/3375
This issue also in the same area. It is about adding filtering not only on span attributes, but also on span events. Sometimes span can have events instead of attributes and it is not possible to control such spans.
