### ISSUE TITLE
Browser version shows incorrect version

### ISSUE THREAD

**Issue by megachan** [Microsoft/ApplicationInsights-Java#339]
We have this
`"User-Agent": "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3)",`
in our request header. It is IE 9 however AI shows chrome 50 in Browser version.

**Comment by debugthings** [comment]
@Dmitry-Matveev I don't think there is enough information on this bug to do anything. I think it should be closed for a couple of reasons, most importantly this looks to be a problem with the AI portal and not the Java SDK.

**Comment by beckylino** [comment]
@megachan as noted by @debugthings, could you provide more information to help us better understand your issue?

**Comment by dhaval24** [comment]
@megachan we haven't seen this issue on the latest releases of SDK for a while. If you had a chance to try one of our latest SDK and have not seen the issue we would like to close this off.

**Comment by dhaval24** [comment]
@megachan please update to the latest SDK version 1.0.10. This issue doesn't occur anymore, please reopen if the problem persists.
