### ISSUE TITLE
Not able to see application insight data for my sample java application

### ISSUE THREAD

**Issue by arroyc** [Microsoft/ApplicationInsights-Java#340]
I'm using a "hello world" type java application to send some data to application insight, but not able to see any thing so far. I have followed the instructions so far. Created app insight resource in azure portal, used that instrumentaion key in my application, kept the applicationinsight

http://stackoverflow.com/questions/40323534/not-able-to-see-application-insight-data-for-my-sample-java-application-failed

**Comment by OriYosefiMSFT** [comment]
You mentioned you're using Fiddler. Can you please let us know if you see traffic going out to https://dc.services.visualstudio.com/v2/track ? 
Also, Can you please also add a "Sleep" after the flush to make sure the network traffic gets sent before the program exits? 
thanks.

**Comment by arroyc** [comment]
I'm not seeing anything in fiddler traffic, I made sure fiddler is capturing other Java outbound traffic (like google.com). No  luck so far. Strange thing is it doesn't throw any exception. Also I want to know for application insight java sdk do you store the telemetry files somewhere like in %APPDATA%/local/ or somewhere? When I used .net, I can see the telemetry files there

**Comment by arroyc** [comment]
@OriYosefiMSFT , after doing some magic with fiddler and java config I was finally able to get some outbound traffic 

> Request Summary

`#	Result	Protocol	Host	URL	Body	Caching	Content-Type	Process	Comments	Custom	
67	200	HTTPS	dc.services.visualstudio.com	/v2/track	49		application/json; charset=utf-8	java:2944			
`
>Request
`{"ver":1,"name":"Microsoft.ApplicationInsights.Event","time":"2016-10-31T13:18:05.589-0700","sampleRate":100.0,"iKey":"3aa27b91-92fd-4d2d-be8a-0ca67c842560","flags":0,"tags":{"ai.internal.sdkVersion":"java:1.0.6","ai.device.id":"MININT-38TTG82.redmond.corp.microsoft.com","ai.device.locale":"en-US","ai.device.os":"Windows 10","ai.device.roleInstance":"MININT-38TTG82.redmond.corp.microsoft.com","ai.device.osVersion":"Windows 10"},"data":{"baseType":"EventData","baseData":{"ver":2,"name":"WinGame1","properties":{"Game":"GameName","Difficulty":"hard","DeveloperMode":"true"},"measurements":null}}}`
>Response
`{"itemsReceived":1,"itemsAccepted":1,"errors":[]}`

**Comment by arroyc** [comment]
It works, there was a confusion, I was sending custom events but from the portal I was looking for request events so I was not seeing anything. It's working absolutely fine for me. As I said I'm new to app insight so the UI made me little confused. Thanks all for the help
