### ISSUE TITLE
General Availability target for sampling overrides

### ISSUE THREAD

**Issue by dcbrown16** [microsoft/ApplicationInsights-Java#3433]
The sampling override feature for Application Insights for Java is in preview as of December 2023.
https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-sampling-overrides

Please keep us informed of the target for general availability and any changes we may need to make to switch to the GA version if currently using the preview version. Thanks!

**Comment by heyams** [comment]
@dcbrown16 will do. We plan to GA sampling overrides in December's release. There might be some delay due to holidays and vacation around this time of the year. I will keep you informed though. Thanks!

**Comment by heyams** [comment]
Just want to let you know that 3.5 GA will happen in January 2024 with OpenTelemetry 2.0 (will be released by the end of December 2023 if no delay). We will have a release in December for 3.4.19, but it won't have the sampling overrides GA. 
@dcbrown16

**Comment by dcbrown16** [comment]
Hi @heyams , is there any info at this point about what changes we might need to make to use the GA version if currently using the preview version of sampling overrides? Thanks!

**Comment by heyams** [comment]
@dcbrown16 the only change is the json layout:

preview prior to 3.5 GA: 

```json
"preview": {
    "sampling": {
      "overrides": [
        {YOUR SAMPLING OVERRIDES}
     ]
   }
}
```

3.5+ GA:

```json
"sampling": {
    "overrides": [
      {YOUR SAMPLING OVERRIDES}
   ]
 }
```

If your customer continues to use the deprecated preview json config, it will continue to work when they upgrade to 3.5 GA later. We support backward compatibility.

**Comment by heyams** [comment]
@dcbrown16 I need to correct my early response. 

We'll support the stable HTTP semconv in 3.5 GA, which contains lots of breaking changes that will affect existing sampling overrides. But we'll support backward compatibility using the old attribute keys.
