### ISSUE TITLE
Classic SDK TelemetryClient not capturing any data

### ISSUE THREAD

**Issue by sethcrichton** [microsoft/ApplicationInsights-Java#3441]
### Expected behavior
We migrated from an older version of the SDK (2.6.4).  Earlier version allowed us to configure the client at runtime by using the TelemetryConfiguration class to specify the Instrumentation Key.

We have upgraded to version 3.4.18, and none of our various attempts to configure the client and capture telemetry are working.

### Actual behavior
No telemetry is being captured.

### To Reproduce

- Set connection string via APPLICATIONINSIGHTS_CONNECTION_STRING environment variable
- Set connection string at runtime using com.microsoft.applicationinsights.connectionstring.ConnectionString class and setting `"connectionStringConfiguredAtRuntime": true` in configuration

### System information
Please provide the following information:
 - SDK Version: 3.4.18
 - OS type and version: Docker image (groovy:4.0-jdk17)
 - Using spring-boot? No

**Comment by heyams** [comment]
can you check out this doc: https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#connection-string-configured-at-runtime?

**Comment by sethcrichton** [comment]
Yes, please see the second bullet in the "steps to reproduce" above.  

However, perhaps we have misunderstood those instructions, as they appear to align with the previous 2.6.x approach where `applicationinsights-core` is added as a dependency -- is that library by itself sufficient or does this approach still require that the agent is installed and running/configured?

**Comment by heyams** [comment]
here is our guide on how to upgrade from legacy sdk to 3.x agent. https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-upgrade-from-2x

yes, you need 3.4.18 agent in order to use `applicationinsights-core`. please don't use 2.x approach anymore.
