### ISSUE TITLE
Error when using `TelemetryClient.trackSessionState`

### ISSUE THREAD

**Issue by tobiasdiez** [Microsoft/ApplicationInsights-Java#347]
The code
````java
        telemetryClient = new TelemetryClient();
        telemetryClient.trackSessionState(SessionState.Start);
        telemetryClient.trackEvent("TestEvent");
        telemetryClient.trackSessionState(SessionState.End);
````
results in two identical errors
> Failed to send, Bad request  : {"itemsReceived":1,"itemsAccepted":0,"errors":[{"index":0,"statusCode":400,"message":"Unknown domain type 'Microsoft.ApplicationInsights.SessionStateData'"}]}

The session is not tracked in the online portal but the custom event "TestEvent" shows up (thus the connection works in principle). How can I track session start and end?

**Comment by Dmitry-Matveev** [comment]
trackSessionState() is going to be removed from the upcoming version of the API.
Currently, only HockeyApp SDK supports SessionState, Java SDK and .NET SDK cannot successfully submit this telemetry type. It was already removed from [TelemetryClient](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/Core/Managed/Shared/TelemetryClient.cs) in .NET SDK.

To workaround this limitation one can submit a metric with the duration of the session and plot it in AI.
