### ISSUE TITLE
Enable filter in log4j ApplicationInsightsAppender

### ISSUE THREAD

**Issue by tobiasdiez** [Microsoft/ApplicationInsights-Java#348]
The configuration 
````xml
<ApplicationInsightsAppender name="applicationInsightsAppender">
   <ThresholdFilter level="ERROR" onMatch="ACCEPT" onMismatch="DENY" />
</ApplicationInsightsAppender>
````
results in the error
> appender ApplicationInsightsAppender has no parameter that matches element ThresholdFilter.

----

I think, as a fix the appender needs to add a builder
````java
@PluginBuilderFactory
public static <B extends Builder<B>> B newBuilder() {
    return new Builder<B>().asBuilder();
}
́public static class Builder<B extends Builder<B>> extends AbstractAppender.Builder<B>
            implements org.apache.logging.log4j.core.util.Builder<ApplicationInsightsAppender> { ... }
````

**Comment by dhaval24** [comment]
@tobiasdiez could you please shed some more details on this issue? Also, I see you suggesting a fix in the issue discussion. We are very open to contributions and would be really great if you could send a PR if it is possible ?

**Comment by tobiasdiez** [comment]
Sadly, I don't have time right now to create a PR but, of course, I'm happy to provide more details.

The default log4j2 appender accept the options `filter, layout, ignoreExceptions` (see [AbstractAppender](https://logging.apache.org/log4j/2.x/log4j-core/apidocs/org/apache/logging/log4j/core/appender/AbstractAppender.html#AbstractAppender(java.lang.String,%20org.apache.logging.log4j.core.Filter,%20org.apache.logging.log4j.core.Layout,%20boolean))). The `ApplicationInsightsAppender` should also support these basic settings. For this, the factory method
https://github.com/Microsoft/ApplicationInsights-Java/blob/36214d5c28eb975e008c5b7c60c4840fdd10ec20/logging/log4j2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v2/ApplicationInsightsAppender.java#L81-L83
needs to be extended by the arguments `                                              @PluginAttribute("ignoreExceptions") boolean ignoreExceptions,
                                              @PluginElement("Layout") Layout layout,
                                              @PluginElement("Filters") Filter filter` (see [log4j documentation](http://logging.apache.org/log4j/2.x/manual/extending.html#Appenders) for an example. What is not shown in the example is that you simply pass these arguments to the parent constructor.).
Moreover, the [log4j documentation](https://logging.apache.org/log4j/2.x/manual/extending.html) suggests to use the builder pattern.

**Comment by dhaval24** [comment]
@tobiasdiez thank you very much for the input. I will soon push out a PR. But most likely, it won't be a part of stable release of 2.0.0-BETA, instead would come out in 2.0.1 release as this would be a new feature, and just would defy the transition of Beta to stable.
