### ISSUE TITLE
Possibly incorrect mapping of Trace ID and Span ID

### ISSUE THREAD

**Issue by vprudnikov** [microsoft/ApplicationInsights-Java#3486]
### Expected behavior
I don't know exactly how it should be displayed, however, the current solution doesn't seem to be logical, based on the documentation.
Maybe `operation_id` should correspond to `spanId` and `operation_ParentId` correspond to `traceId` since "Trace" usually represents the entire operation.

### Actual behavior
`operation_id` corresponds to `traceId`
`operation_ParentId` corresponds to `spanId`

### To Reproduce
I use Application Insights with a default configuration.
The following dependencies are declared in the `pom.xml` file:
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-otel</artifactId>
        </dependency>
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>applicationinsights-runtime-attach</artifactId>
            <version>3.4.19</version>
        </dependency>
```

### System information
Please provide the following information:
 - SDK Version: 3.4.19
 - JDK: 21
 - OS type and version: Windows (runs my app locally)
 - Using spring-boot - yes - 3.2.0

### Logs
```
2024-01-04 10:37:52.770+01:00 INFO  c.m.applicationinsights.agent - Application Insights Java Agent 3.4.19 started successfully (PID 40224, JVM running for 2.415 s)
2024-01-04 10:37:52.783+01:00 INFO  c.m.applicationinsights.agent - Java version: 21.0.1, vendor: Eclipse Adoptium, home: C:\Users\vadzimp\.jdks\temurin-21.0.1
```

### Screenshots
![image](https://github.com/microsoft/ApplicationInsights-Java/assets/10853235/47744b05-a798-45bc-a898-df28107adc2c)

**Comment by jeanbisutti** [comment]
[This section](https://learn.microsoft.com/en-us/azure/azure-monitor/app/data-model-complete#operation-id) defines the  Operation ID, and [this one](https://learn.microsoft.com/en-us/azure/azure-monitor/app/data-model-complete#parent-operation-id) the Parent operation ID. We have checked the [implementation](https://github.com/Azure/azure-sdk-for-java/blob/5a079d8c09a1ea5aaef3a2e10c85f08f3b596375/sdk/monitor/azure-monitor-opentelemetry-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/implementation/SpanDataMapper.java#L277) and it seems correct. The custom dimensions diaplay on the screenshot are not populated by Application Insights. They may come from Micrometer.

**Comment by vprudnikov** [comment]
@jeanbisutti , thanks for your comment.
You are right, the custom dimensions come from Spring Boot. However, they are strangely mapped.
According to https://opentelemetry.io/docs/concepts/signals/traces/ , "Trace" represents the entire operation, and "Span" is a building block of a trace. 

That's why it's unclear why the Operation is mapped to Trace and the Parent Operation to Span. I get confused when seeing "trace having a parent".

**Comment by trask** [comment]
hi @vprudnikov, I don't disagree that the naming is a bit confusing. I suspect that's may be due to historical factors since those Application Insights fields predate W3C and OpenTelemetry by many years, and so their definition / modeling may have changed over time.

**Comment by vprudnikov** [comment]
Thanks to all for your answers. I understand that I got confused by the "operation parent id" which actually means a parent of a single item inside the whole operation :)
I believe that the following mapping would make sense:
Id - span id (the id is missing in my example)
Operation id - trace id
Operation parent id - parent span id

However, due historical and technical reasons, that may not be possible.

I don't have any further questions.

**Comment by trask** [comment]
just to clarify, this _is_ how the fields are mapped:

> Id - span id (the id is missing in my example)
Operation id - trace id
Operation parent id - parent span id

**Comment by vprudnikov** [comment]
@trask , thanks for the clarification! 
Is it correct that the "id" is missing on my screenshot?

**Comment by trask** [comment]
> Is it correct that the "id" is missing on my screenshot?

correct, logs don't have an "id" since they aren't spans

**Comment by vprudnikov** [comment]
Thanks! I'm closing the issue. I hope it will help others in case of the same misunderstanding I got initially.
