### ISSUE TITLE
Problem to configure sampling override

### ISSUE THREAD

**Issue by pasomaal** [microsoft/ApplicationInsights-Java#3511]
**Is your feature request related to a problem? Please describe.**
How do I configure sampling to e.g. 30% and keep all underlying process exceptions logged.
I have a running process where requests are logged and sampled at 30%.
A background process is generating exceptions and these seem also to be sampled at 30%.
How do I keep all exceptions logged?

**Describe the solution you would like**
Keep all exceptions logged using a sampling override.

**Additional context**
I tried the below configuration, but doesn't seem to work.

````
{
  "connectionString": "someconnectionstring",
  "role": {
    "name": "SomeRoleName"
  },
  "instrumentation": {
	"logging": {
	  "level": "WARN"
	}
  },
  "sampling": {
	"percentage": 30
  },
  "preview": {
	"sampling": {
	  "overrides": [
	    {
		  "telemetryType": "exception",
		  "attributes": [
		    {
			  "key": "exception.type",
			  "value": ".*",
			  "matchType": "regexp"
			}
		  ],
		  "percentage": 100
		}
	  ]
	}
  }
}
```

**Comment by heyams** [comment]
@pasomaal it should work if there is an attribute called "exception.type". 

can you double check log at the debug level?
![image](https://github.com/microsoft/ApplicationInsights-Java/assets/56097766/afc7dd12-ec2b-421b-a518-58767413f6b6)

**Comment by pasomaal** [comment]
@heyams 

Thanks for your quick answer. We tried the override of type telemetryType "exception" without the attributes section. But doesn't work in our case.
What do you mean with span exception is not supported?
Does this mean that we need to override the telemetryType "request" or "dependency"?

Kind Regards,

Patrick

**Comment by heyams** [comment]
@pasomaal 
sorry for the delay.

1. scenario 1: it's not possible currently using our java agent. it requires tail-based sampling. However, we use head-based sampling, and it doesn't know whether a request is successful or failed at the beginning of the span. 
2. scenario 2 is possible using OpenTelemetry Java Extension. We're going to release 3.5 GA, which will support Extension. When it becomes available, i can come up with a sample app and demonstrate how it is implemented using the extension. 

Hope this helps. Thank you for your patience.

**Comment by pasomaal** [comment]
Helen,

Thanks for your answer!
1. Scenario 1: any plans to add tail-base sampling?
2. Scenario 2: hope to see 3.5 GA

Kind Regards,

Patrick

**Comment by heyams** [comment]
@pasomaal [3.5.0](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/v3.5.0) is live today. 
I have passed on your #1 to our PM. No confirmation yet. Thanks.
