### ISSUE TITLE
Auto-instrumentation support for Pekko 1.0.0 in Java agent

### ISSUE THREAD

**Issue by AnastasiiaZu** [microsoft/ApplicationInsights-Java#3512]
Hi all!

My company is currently experimenting with Pekko 1.0.0 (fork of Akka). We collect our logs via Microsoft's Application Insights. Java logging agent from Application Insights [provides](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#preview-instrumentations) an Akka instrumentation as an option:

    "instrumentation": {
      "akka": {
        "enabled": true
      },
but not Pekko at the moment.
As a result, when Pekko is used, no logs are being published to AI.

Could a new instrumentation be added to [configurations](https://github.com/microsoft/ApplicationInsights-Java/blob/bd91f620189d797bee62541a532740d25c8c46e4/agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java#L476) like:

`public DisabledByDefaultInstrumentation pekko = new DisabledByDefaultInstrumentation();`
?

Best,
Anastasiia Zu

**Comment by pjfanning** [comment]
I'm guessing but I presume this also needs change:

https://github.com/microsoft/ApplicationInsights-Java/blob/5460d4e3fc3a53671d4e66189747a3f1ea44c84f/agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/AiConfigCustomizer.java#L272-L276

So we may also need otel to also change to support Pekko.

**Comment by jeanbisutti** [comment]
A PR was created to enable the Pekko instrumentation with 

```
"instrumentation": {
  "pekko": {
    "enabled": true
  }
```
