### ISSUE TITLE
Azure function app integration to Dynatrace in Linux with Open telemetry

### ISSUE THREAD

**Issue by BechenThoppil** [microsoft/ApplicationInsights-Java#3551]
We are trying to integrate Dynatrace with Azure Functions (Java 17- spring-cloud-function-adapter-azure version 3.1.5) for monitoring.
 
Our Environment: Azure Functions running on App service plan with platform as Linux.
 
Issue:
We couldn’t find an extension-based approach for the Azure functions in Linux (which is present in Windows). Due to this we tried Open-Telemetry approach as recommended by Dynatrace. We are able to start the agent, but OTEL was unable to invoke Dynatrace end points with the provided tokens. All the configuration/dependencies for open telemetry are made at function app created with java.
 
When we switched the platform from Linux to Windows, we were able to connect to Dynatrace and view the traces. (It’s configured via Dynatrace open agents added as an extension in the function app).

<img width="462" alt="azure-log" src="https://github.com/microsoft/ApplicationInsights-Java/assets/160215660/0de4054d-5ea5-49e5-989a-cab3fc966f57">

**Comment by RohitRanjanMS** [comment]
Hi @BechenThoppil , I'm sorry, but it's necessary for you to collaborate with Dynatrace in order to investigate this issue.

**Comment by heyams** [comment]
@BechenThoppil please set `APPLICATIONINSIGHTS_ENABLE_AGENT=false`.
