### ISSUE TITLE
HTTP dependencies are not reported in latest Spring Boot 3.2.

### ISSUE THREAD

**Issue by numirov** [microsoft/ApplicationInsights-Java#3561]
### Expected behavior
HTTP dependencies to appear in app insights

### Actual behavior
They are not appearing

### To Reproduce
Issue is in underlying OTEL lib, which is fixed in latest versions 1.32.1/1.33 . Link to their fix: https://github.com/open-telemetry/opentelemetry-java-instrumentation/commit/bbfe950ad0ace8123a5e6817fb3767e27a1a2cee

### System information
Please provide the following information:
 - SDK Version: 3.4.19
 - OS type and version: 
 - Application Server type and version (if applicable):
 - Using spring-boot? Spring Boot 3.2, java21
 - Additional relevant libraries (with version, if applicable):

### Logs
java.lang.NullPointerException: Cannot invoke "org.apache.hc.core5.http.HttpHost.getSchemeName()" because "httpHost" is null
	at io.opentelemetry.javaagent.instrumentation.apachehttpclient.v5_0.RequestWithHost.<init>(RequestWithHost.java:23)
_Be sure to remove any private information from the logs before posting!_

This is affecting our upgrade to latest spring boot, may I please know when is the next release planned? Hopefully otel version will be bumped in that one?

**Comment by jeanbisutti** [comment]
@numirov It should be fixed with Application Insights 3.5.0. Can you try with Application Insights 3.5.0?
