### ISSUE TITLE
Download URL format changed in 3.5.0

### ISSUE THREAD

**Issue by paulridout** [microsoft/ApplicationInsights-Java#3566]
The format for the download URL has changed for release 3.5.0.

The URL for release 3.4.19 is:
https://github.com/microsoft/ApplicationInsights-Java/releases/download/3.4.19/applicationinsights-agent-3.4.19.jar

The URL for release 3.5.0 is:
https://github.com/microsoft/ApplicationInsights-Java/releases/download/v3.5.0/applicationinsights-agent-3.5.0.jar

The difference is the "v" prefix for the version number.  This appears to be because the release has been tagged with v.3.5.0 instead of 3.5.0.  The tags for releases prior to 3.5.0 aren't prefixed with "v".

This causes an issue with the utility we're using to manage dependency updates.  It expects the version number to be in the same format in both places in the URL.

Was this change intentional and will it always be like this going forward?

For reference, the same issue was reported before in https://github.com/microsoft/ApplicationInsights-Java/issues/838.

**Comment by heyams** [comment]
thanks for pointing it out. release tag was created manually for v3.5.0 due to github action failure. 
release notes of earlier versions were done automatically by github action. i will fix it.

**Comment by heyams** [comment]
Fixed. Please check it out again.

**Comment by paulridout** [comment]
Thanks @heyams - the change you made has worked.  Feel free to close this issue.
