### ISSUE TITLE
Operation name/ Operation id missing for manual created threads

### ISSUE THREAD

**Issue by Charlie441324219** [microsoft/ApplicationInsights-Java#3569]
### Expected behavior
Parent thread pass Operation name/ Operation id to children thread

### Actual behavior
Operation name/ Operation id is missing for manual created threads (new Thread().start()), but works fine with CompletableFuture.runAsync()

### To Reproduce

```
		telemetry.trackEvent(baseHeaders, null, membershipNbr, "AI_LOG_PARENT_THREAD");

		new Thread(() -> telemetry.trackEvent(baseHeaders, null, membershipNbr, "AI_LOG_CHILDREN_THREAD_THREAD")).start();//Operation name/ Operation id missing HERE

		CompletableFuture.runAsync(() -> telemetry.trackEvent(baseHeaders, null, membershipNbr, "AI_LOG_CHILDREN_THREAD_THREAD_POOL"));
```

### System information
Please provide the following information:
 - SDK Version:3.4.17
 - OS type and version:ios, java 11
 - Application Server type and version (if applicable):
 - Using spring-boot?no
 - Additional relevant libraries (with version, if applicable):

### Screenshots
![Screenshot 2024-03-04 at 10 34 02 AM](https://github.com/microsoft/ApplicationInsights-Java/assets/22875442/4ed64f90-ec0d-41fa-815a-104656655a0a)

**Comment by jeanbisutti** [comment]
@Charlie441324219 `CompletableFuture` is auto-instrumented but `Thread` is not.

You can do the following thing to propagate the context:

```java
            io.opentelemetry.context.Context context = io.opentelemetry.context.Context.current();
			Thread thread = new Thread(new Runnable() {
			    @Override
			    public void run() {
					try (Scope scope = context.makeCurrent()) {
				telemetry.trackEvent(baseHeaders, null, membershipNbr, "AI_LOG_CHILDREN_THREAD_THREAD")).start();
					}
			    }
			});
			thread.start();
```

**Comment by Charlie441324219** [comment]
Hi @jeanbisutti ,

Thank you so much for your help, can you please provide more details about what condition context can auto propagate or what condition it cannot ?

**Comment by jeanbisutti** [comment]
> de more details about what condition context can auto propagate or what condition it cannot ?

@Charlie441324219, The propagation context is automatically propagated between all the automatic instrumentations. So, the context is propagated to `CompletableFuture` and the HTTP request can be known.

`Thread` is not automatically instrumented. So, the context is not automatically propagated into the methods of `Thread` , and it is needed to programmatically propagate the context.

**Comment by Charlie441324219** [comment]
Hi @jeanbisutti , thank you for your reply, can you please provide more details about how to know if a JAVA asynchronous technology is automatic instrumentations or not ?

**Comment by jeanbisutti** [comment]
See https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-add-modify?tabs=java

**Comment by Charlie441324219** [comment]
Thank you @jeanbisutti @trask ,
