### ISSUE TITLE
Azure ApplicationInsights stopped reporting Query paramters in Request traces - With 3.5.0

### ISSUE THREAD

**Issue by mohitj13** [microsoft/ApplicationInsights-Java#3580]
### Expected behavior
With previous versions the complete http path along with query parameter was reported in the HTTP request span in the application insights view. 

### Actual behavior
With new 3.5.0 version the HTTP request span only show the reduced path of the request without query parameter. 

### System information
Please provide the following information:
 - SDK Version: 3.5.0
 - OS type and version: N/A
 - Application Server type and version (if applicable): N/A
 - Using spring-boot? 3.2.2
 - Additional relevant libraries (with version, if applicable): N/A
 
 Looks like the semantic change might have created this issue - https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/migration-guide.md#summary-of-changes

**Comment by trask** [comment]
Thanks for reporting this! We will get it fixed quickly.
