### ISSUE TITLE
Q: regarding client secrets support

### ISSUE THREAD

**Issue by lmcdasi** [microsoft/ApplicationInsights-Java#3584]
Hi,

   I do have an on-prem application that get's authenticated using Entra ID by using certificates.
   I would like to use the same config when using App Insight but I noticed that the SAMI section using secrets is marked as deprecated in the code.
   Is there any time frame where the secret support will be completely removed ? And does it mean that I have to use Azure Arc in order to use Managed Identities ?

   Thank you.

Best Regards.

**Comment by heyams** [comment]
@lmcdasi we will remove the clientSecret support in 4.0.0 GA. Please start using SAMI or UAMI AAD authentication. 
We encourage customers to migrate to `SAMI` or `UAMI`. 
https://learn.microsoft.com/en-us/azure/azure-monitor/app/azure-ad-authentication?tabs=java
