### ISSUE TITLE
Hard time unit testing adal4j

### ISSUE THREAD

**Issue by Cpt-xx** [Microsoft/ApplicationInsights-Java#361]
We're having a hard time unit testing adal4j in isolation. The way the authentication needs to be set up (creating a new com.microsoft.aad.adal4j.AuthenticationContext) forces us to run unit tests in an environment where an active AAD needs to be present. This can be circumvented by using debatable products as PowerMock (intercepting the 'new' and allowing a replacement to be put into place). Also the use of final classes (such as com.microsoft.aad.adal4j.AuthenticationResult) forces the use of PowerMock.
We would rather not use PowerMock to run our unit tests, and would rather use a more controlled adal4j provided test framework, or use a adal4j provided factory. 

If that factory were to be implementing an interface, that would make injecting the factory as a collaborator a neat pattern, allowing for easy and clear unit testing possible. Removing the final directive from the AuthenticationResult, replacing this with an interface and an actual implementing class (which can be made final if you should wish to) also makes for much easier unit testing without the use of PowerMock.

Are there any documents in place guiding us in creating isolated unit tests which would not require an active ActiveDirectory to be present?

**Comment by Dmitry-Matveev** [comment]
@Cpt-xx , are you sure this issue is about Application Insights Java SDK? I do not think AI Java SDK relies on adal4j anywhere in the code, could you please provide an example of such dependency if I missed it?

**Comment by Cpt-xx** [comment]
this is indeed not for AI.I was lead to this thread as the thread to ask questions about ADAL4J.

So the question is about ADAL4J, and the hard time it gives us to do proper unit testing in Java with the classes mentioned being final and not using interfaces nor factory patterns.

**Comment by Cpt-xx** [comment]
That is a bit harsh... Could you not at least have specified with whom I need to take up this issue? Or provide a reason why not being able to unit test classes that use such a vital piece of ADAL4J (the API, the connection with the outside world, the one piece that offers access to ADAL4J) is not an issue?!

**Comment by Cpt-xx** [comment]
In the meantime I have been using ADAL4J (yes, ADAL4J, not only the AuthenticationContext) and I've run in another couple of problems with unit testing.
Example:
KeyVaultClient.
KeyVaultClient is a class that is used, basically as an interface to the KeyVault. It translates java-invocations in Rest-interactions with the Azure Key Vault.

In order to use that you have to instantiate the KeyVaultClient with an authorisation token object.
So if I want to unit test the application facing class I hand it the mock of a token (I don't want to calculate a token for each unit test, why should I, that is done by classes that are not mine). But, wait... that will ask all kinds of questions to my token mock, because it wants to actually initialize the KeyVaultClient. And I can't guarantee that I have a KeyVault running in my unit test environment.
Solution: use a KeyVaultClient factory and have that factory return a mock KeyVaultClient in a unit test environment. That way I can precisely let the KeyVaultClient mock return whatever I want it to, without having to have a KeyVault infrastructure up and running.
But wait... I cannot use Mockito (a fairly standard tool for mocking classes) because KeyVaultClient is final, it can't be used by Mockito (and probably also not by EasyMock) to create a mock for, as you can't extend a final class.
So now I not only have to create KeyVaultClientFactory (which I had to do anyway) but now also I need to create a KeyVaultClientWrapper, which delegates the calls to the KeyVaultClient (inner class) and implement all methods that I use in my whole application so that I can mock the KeyVaultClient class (via the wrapper) and have the KeyVaultClientWrapper class returned from the KeyVaultClientFactory.

This is just one example, there are plenty more.
My suggestion would be for you to look at other frameworks such as java.security.* which uses interfaces extensively to communicate with the outside world and hides implementation details (such as a final class) from the outside world. This leaves open the possibility of creating mocks (as interfaces are easily and always mockable), but (and that is perhaps more compelling for you guys) also opens up the way for easy extension and replacement of implementations of these interfaces by your application.

**Comment by Cpt-xx** [comment]
Further suggestions:
In order for ADAL4J to be better mockable, I would suggest you replace the classes with interfaces (with the same name) and have the implementation be final. That way the interfaces can easily be mocked (interfaces are mockable by definition as they cannot be final). By using a factory class to obtain the implementation you open up the easy way of introducing better, other implementations which can be instantiated by using configuration files.  That way we can inject a mock of the interface into the class which is under unit test and take away the dependency which we now have on an actual implementation running in the Unit test environment (which is the actual root of the problem here).

**Comment by dhaval24** [comment]
@Cpt-xx I appreciate your concern and so many great advises on how to improve ADAL4j. However, I believe this is as far as I understand not the correct repository for Azure Active Directory Library's repository . The correct repository where you can open this issue and reach broader set of audience is : https://github.com/AzureAD/azure-activedirectory-library-for-java
I would be more than happy if you can open the issue there and we can close it from here .

**Comment by Cpt-xx** [comment]
Opened issue under this url: https://github.com/AzureAD/azure-activedirectory-library-for-java/issues/188
