### ISSUE TITLE
class "javax.annotation.Nullable"'s signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by maciek-prokopiuk** [Microsoft/ApplicationInsights-Java#362]
There is `javax.annotation` package inlined in applicationinsight-core.jar (v 1.0.7). Unfortunately whole jar is signed so it force us to use classes from the same package. While, for example, Nullable class is included in both JDK and applicationinsights-core we are getting `class "javax.annotation.Nullable"'s signer information does not match signer information of other classes in the same package`. Are there any known solutions for dealing with such issue? 

Possible solution could be to exclude `javax.annotation` package from the JAR and use one included in JDK.

**Comment by jwoehrle** [comment]
I can confirm this issue. For the time being I switched back to version 1.0.6. This version does not contain the dependency to JSR-305.

**Comment by dimonok** [comment]
can confirm, we are also facing this issue. we will switch back to 1.0.6

**Comment by Dmitry-Matveev** [comment]
Thank you for reporting this! This should be addressed as part of 1.0.8 release.

**Comment by tomaszglinski** [comment]
I have the same problem. I suppose the may happen will all of other dependencies copied into jar, like org.objectsweb.asm, but javax is the most common blocker.

When is some new release going to be rolled out?

**Comment by debugthings** [comment]
#367 Related

**Comment by beckylino** [comment]
@maciek-prokopiuk, @tomaszglinski, @jwoehrle, and @dimonok were any of you able to upgrade to the our version 1.0.8 of our SDK? Is this issue still persisting? Thanks :)

**Comment by maciek-prokopiuk** [comment]
Unfortunately I am not working on this project anymore and do not have access to the codebase. Maybe other guys can check it.  Good luck ;)

**Comment by tomaszglinski** [comment]
I will try it when I get some free time :)

**Comment by jwoehrle** [comment]
puh, I don't remember how to reproduce this issue... Did it happen at compile or at runtime?

**Comment by maciek-prokopiuk** [comment]
@jwoehrle it was SecurityException which is Runtime one. At compile time you do not know which jar will be used as it could be provided for example.

**Comment by dhaval24** [comment]
@maciek-prokopiuk it seems that we are repackaging the javax.annotation dependency in the code using shadow jar in the latest 1.0.10 version of the SDK. were you able to try this with latest SDK? If issue no longer persist feel free to close the issue on github

**Comment by maciek-prokopiuk** [comment]
@dhaval24 sorry I have no longer access to the codebase that uses Insights. maybe someone else can check that as I will have no possibilities to do that soon

**Comment by dhaval24** [comment]
@maciek-prokopiuk thanks for letting me know. I will keep the thread open for few more days to see if anyone else is facing the same issue before closing it.

**Comment by littleaj** [comment]
Verified the `javax.annotation` is no longer included inside the AI jars.
