### ISSUE TITLE
Unable to run Application Insights Java Agent 1.0.7

### ISSUE THREAD

**Issue by YuiRakjit** [Microsoft/ApplicationInsights-Java#363]
This error was thrown when I started Wildfly 10 with Application Insights Java Agent 1.0.7.

> Agent is NOT activated: failed to load to bootstrap class loader: com.microsoft.applicationinsights.agent.internal.config.AgentConfiguration.isSelfRegistrationMode()Z

Do you have any workaround to fix this issue?

Thank you

**Comment by Dmitry-Matveev** [comment]
Do you have all the necessary configuration files for AI Agent on the path?
Also, do you have AI Web SDK running within this process? As far as I know self registration should only happen if no Web SDK is present or if self-registration is specified manually in the configuration file.

AI Core SDK should be present for operation of AI Java Agent (Agent will send telemetry items via Core SDK).

**Comment by beckylino** [comment]
@YuiRakjit were you able to try the recommendations by @Dmitry-Matveev?

**Comment by YuiRakjit** [comment]
Sorry for late reply. I just got back from holiday, I will check for you before at the end of this week.

**Comment by dhaval24** [comment]
@YuiRakjit We have released a new version of SDK v1.0.10 last Friday. Can you please see the behavior if it persists in new version so we can triage it accordingly for our next sprints.

**Comment by dhaval24** [comment]
@YuiRakjit we haven't found issues loading the agent in JDK 1.7 in the latest 1.0.10 version of the SDK. If you can provide exact steps to reproduce this issue it would be great or else we should be good to close this issue.

**Comment by dhaval24** [comment]
@YuiRakjit  please update to the latest SDK version 1.0.10. This issue doesn't occur anymore, please reopen if the problem persists.
