### ISSUE TITLE
Sampling override based on request processing time?

### ISSUE THREAD

**Issue by kemuri-9** [microsoft/ApplicationInsights-Java#3637]
**Is your feature request related to a problem? Please describe.**
On a particular project I've found that most of the ingestion into application insights is from dependency metrics collected.
For us this includes JDBC, HTTP client, and Redis.
For quickly responding requests these dependency metrics aren't actually that desired, as performance evaluation of the request will not be evaluated.
I've been trying to go through the configuration to see how there could be an override to change the sampling rate for dependencies when the request is "quick" (as a concrete example, let's say <5 seconds is "quick").
But so far I've not been able to see anything like this. I have not yet found any span that was the processing time of the request to do this override.

**Describe the solution you would like**
Is this currently possible somehow? It would be great for us to be able to not sample dependencies for quick requests to reduce our ingestion into insights (and reduce our running cost).

**Describe alternatives you have considered**
Not interested in turning off all dependency sampling as this is necessary to investigate why slow requests are slow.

**Additional context**

**Comment by kemuri-9** [comment]
Currently using v3.5.1

**Comment by heyams** [comment]
@kemuri-9 sorry for the late response. 
Please try this sample app [filter telemetry based on request duration](https://github.com/Azure-Samples/ApplicationInsights-Java-Samples/tree/main/opentelemetry-api/java-agent/TelemetryFilteredBaseOnRequestDuration). I believe this will help.

**Comment by kemuri-9** [comment]
Looking at the referred example, it looks like the core functionality being referred to is within https://github.com/Azure-Samples/ApplicationInsights-Java-Samples/tree/main/opentelemetry-api/java-agent/extensions/FilterSpanBasedOnDuration
and this functionality is an open telemetry extension that decides whether to export (or to not export) the span based on its duration.
So the desired functionality is purely available in the application insights json configuration, but requires a separate code module to be implemented.
Is this understanding correct?

**Comment by heyams** [comment]
@kemuri-9 please look closer to the sample, it doesn't require a json configuration. sampling overrides apply at the beginning of the span. span duration is captured at the end of a span. Extensions give you more control to make decision what to export. You can filter based on any attributes or anything else that can be used uniquely identifying a span.

**Comment by heyams** [comment]
> Looking at the referred example, it looks like the core functionality being referred to is within https://github.com/Azure-Samples/ApplicationInsights-Java-Samples/tree/main/opentelemetry-api/java-agent/extensions/FilterSpanBasedOnDuration and this functionality is an open telemetry extension that decides whether to export (or to not export) the span based on its duration. So the desired functionality is not purely available in the application insights json configuration, but requires a separate code module to be implemented. Is this understanding correct?

Yes

**Comment by kemuri-9** [comment]
Then there is a methodology to achieve the desired behavior, so resolved.
