### ISSUE TITLE
Release already a new version...

### ISSUE THREAD

**Issue by tomaszglinski** [Microsoft/ApplicationInsights-Java#364]
Hi, I see that there are already many changes done on master compared to 1.0.7. Please release soon...

**Comment by Dmitry-Matveev** [comment]
@tomaszglinski, unfortunately, there is no certain date yet for 1.0.8 release, I will share one here as soon as I have it.

**Comment by Dmitry-Matveev** [comment]
@tomaszglinski , 1.0.8 was just released, it should appear on Maven in couple hours.
