### ISSUE TITLE
Support for OTEL Synchronous Gauge

### ISSUE THREAD

**Issue by ivan-zaitsev** [microsoft/ApplicationInsights-Java#3647]
### Expected behavior
```
import io.opentelemetry.api.GlobalOpenTelemetry;
import io.opentelemetry.api.incubator.metrics.ExtendedLongGaugeBuilder;
import io.opentelemetry.api.incubator.metrics.LongGauge;

LongGauge gauge = ((ExtendedLongGaugeBuilder) GlobalOpenTelemetry.getMeter("meter").gaugeBuilder("gauge").ofLongs()).build();
gauge.set(1);
```

Otel PR: https://github.com/open-telemetry/opentelemetry-java/pull/5506

### Actual behavior
```
java.lang.ClassCastException: class io.opentelemetry.javaagent.instrumentation.opentelemetryapi.v1_10.metrics.ApplicationLongGaugeBuilder cannot be cast to class io.opentelemetry.api.incubator.metrics.ExtendedLongGaugeBuilder (io.opentelemetry.javaagent.instrumentation.opentelemetryapi.v1_10.metrics.ApplicationLongGaugeBuilder and io.opentelemetry.api.incubator.metrics.ExtendedLongGaugeBuilder are in unnamed module of loader 'app')
```

### System information
SDK version: 3.5.1
Spring boot version 3.2.4

**Comment by trask** [comment]
hi @ivan-zaitsev, it looks like you may be using older versions of OpenTelemetry API and OpenTelemetry Incubator, can you double check that you are using 1.36.0 for both `io.opentelemetry:opentelemetry-api` and `io.opentelemetry:opentelemetry-api-incubator`

also double check that the Spring dependency management isn't overriding the dependency versions you specify, check out https://opentelemetry.io/docs/languages/java/instrumentation/#dependency-management
