### ISSUE TITLE
SDKShutdownActivity is calling multiple times for same Channel

### ISSUE THREAD

**Issue by Mart-Bogdan** [Microsoft/ApplicationInsights-Java#366]
I've noticed problem leading to memory leaks and executing of shutdown hook many times, instead of single time!
First of all take a look at constructor of `com.microsoft.applicationinsights.TelemetryClient`:
```java
    public TelemetryClient(TelemetryConfiguration configuration) {
        if (configuration == null) {
            configuration = TelemetryConfiguration.getActive();
        }

        synchronized (TELEMETRY_STOP_HOOK_LOCK) {
            SDKShutdownActivity.INSTANCE.register(new TelemetryClientChannelFetcher());
        }

        this.configuration = configuration;
    }
```
We are registering platform shutdown hook `SDKShutdownActivity.INSTANCE.register(new TelemetryClientChannelFetcher());` and passing inner class `TelemetryClientChannelFetcher`:
```java
public class TelemetryClient {
    private final class TelemetryClientChannelFetcher implements ChannelFetcher {
        public TelemetryChannel fetch() {
            return getChannel();
        }
    }
```
As this is sinner class, it holds hidden reference to TelemetryClient, otherwise it won't be able to call `TelemetryClient#getChannel()`. So all created TelemetryClient's would be hold in memory, no WeakReferences are used.
Then let's take a look at `com.microsoft.applicationinsights.internal.shutdown.SDKShutdownActivity`:
```java
        private void stopChannels() {
            for (ChannelFetcher fetcher : fetchers) {
                try {
                    TelemetryChannel channelToStop = fetcher.fetch();
                    if (channelToStop != null) {
                        channelToStop.stop(1L, TimeUnit.SECONDS);
                    }
                } catch (Throwable t) {
                    InternalLogger.INSTANCE.error("Failed to stop channel: '%s'", t.getMessage());
                }
            }
        }
```

We are calling stop on every channel, but most TelemetryClients would have **SAME** channel! As most clients are using `configuration = TelemetryConfiguration.getActive();` which is holding channel:
```java
class TelemetryClient {
    /**
     * Gets the channel used by the client.
     */
    TelemetryChannel getChannel() {
        if (channel == null) {
            this.channel = configuration.getChannel();
        }

        return this.channel;
    }
```

So here are two problems:

1. TelemetryChannel#stop is called multiple times
2. TelemetryClients remains live in memory, as there are global references to them, and TC can hold quite big Context inside.

Even if context data isn't big, it still consumes memory, espessialy if create context man times, as seems appealing due to fact it holds userId, so I've tried to use instance per request, now seems not as good idea.

I would suggest:
1. don't store references TelemetryClients in global, just copy channel from it.
2. Subscribe channel for shutdown in TelemetryConfiguration creation factory.

*P.S.* maybe I don't understand something, than could somebody explain me why it's implemented this way? Am I misusing it, and should create single TelemetryCLient per application?

Thanks,
Bogdan.

**Comment by Mart-Bogdan** [comment]
I don't see anything like this in .Net client:
```c#
        /// <summary>
        /// Initializes a new instance of the <see cref="TelemetryClient" /> class. Send telemetry with the specified <paramref name="configuration"/>.
        /// </summary>
        /// <exception cref="ArgumentNullException">The <paramref name="configuration"/> is null.</exception>
        /// <exception cref="ArgumentException">The <paramref name="configuration"/> does not contain a telemetry channel.</exception>
        public TelemetryClient(TelemetryConfiguration configuration)
        {
            if (configuration == null)
            {
                CoreEventSource.Log.TelemetryClientConstructorWithNoTelemetryConfiguration();
                configuration = TelemetryConfiguration.Active;
            }

            this.configuration = configuration;

            if (this.configuration.TelemetryChannel == null)
            {
                throw new ArgumentException("The specified configuration does not have a telemetry channel.", "configuration");
            }
        }
```

**Comment by Dmitry-Matveev** [comment]
I would recommend to go with fewer `TelemetryClient` instances to limit the impact. I cannot talk about why it was implemented in this particular way, we may need to involve the original code owners here.

.NET SDK usage typically involves a limited set of Telemetry Client instances, but it does not save user context in there, thus no appeal for "new"-ing up new instance every time. I would expect that Java SDK also should not save such a context per client instance.

BTW, .NET [used to have a leak](https://github.com/Microsoft/ApplicationInsights-dotnet/issues/364) in Telemetry Clients and Channels as well.

**Comment by beckylino** [comment]
@Mart-Bogdan were you able to diminish the number of TelemetryClient instances as recommended by @Dmitry-Matveev? Did this help?

**Comment by Mart-Bogdan** [comment]
@beckylino hellom thanks, yes we've managed this workaround.

**Comment by dhaval24** [comment]
@Mart-Bogdan closing this issue as you had got a working workaround.
