### ISSUE TITLE
Custom Availability telemetry not working 

### ISSUE THREAD

**Issue by opensourcevk** [microsoft/ApplicationInsights-Java#3675]
AI version: 3.5.1
Java: 17

Steps to reproduce:
1.  create AvailabilityTelemetry object with values
2.  Telemetryclient.track(AvailabilityTelemetry)

Expected result:
On azure portal Application Insights custom availability should be displayed on availability page.

Actual result:
No custom availability is shown on availability page.

**Comment by trask** [comment]
hi @opensourcevk! we have tests for trackAvailability so this should be working. Can you provide a small repro that we can check to see why this isn't working for you? thanks
