### ISSUE TITLE
APPLICATIONINSIGHTS_CONNECTION_STRING does not work in 3.5.x, works in 3.4.x

### ISSUE THREAD

**Issue by mercer** [microsoft/ApplicationInsights-Java#3707]
### Expected behavior
APPLICATIONINSIGHTS_CONNECTION_STRING works in 3.5.x

### Actual behavior

APPLICATIONINSIGHTS_CONNECTION_STRING does not work in 3.5.x (tried 3.5.0, 3.5.1, 3.5.2)

### To Reproduce

1. add dependency com.microsoft.azure:applicationinsights-runtime-attach:3.4.19
2. add applicationinsights.json in src/resources, see bellow
3. provide connection string via APPLICATIONINSIGHTS_CONNECTION_STRING environment variable
4. attach to agent via ApplicationInsights.attach();
5. start app
6. agent connects to appinsights, traces are sent to apinsights; we had this setup for more than 1 year
7. upgrade to com.microsoft.azure:applicationinsights-runtime-attach:3.5.2
8. start app (no other changes, no changes to applicationinsights.json)
9. agent does not connect, see error bellow in app console

```
*************************
Application Insights Java Agent 3.5.2 startup failed (PID 46492)
*************************

Description:
Error loading connection string from a file ("unknown-from-application-insights-json").
Please use this format instead:
{ "connectionString": "${file:connection-string-file.txt}" }


Action:
Learn more about configuration options here: https://go.microsoft.com/fwlink/?linkid=2153358

```

### System information
Please provide the following information:
 - SDK Version: 3.5.x
 - OS type and version: Mac M2
 - Application Server type and version (if applicable):
 - Using spring-boot? yes
 - Additional relevant libraries (with version, if applicable):

### Logs
```
2023-05-30 17:02:01.940+03:00 ERROR c.m.applicationinsights.agent - Application Insights Java Agent 3.4.13 startup failed (PID 20200)
java.lang.IllegalArgumentException: Missing 'InstrumentationKey'
	at com.azure.monitor.opentelemetry.exporter.implementation.configuration.ConnectionStringBuilder.mapToConnectionConfiguration(ConnectionStringBuilder.java:85)
	at com.azure.monitor.opentelemetry.exporter.implementation.configuration.ConnectionStringBuilder.setConnectionString(ConnectionStringBuilder.java:39)
	at com.azure.monitor.opentelemetry.exporter.implementation.configuration.ConnectionString.lambda$parse$0(ConnectionString.java:37)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)

```

```
{
  "connectionString": "unknown-from-application-insights-json",
  "role": {
    "name": "app-role"
  },
  "sampling": {
    "percentage": 100
  },
  "instrumentation": {
    "logging": {
      "level": "INFO"
    }
  },
  "preview": {
    "processors": [
      {
        "type": "attribute",
        "actions": [
          {
            "key": "http.url",
            "pattern": "^(.*)(?<pii>[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4})(.*)",
            "action": "extract"
          }
        ]
      },
      {
        "type": "attribute",
        "include": {
          "matchType": "strict",
          "attributes": [
            {
              "key": "pii"
            }
          ]
        },
        "actions": [
          {
            "key": "http.url",
            "action": "hash"
          },
          {
            "key": "pii",
            "action": "delete"
          }
        ]
      }
    ],
    "sampling": {
      "overrides": [
        {
          "telemetryType": "request",
          "attributes": [
            {
              "key": "http.url",
              "value": ".*/actuator/health.*",
              "matchType": "regexp"
            }
          ],
          "percentage": 0
        },
        {
          "telemetryType": "request",
          "attributes": [
            {
              "key": "http.url",
              "value": ".*/actuator/dbcheck.*",
              "matchType": "regexp"
            }
          ],
          "percentage": 0
        },
        {
          "telemetryType": "dependency",
          "attributes": [
            {
              "key": "db.system",
              "value": "mssql",
              "matchType": "strict"
            }
          ],
          "percentage": 50
        }
      ]
    }
  }
}

```

**Comment by jeanbisutti** [comment]
@mercer Could you please set the `APPLICATIONINSIGHTS_SELF_DIAGNOSTICS_LEVEL` env variable to `TRACE` and send the `applicationinsights.json` file to jeanbisutti@microsoft.com?

**Comment by jeanbisutti** [comment]
@mercer I have done some tests and have not noticed any issue with `com.microsoft.azure:applicationinsights-runtime-attach:3.5.2`.

You have provided this error:

```
Description:
Error loading connection string from a file ("unknown-from-application-insights-json").
Please use this format instead:
{ "connectionString": "${file:connection-string-file.txt}" }
```

It could be explained by this JSON config you have provided:

```
 {
  "connectionString": "unknown-from-application-insights-json",

```

Could you please check your connection string and retest if something wrong is noticed?

**Comment by jeanbisutti** [comment]
@mercer The error messages were misleading. Sorry about that. See #3709

**Comment by mercer** [comment]
I have two issues with this

1. Isn't this a breaking change that APPLICATIONINSIGHTS_CONNECTION_STRING no longer works with a connection string and now requires a file path? 3.5.x is a minor, not a major semaversion
2. [Documentation](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#connection-string) has not change, it states that APPLICATIONINSIGHTS_CONNECTION_STRING can be used to provide the connection string at runtime via spring boot's override option

![image](https://github.com/microsoft/ApplicationInsights-Java/assets/95358/32924252-c3a3-40f8-bd81-5dee61d71464)

**Comment by jeanbisutti** [comment]
In #3709, only the error message that could be misleading has changed. It does not affect the connection string features.

**Comment by mercer** [comment]
Then I'd expect my setup to work in 3.5.x just as in 3.4.x, but it doesn't. If you need more details in this ticket, let me know 🙏

**Comment by mercer** [comment]
With 3.4.19 I see this applicationinsights.log

```
2024-06-05 16:27:59.395+03:00 INFO  c.m.applicationinsights.agent - Application Insights Java Agent 3.4.19 started successfully (PID 49245, JVM running for 1.627 s)
2024-06-05 16:27:59.399+03:00 INFO  c.m.applicationinsights.agent - Java version: 17.0.7, vendor: Azul Systems, Inc., home: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
```

**Comment by jeanbisutti** [comment]
HI @mercer, 
Sorry for the delay. I was off.
I had tried with a Petclinic application and Application Insights Runtime Attach 3.5.2 without observing any issue.
To be able to help you, could you please point to a Github repository reproduding the issue or send by email the Application Insights logs at the TRACE level [as previously asked](https://github.com/microsoft/ApplicationInsights-Java/issues/3707#issuecomment-2122261892)?

**Comment by Cloud5000** [comment]
I can confirm what @mercer mentioned. APPLICATIONINSIGHTS_CONNECTION_STRING works with 3.4.19 but not with 3.5.x.

**Comment by jeanbisutti** [comment]
Hi @mercer and @Cloud5000 

I have retested the Petclinic application with the Runtime Attachment feature and with the `APPLICATIONINSIGHTS_CONNECTION_STRING`  environment variable. I can see the telemetry data on the Azure portal with the 3.5.2 and 3.5.3 versions.

The only way to reproduce the same error message seen by @mercer is to use an invalid connection string in the applicationinsights.json file:

```
*************************
Application Insights Java Agent 3.5.3 startup failed (PID 4336)
*************************

Description:
Your connection string seems to have a wrong format: "unknown-from-application-insights-json").
If you want to load the connection string from a file, please use this format:
{ "connectionString": "${file:connection-string-file.txt}" }
```


Could you please remove the following connection string from the applicationinsights.json file:

```
{

  "connectionString": "unknown-from-application-insights-json"
}
```

**Comment by mercer** [comment]
Ok, but this is a regression. As this is semver, a minor version change should not introduce a breaking change.
