### ISSUE TITLE
Ability to flush logs at shutdown

### ISSUE THREAD

**Issue by epot** [Microsoft/ApplicationInsights-Java#372]
I am following this tutorialL https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-get-started to use this component and it is not clear how I can flush all logs to AppInsights before shutting down. I saw that flush methods exist (added here https://github.com/Microsoft/ApplicationInsights-Java/pull/142) but I am not sure if they apply to logs and how I can use them when the app shuts down (since I never instantiate anything in Java, I fully rely on logback configuration). Would it be possible to get a small explanation ?

**Comment by epot** [comment]
It seems a:
    new TelemetryClient().flush()
does the job, but it is a bit weird.

**Comment by Dmitry-Matveev** [comment]
@epot, if you are using logback adapter, then events from this adapter are actually sent through the internal `TelemetryClient` within adapter.

You can get this client with `getTelemetryClientProxy().getTelemetryClient()` as per [this public interface](https://github.com/Microsoft/ApplicationInsights-Java/blob/abd0f195b7f7afe5081018357ff5cafde96b7e20/logging/logback/appenderSrc/main/java/com/microsoft/applicationinsights/logback/ApplicationInsightsAppender.java#L46) in Appender and [this public method ](https://github.com/Microsoft/ApplicationInsights-Java/blob/abd0f195b7f7afe5081018357ff5cafde96b7e20/logging/common/src/main/java/com/microsoft/applicationinsights/internal/common/LogTelemetryClientProxy.java#L115 )in Proxy.

However, I'm not fully positive that the execution of the `Flush()` is fully synchronous,[ this method ](https://github.com/Microsoft/ApplicationInsights-Java/blob/abd0f195b7f7afe5081018357ff5cafde96b7e20/core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmitterImpl.java#L192) seems [to schedule a task with 0 timeout ](http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html#schedule(java.lang.Runnable,%20long,%20java.util.concurrent.TimeUnit)) on `ScheduledThreadPoolExecutor`. I didn't find a promise in documentation of this class that it will execute such task synchronously and won't just schedule it on thread pool with 0 initial timeout without waiting for it to execute.

**Comment by epot** [comment]
Ok thanks, I will try that.
