### ISSUE TITLE
APPLICATIONINSIGHTS_CONFIGURATION_CONTENT will not be considered in Azure Functions

### ISSUE THREAD

**Issue by franden** [microsoft/ApplicationInsights-Java#3761]
### Expected behavior
Content of environment variable APPLICATIONINSIGHTS_CONFIGURATION_CONTENT is considered by application insights agent

### Actual behavior
We are using a quarkus framework to create and run our Azure Function. We set the application insights setting "Collection level" to Recommended so that the application insights agent is automatically added. Because vertx communication is not visible in the Application Insights we would like to enable it via  entry in `applicationinsights.json`

```
{
   "preview":{
      "instrumentation":{
         "vertx":{
            "enabled":true
         }
      }
   }
}
```
we provided the content via environment variable APPLICATIONINSIGHTS_CONFIGURATION_CONTENT, but the issue is still present. We added some more configuration to APPLICATIONINSIGHTS_CONFIGURATION_CONTENT, but it seems that this doesn't have any effect. Even if the content is not a valid json, nothing happens (even no logs).

### To Reproduce

1. create quarkus application
2. deploy the application
3. set the "Collection level" to Recommended
4. set environment variable APPLICATIONINSIGHTS_CONFIGURATION_CONTENT with some content

### System information
Please provide the following information:
 - Quarkus 3.11.1 it uses azure-functions-java-library 3.1.0
 - Java 17
 - Azure Function OS: Linux
 - Azure Function Runtime version: 4.34.2.2
 - Used application insights agent version: ?? is not printed in the log

### Logs
-

### Screenshots
-

**Comment by franden** [comment]
@heyams any idea how to solve the problem

**Comment by heyams** [comment]
@franden I haven't had a chance to test it yet. Will get back to you soon. Thanks for reminding me.

**Comment by heyams** [comment]
@franden which plan are you using? consumption plan doesn't support this env var.

**Comment by franden** [comment]
> @franden which plan are you using? consumption plan doesn't support this env var.

Yes I awe are using the consumption plan. I can not find any documentation that this env var is not supported for consumption plan 🤔
But then, how I can pass the `applicationinsights.json` to my function? According to the [documentation](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#configuration-file-path) this file must be located in the same directory as applicationinsights-agent.jar.  If the "Collection level" is set to Recommended, agent jar is attached automatically. I am even not aware where the jar is located.

**Comment by heyams** [comment]
@franden we can introduce a new env var for you to use similar to [this](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#preview-instrumentations:~:text=APPLICATIONINSIGHTS_INSTRUMENTATION_AZURE_SDK_ENABLED,APPLICATIONINSIGHTS_INSTRUMENTATION_SPRING_SCHEDULING_ENABLED)

something like APPLICATIONINSIGHTS_INSTRUMENTATION_VERTX_ENABLE. will that work? This requires Azure function team to integrate with a newer version of java agent. It might take a while to get to production. Alternatively, I think there is a way to pass in a system property via the jvm arguments. Let me find out.

**Comment by heyams** [comment]
@franden Azure Functions has an instruction how to use a custom version of java agent. 
You can deploy json config along with the java agent in the same path.

https://github.com/Azure/azure-functions-java-worker/wiki/Distributed-Tracing-for-Java-Azure-Functions#customize-distribute-agent can you try it and let me know if that works? I haven't test it using consumption plan and I've reached out to functions team to confirm. system property I mentioned above won't work because consumption plan uses pool of pre-warmed up Java processes.

**Comment by heyams** [comment]
@franden we have updated the azure doc: https://learn.microsoft.com/en-us/azure/azure-monitor/app/monitor-functions#configuration. We decided not to make that env var available because of the pre-warm up pool.

**Comment by franden** [comment]
> @franden we have updated the azure doc: https://learn.microsoft.com/en-us/azure/azure-monitor/app/monitor-functions#configuration. We decided not to make that env var available because of the pre-warm up pool.

😢packaging of custom application insights agent means additional complexity for the build configuration.

I don't get the issue with the pre-warm up pool. Are there pre-warmed JVMs which already have attached application insights agents, so that it is not possible to add additional configuration?
