### ISSUE TITLE
Should there be constructor with URL argument too?

### ISSUE THREAD

**Issue by krnkhanna** [microsoft/ApplicationInsights-Java#3762]
I am trying to use TelemetryClient to track a request and found that I can add a URL only via a setter method. I think there should also be a method with URL like:

`
public RequestTelemetry(
      String name, URL url, Date timestamp, long duration, String responseCode, boolean success) 
`

https://github.com/microsoft/ApplicationInsights-Java/blob/f0a41702ac7cdb49f8efbc452b7951303b82bd86/classic-sdk/core/src/main/java/com/microsoft/applicationinsights/telemetry/RequestTelemetry.java#L36

**Comment by heyams** [comment]
@krnkhanna you can use `setUrl` from `RequestTelemetry`. 
We will deprecate track request API in the future. Please start using the OpenTelemetry way. Here is how:
https://opentelemetry.io/docs/languages/java/instrumentation/#create-spans

It's similar to this sample https://raw.githubusercontent.com/Azure-Samples/ApplicationInsights-Java-Samples/main/opentelemetry-api/exporter/TrackDependency/src/main/java/com/example/TrackDependency.java#:~:text=.setSpanKind(SpanKind.CLIENT). When you set `SpanKind` to `SERVER`, that becomes a request. 

Please let me know if you still need further assistance.
