### ISSUE TITLE
Sampling overrides with multiple telemetry types, with different default sampling rates

### ISSUE THREAD

**Issue by alokjoshi89** [microsoft/ApplicationInsights-Java#3789]
I'm using [sampling overrides](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-sampling-overrides) to apply sampling on different telemetry types. I'd like to know if I can use different default percentages for different telemetry types, along with their own overrides. A use case for me is:

- Overall default sampling percentage should be 100 (i.e. log everything). The exceptions to this are health check request spans (0% logging for health checks) and below overrides
- Default sampling for trace logs should be 10%, except for trace logs that contain `.audit`. Audit logs should be logged 100% of time
- Default sampling for dependency logs should be 25%

Here is a pseudo-config I'm thinking:

```
{
    "preview": {
        "sampling": {
            "percentage": 100                                                 => overall sampling percentage (100)
            "overrides": [
                {
                    "telemetryType": "trace",
                    "percentage": 10,                                          => overall sampling percentage for traces. This should override the default set at parent (100)
                    "overrides": [
                        {
                            "percentage": 100,                                => override the default sampling for traces (10%)
                            "attributes": [
                                <match with entries that contain `.audit` in the trace message>               => is this even possible? the trace message body is not part of attributes. Even if it was in the attributes, can we achieve this?
                            ]
                        }
                    ]
                },
                {
                    "telemetryType": "request",
                    "attributes": [
                        {
                            "key": "http.target",
                            "value": "/actuator/health",
                            "matchType": "strict"
                        }
                    ],
                    "percentage": 0
                },
                {
                    "telemetryType": "dependency",
                    "percentage": 25                                           => overall sampling percentage for dependencies
                }
            ]
        }
    }
}
```

I am also using [telemetry processors](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-telemetry-processors) to sample custom metrics, but for the above use case (since percentages are involved), I am not sure if I can use telemetry processors

**Comment by alokjoshi89** [comment]
@heyams thanks for your suggestion.

You are on point in mentioning that there must be an attribute that has `.audit` to be able to sample on it. I don't have such attribute on the audit logs (.audit is part of trace message, which isn't available as an attribute). So, I understand I'll be able to filter audit logs after adding such attribute.

There is a bigger overall concern for me atm with sampling. Any sampling on traces or dependencies will not work, **if** there is no sampling applied on requests, and if said traces and dependencies are in the span of those requests. I am looking to always sample traces and dependencies, even if their parent span (i.e. request) isn't sampled. Is this possible? The majority of my traces and dependencies (that I want to sample) are in scope of requests that I don't want to sample.

For example, I am trying this simple config (similar to [this](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-sampling-overrides#example-collect-100-of-telemetry-for-an-important-request-type) documented example)

{
    "sampling": {
        "percentage": 0
    },
    "sampling": {
        "overrides": [
            {
                "telemetryType": "request",
                "percentage": 100
            }
        ]
    },
}

All my traces and dependencies will still get logged because they are logged inside requests context, and I don't want to sample requests. I want to sample traces and dependencies even if they are in request span, and requests are not being sampled. Is it possible to achieve this.

**Comment by trask** [comment]
hi @alokjoshi89! the `percentage` is the percentage of the `telemetryType` that you want to capture (sample-in) and send to Azure Monitor, as opposed to the percentage that you don't want to capture (sample-out), so based on your use case I think you want something like this:

```
{
    "sampling": {
        "percentage": 100
    },
    "sampling": {
        "overrides": [
            {
                "telemetryType": "request",
                "percentage": 0
            },
            {
                "telemetryType": "trace",
                "percentage": 100
            },
            {
                "telemetryType": "dependency",
                "percentage": 100
            }
        ]
    }
}
```

**Comment by ripenedcat** [comment]
Hi Team,

What if it's just a basic logging without any attributes, is there still a way for us to drop logs with such pattern with Sampling Override or Processor? 
```
@RequestMapping("/")
@Controller
@Slf4j
public class TestCtrl {
@RequestMapping(value = "/string")
    @ResponseBody
    public String returnString() {
        log.info("Lucas Info");
        log.warn("Lucas warn");
        log.error("Lucas error");
        log.debug("Lucas debug");
        return "123";
    }
}
```


Raw logging from self-diagnostics as below. Can you please share with me an example on how can we drop logging with "Lucas Info"? 

```
2024-08-05 14:24:21.293+08:00 DEBUG c.m.a.a.i.exporter.AgentLogExporter - exporting log: SdkLogRecordData{resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.13.0, attributes={host.arch="amd64", host.name="CPC-lucas-W9M5G", os.description="Windows 11 10.0", os.type="windows", process.command_line="C:\Program Files\Microsoft\jdk-17.0.11.9-hotspot\bin\java.exe -XX:TieredStopAtLevel=1 -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -Dmanagement.endpoints.jmx.exposure.include=* -javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2023.3.6\lib\idea_rt.jar=54981:C:\Program Files\JetBrains\IntelliJ IDEA 2023.3.6\bin -Dfile.encoding=UTF-8", process.executable.path="C:\Program Files\Microsoft\jdk-17.0.11.9-hotspot\bin\java.exe", process.pid=11296, process.runtime.description="Microsoft OpenJDK 64-Bit Server VM 17.0.11+9-LTS", process.runtime.name="OpenJDK Runtime Environment", process.runtime.version="17.0.11+9-LTS", service.name="JavaAgent3.2.7RoleName", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.19.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=com.lucas.springboot2demo.controller.TestCtrl, version=null, schemaUrl=null, attributes={}}, epochNanos=1722839061273000000, spanContext=ImmutableSpanContext{traceId=b923e3d60c9434f89a516882d01373ce, spanId=228d6ed769f637a6, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, severity=INFO, severityText=INFO, body=StringBody{asString=**Lucas Info**}, attributes={applicationinsights.internal.item_count=1, applicationinsights.internal.operation_name="GET /string", thread.id=73, thread.name="http-nio-22222-exec-1"}, totalAttributeCount=4}
```
Thanks.

**Comment by alokjoshi89** [comment]
@trask yes, you're right. It was a copy paste error when I was setting the top level sampling percentage. Having said that, I'd still want something like below where I am logging all request types but not logging traces or dependencies. This works for traces and dependencies that are not in request scope (i.e. they are not logged) but all logs in request scope are logged, including traces and dependencies. 

```
{
    "sampling": {
        "percentage": 100                                            // I believe this is the default anyways so no need to declare specifically
    },
    "sampling": {
        "overrides": [
            {
                "telemetryType": "request",
                "percentage": 100
            },
            {
                "telemetryType": "trace",
                "percentage": 0
            },
            {
                "telemetryType": "dependency",
                "percentage": 0
            }
        ]
    }
}
```

**Comment by heyams** [comment]
@ripenedcat https://github.com/microsoft/ApplicationInsights-Java/blob/main/agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/sampling/AiSampler.java#L69

sampling override respects parent-based sampling percentage if trace/dependency is associated with a request. 
Can you try [inherited attribute](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#inherited-attribute-preview) to set a custom dimension programmatically on your request telemetry. It ensures inheritance by dependency and log telemetry. All are captured in the context of that request.

and then you can sampling overrides to filter logs/dependency based on that inherited attribute.

**Comment by ripenedcat** [comment]
Many thanks @alokjoshi89 @heyams , I have no further questions atm.
