### ISSUE TITLE
Please provide examples on how to unit test classes which use ADAL4J

### ISSUE THREAD

**Issue by Cpt-xx** [Microsoft/ApplicationInsights-Java#382]
This is linked to issue #361 which has been (unjustly in my view, or at least prematurely) closed.

Please provide more information as to to whom we need to turn to request better support for unit testing classes which use ADAL4J. Or at least specify why #361 was closed without comments as to why this was not an issue (and then providing some way of how to unit test classes using ADAL4J).

**Comment by beckylino** [comment]
thanks @Cpt-xx I have reopened the 361

**Comment by Cpt-xx** [comment]
Thanks @beckylino
