### ISSUE TITLE
Gradle module metadata is not published to Maven Central, while POM file does advertise it

### ISSUE THREAD

**Issue by evpaassen** [microsoft/ApplicationInsights-Java#3822]
### Expected behavior
I expect either:
1. Gradle module metadata to be published to Maven Central, or;
2. The `pom.xml` file that is published to Maven Central to NOT include the following section:
    ```xml
    <!-- This module was also published with a richer model, Gradle metadata,  -->
    <!-- which should be used instead. Do not delete the following line which  -->
    <!-- is to indicate to Gradle or any Gradle module metadata file consumer  -->
    <!-- that they should prefer consuming it instead. -->
    <!-- do_not_remove: published-with-gradle-metadata -->
    ```

### Actual behavior
Currently the published `pom.xml` file does include the section above ([see here](https://central.sonatype.com/artifact/com.microsoft.azure/applicationinsights-runtime-attach/3.5.3)), but the actual metadata file (e.g. `applicationinsights-runtime-attach-3.5.3.module`) is not published to Maven Central.

Under normal circumstances, it is not a fatal error when Gradle can't find the module metadata (that means, 404 from the repository). It just uses the POM instead. But there are many misconfigured enterprise Maven proxies out there, which do not return a 404 if a file can't be found, but some bogus content instead. For example, this may be the case when there is a fallback to some download site that returns a directory index HTML file instead. (Yes, I have seen this happen... 🙄)

The easiest way to fix this is to disable Gradle Module Metadata publication as described here, since the metadata currently isn't published anyway:
https://docs.gradle.org/current/userguide/publishing_gradle_module_metadata.html#sub:disabling-gmm-publication

### To Reproduce
Not needed, you can just look at the `pom.xml`.

### System information
Not applicable.

### Logs
Not applicable.

**Comment by evpaassen** [comment]
I'd be happy to submit a PR to fix this issue.

**Comment by heyams** [comment]
@evpaassen thank you for reporting!
