### ISSUE TITLE
Certificate-based AD authentication

### ISSUE THREAD

**Issue by karolmie1** [microsoft/ApplicationInsights-Java#3826]
**Is your feature request related to a problem? Please describe.**
Microsoft's recommendation for certificate authentication is mentioned directly on the "Certificates & Secrets" page in an application's page in Azure AD:

Credentials enable confidential applications to identify themselves to the authentication service when receiving tokens at a web addressable location (using an HTTPS scheme). For a higher level of assurance, we recommend using a certificate (instead of a client secret) as a credential.

**Describe the solution you would like**
I'd like to use certificate authentication instead of use-password authentication.

**Describe alternatives you have considered**
Currently I'm using user password-authentication.

**Comment by heyams** [comment]
@karolmie1 have you tried system assigned / user assigned managed identities? 
please check out this [doc](https://learn.microsoft.com/en-us/azure/azure-monitor/app/azure-ad-authentication?tabs=java#configure-and-enable-microsoft-entra-id-based-authentication), it will guide you through howto.

**Comment by karolmie1** [comment]
Only now I see that I omitted important piece of context. 
My setup is that I am using on premise servers (not azure cloud ones), and export telemetry to application insights. 
I am authenticating to application insights through 'enterprise application' with secrets - this works for my on premise setup, but I'd like to enhance that by using certificates. 

I'm afraid that setting up entra id on on premise servers will be challenging process, and of course I would love to keep my existing workflow.

I hope enough people will have same issue to justify doing this work.

**Comment by heyams** [comment]
We do not have plan to support this in Java agent.

Azure identity does support https://learn.microsoft.com/en-us/java/api/com.azure.identity.clientcertificatecredential?view=azure-java-stable. Can you try [Azure Monitor OpenTelemetry Exporter](https://learn.microsoft.com/en-us/java/api/overview/azure/monitor-opentelemetry-exporter-readme?view=azure-java-preview) by passing your own credential object programmatically via [this method](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/monitor/azure-monitor-opentelemetry-exporter/src/main/java/com/azure/monitor/opentelemetry/exporter/AzureMonitorExporterBuilder.java#L232C5-L232C80)?

I think this is what I would recommend.

**Comment by karolmie1** [comment]
Thank you for considering my request.
If you do not plan to support this feature in Java agent, then let's close this ticket.
