### ISSUE TITLE
TransmissionNetworkOutput sending loop should delay for all exceptions and not dispose connection all the time

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-Java#385]
There are other exceptions that needs delay for the next loop. Otherwise on azure web apps SDK takes out all the available connections.

https://github.com/Microsoft/ApplicationInsights-Java/blob/master/core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionNetworkOutput.java#L131

**Comment by dhaval24** [comment]
@SergeyKanzhelev the delay mechanism is now in place for all the exceptions. Please check latest master if interested. Quick question though, I see that current default backoff time is set o 300 sec which can be sometimes too much in high throughput applications. We have seen this with some of the users resulting in lost telemetry. A dirty fix was to have 3 immediate retries before going to 300 seconds backoff. This would be fix unblocking several people though something else could be ideal. Let me know your thoughts and I would be closing this one.

**Comment by SergeyKanzhelev** [comment]
spin-lock's like retries sounds good. I remember I caused this connections starvation when I had some packages mismatch and it kept failing for me with the exception un-expected in code. If this is fixed - great, please close the issue.

**Comment by dhaval24** [comment]
https://github.com/Microsoft/ApplicationInsights-Java/blob/7a5e572b2ffd3256898c6bd05dc3bec6754e3629/core/src/main/java/com/microsoft/applicationinsights/internal/channel/common/TransmissionNetworkOutput.java#L172

Here is the fix. We now back-off for any kind of exceptions.  Here is the PR for retrying 3 times before Back_off #501
