### ISSUE TITLE
Ability to collect performance counter data at 10 second intervals 

### ISSUE THREAD

**Issue by beckylino** [microsoft/ApplicationInsights-Java#387]

**Comment by littleaj** [comment]
It appears this is already available via:
collectionFrequencyInSec: https://github.com/microsoft/ApplicationInsights-Java/wiki/ApplicationInsights.XML#performancecounters
FlushIntervalInSeconds: https://github.com/microsoft/ApplicationInsights-Java/wiki/ApplicationInsights.XML#channel
