### ISSUE TITLE
Traces Not Appearing in Application Insights Despite Sampling Configuration

### ISSUE THREAD

**Issue by jacopocarlini** [microsoft/ApplicationInsights-Java#3926]
### Expected behavior
I expect the sampling overrides to work correctly. I want to capture 100% of the traces if the message starts with `Invoking`.

### Actual behavior
The override is ignored. 

### To Reproduce

I'm using Spring Boot v3.2.3 along with the latest `applicationinsights-agent-3.6.0.jar`.

Below is my `applicationinsights.json` configuration:

```
{
  "selfDiagnostics": {
    "destination": "console",
    "level": "INFO"
  },
  "sampling": {
    "percentage": 0,
    "overrides": [
      {
        "telemetryType": "dependency",
        "percentage": 5
      },
      {
        "telemetryType": "trace",
        "percentage": 100,
        "attributes": [
          {
            "key": "message",
            "value": "Invoking .*",
            "matchType": "regexp"
          }
        ]
      },
      {
        "telemetryType": "exception",
        "percentage": 100
      },
      {
        "telemetryType": "request",
        "percentage": 100
      }
    ]
  }
}
```

The application produces two log entries:
```
"log.level": "INFO","message":"Invoking API operation healthCheck",
"log.level": "INFO","message":"Ignore this log"
```

However, I don't see any traces appearing in Application Insights.

### System information
Please provide the following information:
 - SDK Version: 3.6.0
 - OS type and version: on docker image `eclipse-temurin:17-jre`
 - Application Server type and version (if applicable):
 - Using spring-boot? yes
 - Additional relevant libraries (with version, if applicable):

**Comment by jacopocarlini** [comment]
Thank you for your reply, @jeanbisutti.

I’ve updated my Java code as follows:

```java
log.info("Ignore this log info");
Marker marker = MarkerFactory.getMarker("aMarker");
log.info(marker, "Invoking API operation healthCheck");
````

I’m using the following configuration:

```json
{
  "selfDiagnostics": {
    "destination": "console",
    "level": "INFO"
  },
  "preview": {
    "captureLogbackMarker": true
  },
  "sampling": {
    "percentage": 0,
    "overrides": [
      {
        "telemetryType": "dependency",
        "percentage": 5
      },
      {
        "telemetryType": "trace",
        "percentage": 100,
        "attributes": [
          {
            "key": "logback.marker",
            "value": "aMarker",
            "matchType": "regexp"
          }
        ]
      },
      {
        "telemetryType": "exception",
        "percentage": 100
      },
      {
        "telemetryType": "request",
        "percentage": 100
      }
    ]
  }
}
```
However, the logs are still not being sent to Application Insights. Could you help me identify what I might be missing?

Additionally, could you share any documentation that includes a list of the default attributes I can use?

Thank you

**Comment by jeanbisutti** [comment]
@jacopocarlini Unfortunately a log marker attribute can't be used today with the sampling override (array attribute).

**Comment by jeanbisutti** [comment]
@jacopocarlini Another option could be to add an MDC attribute and use it in the sampling override:

```java
    MDC.put("attributeKey", "attributeValue");
    try {
      logger.info("Log message");
    } finally {
      MDC.remove("attributeKey");
    }
````
