### ISSUE TITLE
Link to download the agent is broken

### ISSUE THREAD

**Issue by lcf** [microsoft/ApplicationInsights-Java#3937]
https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-enable?tabs=java

![Image](https://github.com/user-attachments/assets/13922022-dbfb-4318-a8f3-946de8280f5d)

**Comment by heyams** [comment]
@lcf thanks for reporting. will push a fix soon.

**Comment by heyams** [comment]
@lcf fix has been merged and will be published soon.

in the meantime, please use this latest version [3.6.1](https://github.com/microsoft/ApplicationInsights-Java/releases/download/3.6.1/applicationinsights-agent-3.6.1.jar)
