### ISSUE TITLE
Sampling override applicationinsights-java-agent telemetryType requests not work

### ISSUE THREAD

**Issue by serignemodou** [microsoft/ApplicationInsights-Java#3949]
**Expected behavior**
I want to 
- capture 100% for only some requests url that contains path /parcours
- Not capture all the rest
I'm following this [document](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-sampling-overrides) 

**Actual behavior**
The override is ignored.

**To Reproduce**
I'm using 
- Spring Boot v3.2.3 
- Applicationinsights-agent  3.5.1

Below is my applicationinsights.json configuration:

```
{
	"connectionString": "key-applicationinsights"
	"role": {
		"name": "demo name"
	},
	"instrumentation": {
		"logging": {
			"level": "TRACE"
		}
	},
	"selfDiagnostics": {
		"destination":"file+console",
		"level": "DEBUG",
		"file": {
			"path": "applicationinsights.log",
			"maxSizeMb": 5,
			"maxHistory": 1
		}
	},  
	"sampling": {
		"percentage": 0,
		"overrides":  [ 
			{
				"telemetryType": "request",
				"attributes": [
				  {
					"key": "url.path",
					"value": ".*/parcours/.*",
					"matchType": "regexp"
				  }
				],
				"percentage": 100
			}
		]
	}
}
```

**Logs result on app insights requests ![Image](https://github.com/user-attachments/assets/49c821b6-2c1d-496c-8a31-88452e1cf4b1)
As you can see, all the logs are collected, that's means the sampling override is ignored.

**Comment by serignemodou** [comment]
By looking, the span attributes in the logs, i found that my key, value are not directely on the attributs list 
 attributes=AttributesMap{data={url.scheme=https, network.peer.port=39621, http.request.method=GET, http.route=/app/v1/health-check, **url.path=/app/v1/parcours/utilisateurs**}

How can I access this value key ?

**Comment by serignemodou** [comment]
In the first line no, i made a mistake on the copy.
I have no warning on the agent

**Comment by serignemodou** [comment]
it seems that the span does not record the attributes, on the agent logs I see the attribute field empty attributes={}

**Comment by trask** [comment]
what about the log you pasted above? that one looked like it picked up `url.path`:

> attributes=AttributesMap{data={url.scheme=https, network.peer.port=39621, http.request.method=GET, http.route=/app/v1/health-check, url.path=/app/v1/parcours/utilisateurs}

**Comment by serignemodou** [comment]
One the logs, i have two attributes lines:
An Attributes with empty content: attributes={} 
And this attributes=AttributesMap{data={url.scheme=https, network.peer.port=39621, http.request.method=GET, http.route=/app/v1/health-check, url.path=/app/v1/parcours/utilisateurs}

However , the request filter with attributes url.path does not work, that's why i ask if the filter use the first attribute (Attributes with empty content) or not ?
And how i can use the attributes=AttributesMap in my applicationinsights.json config

**Comment by trask** [comment]
> attributes={service.name=‘my-service-name’, telemetry.sdk.language=‘java’, telemetry.sdk.name=‘opentelemetry’, telemetry.sdk.version=‘1.35.0’}}

these are opentelemetry resource attributes and are not supported by the sampling overrides

`http.route` isn't supported by sampling overrides b/c it is typically set after span start

`url.path` should work

would you be able to create a small repro that we can look at to see what the issue might be?

**Comment by serignemodou** [comment]
Ok, 
Unfortunately the url.path not work for me.
I have a repo demo, i will invite.

**Comment by trask** [comment]
hi @serignemodou, thanks for the demo app. I ran it locally and hit `http://localhost:8080/app/v1/health-check/test` and didn't see any request telemetry captured.

How does it work for you locally (not in App Services)? thanks

**Comment by serignemodou** [comment]
Hi @trask 
Exact, it work well locally.
And why it doesn't work on App Service ?

**Comment by trask** [comment]
Are you using the Application Insights / App Services Integration? that will automatically add the -javaagent which will take precedence over the runtime attach, and so won't pick up your json configuration file

**Comment by serignemodou** [comment]
Hi,
I'm using applications insights [enabled programmatically](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-spring-boot#enabling-programmatically) 

- Langage: spring boot
- applicationinsights.json location: src/main/resources/applicationsinsights.json
- Package on pom.xml to load file config: applicationinsights-runtime-attach and applicationinsights-core
- Package version 3.5.1
- Load file config on startup application in main java function
`	public static void main(String[] args) {
		ApplicationInsights.attach();
        SpringApplication.run(DemoApplication.class, args);
    }`

**Comment by serignemodou** [comment]
Hi,
The problem has been solved, the connectionString line in the applicationinsights.json file had to be deleted because its contents are automatically added as an environment variable to the app service.

Thanks @trask for you support

**Comment by serignemodou** [comment]
I close the issue
