### ISSUE TITLE
Java Agent: Dependency sampling overrides stops working after adding span processor

### ISSUE THREAD

**Issue by ralarcon** [microsoft/ApplicationInsights-Java#3977]
### Expected behavior
I expect the pre-existing sampling override continue to match and filter the dependencies. Also to be able to filter out the dependencies based on the new sampling override

### Actual behavior
The dependencies previously being filtered appears again. I know the processor I've added to the config applies to all spans (I have plans later to reduce the scope by using an `include` config, but I was expecting to apply the filtering over the spans with the new attribute.

### To Reproduce

I had a sampling override as follows which was working ok:
``` json
    "sampling": {
        "overrides": [
            {
                "telemetryType": "dependency",
                "attributes": [
                    {
                        "key": "messaging.destination.name",
                        "value": "sys.edge.container",
                        "matchType": "strict"
                    }
                ],
                "percentage": 0
            }
        ]
    }
```

I'm trying to filter out some other dependencies, but the spans didn't have the attributes I need to make it, so I tried to add a span processor to make the info I need available:

``` json
    "preview": {
        "captureLoggingLevelAsCustomDimension": true,
        "liveMetrics": {
            "enabled": false
        },
        "processors": [
            {
                "type": "span",
                "name": {
                    "toAttributes": {
                        "rules": [
                            "(?<myAppSpanName>.*?)$"
                        ]
                    }
                }
            },
            {
                "type": "span",
                "name": {
                  "fromAttributes": [
                    "myAppSpanName"
                  ]
                }
            }
        ]
    },
    "sampling": {
        "overrides": [
            {
                "telemetryType": "dependency",
                "attributes": [
                    {
                        "key": "messaging.destination.name",
                        "value": "wos.myApp.sys.edge.container",
                        "matchType": "strict"
                    }
                ],
                "percentage": 0
            },
            {
                "telemetryType": "dependency",
                "attributes": [
                    {
                        "key": "myAppSpanName",
                        "value": "Facility to MyApp Event",
                        "matchType": "strict"
                    }
                ],
                "percentage": 0
            }
        ]
    }
```
I needed to add two processors: one to add the `myAppSpanName` to the span attributes, the second to restore the original name of the span. The processor looks like working properly.

I notice the exported data for the span has changed, now instead the `SpanData` it starts with `DelegatingSpanData`, not sure if this is the root cause or it is the precedence of the operations executed by processors and sampling overrides:
Before:
``` text
SpanData{
    spanContext=ImmutableSpanContext{
    traceId=c3c7f37e49948eb41acaf91da1904823, 
    spanId=dcc6a0f5a71c1473, 
    traceFlags=01, 
    traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, 
    parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, resource=Resource{schemaUrl=null, attributes={service.name="myapp-pre-weu-atx", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.40.0"}}, 
    instrumentationScopeInfo=InstrumentationScopeInfo{name=com.fx.telemetry, version=null, schemaUrl=null, attributes={}}, 
    name=Facility To MyApp Event, 
    kind=INTERNAL, 
    startEpochNanos=1733311243116217918, 
    endEpochNanos=1733311243732459467, 
    attributes=AttributesMap{
        data={
            thread.id=54, 
            thread.name=RxComputationThreadPool-1
        },
    capacity=128, totalAddedValues=2
    }, 
    totalAttributeCount=2, 
    events=[], 
    totalRecordedEvents=0, 
    links=[], 
    totalRecordedLinks=0, 
    status=ImmutableStatusData{statusCode=UNSET, description=}, hasEnded=true}
```

After:
``` text
DelegatingSpanData{
    spanContext=ImmutableSpanContext{
        traceId=d2b1d6a62f1bf0b83bc0ecd1a4ad855a, 
        spanId=efa47cc6eefd29b9, 
        traceFlags=01,
        traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, 
        parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, resource=Resource{schemaUrl=null, attributes={service.name="myapp-pre-weu-atx", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.40.0"}}, 
        instrumentationScopeInfo=InstrumentationScopeInfo{name=com.fx.telemetry, version=null, schemaUrl=null, attributes={}}, 
        name=Facility To MyApp Event, 
        kind=INTERNAL, startEpochNanos=1733350046244777696, 
        attributes={
            myAppSpanName="Facility To MyApp Event", 
            thread.id=51, 
            thread.name="RxComputationThreadPool-1"
            }, 
        events=[], 
        links=[], 
        status=ImmutableStatusData{statusCode=UNSET, description=}, endEpochNanos=1733350046247381769, hasEnded=true, totalRecordedEvents=0, totalRecordedLinks=0, totalAttributeCount=2}
```

### System information
Please provide the following information:
 - SDK Version: java:3.5.4
 - OS type and version: Ubuntu 
 - Application Server type and version (if applicable): containerized Java app
 - Using spring-boot? nop, but using spring.
 - Additional relevant libraries (with version, if applicable):
   -  c.m.applicationinsights.agent - Java version: 21.0.2, vendor: Eclipse Adoptium
   - Application Insights Java Agent 3.5.4

**Comment by jeanbisutti** [comment]
Hi @ralarcon

The telemetry processors are executed when the spans are exported. The attributes added by the telemetry processors are not accessible by the sampling override.

> I'm trying to filter out other dependencies, but the spans don't have the attributes I need to do this.

Could you please elaborate?

Perhaps removing some instrumentations would meet your needs: https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#suppress-specific-autocollected-telemetry

**Comment by ralarcon** [comment]
We managed to add a custom attribute to the span to enable filtering using the sampling overrides. 

To mention that this [point in the documentation](https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-sampling-overrides#:~:text=Only%20attributes%20set%20at%20the%20start%20of%20the%20span%20are%20available%20for%20sampling) is really to  be able to apply the sampling. 

If you add the attributes once the span is started those are not captured by the agent. 

Thanks.
