### ISSUE TITLE
Rename applicationinsights-core package to simply applicationinsights

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-Java#399]
It will be easier to discover if the `applicationinsights-core` package will be named just `applicationinsights`. Or `applicationinsights-api`. The term `core` is overloaded.

**Comment by dhaval24** [comment]
@SergeyKanzhelev closing this one for now as we do not have any concrete plans for this. We can reopen when we think of rebranding,
