### ISSUE TITLE
Configure Alerts based on Analytic Queries

### ISSUE THREAD

**Issue by SaiVikas-Dharmaraju** [Microsoft/ApplicationInsights-Java#402]
Hi,

Currently we can setup Alerts in App Insights based on predefined metrics. Can we have means to setup alerts on a granular level.

For instance we can configure Alerts now based on Server Exceptions which is generic to all the exceptions that are thrown in a webapp, but we cannot set alert rules specific to one type of exception. 

Since AI Query Analytics already powers dashboard, can we have a functionality which can enable us to trigger alerts based on AI queries, it will give us the liberty to setup alerts based on our custom needs instead of relying on predefined metrics alone.

Thanks.

**Comment by beckylino** [comment]
Thank you for your feedback! 

There is a private preview for this feature - please email us vsai (at) microsoft.com, with your subscription IDs and we will be happy to enable this for you.

You can up vote this feature request on user voice here: https://feedback.azure.com/forums/357324-application-insights/suggestions/14428134-add-alerts-based-on-results-of-analytics-queries

**Comment by SaiVikas-Dharmaraju** [comment]
@beckylino  : Our IT team is currently working with Azure Enterprise support team to get this enabled. Thanks for the timely information. 

I did upvote this feature. :)
