### ISSUE TITLE
Should use X-Forwarded-For as Client IP when present

### ISSUE THREAD

**Issue by klazuka** [microsoft/ApplicationInsights-Java#404]
Many load balancers / proxies automatically set the `X-Forwarded-For` HTTP request header to indicate the original IP of the client. The Application Insights SDK for .NET uses this header when present to fill in the client IP, but the Java SDK does not. For more details, see http://apmtips.com/blog/2016/07/05/client-ip-address/

The fix would be to copy what the .NET SDK does: handle `X-Forwarded-For` automatically by default, while still allowing the ability to specify an alternative HTTP header name for the IP.

**Comment by littleaj** [comment]
@trask @AlexKlimovMS seems reasonable and still relevant

**Comment by trask** [comment]
This is fixed now in [Preview.7](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.0-PREVIEW.7)
