### ISSUE TITLE
NoClassDefFoundError thrown from application insights

### ISSUE THREAD

**Issue by xscript** [microsoft/ApplicationInsights-Java#416]
When used in a Maven plugin, AI java SDK throws `NoClassDefFoundError` after the maven build is finished successfully. Please refer to below snapshot.
![image](https://user-images.githubusercontent.com/2300784/29747564-2cebfc54-8b31-11e7-9627-12e73ec21170.png)

It doesn't always happen. But for certain scenarios (such as unexpected exception in Maven plugin), this error will also be thrown.

Not sure what's the root cause here. Suggestion is to add `UncaughtExceptionHandler` for DataSender and Coordinator threads at [here](https://github.com/Microsoft/ApplicationInsights-Java/blob/master/core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/QuickPulse.java#L81-L87), so that such exception is properly handled (for my case, exception message should not be displayed to user).

**Comment by dhaval24** [comment]
@xscript Can you please clarify on this issue. I believe you are getting the error when you are including AI-Java SDK in your maven project and when you try to build your maven project maven throws this exception? 

Or you are referring to building the Java-SDK? Also please tell us what all steps you took in either case to have a better understanding.

**Comment by dhaval24** [comment]
@xscript as far as I remember I have very recently added AI (1.0.9) as a maven dependency in my maven project and it build successfully. I assume you are referring to the same of adding Application Insights as a maven dependency by following the steps mentioned on the documentation page.

If you are doing something in a different way can you please expand on how you are including AI in Maven Plugin so that I can replicate the bug and see what the fix can likely be. Thanks a lot in advance.

**Comment by xscript** [comment]
@dhaval24 
This is not a build issue of AI SDK. This is a runtime issue when using AI SDK in a maven plugin.

### Maven Plugin project
In this project, AI SDK is referenced as the documentation. Version 1.0.9 is used. Building is successful in this project.
You can find the usage as listed below:
- https://github.com/Microsoft/azure-maven-plugins/blob/master/azure-maven-plugin-lib/pom.xml#L139-L149
- https://github.com/Microsoft/azure-maven-plugins/blob/master/azure-functions-maven-plugin/src/main/resources/ApplicationInsights.xml

### Normal Maven project
In this project, above Maven Plugin is referenced in `pom.xml`.
`mvn package` will trigger the execution of above Maven Plugin, hence AI SDK will be called to report telemetry.

The issue i am reporting here is after the execution of `mvn package`, `NoClassDefFoundError` is thrown from AI as below snapshot.
![image](https://user-images.githubusercontent.com/2300784/29803628-ed519380-8caf-11e7-91e6-0b23def16b11.png)

It happens in certain scenario. For example, when the application is crashed due to unexpected exception, this error will be thrown from AI at the same time.

**Comment by dhaval24** [comment]
@xscript Thank you so much for the detailed explanation. I got it, that when you instrument Application Insights as Maven project and then try to run mvn package you get the error above but not always. I did recently instrumented AI in the same way in the maven project however as you mentioned it does not happen always I might not hit the same condition and therefore not hit the same issue. I will see if the issue replicates.

**Comment by dhaval24** [comment]
@xscript I have tried to replicate the same thing in my test maven application:
My pom.xml looks as follows:

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>FirstMavenWebApp</groupId>
  <artifactId>FirstMavenWebApp</artifactId>
  <packaging>war</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>FirstMavenWebApp Maven Webapp</name>
  <url>http://maven.apache.org</url>
  <properties>
      <jdk.version>1.8</jdk.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
      <dependency>
          <groupId>com.microsoft.azure</groupId>
          <artifactId>applicationinsights-web</artifactId>
          
          <version>1.0.9</version>
      </dependency>

      <dependency>
          <groupId>javax.servlet</groupId>
          <artifactId>javax.servlet-api</artifactId>
          <version>3.1.0</version>
          <scope>provided</scope>
      </dependency>
  </dependencies>
  <build>
    <finalName>FirstMavenWebApp</finalName>
      <plugins>
          <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-compiler-plugin</artifactId>
              <version>3.5</version>
              <configuration>
                  <source>1.8</source>
                  <target>1.8</target>
              </configuration>
          </plugin>
          
      </plugins>
  </build>
</project>

I am using Intellij Idea for the Maven Application and I am able to execute mvn package without any issues. It may be possible that this happens only in certain scenario.  I am not which of them are exactly those. If you come across an exact point after this thing happens would be helpful to debug.

**Comment by dhaval24** [comment]
@xscript were you able to resolve the issue with the reference to above?

**Comment by dhaval24** [comment]
@xscript please let us know if this issue is persistent. If so please provide us steps to reproduce your issue? Also Application Insights SDK used in Azure Functions here?

**Comment by xscript** [comment]
@dhaval24 Yes, we are using AI to instrument our maven plugin for Azure Functions.
Right now we catch the exception from AI as a work around.

**Comment by dhaval24** [comment]
@xscript can you please give this a shot with latest AI java SDK version 2.0.1 and let me know if the issue persist?

**Comment by jdneo** [comment]
Have another try, got another different error: 

java.lang.NoClassDefFoundError: com/microsoft/applicationinsights/core/dependencies/http/impl/conn/PoolingHttpClientConnectionManager$InternalConnectionFactory

I'm using MAC

**Comment by dhaval24** [comment]
@jdneo at this point I am totally confused. I don't see this exception coming to anyone else. To me it seems that some how you are not able to import the whole package, and some files are missing especially the ones that are repackaged. To diagnose this issue better, I would suggest that you upload a trim down version of your application.

Also what is the environment where you are tying to use the SDK?

**Comment by jdneo** [comment]
@dhaval24 I also tried to downgrade the AI to 1.0.10. Though still getting the `java.lang.NoClassDefFoundError`, but the command will not be hanged.

**Comment by littleaj** [comment]
For this you could try disabling QuickPulse: https://github.com/microsoft/ApplicationInsights-Java/wiki/ApplicationInsights.XML#quickpulse
Alternatively or in addition, you could set the `MaxTelemetryBufferCapacity` to 1, https://github.com/microsoft/ApplicationInsights-Java/wiki/ApplicationInsights.XML#channel, which would send telemetry as soon as it was queued. Let us know if this does not fix the issue.

**Comment by Flanker32** [comment]
@littleaj Thanks for your help, tried disable QuickPulse and set MaxTelemetryBufferCapacity to 1, but this issue still occurs, will throw NoClassDefFoundError and come into endless loop
