### ISSUE TITLE
Status monitor for Java

### ISSUE THREAD

**Issue by beckylino** [microsoft/ApplicationInsights-Java#417]
Status monitor gather a lot of useful info, it would be nice getting a status monitor for other web servers (Tomacat, Apache), hooking into Java SDK too, and compatible with Windows and Linux.
Also, status monitor for other types of servers like SQL Server or Oracle, or non web based app servers would be usefull to understand system behaviors for end to end analysis.
Moreover, installing an agent while system is already in production is a change easy to test and apply, whereas asking for a new release including custom telemetry can take time (depending on continous deployment efficiency).

**Comment by SergeyKanzhelev** [comment]
To the extend `javaagent` is already behaving like a Status Monitor. It is something you install on java machine, not individual app and it allows you to instrument certain dependencies in runtime.

Are you looking into automatic instrumentation capability of Status Monitor?
