### ISSUE TITLE
java.lang.VerifyError (ByteCode Instrumentation Error) while collecting SQL dependencies 

### ISSUE THREAD

**Issue by dhaval24** [Microsoft/ApplicationInsights-Java#418]
When collecting SQL dependency using Java Agent with Tomcat as web-server I hit following error:

java.lang.VerifyError: Expecting a stackmap frame at branch target 19
Exception Details:
  Location:
    oracle/jdbc/driver/OracleStatement.removeChild(Loracle/jdbc/driver/OracleStatement;)V @5: if_acmpne
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2b2a b401 6ba6 000e 2a2b b401 6fb5 016b
    0x0000010: a700 202a b401 6b4d 2cb4 016f 2ba5 000b
    0x0000020: 2cb4 016f 4da7 fff3 2c2b b401 6fb5 016f
    0x0000030: 2b01 b501 6d2b 01b5 016f b1            

	oracle.jdbc.driver.T4CDriverExtension.allocateStatement(T4CDriverExtension.java:56)
	oracle.jdbc.driver.PhysicalConnection.createStatement(PhysicalConnection.java:1507)
	oracle.jdbc.driver.PhysicalConnection.createStatement(PhysicalConnection.java:1478)
	com.Servlet.doPost(Servlet.java:43)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.doFilter(WebRequestTrackingFilter.java:81)

The possible reason is due to the stricter rules of byte code instrumentation induced in JDK 1.7+

One work around is to use the following flag in in the tomcat startup script:
**Xverify:none**

This flag suppress the byte code validation but might violate security.

**Comment by dhaval24** [comment]
Here are the links which explain this issue in more detail:
http://blog.takipi.com/oracles-latest-java-8-update-broke-your-tools-how-did-it-happen/
https://dzone.com/articles/oracles-latest-java-8-update
http://chrononsystems.com/blog/java-7-design-flaw-leads-to-huge-backward-step-for-the-jvm

**Comment by SergeyKanzhelev** [comment]
So did you fix the underlying problem of injecting an invalid code?

**Comment by dhaval24** [comment]
@SergeyKanzhelev we were not able to identify a fix yet. As explained in the blogposts above from JDK 1.7 concept of StackMaps was introduced and bytecode verification became more stricter. That has created this issue. As of what I had read one of the changes was that from now you cannot inject any code before the call of super() constructor. I don't have a fix yet but they say that JDK1.9 will mostly have this fix. If you have any ideas on fixing this please let me know

**Comment by SergeyKanzhelev** [comment]
so you pinpoint the problem to the constructor call instrumentation? Why do you need to instrument constructors at all?

**Comment by dhaval24** [comment]
That is one thing that might be happening. Haven't taken a deep look into how and where our agent does instrumentation. It might or might not be doing constructor call instrumentation. I will have to look more deeply into this.

**Comment by dhaval24** [comment]
Fixed in #449
