### ISSUE TITLE
Content-Length field in response object for Request Telemetry

### ISSUE THREAD

**Issue by Ramji-S** [Microsoft/ApplicationInsights-Java#424]
Is there a way to support Content-Length by default in AppInsights for the response object to be part of the Request Telemetry ? This is needed in cases where we need to record the amount of bytes sent back in Response typically for GET HTTP APIs and currently we do not see that in Request Properties as part of Telemetry

**Comment by SergeyKanzhelev** [comment]
You can put it into [`Metrics` collection](https://github.com/Microsoft/ApplicationInsights-Java/blob/10becb08b728463c9415484d974f47dd4d1e80d0/core/src/main/java/com/microsoft/applicationinsights/telemetry/RequestTelemetry.java#L114). See more in [docs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-custom-events-metrics#properties)

**Comment by SergeyKanzhelev** [comment]
Please re-open if you have more quesitons

**Comment by Ramji-S** [comment]
Thanks. We do make use of Custom Properties to record Content-Length to push to AI via Telemetry Module. I was asking if this header can be natively supported by AI similar to other fields like ResponseTime etc. Content-Length for incoming requests with payloads are pushed properly to AI today because this is already set by the container, in our case Tomcat and is available for the Telemetry Module. But for the outgoing payload size, this is not available at filter level because, the value gets sets at the container level. We have a workaround for recording this by setting a custom property in HTTP response by calculating the size of the payload to push to AI but it will be easier if this can be implicitly supported.
