### ISSUE TITLE
Portal shows Redis dependency as successful whereas browser shows 500

### ISSUE THREAD

**Issue by dhaval24** [microsoft/ApplicationInsights-Java#425]
When capturing Redis dependency using the unpublished build (most recent master), the portal shows as dependency successful whereas the browser throws 500.

Steps to repro: 1. Instrument app with Redis and AppInsights with Agent. 
2. Set Redis Password as incorrect while authorizing connection.

Attached are the pictures about the same.
![bug](https://user-images.githubusercontent.com/16353121/30443513-ab75bac2-9934-11e7-93fe-e154b22757bf.PNG)
![bug1](https://user-images.githubusercontent.com/16353121/30443514-ad370758-9934-11e7-8fe0-9769d4b974d1.PNG)

**Comment by dhaval24** [comment]
tracking with #600

**Comment by littleaj** [comment]
This is a separate issue. This has to do with DependnecyTelemetry, #600 has to do with RequestTelemetry.

**Comment by dhaval24** [comment]
@littleaj yes however when this happens it should throw 500 correct?

**Comment by littleaj** [comment]
@dhaval24 The response code for the dependency should be the code in the Redis server's reply (probably 401). The response from the application calling Redis can return whatever it wants; the default is 500.

**Comment by dhaval24** [comment]
So what should be there ideally here in the the request telemetry's response code?
