### ISSUE TITLE
Native Java HTTP calls are not captured

### ISSUE THREAD

**Issue by dhaval24** [microsoft/ApplicationInsights-Java#427]
The HTTP dependency calls made via URL (native java class) are not currently captured with Agent.

**Comment by dhaval24** [comment]
@Dmitry-Matveev @grlima  #567 where I instrumented `java.net.URI` to derive URL, host and path should fix this issue also where Native Java HTTP calls are not getting intercepted. Though I need to test and confirm. What do you think?

**Comment by littleaj** [comment]
Fixed in #971
