### ISSUE TITLE
App Insights Alert Mail Customization

### ISSUE THREAD

**Issue by SaiVikas-Dharmaraju** [Microsoft/ApplicationInsights-Java#430]
Hi,

Can we have support to Customize the Email Subject and mail content of the Alert mails today?

To be precise we want support at-least to change the app name/ application in mail subject and mail body.
Today AI alerts substitutes AI  container name in Subject and mail body, instead of this we want the mails to contain the app name[ internal component name ] that AI monitors.

TIA.

**Comment by SergeyKanzhelev** [comment]
Please file a feature request at [User Voice](http://aka.ms/aiuservoice). You can always configure [web hooks](https://docs.microsoft.com/azure/monitoring-and-diagnostics/insights-webhooks-alerts) for alerts and send customizable e-mails this way.
