### ISSUE TITLE
Jackson issue

### ISSUE THREAD

**Issue by valamelkor** [microsoft/ApplicationInsights-Java#439]
Hi, All

I have a strange issue: It seems that AppInsights filter somehow prevents Jackson from properly parsing requests. 

We are using Spring Boot 1.5.3 with Java 8 and latest AppInsights Web 1.0.10
AppInsights initialization code
```java
@Configuration
@ComponentScan("com.microsoft.applicationinsights.web.spring")
@EnableAutoConfiguration
public class ApplicationInsightsConfiguration {

    @Bean
    public FilterRegistrationBean AiFilterRegistration() {

        final FilterRegistrationBean registration = new FilterRegistrationBean();
        registration.setFilter(new WebRequestTrackingFilter());
        return registration;
    }
}
```

I have the following Jackson config in application.yaml
```yaml
spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
```
and Jackson config bean
```java
@Configuration
public class JacksonConfig {

    /**
     * @return Jackson jdk8 module to be registered with every bean of type
     * {@link ObjectMapper}
     */
    @Bean
    public Module jdk8JacksonModule() {
        return new Jdk8Module();
    }
}
```
I have parsing errors with Application Insights filter enabled. It looks like Jackson configuration is ignored and switched to default (camel case), so all parsing mechanics is broken...

**Comment by dhaval24** [comment]
@valamelkor thank you for reporting this issue. We will fix it in upcoming updates.

**Comment by littleaj** [comment]
@valamelkor Do you still see this issue with the latest version, 2.4.0?
