### ISSUE TITLE
Several tests' asserts have expected/actual parameters reversed

### ISSUE THREAD

**Issue by littleaj** [Microsoft/ApplicationInsights-Java#440]
JUnit's `assertEquals` method has the form `assertEquals(X expected, X actual)`, but most of the tests here have expected and actual in the wrong parameter slot. The result _should_ be the same (since equality is symmetric), but the test output will be incorrect. For example, assertEquals produces the output "java.lang.AssertionError: expected: <E>, but was: <A>" where _E_ is the value you expect and _A_ is the actual value read from the code under test. Current tests will have those values reversed which can cause confusion while debugging.

**Comment by dhaval24** [comment]
@littleaj do we have a PR on this issue already?

**Comment by littleaj** [comment]
@dhaval24, Not that I know of.
