### ISSUE TITLE
TrackException(e) does not work in 1.0.10

### ISSUE THREAD

**Issue by MS-TimothyMothra** [Microsoft/ApplicationInsights-Java#441]
The following snippet works in 1.0.9 but does NOT work in 1.0.10.

Events are collected, but Exceptions are not.

```
public class DmServlet extends HttpServlet {
    private TelemetryClient client = new TelemetryClient();

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

        EventTelemetry customEvent = new EventTelemetry("DmServlet Call");
        customEvent.getProperties().put("Name", "Demo-2");
        client.trackEvent(customEvent);

        sendExceptionEvent(new Exception("Test's exception"), "Test");

        response.getWriter().write("Test's servlet");
    }

    public void sendExceptionEvent(Exception e, String source) {
        client.trackException(e);
    }

```

**Comment by dhaval24** [comment]
I just tried following - 

protected void doGet(javax.servlet.http.HttpServletRequest request, javax.servlet.http.HttpServletResponse response) throws javax.servlet.ServletException, IOException {

        PrintWriter pw = response.getWriter();
        response.setContentType("text/html");
        TelemetryClient client = new TelemetryClient();
        EventTelemetry event = new EventTelemetry();
        event.setName("JsonString");
        event.getProperties().put("ConstructValue",
                "{\"entityType\":\"CONTACTNAME\",\"contactField\":\"\",\"query\":\"zuck\",\"candidates\":[{\"id\":\"2\",\"name\":\"Andrew Zuck\",\"aliases\":[],\"phoneNumbers\":[{\"type\":\"MOBILENUMBER\",\"number\":\"+1 (555) 222-2222\"}],\"emailAddresses\":[],\"streetAddresses\":[]}],\"scores\":{\"2\":2.327993297520463}}");

        //event.getProperties().put("val", "abc");
        client.trackEvent(event);
        client.trackException(new Exception("My Exception"));
        pw.print("custom telemetry testing");
        pw.close();
    }

and this works fine.  Here is the snapshot for the same. I have no idea why it didn't worked for you. 

![image](https://user-images.githubusercontent.com/16353121/31304137-2fb144d0-aad0-11e7-84e5-f04e3828afde.png)

**Comment by dhaval24** [comment]
A deeper context. The SDK version also shows 1.0.10. Please do double check and see you have all the dependencies and the AI configured correctly.

![image](https://user-images.githubusercontent.com/16353121/31304168-00db8b92-aad1-11e7-9433-f06bec5c5734.png)

**Comment by debugthings** [comment]
Close this as we have identified the issue with the customer who reported.

**Comment by dhaval24** [comment]
Closing this issue as mentioned by James Davis (Issue identified on the customer end)
