### ISSUE TITLE
Collect App Service Performance Counters Similar to .NET SDK

### ISSUE THREAD

**Issue by debugthings** [microsoft/ApplicationInsights-Java#442]
Implement App Service performance counters similar to how it's done in the .NET SDK so we can collect what is needed out of the box.

https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/4093e9a6d350a9d4759eb64a2be17a90dc23f85a/Src/PerformanceCollector/Perf.Shared.NetFull/Implementation/WebAppPerformanceCollector/CounterFactory.cs#L1

**Comment by dhaval24** [comment]
@debugthings do you have more insights on this? What is the exact difference. I would like to understand this scenario better because App Service users are increasing. Does the above implementation work for Linux App Services also?

**Comment by debugthings** [comment]
@dhaval24 Yes. Right now we look for the actual windows performance counters on all windows machines, ie make a call into the Windows Performance counters via the [Java Native PC connector](https://github.com/Microsoft/ApplicationInsights-Java/blob/master/core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/JniPCConnector.java#L61). For App Services Azure sandboxes the applications and they are not given access to all of the performance counters available to it. ***Some*** of these counters don't matter, but some do of course.

https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/4093e9a6d350a9d4759eb64a2be17a90dc23f85a/Src/PerformanceCollector/Perf.Shared.NetFull/Implementation/WebAppPerformanceCollector/PerformanceCounterImplementation.cs#L16

https://github.com/projectkudu/kudu/wiki/Azure-runtime-environment

https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox
