### ISSUE TITLE
issue with SeverityLevel in ver 1.0.10 of logback implementation

### ISSUE THREAD

**Issue by lahans** [Microsoft/ApplicationInsights-Java#448]
After update to 1.0.10 we stopped getting data in AI. Specifically statements like this would no longer come through:

this.logger.debug("Starting Services:debug");
this.logger.error("Starting Services:error");
this.logger.info("Starting Services:info");
this.logger.trace("Starting Services:trace");
this.logger.warn("Starting Services:warn");

However if I used the TelemetryClient directly, it worked just fine:
this.telemetry.trackTrace("Starting services:custom trace:"+new java.util.Date());

After some digging around, whenever SeverityLevel was set on a TraceTelemetry object, it would not come through.

I could get it working again by doing my own implementation of ApplicationInsightsLogEvent.java which would always return null in the getNormalizedSeverityLevel method.

For now, I just downgraded to ver 1.0.9 and everything is working again

Br /Lars

**Comment by dhaval24** [comment]
@lahans this issue had been notified previously and we have a fix merged in for this in the master branch. If you would like to build master locally you are most welcomed. We plan to have next version released soon which will come with the fix.

**Comment by tobiasdiez** [comment]
I have a similar issue with the "trackPageView" method. Is this problem also known and will addressed with the next release?

**Comment by dhaval24** [comment]
@tobiasdiez if this issue is related to setting severity level in the PageViewTelemetry then yes this problem is known to us. The issue with Severity level will affect all kind of telemetries where one tries to set it. We have already merged a PR to fix this issue and will be as a part of next release.

**Comment by dhaval24** [comment]
Changes already in master. Please try it out by building locally or with the upcoming latest release. Reopen if needed.
