### ISSUE TITLE
AppInsights for JBoss having issues in starting up

### ISSUE THREAD

**Issue by avnsiva** [Microsoft/ApplicationInsights-Java#450]
I am trying to get the App Insights to work with JBoss Application Server. In my application, I am having the  files applicationinsights-core-1.0.10.jar, applicationinsights-web-1.0.10.jar and ApplicationInsights.xml in the folder /WEB-INF/lib folder of my war file.

I am getting the following logs when I am trying to access the application for the first time:

20:28:29,802 ERROR [stderr] (default task-5) AI: INFO 21-10-2017 20:28, 153: Registering WebApp with name 'cas'
20:28:29,820 ERROR [stderr] (default task-5) AI: INFO 21-10-2017 20:28, 153: Configuration file 'ApplicationInsights.xml' was NOT found by default class loader
20:28:29,820 ERROR [stderr] (default task-5) AI: WARN 21-10-2017 20:28, 153: Can not access folder '/content/cas.war/WEB-INF/lib/applicationinsights-core-1.0.10.jar'
20:28:29,822 ERROR [stderr] (default task-5) AI: WARN 21-10-2017 20:28, 153: Configuration file 'ApplicationInsights.xml' could not be found
20:28:30,052 ERROR [stderr] (default task-5) AI: INFO 21-10-2017 20:28, 153: Registered WebApp 'cas' key='cas'
20:28:30,053 ERROR [stderr] (default task-5) AI: INFO 21-10-2017 20:28, 153: Successfully registered the filter 'ApplicationInsightsWebFilter'

Now, 

1. JBoss logs reports it as category 'ERROR' and AI reports them as 'WARN' and 'INFO.
2. Despite generating traffic, nothing appears in the Overview of App Insight in Portal.

**Comment by dhaval24** [comment]
@avnsiva as far as I remember @littleaj was using JBoss Application Server for monitoring his test app using Wildfly the community version of JBoss. Are you using the enterprise version or community version. @littleaj to comment more on this.

**Comment by avnsiva** [comment]
I am using the enterprise version.

Now I moved the ApplicationInsights.xml from the WEB-INF folder into WEB-INF/classes folder and it worked...In one of the servers it worked without issues. But in the second server I got this error: Both are using the same JDK jdk1.8.0_92.

09:30:12,531 ERROR [stderr] (default task-5) AI: INFO 23-10-2017 09:30, 138: Registering WebApp with name 'cas'
09:30:12,541 ERROR [stderr] (default task-5) AI: INFO 23-10-2017 09:30, 138: Configuration file 'ApplicationInsights.xml' was NOT found by default class loader
09:30:12,542 ERROR [stderr] (default task-5) AI: WARN 23-10-2017 09:30, 138: Can not access folder '/content/cas.war/WEB-INF/lib/applicationinsights-core-1.0.10.jar'
09:30:12,542 ERROR [stderr] (default task-5) AI: WARN 23-10-2017 09:30, 138: Configuration file 'ApplicationInsights.xml' could not be found
09:30:12,812 ERROR [stderr] (default task-5) AI: INFO 23-10-2017 09:30, 138: Registered WebApp 'cas' key='cas'
09:30:12,813 ERROR [stderr] (default task-5) AI: INFO 23-10-2017 09:30, 138: Successfully registered the filter 'ApplicationInsightsWebFilter'

**Comment by littleaj** [comment]
@avnsiva Regarding point 1 from your original post, stderr is currently default output stream for logging. So, in JBoss, AI logs always show up as `<`_time_`> ERROR [stderr] (`_thread_`) AI: ...` for now.

It is true, the XML file should be in WEB-INF/classes and the jars in WEB-INF/lib and the classloaders should find the config file from there. It's odd the second server didn't find it. Is there anything different about that server's configuration?

I'll run some experiments with my local server and get back to you.

**Comment by littleaj** [comment]
I haven't been able to reproduce the issue you are seeing. Has anything changed on your end?

If you are still seeing this issue, please provide some more information about your environment:
Are you using a managed or unmanaged/exploded deployment?
Which version of JBoss are you using?
Are you using standalone, domain or a custom configuration mode?

Finally, could provide us with the WAR which is having problems? This will speed up the process. Thanks!

**Comment by dhaval24** [comment]
@avnsiva are you still facing this issue? If so is it possible for you to provide information @littleaj requested so we can investigate? If issue is no longer persistent feel free to close the issue.

**Comment by dhaval24** [comment]
@avnsiva we have not been able to replicate the issue. Please provide us with the steps to replicate this. If the issue no longer persists we would be happy if you can close this.

**Comment by dhaval24** [comment]
@littleaj I remembered based on your investigation there JBoss issues were now resolved correct? Please convey the same to @avnsiva.

@avnsiva please give a shot to latest SDK version 2.0.0-BETA and if issue doesn’t persist let us know so w can close this

**Comment by littleaj** [comment]
This is fixed in v2.0.1
