### ISSUE TITLE
Can't get sql dependency data when using the Apache Derby DB

### ISSUE THREAD

**Issue by aivendortest** [microsoft/ApplicationInsights-Java#452]
1. Create a java web app and configure ai resource.
2. Download the apache derby at here http://db.apache.org/derby/derby_downloads.html 
3. Add derby.jar to ../WEB-INF/lib
4.Add below code 
Class.forName("org.apache.derby.jdbc.EmbeddedDriver");				
				System.out.println("Loaded the derby driver");
				 String protocol = "jdbc:derby:";
			    String dbName = "C:\\Derby\\db-derby-10.14.1.0-bin\\lib\\mytestdb";		
				Connection conn = DriverManager.getConnection(protocol + dbName+ ";create=true");
				System.out.println("connected and create db");
				
		        String sql = "select * from mytable";
				Statement st=conn.createStatement();
				ResultSet rs=st.executeQuery(sql);
				System.out.println("select from db");
				while(rs.next()){
					System.out.println(rs.getInt(1));
					System.out.println(rs.getString(2)); 
				}  

5. we can see dependency data shows up in the console without error but can't see dependency data in the portal. Please see attached screenshot 'consoledata'.
![consoledata](https://user-images.githubusercontent.com/30819171/31933760-a2865594-b8dc-11e7-8216-d3ce80572e4a.PNG)

**Comment by littleaj** [comment]
Hi @aivendortest,

Regarding dependency data in the portal, the Java agent is required for automatic collection. I can't tell if it's loaded or not from this screenshot. If it's not yet attached to Tomcat, [here's how to get started](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-agent).

If you have already attached and configured the agent, please attach the complete log file.

**Comment by dhaval24** [comment]
@littleaj I believe this issue was created by our CTI team and they discovered this issue while exhaustively testing our agent. I believe that they might have Agent loaded correctly as they were able to see other dependencies although I might be wrong too.

**Comment by littleaj** [comment]
Fixed in #971
