### ISSUE TITLE
AI-Agent.xml does not allows methods and class names with wildcards

### ISSUE THREAD

**Issue by avnsiva** [microsoft/ApplicationInsights-Java#455]
Hi,

I am using AI-agent.xml to define what methods to profile. But if I want to provide a way to profile all classes and methods excluding my code, I could not find a way to do it,.

For example, profile all classes starting with com.app1.*.
Exclude classes starting with org.hibernate, com.oracle.*

Is there a way to perform this in AI-agent.xml ?

**Comment by dhaval24** [comment]
@avnsiva I am currently not sure if we can do this. I will experiment with this issue and let you know. If this is not possible we will take this as a feature request.

**Comment by avnsiva** [comment]
@dhaval24 are you able to start the Jboss EAP by using javaagent option in the jvm arguments? 

I am getting VM initialization error.

JBoss Bootstrap Environment

  JBOSS_HOME: /app/server/EAP/jboss-eap-7.0-CRMS

  JAVA: /app/software/jdk1.8.0_92/bin/java

  JAVA_OPTS:  -server -verbose:gc -Xloggc:"/app/server/EAP/jboss-eap-7.0-C/standalone/log/gc.log" -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=3M -XX:-TraceClassUnloading  -javaagent:/app/server/EAP/jboss-eap-7.0-C/bin/applicationinsights-agent-1.0.10.jar -Xbootclasspath:/app/server/EAP/jboss-eap-7.0-C/modules/system/layers/base/org/jboss/logging/main/jboss-logging-3.3.0.Final-redhat-1.jar -Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager,org.apache.log4j -Djava.awt.headless=true -Dorg.jboss.boot.log.file=/app/server/EAP/jboss-eap-7.0-C/standalone/log/boot.log -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Xbootclasspath:/app/server/EAP/jboss-eap-7.0-C//modules/system/layers/base/org/jboss/log4j/logmanager/main/log4j-jboss-logmanager-1.1.2.Final-redhat-2.jar -Dlogging.configuration=file:/app/server/EAP/jboss-eap-7.0-C/standalone/configuration/logging.properties  -Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager,org.apache.log4j -Djava.awt.headless=true

=========================================================================

Error occurred during initialization of VM

**Comment by avnsiva** [comment]
@dhaval24 if you have a working JVM arguments for EAP 7, can you please share it, I can try with that.

**Comment by dhaval24** [comment]
@avnsiva I have not experimented with Jboss however, I know that there might be some difficulty and I believe @littleaj who will be experimenting with this should be able to relay his results sometime. As far as this thread is concerned about the wildcards they are not supported and this was the initial design decision. However if it is required and within the scope of future iteration we will take it as feature request.

**Comment by littleaj** [comment]
We may be adding support for wildcards in the near future, but I would not recommend it on the scale you suggested. Using the Java Profiler for App Insights on-demand may be a better choice for this scenario.
