### ISSUE TITLE
High CPU load with 'idle' servlet

### ISSUE THREAD

**Issue by HeikoH** [Microsoft/ApplicationInsights-Java#456]
After adding App Insights following [this](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-get-started) the JVM seems to be consuming a lot more CPU, even when the service is completely idle. Anybody else seeing this?

**Comment by littleaj** [comment]
@HeikoH We will investigate this. Could you provide more information about your environment (SDK version, JRE version, OS, any relevant frameworks)? Also, did you setup the agent or add any additonal performance counters?

**Comment by dhaval24** [comment]
@HeikoH would be great if you can provide the requested information which @littleaj asked for and also if how you are exactly noticing high cpu usage ( i.e via task manager)

**Comment by HeikoH** [comment]
I don't see this issue anymore.
