### ISSUE TITLE
Lack of throttling documentation

### ISSUE THREAD

**Issue by gondar** [microsoft/ApplicationInsights-Java#458]
Be me.
Java newbie. I was setting up default AI integration for our legacy java project. Decided to add it manually (this is just couple of jars and changes to the config file, right?). Got really frustrated that every time AI tried to sent any message I got message that it was throttled. My frustration raised when I realised throttling implementation is utterly undocumented. After digging into source code of client I learnt how to disable it and everything started running smoothly.
Thanks for the great client! This ticket/issue is to allocate a bit time for documenting throttling option and verifying if it should be turned on/off by default.

**Comment by dhaval24** [comment]
@gondar thank you very much for creating this issue. We acknowledge that our documentation is not the strongest out there but we are constantly working to improve it and will take your request into consideration in our subsequent updates. Hope you liking AI and monitoring solutions it is providing. Feel free to raise more issues or suggestions as you explore the product more.

**Comment by grlima** [comment]
@gondar "I got message that it was throttled" - could you please share this error message? I'd like to see which scenario you were facing and what could be improved as far as documentation goes.

**Comment by gondar** [comment]
08:03:55,520 ERROR [stderr] (Thread-549) AI: TRACE 30-10-2017 08:03, 778:
App is throttled, telemetries are blocked from now, for 300 seconds

it was happening every time I issued new request. Not sure yet why.

**Comment by dhaval24** [comment]
@Gondar thank you very much for providing the information. Do you also receive "partial items are rejected" or similar in the console with SDKLogger being enabled? If that is the case then I believe that there are some telemetry items which are not being sent to the end point because of invalid characters or similar issues. Nonetheless we will take your ask to improve our documentation on this.

**Comment by gondar** [comment]
No. None sucg message. Just enabling msg and immediatel throttle msg. 5 min
enable and throttle and nothing sent to ai.

08.11.2017 17:27 "Dhaval Doshi" <notifications@github.com> napisał(a):

**Comment by grlima** [comment]
@gondar - This usually happens when the client machine cannot send telemetry to the cloud. Reasons are varied: socket exception/timeout, connection pool timeout, etc... I've seen this before when having fiddler enabled on the box. Do you have some sort of proxy in between your client running the SDK and the internet?

**Comment by gondar** [comment]
So interestingly once I change configuration to turn off throttling all
started working. So I doubt it would be proxy related.

Still if that were the case it would be quite confusing log message :).

On Monday I can send you change I did in the config file.

09.11.2017 5:51 PM "Gustavo Lima" <notifications@github.com> napisał(a):

**Comment by grlima** [comment]
Please do, thanks!

**Comment by dhaval24** [comment]
@gondar is there any update on this issue from your end? Have you tried @grlima 's suggestions ?

**Comment by gondar** [comment]
Yeah, life catched up and forgot about you! Below my config without
instrumentation key :-). The suggestion was more of sharing experiences. I
don't have proxy there.

<?xml version="1.0" encoding="utf-8"?>
<ApplicationInsights xmlns="
http://schemas.microsoft.com/ApplicationInsights/2013/Settings"
schemaVersion="2014-05-30">


    

    <InstrumentationKey>(...)</InstrumentationKey>

    <Channel>
        <MaxTelemetryBufferCapacity>100</MaxTelemetryBufferCapacity>
        <FlushIntervalInSeconds>1</FlushIntervalInSeconds>
        <Throttling>0</Throttling>
    </Channel>

    <PerformanceCounters>
        <Jmx>
            <Add objectName="java.lang:type=ClassLoading"
attribute="TotalLoadedClassCount" displayName="Loaded Class Count"/>
            <Add objectName="java.lang:type=Memory"
attribute="HeapMemoryUsage.used" displayName="Heap Memory Usage-used"
type="composite"/>
        </Jmx>
    </PerformanceCounters>

    

    <TelemetryModules>
        <Add
type="com.microsoft.applicationinsights.web.extensibility.modules.WebRequestTrackingTelemetryModule"/>
        <Add
type="com.microsoft.applicationinsights.web.extensibility.modules.WebSessionTrackingTelemetryModule"/>
        <Add
type="com.microsoft.applicationinsights.web.extensibility.modules.WebUserTrackingTelemetryModule"/>
    </TelemetryModules>

    
    

    <TelemetryInitializers>
        <Add
type="com.microsoft.applicationinsights.web.extensibility.initializers.WebOperationIdTelemetryInitializer"/>
        <Add
type="com.microsoft.applicationinsights.web.extensibility.initializers.WebOperationNameTelemetryInitializer"/>
        <Add
type="com.microsoft.applicationinsights.web.extensibility.initializers.WebSessionTelemetryInitializer"/>
        <Add
type="com.microsoft.applicationinsights.web.extensibility.initializers.WebUserTelemetryInitializer"/>
        <Add
type="com.microsoft.applicationinsights.web.extensibility.initializers.WebUserAgentTelemetryInitializer"/>

    </TelemetryInitializers>
</ApplicationInsights>

**Comment by dhaval24** [comment]
@gondar Thank you very much for taking pain to notify us of this. It would really help in better shaping the documentation. I agree that SDK has many configurable parameters which are not very clearly documented and this being one of it. 

Regarding ApplicationInsights.xml finding, would you mind taking a glance at this #477 . It allows passing the xml files as the SYSTEM property, essentially allowing it to be kept anywhere in the directory. Let me know your thoughts.

**Comment by dhaval24** [comment]
@grlima I am assigning this to you as a part of our documentation effort, as I believe you have more background on this. Let me know.

**Comment by nikmd23** [comment]
@DaleKoetke, it'd be great to have our default throttling policies documented.

Can you provide a rough sketch of what they are here, and then we can turn them into true blue docs?
