### ISSUE TITLE
Telemetry Naming not align with .net Version

### ISSUE THREAD

**Issue by XiaoliangHuang** [Microsoft/ApplicationInsights-Java#462]
# Issue Description

when I use the Java sdk, the log sent out is named as
 
**"name": "Microsoft.ApplicationInsights.Request"**

but when I use .net sdk, the name contains the instrumentation key, like:

**"name": "Microsoft.ApplicationInsights.aif4614a93a841f4d9dae2754a1d946fc8b.Message",**

# Impact

While using the ApplicaitonInsights Java SDK as FirstParty Partner to onboard Microsoft Asimove Platform, no source node will be created, as the Event Name does not contains the Key

Ref: 
[Xpert Ticket 2777] (http://asimovtickets/helpdesk/Ticket/2777)

# Root Cause
The root cause is that Java SDK hard corded the Telemetry Name, but .net SDK process it with give prefix:

```
        /// <summary>
        /// Normalize instrumentation key by removing dashes ('-') and making string in the lowercase.
        /// In case no InstrumentationKey is available just return empty string.
        /// In case when InstrumentationKey is available return normalized key + dot ('.')
        /// as a separator between instrumentation key part and telemetry name part.
        /// </summary>
        private static string NormalizeInstrumentationKey(string instrumentationKey)
        {
            if (instrumentationKey.IsNullOrWhiteSpace())
            {
                return string.Empty;
            }

            return instrumentationKey.Replace("-", string.Empty).ToLowerInvariant() + ".";
        }
```

**Comment by SergeyKanzhelev** [comment]
@XiaoliangHuang please feel free to send a PR.

**Comment by dhaval24** [comment]
@XiaoliangHuang thank you very much for submitting the PR for this issue. #464 is the PR fixing this issue.
