### ISSUE TITLE
Found a few double-checked locking for initializing non-volatile variables

### ISSUE THREAD

**Issue by littleaj** [microsoft/ApplicationInsights-Java#465]
This is something I came across a few years ago. It's low priority since it's a rare occurrence, but I prefer to be on the safe side.

[See this article for full details](https://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html)

TL;DR - If using double-checked locking for lazy instantiation, mark the lazy variable `volatile` or as a static variable in a separate class.

**Comment by dhaval24** [comment]
@littleaj I believe you had fixed most of them correct? If not have you identified the places where these exist?
