### ISSUE TITLE
"StatusCode: 400 SyntaxError: Unexpected token '" due to single quote in an SQL statement

### ISSUE THREAD

**Issue by nobiinu-and** [Microsoft/ApplicationInsights-Java#470]
Reproduce

1) Use single quote in SQL Statement
   ex. `select * from foo where id = ? and year = '2001'`
2) Monitoring JDBC using Application Insights Agent
3) Error above occured

related #445 ?

**Comment by nobiinu-and** [comment]
Now, this issue never occurred. Thanks! Team Application Insights!!!

**Comment by dhaval24** [comment]
@nobiinu-and glad this issue no longer persists for you. Just for knowledge are you using a local build of the project or public version?

**Comment by nobiinu-and** [comment]
@dhaval24 We use public version (1.0.10).
Yesterday afternoon(JST) we met this issue. and could reproduce until 21:30 JST.
But We could not reproduce on 22:20 JST.
I think, because server is updated and fixed this issue.

**Comment by dhaval24** [comment]
@nobiinu-and sounds great! By the way if you have a chance can you go through these two issues and complete a short survey there #469 #468. It would be really helpful.

**Comment by nobiinu-and** [comment]
@dhaval24 Thank you! I would like to use beta version, answer survey later.

**Comment by dhaval24** [comment]
@nobiinu-and thank you very much. Please just update on the issue with how you would like to be notified in this case so that we know whom all to send a reminder when Beta versions are out.

**Comment by dhaval24** [comment]
@nobiinu-and were you able to onboard the Beta SDK version? Could you please provide me with your email address on dhaval.doshi@microsoft.com so we can also have a good feedback loop for the same.
