### ISSUE TITLE
Custom PerformanceCounters

### ISSUE THREAD

**Issue by HeikoH** [Microsoft/ApplicationInsights-Java#475]
How to register a custom PerformanceCounter? (i.e. a class that implements `PerformanceCounter`)

**Comment by HeikoH** [comment]
Found it
```java
PerformanceCounterContainer.INSTANCE.register(new MyPerformanceCounter());
```

**Comment by dhaval24** [comment]
@HeikoH awesome. Are you guys at Esri using AI for production applications? Also if you can have a look at #468 and #469 it would be great!
