### ISSUE TITLE
Jet Brains Rider IDE Java issues

### ISSUE THREAD

**Issue by MarcusBullock** [Microsoft/ApplicationInsights-Java#478]
Hi guys,

I recently installed Jet Brains Rider and I was not able to even use the application until I disabled Visual Studio Team Services from the configuration.

From looking at the logs and speaking with the JetBrains people, it's clear that this was due to a Java error. Worth looking into as Rider will become pretty popular soon.

**Comment by dhaval24** [comment]
@MarcusBullock is this question related to DotNet SDK as I believe the Jet Brains Rider IDE is for .NET development. If that is the case, would be great if you can open the issue on their repository (https://github.com/Microsoft/ApplicationInsights-DotNet) and I can close this off here.

**Comment by dhaval24** [comment]
@MarcusBullock could you please confirm the above? It would be really helpful to better manage this issue.

**Comment by MarcusBullock** [comment]
yeah you're right, it's better placed there. i'll move it! cheers

**Comment by dhaval24** [comment]
@MarcusBullock were you using Application Insights - Java SDK at all? Or which Application Insights SDK were you using ? Can you provide more details on this.

**Comment by dhaval24** [comment]
@MarcusBullock could you please provide the update on this thread? I am using Intellij Idea here which is Jet Brains IDE for java along with AI Java SDK without any sorts of isses, please let me know more details on this or update accordingly

**Comment by dhaval24** [comment]
@MarcusBullock I am closing this issue as of now, hopefully your problem is resolved and more or less if Application Insights Java SDK wasn't being used then it has little to do with this. Happy to help if you shed more details here. Please reopen if needed.

**Comment by kaylangan** [comment]
@MarcusBullock do you know what version of the VSTS plugin you were on?
