### ISSUE TITLE
Upgrading gradle wrapper to latest version breaks win native build

### ISSUE THREAD

**Issue by littleaj** [Microsoft/ApplicationInsights-Java#480]
Just something I found while trying to upgrade the gradle wrapper. The current wrapper version is 3.5 and the latest gradle version is 4.6. We should upgrade eventually, but need to understand why this is happening before we do.

**Comment by dhaval24** [comment]
@littleaj is this still relevant?

**Comment by littleaj** [comment]
Technically, it is an issue that I found; but we have no drivers at this time to upgrade. I'm going to close it and we'll tackle it if upgrading becomes necessary.
