### ISSUE TITLE
Please update documentation to explain correlation in Java SDK

### ISSUE THREAD

**Issue by dhaval24** [Microsoft/ApplicationInsights-Java#487]
Please update official documentation to support cross-component telemetry correlation in Java SDK. This should include examples on automatic correlation support as well as the current capabilities of manual correlation with examples. It should also clearly specify the limitations and ongoing work.

**Comment by nikmd23** [comment]
Would you help us understand a bit more about what you're looking for here?

We have the [dependency auto-collection](https://docs.microsoft.com/en-us/azure/application-insights/auto-collect-dependencies) doc, but I don't think that covers everything you're looking for.

Does this exist in any of our language docs? Perhaps you're asking for a Java equivalent of this: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-custom-events-metrics#trackdependency?

**Comment by dhaval24** [comment]
i think this is dup of #601. Closing it!
