### ISSUE TITLE
Please create a Wiki article / blog/ document update to explain the support of Spring Boot with AI

### ISSUE THREAD

**Issue by dhaval24** [Microsoft/ApplicationInsights-Java#488]
Please create a Wiki Article / Blog Post / official documentation update to explain how to enable application insights in spring boot (i.e enable web request tracking filter, collect dependency, page view data etc). 

The article should also explain the limitations of the current approach and upcoming possible Spring Boot Starter for Application Insights vision.

**Comment by grlima** [comment]
Complete.
