### ISSUE TITLE
High data volume for custom metrics and events

### ISSUE THREAD

**Issue by adoelger** [Microsoft/ApplicationInsights-Java#498]
Hi, 
I'm using the Application Insights Java SDK to trace a custom metric -> name "l" (for latency) and a integer value. Should be a few bytes per trace. When I look into Application Insights Analytics I see the following attributes for each metric trace: 

{
    "timestamp": "2017-12-15T10:36:02.074Z",
    "name": "l",
    "value": 95,
    "valueCount": 1,
    "valueSum": 95,
    "valueMin": 95,
    "valueMax": 95,
    "valueStdDev": 0,
    "customDimensions": "null",
    "operation_Name": "null",
    "operation_Id": "null",
    "operation_ParentId": "null",
    "operation_SyntheticSource": "null",
    "session_Id": "null",
    "user_Id": "null",
    "user_AuthenticatedId": "null",
    "user_AccountId": "null",
    "application_Version": "null",
    "client_Type": "PC",
    "client_Model": "Other",
    "client_OS": "Linux",
    "client_IP": "104.41.212.0",
    "client_City": "Amsterdam",
    "client_StateOrProvince": "North Holland",
    "client_CountryOrRegion": "Netherlands",
    "client_Browser": "Apache-HttpClient 4.5",
    "cloud_RoleName": "null",
    "cloud_RoleInstance": "10.232.131.26",
    "appId": "a5aa4e41-24e3-442c-a787-0deb2037XXXX",
    "appName": "scan-ai-dev",
    "iKey": "a4ceb415-9985-4310-837e-d21ea944XXXX",
    "sdkVersion": "java:1.0.10",
    "itemId": "c24e3480-e183-11e7-8320-71b3a670XXXX",
    "itemType": "customMetric"
  }

So 99% of each entry are overhead to me, but I will be charged by Application Insights for all this metadata. In my case I have 20 million traces per day, that will result in 10 GB datavolume to Application Insights per day! For just one metric - another metric or event will add another 10 GB per day.
I really like Application Insights but this way it is really too expensive. Is there a way (not sampling) to reduce the metadata for custom metrics and events?

**Comment by dhaval24** [comment]
@adoelger apologies for a delayed response. I get you, I think you can filter out these additional meta data by creating your own telemetry processor and removing the meta data from the packet. I think it comes as are stored as ContextTags which is basically a Map of key and values. The custom processor can remove those informations from the packet and later push this modified JSON to the endpoint. 

The steps to glue in the custom processor would be : 
1. Create a TelemetryProcessor class which extends TelemetryProcessor Interface.
2. Override the process() method which will do the required processing.
3. Place this processor inside the ApplicationInsights.xml file. 

Let me know if you have further questions.

**Comment by adoelger** [comment]
Fixed!

**Comment by dhaval24** [comment]
@adoelger, I hope the above solution worked out for you. By the way do you mind sending out a PR for the same? May be many people want to have similar kind of processor, so we might have a look and see if it’s feasible to be a part of SDK itself.

**Comment by adoelger** [comment]
Yes the solution works. Currently we just remove all tags from the custom event, because we do not need these informations.

```
public class ApplicationInsightsTagsFilter implements TelemetryProcessor
{
   @Override
   public boolean process( Telemetry telemetry )
   {
      Map<String, String> tags = telemetry.getContext().getTags();
      tags.forEach( ( key, value ) -> tags.remove( key ) );
      return true;
   }
}
```

ApplicationInsights.xml:
```
...
	<TelemetryProcessors>
		<CustomProcessors>
			<Processor type="com.mypackage.ApplicationInsightsTagsFilter"/>
		</CustomProcessors>
	</TelemetryProcessors>
...
```

Cuts down paid ingress data to Application Insights by 50%!

**Comment by dhaval24** [comment]
@adoelger great to see that this works for you. 50% wow that is a whooping number!! Just wanted to check were you able to give our latest SDK v2.0.0-BETA a shot and share your experience ?
