### ISSUE TITLE
Application Insights Java SDK v2.0.0-BETA is out!

### ISSUE THREAD

**Issue by dhaval24** [Microsoft/ApplicationInsights-Java#500]
Application Insights Java SDK v2.0.0-BETA is now out. It has significant improvements over the past versions of the SDK.  I would encourage everyone out there to try out this version. We are looking for some great feedback both positive as well as negative so together we can shape this project in the best possible way!

https://github.com/Microsoft/ApplicationInsights-Java/releases/tag/v2.0.0-BETA (Here is the release)

Cheers,
Application Insights Team

**Comment by gondar** [comment]
Actually it was replaced as default here: https://aijavasdk.blob.core.windows.net/sdk/sdk.html

Does it mean you encourage production usage of it? Still going to try it out. I love that I can finally choose where ApplicationInsights.xml is :-P

**Comment by dhaval24** [comment]
@gondar unfortunately, there is only one blob storage where this Jars are uploaded (usually only recommended when you don't have dependency management systems). From maven/gradle you can still pull down the latest stable release. I am glad that you will give a shot to this newly released Beta SDK and share the feedback. My personal recommendation for production usage would be:

1. Try it first on lower (dev / test) environment. 
2. If performance is satisfactory in above environments for a considerable time, I would not hesitate to use it in production.

This version of SDK is infact better tested then the previous releases, however since we introduced new features, deprecated the support for JDK 6 and upgraded the dependencies it would be unfair to call it stable straight off. Hence the beta tag :-)

**Comment by mcmilleon-will** [comment]
Any estimate on the next release date, and do you know if it will be a GA release instead of beta?

**Comment by dhaval24** [comment]
@mcmilleon-will if all goes well and we do not hit a blocker a stable 2.0.0 version of Application Insights Java SDK is scheduled to be released sometime in 3rd week of this month. (February)
