### ISSUE TITLE
TelemetryClient.trackException not pushing data to AI 

### ISSUE THREAD

**Issue by SaiVikas-Dharmaraju** [Microsoft/ApplicationInsights-Java#502]
Hi,

The following piece of code use to work prior to 1.0.9 SDK, but  from 1.0.10 it doesn't push the exception telemetry 

Snippet:

exception = (throwable instanceof Exception) ? (Exception)throwable : new Exception(throwable);
ExceptionTelemetry exceptionTelemetry = new ExceptionTelemetry(exception);
exceptionTelemetry.setSeverityLevel(getAISeverityLevel(event));
exceptionTelemetry.getContext().getProperties().put(MSG_LABEL, formattedMessage);
client.trackException(exceptionTelemetry);

Did anything change in the underlying SDK implementation that stops pushing telemetry this way??

**Comment by dhaval24** [comment]
Did you tried this with the latest release of 2.0.0-BETA. This was a known issue in 1.0.10 and is fixed in the latest release.

**Comment by SaiVikas-Dharmaraju** [comment]
BETA version was not tried yet, I don't prefer BETA version in Production. Do we have any latest stable release available that doesn't have this issue.

**Comment by dhaval24** [comment]
@SaiVikas-Dharmaraju I am afraid there is no stable release yet which fixes the particular issue. This was an issue due to sanitization of JSON which showed up in version 1.0.10 and 2.0.0-BETA is the only release after that. I listen your voice on not using BETA in production, however I would like if possible you give this version a shot in your pre-production environment if there is one and see if issue replicates. I am pretty sure it should not.

**Comment by SaiVikas-Dharmaraju** [comment]
@dhaval24  i will definitely try out the BETA version in lower environment.

Do we have any process that notifies user about issues like this.  AI being not able capture telemetry is a bigger dent since that functionality is very important and it's some time before we found exceptions were not being pushed.

I believe that issues of this magnitude(functionally) should be addressed ASAP so it will have less client impact as 1.0.10 was released on late September

**Comment by dhaval24** [comment]
We will try to release the stable version of 2.0.0-BETA as soon as possible. We understand your pain here and it’s definitely a critical piece. This was a sanitization issue which was popping up when user specified the severity level. Let me know how this beta treats you, I would say this version though named beta was tested to fullest standards. We wanted to establish this practice so we can have better stable releases.

**Comment by dhaval24** [comment]
@SaiVikas-Dharmaraju  #509 was a very similar issue to this one and the user just tried on 2.0.0-BETA and things worked. I believe it should work for you also hopefully :-)

**Comment by grlima** [comment]
@SaiVikas-Dharmaraju - If you're not willing (understandably) to use the beta release in production, I believe a possible workaround (until the stable release is out) is to remove the line of code which sets the severity level - not sure that's acceptable in your current use of the SDK though.

**Comment by SaiVikas-Dharmaraju** [comment]
@grlima - I removed the Severity level and this got resolved. Apologies that i didn't update this thread earlier.

Thanks @dhaval24  for the inputs

**Comment by dhaval24** [comment]
@SaiVikas-Dharmaraju that's okay. Glad that you can adjust with the work around for the time being. And as you said you will give a try to Beta SDK on lower environment it would also be a good feedback for us on how you feel about it. As I mentioned the problem with severity level is also fixed there. I will close this issue now and if you find any further troubles even on Beta SDK feel free to reopen.
