### ISSUE TITLE
Initialization happens twice

### ISSUE THREAD

**Issue by StefanHub** [Microsoft/ApplicationInsights-Java#503]
On startup we see these log messages:
```
AI: INFO 20-12-2017 08:47, 1: Configuration file has been successfully found as resource
AI: INFO 20-12-2017 08:47, 1: 'MaxTelemetryBufferCapacity': null value is replaced with '500'
AI: INFO 20-12-2017 08:47, 1: 'FlushIntervalInSeconds': null value is replaced with '5'
AI: TRACE 20-12-2017 08:47, 1: Using Http Client version 4.3+
AI: INFO 20-12-2017 08:47, 1: 'Channel.MaxTransmissionStorageCapacityInMB': null value is replaced with '10'
AI: TRACE 20-12-2017 08:47, 1: C:\Users\sli\AppData\Local\Temp\AISDK\native\1.0.9 folder exists
AI: ERROR 20-12-2017 08:47, 1: Failed to load native dll, Windows performance counters will not be used. Please make sure that Visual C++ Redistributable is properly installed: C:\Users\..... [omitted]
AI: ERROR 20-12-2017 08:47, 1: Failed to initialize JNI connection.
AI: INFO 20-12-2017 08:47, 1: Configuration file has been successfully found as resource
AI: INFO 20-12-2017 08:47, 1: 'MaxTelemetryBufferCapacity': null value is replaced with '500'
AI: INFO 20-12-2017 08:47, 1: 'FlushIntervalInSeconds': null value is replaced with '5'
AI: INFO 20-12-2017 08:47, 1: 'Channel.MaxTransmissionStorageCapacityInMB': null value is replaced with '10'
```
as you can see "Configuration file has been successfully found as resource" appears twice. 

This is because while initializing in TelemetryConfiguration:
```
    public static TelemetryConfiguration getActive() {
        if (!initialized) {
            synchronized (s_lock) {
                if (!initialized) {
                    active = new TelemetryConfiguration();
                    TelemetryConfigurationFactory.INSTANCE.initialize(active);
                    initialized = true;
                }
            }
        }

        return active;
    }
```
TelemeryConfiguration.getActive() gets called again (stacktrace in debugger):
![grafik](https://user-images.githubusercontent.com/5167310/34197409-a52894ae-e566-11e7-9abb-b99a9d96f929.png)

This appears unsound to me.

Using version 1.0.9 (can´t use 1.0.10 because of https://github.com/Microsoft/ApplicationInsights-Java/issues/502)

**Comment by dhaval24** [comment]
@StefanHub this seems to be wierd and never noticed. Could cause potential performance issues. However could you please give a shot to latest release 2.0.0-BETA ? This version introduces lots of great features, fixes essential bugs including #502

**Comment by StefanHub** [comment]
Still the same.

**Comment by dhaval24** [comment]
@StefanHub thanks for trying out and letting us know. We will try and fix this issue as part of 2.0.0 Stable release. Do you have potential idea of why this is happening ? I see that getActive() method is being called twice which is not the best, do you think it could be potential synchronization issue? Just speculating.

**Comment by StefanHub** [comment]
The second call to getActive() is done because the code needs the instrumentation key if I remember it correctly.
And I don't think that it is an synchronisation issue. It happens on the same thread.
I think the problem is that reading the configuration and instantiating objects are interweaved - there are no two distinct phases. Just my guess!

**Comment by dhaval24** [comment]
@StefanHub  You are essentially correct. when the AI initializes, it first calls out the getActive() method when TelemetryClient is initialized which internally tries to initialize all the configuration. Now before the boolean flag initialized in the above code you referenced becomes true, it again calls the same getActive() method when it tries to retrive instrumentation key to initialize the quick pulse module. This makes a mess because even before the first call of the getActive() method is over the second call is made, causing two consequent initializations. This is the crux, and may be a factor causing slow initialization of ApplicationInsights. I will look into good way to fix this. Any suggestions are welcomed.

**Comment by dhaval24** [comment]
@StefanHub please have a look at #505 PR. This should fix this issue! Let me know if you think of any better way here.

**Comment by StefanHub** [comment]
Well, the last change definitely prevents multiple initialization, but what is with the code (QuickPulse) that expected to get the instrumentation key? It will now access an uninitialized TelemetryConfiguration with probably no instrumentation key set.
Is that a problem?

**Comment by dhaval24** [comment]
@StefanHub , the code to initialize QuickPulse happens only after the configuration object has InstrumentationKey set. Here is the code where the initialization for QuickPulse happens. 
https://github.com/Microsoft/ApplicationInsights-Java/blob/28dec6fabd6444905beeb8d70f3c124dc5d7ea57/core/src/main/java/com/microsoft/applicationinsights/internal/config/TelemetryConfigurationFactory.java#L110

Also initialize() here is called from getActive() method which is first time activated by a call from WebRequestTracking filter class if ApplicationInsights-web is also being used. Therefore, I believe that Configuration object will never be without iKey when it comes to initializing the QuickPulse.

**Comment by StefanHub** [comment]
Yes, I think you are right.
