### ISSUE TITLE
Improve Trouble shooting Guide on Microsoft Docs

### ISSUE THREAD

**Issue by dhaval24** [Microsoft/ApplicationInsights-Java#521]
The Trouble shooting guide for SDK seems to be too old on Microsoft Docs : 

https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot

We need to do several fixes here, including version of SDK, what we currently support and what we don't at this point etc.

**Comment by grlima** [comment]
Complete.
