### ISSUE TITLE
Add code samples in the code sample portion of Microsoft docs

### ISSUE THREAD

**Issue by dhaval24** [microsoft/ApplicationInsights-Java#522]
I found that most of the code samples stay for different azure services stay at : https://azure.microsoft.com/en-us/resources/samples/?service=application-insights&sort=0

There is currently only 1 code sample for AI there. I think there should be simple enough Java Application with decent UI present there for users to have a look at how instrumentation works. I think SpringBoot example would be great one. May be one which CAT team has done.

**Comment by grlima** [comment]
Complete.

**Comment by nikmd23** [comment]
@littleaj can you let us know why this was reopened?

**Comment by littleaj** [comment]
@nikmd23, because we still have zero results: https://azure.microsoft.com/en-us/resources/samples/?sort=0&term=application+insights&platform=java
