### ISSUE TITLE
Update Dependency support with exact versions which we support on Microsoft docs

### ISSUE THREAD

**Issue by dhaval24** [Microsoft/ApplicationInsights-Java#523]
This page for our agent and dependencies is very out dated. It has several things claimed but is not supported currently. 

https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-agent

We need to fix this, come up with exactly what we support currently with the accurate version number too!

Also the link here to diagnose dependency telemetry points to diagnosis guide for DotNet. We need to fix this to point to right page if there to diagnose dependency telemetry for java or either put it in a section in troubleshooting guide as a new section. Either works fine

**Comment by grlima** [comment]
Complete.
