### ISSUE TITLE
Should add null check when put data into concurrenthashmap

### ISSUE THREAD

**Issue by jdneo** [Microsoft/ApplicationInsights-Java#526]
The code here:
https://github.com/Microsoft/ApplicationInsights-Java/blob/v1.0.9/core/src/main/java/com/microsoft/applicationinsights/internal/util/MapUtil.java#L43

put data into a ConCurrentHashMap but does not have null check.

which will casue an NPE error if the `entry.getValue()` is null.

**Comment by dhaval24** [comment]
@jdneo thanks for pointing this out. By the way recent master also might have the same issue. Is it possible for you to send out a PR for this. Your contribution would be greatly appreciated. Let me know.

**Comment by jdneo** [comment]
Hi @dhaval24 Sure, I'll send a PR sooner.

**Comment by dhaval24** [comment]
@jdneo thank you very much. Just curios have you encountered this issue while SDK is running? Wondering how you caught this up.

**Comment by jdneo** [comment]
Yes, some of our users encounter this problem. 

Here are some related links:
https://docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin#configure-maven-to-use-your-azure-service-principal
https://github.com/Microsoft/azure-maven-plugins/issues/73

**Comment by dhaval24** [comment]
I see. So just was checking the java docs and found that standard maps allow null keys and values but concurrent map doesn't allow them. Since this method is generic for any kind of maps it would make sense to apply check with condition on type too (source instance of ConcurrentHashMap && entry.getValue() != null)

**Comment by jdneo** [comment]
Yes, but if entry.getValue() is null, what should we do? Since we have no ide what type is for `Value`

**Comment by dhaval24** [comment]
In case of concurrent maps, key with null value doesn't make sense at all so we might skip the key itself. and then log a trace with the help of Internal SDK Logger. (InternalLogger.instance.trace("Skipping key %s while copying because of null value", value)

**Comment by jdneo** [comment]
@dhaval24 That's fine!

**Comment by dhaval24** [comment]
@jdneo please also do add a test case for it :-)
