### ISSUE TITLE
Sample rate with logging

### ISSUE THREAD

**Issue by MatthewDavidCampbell** [Microsoft/ApplicationInsights-Java#530]
Using latest 2 beta with Java 9....

When using the logging to append to Application Insights I see that the sampleRate defaults to 100 when processing the envelope.  Just want to have clarified that tracking when logging is never sampled i.e. all logs as long as the level criteria is met are always sent.

**Comment by dhaval24** [comment]
@MatthewDavidCampbell not sure if I got your question correctly,but yes default sampling rate is 100 (which means no data would be sampled out). Also with 2.0.0-BETA SDK you cannot set ThreshholdFilters on specific Appenders for logging. Appender picks the root level of threshold. 2.0.1 Version of SDK would have this feature where you could set the ThreshholdFilter on specific ApplicationInsights appender. #514  . Do you think similar feature for Logback would also add value? If so feel free to open an enhancement issue on Github.

**Comment by MatthewDavidCampbell** [comment]
Super.  Thanks for the quick response Dhaval.  Just wanted to double check.  Far as access to configuration I would love to see the appender be more programmatic rather than setup från XML.  When I get a moment over I will fire up a gist of what I mean and get back to you.
