### ISSUE TITLE
Http DependencyTelemetry data structure is inconsistent with .NET SDKs

### ISSUE THREAD

**Issue by lmolkova** [Microsoft/ApplicationInsights-Java#533]
Java SDK reports method and URI in custom dimensions (in .NET SDKs it's dependency name and target)
while reporting instrumented method in the name and target
![image](https://user-images.githubusercontent.com/2347409/35120438-fb4d8e28-fc4c-11e7-8b2f-7bf7a2597b8e.png)

There are other potential discrepancies (e.g. for successful outgoing http request request target reported in 'cid-v1:' )
![image](https://user-images.githubusercontent.com/2347409/35120479-1fe298d2-fc4d-11e7-8207-617c326c543b.png)

Java SDK should follow telemetry data structure and be consistent with .NET SDKs.

**Comment by dhaval24** [comment]
@lmolkova thank you very much for reporting the inconsistency in HTTP DependencyTelemetry datastructure. If I recall correctly both Dot Net and Java SDK share the same Bond definition which is use
e the same Bond definition which is used to generate the DependencyData data-structure so ideally this difference should not arise, I would have to double check, however let me ask you this question : 
1. As you mentioned that custom dimension in Dot Net is reported as dependency name and target so it should be like this {Dependency Name = GET, target = URL } what does target look like ? Isn't it URI ?
2.  What does Dot Net SDK show in case of successful dependency call in target field. I have no idea from where the cid-v1 is getting populated in Java.

**Comment by lmolkova** [comment]
@dhaval24 

As per Dependency Collector code in .NET (e.g. [here](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/Implementation/HttpCoreDiagnosticSourceListener.cs#L397) and [here](https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/DependencyCollector/Shared/Implementation/HttpProcessing.cs#L160))


Name - method + aboslute path
Target = host

Example

![image](https://user-images.githubusercontent.com/2347409/35165966-1c3281b2-fd05-11e7-8966-3c4d71a5bb91.png)

**Comment by lmolkova** [comment]
Update: there might be different behavior for 'target' in case of same i-key and multiple i-keys, but I'm not aware of the details

**Comment by dhaval24** [comment]
@lmolkova #567 should fix this.
