### ISSUE TITLE
Where is session cookie set?

### ISSUE THREAD

**Issue by gondar** [Microsoft/ApplicationInsights-Java#536]
It seems there is code for creating a cookie, but not being called anywhere. This makes session depend on client js creating it in the first place. Not ideal (and not at all similar to .net behaviour). Ideally we would take advantage of session cookie creation code and create it if we didn't receive it from the FE.
Reasons for this are following:
-> Java AI should be able to provide session information without using client JS library
-> For the first call Server Side is involved earlier than Javascript, hence all sessions will miss the first call...
-> Java and .Net implementations could be similar in that matter making it easier to infer knowledge about implementations

**Comment by gondar** [comment]
https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/8c51d66c08c1baf0844613637fa5d3ccfc7590f9/Src/DependencyCollector/Shared/Implementation/WebRequestDependencyTrackingHelpers.cs#L38 <- this is where .net does it

**Comment by dhaval24** [comment]
@gondar apologies I am not very familier with this part of the SDK but is this issue very similar to the PR #537 where we have stripped off all the date parsing logic and kept only the SessionId as other fields are already deprecated.

**Comment by gondar** [comment]
it was mentioned in above #537 that only if client is there we will have a session. That is a bit of shame but I guess cannot be easily helped.
