### ISSUE TITLE
WebRequestTrackingFilter should catch Exception, not RuntimeException

### ISSUE THREAD

**Issue by littleaj** [Microsoft/ApplicationInsights-Java#555]
WebRequestTrackingFilter.java:90

I'm pretty sure the intent here was to catch `Exception`. This will also catch `RuntimeException`, so that's covered. I just can't think of a reason why we would want to catch `RuntimeException` instead of `Exception`.

**Comment by grlima** [comment]
@littleaj - good point, SDK might be missing application specific exceptions.

**Comment by dhaval24** [comment]
@littleaj I remember you talking about this that it should be `RuntimeException` . I also think based on my observation servlet can throw ServletException, IOException and RuntimeException only. If you have confirmed please do close this issue.

**Comment by littleaj** [comment]
@dhaval24 I had the same realization recently. There _are_ places in the docs where RuntimeException is references incorrectly. I guess I got a bit overzealous looking for its misuse. :)
