### ISSUE TITLE
Add App ApplicationInsights.xml Reference Documentation

### ISSUE THREAD

**Issue by debugthings** [Microsoft/ApplicationInsights-Java#558]
An example of this for .NET is here [ApplicationInsights.config Reference](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-configuration-with-applicationinsights-config)

**Comment by grlima** [comment]
Yep, a page should be added for Java on this and linked to the main "Getting started" page. We should also remove the Java pieces that are currently there in the .NET one (referred by @debugthings above)

**Comment by littleaj** [comment]
I created a reference in our github wiki [here](https://github.com/Microsoft/ApplicationInsights-Java/wiki/ApplicationInsights.XML)
