### ISSUE TITLE
Remove Misleading Log Messages in WebRequestTrackingFilter

### ISSUE THREAD

**Issue by dhaval24** [Microsoft/ApplicationInsights-Java#579]
The log message in the catch block inside `initialize(FilterConfig filterConfig)` method in `WebRequestTrackingFilter.java`  class is very misleading.  This is emitted even in situations when user doesn't use the agent and filter is successfully registered. 

PS: It is general behavior of the filter to test if agent is present and throw. The catch statements should be specific and use different logs for different exceptions.

**Comment by dhaval24** [comment]
#646 will address this.

**Comment by littleaj** [comment]
Which log message? I don't see one that is obviously misleading.

Regarding your PS, catch statements don't always need to be specific.

**Comment by dhaval24** [comment]
This has been resolved.
