### ISSUE TITLE
Published POM for 2.0.0 is invalid

### ISSUE THREAD

**Issue by lhotari** [Microsoft/ApplicationInsights-Java#581]
Resolving from jcenter gives this error: 
```
> Could not resolve com.microsoft.azure:applicationinsights-core:2.0.0.
      > Could not get resource 'https://jcenter.bintray.com/com/microsoft/azure/applicationinsights-core/2.0.0/applicationinsights-core-2.0.0.pom'.
         > Could not GET 'https://jcenter.bintray.com/com/microsoft/azure/applicationinsights-core/2.0.0/applicationinsights-core-2.0.0.pom'. Received status code 409 from server: Conflict
```

https://jcenter.bintray.com/com/microsoft/azure/applicationinsights-core/2.0.0/applicationinsights-core-2.0.0.pom shows the error message:
"The target deployment path 'com/microsoft/azure/applicationinsights-core/2.0.0/applicationinsights-core-2.0.0.pom' does not match the POM's expected path prefix 'com/microsoft/azure/core/2.0.0'. Please verify your POM content for correctness and make sure the source path is a valid Maven repository root path."

**Comment by lhotari** [comment]
This problem might be related to changes made by #551 . @littleaj , could you please check?

**Comment by lhotari** [comment]
The POM for 2.0.0-BETA is valid. 
[list of published versions in mavencentral](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.microsoft.azure%22%20AND%20a%3A%22applicationinsights-core%22).
2.0.0-BETA's pom has `<artifactId>applicationinsights-core</artifactId>`, but 2.0.0 has `<artifactId>core</artifactId>`

**Comment by dhaval24** [comment]
@lhotari yes we are working on this issue for last few hours trying to patch the updated release. Somehow maven doesn't allow to override, so if ultimately we don't get permissions to do so we would release a 2.0.1 version with fixed POMs. Deepest apologies for inconvenience here.

**Comment by lhotari** [comment]
@dhaval24 Published versions are immutable in MavenCentral, so you will have to release another version.

**Comment by lhotari** [comment]
@dhaval24 I wonder if #551 changes broke POM creation? Is `STABLE-2.0.0` the branch that was used to publish? #551 changes seem to be the only changes in `gradle` directory in `STABLE-2.0.0` branch after 2.0.0-BETA was released. See https://github.com/Microsoft/ApplicationInsights-Java/commits/2.0.0-STABLE/gradle

**Comment by lhotari** [comment]
The artifactId for the pom used the `archivesBaseName` value ([gradle docs](https://docs.gradle.org/current/userguide/maven_plugin.html#sec:maven_pom_generation)) before making #551 changes. @dhaval24 do you need help in fixing the issue with the Gradle build?

**Comment by dhaval24** [comment]
@lhotari yes 2.0.0-STABLE is the branch that was used to publish. If you can have some help would be great. What is the fix you think we need here? Currently I am preparing the build but had to manually modify the pom names and artifactIds. Should this work atleast for the release this time. Build ofcourse we need to fix.

**Comment by lhotari** [comment]
@dhaval24 thanks. yes, http://repo1.maven.org/maven2/com/microsoft/azure/applicationinsights-core/2.0.1/applicationinsights-core-2.0.1.pom looks ok. btw. I pushed another commit to the PR to make the pom.xml look similar so that the licence is added after the xml declaration row.

**Comment by dhaval24** [comment]
@lhotari thank you very much. I am closing down this issue as the patched version is already out on maven central and is downloadable via gradle and maven. Thank you very much for turning up and providing your assistance in real time here.
