### ISSUE TITLE
Code Sample to Set Instrumentation Key on Microsoft Docs does not reflect according to Java

### ISSUE THREAD

**Issue by dhaval24** [Microsoft/ApplicationInsights-Java#588]
Code Sample to Set Instrumentation Key on Microsoft Docs does not reflect according to Java

https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-get-started
Look in the alternative ways to set the instrumentation key section. It says 
telemetryClient. InstrumentationKey="...."

Instead it should be - 
```
String telemetryKey = "000-0000-00000";
 if (telemetryKey != null) {
            TelemetryConfiguration.getActive().setInstrumentationKey(telemetryKey);
 }
```

Update this part of docs

**Comment by grlima** [comment]
Complete.
