### ISSUE TITLE
Silent start possible?

### ISSUE THREAD

**Issue by tobiasdiez** [Microsoft/ApplicationInsights-Java#589]
When the telemetry configuration is loaded from the XML file, always the message `Configuration file has been successfully found as resource` is printed to the console. Is it possible to hide this info message?

**Comment by dhaval24** [comment]
@tobiasdiez thank you for asking this question. As of 2.0.1 version this is not possible. I think this message is written in `logAlways()` and it would log always regardless of the logging method. Is the cold start something which you would prefer usually ?

**Comment by dhaval24** [comment]
I have opened a task to revisit all logAlways messages. #590

**Comment by tobiasdiez** [comment]
Thanks for the quick response. We are using Applications Insights in a console application and thus this informative logging adds additional noise for the user. In my opinion, a debug level should suffice for this particular message.

**Comment by dhaval24** [comment]
Thank you for the feedback. As I mentioned, we will revisit our logAlways statements and reduce all the informative logs to the warn/info level and only log breaking things as logAlways.

**Comment by grlima** [comment]
We're working on improving this. Tracking with #590
