### ISSUE TITLE
Provide an XML Configuration to configure the value of MaxInstantRetry

### ISSUE THREAD

**Issue by dhaval24** [Microsoft/ApplicationInsights-Java#591]
Currently the `InProcessTelemetryChannel` has the capacity to programatically set the value of MaxInstantRetries between [1.,10]. However, this value should be configurable via XML Configuration.

Possible solution :  
Add XML attribute `MaxInstantRetry` in the `ChannelXMLElement` class for configuration to pick this up.

**Comment by littleaj** [comment]
Agreed.
