### ISSUE TITLE
Add additional SpringBoot instructions for filter after Servlet upgrade

### ISSUE THREAD

**Issue by littleaj** [Microsoft/ApplicationInsights-Java#595]
#568 started using some annotation for the Filter and the newly introduced ServletContextListener.
This changes how a SpringBoot application should onboard to the AppInsights Java SDK.

From the comments on #568
> ... We would no longer need to specify FilterRegistrationBean and Bean for WebRequestTrackingFilter. Instead with this change the user will have to annotate the SpringBoot main class with @@ServletComponentScan("com.microsoft.applicationinsights.web.internal") tag so that Spring auto configuration can pick up the filter from the Microsoft package. Also the current users who used the bean registration users won't get affected (i.e broken) if they update the library. Both the methods should work fine. Please make sure to update the SpringBoot Documentation to include the same.

> SpringBoot needs this additional tag to pick up the Servlet annotations because of embedded servlet containers it uses.

**Comment by dhaval24** [comment]
This would be obsolete wrt to #568. Please look the updated comment. Though, let's keep this task as we would have to update the documentation when we release the starter.
