### ISSUE TITLE
Pass Information from ai_authuser Cookie to Server SDK?

### ISSUE THREAD

**Issue by mjmurray88** [microsoft/ApplicationInsights-Java#599]
We were looking to pass the Authenticated User Id and Account Id that are created and stored in the `ai_authuser` cookie by the JavaScript SDK.  However, it does not appear that any of the telemetry initializers in the Java SDK parse that cookie and add those fields to the telemetry feeds.

I was expecting to see a `AuthenticatedUserIdTelemetryInitializer` or `AccountIdTelemetryInitializer` like in other [AI documentation](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-configuration-with-applicationinsights-config).

Is there already a plan on the roadmap for this?

**Comment by dhaval24** [comment]
@mjmurray88 thank yes today there are no initializers like this. Thank you for bringing this up. We will take this as a backlog. @grlima are you aware of this part in the SDK?

**Comment by grlima** [comment]
@mjmurray88 - thanks for pointing it out. We will triage this for future releases.
