### ISSUE TITLE
Add documentation on manually correlating telemetry on Queue operations in Java SDK

### ISSUE THREAD

**Issue by grlima** [microsoft/ApplicationInsights-Java#601]
.NET Examples are here:
https://docs.microsoft.com/en-us/azure/application-insights/application-insights-custom-operations-tracking

**Comment by dhaval24** [comment]
@grlima I believe you had some similar examples in an email conversation. If you can upload it here, may be @nikmd23 can assist in documenting this? Does that work for you @nikmd23 ?

**Comment by nikmd23** [comment]
Yes, please post the examples here @grlima.

**Comment by benjamin-bader** [comment]
Hi, any update on this?  We'd very much like some kind of auto-correlation for non-HTTP-request workflows.  We're currently hacking it by setting up a fake RequestTelemetryContext, but we'd love to avoid relying on internal details.

**Comment by trask** [comment]
[3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent) supports auto-collection of Kafka and JMS in case you are using either of those

**Comment by fr1zle** [comment]
Something like this would probably also be needed to allow the tracking of batch-like operation, or is there a way to do this today?

**Comment by trask** [comment]
Closing this, messaging telemetry is auto-correlated in 3.x for Kafka, JMS, and RabbitMQ. Please open a new issue if messaging correlation across any other framework is needed. thx!
