### ISSUE TITLE
Release: AI Agent For Java 1.0.10 not available 

### ISSUE THREAD

**Issue by brunolins16** [Microsoft/ApplicationInsights-Java#605]
The release for version v1.0.10 does not list **application-insights-agent*.jar** file: 

https://github.com/Microsoft/ApplicationInsights-Java/releases/tag/v1.0.10

Please make this .jar file available for download because some users are still using JDK 1.6.

**Comment by grlima** [comment]
@brunolins16  - Thanks for posting. Until version 2.0.0, we did not keep a history of previous agent jars. Starting with version 2.0.0, we will be uploading them to https://github.com/Microsoft/ApplicationInsights-Java/releases
