### ISSUE TITLE
Process CPU Performance Counter doesn't show up in Metrics Explorer

### ISSUE THREAD

**Issue by dhaval24** [Microsoft/ApplicationInsights-Java#610]
Process CPU Performance Counter is not seen on the Metrics Explorer. The possible reason seems to be the SDK Sends this counter with a name : - % Processor Time 

However, the UX expects the name to be Process CPU. 

![image](https://user-images.githubusercontent.com/16353121/37548356-8bc54770-2934-11e8-81ea-fbfa6ffc2a33.png)

However when you look in the Analytics, this counter comes up with the name - % Processor Time

![image](https://user-images.githubusercontent.com/16353121/37550025-1567cab6-2944-11e8-816e-2348277cf1d9.png)

**Comment by grlima** [comment]
Misconfigured C++ redistribution lib.
