### ISSUE TITLE
TelemetryConfiguration should be Singleton Class

### ISSUE THREAD

**Issue by dhaval24** [Microsoft/ApplicationInsights-Java#612]
`TelemetryConfiguration.java` should be a singleton class. Ideally we never want TelemetryConfiguration object to be empty (i.e it should always have some default configuration except springboot scenario) and once a configuration object is created we should always reuse the same. 

The intention of `getActive()` method in the class looks like the same. I think the only reason this class isn't kept as singleton currently is because of tests. There is heavy use of 
`TelemetryConfiguaration mockConfig = new TelemetryConfiguration()`

However, this can be easily acomplished by using reflection : 
http://dunwood.blogspot.com/2004/05/instantiate-java-class-that-has.html

This will seal the SDK from users accidentally messing up with configuration object.

**Comment by grlima** [comment]
One may want to have multiple TelemetryConfiguration objects. That way different telemetry clients can use different configurations based on need (for example, send data to separate ikeys, different endpoints, different channel config, etc). I don't believe it was supposed to be a single instance. The "active" is simply the one used by automatic collection (requests, dependencies), but with the current design, the TelemetryClient has the freedom to use a different config.

**Comment by dhaval24** [comment]
@grlima  I believe this causes more confusion to user then ease. It will indeed be very difficult to keep a track of which TelemetryClient uses which configuration object. Ideally I think no one would want to for say use two different channels to send telemetry from the same application, or turn on SDKLogger for some client and off for other.

IMHO, simplicity should take precedence. There can be cases like this where your library is opinionated leaving behind some flexibility. For example - "Spring allowed users to do all sorts of fancy config but ultimately it was really hard. The way springboot solved this was the keep somethings opinionated to best practice. I believe this should be a good design change to consider. 

If you disagree, please provide me with certain user scenarios where you have actually seen people using different configuration with different telemetry client and we can brainstorm better alternative.

Infact, we also do not need multiple instances of telemetry client. In boot, we are doing the same. when spring creates beans and do dependency injection, it creates beans which are singleton in nature. Therefore when you autowire them in your client (class where dependencies are injected) they always get the same instance. This frees up lot of confusion and is almost always performance efficient too. Think about it :)
