### ISSUE TITLE
No data collected for default Performance Counters

### ISSUE THREAD

**Issue by MicNeo** [Microsoft/ApplicationInsights-Java#617]
Hi,

I'm running Spring app with AI SDK version 2.0.1. I've a problem, because I can see a lot of stuff collected from my app (like dependency calls, exceptions etc). However, when I open Servers tab, there is no data for counters like: Process CPU, Available memory, Process Time etc. Only one counter is collected: Process CPU (all cores). 

I'm running my app on Windows machine, I read that to collect that data I need to make sure that user which runs application should be in a “Performance Monitor Users" group. I added that user and rebooted machine, but it still doesn't collect that data. I don't see any errors related with those counters in my logs.

Any idea what can be wrong with my setup?

**Comment by dhaval24** [comment]
@MicNeo can you please go to analytics portal and run the following query : 

```
performanceCounters
| summarize by name
```

It will list all the performance counters which are getting collected from your machine. Also some of the windows performance counter requires  - Visual C++ Redistributable

Please turn on SDK Logs and see if you get this error : 

Failed to load native dll, Windows performance counters will not be used. Please make sure that Visual C++ Redistributable is properly installed: java.lang.RuntimeException: Failed to find 'applicationinsights-core-native-win64.dll' in jar.

**Comment by MicNeo** [comment]
@dhaval24 there're only few PC when I run that query, and most of them are my JMX counters. I can see only two default PC:
- % Processor Time
- Private Bytes

When app is booting up, in logs I have error like that:
`AI: TRACE 23-03-2018 09:56, 1: C:\Users\TEMP00~1\AppData\Local\Temp\2\AISDK\native\2.0.1 folder exists
AI: ERROR 23-03-2018 09:56, 1: Failed to load native dll, Windows performance counters will not be used. Please make sure that Visual C++ Redistributable is properly installed: C:\Users\USER\AppData\Local\Temp\2\AISDK\native\2.0.1\applicationinsights-core-native-win32.dll: Can't find dependent libraries.`

Which is strange, because I checked that path, and there is such file... Could be some permissions issue, I will check that. If you have any ideas please let me know.

I also noticed that AI is initializing twice. Seems like issue described here: https://github.com/Microsoft/ApplicationInsights-Java/pull/505 But that shouldn't effect it, becaise my JMX metrics are collected like they should be.

**Comment by MicNeo** [comment]
@dhaval24 i checked it, and it looks like that library is corrupted or something. I cannot load it even in very simple Java app (like only with System.load("path_to_lib")). I tried other libs, e.g. coming from C:\Windows\System32, I copied one of them to that path: "C:\Users\TEMP00~1\AppData\Local\Temp\2\AISDK\native\2.0.1", renamed it, and try to load it and it worked. But as soon as I try to load that AI library it breaks with UnsatisfiedLinkError.

**Comment by dhaval24** [comment]
@MicNeo thank you very much for going into details around this topic. I am marking this as a bug for now and one of us will pick this at the earliest. Btw, you are also free to pull down our repository and contribute. We really value all contributions here. 

Regarding #503 the branch is already merged in master and the next release should have it addressed.

**Comment by littleaj** [comment]
@MicNeo, you may be missing the Visual C++ Redistributable package. Try installing it ([here](https://www.microsoft.com/en-us/download/details.aspx?id=48145)) and restarting you application. Let me know if you continue to see that error after installing.

**Comment by MicNeo** [comment]
@littleaj I got it installed already. The file which AI tries to load is there. I even try reinstalling, but without success.

Maybe there're some other dependencies that I'm missing and that library cannot be loaded. Like I said, I tried simple Java app with System.load() and it didn't work with AI lib.

**Comment by MicNeo** [comment]
@littleaj @dhaval24 I found out the issue. It turned out that I've 32 bit JVM installed on 64 bit Windows with 64 version of Visual C++... and AI tries to use 32 bit of dll since there is 32bit Java installed. Since there wasn't 32bit version of Visual installed it crashed. That's why I couldn't run even simple app. After installing 32 bit version of Visual it start to working just fine. Shame on me :)
