### ISSUE TITLE
SQL Command is not being sent to Application Insights

### ISSUE THREAD

**Issue by rstirling** [Microsoft/ApplicationInsights-Java#626]
Hi,

I'm trying to collect the SQL commands executed by my App with no success. During the debug I can see the command value inside the Statement object, but it's not forwarded to RemoteDependencyTelemetry in class CoreAgentNotificationsHandler. My application uses Spring 4 and Hibernate to handle data from MSSQL server. The values I can get from command field in AI are all the same:

_jdbc:sqlserver://localhost:1433;authenticationScheme=nativeAuthentication;xopenStates=false;sendTimeAsDatetime=true;trustServerCertificate=false;sendStringParametersAsUnicode=true;selectMethod=direct;responseBuffering=adaptive;packetSize=8000;multiSubnetFailover=false;loginTimeout=15;lockTimeout=-1;lastUpdateCount=true;encrypt=false;disableStatementPooling=true;databaseName=ttc;applicationName=Microsoft JDBC Driver for SQL Server;applicationIntent=readwrite;_

This behavior is expected or there is a problem with my configuration?

**Comment by grlima** [comment]
@rstirling - Hi, thanks for posting. Have you configured the java agent?
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-agent#install-the-application-insights-agent-for-java

**Comment by rstirling** [comment]
@grlima - Hi, yes I got these lines on my console output:
_AI-Agent: INFO 02-04-2018 08:39, 1: Agent jar found at /C:/Users/rafael.stirling/Documents/apache-tomcat-8.0.39/webapps/ROOT/WEB-INF/lib/applicationinsights-agent-2.0.1.jar
AI-Agent: INFO 02-04-2018 08:39, 1: Agent jar name is applicationinsights-agent-2.0.1.jar
AI-Agent: TRACE 02-04-2018 08:39, 1: Successfully loaded Agent jar
AI-Agent: TRACE 02-04-2018 08:39, 1: Adding built-in instrumentation
AI-Agent: TRACE 02-04-2018 08:39, 1: Adding built-in JDBC Statements instrumentation
AI-Agent: TRACE 02-04-2018 08:39, 1: Adding built-in JDBC Prepared Statements instrumentation
AI-Agent: TRACE 02-04-2018 08:39, 1: Adding built-in HTTP instrumentation
AI-Agent: TRACE 02-04-2018 08:39, 1: Adding built-in Jedis instrumentation
AI-Agent: TRACE 02-04-2018 08:39, 1: Adding 'org/mule/module/client/MuleClient'
AI-Agent: INFO 02-04-2018 08:39, 1: Successfully registered Jmx connector.
AI-Agent: INFO 02-04-2018 08:39, 1: Agent is up_

**Comment by rstirling** [comment]
Hi,

I upgraded AI dependencies to 2.0.2 and the problem remains:
![image](https://user-images.githubusercontent.com/7254787/38442209-98fdc160-39b5-11e8-9f46-45e7311b827f.png)

**Comment by grlima** [comment]
@rstirling - Hi, thanks for posting. Do you see the SQL command when you search for dependencies in Analytics? For example, you can run this:

dependencies
| where type == "SQL"
| take 1 
| project data

**Comment by rstirling** [comment]
Hi @grlima ,

I set the log level to trace for AI and I got this line for every query executed:

_AI: TRACE 11-04-2018 10:40, 271(http-nio-8080-exec-3): Sending Sql RDD event for 'jdbc:sqlserver://localhost:1433;authenticationScheme=nativeAuthentication;xopenStates=false;sendTimeAsDatetime=true;trustServerCertificate=false;sendStringParametersAsUnicode=true;selectMethod=direct;responseBuffering=adaptive;packetSize=8000;multiSubnetFailover=false;loginTimeout=30;lockTimeout=-1;lastUpdateCount=true;encrypt=false;disableStatementPooling=true;databaseName=ttc;applicationName=Microsoft JDBC Driver for SQL Server;applicationIntent=readwrite;', command: '', duration=0 ms_

The command is always empty. I believe that is not suppose to be empty, right?

**Comment by grlima** [comment]
Hey @rstirling - Thanks for providing the traces! You are correct. It should not be empty. could you please share more information about your application so we can try to repro it ourselves? Mostly I think the SQL Server driver version you're using and your SQL client code where you execute the query. Thanks!

**Comment by rstirling** [comment]
Hi @grlima ,
I'm using Hibernate (5.2.10.Final) and sqljdbc4 (4.0) for my persistence layer. The queries are managed by Hibernate framework. I'll try to replace sqljdbc for mssql-jdbc to see what happens. Thanks.

**Comment by rstirling** [comment]
Hey @grlima ,

Good news! With the newer driver version I'm able see the SQL command in AI dependencies details panel. That was exactly the cause of the problem.

![image](https://user-images.githubusercontent.com/7254787/38948294-25661f0c-430d-11e8-8f1d-72b5f630110a.png)

I'm using the version _group: 'com.microsoft.sqlserver', name: 'mssql-jdbc', version: '6.4.0.jre8'_ to acquire the command correctly.

Thanks

**Comment by dhaval24** [comment]
Great. I will be closing this issue then.

**Comment by anmtando** [comment]
> Hey @grlima ,
> 
> Good news! With the newer driver version I'm able see the SQL command in AI dependencies details panel. That was exactly the cause of the problem.
> 
> ![image](https://user-images.githubusercontent.com/7254787/38948294-25661f0c-430d-11e8-8f1d-72b5f630110a.png)
> 
> I'm using the version _group: 'com.microsoft.sqlserver', name: 'mssql-jdbc', version: '6.4.0.jre8'_ to acquire the command correctly.
> 
> Thanks

What do you notice in case of a stored procedure? Will it show the complete stored procedure or the specific query. I want to see the cost of queries of a single stored procedure in Application Insights. I believe DMVs and SQL profilers give me that info but I wanted to see if I can get that info in AI directly.
