### ISSUE TITLE
Allow configuration for ApacheSenderFactory/ApacheSender

### ISSUE THREAD

**Issue by koldyr** [microsoft/ApplicationInsights-Java#630]
Currently we are not able to assign SSLContext with my TrustManager to HttpClients created in ApacheSenders. Would be really useful to allow such configuration.

**Comment by dhaval24** [comment]
@koldyr thank you very much for passing on the feature ask. Can you please also add a code sample to the issue demonstrating the behavior which you would like to see.

**Comment by koldyr** [comment]
Well, i forced to do following:
1 i implement ApacheSender. like this 
```
public class GeoApacheSender implements ApacheSender {

    private final CloseableHttpClient httpClient;

    public GeoApacheSender() throws KeyManagementException, NoSuchAlgorithmException {
        ConnectionSocketFactory reuseStrategyCopy = new SSLConnectionSocketFactory(SSLUtil.getSslContextTrustAll(), null, null,
                NoopHostnameVerifier.INSTANCE);

        final Registry<ConnectionSocketFactory> registry = RegistryBuilder.<ConnectionSocketFactory>create()
                .register("http", PlainConnectionSocketFactory.getSocketFactory())
                .register("https", reuseStrategyCopy).build();

        PoolingHttpClientConnectionManager cm = new PoolingHttpClientConnectionManager(registry);
        cm.setMaxTotal(DEFAULT_MAX_TOTAL_CONNECTIONS);
        cm.setDefaultMaxPerRoute(DEFAULT_MAX_CONNECTIONS_PER_ROUTE);

        httpClient = HttpClients.custom()
                .setConnectionManager(cm)
                .useSystemProperties()
                .build();
    }

    @Override
    public HttpResponse sendPostRequest(HttpPost post) throws IOException {
        return httpClient.execute(post);
    }

    @Override
    public void dispose(HttpResponse response) {
        try {
            if (response != null) {
                ((Closeable) response).close();
            }
        } catch (IOException e) {
            InternalLogger.INSTANCE.error("Failed to send or failed to close response, exception: %s", e.toString());
        }
    }

    @Override
    public void close() {
        try {
            httpClient.close();
        } catch (IOException e) {
            InternalLogger.INSTANCE.error("Failed to close http client, exception: %s", e.toString());
        }
    }

    @Override
    public HttpClient getHttpClient() {
        return httpClient;
    }

    @Override
    public void enhanceRequest(HttpPost request) {
        RequestConfig requestConfig = RequestConfig.custom()
                .setConnectionRequestTimeout(REQUEST_TIMEOUT_IN_MILLIS)
                .setSocketTimeout(REQUEST_TIMEOUT_IN_MILLIS)
                .setConnectTimeout(REQUEST_TIMEOUT_IN_MILLIS)
                .setSocketTimeout(REQUEST_TIMEOUT_IN_MILLIS).build();

        request.setConfig(requestConfig);
    }
}

```

2 i assign this instance to factory during app initialization:

```
            final Field apacheSenderField = ApacheSenderFactory.class.getDeclaredField("apacheSender");
            apacheSenderField.setAccessible(true);
            ApacheSender apacheSender = new GeoApacheSender();
            apacheSenderField.set(ApacheSenderFactory.INSTANCE, apacheSender);

```
Only after such manipulation my app can reach AI from our intranet. 

So it would be good to allow in ApacheSenderFactory create my instance of ApacheSender. Or in ApacheSender43 allow to pass PoolingHttpClientConnectionManager or any other ability configure httpClient

**Comment by grlima** [comment]
@koldyr - we will consider allowing config to specify custom senders, but a discussion is needed on the security implications as it will allow random code to be run. Possibly we can only allow the injection of Trust Managers or something else. But a question: are you doing this in order to trust all certs out there? Isn't this a security concern for you? Would it be better to install whatever certificates you expect to encounter in your intranet in the trusted store locally in the machines where AppInsights runs? That way you don't incur the risk of allowing any certs out in the wild.

**Comment by koldyr** [comment]
@grlima well, yes, basically you are right. but my particular case is specific to me and i realize mentioned security concerns still... it would be good to allow user configure httpClient in more flexible way, not only trust manager or SSLContext.
