### ISSUE TITLE
OkHttp3 not instrumented

### ISSUE THREAD

**Issue by tomaszglinski** [microsoft/ApplicationInsights-Java#636]
While looking for solution for #635, I found https://github.com/Microsoft/ApplicationInsights-Java/blob/master/agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/http/HttpClassDataProvider.java which defines the list of supported HTTP client libs. There is okhttp on the list, but current version has okhttp3 in the packages name, so it is not instrumented.
Could you add it?

**Comment by dhaval24** [comment]
@tomaszglinski thank you for raising an issue. Yes this is correct the OKHTTP version which is instrumented was version 2.x.x. AFAIR, OK HTTP instrumentation also doesn't support correlation in our SDK yet. Regarding OKHttp3 it has significant public API changes as compared to OKHttp2, so it would require full blown feature to add instrumentation. We can take this as a feature request and keep it in our backlog and triage appropriately.

At the same time, if you have time and motivation please feel free to create a PR for OKHttp3 instrumentation. We really value our external contributors and would love to have your contribute if you would like.

**Comment by littleaj** [comment]
Fixed in #971
