### ISSUE TITLE
 org.apache.httpcomponents:httpclient dependency data incorrect (class name instead of host)

### ISSUE THREAD

**Issue by tomaszglinski** [Microsoft/ApplicationInsights-Java#637]
While looking for solution for #635 I tried to use  io.github.openfeign:feign-httpclient lib as HTTP client lib provider, which uses org.apache.httpcomponents:httpclient (version 4.5.1 in my case). It worked a little bit, but the telemetry data looks incorrectly filled:

![image](https://user-images.githubusercontent.com/8693263/38315799-8802627c-3829-11e8-90b1-253ca87dcea3.png)

Is it a bug or some versions mismatch?

**Comment by grlima** [comment]
@tomaszglinski - are you using the latest version of the SDK (2.0.2)? I believe this issue has been fixed in #567

**Comment by dhaval24** [comment]
@tomaszglinski that is strange. I might have to reproduce this locally to understand better. Can you add a sample stripped down version of Springboot application using Feign client? I can then try to see what is going under the hood in this case.

**Comment by timja-kainos** [comment]
If it helps, I'm using spring boot with app insights 2.0.2, feign client configured to use Apache http client and it works
https://github.com/hmcts/cmc-claim-store/blob/master/src/main/java/uk/gov/hmcts/cmc/claimstore/config/HttpClientConfiguration.java#L21

![image](https://user-images.githubusercontent.com/21194782/38470751-32acaa1a-3b5f-11e8-9e0f-acb58e9a4dca.png)
![image](https://user-images.githubusercontent.com/21194782/38470756-46c937ac-3b5f-11e8-9e6a-2685f2124c80.png)

**Comment by dhaval24** [comment]
@timja-kainos this is awesome. Thank you very much for taking out time to show a working example. I believe @tomaszglinski might have missed updating the application-insights agent to version 2.0.2. 

PS: Your app-map looks great :)

**Comment by grlima** [comment]
This is fixed in the latest version (2.0.2).
