### ISSUE TITLE
Document how to set RoleName field for java

### ISSUE THREAD

**Issue by timja-kainos** [Microsoft/ApplicationInsights-Java#640]
Hi

How do you set the role name field for java for multi role applications?
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-monitor-multi-role-apps

The node.js sdk has a section like this:
https://github.com/Microsoft/ApplicationInsights-node.js#multiple-roles-for-multi-component-applications

Could the same be added for java sdk?
Happy to add it if you could provide a small sample, otherwise will keep digging.

Thanks

**Comment by timja-kainos** [comment]
I see this: https://github.com/Microsoft/ApplicationInsights-Java/issues/632

**Comment by timja-kainos** [comment]
We'll try it out on Monday, thanks @dhaval24

**Comment by grlima** [comment]
@timja-kainos - the documentation updates have been made to include this. It will go live today on this page: https://docs.microsoft.com/en-us/azure/application-insights/application-insights-correlation and the java [getting started page](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-get-started).

**Comment by grlima** [comment]
here's the doc:
https://docs.microsoft.com/en-us/azure/application-insights/application-insights-correlation#role-name
