### ISSUE TITLE
Create reference for AI-Agent.xml

### ISSUE THREAD

**Issue by littleaj** [microsoft/ApplicationInsights-Java#641]
Similar to the wiki page on [ApplicationInsights.xml](https://github.com/Microsoft/ApplicationInsights-Java/wiki/ApplicationInsights.XML), we should have a similar document for the agent config file.

**Comment by nikmd23** [comment]
Great idea!

Can you provide the initial listing of config keys/values? With that draft we can get this properly documented.

**Comment by v-gamaar** [comment]
Hello collegues

Do you have any update about this documantation? Thanks in advance, have an excellent day.

**Comment by dhaval24** [comment]
@v-gamaar unfortunately, we haven't been able to get to this yet. Are you looking for something specific where we can help out. @littleaj we should get to this at some point sooner rather than later.

**Comment by sairam-github** [comment]
Is there a further update on this? A reference document would really help. I had to spend a couple of hours to find a reference for adding configuration for method tracking. Refer https://github.com/microsoft/ApplicationInsights-Java/wiki/Configure-Dependecy-Type-in-the-Agent-Configuration.

**Comment by trask** [comment]
This is resolved in [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent) (configuration options are fully documented)
