### ISSUE TITLE
Docs: Add java examples on telemetry initializers and processors

### ISSUE THREAD

**Issue by grlima** [microsoft/ApplicationInsights-Java#649]
This page describes how telemetry initializers/processors can be coded, but no java examples are available: 
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-filtering-sampling

**Comment by nikmd23** [comment]
Can you let us know what's missing from or wrong with the ones in the doc right now at https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-filtering-sampling#java-telemetry-initializers
