### ISSUE TITLE
Agent calls logger before logger initialization. System property to enable javaagent logger?

### ISSUE THREAD

**Issue by littleaj** [Microsoft/ApplicationInsights-Java#653]
I noticed that there are several calls to `InternalAgentLogger` before the config file is read. This is odd because enabling the logger is done using that file.

It may be a good idea to have a system property which enables logging before the config file is read.

Thoughts?

**Comment by grlima** [comment]
What's the impact on users? Does this mean log messages are emitted even if agent logging is disabled in the config file?

**Comment by littleaj** [comment]
Yes, the proposed property would override the config file setting.

To be clear the goal here is to initialize the logger before the code path reaches the first log message. So, this could also be accomplished by reworking where and how the config file is parsed.
