### ISSUE TITLE
Relocate Guava package com.google.thridparty

### ISSUE THREAD

**Issue by florian-beetz** [Microsoft/ApplicationInsights-Java#661]
I noticed that the core library exports the package `com.google.thirdparty` of Guava.
Is there any reason why this package is not relocated, like all other packages of dependencies?

When this package is relocated, the SDK also seems to be compatible with Java 9.

**Comment by dhaval24** [comment]
@florian-beetz we relocate `com.google.common` but you are correct relocation of this package is missed. However you look at the POM for core: https://search.maven.org/remotecontent?filepath=com/microsoft/azure/applicationinsights-core/2.1.0/applicationinsights-core-2.1.0.pom It doesn't import the guava dependency so I believe it should not be a cause of any sort of conflict. 

Further, about Java 9, overall the main issue with the usage is on how to use the Java agent. Have you tried using Java agent to collect dependencies in Java 9 and did it worked out?

**Comment by florian-beetz** [comment]
The reason why this is relevant for Java 9 is that JPMS does not allow two modules exporting the same package. So when I try to compile a project that uses both Guava and ApplicationInsights compilation fails.

When this package is relocated the project can be compiled, but I was not aware of the problems with the Java agent.
