### ISSUE TITLE
Application hangs on exit with v2.1.0

### ISSUE THREAD

**Issue by curtisporter1** [Microsoft/ApplicationInsights-Java#662]
A standalone application built with ApplicationInsights-Java hangs on exit.  There is a thread pool (pool-1-thread-1) that is not shut down, and it prevents the application from exiting.  This does not occur with version 2.0.2.

Attached is a trivial program that demonstrates the problem.

[telemetrysample.zip](https://github.com/Microsoft/ApplicationInsights-Java/files/1985144/telemetrysample.zip)

**Comment by littleaj** [comment]
Thank you for bringing this to our attention. We're investigating the issue.

**Comment by littleaj** [comment]
I found the issue and have a PR for it. In the meantime, if this is blocking you, there is a workaround:

At the bottom of your main method, add `SDKShutdownActivity.INSTANCE.stopAll();`. This will stop all the threads in the SDK, including the one in question. If you have the SDKLogger enabled, you may see some exceptions, but this is expected.

**Comment by littleaj** [comment]
This fix will ship in the next release.
