### ISSUE TITLE
Consider renaming prefix for configuration properties

### ISSUE THREAD

**Issue by snicoll** [microsoft/ApplicationInsights-Java#673]
The current root namespace for this project is `azure.application-insights`. The Spring Boot project tries as much as possible to be concise and not use more than one word for namespacing to differentiate from the root prefix (the namespace) and a property name.

Perhaps this could be renamed to `azure.insights` or `azure.applicationinsights` to be consistent with the artifactId prefix [that is already used](http://search.maven.org/#search%7Cga%7C1%7Capplicationinsights)?

**Comment by dhaval24** [comment]
@snicoll this is fair. Though a point to ponder here is, how many users have onboarded to the starter by the time we make this change. This would be potential breaking change and can affect users already using beta version already released.

**Comment by snicoll** [comment]
@dhaval24 fair point as well though this is totally acceptable change for a beta IMO

**Comment by dhaval24** [comment]
@snicoll we will discuss on a plan for this item, as we pave way for stable release and I will update this thread. As far as starter is concerned, since you are one of the main contributors for the spring-boot framework, and had a chance to look at the application insights springboot starter, are there any other potential concerns I should know about, which are not upto the mark according to SpringBoot?

**Comment by snicoll** [comment]
@dhaval24 thanks for the feedback. I haven't had a chance to look at the code at all. Is there some sort of deadline for this?

**Comment by dhaval24** [comment]
@snicoll ideally, we would like to get user voice on their experience with the starter, fix burning issues and move to the first stable release (as this is a major milestone for many enterprise users to onboard fully), but that being said user feedback is important and we would like to get some meaningful ones. So, it should be safe to assume atleast 1/1.5 months of wait from now. By that time if we know the main loopholes, we could come up with a better stable release (which is more appreciated on start.spring.io)

**Comment by dhaval24** [comment]
@snicoll did you ever got a chance to look at the starter deeply? I would really like to hear your feedback.

**Comment by snicoll** [comment]
@dhaval24 thanks for the ping. I am afraid I did not: I've been very busy and out of the office lately. Late June doesn't look different so I'll do my best to squeeze this whenever I can

**Comment by dhaval24** [comment]
@snicoll thank you very much. Take your time!

**Comment by snicoll** [comment]
@dhaval24 I've sent a review in DM on Gitter, we can continue the discussion where you feel it is appropriate.

**Comment by snicoll** [comment]
If you use a `enabled` flag only in `@ConditionalOnProperty`  then the best practice is to write a manual metadata entry rather than an unused property in `@ConfigurationProperties`.

**Comment by dhaval24** [comment]
@snicoll much of this asks and feedback is being completed in #718 . Thanks for all your help!
