### ISSUE TITLE
Add documentation on how to onboard the agent to AppServices

### ISSUE THREAD

**Issue by grlima** [microsoft/ApplicationInsights-Java#678]

**Comment by dhaval24** [comment]
@nikmd23 can you take a stab at this? There are many instance where customers have asked to onboard to app services and they do not find an easy documentation. Specifically on onboarding Java Agent on App Services has always been a question!

**Comment by littleaj** [comment]
There's this: https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-custom-docker-image

I found that here: https://github.com/Azure-App-Service/tomcat

Basically, you set the `APPINSIGHTS_INSTRUMENTATIONKEY` environment variable to your iKey and it add the filter and agent to Tomcat automatically. https://github.com/Azure-App-Service/tomcat/blob/a268fb5281166180c44ecfcc58ef0bc07805aef8/8.5-jre8/init_container.sh#L70


I'm not sure if there are plans streamline this in the UI.

**Comment by dhaval24** [comment]
@nikmd23 in addition to what @littleaj told above we should also document how customers can onboard  java agent in traditional way. i.e what should be the location where they upload the agent and which place they would need to put the flag in tomcat's server.xml file.

**Comment by dhaval24** [comment]
In order to deploy springboot apps on windows app service, you would also have to modify web.config with following.

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <handlers>
            <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
        </handlers>
        <httpPlatform processPath="%JAVA_HOME%\bin\java.exe" arguments="-Djava.net.preferIPv4Stack=true -Dserver.port=%HTTP_PLATFORM_PORT% -jar &quot;%HOME%\site\wwwroot\AzureWebAppExample-0.0.1-SNAPSHOT.jar&quot;">
        </httpPlatform>
    </system.webServer>
</configuration>
```

To install java agent, you need to add a property `JAVA_OPTS` in the properties settings for App Services with the following value 

`-javaagent:D:/home/site/wwwroot/applicationinsights-agent-2.2.1-SNAPSHOT.jar`

This is essentially the path where java agent resides on app services.

**Comment by dhaval24** [comment]
@mrbullwinkle what is the update on this documentation. It's super critical =)

**Comment by mrbullwinkle** [comment]
This will go in on Monday Lauryn and I have time blocked out for Java docs then. Thanks for the reminder.

**Comment by dhaval24** [comment]
@mrbullwinkle what is the timeline for this change to happen. I see the docs pr still pending. I have added some comments there as well. We have a lot of tickets coming for this.
