### ISSUE TITLE
Can SDKLogger be enabled via springboot config?

### ISSUE THREAD

**Issue by Blackbaud-ChrisBlythe** [Microsoft/ApplicationInsights-Java#681]
After quickly reviewing the code, there doesn't appear to be a way to do this. Any recommendations/workarounds? Or does a property need to be added?

**Comment by dhaval24** [comment]
@Blackbaud-ChrisBlythe I assume you are using SpringBoot starter for Application Insights. In that case have you take a look at the readme : https://github.com/Microsoft/ApplicationInsights-Java/tree/master/azure-application-insights-spring-boot-starter

It has a whole bunch of properties which can be configured. Specifically to answer your question:

azure.application-insights.logger.level=trace

Add this property in your application.properties or yml file and you will start seeing the SDKLogs on the console. Hope it helps

**Comment by Blackbaud-ChrisBlythe** [comment]
Ah.... I looked at that, but missed it! Thanks!
