### ISSUE TITLE
TransmissionFileSystemOutput not working

### ISSUE THREAD

**Issue by spasero** [Microsoft/ApplicationInsights-Java#697]
Hello, 

I'm trying to stress Appinsights tracking mechanism, and I figured out that there's a bug inside the class TransmissionFileSystemOutput.
I tried to track 300,000 telemetry (traces, requests, dependencies), but I ran into error messages : "Persistent storage max capacity has been reached", even if the "MaxTransmissionStorageFilesCapacityInMB" was set to 1000MB.
I looked into the transmission folder inside the system temporary folder and saw that the error was raised when I had only a hundred files of 8KB each.
So, looking at the Java code (TransmissionFileSystemOutput.java:137) : 
```java
if (size.get() >= capacityInKB) {
    InternalLogger.INSTANCE.logAlways(InternalLogger.LoggingLevel.WARN, "Persistent storage max capacity has been reached; currently at %s KB. Telemetry will be lost, please set the MaxTransmissionStorageFilesCapacityInMB property in the configuration file.", size.get());
    return false;
}
```
If I'm correct, the variable "size" is updated with temporary file size in **bytes**, and the maximum capacity is in **MB**.
I rebuilt with the following condition `(size.get() >= capacityInKB * 1024)` and it worked perfectly.

Could you also please tell me where to find detailed information about the parameters of the "Channel" element of the ApplicationInsights.xml file ?
Does this configuration work for Java projects or are there still some issues like this one  ?

Regards,
Sebastien

**Comment by littleaj** [comment]
Good catch, @spasero! We are working on a fix.
