### ISSUE TITLE
eliminate log whem applicationinsight.xml is missing

### ISSUE THREAD

**Issue by Incarnation-p-lee** [Microsoft/ApplicationInsights-Java#699]
Is there any way to provide constructor for TelemetryClient with instrumentationKey. If I set the key without ApplicationInsight.xml, there must be some log as following:
`
AI: INFO 11-07-2018 15:53, 1: Configuration file 'ApplicationInsights.xml' was NOT found by default class loader
AI: INFO 11-07-2018 15:53, 1: Did not find configuration file 'ApplicationInsights.xml' in 'C:\Users\panli\.m2\repository\com\microsoft\azure\applicationinsights-core\2.0.1'
AI: INFO 11-07-2018 15:53, 1: Did not find configuration file 'ApplicationInsights.xml' in 'C:\Program Files\Java\jdk1.8.0_171\jre\lib'
AI: INFO 11-07-2018 15:53, 1: Did not find configuration file 'ApplicationInsights.xml' in 'C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext'
AI: INFO 11-07-2018 15:53, 1: Did not find configuration file 'ApplicationInsights.xml' in 'C:\Users\panli\Desktop\workspace\repo\azure\spring-cloud-azure\spring-cloud-azure-samples\spring-cloud-azure-eventhub-binder-sample\target\classes'
AI: INFO 11-07-2018 15:53, 1: Did not find configuration file 'ApplicationInsights.xml' in 'C:\Users\panli\Desktop\workspace\repo\azure\spring-cloud-azure\spring-cloud-azure-eventhub-stream-binder\target\classes'
AI: INFO 11-07-2018 15:53, 1: Did not find configuration file 'ApplicationInsights.xml' in 'C:\Users\panli\Desktop\workspace\repo\azure\spring-cloud-azure\spring-integration-azure\target\classes'
AI: INFO 11-07-2018 15:53, 1: Did not find configuration file 'ApplicationInsights.xml' in 'C:\Users\panli\Desktop\workspace\repo\azure\spring-cloud-azure\spring-cloud-azure-context\target\classes'
AI: INFO 11-07-2018 15:53, 1: Did not find configuration file 'ApplicationInsights.xml' in 'C:\Users\panli\Desktop\workspace\repo\azure\spring-cloud-azure\spring-cloud-azure-starters\spring-cloud-azure-starter-eventhub\target\classes'
`

**Comment by littleaj** [comment]
Here are some additional options for [setting the instrumentation key](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-get-started#alternative-ways-to-set-the-instrumentation-key). Those logs are for diagnostic purposes; they are only shown when `<SDKLogger />` is enabled in the configuration.

Let us know if that answers your question.

**Comment by Incarnation-p-lee** [comment]
@littleaj 
Thanks for your response, I mean if I use `setInstrumentationKey(key)` for AI, is there any way to remove logs for missing ApplicationInsight.xml. It looks boring when sdk initialization.

**Comment by dhaval24** [comment]
@Incarnation-p-lee in this case you are trying to programmatically set the instrumentation key of for telemetry client which is common case with SpringBoot. When you use our starter you won't see this message at all because it creates telemetry client using dependency injection. 
Apart from it we recommend the way of setting instrumentation key mentioned in the above documentation for friction free usage of ApplicationInsights Java SDK.

**Comment by Incarnation-p-lee** [comment]
@dhaval24 
Thanks for you details explain. So there is no way to disable these message from SDK side, right ?
 I think SDK and starter should keep the same behavior from users. I notice that `TelemetryClient` constructor has no way to configuration this.

**Comment by grlima** [comment]
Those are informational logs and, as such, are verbose in nature. They're not enabled by default.

**Comment by warrenzhu25** [comment]
@grlima As you said, these informational logs are disabled by default. I disagree with this. Actually, there is a bug related this. Inside `InternalLogger`, 

```java
    public void logAlways(LoggingLevel requestLevel, String message, Object... args) {
        String logMessage = createMessage(requestLevel.toString(), message, args);
        if (!initialized || loggerOutput == null) { //This condition is always true, so use ConsoleLoggerOutput
            new ConsoleLoggerOutput().log(logMessage);
        } else {
            loggerOutput.log(logMessage);
        }
    }
````

Below is your  implementation of `ConsoleLoggerOutput`, which always logs to standard error output
```java
public final class ConsoleLoggerOutput implements LoggerOutput {
    private final static String PREFIX = "AI: ";

    ConsoleLoggerOutput() {
    }

    @Override
    public void log(String message) {
        System.err.println(PREFIX + message);
    }

    @Override
    public void close() {
    }
}
```
Could you help fix this? You can easily reproduce this by removing applicationInsights.xml.
