### ISSUE TITLE
Trigger Event with TelemetryClient is silent without any information

### ISSUE THREAD

**Issue by Incarnation-p-lee** [Microsoft/ApplicationInsights-Java#700]
when trigger custom events with TelemetryClient, there is not information out, from user side, we have no idea about it works well or trigger failure.

**Comment by littleaj** [comment]
@Incarnation-p-lee, under normal operation, there won't be any output from the SDK on the client side. You should only see the event from your App Insights blade in the Azure Portal.

If you do not see telemetry in Azure, turn on the [SDK's diagnostic logging](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach the logs here (after redacting any private information, if any).

**Comment by dhaval24** [comment]
@Incarnation-p-lee I agree with what @littleaj said above. Here is a scenario when you used a custom event and why it doesn't make sense to get a log about a custom event sent to AI:
 
```
if (jobA.getResult() == false) {
    // Sends telemetry on AI Portal about the failed job 
    telemetryClient.trackEvent("jobA Failed", properties);
}
```

The whole point of monitoring is to get the information about irregular behavior of the applications right on cloud!

**Comment by Incarnation-p-lee** [comment]
@littleaj  @dhaval24 
Thanks for you explain, Here I mean it should show some result when trigger the event, either success or failure. Go to portal to check result is not the best practice, that seems confuse user from my opinion.

**Comment by dhaval24** [comment]
@Incarnation-p-lee just for your information : Monitoring systems are designed to be very low overhead systems with minimal logging. Infact if you look into what a monitoring system on cloud is - it provides observability of the underlying application with telemetry on the cloud. User flow is actually if some wiered behavior happens fire an alert or page on whatever alerting systems is there. 

Moresoever, internal SDK logging is used only to track if there are wiered issues going with SDK which negatively affects the user application and is turned on the by the user only when they see an exception coming on in the stack trace whose roots lie with the Application Insights Java SDK.

Therefore, it doesn't make any sense to have a log fired anytime when a custom event is sent to the AI. I think you are confused with what an event in real world MVC means whereas what a term event means in terms of telemetry. I hope I was able to clarify you. I would close this ticket with this and please feel free to comment or reopen if you feel so.
