### ISSUE TITLE
SmokeTest containers which are not yet pulled causes test to fail with timeout

### ISSUE THREAD

**Issue by littleaj** [microsoft/ApplicationInsights-Java#704]
### Expected behavior
When a dependency image does not exist locally, the smoketests should wait for the image to pull and start without timing out. This applies to classes using `@WithDependencyContainers`.

### Actual behavior
The smoketests have caused test failures because the timeout is hit before the image has finished downloading or started. This usually happens on the first run when the image has to be pulled; subsequent runs have the image available and run as expected.

**Comment by dhaval24** [comment]
@littleaj is it possible to have some sort of wait / check to see if that the tests have pulled down all the required images ?

**Comment by littleaj** [comment]
@dhaval24, maybe. I want to improve the policy for interacting with the docker client. Right now it just uses a timeout to determine if the process "hung," but (as this bug shows) this doesn't work in all cases.

**Comment by littleaj** [comment]
Fixed https://github.com/microsoft/ApplicationInsights-Java/pull/959
