### ISSUE TITLE
WebRequest tracking in Netty

### ISSUE THREAD

**Issue by rameezrajas** [microsoft/ApplicationInsights-Java#707]
**Is your feature request related to a problem? Please describe.**
Our web application is reactive runs on Netty server and not on Tomcat.  Need a feature to track the Webrequest in netty. Right now WebRequestTrackingFilter is based on Servlet.

**Describe the solution you would like**
Describe what you want to happen.

**Describe alternatives you have considered**
Describe any alternative solutions or features you've considered.

**Additional context**

**Comment by dhaval24** [comment]
@grlima and @littleaj I think this would be a pretty cool feature to have. Some of the prominent drivers like CosmosDB driver runs on Netty and Reactive communication library.

**Comment by grlima** [comment]
Marking as "future". We will consider for future releases.

**Comment by MS-jgol** [comment]
Are you using App Service or AKS by any chance? We do have Netty support in preview in those environments. Let's connect if this is something of interest, send me a dm!

**Comment by trask** [comment]
Netty is supported now in [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent)
