### ISSUE TITLE
VerifyError when using spring 5 web

### ISSUE THREAD

**Issue by rameezrajas** [Microsoft/ApplicationInsights-Java#708]
### Expected behavior
Application should start without VerifyError with application insights agent 2.1.1

### Actual behavior
Caused by: java.lang.VerifyError: Expecting a stackmap frame at branch target 175
Exception Details:
  Location:
    org/springframework/web/client/RestTemplate.<init>()V @138: ifeq
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2ab7 002c 2abb 002e 59b7 002f b500 312a
    0x0000010: bb00 3359 b700 34b5 0036 2abb 0038 59b7
    0x0000020: 0039 b500 3b2a bb00 0b59 01b7 003e b500
    0x0000030: 402a b400 31bb 0042 59b7 0043 b900 4902
    0x0000040: 0057 2ab4 0031 bb00 4b59 b700 4cb9 0049
    0x0000050: 0200 572a b400 31bb 004e 5903 b700 51b9
    0x0000060: 0049 0200 572a b400 31bb 0053 59b7 0054
    0x0000070: b900 4902 0057 2ab4 0031 bb00 5659 b700
    0x0000080: 57b9 0049 0200 57b2 0059 9900 252a b400
    0x0000090: 31bb 005b 59b7 005c b900 4902 0057 2ab4
    0x00000a0: 0031 bb00 5e59 b700 5fb9 0049 0200 57b2
    0x00000b0: 0061 9900 172a b400 31bb 0063 59b7 0064
    0x00000c0: b900 4902 0057 a700 1ab2 0066 9900 142a
    0x00000d0: b400 31bb 0068 59b7 0069 b900 4902 0057
    0x00000e0: b200 6b99 0017 2ab4 0031 bb00 6d59 b700
    0x00000f0: 6eb9 0049 0200 57a7 0034 b200 7099 0017
    0x0000100: 2ab4 0031 bb00 7259 b700 73b9 0049 0200
    0x0000110: 57a7 001a b200 7599 0014 2ab4 0031 bb00
    0x0000120: 7759 b700 78b9 0049 0200 57b2 007a 9900
    0x0000130: 142a b400 31bb 007c 59b7 007d b900 4902
    0x0000140: 0057 b200 7f99 0014 2ab4 0031 bb00 8159
    0x0000150: b700 82b9 0049 0200 57b1  

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version:  ApplicationInsights-Java-2.1.1
 - OS type and version: Windows Server
 - Application Server type and version (if applicable): 
 - Using spring-boot? Yes 
 - Additional relevant libraries (with version, if applicable):
    Spring-web-5.07-RELEASE

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

**Comment by dhaval24** [comment]
@rameezrajas are you using Application Insights Java Agent also?

**Comment by rameezrajas** [comment]
@dhaval24 Yes. we are using application insights java agent

**Comment by dhaval24** [comment]
@rameezrajas could you try using the plain SDK without agent once and see if the issue persist. To my best knowledge this seems to be an issue in instrumentation with Agent.

**Comment by rameezrajas** [comment]
@dhaval24 It works fine without the agent

**Comment by dhaval24** [comment]
Thanks, we will triage this issue and fix it in forthcoming releases based on the backlog.

**Comment by grlima** [comment]
@rameezrajas - could you please provide repro steps or a sample code of how you're using Spring RestTemplate? Also, does it happen with earlier or later versions of Spring web or is this isolated to a specific version?

**Comment by rameezrajas** [comment]
@grlima We are no longer seeing this error. I think our spring 5 application was pointing to old version application insights agent 1.0.8 instead of 2.1.1. We can close this issue
