### ISSUE TITLE
ApplicationInsights-Java having issues with Tomcat Shutdown.

### ISSUE THREAD

**Issue by sudhanshu20** [Microsoft/ApplicationInsights-Java#712]
### Expected behavior
All open threads by ApplicationInsights  close gracefully while Tomcat shuts down.

### Actual behavior
Tomcat 8.5 shutdown gets stuck while probably closing threads started by appinsights filter. This creates issues with Jenkins application auto build and deploy.
Removing the filter lets tomcat shutdown gracefully.

Attached shutdown log of tomcat which get stuck and does not respond.

[appinsights_issue.txt](https://github.com/Microsoft/ApplicationInsights-Java/files/2243920/appinsights_issue.txt)

**Comment by dhaval24** [comment]
@sudhanshu20 could you please provide the way you are instrumenting your application.

Also what kind of application are you having. Could you please provide details. Also please turn on SDK logs and provide us with those also.

**Comment by sudhanshu20** [comment]
@dhaval24 Its REST based api using Spring MVC and we are instrumenting the application using ApplicationInsights.xml instrumentationkey. The logging to the portal has no issues and we can access the logs via portal. The problem is with Tomcat Shutdown/Restart after the introduction of the app insights filter. What specific logs are you looking from the application?

**Comment by dhaval24** [comment]
@sudhanshu20 I am looking for the Application Insights SDK logs to see if the SDK is behaving wierdly. You can turn SDK logs on by `<SDKLogger />` adding this tag in your applicationinsights.xml

**Comment by littleaj** [comment]
@sudhanshu20 , There is a `ServletContextListener` which triggers the shutdown of the Application Insights thread pools. For spring-boot, it appears the application needs an additional annotation to find this listener, e.g. `@ServletComponentScan("com.microsoft.applicationinsights.web.internal")`. I noticed in the shutdown logs that I did not see `Shutting down thread pools` in the logs which is printed by the listener.

Here's an article with more general information about the spring-boot annotation: https://www.baeldung.com/spring-servletcomponentscan

Let us know if this is a sufficient workaround. We're investigating ways for this to be picked up without additional configuration.

For our reference, is this packaged as a WAR or JAR?

(for our records: #568, #513)

**Comment by sudhanshu20** [comment]
@littleaj , @dhaval24 . Thanks for looking into the issue. The workaround worked!. I added the following listener code in web.xml of the app and now server shutdown is smooth. FYI, it now prints the shutdown comment 'Shutting down thread pools' as well.

<listener>
		<listener-class>com.microsoft.applicationinsights.web.internal.ApplicationInsightsServletContextListener</listener-class>
	</listener>
The app is packaged as a WAR. It is built (using maven) and deployed on tomcat 8.5 using jenkins.
