### ISSUE TITLE
Locking connection threads on application start

### ISSUE THREAD

**Issue by gondar** [microsoft/ApplicationInsights-Java#719]
**Is your feature request related to a problem? Please describe.**
When application starts app insights will block and synchronise all incoming requests, due to lock on getContext method. This is far from ideal and looks to be against other design patterns in code.

**Describe the solution you would like**
Move context initialisation to init phase OR
decrease lock level on context initialisation to be on instance level not global

**Describe alternatives you have considered**
Both discussed above.

**Additional context**
The relevant bits of code: https://github.com/Microsoft/ApplicationInsights-Java/blob/master/core/src/main/java/com/microsoft/applicationinsights/TelemetryClient.java 
and 
https://github.com/Microsoft/ApplicationInsights-Java/blob/master/web/src/main/java/com/microsoft/applicationinsights/web/extensibility/modules/WebRequestTrackingTelemetryModule.java

The easiest solution looks like just initialising context in constructor of telemetry client.
<img width="1000" alt="screen shot 2018-08-27 at 07 44 43" src="https://user-images.githubusercontent.com/252896/44644268-ce5a0600-a9d3-11e8-8a2d-85dfeb1393f8.png">
<img width="1080" alt="screen shot 2018-08-27 at 07 45 05" src="https://user-images.githubusercontent.com/252896/44644269-ce5a0600-a9d3-11e8-9983-42d91babf0de.png">

**Comment by littleaj** [comment]
I think you make some good points here, @gondar. I don't think there's a good reason for TelemetryContext to be lazy here.

@dhaval24 , @grlima : Let's review this. At first glance, I think this would be a good change.

**Comment by dhaval24** [comment]
@littleaj yes on the surface this looks like a worth while performance improvement. We should consider if this works and initialization of most things should be in constructor as that is what constructors are meant for :) (though we would need to verify that it doesn't break out things)

**Comment by dhaval24** [comment]
@littleaj @grlima we should think about this. Having a synchronized here seems nasty for startup performance.

**Comment by littleaj** [comment]
I'm in favor of @gondar 's suggestion to move the context initialization to the TelemetryClient constructor. As I said above, I don't see what we gain from having it lazy init. Then we can remove the lock and declare context as `final`.

**Comment by trask** [comment]
Please try out [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent) and let us know if that resolves the issue for you
