### ISSUE TITLE
Structured logging from full text structured message

### ISSUE THREAD

**Issue by jivane** [microsoft/ApplicationInsights-Java#720]
**Is your feature request related to a problem? Please describe.**
We want to log a message through Log4J appender. However, it's full message and we would like to map some part in the message in specific appinsight fields
Example : logger.info(“
Sun Jun 26 12:05:05 -0700 2016,(NumberComparerTest.java:55) INFO : canCompareLess result is Less
“)
Use a conversation pattern to map part of msg to fields :
<param name="ConversionPattern" value="%d{EEE MMM dd HH:mm:ss ZZZ yyyy},(%F:%L) %-5p: %m%n" />

**Describe the solution you would like**
Change the appender code to use a conversion pattern
https://github.com/Microsoft/ApplicationInsights-Java/blob/4c63e07b7ce433053eedec4136f009f33d1b1705/logging/log4j2/appenderSrc/main/java/com/microsoft/applicationinsights/log4j/v2/internal/ApplicationInsightsLogEvent.java#L41-L47 

**Describe alternatives you have considered**
Changing the conversion pattern ourself. however we won't have any sdk update
Using ELK

**Additional context**
We don't want to rewrite code (the way we logged today).

https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/PatternLayout.html

**Comment by dhaval24** [comment]
@jivane thank you very much for raising a feature request. We would triage this for our future releases. If you would like to contribute please feel free to file a PR!
