### ISSUE TITLE
Support MongoDB dependencies in javaagent

### ISSUE THREAD

**Issue by tomaszglinski** [microsoft/ApplicationInsights-Java#727]
**Is your feature request related to a problem? Please describe.**
AI does not support MongoDB dependencies

**Describe the solution you would like**
Add support for MongoDB client lib(s)

**Comment by dhaval24** [comment]
@tomaszglinski thank you very much for raising feature request. Yes, we do not support MongoDB calls to be autocollected today. We will triage this feature for our future planning. In the meanwhile if you like feel free to contribute to the project. We are very open to accepting PRs and we recognize and appreciate contributions very much :)

**Comment by emmansun** [comment]
We implemented a `CommandListener` and injected it into `MongoClient` via `MongoClientOptions` to collect mongodb dependencies. In fact, the nodejs version also used such mongodb driver's APM feature to implment mongodb's telemetry auto-collect.

**Comment by hirowla** [comment]
This is something I'm very interested in having - in relation to Spring Boot applications.
