### ISSUE TITLE
Documentation: Update Quickstart

### ISSUE THREAD

**Issue by nikmd23** [microsoft/ApplicationInsights-Java#730]
Since we can't do what was proposed in https://github.com/Microsoft/ApplicationInsights-Java/issues/598,

update the content in our Quickstart so that is matches technically with the getting-started page but follows the format required for quickstarts.

**Comment by dhaval24** [comment]
@nikmd23 I agree with this one. By the way, some other teams in MS have also been actively creating docs around java and now this one features even on broader page of Java on Azure.

https://docs.microsoft.com/en-us/java/azure/?view=azure-java-stable

go to monitor webapps and you will see the same page of eclipse plugin. Definitely need to fix,

**Comment by littleaj** [comment]
Done
