### ISSUE TITLE
Documentation for LocalForwarderChannel

### ISSUE THREAD

**Issue by littleaj** [microsoft/ApplicationInsights-Java#741]
From PR #723:

## Proposed Documentation
To use the `LocalForwarderChannel`:

Add the following to your configuration file (ApplicationInsights.xml):
```xml
<Channel type="com.microsoft.applicationinsights.channel.concrete.localforwarder.LocalForwarderTelemetryChannel">
   <DeveloperMode>false</DeveloperMode>
   <EndpointAddress><!-- put the hostname:port of your LocalForwarder instance here --></EndpointAddress>

   <!-- The properties below are optional. The values shown are the defaults for each property -->
   <FlushIntervalInSeconds>5</FlushIntervalInSeconds><!-- must be between [1, 500]. values outside the bound will be rounded to nearest bound -->
   <MaxTelemetryBufferCapacity>500</MaxTelemetryBufferCapacity><!-- units=number of telemetry items; must be between [1, 1000] -->
</Channel>
```

If you are using SpringBoot starter, add the following to your configuration file (application.properties)
```yml
azure.application-insights.channel.local-forwarder.endpoint-address=<!--put the hostname:port of your LocalForwarder instance here-->
```
  
```yml
azure.application-insights.channel.local-forwarder.flush-interval-in-seconds=
azure.application-insights.channel.local-forwarder.max-telemetry-buffer-capacity=
```

Please note the default values are same for properties as well as xml config.

**Comment by mrbullwinkle** [comment]
Thanks @littleaj the changes to update this in the getting started doc and the applicationinsights.xml doc are merged to the private repo. The changes will go live between 10:00-10:30 AM (UTC-7).

**Comment by mrbullwinkle** [comment]
@littleaj one quick set of follow-up questions on this topic: 

What is the value add of having the SDK's telemetry picked up by the local forwarder rather than simply sending directly to Application Insights from the SDK? 

I understand the need of the local forwarder for getting OpenCensus generated traces/metrics into Application Insights, but why would a customer want to introduce an extra hop/potential point of failure in the process if they don't have to for part of their data? Couldn't they just send OpenCensus data via the local forwarder and still send the SDK data directly in parallel to the same ikey?

Is there a correlation/aggregation advantage to sending everything through the local forwarder or is it simply a matter of having a single point of transmission to Application Insights?

**Comment by dhaval24** [comment]
@mrbullwinkle as per my understanding, even for OpenCensus you really do not need a Local Forwarder. You can just have an OC exporter with HttpChannel and send everything in AI schema to endpoint. 

However, the real value that Local Forwarder adds is the rich set of AI capabilities that are today available in .NET SDK and not in other SDKs. Few of them are - Full blown support for Live Metrics, Adaptive Sampling etc. Hope that makes sense. Arthur can add more if he has deeper insights on this.

**Comment by dhaval24** [comment]
@mrbullwinkle I also left a bunch of comments on the PR for docs. @nikmd23 and @mrbullwinkle Going forward can we have a review process set before the merge happens so that we can catch anything which doesn't seem appropriate.

**Comment by littleaj** [comment]
@mrbullwinkle, there have been some asks for out-of-process data transmission. IMO, the best example of this is a swarm/cluster of docker containers deployed to AKS or similar. It will save resources on the host if all the application containers are sending data through the LocalForwarder; but I'm sure there are other scenarios which could be justified to have another process or machine handling the transmission.

The scenario you suggested is also possible.

Regarding correlation: I don't think there is anything gained in this respect by using LF. W.r.t. aggregation, possibly. For a CPU intensive application, one could argue that the TelemetryClient should just pass all the telemetry downstream and let the LF do any additional sampling.

@tokaplan, did I miss anything here?

**Comment by tokaplan** [comment]
What @dhaval24 mentioned above regarding support for Live Metrics, Adaptive Sampling, etc. is the primary driver. With LF, any SDK supports those things without us having to re-implement them. @littleaj's point is also an important one.
