### ISSUE TITLE
Instrument newer versions of the postgres jdbc SDK

### ISSUE THREAD

**Issue by timja** [Microsoft/ApplicationInsights-Java#749]
**Is your feature request related to a problem? Please describe.**
Postgres is not instrumented correctly by the agent

**Describe the solution you would like**
Update the code to support newer postgres SDK versions

**Describe alternatives you have considered**
We're currently manually instrumenting using the agent XML in some places but we have a lot of java applications that are missing out on this functionality.

**Additional context**
Need to update these lines of code:
https://github.com/Microsoft/ApplicationInsights-Java/blob/master/agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementClassDataProvider.java#L63
https://github.com/Microsoft/ApplicationInsights-Java/blob/master/agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementClassDataProvider.java#L222

To handle this commit:
https://github.com/pgjdbc/pgjdbc/commit/42c2e3b7953b2e68281c4ec269bd9749e135065b#diff-fc136162d0d2039cce76db7d26c9ba04

Specifically the rename from:
AbstractJdbc2Connection -> PgConnection

**Comment by dhaval24** [comment]
@timja thank you very much for raising a feature request. PostGres, is something we don't have official auto collection support for, and hence you see its untouched for long. We will take this as a feature request and triage it to future feature releases. 

@nikmd23, here is a feature request for PostGres. 

@timja by the way, feel free to submit a PR if you would be willing to contribute to the project. We welcome all contributions!
