### ISSUE TITLE
Update SDK Logger to output to any directory

### ISSUE THREAD

**Issue by littleaj** [Microsoft/ApplicationInsights-Java#751]
Right now, our logging has two options: `CONSOLE` or `FILE`.
`CONSOLE` prints to stdout.
`FILE` writes to a file, _always relative to `java.io.tmpdir`_ ([source](https://github.com/Microsoft/ApplicationInsights-Java/blob/40809cb6857231e572309a5901e1227305c27c1a/core/src/main/java/com/microsoft/applicationinsights/internal/logger/FileLoggerOutput.java#L140)) and this is the issue. In some environments, the directory to `java.io.tmpdir` is not accessible and the property cannot be overridden.

**solution**
The file path can be set with the XML element `<BaseFolder />`
If the specified path is absolute, use that exact path.
If the specified path is relative, use that path relative to `java.io.tmpdir`.

**possible fallout**
On windows: if someone currently has the BaseFolder set to a path with a leading slash, e.g. `\mylogdir`, then after this change, logs will then be written to the default drive instead of under java.io.tmpdir.
On Linux: same issue. leading slash would write to a different directory.

Note: if the file logger cannot write (e.g. if writing to file throws an IOException), it falls back to console logger. In the examples above, this will be the case if the application cannot write to `/`.

**additional tasks**
Update https://github.com/Microsoft/ApplicationInsights-Java/wiki/ApplicationInsights.XML with a description of the new functionality.

**Comment by dhaval24** [comment]
@littleaj and @grlima we should consider this proposal carefully. I believe it might open any security concerns, as it is very possible that logs may contain sensitive customer information.

**Comment by littleaj** [comment]
Planning to implement via slf4j #309

**Comment by dhaval24** [comment]
Closing as the PR is merged and released.
