### ISSUE TITLE
Update InternalAgentLogger with option to write to file

### ISSUE THREAD

**Issue by littleaj** [Microsoft/ApplicationInsights-Java#752]
This will make this a more consistent experience when configuring the SDK and the agent. SDK allows logging to `CONSOLE` or `FILE`, but [the agent only prints to stdout](https://github.com/Microsoft/ApplicationInsights-Java/blob/24c8eeea20232d9349d3dda393b117b459ea5783/agent/src/main/java/com/microsoft/applicationinsights/agent/internal/logger/InternalAgentLogger.java#L178).

**Solution**
Add the functionality to the agent logger, sharing as much code as possible with `core`.

**Comment by dhaval24** [comment]
@littleaj and @grlima I would rather propose SLF4J as a permanent solution.

**Comment by grlima** [comment]
@dhaval24 - SLF4J makes sense to me as well. Let's consolidate all SDK logging around SLF4J.
