### ISSUE TITLE
Enable queue producer/consumer correlation

### ISSUE THREAD

**Issue by benjamin-bader** [microsoft/ApplicationInsights-Java#764]
I've recently been implementing correlation between a queue producer and queue consumer, [as per the documentation](https://docs.microsoft.com/en-us/azure/application-insights/application-insights-custom-operations-tracking#queue-instrumentation), and hit a snag in the form of insufficient info from the SDK.

**TL;DR: There is no stable/documented/extant way to get a RemoteDependencyTelemetry's operation ID or actual ID, because they aren't generated until after being tracked.**

As I understand the process, the producer side needs to include both its ID and its _operation ID_.  The problem seems to be that the operation ID is not populated until after the call to `TelemetryClient.trackDependency(RemoteDependencyTelemetry)`.  Indeed, in the documentation the sample code uses an extension method `StartOperation<T>`, which [sets up an operation ID on its own](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/src/Microsoft.ApplicationInsights/TelemetryClientExtensions.cs#L101) that is then used to establish correlation.

In Java, there doesn't appear to be any equivalent.

As far as the ID of the `RemoteDependencyTelemetry` itself, I'm not 100% because I don't know this codebase all that well, but I can't find where or how it is _ever set at all_.  The .NET code appears to just generate a random int and base64-encode the binary representation of said int; I don't know whether/how that will work with the Java SDK.

**Describe the solution you would like**
I'd like support in the stable API for initializing operation IDs prior to tracking events, so that we can correlate producer/consumer workflows without relying on internal APIs.

**Describe alternatives you have considered**
I'm currently duplicating logic found in the internal `WebOperationIdTelemetryInitializer` class in my own code, which is obviously going to be fragile:

```java
RemoteDependencyTelemetry rdp = ...
String rootId = generateRandomBase64Id():
String parentId = return ThreadContext.getRequestTelemetryContext()
    .getHttpRequestTelemetry()
    .getContext()
    .getOperation()
    .getId();

dep.setId(rootId);

try {
  enqueueWork(rootId, parentId, theWork);
  rdp.success = true
} catch (e: Exception) {
  rdp.success = false
}

telemetryClient.trackDependency(rdp)
```

**Comment by dhaval24** [comment]
@reyang @lmolkova and @grlima do we have any current plans in near term to support Queue correlation out of the box in Application Insights Java SDK ?

**Comment by lmolkova** [comment]
@benjamin-bader AFAIK there are no immediate plans to support queues in java. Things you rely upon may change in future, e.g. `ThreadContext.getRequestTelemetryContext`, but those are public APIs and we'll have to our best to maintain them for a while. 
Telemetry Ids operationId, parentId, and Id you can safely rely on.

I also see there may be some issues with the code you have.

You should enqueue operation id and dependency id along with the message:

operation id (or root id): 
```java
return ThreadContext.getRequestTelemetryContext()
    .getHttpRequestTelemetry()
    .getContext()
    .getOperation()
    .getId();
```

and dependency id is `dep.getId()` 

So, you track this dependency, but on the consumer side, you have to track request properly.
i.e. 

```java
request.getContext().getOperation().setId(rootId);
request.getContext().getOperation().setParentId(parentId);
request.setId(... random...)
```

and you probably need to set request telemetry context on the ThreadContext so that whatever happens under this request is also correlated.

**Comment by benjamin-bader** [comment]
Thanks, folks; I appreciate the help.

**Comment by dhaval24** [comment]
@benjamin-bader np! Let us know if you were able to successfully instrument queues (producer / consumer) correlation and I will close this issue.
