### ISSUE TITLE
SpringBoot Application Insights Agent support

### ISSUE THREAD

**Issue by MattyNixon** [microsoft/ApplicationInsights-Java#765]
Hi guys, we would like to request native SpringBoot support for the Application Insights **_Agent_**

Things we would like:
1) AI-Agent.xml configuration support by annotations (similar to the fact that SpringBoot App Insights SDK does not require ApplicationInsights.xml). Having to package AI-Agent.xml alongside the applicationinsights-agent jar isn't very neat in the context of SpringBoot
2) A similar Agent project to applicationinsights-spring-boot-starter so the dependencies can be configured by Gradle/Maven automatically so we don’t have to set things like “-javaagent:/myApp/applicationinsights-agent-2.2.0.jar”. This jar is currently _manually_ added via the build process, we would rather this be packaged in Gradle/maven so that the versions can be kept the same

Our chosen platform is Docker, as such we've had to tweak things that are not covered in the guide. See my notes on this Documentation Request: https://github.com/Microsoft/ApplicationInsights-Java/issues/731

We have an open case with  @dhaval24  (hi!) so hopefully this can draw some more attention to this feature request

Demo code using Alpine Linux Docker image:
[appinsights_docker_springboot_demo.zip](https://github.com/Microsoft/ApplicationInsights-Java/files/2504628/appinsights_docker_springboot_demo.zip)

Apologies if I've missed anything!
-Matt

**Comment by dhaval24** [comment]
@MattyNixon thanks for opening this issue. We will keep a track of this.

**Comment by nitishsinghal29** [comment]
when can we have this feature available, it will really incorporate AppInsights java agent in spring boot app flawlessly.

**Comment by stackoverflow2** [comment]
any update on this feature? It will be very helpful if we have agent jar as maven dependency.

**Comment by MS-jgol** [comment]
@nitishsinghal29 @stackoverflow2 
Try the new Java 3.0 agent:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent
