### ISSUE TITLE
Add proper documentation on Spring’s Rest Template usage

### ISSUE THREAD

**Issue by grlima** [Microsoft/ApplicationInsights-Java#770]
In order for Application Insights to successfully instrument HTTP calls made with Spring's Rest Template, it is necessary that the template is configured with the Apache HTTP Client. By default, it is not.

By specifying "HttpComponentsClientHttpRequestfactory" in the constructor of a Rest Template, it will use Apache HTTP.

Here's an example on how to do it via Beans. This is a very simple example which uses the defaults of the factory. 

 @Bean
    public ClientHttpRequestFactory httpRequestFactory() {
        return new HttpComponentsClientHttpRequestFactory()
    }
 
    @Bean(name = 'myRestTemplate')
    public RestTemplate dcrAccessRestTemplate() {
        return new RestTemplate(httpRequestFactory())
    }

**Comment by dhaval24** [comment]
@mrbullwinkle yes, I think a section in the configure-spring-boot-java page as well as the collecting dependencies page should be good. Could you please prioritize this change as it comes often enough.

**Comment by dhaval24** [comment]
@mrbullwinkle could you please help to get this documented ? This is one of the issues we have seen frequently.
