### ISSUE TITLE
can't see  log4j2  System Property Lookup in customDimensions part of a  trace

### ISSUE THREAD

**Issue by MarijaJankovic623** [microsoft/ApplicationInsights-Java#780]
### Expected behavior
I expect to see System Property Lookup and Main Arguments Lookup when using log4j2 as a logger in customDimension part of my trace in application insight, as I can see Context Map Lookup.

### Actual behavior
I can't see System Property Lookup and Main Arguments Lookup as part of a trace customDimension property,
I can see Context Map Lookup.
A screenshot is attached below.

### To Reproduce
To reproduce it you need to follow steps to integrate Java Application Insight.
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-get-started
As a logger you need to use log4j2, and use System Property Lookup
https://logging.apache.org/log4j/2.0/manual/lookups.html

How to integrate log4j2 and application insight:
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/application-insights/app-insights-java-trace-logs.md

#### Sample Application
I created a Java test app that can be used to reproduce an issue, 
you need to add your own application insight key.
https://github.com/MarijaJankovic623/ApplicationInsightTestApp

### System information
Please provide the following information:
 - SDK Version:  1.8 Java
 - OS type and version: Windows 10 Enterprise version 1703
 - Using spring-boot? No
 - Additional relevant libraries:
List of libraries from gradle ( Gradle version 4.5.1 ):

    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile group: 'org.slf4j', name: 'slf4j-api', version: '1.7.25'
    compile group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.11.1'
    compile group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.11.1'
    compile group: 'org.apache.logging.log4j', name: 'log4j-jcl', version: '2.11.1'
    compile group: 'org.apache.logging.log4j', name: 'log4j-1.2-api', version: '2.11.1'
    compile group: 'org.apache.logging.log4j', name: 'log4j-slf4j-impl', version: '2.11.1'
    compile group: 'com.microsoft.azure', name: 'applicationinsights-logging-log4j2', version: '2.2.1'

### Logs
[logs-10.log](https://github.com/Microsoft/ApplicationInsights-Java/files/2652464/logs-10.log)
[logs-1.log](https://github.com/Microsoft/ApplicationInsights-Java/files/2652465/logs-1.log)
[logs-9.log](https://github.com/Microsoft/ApplicationInsights-Java/files/2652466/logs-9.log)
[logs-7.log](https://github.com/Microsoft/ApplicationInsights-Java/files/2652467/logs-7.log)
[logs-8.log](https://github.com/Microsoft/ApplicationInsights-Java/files/2652468/logs-8.log)
[logs-6.log](https://github.com/Microsoft/ApplicationInsights-Java/files/2652469/logs-6.log)
[logs-5.log](https://github.com/Microsoft/ApplicationInsights-Java/files/2652470/logs-5.log)
[logs-4.log](https://github.com/Microsoft/ApplicationInsights-Java/files/2652471/logs-4.log)
[logs-3.log](https://github.com/Microsoft/ApplicationInsights-Java/files/2652472/logs-3.log)
[logs-2.log](https://github.com/Microsoft/ApplicationInsights-Java/files/2652473/logs-2.log)
[logs.log](https://github.com/Microsoft/ApplicationInsights-Java/files/2652474/logs.log)

### Screenshots
Screenshot of a trace in application Insight

![image](https://user-images.githubusercontent.com/18408369/49574036-b9303400-f93f-11e8-9f64-e79ba6b4c43b.png)

Screenshot of a log from log4j2
![image](https://user-images.githubusercontent.com/18408369/49575587-593b8c80-f943-11e8-9091-5819ba310ec4.png)

**Comment by dhaval24** [comment]
@MarijaJankovic623 thanks for reporting the issue. We will take a look at this.

**Comment by dhaval24** [comment]
@MarijaJankovic623 we will treat this as a feature request and triage it. As of today you are right we do not automatically store this in custom dimension.

**Comment by dhaval24** [comment]
@MarijaJankovic623 sure, I will update this issue once this feature is done. By the way feel free to create a PR if you wish to contribute.

**Comment by MarijaJankovic623** [comment]
@dhaval24 Do you have any information when to expect this issue to be fixed? On my current project, we're using this library, and we're thinking to invest an effort into fixing it if the fix is not going to come in the near future.

**Comment by dhaval24** [comment]
Hi @MarijaJankovic623 thanks for the follow up. It might be a while since this feature would be out, as there are some other high p. issues to tackle at the moment. However we do have the item in our backlog.

That being said, we are happy to accelerate this feature, if you are willing to contribute to our library. We appreciate community contribution. You can add the feature to log4j application insights appender.

**Comment by nikhilingole** [comment]
Hi, @littleaj  / @dhaval24  - Has there been any update to this, even I am facing a similar situation 
where I am trying to add properties from either env or spring lookup but can't see it in ApplicationInsights log. I am using Spring Boot starters version - 2.6.0
Can you share a sample log4j2.xml configuration with the PatternLayouts including these look-ups so that I cross check my config.

**Comment by trask** [comment]
this is supported in 3.0 by adding `customDimensions` in the json configuration file: https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#custom-dimensions
