### ISSUE TITLE
Java Application Insights Live Stream Metric

### ISSUE THREAD

**Issue by piotrzaremba** [Microsoft/ApplicationInsights-Java#781]
I composed a simple java application that uses the Application Insights core jar file applicationinsights-core-2.2.1.jar. The only configuration I set is a Application Insights key via an environment variable. My application does NOT have a ApplicationInsights.xml file for configuration. Sending telemetry events works fine however I can not get the Live Stream Metrics to work I get the generic "Demo" template screen. Is there something I am missing?

https://stackoverflow.com/questions/53657353/java-application-insights-live-stream-metric

**Comment by littleaj** [comment]
Thank you for bringing this to our attention. This appears to be a bug with the minimum/default configuration when the ApplicationInsights.xml is not present.

As a workaround, try adding this line after you create the `TelemetryClient` instance:
```java
QuickPulse.INSTANCE.initialize();
```

**Comment by piotrzaremba** [comment]
What in the ApplicationInsights.xml file triggers Live Stream Metrics in Java.

**Comment by piotrzaremba** [comment]
@littleaj any update on my last question?

**Comment by littleaj** [comment]
@piotrzaremba,
QuickPulse reads the instrumentation key from the active configuration: https://github.com/Microsoft/ApplicationInsights-Java/blob/40809cb6857231e572309a5901e1227305c27c1a/core/src/main/java/com/microsoft/applicationinsights/internal/quickpulse/QuickPulse.java#L69

When the context is initialized in the TelemetryClient, it also grabs from the config.

Try this instead:
```java
TelemetryConfiguration.getActive().getChannel().setDeveloperMode(developerMode);
TelemetryConfiguration.getActive().setInstrumentationKey(applicationInsightsKey);
this.telemetryClient = new TelemetryClient();
QuickPulse.INSTANCE.initialize();
```

**Comment by dhaval24** [comment]
@piotrzaremba have you tried the work around that @littleaj suggested. Could you please update this issue with your results.

**Comment by piotrzaremba** [comment]
@littleaj @dhaval24 Works!

**Comment by dhaval24** [comment]
@piotrzaremba great to hear that it works. The message you are seeing, 

"Please upgrade SDK
You can stream any Application Insights metrics or events and filter them with custom queries. However, your app must be instrumented with Application Insights SDK version 2.4.0 or later. Learn more"

is a false message and you can ignore it. 

However it is true that we don't have filtering and sample telemetry support in Live metrics as of today in direct mode of the SDK. @nikmd23 to comment on the future roadmap of having full blown live metric support in the direct mode of the SDK. As far as I know we don't have immediate plans for it.

However, if you are willing to run a Side Car (out of proc agent) called Application Insights Local Forwarder (which can run on Linux as well as Windows) and pipe your telemetry through it you can get full blown live stream support. Here are some documentation on how to get started with Local Forwarder and Java SDK.

https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-get-started?toc=/azure/azure-monitor/toc.json#local-forwarder

Let me know if you have more questions.

**Comment by dhaval24** [comment]
I will close this one now. @piotrzaremba please reopen if you face further issues.
