### ISSUE TITLE
Web in release 2.2.1 doesn't relocate guava

### ISSUE THREAD

**Issue by petergphillips** [Microsoft/ApplicationInsights-Java#784]
We have just tried upgrading to the latest version of application insights - 2.2.1.

The 2.2.0 web version had relocated the guava packages to com.microsoft.applicationinsights.core.dependencies.google.common, but this looks to have been removed in the 2.2.1 release.

Instead the applicationinsights-web-2.2.1.jar includes files under com.google.common without any relocation.  This means that they conflict with guava itself and causes our application to no longer compile.  The guava version used by insights seems to be very old and doesn't include com.google.common.util.concurrent.SimpleTimeLimiter.create, which was added in version 22 of guava, which causes us compilation problems as we are using those features.

Note that this only affects the -web version.  The -core version correctly relocates the guava classes, but for some reason the 2.2.1 release of web no longer relocates.

**Comment by littleaj** [comment]
Thank you for bringing this to our attention. We'll investigate the issue.
