### ISSUE TITLE
WebFlux and Netty APIs are not supported in Springboot.

### ISSUE THREAD

**Issue by dhaval24** [microsoft/ApplicationInsights-Java#790]
Update this https://docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-java-applicationinsights?view=azure-java-stable document - Web Flux and Netty APIs are not supported in SpringBoot.

**Comment by mercer** [comment]
Any plans to offer support?

**Comment by dhaval24** [comment]
@mercer we definitely want to better support webflux and netty. I do not have a timeline for this yet, but this is definitely in our backlogs.
We are very open to contributions as well. Please feel free to contribute/raise a PR if you could :)

**Comment by marceloverdijk** [comment]
Is there an update on this?
I’m using Micronaut (based on Netty) and would like to setup trace logging using Application Insights.
As Netty has no notion of a `java.servlet.Filter` I’m not able to setup the integration unfortunately - as from the docs the integration is based on `Java’s.servlet.*`.

**Comment by dhaval24** [comment]
@marceloverdijk unfortunately, there is still no update on this. However, this feature is definitely on our backlog to support Netty.  If you are open to submit a PR, we would welcome your contribution and I can help review the code and ensure a successful contribution. 

Currently the web integration is based on servelet stack. However, you ca definitely track the requests manually by using `TelemetryClient.trackRequeust()` if you would like to do.

**Comment by marceloverdijk** [comment]
@dhaval24 thx for the feedback.
I will look into the `TelemetryClient.trackRequeust()`

Does the trace logging via Logback as described here https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-trace-logs work without the http filter?

That links refers to the http filter, so it's not clear what is needed to setup this trace logging.

**Comment by dhaval24** [comment]
@marceloverdijk yes log4j and logback would work without http filter. They have no dependency on it.

**Comment by marceloverdijk** [comment]
@dhaval24 that sounds promising! I have some further questions related to the setup in that case, but I don't think it's best to hijack this issue for that. Should I create a new issue with the question, or is there another channel that I can use best?

**Comment by dhaval24** [comment]
@mercer yes please create a new issue for it. This issue is mostly to track Netty and WebFlux support :)

**Comment by dsibilio** [comment]
I've noticed the Pull Request which added Netty/Webflux support has been merged into the **codeless** branch (https://github.com/microsoft/ApplicationInsights-Java/pull/1074).

Any idea on when this feature will be released for usage with the Spring Boot starter module?

**Comment by UncleInf** [comment]
Could you please clarify the state of this feature? Do we have a reasonable (in complexity) path of using insights in webflux even before full spring boot support?

**Comment by MS-jgol** [comment]
Are you using App Service or AKS by any chance? We do have Netty/Webflux support in preview in those environments. Let's connect if this is something of interest, send me a dm!

**Comment by zaabskr** [comment]
@MS-jgol Do you mean you have provided support in applicationinsights-spring-boot-starter for Netty/Webflux? If so do let me know how to enable it.

**Comment by MS-jgol** [comment]
@zaabskr Let's first clarify: are you running your app(s) in App Service or AKS? We started supporting Netty/Webflux in those environments only.

**Comment by zaabskr** [comment]
@MS-jgol I am running the app in App Service

**Comment by intuitiveminds** [comment]
@MS-jgol @trask I'm also interested in testing the Webflux/Netty support. We are using App Service to deploy a Spring Boot-enabled reactive application as a jar file and I included the application insights boot starter (v2.5.1) - should HTTP telemetry flow in automatically? Or do we have to configure something or use a different version of the SDK?

Thanks in advance,
Sven

**Comment by zaabskr** [comment]
@intuitiveminds  The support is available in azure spring cloud. It is in preview mode.

**Comment by J4cku** [comment]
Hi,
jsut to be clear - there is no possibility to use either applicationinsight-spring-boot-starter or java agent for webflux apps right now?

**Comment by trask** [comment]
@J4cku that is correct

**Comment by MS-jgol** [comment]
@zaabskr On App Service, you can use auto instrumentation for your apps on Linux (not for custom containers though) and Windows. WebFlux and Netty are supported in that environment.

**Comment by oscarh** [comment]
If I understand correctly, there has already been a solution developed, but this solution isn't yet publicly available? We are running a number of Java Spring Boot applications using WebFlux in AKS. Is it possible for us to access to a version of the applicationinsights-spring-boot-starter that would work for us?

**Comment by MS-jgol** [comment]
Anyone interested in Application Insights in preview, please follow the instructions here:
https://github.com/microsoft/Application-Insights-K8s-Codeless-Attach/blob/master/SETUP.md

Your feedback is very much appreciated!

**Comment by oscarh** [comment]
> Anyone interested in Application Insights in preview, please follow the instructions here:
> https://github.com/microsoft/Application-Insights-K8s-Codeless-Attach/blob/master/SETUP.md
> 
> Your feedback is very much appreciated!

Sorry about my confusion, but how is this related to the applicationinsights-spring-boot-starter? I think that we would prefer add that to our spring configuration, rather than deploying a side-car on each pod.

**Comment by MS-jgol** [comment]
@oscarh There is at the moment no other way for us application insights to support Webflux/Netty. In March we will be releasing a stand alone agent that will have the functionality you are looking for.

**Comment by apescione** [comment]
Any News about this support? @MS-jgol about the stand alone agent?

**Comment by MS-jgol** [comment]
@oscarh @zaabskr @J4cku @dsibilio @apescione 
We are in private preview now!! The agent works in any environment. Please follow the link below for the full list of functionality supported and the instructions.
Public preview is March 31st. 
Please, everyone, provide your feedback - we really appreciate it!
https://github.com/trask/docs-work-in-progress/wiki/Application-Insights-Java-3.0-Private-Preview

**Comment by oscarh** [comment]
Hi, is the public preview available now?

Where can we provide feedback to the private preview? We seem to have issues connecting to Redis cache since we've added the agent.

**Comment by trask** [comment]
Hi @oscarh! Yes, public preview is available now: https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.0-PREVIEW.

If you have any issues with the preview, please open a new issue here.

**Comment by MS-jgol** [comment]
@oscarh Thank you for getting back to us! @trask beat me to the answer... :)
Here is the link to more docs just in case: 
https://github.com/microsoft/ApplicationInsights-Java/wiki/3.0-Preview:-Getting-started
