### ISSUE TITLE
First call to telemetry.getContext() takes a lot of time to execute

### ISSUE THREAD

**Issue by IndicareLeve** [microsoft/ApplicationInsights-Java#798]
### Expected behavior
Call telemetry.getContext() to set operationId and parentId to correlate events

### Actual behavior
The call gets executed correctly, but it takes about 30/40 seconds for every new TelemetryClient. I'm using application insights with MuleSoft, so I have to instantiate a new TelemetryClient for every request that I receive. Subsequent calls to .getContext() executes normally in no time.

### System information
Please provide the following information:
 - SDK Version: applicationinsights-core version 2.3.0
 - OS type and version: MacOs Mojave
 - Application Server type and version (if applicable): Mulesoft runtime 4.1.3 calls an external java class that wraps Application Insights SDK
 - Using spring-boot? No
 - Additional relevant libraries (with version, if applicable):

### Logs
I've enabled the debug logs but no files get generated.

**Comment by dhaval24** [comment]
@Salamadonna thanks for creating an issue. It seems that this would be pretty much expected with current design as when the first time `getContext()` method is called first time, it takes a lock and then run `createInitializedContext()' method where it initializes all the telemetry initializers once synchronously. 

The above happens only once when first time method is called on TelemetryClient instance. However subsequent calls are cached, so it returns very quickly.

**Comment by dhaval24** [comment]
We usually recommend to reuse TelemetryClient if possible and generally that is a good practice too, to reduce the producers to the telemetry channel.

**Comment by trask** [comment]
Please try out [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent) and let us know if that resolves the issue for you
