### ISSUE TITLE
Provide XML/SB/Agent configuration for exceptions truncation

### ISSUE THREAD

**Issue by vlev** [microsoft/ApplicationInsights-Java#804]
**Is your feature request related to a problem? Please describe.**
We need to have some control on maximum exception's chain depth and trace length in order to guarantee it's acceptance by Azure backend. 
Currently if the size of encoded exception exceeds 64Kb it's being refused by backend. 
Related issue: #482. 

**Describe the solution you would like**
Each type of configuration should provide the ability to set max depth of exception's chain and max trace length per exception. Possible names for these variables: stackSize, traceLength.

**Describe alternatives you have considered**
We may also hardcode those values. But such approach won't be flexible enough.

**Additional context**
Agent already have option stackSize (see ConfigRuntimeExceptionDataBuilder.java) which is used in ExceptionTelemetry.convertExceptionTree as a cap on max exceptions graph length.

**Comment by dhaval24** [comment]
@vlev a quick comment on naming first. I would rather prefer something different than `traceLength`. `trace` is common terminology in Distributed Tracing (a.k.a correlation) and also is sometimes intermixed as logs. This would create yet another confusing. 

May be `exceptionTraceLength` or something of that sort is better alternative. @reyang  your thoughts on this?

**Comment by trask** [comment]
Resolved by #1702
