### ISSUE TITLE
DockerContextInitilizer + SpringBoot +  logback.ApplicationInsightsAppender

### ISSUE THREAD

**Issue by ferantivero** [Microsoft/ApplicationInsights-Java#807]
### Expected behavior
I'd have expected to be able to add docker information to every telemetry information that is being sent to AI using logback.ApplicationInsightsAppender. 

### Actual behavior
I couldn't find a way to get it configured neither from the application profile or imperatively from code. 

Based on some docs I should be able to achieve that through ApplicationInsights.xml by adding the following but I'm using SpringBoot with application.properties: 

```xml
<Add type="com.microsoft.applicationinsights.extensibility.initializer.docker.DockerContextInitializer"/>
```

### To Reproduce
Create Java SpringBoot application using the Application Insights Java SDK (agent config) and try to configure Docker contextualization. 

### System information
Please provide the following information:
 - SDK Version: Application Insights Java SDK 2.3.0
 - Using spring-boot? yes

**Comment by dhaval24** [comment]
@ferantivero you can easily do this by creating a custom Telemetry Processor and wire it as a bean. In the process() method of this telemetry processor you can add  docker related information as custom dimension. This will add that docker information as a key-value pair in every telemetry item. 

PS: If you are using SpringBoot I would recommend that you use Application Insights SpringBoot Starter. It allows you to configure AI with properties file and is springboot friendly.

You can follow this doc : https://docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-java-applicationinsights?view=azure-java-stable 

and this Readme : https://github.com/Microsoft/ApplicationInsights-Java/tree/master/azure-application-insights-spring-boot-starter

**Comment by dhaval24** [comment]
You can also use `DockerContextInitializer` telemetry processor if it suits your needs which comes with the SDK by default. It can be done by adding following bean in SpringBoot app:

```
@Bean
    public TelemetryInitializer DockerContextInitializer() {
        return new DockerContextInitializer();
    }
```

**Comment by ferantivero** [comment]
thanks for quick reply @dhaval24 adding the Bean didn't work. Please note that yesterday I've also tried doing the following imperatively without luck:

```java
TelemetryConfiguration.getCurrent().TelemetryContextInitilizers.Add(new DockerContextInitializer());
```

Maybe I am missing something. I was wondering if we have a same code sample where this is working. Also, Ideally I'd expect to be able to configure this from an application profile.

**Comment by dhaval24** [comment]
The Bean should definitely work. I am not sure, but I will try it in a demo app in a day and let you know. In the starter code, https://github.com/Microsoft/ApplicationInsights-Java/blob/9384cd1737a72fd02027e2ef91a1c6c64d181878/azure-application-insights-spring-boot-starter/src/main/java/com/microsoft/applicationinsights/autoconfigure/ApplicationInsightsModuleConfiguration.java#L73 we also add initializers like bean.

**Comment by dhaval24** [comment]
@ferantivero I exactly added following bean in the main method of the springboot app:

```
@Bean
	public TelemetryInitializer dockerContextInitializer() {
		return new DockerContextInitializer();
	}
```
and when I placed the debugger inside the track() method in telemetry client I could see that DockerContextInitializer() was called successfully so the bean configuration works. 

Wether it gets the required information depends on the information that docker context initializer adds. 

At the very least as I meantioned above you can easily create you own telemetry processor and add it as a bean.

**Comment by dhaval24** [comment]
@ferantivero were you able to address your issue with above recommendation? Please let us know.

**Comment by dhaval24** [comment]
@ferantivero I will close this issue for now. Please reopen if the issue persists.
