### ISSUE TITLE
Application Map diagram has an extra http as part of the topology

### ISSUE THREAD

**Issue by ferantivero** [Microsoft/ApplicationInsights-Java#808]
### Expected behavior
not seeing extra http call or at least not as leaf. 

### Actual behavior
from the application map there is an extra http call drawn as leaf

### To Reproduce
correlate telemetry using Application Insights JAVA SDK (agent) with the following profile:

```
azure.application-insights.enabled=true
# Enable/Disable web modules. Default value: true.
azure.application-insights.web.enabled=true
# Logging level [all, trace, info, warn, error, off]. Default value: error.
azure.application-insights.logger.level=info
# Enable/Disable default telemetry modules. Default value: true.
azure.application-insights.default-modules.ProcessPerformanceCountersModule.enabled=true
azure.application-insights.default-modules.JvmPerformanceCountersModule.enabled=true
azure.application-insights.default-modules.WebRequestTrackingTelemetryModule.enabled=true
azure.application-insights.default-modules.WebSessionTrackingTelemetryModule.enabled=true
azure.application-insights.default-modules.WebUserTrackingTelemetryModule.enabled=true
azure.application-insights.default-modules.WebPerformanceCounterModule.enabled=true
azure.application-insights.default-modules.WebOperationIdTelemetryInitializer.enabled=true
azure.application-insights.default-modules.WebOperationNameTelemetryInitializer.enabled=true
azure.application-insights.default-modules.WebSessionTelemetryInitializer.enabled=true
azure.application-insights.default-modules.WebUserTelemetryInitializer.enabled=true
azure.application-insights.default-modules.WebUserAgentTelemetryInitializer.enabled=true
```
#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: 2.3.0
 - OS type and version: linux containers
 - Application Server type and version (if applicable): tomcat running within a Docker Container in AKS 
 - Using spring-boot? yes
 - Additional relevant libraries (with version, if applicable):

### Screenshots
please note that the circle in red is kind of unexpected as leaf...
<img width="670" alt="image" src="https://user-images.githubusercontent.com/158487/51681080-5879bb00-1fc2-11e9-95dd-76c3808aab31.png">

**Comment by dhaval24** [comment]
@ferantivero there can be multiple possibilities here.
Application Insights Java Agent can currently only Instrument Apache HTTP Client Rest calls. 

1. It might be very likely that one of your services is not using Apache Http under the hood of spring rest template and hence you see it as a terminating HTTP dependency. 

2. It is also possible that one of your service is not able to send Request-Id header in response to the calling service. 

Can we confirm 1. that you are using Apache HTTP client everywhere and if that is the case we might need some fidler traces here.

**Comment by ferantivero** [comment]
thanks for quick reply @dhaval24 

1. I'm actually using Apache HTTPComponents Client for RestTemplate(s). In fact, before using that specific http client AI wasn't even able to correlate properly the invocations.

2. what you see as ```foo-container``` and ```bar-container``` are just a regular ASP.NET Core services apps with zero-code-light and as you can see the topology is correct between this two. That being said, I would expect response header are being sent accordingly. The only problem is between the java service (java...t-container and foo-container). 

do you think it could be an opt-in module/initializer I could turn off? 
I'm ok with this http call being shown but I would expect this as a node between java-...t-container and foo-container and not as a leaf.

**Comment by ferantivero** [comment]
@dhaval24 hold on with this. I've been testing using dev spaces in AKS and I think this could be the root cause for this. I'll confirm tomorrow. Sorry for the inconveniences.

**Comment by dhaval24** [comment]
Sounds good. Let me know

**Comment by ferantivero** [comment]
@dhaval24 I can still reprod this even after removing user dev spaces in AKS. But my cluster is now a bit inconsistent. So please feel free to close this one. I will take a look at this sometime next week in a fresh cluster and will ping you if needed.

**Comment by dhaval24** [comment]
@ferantivero sounds good. Please reopen if you continue to see the issue.
