### ISSUE TITLE
Live Metrics Sample Telemetry

### ISSUE THREAD

**Issue by ferantivero** [Microsoft/ApplicationInsights-Java#809]
### Expected behavior
from Live Metrics I want to see sample telemetry being sent to AI like I'm currently able to see from ASP.NET Core apps

### Actual behavior
AI Live Metrics Stream sample telemetry doesn’t seem to be working with application insights Java Spring Boot Logback.

Please note that telemetry is actually being sent and properly correlated as expected. It is just not being displayed in the Sample Telemetry widget from Live Metrics view.  

### To Reproduce
Spring Boot using Application Insights Java SDK (agent) with a logback appender with level info.

### System information
Please provide the following information:
 - SDK Version: 2.3.0
 - OS type and version: Linux Docker Container deployed into a AKS cluster. 
 - Using spring-boot? yes

**Comment by dhaval24** [comment]
@ferantivero this feature is currently not available in direct mode of AI java SDK. However, you might be able to get this if you configure Local Forwarder https://github.com/Microsoft/ApplicationInsights-LocalForwarder

However, I am not sure if you are willing to take this route. Nonetheless, this feature is currently not available without out of proc Local forwarder. We might add this capability in sdk directly in future but this is not currently in the coming semester roadmap.

**Comment by ferantivero** [comment]
@dhaval24 may I ask if we have plans to implement this in direct mode? I'm trying to understand if full fleshed AI for Java apps is going to be only available through Local Forwarder.

Additionally, I know we have some [docs on this](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-get-started?toc=%2Fazure%2Fazure-monitor%2Ftoc.json#local-forwarder) but I wasn't wondering if we have a demo app with it.
