### ISSUE TITLE
Application Insights showing 200 for failed requests

### ISSUE THREAD

**Issue by DineshAyyapillai** [microsoft/ApplicationInsights-Java#810]
Even from the latest application insights version **2.3.0**, the Response code issue which is described in the below fix is not resolved,

https://github.com/Microsoft/ApplicationInsights-Java/pull/603

Did we find any better alternatives or solution for the issue?

With Regards,
Dinesh Ayyapillai.

**Comment by littleaj** [comment]
@DineshAyyapillai 
Unfortunately, that issue still exists in the filter, but we may be able to find a workaround. I just need some additonal information:

* Just want to confirm that this is with RequestTelemetry, correct?
* Are you using SpringBoot?
* Are you using other filters?
* Are you using custom error pages?
* Is the `success` field correct?

**Comment by dhaval24** [comment]
@DineshAyyapillai, also please mention how you have instrumented your application. Are you using Springboot starter, or just plain SDK? 
We had fixed this problem for Springboot starter case mostly with #766

**Comment by DineshAyyapillai** [comment]
@littleaj 

- Yeah it is RequestTelemetry,
- We are using SpringBoot
- No, We are using "appInsightsWebRequestTrackingFilter"
- We are not using the custom error pages
- No, It's incorrect showing "Successful on failed request"
- @dhaval24 - We are using and we set the precedence order as "1"

**Comment by dhaval24** [comment]
@DineshAyyapillai thanks for mentioning that. @littleaj has a little more context on non springboot scenarios. Often it is possible that sometimes an error code is set in the request telemetry after the object escapes the filter chain. i.e by some error handler etc. In that case it is likely that request telemetry object might miss the result code.

Also, it might be possible if you are using Async servlet request it might have issues similar to that. If possible .

**Comment by dhaval24** [comment]
Essentially this is dup of #600

**Comment by DineshAyyapillai** [comment]
@dhaval24 Yeah, It's almost similar but any idea on whether the issue will be fixed in the upcoming releases of application insights or any alternative solutions to work on.

**Comment by dhaval24** [comment]
moved the label to enhancements, as this is more about handling async requests.

**Comment by dhaval24** [comment]
@DineshAyyapillai could you please also explain you entire scenario of how you are using async requests, so that we can capture the scenario correctly.
