### ISSUE TITLE
Duplicate HTTP dependencies when using Spring Rest Template

### ISSUE THREAD

**Issue by dhaval24** [microsoft/ApplicationInsights-Java#812]
Spring Rest Template instrumentation is incomplete and doesn't add correlation related information. The class `RestTemplateMethodVisitor` doesn't add correlation headers to requests like `HttpClientMethodVisitor` (which instruments ApacheHttpClient). 

Therefore currently if the user uses Apache Http Client with RestTemplate two HTTP dependencies are captured. 

While the correlation happens for dependency captured via Apache Http Client under Rest Template, due to incorrect or incomplete instrumentation of RestTemplate, we get duplicate dependencies on portal.

Temporarily consider disabling the Rest Template Instrumentation, in favor of Apache HTTP Instrumentation.

cc: @littleaj @reyang

**Comment by dslack** [comment]
@dhaval24 Running into this issue, can we exclude the RestTemplate instrumentation through configuration, or perhaps use AOP to prevent the onMethodEnter from executing?

**Comment by dhaval24** [comment]
@dslack there is no easy way to turn this off from configuration. However, there can be a short term workaround. We can easily write a TelemetryProcessor to filter out the duplicate telemetry. Here is the code that you can put in the application which can likely fix this.

```
@Bean
    public TelemetryProcessor duplicateHttpTelemetryFilter() {
        return (telemetry) -> {
            if (telemetry instanceof RemoteDependencyTelemetry) {
                String type = ((RemoteDependencyTelemetry) telemetry).getDependencyKind().toString();
                return !type.equals("HTTP");
            }
            return true;
        };
    }
'''

The ApplicationInsights SpringBoot Starter will then autowire this telemetry processor and filter this duplicate telemetry.

In the long term in subsequent releases, we will either remove rest template instrumentation as we already instrument Apache HTTP Client, or have a working version where headers are properly propagated.

**Comment by dslack** [comment]
@dhaval24 
Great!  That's much simpler than modifying the source code and compiling to a local jar (I had just commented out the HTTP Telemetry call entirely...)

Thanks for the quick response!

**Comment by dhaval24** [comment]
@dslack let me know if this modification works.

**Comment by dhaval24** [comment]
@dslack a short change in the work around I provided above. It uses a deprecated API. Please use following:

```
@Bean
    public TelemetryProcessor duplicateHttpTelemetryFilter() {
        return (telemetry) -> {
            if (telemetry instanceof RemoteDependencyTelemetry) {
                String type = ((RemoteDependencyTelemetry) telemetry).getType();
                return !type.equals("HTTP");
            }
            return true;
        };
    }
```
Let me know if this works.

**Comment by dslack** [comment]
@dhaval24 Just an update, using the TelemetryProcessor works to remove the duplicates, thanks for the code sample and help!

**Comment by littleaj** [comment]
Fixed
