### ISSUE TITLE
Structured instrumentation key does not work

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/ApplicationInsights-Java#819]
### Expected behavior
I should be able to send telemetry using structured instrumentation keys (with 3-letter prefix)

### Actual behavior
Telemetry is not reaching Application Insights

### To Reproduce
Run the app listed below

#### Sample Application
```Java
TelemetryClient client = new TelemetryClient();
client.getContext().setInstrumentationKey("EAP-cee555b9-ab6f-45b1-8752-805bd821442e");
System.out.println("Tracing foo...");
 client.trackTrace("foo-java");
client.flush();
System.out.println("Press Enter to exit");
try { System.in.read(); } catch (java.io.IOException ignored){}
```

### System information
Please provide the following information:
 - SDK Version: applicationinsights-core package version 2.3.1
 - OS type and version: Windows 10
 - Application Server type and version (if applicable): n/a
 - Using spring-boot? no
 - Additional relevant libraries (with version, if applicable): none

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

AI: INFO 27-02-2019 22:55:59.298+0000, 1(main): 'MaxTelemetryBufferCapacity': null value is replaced with '500'
AI: INFO 27-02-2019 22:55:59.303+0000, 1(main): 'FlushIntervalInSeconds': null value is replaced with '5'
AI: TRACE 27-02-2019 22:55:59.329+0000, 1(main): Using Http Client version 4.3+
AI: INFO 27-02-2019 22:55:59.342+0000, 1(main): 'Channel.MaxTransmissionStorageCapacityInMB': null value is replaced with '10'
AI: TRACE 27-02-2019 22:55:59.385+0000, 1(main): Default performance counters will be automatically loaded.
AI: TRACE 27-02-2019 22:55:59.424+0000, 1(main): C:\Users\karolz\AppData\Local\Temp\AISDK\native\2.3.1 folder exists
AI: TRACE 27-02-2019 22:55:59.432+0000, 1(main): Successfully extracted 'applicationinsights-core-native-win64.dll' to local folder
AI: TRACE 27-02-2019 22:56:15.074+0000, 1(main): Java process name is set to 'java#5'
AI: TRACE 27-02-2019 22:56:15.074+0000, 1(main): Successfully loaded library 'applicationinsights-core-native-win64.dll'
AI: TRACE 27-02-2019 22:56:15.076+0000, 1(main): Initializing QuickPulse...
AI: INFO 27-02-2019 22:56:24.276+0000, 1(main): heartbeat is enabled
AI: TRACE 27-02-2019 22:56:24.277+0000, 16(HeartBeatProvider_propertyUpdateService-0): added heartbeat property
osVersion - Windows 10
AI: TRACE 27-02-2019 22:56:24.278+0000, 16(HeartBeatProvider_propertyUpdateService-0): added heartbeat property
sdkVersion - java:2.3.1
AI: TRACE 27-02-2019 22:56:24.278+0000, 16(HeartBeatProvider_propertyUpdateService-0): added heartbeat property
processSessionId - 1a327017-dbe0-4696-84eb-19dce7734d40
AI: TRACE 27-02-2019 22:56:24.278+0000, 16(HeartBeatProvider_propertyUpdateService-0): added heartbeat property
jreVersion - 1.8.0_201
AI: TRACE 27-02-2019 22:56:24.281+0000, 1(main): Registering PC 'DeadLockDetector'
AI: TRACE 27-02-2019 22:56:24.281+0000, 1(main): Registering PC 'JvmHeapMemoryUsedPerformanceCounter'
AI: TRACE 27-02-2019 22:56:24.291+0000, 1(main): Registering PC 'JSDK_ProcessMemoryPerformanceCounter'
AI: TRACE 27-02-2019 22:56:24.292+0000, 1(main): Registering PC 'JSDK_ProcessCpuPerformanceCounter'
AI: TRACE 27-02-2019 22:56:24.292+0000, 1(main): Registering PC 'JSDK_WindowsPerformanceCounterAsPC'
Tracing foo...
Press Enter to exit
AI: TRACE 27-02-2019 22:56:51.612+0000, 22(ActiveTransmissionNetworkOutput_1-0): Http response code 400 not handled by com.microsoft.applicationinsights.internal.channel.common.ErrorHandler
AI: TRACE 27-02-2019 22:56:51.612+0000, 22(ActiveTransmissionNetworkOutput_1-0): Http response code 400 not handled by com.microsoft.applicationinsights.internal.channel.common.PartialSuccessHandler
AI: TRACE 27-02-2019 22:56:51.613+0000, 22(ActiveTransmissionNetworkOutput_1-0): Http response code 400 not handled by com.microsoft.applicationinsights.internal.channel.common.ThrottlingHandler.

**Comment by littleaj** [comment]
@AlexKlimovMS can you provide any insights on this?

**Comment by AlexKlimovMS** [comment]
Some Application Insights ikey have special 3 letter prefixes. We should contact ingestion team for the full list of possible prefixes.

**Comment by trask** [comment]
Closing since this was reported by internal dev team, and haven't had any customer requests for this.
