### ISSUE TITLE
Address Security Vulnerability applicationinsights-core

### ISSUE THREAD

**Issue by bgsenthil** [Microsoft/ApplicationInsights-Java#822]
There is a security vulnerability in applicationinsights-core-2.3.1.jar i.e. on Socks5ProxyHandler.java

CWE-259: Use of Hard-coded Password

Description:
Attack Vector: AUTH_PASSWORD initializer

Number of Modules Affected: 11

Description: This variable assignment uses a hard-coded password that may compromise system security in a way that cannot be easily remedied. The use of a hard-coded password significantly increases the possibility that the account being protected will be compromised. Moreover, the password cannot be changed without patching the software. If a hard-coded password is compromised in a commercial product, all deployed instances may be vulnerable to attack. In some cases, this finding may indicate a reference to a password (e.g. the name of a key in a properties file) rather than an actual password. AUTH_PASSWORD initializer

Remediation: Store passwords out-of-band from the application code. Follow best practices for protecting credentials stored in locations such as configuration or properties files. An HSM may be appropriate for particularly sensitive credentials.

**Comment by dhaval24** [comment]
closing as duplicate of #823
