### ISSUE TITLE
Numerous CWE weaknesses after upgrading to 2.3.1

### ISSUE THREAD

**Issue by bgsenthil** [microsoft/ApplicationInsights-Java#823]
![image](https://user-images.githubusercontent.com/24399107/53655367-9b5c2d80-3c15-11e9-94e6-9ae24394b5bb.png)

**Comment by dhaval24** [comment]
@bgsenthil could you please provide the tools you used to scan this vulnerabilities? We will try to address them in next releases.

**Comment by bgsenthil** [comment]
> @bgsenthil could you please provide the tools you used to scan this vulnerabilities? We will try to address them in next releases.

@dhaval24 ,  I used Veracode to scan our application and these got flagged.  Hope this helps.

**Comment by dhaval24** [comment]
@bgsenthil thanks. We will try to address the ones which are applicable to the library in future releases.

**Comment by littleaj** [comment]
We've addressed these.
