### ISSUE TITLE
Modularize LocalForwarder Telemetry Channel into separate subproject 

### ISSUE THREAD

**Issue by dhaval24** [microsoft/ApplicationInsights-Java#824]
**Is your feature request related to a problem? Please describe.**
LocalForwarder Telemetry Channel Introduces too many dependencies like gRPC, protobuff, netty etc. which are not required by ApplicationInsights-core and web packages in general use. 

**Describe the solution you would like**
Modularize Local Forwarder Telemetry Channel Into  separate gradle subproject and release separate maven binary.

cc: @littleaj @reyang

**Comment by trask** [comment]
Closing as LocalForwarder has been deprecated
