### ISSUE TITLE
Question: AI-Agent.xml MaxStatementQueryLimitInMS 

### ISSUE THREAD

**Issue by AlexIvan2** [Microsoft/ApplicationInsights-Java#837]
Hello,

Could you please help me to understand what this parameter is meant for? MaxStatementQueryLimitInMS = 7000
My assumption was that I can skip all SQL queries which execution time is less than 7 seconds. I still can see queries with 7ms-8ms execution time.

Thank you in advance!
Best Regards.

### System information
Please provide the following information:
 - SDK Version: 2.3.1
 - OS type and version: 
 - Application Server type and version (if applicable):
 - Using spring-boot? No
 - Additional relevant libraries (with version, if applicable):

**Comment by dhaval24** [comment]
@littleaj would you be able to take on this one if possible?

**Comment by AlexIvan2** [comment]
Hello,
I'm sorry. I forgot to mention that we are using Oracle DB. If this parameter is working only for MySQL and PostgreSQL (as mentioned in description), there is some other way how could we "cut" queries with good performance?
Thank you in advance.
BR.

**Comment by dhaval24** [comment]
@AlexIvan2 would you be able to explain better what you are trying to achieve? I am a bit lost in the question. I might be able to better help once I have clear understanding of your problem :)

**Comment by AlexIvan2** [comment]
Hello,
@dhaval24 sorry for confusing. I'm trying to reduce the noise we receive from Application to Azure AI regarding Dependencies calls. For instance, if I have a lot of Dependency calls toward Oracle DB and most of them are faster than 10ms. How can I prevent them from being sent to Application Insights?

**Comment by dhaval24** [comment]
Hi Alex,

No worries. That is simple you can write your own `TelemetryProcessor` to filter our the faster oracle db calls. Since you are not using SpringBoot, you can follow this doc on how to write basic filter.

**Comment by AlexIvan2** [comment]
Hi,

Thanks a lot for help. The filter is working just fine now. I just wonder if I can monitor dependency telemetry by Operation Id? For instance, if I have 3 queries with one Operation Id and I want to send them to application insights if total duration is greater than 10. I see that `RemoteDependencyTelmetry` has `getId()` method, but I'm not sure if this is the same Id which I see in Azure Log analytic by Operation Id.

Best Regards.

**Comment by dhaval24** [comment]
Hi @AlexIvan2 I don't think that is possible. SDK follows a preprocessing pipeline for each telemtry item, before it is sent. 
https://github.com/Microsoft/ApplicationInsights-Java/blob/a1e7d2b2b638b91e7ef26428bd9adcef8e4c61eb/core/src/main/java/com/microsoft/applicationinsights/TelemetryClient.java#L388
Therefore, it is easy to modify each individual telemetry item before sending it to end point, however doing operation on group of Telemetry items is not possible.

**Comment by AlexIvan2** [comment]
Hello @dhaval24, Thank you very much for your assistance!

**Comment by dhaval24** [comment]
No problem @AlexIvan2 . Glad it worked out. Will be closing this issue, please reopen other issues if you find problems.
