### ISSUE TITLE
Download URL changed in 2.3.1

### ISSUE THREAD

**Issue by timja** [Microsoft/ApplicationInsights-Java#838]
Hi

The URL format for downloading the agent changed between 2.3.0 and 2.3.1

https://github.com/Microsoft/ApplicationInsights-Java/releases/download/v2.3.1/applicationinsights-agent-2.3.1.jar

https://github.com/Microsoft/ApplicationInsights-Java/releases/download/2.3.0/applicationinsights-agent-2.3.0.jar

there's a `v` prepended to the version number in 2.3.1

We're trying to setup an automated fetch of the agent in a docker image, and allowing users the flexibility to choose the version they use

Was the change intentional and will it be consistent going forward?
i.e. is the tagging automated to a naming convention?

**Comment by dhaval24** [comment]
@timja great catch. Probably, I think that was unintentional error on our side :( However, looking at past releases I do see some inconsistency. 

@littleaj we should definitely standardize on how we version our sdk's. My opinion would be to go without a prefix "v"!

**Comment by littleaj** [comment]
fixed
