### ISSUE TITLE
How to filter Request telemetry by URL from being sent

### ISSUE THREAD

**Issue by arahlf** [Microsoft/ApplicationInsights-Java#839]
There is [documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-filter-telemetry#request-telemetry-filter) about how to configure a Request Telemetry Filter that can be used to filter out URLs that you don't necessarily care to have reported to AI. In my case, I'm trying to filter out the /actuator/health endpoint.

I looked at the source for the RequestTelemetryFilter class, and it doesn't seem to have any functionality anymore around filtering out URLs.

Is there still a documented or recommended way of filtering out certain request telemetry (URL paths specifically) from being sent to AI?

**Comment by dhaval24** [comment]
@arahlf your code example is pretty correct. However I generally recommend to annotate this as a `@Bean`
and then ApplicationInsightsSpringBoot Starter will autowire this telemetry processor.

**Comment by dhaval24** [comment]
If your question is answered please do feel free to close the issue.

**Comment by arahlf** [comment]
Thanks for the reply. It still autowires fine as a `@Component` like I have it, but I agree it may be more appropriate to declare as a bean instead.
