### ISSUE TITLE
Support Instrumentation of latest version of MySQL JDBC Driver - v8 (Namespaces changed since v6)

### ISSUE THREAD

**Issue by rabbboudi** [microsoft/ApplicationInsights-Java#857]
I have followed the instructions here https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-agent to install the app insights agent on my linux machine.

My application is calling a remote MySQL DB (using com.mysql.cj.jdbc.Driver). app core, app web and the agent have the same version 2.3.1.

Am I missing additional configuration ?
Thank you

### Expected behavior
The dependecy data should be automatically collected and should appear on the application insights application map

### Actual behavior
No dependency data is collected. Other application insights data are correctly collected (instrumented with trackevent, tracktrace ...)

### To Reproduce
You can find in attachment screenshot of the AI-Agent.xml file and the part of catalina.sh file that I modified.

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: 
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
 - OS type and version:
Ubuntu 16.04
 - Application Server type and version (if applicable):
Using CATALINA_BASE:   /opt/apache-tomcat-9.0.16
Using CATALINA_HOME:   /opt/apache-tomcat-9.0.16
Using CATALINA_TMPDIR: /opt/apache-tomcat-9.0.16/temp
Using JRE_HOME:        /usr/lib/jvm/java-8-openjdk-amd64/jre
Using CLASSPATH:       /opt/apache-tomcat-9.0.16/bin/bootstrap.jar:/opt/apache-tomcat-9.0.16/bin/tomcat-juli.jar
Server version: Apache Tomcat/9.0.16
Server number:  9.0.16.0
OS Name:        Linux
OS Version:     4.15.0-1040-azure
Architecture:   amd64
JVM Version:    1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12
JVM Vendor:     Oracle Corporation
 - Using spring-boot? no

### Logs
SEVERE [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [XXXXXXXXXXX] created a ThreadLocal with key of type [com.microsoft.applicationinsights.internal.channel.common.SenderThreadsBackOffManager] (value [com.microsoft.applicationinsigh s.internal.channel.common.SenderThreadsBackOffManager@40257f59]) and a value of type [com.microsoft.applicationinsights.internal.channel.common.SenderThreadLocalBackOffData] (value [com.microsoft.applicationinsights.internal.channel.common.SenderThreadLocalBackOffData@5cc4d4e2]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

### Screenshots
![AI-Agent_XML](https://user-images.githubusercontent.com/48597969/54446710-df881b80-4747-11e9-8344-adc466459826.JPG)
![file_catalina_sh](https://user-images.githubusercontent.com/48597969/54446907-5a513680-4748-11e9-821b-0e0ccd10c775.jpg)

**Comment by dhaval24** [comment]
@rabbboudi could you please turn on the AgentLogs and let us know. I would like to understand if agent is getting picked up in the first place.

**Comment by rabbboudi** [comment]
@dhaval24 : Thank you for your quick response. How can I turn them on ? There is only one application running.

**Comment by dhaval24** [comment]
@rabbboudi here is the documentation to configure AgentLogger. https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-troubleshoot#java-agent

Which version of MySql JDBC driver you are using?

**Comment by rabbboudi** [comment]
@dhaval24 Here is the connector I am using : mysql-connector-java-8.0.14.jar
I have enabled the AgentLogs and run a few tests.
Here are the traces:
ERROR 17-03-2019 10:24:34.690+0000, 1(main): cannot parse the correlation format, will defaultto AI proprietory correlation
ERROR 17-03-2019 10:24:34.710+0000, 1(main): cannot parse the correlation format, will defaultto AI proprietory correlation
TRACE 17-03-2019 10:24:34.712+0000, 1(main): Outbound W3C tracing is enabled : false
TRACE 17-03-2019 10:24:34.713+0000, 1(main): Outbound W3C backport mode is enabled : true
TRACE 17-03-2019 10:24:34.714+0000, 1(main): Adding built-in instrumentation
TRACE 17-03-2019 10:24:34.714+0000, 1(main): Adding built-in JDBC Statements instrumentation
TRACE 17-03-2019 10:24:34.716+0000, 1(main): Adding built-in JDBC Prepared Statements instrumentation
TRACE 17-03-2019 10:24:34.719+0000, 1(main): Adding built-in HTTP instrumentation
TRACE 17-03-2019 10:24:34.721+0000, 1(main): Adding built-in Jedis instrumentation
TRACE 17-03-2019 10:24:34.721+0000, 1(main): Adding 'org/mule/module/client/MuleClient'
INFO 17-03-2019 10:24:35.320+0000, 1(main): Successfully registered Jmx connector.
TRACE 17-03-2019 10:24:35.321+0000, 1(main): Agent is up

Thank you !

**Comment by dhaval24** [comment]
@rabbboudi thanks for the update. We will investigate this issue. It seems that there might be some changes in instrumentation that needs to be done with introduction of JDBC Type 4.0 driver for MySql.

**Comment by rabbboudi** [comment]
@dhaval24 : Thank you for the update. Can you please tell me which version of the driver I have to use to make it work ?

**Comment by rabbboudi** [comment]
@dhaval24 : Tested other drivers. It works fine with mysql-connector-java-5.1.36 but not mysql-connector-java-6.0.6.

**Comment by travisnielsen** [comment]
Confirmed the same issue with Java Spring Boot Starter, which does not work with 6.0.6.

**Comment by dhaval24** [comment]
@rabbboudi @travisnielsen makes sense. The instrumentation in the agent is for Class.forName("com.mysql.jdbc.Driver"). The agent has missing instrumentation for 
com.mysql.cj.jdbc.Driver. Clearly it seems that since MySQL Connector 6 the Driver class is refactored into another namespace called cj.

https://github.com/Microsoft/ApplicationInsights-Java/blob/658347843c177c86b464fe3f131a2fb0abddb991/agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/StatementClassDataDataProvider.java#L43

https://github.com/Microsoft/ApplicationInsights-Java/blob/00f384fa4781f39b52ed300b4fd8c2fa23968e1e/agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/sql/PreparedStatementClassDataProvider.java#L65

The above classes should have the instrumentation for new version of MySQL Drivers.

**Comment by littleaj** [comment]
2.5.0 has this feature
