### ISSUE TITLE
Clean up Try-Catch Block (Remove ThreadDeath Catch Statements)

### ISSUE THREAD

**Issue by dhaval24** [Microsoft/ApplicationInsights-Java#858]
Since Java 7, the calls to Thread.stop() has been deprecated. ThreadDeath is only thrown when `Thread.stop()` class is invoked. It would be good to clean up the code base and remove this unneeded catch statement.  On quick scanning of code base I do not see any reference to `Thread.stop()`.

From the java docs - "An instance of ThreadDeath is thrown in the victim thread when the (deprecated) Thread.stop() method is invoked."

Here are the related links:

https://docs.oracle.com/javase/7/docs/api/java/lang/ThreadDeath.html
https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#stop()

**Comment by littleaj** [comment]
It is deprecated and should not be used, but as long as the method exists and we continue to catch `Throwable`, we have to propagate this exception. It still exists in Java 8/9/10/11: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Thread.html#stop()

Propagating `ThreadDeath` from all instances of `catch (Throwable)` is a safeguard to prevent any possible propagation from dependencies libraries and user code.

**Comment by dhaval24** [comment]
> Propagating `ThreadDeath` from all instances of `catch (Throwable)` is a safeguard to prevent any possible propagation from dependencies libraries and user code.

This makes sense @littleaj.AI-Java SDK code base doesn't use Thread.stop() anywhere but it can be likely that one of the dependency might still be using it. We can continue to catch this for now. 

Will close this issue.
