### ISSUE TITLE
Use Try-With-Resources to close the closeable resources.

### ISSUE THREAD

**Issue by dhaval24** [microsoft/ApplicationInsights-Java#859]
Use Try-With Resources to close the closeable resources. Eg HTTP Client, FileStream, Database calls

This is the best practice since Java 7 and avoids errors like leaking streams when using Try-catch-finally and is much more clean. 

https://dzone.com/articles/java-code-bytes-be-resourceful-with-try-with-resou

**Comment by thiyagu-7** [comment]
I would like to work on this

**Comment by dhaval24** [comment]
@thiyagu-7 please feel free to fork the repository and send a PR :)

**Comment by thiyagu-7** [comment]
Yes. Thanks.
I'll go through the repo to find the places where I have to replace _try..catch..finally_ with Try-With Resource block first (if you already don't have the list already)

**Comment by dhaval24** [comment]
@thiyagu-7 go ahead :)

**Comment by thiyagu-7** [comment]
@dhaval24 I'm just starting on this.

Transforming old *try..catch..finally* to *try-with-resources* style means we no longer close the resources which means we cannot catch the exceptions from the close method. 
1) This means that the existing log messages (and calls to logPerfCounterErrorError) in the finally block can no longer be supported.

2) Also, if the close throws an exception and if the try-with-resource has a catch block, then the exception will go into the catch block. This cannot differentiate between exception from try block body and exceptions when closing the resoruce. So, the log might be misleading.

Example:
https://github.com/Microsoft/ApplicationInsights-Java/blob/40809cb6857231e572309a5901e1227305c27c1a/core/src/main/java/com/microsoft/applicationinsights/internal/perfcounter/UnixTotalCpuPerformanceCounter.java#L109

As per my point 1, `logPerfCounterErrorError("Error while closing file : '%s'", e.toString());` cannot be supported. For my point 2, if *close* throws an exception, it will go into the catch block and logs *Error while parsing file* even though the try block body didn't throw an exception.

Thoughts??

**Comment by littleaj** [comment]
non-essential
