### ISSUE TITLE
JedisConnectionException while running smoke tests

### ISSUE THREAD

**Issue by dhaval24** [microsoft/ApplicationInsights-Java#861]
Redis dependency container throws `JedisConnectionException` while running Caching Calculator Smoke Tests.

**Comment by littleaj** [comment]
I figured out why this was happening and was able to get the test working properly with an actual connection to the redis container on my machine. For a reason I have yet to find, the default names (*adjective*_*person's name*) do not seem to be registered with the docker DNS, but if the `--name` option is specified during `docker run`, the custom name is found in DNS and things work as expected.

I'll provide an update an close this issue.

**Comment by dhaval24** [comment]
Awesome! Thanks @littleaj

**Comment by littleaj** [comment]
fixed
