### ISSUE TITLE
Update CONTRIBUTING.md build instructions

### ISSUE THREAD

**Issue by littleaj** [microsoft/ApplicationInsights-Java#868]
The contributing guide is very minimal. There should be more information on how to get started building and contributing to ApplicationInsights-Java. Let's use this issue to discuss what we'd like to see there.

https://github.com/Microsoft/ApplicationInsights-Java/blob/master/.github/CONTRIBUTING.md

**Comment by cijothomas** [comment]
We have some guides for .NET SDK repos. You can refer it and offer any suggestions .
https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/.github/CONTRIBUTING.md
https://github.com/Microsoft/ApplicationInsights-aspnetcore
https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/CONTRIBUTING.md

**Comment by littleaj** [comment]
Some bugs in the current doc:

To be more clear, [this section](https://github.com/Microsoft/ApplicationInsights-Java/blob/master/.github/CONTRIBUTING.md#getting-started) should add dot slash to the build command `./gradlew build`

[This section](https://github.com/Microsoft/ApplicationInsights-Java/blob/master/.github/CONTRIBUTING.md#using-eclipse-ide) should use `./gradlew` and specify which version we support. I'm not entirely sure you need to install gradle for this to work. Some investigation here is needed. In IntelliJ (another section we should add), you can configure it to use the provided wrapper, `gradlew`.

Things I see missing:
Even though you can find this information in the gradle documentation, we should explain a few basic tasks (build targets) to use in development, e.g. `build`==`assemble check`, `check` runs the "checks" (tests), `clean`, `assemble` if you don't want tests to run, etc.

Link to `smokeTest` documentation

**Comment by dhaval24** [comment]
Currently, the build isn't very friendly on non windows devices. Especially Mac OS. I had to hack around to disable native portion from building, but still constantly saw some tests fail.

**Comment by dhaval24** [comment]
I would also suggest that this guide should be in root directory. Currently it is in .github folder which makes it very hard to be discovered.

**Comment by lmolkova** [comment]
also document WIN_SDK_LIB_PATH

**Comment by littleaj** [comment]
`WIN_SDK_LIB_PATH` was removed in favor of `APPINSIGHTS_WIN_SDK_PATH` and `APPINSIGHTS_VS_PATH`.

#918
https://github.com/microsoft/ApplicationInsights-Java/pull/918/commits/a96b53570a47c5db48336be2dcfe866dfad735c3
