### ISSUE TITLE
Option to conceal SQL connection detail

### ISSUE THREAD

**Issue by ElliotZhang** [microsoft/ApplicationInsights-Java#869]
**Problem**
In some business cases App Insight users might not want to disclose the SQL connection details. However, as per current App Insight agent implementation the SQL dependency uses the whole SQL connection string as name.
We currently using a workaround of TelemetryInitializer to manually setting the name the SQL dependency telemetry, but it would be nice if App Insight support this out of box.

**Desired Solution**
App Insight provides settings in AI-Agent.xml to disable/enable SQL connection string as name. And also ability to select exactly which connection to conceal is preferred.

**Comment by littleaj** [comment]
A very good point. We will investigate alternatives.

**Comment by dhaval24** [comment]
@ElliotZhang fair point. Please feel free to contribute if you would like to. We welcome all contributions :)

**Comment by trask** [comment]
Addressed in 3.0 Preview (it now parses and captures only specific parts of the connection string)
