### ISSUE TITLE
Align AI SDK Diagnostic logging levels to standard java logging levels

### ISSUE THREAD

**Issue by reyang** [microsoft/ApplicationInsights-Java#873]
**Here goes the original words from the customer**

This is a requested feature and i am hoping for some feedback as I am not at all familiar with Java. Thanks

 
add support for standard log levels in Java (https://en.wikipedia.org/wiki/Java_logging_framework). Most of the time we leverage SLF4J and / or Logback libraries and these tie nicely into Application Insights. Unfortunately App insights isn’t supporting the log methods of the provided frameworks. 

When you start the framework using DEBUG as the log level App Insights throws an exception with the following:

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'azure.application-insights.logger.level' to com.microsoft.applicationinsights.internal.logger.InternalLogger$LoggingLevel:

    Property: azure.application-insights.logger.level
    Value: ${integrator_report_logger_level}
    Origin: class path resource [application.properties]:34:41
    Reason: failed to convert java.lang.String to com.microsoft.applicationinsights.internal.logger.InternalLogger$LoggingLevel

Action:

Update your application's configuration. The following values are valid:

    ALL
    ERROR
    INFO
    OFF
    TRACE
    WARN

We are using this in our project:

<dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>applicationinsights-spring-boot-starter</artifactId>
            <version>1.1.1</version>
        </dependency>

**Comment by dhaval24** [comment]
This is because when SpringBoot autoconfig mechanism calls: https://github.com/Microsoft/ApplicationInsights-Java/blob/230ed8807bf3e8aa62093df0b426b7a9f704231e/azure-application-insights-spring-boot-starter/src/main/java/com/microsoft/applicationinsights/autoconfigure/ApplicationInsightsProperties.java#L517 
It tries to find a matching level in the `LoggingLevel.java` class. When a different logging level is used which is not present in the above mentioned class, spring autoconfig throws an exception. 
The best solution in this case may be to align to common logging levels. 

Springboot autoconfig throws by default when there is a config mismatch like above.

**Comment by dhaval24** [comment]
@reyang I renamed this issue to a better title and assigned an enhancement tag to it.

**Comment by littleaj** [comment]
@reyang @dhaval24 `DEBUG` is a common log level setting in other logging frameworks. I actually did this when I first used the SDK. I don't think there's a standard for us to adopt. I've see some other frameworks that use use `FINE`, `FINER`, `FINEST`.

To resolve this bug, the SDK should not throw if the log level is incorrect. It should have a default. `INFO` is a good default, IMO.

**Comment by littleaj** [comment]
I see now that it was SpringBoot which attempted the parsing. I say we change this: https://github.com/Microsoft/ApplicationInsights-Java/blob/230ed8807bf3e8aa62093df0b426b7a9f704231e/azure-application-insights-spring-boot-starter/src/main/java/com/microsoft/applicationinsights/autoconfigure/ApplicationInsightsProperties.java#L463 to be a `String` and parse it ourselves.

**Comment by dhaval24** [comment]
I agree if there is a way to prevent throwing then we should.
