### ISSUE TITLE
How and what to configure for logback logging in Netty server

### ISSUE THREAD

**Issue by marceloverdijk** [Microsoft/ApplicationInsights-Java#878]
@dhaval24 this is the follow up from https://github.com/Microsoft/ApplicationInsights-Java/issues/790

I ended up on https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-trace-logs to configure Java logging using Application Insights.

The page mentions to include the `com.microsoft.azure:applicationinsights-logging-logback` dependency and add the appender to `logback.xml`.

The page _also_ mentions to "Follow the instructions to install Application Insights SDK for Java, if you haven't already done that." >> https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-get-started

That Java getting started page states many steps to setup including the `com.microsoft.azure:applicationinsights-web` dep, `ApplicationInsights.xml` and setting up the Http filter.

Setting up the HTTP filter is not possible for Netty as it depends on the `javax.servlet.*` api.
As @dhaval24 mentioned in the other issue the HTTP filter is not needed for logback integration.

But is the `com.microsoft.azure:applicationinsights-web` dep than needed?
And all the `com.microsoft.applicationinsights.web.*` modules and initialisers in `ApplicationInsights.xml`.
Or would it be possible to omit that dep and xml file and simply provide the application insights key via ` -DAPPLICATION_INSIGHTS_IKEY=your_ikey`?

**Comment by dhaval24** [comment]
@marceloverdijk in order to use `applicationinsights-logging-logback` appender and send logs to azure monitor, you do not need to have `applicationinsights-web` dependency. 
You can set instrumentation key using  environment variable `APPLICATION_INSIGHTS_IKEY=your-ikey`.

**Comment by marceloverdijk** [comment]
Thx a lot for the feedback!
