### ISSUE TITLE
Creating ChildTraceParent retuns 'null' when running in Kubernetes

### ISSUE THREAD

**Issue by travisnielsen** [Microsoft/ApplicationInsights-Java#879]
### Expected behavior
I'm working with @dhaval24 on an approach to set correlation between message queue consumers / producers as discussed in issue #764. My approach is based on [this sample application](https://github.com/dhaval24/OrderManagement).

Telemetry correlation works 100% locally on my laptop and also locally when running in Docker. My expectation is this would work the same in Kubernetes.

### Actual behavior
The call for `TraceContextCorrelation.generateChildDependencyTraceparent()` returns `null` when running in Kubernetes. 

### To Reproduce
Deploy workload to AKS (version 1.12.5).

#### Sample Application
[Full source code is here](https://github.com/travisnielsen/appinsights-spring-boot-demo/blob/0566c243e644b4f655b88bc8f01248ad75537b01/user-service/src/main/java/com/usermanagement/domain/UserController.java#L76)

### System information
Please provide the following information:
 - SDK Version: 2.3.1
 - OS type and version: Debian 9
 - Application Server type and version (if applicable): Tomcat
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable): OpenJDK 8

My Kubernetes environment is Azure Kubernetes Service (AKS) version 1.12.5.

### Logs
N/A

### Screenshots
Example of the application running locally in Docker:

![image](https://user-images.githubusercontent.com/3196834/55014363-d81f0880-4fb8-11e9-917c-31bac9100e01.png)

Example of ThreadContext in Kubernetes and the null value returned for `generateChildDependencyTraceparent()`. I handle this null condition in my code.

![image](https://user-images.githubusercontent.com/3196834/55014536-23391b80-4fb9-11e9-85d0-c95b39ac3018.png)

**Comment by dhaval24** [comment]
Thanks @travisnielsen for opening the issue. Let's investigate this further.

**Comment by travisnielsen** [comment]
Whatever is causing this, it appears to be resolved in the current master branch of the SDK.  After building from latest and switching to...

```XML
<dependency>
   <groupId>com.microsoft.azure</groupId>
   <artifactId>applicationinsights-spring-boot-starter</artifactId>
   <version>1.2.0</version>
</dependency>
```
...and subsequent deployment to AKS, I now see the correlation data flowing.

![image](https://user-images.githubusercontent.com/3196834/55168542-02033700-5141-11e9-94e1-ea2106a7a056.png)

**Comment by travisnielsen** [comment]
Just to double-check, I reverted back to the current release SDK and was unable to reproduce this issue. Whatever the issue was it, appears to have been specific to my environment at that specific time. I can no longer reproduce it so I'm closing this issue.
