### ISSUE TITLE
Would it make easier to discover if springboot sample will be moved to https://github.com/Azure-Samples?

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-Java#886]
Subj

**Comment by littleaj** [comment]
@SergeyKanzhelev Maybe. Should it be in both?

**Comment by SergeyKanzhelev** [comment]
just one. I think Samples would be a better place. And it will be clean as it will eliminate any cross dependencies to actual code of SDK like end users use it.

**Comment by dhaval24** [comment]
Would it be better to have more complex and complete example on Azure-Samples? For example this: 
https://github.com/dhaval24/OrderManagement/

**Comment by littleaj** [comment]
@SergeyKanzhelev Sounds good to me.

@dhaval24 I'd say put both there, if possible

**Comment by SergeyKanzhelev** [comment]
let me know if you need help setting those repositories up. Should be quite straightforward. Thank you!
