### ISSUE TITLE
Provide internal SDK versions for auto-collected telemetries

### ISSUE THREAD

**Issue by lmolkova** [microsoft/ApplicationInsights-Java#889]
As discussed offline, for debugging and usage statistics we want to understand more about how telemetry was captured.

Currently, we have the following SDK version that we set: https://github.com/Microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/SDK-VERSIONS.md

Java today report everything under "java:version" SDK version.

I've gone through all places we create `TelemetryClient`, but might have missed something, correct me if I did. I didn't put much thought into SDK prefixes, feel free to chance as needed.

| feature | telemetry it collects | proposed SDK version prefix |  where TelemteryClient is created 
|---------| ------|---------| ---------|  
| collectd |  metrics | cdjava | com.microsoft.applicationinsights.collectd.ApplicationInsightsWriter | 
| Spring boot started | ? | perhaps leave untouched, as it seems to be used by customers and shoudl be java | com.microsoft.applicationinsights.autoconfigure.ApplicationInsightsTelemetryAutoConfiguration | 
| agent | exceptions, dependencies | I wish we could have different names for different instrumented clients like 'jrdd-okhttp' or 'jrdd-apache' | com.microsoft.applicationinsights.internal.agent.CoreAgentNotificationsHandler | 
| heartbeats |heartbeats |  hbjava |  com.microsoft.applicationinsights.internal.heartbeat.HeartBeatProvider | 
| performance counters | perf counters | pcjava | com.microsoft.applicationinsights.internal.perfcounter.PerformanceCounterContainer | 
| log4j1_2 |  traces, exceptions | log4j1_2 | com.microsoft.applicationinsights.internal.common.LogTelemetryClientProxy |
| log4j2 | traces, exceptions | log4j2 |  com.microsoft.applicationinsights.internal.common.LogTelemetryClientProxy | 
| logback |   traces, exceptions | logback | com.microsoft.applicationinsights.internal.common.LogTelemetryClientProxy | 
| web | requests |  jweb | com.microsoft.applicationinsights.web.extensibility.modules.WebRequestTrackingTelemetryModule | 
| micrometer | metrics | java:micrometer ? | https://github.com/micrometer-metrics/micrometer/blob/38e39c965c88a05a1f2f91ef72248aff8607a6d9/implementations/micrometer-registry-azure-monitor/src/main/java/io/micrometer/azuremonitor/AzureMonitorMeterRegistry.java#L49|

**Comment by littleaj** [comment]
Setting different values for the various dependencies may be possible

**Comment by dhaval24** [comment]
@lmolkova we also have Micrometer for automatically collecting metrics and aggregation.It uses "java:micrometer" as the SDK-Version. Here is the link to the code:
https://github.com/micrometer-metrics/micrometer/blob/38e39c965c88a05a1f2f91ef72248aff8607a6d9/implementations/micrometer-registry-azure-monitor/src/main/java/io/micrometer/azuremonitor/AzureMonitorMeterRegistry.java#L49
Would you update the table in this issue and add it as well?

**Comment by SergeyKanzhelev** [comment]
>Would you update the table in this issue and add it as well?

@dhaval24 please send PR to the home repo

**Comment by dhaval24** [comment]
@SergeyKanzhelev there is no special prefix for micrometer metrics telemetry. We just send it with "java:micrometer" where micrometer is the sdk version. It was done in this way because: We are only interested in telemetry coming from Micrometer extension. Whether it was coming from a specific version of micrometer was of little interest (atleast at the time of designing this work). 

With that in mind, when I look at home repo, I do not see any place where I can tag a specific version of the sdk. Please let me know if there is one and I will create a PR.

**Comment by littleaj** [comment]
I removed the "logging" row. That's the common lib for log4j and logback

**Comment by lmolkova** [comment]
@littleaj 

 > I removed the "logging" row. That's the common lib for log4j and logback

logging still constructs telemtery client and tracks telemtery. So we should assign something. I am I missing anything?

**Comment by littleaj** [comment]
@lmolkova it will be covered in the log4j2, log4j1_2 and logback cases. they all use the same classes from the 'logging' project, but it doesn't report anything as a separate entity.

**Comment by lmolkova** [comment]
so the code that reports telemtery there is a dead code that is never executed?

**Comment by littleaj** [comment]
no, it's a dependency of the 3 logger adapter implementations.

**Comment by lmolkova** [comment]
so then we should pass SDK version from the implementation to this common code, right? So it probably just shouldn't create a client and get it from specific implementation.?

**Comment by littleaj** [comment]
oh i see. the no-arg constructor isn't used. it should be removed.
so the adapter implementations will provide their own client with the prefix appropriately set.

**Comment by trask** [comment]
Using attach-focused sdk naming now in 3.0 Preview
