### ISSUE TITLE
Application Insight Java Agent does not work with Java 11

### ISSUE THREAD

**Issue by J4cku** [Microsoft/ApplicationInsights-Java#897]
### Expected behavior
I expected Application Insight Java Agent work fine with Java 11 application

### Actual behavior
Java process exits with 255 exit code running application like:
java -javaagent:applicationinsights-agent.jar -jar my-app.jar
Used openjdk 11.0.2 with spring-boot 2.1.3
Appinsight both 2.4.0-BETA and 2.3.1

### To Reproduce
package spring-boot 2.1.3 app with applicationinsights-spring-boot-starter 1.2.0-BETA
try running it with Java

### System information
Please provide the following information:
 - SDK Version: 2.4.0-BETA, 2.3.1
 - OS type and version: Both linux and windows
 - Using spring-boot? Y

**Comment by dhaval24** [comment]
This is a a known issue and we have this enhancement in our backlog. I would be closing this in favor of common issue:  https://github.com/Microsoft/ApplicationInsights-Java/issues/674 Please upvote there and feel free to contribute to the repo as well if you would like to :)
