### ISSUE TITLE
Apache HTTP Client generates lot of  "http-outgoing-0 << "[read] I/O error: Read timed out"

### ISSUE THREAD

**Issue by SergeyKanzhelev** [microsoft/ApplicationInsights-Java#898]
Using apache logs:

```
 DEBUG wire                           - http-outgoing-11 << "[read] I/O error: Read timed out"
```

You can see it in idea when enable breakpoint on exception:

![image](https://user-images.githubusercontent.com/9950081/55491571-90b4ff80-55ea-11e9-8eeb-3c3164618015.png)

It seems to be caused by this issue:
https://stackoverflow.com/questions/34513826/apache-http-client-prints-read-i-o-error-read-timed-out

**Comment by dhaval24** [comment]
It appears that most of these Timeouts are happening when QuickPulse is turned on. When Quickpulse is disabled either there are no timeouts or there are just one or two. I am investigating more.

**Comment by littleaj** [comment]
#903 was breaking some integration tests; reverting.
