### ISSUE TITLE
TelemetryConfiguration.CreateFromConfiguration()

### ISSUE THREAD

**Issue by piotrzaremba** [microsoft/ApplicationInsights-Java#899]
Can the following method be ported from the .net SDK into the java SDK to allow a user to set the path to the configuration file instead of deferring to ./ApplicationInsights.xml.

**Comment by dhaval24** [comment]
@piotrzaremba regarding this (https://github.com/Microsoft/ApplicationInsights-dotnet/blob/91e9c91fcea979b1eec4e31ba8e0fc683bf86802/src/Microsoft.ApplicationInsights/Extensibility/TelemetryConfiguration.cs#L291) 

Today we already have three ways to initialize the configuration object:
1. via XML 
2. via Springboot Autoconfiguration. 
3. `new TelemetryConfiguration()`

I really do not want to add the 4th way which. It piles up to a lot of confusion for the end consumer of the SDK. Most of the java projects have a convenient place to put ApplicationInsights.xml (in traditional java EE apps) and Application.properties in Springboot apps.  Usually resources folder of the project is the place where you put this configuration file. 

Would you please explain me your use case for this method and what is blocking from referring to xml assuming your application is Java EE based?

**Comment by dhaval24** [comment]
@reyang @littleaj what's your take on this?

**Comment by piotrzaremba** [comment]
@dhaval24 so I know how to do this in the .net version which has the method I mentioned but how do I do it in the java version where the xml file resides in some folder structure e.g. /app/ai/myconfigs/ApplicationInisghts.xml

**Comment by trask** [comment]
Hi @piotrzaremba, you can set the config directory via system property `applicationinsights.configurationDirectory` (code is in [ConfigurationFileLocator.java](https://github.com/microsoft/ApplicationInsights-Java/blob/2.5.0-BETA.2/core/src/main/java/com/microsoft/applicationinsights/internal/config/ConfigurationFileLocator.java#L49)). Let us know if this addresses what you need. Thanks.
