### ISSUE TITLE
RemoteDependencyTelemetry causes com.sun.jdi.InvocationException.

### ISSUE THREAD

**Issue by piotrzaremba** [microsoft/ApplicationInsights-Java#900]
SDK Version: 2.3.1

Configuration:

TelemetryConfiguration.getActive().getChannel().setDeveloperMode(developerMode);
TelemetryConfiguration.getActive().setInstrumentationKey(applicationInsightsKey);
TelemetryClient telemetryClient = new TelemetryClient();
QuickPulse.INSTANCE.initialize();

Issue:

RemoteDependencyTelemetry telemetry = new RemoteDependencyTelemetry();

Causes:

com.sun.jdi.InvocationException occurred invoking method in Eclipse debugger.

Subsequent issues not sure if this is the root cause but at times in the Java SDK dependency telemetry is not logged to Application Insights it is very intermittent.

**Comment by piotrzaremba** [comment]
SDK Version: 2.3.1

**Comment by dhaval24** [comment]
@piotrzaremba I haven't seen this issue myself. It would be great if you can give a small repro of the same.

**Comment by trask** [comment]
I suspect this is fixed in 2.5.0-BETA.2 by #978
