### ISSUE TITLE
Support for Jersey projects

### ISSUE THREAD

**Issue by vincpa** [microsoft/ApplicationInsights-Java#902]
**Is your feature request related to a problem? Please describe.**
I am unable to instrument my Java application with Application Insights using the existing documentation on the Microsoft Docs website.

**Describe the solution you would like**

An article or instructions on adding AI to a Java Jersey application

**Describe alternatives you have considered**

None at this stage.

**Additional context**

Jersey can be found here https://jersey.github.io/index.html

**Comment by katafractari** [comment]
+1

**Comment by trask** [comment]
This should work now without additional configuration in [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent)
