### ISSUE TITLE
JDBC Telemetry on explain plan is filter on uppercase "SELECT" only

### ISSUE THREAD

**Issue by cy33hc** [microsoft/ApplicationInsights-Java#907]
### Expected behavior
JDBC telemetry should filter on query with mixed case "SELECT" cmd

### Actual behavior
Filtering only on uppercase "SELECT"

### To Reproduce
enable jdbc telemetry in AI-Agent.xml. Then create a slow jdbc query with lowercase "select" to activate the explain plan.

#### Sample Application
See the code from application insights.

https://github.com/Microsoft/ApplicationInsights-Java/blob/master/core/src/main/java/com/microsoft/applicationinsights/internal/agent/CoreAgentNotificationsHandler.java

![image](https://user-images.githubusercontent.com/4947747/56055534-8becfb80-5d0e-11e9-92ed-947b69bab754.png)

**Comment by dhaval24** [comment]
@cy33hc thanks for opening this issue! This is a bug and should be fixed!
