### ISSUE TITLE
Support for Java Jersey based applications

### ISSUE THREAD

**Issue by vincpa** [microsoft/ApplicationInsights-Java#911]
I have instrumented a front-end and Node based app on Express JS and now I'd like to instrument my Java based application written in Jersey. Unfortunately, I can't find a single blog post or article on how to do this.

I should also add that I am looking at this from a DevOps perspective and don't have the knowledge to do this in Jersey. I'd like to add a code snippet somewhere and have it instrumented.

My build system is based on Maven.

Any help would be appreciated.

**Comment by SergeyKanzhelev** [comment]
https://docs.microsoft.com/azure/azure-monitor/learn/java-quick-start

**Comment by dhaval24** [comment]
@SergeyKanzhelev thanks for the link. @vincpa you can refer this https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-get-started as generic documentation for instrumenting java web apps. Though this is not specifically for Jersy, it should still give some idea.

**Comment by trask** [comment]
Closing, but please re-open if you are still having this issue. Thanks.
