### ISSUE TITLE
It's not possible to turn on GCPerformanceCounter using <JvmPC name="GC" enabled="true" /> 

### ISSUE THREAD

**Issue by lidkowiak** [microsoft/ApplicationInsights-Java#929]
It's not possible to turn on GCPerformanceCounter with such configuration:

```
 <PerformanceCounters collectionFrequencyInSec="60">
        <UseBuiltIn>true</UseBuiltIn>
        <Jvm enabled="true">
            <JvmPC name="GC" enabled="true" />
        </Jvm>
    </PerformanceCounters>
```

Is it possible to turn it on somehow?

**Comment by littleaj** [comment]
@lidkowiak, the GC performance counters should be on by default. 

On what environment are you using the SDK: OS? App Server? Web Framework (e.g. Servlets, Spring)? SDK Version?

**Comment by lidkowiak** [comment]
OS: Mac
App Server: Wildfly
SDK version: 2.1.2

I haven't found code that even create instance of GCPerformanceCounter.
