### ISSUE TITLE
xss

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [microsoft/ApplicationInsights-Java#930]
### Expected behavior
Describe what you expected to happen.

### Actual behavior
Describe what actually happened that was unexpected.

### To Reproduce
![图片](https://user-images.githubusercontent.com/39950310/57836342-0ff54000-77f3-11e9-9165-1064a8f66097.png)
When the accessed path does not exist, the program directly pastes the path into a string and returns it on the error page. The attacker may construct a malicious url (/xxxx/<script>alert(1)</script>) for xss attack.

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: 
 - OS type and version:
 - Application Server type and version (if applicable):
 - Using spring-boot?
 - Additional relevant libraries (with version, if applicable):

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

**Comment by trask** [comment]
This is test code
