### ISSUE TITLE
How to configure app insights with dropwizard application

### ISSUE THREAD

**Issue by swati-rashmi** [microsoft/ApplicationInsights-Java#931]
Configuring app insights with dropwizard application

**Comment by swati-rashmi** [comment]
@littleaj Is there a way by which this can be done

**Comment by trask** [comment]
Hi @swati-rashmi, this should be easier now with 2.5.0-BETA. Check out https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-get-started-25-beta, and let us know if you have any troubles. Thanks.
