### ISSUE TITLE
Spring boot tracing not work

### ISSUE THREAD

**Issue by a651694192** [microsoft/ApplicationInsights-Java#934]
I just create a project which is exactly same as spring boost demo, just change from gradlew to maven, I just see requests but not dependencies in Azure insight database.

### Expected behavior
As we call a GET /trackDependencyAutomatically to our localhost server and then the handler would call another GET request to google, there should be a dependency record in the dependencies table in azure insight database, but I just get a request record.
And In my understanding, the second call's operationParentID should equal to the first one's operation ID, but its operationParentID  just equal to itself.

#### Sample Application
My pom:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.5.RELEASE</version>
        <relativePath/> 
    </parent>
    <groupId>com.example</groupId>
    <artifactId>server</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>server</name>
    <description>Demo project for Spring Boot</description>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>applicationinsights-spring-boot-starter</artifactId>
            <version>1.1.2</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>

### System information
start command: java -javaagent:.\src\main\resources\applicationinsights-agent-2.4.0-BETA-SNAPSHOT.jar -jar .\target\server-0.0.1-SNAPSHOT.jar
Please provide the following information:
 - SDK Version: starter 1.1.2, agent: 2.4.0-BETA-SNAPSHOT
 - Using spring-boot? yes

**Comment by patternpaul** [comment]
@littleaj This may or may not help. I can confirm that you NEED to use applicationinsights-spring-boot-starter 1.2.0-BETA with agent: 2.4.0-BETA-SNAPSHOT. I can also confirm that using applicationinsights-spring-boot-starter 1.2.0-BETA with agent 2.3.1 or lower wont work. I am confirming this with an application built with Maven.

And by "wont work", I mean custom instrumentation or downstream dependencies won't be sent to AppInsights (running with debug mode shows that no "Sending RDD event for" are even logged).

Here is where it get's fun. Even having the 2.4.0-BETA-SNAPSHOT agent in the same directory as the other agents will cause instrumentation not to be sent. Screenshots below.

Running 1.1.2. Any non 2.4.0 agent in the directory when I boot.
![image](https://user-images.githubusercontent.com/3682501/60384925-283eb880-9a49-11e9-8a13-e041a12fbda7.png)
I run `java -javaagent:./applicationinsights-agent-2.3.1.jar -jar ./target/my-app.jar`
![image](https://user-images.githubusercontent.com/3682501/60384959-8cfa1300-9a49-11e9-8fcf-114bff1fe295.png)
You can see events are being sent. Then I add the 2.4.0-BETA agent into the directory beside the other agents
![image](https://user-images.githubusercontent.com/3682501/60385003-f4b05e00-9a49-11e9-98db-13f6f88c7467.png)

And boot the app up (still using the old agent `java -javaagent:./applicationinsights-agent-2.3.1.jar -jar ./target/my-app.jar`) and none of the events are reported.
![image](https://user-images.githubusercontent.com/3682501/60385007-17427700-9a4a-11e9-9588-053b4650b1d6.png)



Note that I am not adding this information to indicate it's a blocker for me. I now know
- I need to use the 1.2.0-BETA SDK with the 2.4.0-BETA agent. I can't intermix older versions
- I can't have the 2.4.0-BETA agent in the same directory as the older agents.

I figured the extra information might be useful /shrug.

**Comment by trask** [comment]
@patternpaul, thanks for the info. Starting with 2.5.0-BETA, we have sync'd the version numbering between the spring boot starter, SDK and Agent to make this clearer. I'm not sure, but I suspect that the issue you had with agent jars being present in same directory is fixed in 2.5.0-BETA (we have entirely re-written the agent).

@a651694192, are you still having an issue? If so, can you post your `AI-Agent.xml` file? Thanks.
