### ISSUE TITLE
Keep applicationinsights-spring-boot-starter version the same as applicationinsights-core

### ISSUE THREAD

**Issue by GeorgHoffmeyer** [microsoft/ApplicationInsights-Java#937]
currently there is a gap between the actual appinsights version and the version of the spring-boot-starter.
The version of applicationinsight and the starter should be the same, so that there is only one versioning.

**Comment by trask** [comment]
Hi @GeorgHoffmeyer, this is fixed now in 2.5.0-BETA. Thanks.
