### ISSUE TITLE
CoreAgentNotificationsHandler->fetchExplainQuery fails with Oracle driver when long query is detected 

### ISSUE THREAD

**Issue by emorozovs** [microsoft/ApplicationInsights-Java#939]
Hi guys,

Oracle jdbc driver cannot process query with standard SQL syntax EXPLAIN SELECT <query...>. That invoked from CoreAgentNotificationHandler.fetchExplainQuery in condition when query time is more than ImplementationsCoordinator.INSTANCE.getQueryPlanThresholdInMS(). Please resolve the issue by changing the query for OracleDB to EXPLAIN PLAN FOR SELECT <query...>, or by adding feature to disable second query.

version of AI 2.3.1
ojdbc driver - ojdbc7 - 12.1.0.2.0

Stacktrace:
java.sql.SQLSyntaxErrorException:
at oracle.jdbc.driver.T4CTTIoer.processError (T4CTTIoer.java450)
at oracle.jdbc.driver.T4CTTIoer.processError (T4CTTIoer.java399)
at oracle.jdbc.driver.T4C8Oall.processError (T4C8Oall.java1059)
at oracle.jdbc.driver.T4CTTIfun.receive (T4CTTIfun.java522)
at oracle.jdbc.driver.T4CTTIfun.doRPC (T4CTTIfun.java257)
at oracle.jdbc.driver.T4C8Oall.doOALL (T4C8Oall.java587)
at oracle.jdbc.driver.T4CStatement.doOall8 (T4CStatement.java210)
at oracle.jdbc.driver.T4CStatement.doOall8 (T4CStatement.java30)
at oracle.jdbc.driver.T4CStatement.executeForRows (T4CStatement.java931)
at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout (OracleStatement.java1150)
at oracle.jdbc.driver.OracleStatement.executeQuery (OracleStatement.java1309)
at oracle.jdbc.driver.OracleStatementWrapper.executeQuery (OracleStatementWrapper.java422)
at com.microsoft.applicationinsights.internal.agent.CoreAgentNotificationsHandler.fetchExplainQuery (CoreAgentNotificationsHandler.java565)
at com.microsoft.applicationinsights.internal.agent.CoreAgentNotificationsHandler.sendSQLTelemetry (CoreAgentNotificationsHandler.java498)
at com.microsoft.applicationinsights.internal.agent.CoreAgentNotificationsHandler.report (CoreAgentNotificationsHandler.java416)
at com.microsoft.applicationinsights.internal.agent.CoreAgentNotificationsHandler.finalizeMethod (CoreAgentNotificationsHandler.java409)
at com.microsoft.applicationinsights.internal.agent.CoreAgentNotificationsHandler.methodFinished (CoreAgentNotificationsHandler.java237)
at com.microsoft.applicationinsights.agent.internal.coresync.impl.ImplementationsCoordinator.methodFinished (ImplementationsCoordinator.java250)

**Configuration:**
2. Part from POM:
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>applicationinsights-web</artifactId>
    <version>2.3.1</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>applicationinsights-logging-logback</artifactId>
    <version>2.3.1</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>applicationinsights-core</artifactId>
    <version>2.3.1</version>
</dependency>

3. AI Agent
applicationinsights-agent-2.3.1.jar
JAVA_OPTS: -javaagent:<path>/applicationinsights-agent-2.3.1.jar

4. AI-Agent.xml
<?xml version="1.0" encoding="utf-8"?>
<ApplicationInsightsAgent>
    <Instrumentation>

        
        <BuiltIn enabled="true">
            <JDBC enabled="true" thresholdInMS="5000"/>
            <HTTP enabled="true" W3C="true" enableW3CBackCompat="true"/>

            
            <MaxStatementQueryLimitInMS>10000</MaxStatementQueryLimitInMS>
        </BuiltIn>

    </Instrumentation>
</ApplicationInsightsAgent>

5. ApplicationInsights.xml
<?xml version="1.0" encoding="utf-8"?>
<ApplicationInsights xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings" schemaVersion="2014-05-30">

    
    <Channel>
        <FlushIntervalInSeconds>5</FlushIntervalInSeconds>
        <MaxTelemetryBufferCapacity>500</MaxTelemetryBufferCapacity>
    </Channel>

    <PerformanceCounters collectionFrequencyInSec="10">
        
        <UseBuiltIn>false</UseBuiltIn>

        
        
        <Jmx>
            <Add objectName="java.lang:type=Memory" attribute="HeapMemoryUsage.used"
                 displayName="Heap Used" type="composite"/>
            <Add objectName="java.lang:type=Memory" attribute="HeapMemoryUsage.committed"
                 displayName="Heap Commited" type="composite"/>
            <Add objectName="java.lang:type=Memory" attribute="HeapMemoryUsage.max"
                 displayName="Heap Max" type="composite"/>
            <Add objectName="java.lang:type=Memory" attribute="NonHeapMemoryUsage.used"
                 displayName="Non Heap Used" type="composite"/>
            <Add objectName="java.lang:type=Memory" attribute="NonHeapMemoryUsage.committed"
                 displayName="Non Heap Commited" type="composite"/>
            <Add objectName="java.lang:type=Memory" attribute="NonHeapMemoryUsage.max"
                 displayName="Non Heap Max" type="composite"/>

            <Add objectName="java.lang:type=Threading" attribute="ThreadCount" displayName="Thread Count"/>
        </Jmx>
    </PerformanceCounters>

    <QuickPulse enabled="false">
    </QuickPulse>

     
    
    
    
    

    
    <TelemetryModules>
        <Add type="com.microsoft.applicationinsights.web.extensibility.modules.WebRequestTrackingTelemetryModule"/>
        <Add type="com.microsoft.applicationinsights.web.extensibility.modules.WebSessionTrackingTelemetryModule"/>
        <Add type="com.microsoft.applicationinsights.web.extensibility.modules.WebUserTrackingTelemetryModule"/>
    </TelemetryModules>

    <TelemetryInitializers>
        <Add type="com.microsoft.applicationinsights.web.extensibility.initializers.WebOperationIdTelemetryInitializer"/>
        <Add type="com.microsoft.applicationinsights.web.extensibility.initializers.WebOperationNameTelemetryInitializer"/>
        <Add type="com.microsoft.applicationinsights.web.extensibility.initializers.WebSessionTelemetryInitializer"/>
        <Add type="com.microsoft.applicationinsights.web.extensibility.initializers.WebUserTelemetryInitializer"/>
        <Add type="com.microsoft.applicationinsights.web.extensibility.initializers.WebUserAgentTelemetryInitializer"/>
    </TelemetryInitializers>
</ApplicationInsights>

6. Listener com.microsoft.applicationinsights.web.internal.ApplicationInsightsServletContextListener 
and filter com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter are initialized in web.xml

### Screenshots
<img width="736" alt="error" src="https://user-images.githubusercontent.com/9250122/58407556-bbfd1d80-8074-11e9-8dfd-353825bb429d.PNG">

![image](https://user-images.githubusercontent.com/9250122/58407385-5446d280-8074-11e9-9d10-9eb9944e393d.png)

**Comment by maxgolov** [comment]
As a temporary workaround, could you please refer to this example config:
https://github.com/Microsoft/ApplicationInsights-Java/wiki/AI-Agent.xml

and try to change
**<MaxStatementQueryLimitInMS>10000</MaxStatementQueryLimitInMS>**
   to
**<MaxStatementQueryLimitInMS>1000000</MaxStatementQueryLimitInMS>**
That way the exception is going to be avoided on longer-running SQL queries.

The proper fix should be to add **EXPLAIN PLAN FOR SELECT …** in Oracle DB use-case.

**Comment by trask** [comment]
Hi @emorozovs, this should be fixed in 2.5.0-BETA. Thanks.
