### ISSUE TITLE
livemetrics does not pick instrumentation key in code.

### ISSUE THREAD

**Issue by cijothomas** [microsoft/ApplicationInsights-Java#969]
### Expected behavior
Configured ikey in code as per below doc.
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-get-started?toc=%2Fazure%2Fazure-monitor%2Ftoc.json#alternative-ways-to-set-the-instrumentation-key
LiveMetrics and every other telemetry should pick this instrumentationkey.
### Actual behavior
Describe what actually happened that was unexpected.
All expect Livemetrics is picking the instrumentation key.
### To Reproduce
Follow doc above to set ikey in code, NOT in ai.xml.

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: 
 - OS type and version:
 - Application Server type and version (if applicable):
 - Using spring-boot?
 - Additional relevant libraries (with version, if applicable):

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

**Comment by itsforbrijesh** [comment]
we are also facing this issue, support case created.

1. Create Dynamic Java project and add new servlet 
2. Add code TelemetryConfiguration.getActive().setInstrumentationKey(instrumentationKey);
3. Remove Instrumentation key from ApplicationInsights.xml
4. Update web.xml

[files.zip](https://github.com/microsoft/ApplicationInsights-Java/files/3379137/files.zip)

Application Type: Dynamic Web with Servlet (java)
SDK version :2.3.1
OS : Windows 10 laptop
Using Springboot - No
Added all required libraries to enable ApplicationInsights

**Comment by cijothomas** [comment]
@trask please update the doc (Please note that Live Metrics does not support reading instrumentation key from code.) that this is supported from newer version of sdk.

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-get-started this doc i meant

**Comment by trask** [comment]
Thanks @cijothomas, I have created docs PR https://github.com/MicrosoftDocs/azure-docs/pull/35789.
