### ISSUE TITLE
Add possibility for adding operation(parent)id using the application insight logback appender

### ISSUE THREAD

**Issue by gernd** [microsoft/ApplicationInsights-Java#970]
At the moment I see no possibility (correct me if I am wrong) to provide the operation_id or the operation_parentId to the Trace Telemetries that are sent using the logback appender.

It would be helpful (for correlating these traces to the related requests) to provide such a possibility

**Comment by littleaj** [comment]
We added automatic collection for logback using `applicationinsights-agent` (without using appender) in 2.5.0-BETA which also has this feature.

**Comment by gernd** [comment]
Thanks for your reply! This means that are no plans in near future to provide such functionality for the appender lib in case I do not want to use the agent?

**Comment by trask** [comment]
For the near future, we are focusing on the agent and auto-collection.
