### ISSUE TITLE
Can not auto collect http remote dependency for azure blob storage via agent

### ISSUE THREAD

**Issue by emmansun** [microsoft/ApplicationInsights-Java#976]
### Expected behavior
I hope to see blob store http remote dependency with agent

### Actual behavior
I can't find any http remote dependency, but i can see method dependency and exception.

#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: 2.3.1
 - OS type and version: Linux
 - Application Server type and version (if applicable):
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable):
spring boot 2.0.5
azure-storage-spring-boot-starter 2.0.5
azure-storage 5.5.0

### Logs
AI: WARN 12-07-2019 05:43:20.157+0000, 1(main): Instrumentation debug mode set to 'true'
AI: ERROR 12-07-2019 05:43:20.175+0000, 1(main): cannot parse the correlation format, will defaultto AI proprietory correlation
AI: ERROR 12-07-2019 05:43:20.176+0000, 1(main): cannot parse the correlation format, will defaultto AI proprietory correlation
AI: TRACE 12-07-2019 05:43:20.178+0000, 1(main): Outbound W3C tracing is enabled : false
AI: TRACE 12-07-2019 05:43:20.178+0000, 1(main): Outbound W3C backport mode is enabled : true
AI: TRACE 12-07-2019 05:43:20.179+0000, 1(main): Adding built-in instrumentation
AI: TRACE 12-07-2019 05:43:20.179+0000, 1(main): Adding built-in JDBC Statements instrumentation
AI: TRACE 12-07-2019 05:43:20.180+0000, 1(main): Adding built-in JDBC Prepared Statements instrumentation
AI: TRACE 12-07-2019 05:43:20.182+0000, 1(main): Adding built-in HTTP instrumentation
AI: TRACE 12-07-2019 05:43:20.183+0000, 1(main): Adding built-in Jedis instrumentation
AI: TRACE 12-07-2019 05:43:20.183+0000, 1(main): Adding 'org/mule/module/client/MuleClient'
AI: TRACE 12-07-2019 05:43:20.183+0000, 1(main): Adding 'com/xxxx/xxx/service/DocumentServiceImpl'
AI: INFO 12-07-2019 05:43:20.315+0000, 1(main): Successfully registered Jmx connector.
AI: TRACE 12-07-2019 05:43:20.315+0000, 1(main): Agent is up

### Screenshots
![image](https://user-images.githubusercontent.com/7235232/61106971-44af0c00-a4b1-11e9-8697-1a7beb3278a4.png)
![image](https://user-images.githubusercontent.com/7235232/61107046-7627d780-a4b1-11e9-8e9a-796f5ae0fe87.png)

**Comment by emmansun** [comment]
Support java.net.HttpURLConnection from 2.5.0-BETA?

**Comment by emmansun** [comment]
Use `StorageEvent<SendingRequestEvent>` and `StorageEvent<RequestCompletedEvent>` to write AZURE BLOB Storage telemetry manually first.

**Comment by trask** [comment]
Hi @emmansun, what library are you using to send data to Azure Blob Storage? Thanks.

**Comment by emmansun** [comment]
Hi @trask , we used `https://github.com/Azure/azure-storage-java/tree/v5.5.0/microsoft-azure-storage/src/com/microsoft/azure/storage/blob`, it used `java.net.HttpURLConnection`.

**Comment by trask** [comment]
This should be resolved in [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent)
