### ISSUE TITLE
Configurations for pax logging

### ISSUE THREAD

**Issue by ambergoel** [microsoft/ApplicationInsights-Java#991]
### Expected behavior
Currently I am using Jboss Fuse ESB product , which is internally using pax framework for logging application logs. I want to use Azure application insight to view my esb logs.

### Actual behavior
When I configure pax logging as per given instructions , I got below error
```
2019-07-23 11:49:21,640 CM Configuration Updater (Update: pid=org.ops4j.pax.logging) ERROR Appenders contains an invalid element or attribute "ApplicationInsightsAppender" 
2019-07-23 11:49:21,642 CM Configuration Updater (Update: pid=org.ops4j.pax.logging) ERROR Unable to locate appender "aiAppender" for logger config "root"
```

### To Reproduce
I am using default pax loging configuration and supplying log4j2.xml file with below details -
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="INFO" packages="com.microsoft.applicationinsights.log4j.v2">
      <Appenders>
        <ApplicationInsightsAppender name="aiAppender" instrumentationKey="XXXXXXX" />
      </Appenders>
      <Loggers>
        <Root level="INFO">
          <AppenderRef ref="aiAppender"/>
        </Root>
      </Loggers>
</Configuration>
```

#### Sample Application
Any jboss fuse esb can be consider for this.
1. Download jboss fuse esb
2. extract fuse esb from downloaded zip file
3. go to etc folder and open org.ops4j.pax.logging.cfg for configure your appender

### System information
Please provide the following information:
 - OS type and version: windows
 - Application Server type and version (if applicable): Jboss fuse 7.2
 - Using spring-boot? No

**Comment by ambergoel** [comment]
Now I am trying with pax logging configuration and stuck up with appender type option , can any one suggest the appender type here -

log4j2.appender.aiAppender.name = aiAppender
log4j2.appender.aiAppender.packages = com.microsoft.applicationinsights.log4j.v2
#log4j2.appender.aiAppender.type = org.apache.logging.log4j
log4j2.appender.aiAppender.ApplicationInsightsAppender.name = aiAppender
log4j2.appender.aiAppender.ApplicationInsightsAppender.instrumentationKey = mykey

**Comment by trask** [comment]
Hi @ambergoel, it looks like Fuse is not finding the ApplicationInsightsAppender class. Check out Redhat's article [How Do I Add a Custom Log4J Appender to Fuse Karaf or Fabric?](https://access.redhat.com/solutions/2479471).

Alternatively, you could try ApplicationInsights Java Agent 2.5.0-BETA.2, which captures logging automatically (without needing to register an appender), see https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-agent-25-beta, and let us know if you try this and/or have any issues with it.

**Comment by ambergoel** [comment]
hello Trask , yes you are right fuse is not able to find out the ApplicationInsightsAppender class , I tried to execute the steps mentioned in url , but it doesn't work. Getting the same error.

**Comment by trask** [comment]
Hi @ambergoel, can you try using the [ApplicationInsights Java Agent 2.5.0.BETA.3](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/2.5.0-BETA.3) to capture the logging? See https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-agent-25-beta
