### ISSUE TITLE
How to Use Application Insights with Spring Boot

### ISSUE THREAD

**Issue by crows9p** [microsoft/ApplicationInsights-Java#998]
**Use Framework**
- Spring Boot 2.1.6.RELEASE

**Use Agent**
- applicationinsights-agent-2.5.0-BETA.2.jar

**Add Depedency(pom.xml)**
```xml
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>applicationinsights-spring-boot-starter</artifactId>
    <version>2.5.0-BETA.2</version>
</dependency>
```

**Add Properties(application.yml)**
```yaml
azure.application-insights: 
  instrumentation-key: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

**Create Java Configuration**
```java
@Configuration
public class RestTemplateConfiguration {

    @Bean
    public ClientHttpRequestFactory httpRequestFactory() {
        return new HttpComponentsClientHttpRequestFactory();
    }

    @Bean
    public RestTemplate restTemplate() {
        return new RestTemplate(httpRequestFactory());
    }
}

```

**Create AI-Agent.xml**
```xml
<?xml version="1.0" encoding="utf-8"?>
<ApplicationInsightsAgent>
    <Instrumentation>
        <BuiltIn enabled="true">
            <HTTP enabled="true" W3C="true" enableW3CBackCompat="true"/>
        </BuiltIn>
    </Instrumentation>
</ApplicationInsightsAgent>
```

`AI-Agent.xml` file is setting in the same path as `applicationinsights-agent-2.5.0-BETA.2.jar` file  

Made these settings for two applications

**Execute Command**

```
java -javaagent:C:/worker/applicationinsights-agent-2.5.0-BETA.2.jar -jar ./target/app1.jar
```

```
java -javaagent:C:/worker/applicationinsights-agent-2.5.0-BETA.2.jar -jar ./target/app2.jar
```

As a result, it was possible to monitor as expected.   
Is there any problem with the way?  

![map](https://user-images.githubusercontent.com/39488718/62040843-54f71300-b235-11e9-888d-43ea4b48561d.png)

I have some questions.

**Questions**
- Is an `AI-Agent.xml` file required to use the Agent ? (`applicationinsights-agent-2.5.0-BETA.2.jar`)
- Is an Agent Required to Monitor W3C Traces ?
- Can control be done with `application.yml` file instead of `AI-Agent.xml` file ?
- Where is the reference for `AI-Agent.xml` file ?

**Comment by trask** [comment]
Hi @crows9p,

* Yes, `AI-Agent.xml` is required
* Agent is required for monitoring outgoing HTTP calls (e.g. calls made via `RestTemplate`)
* No
* https://github.com/microsoft/ApplicationInsights-Java/wiki/AI-Agent.xml

Thanks,
Trask

**Comment by crows9p** [comment]
Thank you!
