### ISSUE TITLE
Enable package scan for instrumentation (not have to list class with methods which should be instrumented)

### ISSUE THREAD

**Issue by abialas** [microsoft/ApplicationInsights-Java#999]
**Is your feature request related to a problem? Please describe.**
I want to analyze the performance problem of the application. However, I do not know where exactly the problem is located so I do not know which classes / methods I have to list inside <Instrumentation></Instrumentation>. 

**Describe the solution you would like**
To list all classes and methods it is very time-consuming. Maybe there can be a package definition inside <Instrumentation></Instrumentation> which can define that I want to instrument all classes and methods from this package.

**Comment by trask** [comment]
Hi @abialas, I think a profiler would be better suited to this task. An integrated profiler is on our road map, but in the meantime, you could use Java Flight Recorder to profile your app. Check out https://docs.microsoft.com/en-us/azure/app-service/containers/configure-language-java#flight-recorder, and feel free to post back here with any questions. Thanks.
